### ISSUE TITLE
大きな範囲を選択してテキスト・メニューをクリックすると、レインボーカーソルとなり処理が滞る

### ISSUE THREAD

**Issue by wanik** [coteditor/CotEditor#1002]
## Environment

- CotEditor: 3.8.4 (381)
- System: macOS Version 10.13.6 (Build 17G9016)
- Language: English

## Short Description

文字種に依存するようですが、大きな範囲を選択してテキスト・メニューをクリックすると、レインボーカーソルとなり処理が滞ります。

## Steps to Reproduce the Issue

**1. 症状**

合成可能なディアクリティカルマークやギリシア文字を含む大きなテキストファイル（3000行、約19万字）を全範囲選択して、テキスト・メニューをクリックすると、レインボーカーソルとなり、処理が滞ります。

アクティビティーモニタ上では、CotEditor が Not Responding となります。

テキスト・メニュー以外のメニュー項目では、症状は発生しません。

全範囲選択でなくても、選択範囲が 5〜6万字程度を超えると、レインボーカーソルになります。Mac 本体の処理能力によるかも知れませんが。

**2. 比較**

比較のため、アスキー文字からなる同規模のテキストファイルで同様にやってみると、問題ありません。

同じ内容をコピペして、10倍程度（3万行、約190万字）まで増やしても、問題ありませんでした。このため、文字種の影響が考えられます。

**3. スクリーンの動画とテスト用ファイル**

スクリーンの記録を添付いたします。
（QuickTime Player ではレインボーカーソルが録画できなかったため、スクリーンを携帯でビデオ撮りしました。画質が悪いですが、ご容赦下さい。）

[raibowcursor.mp4.zip](https://github.com/coteditor/CotEditor/files/3836542/raibowcursor.mp4.zip)

テストしたテキストファイル 2種も添付いたします。
（中身は、テスト用のランダムな文字列となっています。）

[rainbowcursor_text.zip](https://github.com/coteditor/CotEditor/files/3836544/rainbowcursor_text.zip)

## Expected Result

大きな範囲を選択した場合に、文字種に関わらず、テキスト・メニューで滞りが生じないのが望ましいです。

**Comment by 1024jp** [comment]
duplicated #996.
重複のためクローズしますがレポートありがたいです。

発生箇所はおおよそ絞れているのですが、まだ解決法を発見するに至っておらず修正が遅れています。申しわけないです。
見立てが正しければ、「折り返した行のインデント」をオフにするとこの処理が走らずレインボーカーソルまでいかないはずです。

**Comment by 1024jp** [comment]
文脈を読み間違えました。再開します。

**Comment by wanik** [comment]
お手数ですが、よろしくお願いいたします。

補足です。
平仮名のみだと、5万行、100万字を超えても問題ありませんでした。

ギリシア文字のみ（ディアクリティカルマークなし）だと、例えば、2000行、5万字を超えるくらいで、処理が遅くなるようです。（この程度だと、レインボーカーソルの時間も短いですが、サイズが大きくなると、Not Responding 状態になります。）

**Comment by 1024jp** [comment]
計算方法を改良し、選択範囲が大きくても影響が出ないようにしました。次のCotEditor 3.8.5で導入されます。1週間以内くらいにリリースする予定です。

**Comment by wanik** [comment]
さっそくのご対応、どうもありがとうございます。
3.8.5 お待ちしております。

**Comment by wanik** [comment]
3.8.5 にアップデートしまして、症状なくなりました。
快適です。どうもありがとうございます。
