### ISSUE TITLE
Serif font in "Basic Regular Expression Syntax"

### ISSUE THREAD

**Issue by nuno-agostinho** [coteditor/CotEditor#1005]
The serif font used in the title of the **Basic Regular Expression Syntax** seems out of place. Moreover, when dragging the window, the Close button overlaps with the title.

- CotEditor: 3.8.5 (384)
- System: macOS Version 10.14.6 (Build 18G87)
- Language: English

![Screenshot 2019-11-15 at 15 26 43](https://user-images.githubusercontent.com/3199157/68954679-694b2580-07bc-11ea-8d70-e9bf68243517.png)

**Comment by 1024jp** [comment]
Adjusted. Thank you.

<img width="582" alt="Screen Shot 2019-11-19 at 13 36 07" src="https://user-images.githubusercontent.com/1165044/69116974-9277f880-0ad1-11ea-85bd-7aa6510445aa.png">
