### ISSUE TITLE
Keyboard shortcut [CMD+ PLUS] for bigger text not working correctly.

### ISSUE THREAD

**Issue by kool-kat** [coteditor/CotEditor#1008]
## Environment

- CotEditor: 3.8.5 (384)
- System: macOS Version 10.13.6 (Build 17G9016)
- Language: English

## Short Description

Keyboard shortcut [CMD+ PLUS] for bigger text not working correctly.
Second use of shortcut reverts text to previous size, third and subsequent use of shortcut does no text change

## Steps to Reproduce the Issue

Type any text. 
Select the text typed. 

Press Command Plus, Repeat shortcut

If you select the menu item [bigger] multiple times it will enlarge. It is just the shortcut that isn't Note: working. The shortcut is working for smaller though.

## Expected Result

Text should progressively enlarge at each press of shortcut. As it does with opposite shortcut - Command Minus.

**Comment by 1024jp** [comment]
You maybe invoke not <kbd>Command</kbd>+<kbd>+</kbd> but <kbd>Command</kbd>+<kbd>=</kbd>.
That behavior is the "Reset to Default" command in Format > Font menu.

For instance, with a normal US keyboard by Apple, you actually need to type <kbd>Command</kbd>+<kbd>Shift</kbd>+<kbd>=</kbd> to input <kbd>Command</kbd>+<kbd>+</kbd>.

Which keyboard do you use?
When you are sure you get the "Reset to Default" behavior with <kbd>Command</kbd>+<kbd>+</kbd>, let me know your keyboard layout.
In addition, if you use some keyboard remapper, please let me know the name and version.

**Comment by kool-kat** [comment]
@1024jp you have nailed it. How tricky... I feel stupid.. 

So used to instinctively doing [command]+ [plus/equals] and it working as it does on so many applications. I have never had to hold down shift.

You are correct. cancel report.

**Comment by 1024jp** [comment]
@kool-kat Glad to hear that.

As you pointed out, it seems many other text editors (or other apps) accept <kbd>Commnad</kbd>+<kbd>=</kbd> also to make text bigger. So, maybe, it's worth considering changing the default keymapping for "Zoom" and "Reset to Default" for consistency among other apps. I'll consider. Thank you.

**Comment by 1024jp** [comment]
Ok, changed in the next version.

<img width="400" alt="Screen Shot 2019-11-21 at 18 11 31" src="https://user-images.githubusercontent.com/1165044/69323591-5e940300-0c8a-11ea-99c3-ac455fe46cc2.png">

**Comment by kool-kat** [comment]
Awesome, that is more intuitive and in-line with defacto standards. Love it.
