### ISSUE TITLE
全角スペースの表示が半角スペース分になってしまっている

### ISSUE THREAD

**Issue by kimipooh** [coteditor/CotEditor#1010]
## Environment (環境)

- CotEditor: 3.8.5 (384)
- System: macOS バージョン10.15.1（ビルド19B88）
- Language: Japanese

## Short Description (簡単な説明)

全角スペースの表示がおかしい

## Steps to Reproduce the Issue (不具合が発生したときに行っていた操作、または再現手順)

全角スペースが半角分しかスペースが空いておらず、非常に見にくくなっている。

## Expected Result (期待される挙動)

全角空白は、全角空白（半角スペースの２倍）の間隔を開けてほしい

**Comment by 1024jp** [comment]
使用しているフォントと教えてください。また、その状態のスクリーンショットをいただけませんか？

**Comment by 1024jp** [comment]
再現できないので、このまま返信がない場合1週間ほどでこのissueは一旦クローズします。
