### ISSUE TITLE
Overscroll and Opacity values in Window section should add the percent sign automatically

### ISSUE THREAD

**Issue by willbprog127** [coteditor/CotEditor#1011]
**What happens now**
When editing Preferences in the Window section on CotEditor Version 3.8.5 (384), when you enter a new number for _Overscroll_ or _Opacity_ and don't enter a percent (%) sign at the end, you receive an error saying the value is not valid.  

**What should happen**
CotEditor should just accept the new value entered and add the percent sign automatically if the percent sign was not been entered by the user.  A further improvement would be to eliminate the percent sign completely within the text box and instead use a label to display the percent sign.

**Comment by 1024jp** [comment]
Thank you for pointing it out.
That’s a reasonable request.
I’ll improve it in the next version.

**Comment by willbprog127** [comment]
Thank you 👍

**Comment by willbprog127** [comment]
Received the update today and it's working great! 😄 Good work! 👏
