### ISSUE TITLE
Automatic association and auto-completion

### ISSUE THREAD

**Issue by lchecho** [coteditor/CotEditor#1012]
Currently, I must press option+esc(macos) to get the association.I wonder if you can add this feature, thx! 

- CotEditor: 3.8.5 
- System: macOS Version 10.14.5
- Language: English

**Comment by 1024jp** [comment]
In CotEditor Preferences > Edit > Completion, there is a checkbox to enable auto-completion suggestion.
This may be what you wish.

<img width="672" alt="Screen Shot 2019-12-18 at 18 17 27" src="https://user-images.githubusercontent.com/1165044/71072936-ca528880-21c2-11ea-8a9d-2bef1b21959f.png">
