### ISSUE TITLE
[request] add more customzation options to the console

### ISSUE THREAD

**Issue by Antisunny** [coteditor/CotEditor#1013]
I'm using MacOS Catalina 10.15.1, CotEditor v3.8.5 (MAS).

It should be admitted that the `write to console` command is a great feature in v3.8.5, but it's so limited as to ...

## found

- The "timestamp and running script name" line
- The prefixed spaces each line following the "timestamp and running script name" line

is unnecessary and annoying.

problems:

- the line height: the space between lines too close.
- font ligated, text in the timestamp part is ligated or not monospaced as declared.
- font family, maybe monospaced as declared, but not same as the editor font I set in the preferences.
- cannot the prompted small console window to the most front

## expected

it would be better if cot

1. supports tabs in console window, such as `create new console window`, `create new console tab` commands
2. supports `clear console` command
3. adds options to turn off the "timestamp and running script name" line and the prefixed spaces
4. supports _text settings_, like font family, font size, line height, letter spacing, .... (better IF there will be "Console" tab in the Preferences )
5. supports being _attached_ to the main window, to the right, to the bottom
6. supports

**Comment by mer60** [comment]
for me the following points would be nice:
- an applescript command to clear the console before writing to it
- an option (command or setup feature) to disable timestamp and script name

**Comment by 1024jp** [comment]
@Antisunny, @mer60 
To the next release, CotEditor 5.0.7, I've added the options to adjust visibility of the script name and timestamp when writing a message to console.
Now, you can write like below:

```applescript
write to console "foo bar" without title and timestamp
```

Answering the rest of requests:

> 1. supports tabs in console window, such as `create new console window`, `create new console tab` commands

> 5. supports being attached to the main window, to the right, to the bottom

No. This is against the design concept of the console in CotEditor. 


> 2. supports clear console command

I'm now planning to add in a future version.

> 4. supports text settings, like font family, font size, line height, letter spacing, .... (better IF there will be "Console" tab in the Preferences )

You can already adjust the console’s font size by pressing the `⌘+` and `⌘-` shortcuts while keeping your focus on the console.
Regarding other setting options, CotEditor has a policy to minimize the setting options as much as possible.
I feel those settings are too much.

**Comment by 1024jp** [comment]
> supports clear console command
>> I'm now planning to add in a future version.

I’ve thoroughly considered the design of this implementation, and despite the initial plan, I’ve decided that it’s not appropriate to add this API at this time.
I believe clearing the entire log from a script is too much.
Furthermore, the user already has the option to clear the log from the clear button located in the console window.

**Comment by mer60** [comment]
what a pity ... I'm looking forward to new features coming ...

sincerely Michael
