### ISSUE TITLE
[request] allow keybinding to the scripts

### ISSUE THREAD

**Issue by Antisunny** [coteditor/CotEditor#1014]
> I'm using MacOS Catalina 10.15.1  and CotEditor 3.8.5

It's really not efficient to run script by clicking "Scripts -> ScriptYouWannaRun" or rightclicking "Scripts -> ScriptYouWannaRun". If I need running a script high-frequently, it really annoys me since keybinding is not allowed to scripts.

Is there a way to bing keystokes in the Preferences to self defined scripts?

**Comment by mer60** [comment]
@Antisunny: maybe you want to take a look at CotEditor Help;-))
At "File naming rules for CotEditor scripts" there's a description how to add keybindings to your scripts as well as an item for customizing your Script Menu.

Best regards

**Comment by 1024jp** [comment]
I close this issue since @mer60 explained (thank you!) exactly how to add shortcuts to scripts.
