### ISSUE TITLE
Delay in Selecting a Line of Text

### ISSUE THREAD

**Issue by t-bullock** [coteditor/CotEditor#1015]
With a large file (3,000+ lines), selecting a line to the right with shift+cmd+→ quickly highlights the line, but selecting a line to the left with shift+cmd+← has a delay.  The larger the file, the longer the delay in highlighting the line.

If I select a word with opt+shift+←, there is no delay.

**Comment by 1024jp** [comment]
note: `EditorTextView.moveToBeginningOfLineAndModifySelection(_:)`

**Comment by t-bullock** [comment]
This bug seems to be fixed (or mitigated) in version 3.8.10.

**Comment by 1024jp** [comment]
Oh, that's glad to hear.
I worked on performance optimization a lot in the last few versions, and one of the measures would work also for this issue.
Thank you for your follow-up reply.
