### ISSUE TITLE
「検索を折り返す」がONのときにウインドウが点滅することがある

### ISSUE THREAD

**Issue by doraTeX** [coteditor/CotEditor#1016]
## Environment (環境)

- CotEditor: 3.8.7 (389)
- System: macOS バージョン10.15.3（ビルド19D49f）
- Language: Japanese

## Short Description (簡単な説明)

検索パネルで「検索を折り返す」がONのとき，折り返す瞬間にウインドウが点滅することがあります（点滅しないこともあります）。

### 設定画面
![image](https://user-images.githubusercontent.com/6186180/71390381-7ec93000-2643-11ea-8c6f-3f11ac3ed2fb.png)

### 再現の様子

[画面収録した動画です](https://www.dropbox.com/s/hu6y26n2xhign29/coteditorflashbug.mov?dl=0)。

## Expected Result (期待される挙動)

毎回点滅せずに折り返す。

**Comment by 1024jp** [comment]
おぉ、同じmacOS 10.15.3で再現しました。
これは...、macOS側のバグじゃないからしら...。
なんだろう、調べてみます。

**Comment by 1024jp** [comment]
> これは...、macOS側のバグじゃないからしら...。

macOS側じゃなくてこちらの手違いでした orz。
無事修正したので次バージョンで直ります。
報告ほんとうにありがとうございました。
