### ISSUE TITLE
CodEditor on mac crashes when editing some text

### ISSUE THREAD

**Issue by indux** [coteditor/CotEditor#1019]
## Environment

- CotEditor: 3.8.0 (373)
- System: macOS Version 10.14.6 (Build 18G2022)
- Language: English

**1. put the following text in a new tab**

======================start(excluded)==========================
Monitor
 ---take advantage of auto alert and notification feature provided by kibana for FM @wenbin
 ---need to design EDRS phase 2 monitor strategy, more kibana view maybe needed @wenbin
 ---create kibana view for SCA@yeyong
 
 
Meeting
 ---every meeting should have action items with DoD, ETA, 
 ---meeting organizer should follow up the items until they are done
 

Code review
 ---purpose: product quality + code quality
 ---at least 2 assignees, 1 of which is key reviewer
 ---take advantage of best practice
 _**---ecd p1/p2 (dmp))) should not increase**_

Test Quality
 ---ut, acceptance test effitiveness
 ---acceptance test modatory for new feature

Communication
 ---team internal
 ---cross team expectation

Common tool crossing team

======================end(excluded)==========================

**2. try to edit this line in the text**
 ---ecd p1/p2 (dmp))) should not increase

**3. try to remove the characters one by one in this order (use Del on your keyboard):**
d m p ) )

**4. CotEditor does not respond now**

**Comment by 1024jp** [comment]
The current latest version of CotEditor is 3.8.7.
Please try it and tell me whether it still exists, since I believe it has been already fixed.

**Comment by indux** [comment]
After upgrading to v3.8.7, the issue disappeared. Thanks!
