### ISSUE TITLE
Memory leak when reinterpreting open file

### ISSUE THREAD

**Issue by wtn** [coteditor/CotEditor#1020]
I opened [this small file](https://github.com/simonrepp/titlekit/blob/v1.2.3/spec/files/ass/authentic.ass) (45453B) in CotEditor version 3.8.7 (389). It loaded as UTF-8.

I used the File Encoding pop-up button to reinterpret as UTF-16. The app's memory usage increased to many GB.

<img width="539" alt="leak" src="https://user-images.githubusercontent.com/35801/72686193-a501b480-3ab7-11ea-865d-e6023023b08e.png">

I can only replicate this problem with the specific file I mentioned above. I'm not sure why, probably I missed something.

**Comment by 1024jp** [comment]
Thank you for the feedback.

The file you refer to is saved not as UTF-16 but UTF-8. Therefore, forcibly reinterpreting and rendering it, which actually causes text garbling, is hard work for the app.

Well, anyway, I believe this issue is now already solved in the latest CotEditor 3.8.10.

**Comment by wtn** [comment]
ありがとうございます。
