### ISSUE TITLE
「未保存の編集行」の強調表示 / Emphasize unsaved lines

### ISSUE THREAD

**Issue by stein2nd** [coteditor/CotEditor#1027]
Windows向け「Mery」「EmEditor」に搭載されてる、「未保存の編集行」を強調する仕組みをCotEditorに搭載することはできませんか？

「Mery」変更行の強調表示
https://www.haijin-boys.com/software/mery/mery-2-6-9#4

窓の杜「変更行をスクロールバー上に表示する機能を追加した「EmEditor」v14.3.0の正式版」
https://forest.watch.impress.co.jp/docs/news/635724.html

**Comment by 1024jp** [comment]
CotEditorは基本的にオートセーブを推奨しているため、「未保存の編集行」は存在しない立場をとっています。
（これは近年のmacOSでの書類編集アプリケーションでの推奨される振る舞いを踏襲しています）
このオートセーブは環境設定で無効にもできるためそのときは有用ではあるのですが、実装および差分算出の処理コストと見合わないと考えるため、申し訳ないですが要望は棄却させてください。

またgitなどのバージョン管理ツールとの統合は、今後の実装予定機能の優先順位の関係で目下対応予定はありません。
