### ISSUE TITLE
3.8.8 crash after launch

### ISSUE THREAD

**Issue by superhonya** [coteditor/CotEditor#1028]
いつも便利に使わせていただいてます。

3.8.7から3.8.8にアップデートしたところ、アプリ起動直後に毎回クラッシュするようになってしまいました。
具体的には、前回終了時開いていた書類が自動的に復帰した直後のタイミングです。
未保存の書類が大量にあるので、復帰機能を使わないとどうなるかは試していません。

3.8.7に戻したところ症状は出なくなりました。

クラッシュログを添付します。10.13の環境です。
[CotEditor_2020-01-30-101921_macbookpeko.crash.txt](https://github.com/coteditor/CotEditor/files/4131703/CotEditor_2020-01-30-101921_macbookpeko.crash.txt)

**Comment by 1024jp** [comment]
duplicated: #1026

申し訳ない、本件既に修正版をMac App Storeに提出済みで現在Store側のレビュー待ちです。
今日中には通ると思っているのですが、リリースまでしばしお待ちください。

**Comment by 1024jp** [comment]
CotEditor 3.8.9リリースしました。
