### ISSUE TITLE
インスペクタのunicodeがnot selectedになる / Unicode information in inspector displays always "not selected"

### ISSUE THREAD

**Issue by emikoharayama** [coteditor/CotEditor#1029]
ドキュメントのインスペクタ→文字→Unicodeで選択した文字のunicode番号を調べようとしても、Not selectedになってしまいます。以前は正しく表示されていました。

**Comment by 1024jp** [comment]
本当だ...、ありがとうございます。申し訳ない。
次バージョンは別件のバグ修正で既にストアに提出中なのでその次バージョンで修正します。

**Comment by emikoharayama** [comment]
ありがとうございます！
わたしにとってCotEditorの魅力のひとつは文字コードに強いところなので、
これからもどうぞよろしくお願いします！
