### ISSUE TITLE
A built-in terminal emulator?

### ISSUE THREAD

**Issue by p-z-l** [coteditor/CotEditor#1031]
A built-in terminal emulator could be very useful for me - I sometimes use CotEditor to write some code snippets. In this case a built-in terminal emulator could allow me to run my script directly inside the editor, instead of switching to another App and switch it back.

> Also: thanks for making this app, CotEditor is an awesome replacement for TextEdit.app

**Comment by 1024jp** [comment]
Hmm, currently, I don't have any plan to implement such a build-in terminal, not because it's against the CotEditor's philosophy but only because of the cost of the implementation and the priority of my todo list.

related: #796
