### ISSUE TITLE
UI language is wrong

### ISSUE THREAD

**Issue by said50** [coteditor/CotEditor#1032]
Hi,
just installed this on my new MBP 16", which has dutch as the default language. 
The problem is that CotEditor is in French, which I can't understand. Is there a way to change it to English or dutch?

Thanks

**Comment by 1024jp** [comment]
CotEditor refers to the user preference in the System Preferences > Language & Region.

<img width="780" alt="Screen Shot 2020-02-17 at 12 17 12" src="https://user-images.githubusercontent.com/1165044/74621212-6ecf5780-517f-11ea-9bca-48b7e0181c39.png">

So, if you prioritize English higher than French, by dragging the item in the "Preferred Languages"  box, English will be used from the next launch of the app.

**Comment by said50** [comment]
Thanks, it worked. You got a tutorial on how to make it work like notepad++ ?

**Comment by 1024jp** [comment]
Good.

> You got a tutorial on how to make it work like notepad++ ?

You can find the documentation for users about the general usage of CotEditor in the Help menu.

<img width="510" alt="Screen Shot 2020-02-18 at 15 48 29" src="https://user-images.githubusercontent.com/1165044/74710937-1fb02200-5266-11ea-89cf-af90c7f13f5e.png">
