### ISSUE TITLE
Can not select result when search very long text

### ISSUE THREAD

**Issue by qokelate** [coteditor/CotEditor#1039]
sarch a very long string in big text file(like log), search box can not select result(not focus to result).

![](https://i.ibb.co/TkNwbNc/111.png)

**Comment by 1024jp** [comment]
Thank you for the feedback.
I've just changed to truncate the rest when the find string is too long. Instead, users can see the entire find string via tooltip if they want.

<img width="569" alt="Screen Shot 2020-03-03 at 14 19 17" src="https://user-images.githubusercontent.com/1165044/75745218-fa3d1100-5d59-11ea-9588-c2374ccdc192.png">
