### ISSUE TITLE
how to format or reindent code?

### ISSUE THREAD

**Issue by crotel** [coteditor/CotEditor#1042]
## Environment

- CotEditor: 3.8.12 (400)
- System: macOS Version 10.15 (Build 19A602)
- Language: English

## Short Description

like sublime reindent or bbedit format function.
how to do this in coteditor?
I mean while write javascript.
I saw that you release a `PHP syntax formatting/beautify`, how about javascript same function?

**Comment by 1024jp** [comment]
There is currently no built-in way to reindent code in CotEditor.
Instead, you can create your own script.

See _CotEditor Scripting Guide_ in the Help menu to know how to write a CotEditor script.
In addition, [PHP syntax formatting/beautify](https://github.com/uschmelzer/coteditor-scripting-test/blob/master/Scripts/Format-PHP/php-cs-fixer.php) is not released by us but by a user.
However, this script might help you to make a variation.
