### ISSUE TITLE
JXA sets wrong string to newly opend document / CotEditorスクリプト（JXA） TextSelection.contents取得後のDocument.open()について

### ISSUE THREAD

**Issue by tsuki-fukurou** [coteditor/CotEditor#1044]
CotEditorスクリプトにて、選択範囲のデータを取得した後にファイルを開くスクリプトを実行したところ、以下のような現象が発生します。
1. すでに開いているwindowのテキストを範囲選択する（caretを置くだけでも良い）。
2. スクリプトを実行する。
3. 新規windowが開く前に、現在windowの選択範囲（caret位置）に開くファイルのテキストがペーストされる。
4. 新規windowが開く。読み込まれるテキストは正常の内容であり、[3]と同じ内容。

発生頻度としては、50回実施して2〜3回程度です。
作成したスクリプトのコードを間違えているのかもしれないと思い、問題の発生する条件を調査したのですが、以下のようなスクリプトを実行しても同様の現象が発生することを確認しました。

var App = Application("CotEditor") ;
App.activate() ;
delay(0.1) ;
var textSelected = App.documents[0].selection.contents() ;
App.open(Path("/Users/xxxxx/filename")) ;

contentsを読み出した後にcaretの位置を変えたり、再度設定してみたりしたのですが、改善することはできませんでした。

**Comment by 1024jp** [comment]
現象再現しました。
明らかにバグなので修正を試みます。
ご報告ありがとうございます。

**Comment by 1024jp** [comment]
修正しました。同じく CotEditor 3.9.0 で反映予定です。
