### ISSUE TITLE
CotEditorスクリプト（JXA） Document string実行時の異常終了

### ISSUE THREAD

**Issue by tsuki-fukurou** [coteditor/CotEditor#1045]
CotEditorスクリプト（JXA）にて、Document string methodを実行するとCotEditorが異常終了します。
実行したスクリプトの内容としては以下の通りです。

Application("CotEditor").documents[0].string({in:[1,1]}) ;

JXAは慣れていないのですが、パラメータの設定に問題がありますでしょうか？

**Comment by 1024jp** [comment]
クラッシュしてしまうのはまずい気がするので後々調査しますが、
JXAでCotEditorの最前面書類の内容をとるときは `.string` でなくて `.text` または `.conents`でアクセスしてください。
私も

```javascript
var str = Application("CotEditor").documents[0].contents();
```

**Comment by tsuki-fukurou** [comment]
ご確認ありがとうございました。
承知しました。
通常、公開していただいているサンプルに従い`.contents`を使用して内容を取得しているのですが、続いてファイルを開くと選択領域に意図せずペーストされてしまう現象があり、いろいろ試した中で気づいたのでご報告した次第です。
機能としては`.contents`と重なるので`.string`はなくても事足りそうな気がします。

**Comment by 1024jp** [comment]
現行のワークアラウンドとして代替を提案させてもらいましたが、`.string`で落ちるのはおかしいので、
修正案件としたいのでreopenします。

**Comment by 1024jp** [comment]
本件、CotEditor側のバグでした。
次のCotEditor 3.9.0（4 or 5月リリース）で修正を取り込む予定です。
ご報告いただきありがとうございます。
