### ISSUE TITLE
Could you put some build here ? (I'm not a fan of app stores)

### ISSUE THREAD

**Issue by freeeflyer** [coteditor/CotEditor#1046]
Hello,

I like OpenSource, but somehow I'm not fan of any app store. 
Is it possible to put some build here on github ?

Thanks

**Comment by 1024jp** [comment]
There are already here.

https://github.com/coteditor/CotEditor/releases

**Comment by freeeflyer** [comment]
Cool thanks for the answer. (and sorry not finding them in the first place)

**Comment by 1024jp** [comment]
No problem.
In addition, you can get the latest from a more fancy webpage: https://coteditor.com/archives
