### ISSUE TITLE
Wrong line wrapping position in vertical text layout / 縦書きで保存したファイルを開くと、折り返し位置が正しく表示されない

### ISSUE THREAD

**Issue by wanik** [coteditor/CotEditor#1051]
## Short Description

縦書きで入力して保存したファイルを開くと、折り返し位置が正しく表示されないようです。

## Steps to Reproduce the Issue

状況の動画を添付いたします。（以下の、2.からスタート）
[verticalwraplines.zip](https://github.com/coteditor/CotEditor/files/4454640/verticalwraplines.zip)

1. 縦書きでテキストを作成し、保存します。（Wrap lines を有効にしてあります。）

2. そのファイルを開くと、ウィンドウの下端でテキストが折り返されずに、テキストの一部が隠れて見えなくなります。

3. その状態で、テキストの入力を続けても（例えば、コピペを繰り返す）、折り返し位置は不適正なままです。

4. Wrap lines / Unwrap lines をすると、正常に戻ります。

（横書きの場合は、異常はありません。）

5. また、行番号が飛び飛びにしか表示されません。

## Expected Result

縦書きで保存されたファイルを開いたときに、自動的にウィンドウの下端でテキストが折り返されるようになると助かります。

また、行番号はすべて表示されたほうがありがたいです。

**Comment by wanik** [comment]
スクリーンショットです。

![verticalwraplines](https://user-images.githubusercontent.com/34469683/78869514-aec80200-7a7f-11ea-8463-90c4d15522e6.jpg)

**Comment by 1024jp** [comment]
なるほど...。報告ありがとうございます。
おそらくこれはApple側のバグに起因していて、去年Appleの技術者にも伝えてるんですけどまだ手が入ってないようなんですよねぇ。
とはいえ 、ひとまずは迂回できないか模索してみます。

> また、行番号が飛び飛びにしか表示されません。

これに関しては、縦書きの時はわざと5行毎にしか番号を表示しないようにしています。
主な理由は、桁数が増えた時に毎行だと表示するスペースがなくなるためです。
ご了承ください。

**Comment by 1024jp** [comment]
ref. #916

**Comment by wanik** [comment]
> とはいえ 、ひとまずは迂回できないか模索してみます。

さっそく、どうもありがとうございます。
Apple側で早く対処してくれると、いいですね。

> これに関しては、縦書きの時はわざと5行毎（と最終行と選択行）にしか番号を表示しないようにしています。
> 主な理由は、桁数が増えた時に毎行だと表示するスペースがなくなるためです。

そのとおりですね。行番号の桁が増えると、困りますね。
了解です。失礼しました。

**Comment by 1024jp** [comment]
本件についてはおそらく修正できたかと思います。
この変更は次のCotEditor 3.9.0 (5月リリース予定) で反映されます。
報告ありがとうございます。

**Comment by wanik** [comment]
Apple matter でご面倒なところ、
早々とご対応下さり、どうもありがとうございます。

**Comment by wanik** [comment]
CotEditor 3.9.0-beta 試してみました。

https://coteditor.com/releasenotes/3.9.0-beta.ja
「縦書き表示で書類を開くと行の折り返し位置がおかしかった不具合を修正」
いただきましたが、
macOS **10.13.6** では、修正が反映されないようです。

古いOSで恐縮ですが、ひとまずご報告いたしておきます。

## Environment
- CotEditor: 3.9.0-beta (411)
- System: macOS Version 10.13.6 (Build 17G12034)
- Language: English

![vertical](https://user-images.githubusercontent.com/34469683/80940657-64863680-8e1b-11ea-9456-c82a217374f8.jpg)

**Comment by 1024jp** [comment]
うぅ、報告ありがとうございます。
調べてみます。解決してないのでひとまずreopenしますね。

**Comment by wanik** [comment]
よろしくお願いいたします。

**Comment by 1024jp** [comment]
overscrollingの値も補正する必要があったようです。今度こそ多分大丈夫かと信じたいです...。
今週末出す予定の3.9.0 beta.3でお試しいただけるかと。

**Comment by wanik** [comment]
ありがとうございます。
beta.3 試してみます。

**Comment by wanik** [comment]
当初問題にしていた事案は、解決していますので、助かりました。
どうもありがとうございます。

**Comment by wanik** [comment]
当初問題にしていた事案は、解決していますので、助かりました。
どうもありがとうございます。

この件の絡みで、ひとつ質問です。
ウィンドウサイズを上下あるいは左右方向に拡大・縮小させた場合の
カレントラインの表示の挙動です。

（動画のファイルです）
[tateWindowSize.zip](https://github.com/coteditor/CotEditor/files/4638553/tateWindowSize.zip)

まず、
**問題ない場合**です。

初めに、ファイルの**中央部分辺りにカーソルを置き**
（例えば 200行あるファイルの 100行目）、
カレントラインがウィンドウ内に表示された状態にします。

1. Writing Orientation が **Horizontal** のとき【動画冒頭〜】
ウィンドウサイズを**上下方向**に変化させると、
カレントラインがウィンドウの中央になるように
配置しなおしてくれます。ありがたいです。

2. Writing Orientation が **Vertical** のとき【動画13秒目〜】
ウィンドウサイズを**左右方向**に変化させると、
同じように動きますので、問題ありません。

次に、ファイルの**1行目にカーソルを置き**、
カレントラインが表示されている状態にします。

3. Writing Orientation が **Horizontal** のとき【動画32秒目〜】
ウィンドウサイズを**上下方向**に変化させると、
カレントラインである 1行目が表示されたままですので、
これは問題ありません。

これに対して、
**問題と考えられる場合**です。

4. Writing Orientation を **Vertical** にしたとき【動画42秒目〜】
ウィンドウサイズを**左右方向**に変化させると、
**カレントラインの1行目が、隠れてしまいます**。

![tateWindowSize](https://user-images.githubusercontent.com/34469683/82122566-7f6b8a00-97cf-11ea-97a5-a8fc88b14869.jpg)

重大な問題ではないのですが、
Vertical の場合の挙動が、Horizontal の場合とは対称的でない
という感じになります。
（念のため、ご報告いたしておきます。）

環境は、以下のとおりです。
- CotEditor: 3.9.0-beta.3 (415)
- System: macOS Version 10.13.6 (Build 17G12034)
- Language: English

**Comment by 1024jp** [comment]
修正の検証ありがとうございます。
懸案の事項については無事動作したようでよかったです。

さて、2件目の件に関してですが、
これに関してはもう100% Appleのフレームワーク側のバグでこちらからはどうしようもできないでいます（↓に書いた事項です）。

> おそらくこれはApple側のバグに起因していて、去年Appleの技術者にも伝えてるんですけどまだ手が入ってないようなんですよねぇ。

向こうの技術者にworkaroundがないかも訊いたのですがなさそうで...。
縦書きの挙動については現状が間違ってると思ってます。
が、macOS 10.16に期待するくらいしかいまのところ取れる策(?)がなさそうです。

**Comment by wanik** [comment]
ありがとうございます。

Appleマターなので、仕方がないですね。
今後の macOS の改善を待ちたいと思います。
