### ISSUE TITLE
関連付けを行う拡張子を選択できると助かります

### ISSUE THREAD

**Issue by mugicha20100** [coteditor/CotEditor#1053]
インストールするといくつかの拡張子がCotEditorに関連付けられますが、
現在、どの拡張子に関連付けられているかを確認でき、
それぞれ任意に選択出来るようになると助かります。
宜しくお願い致します。

**Comment by 1024jp** [comment]
回答遅くなり申し訳ないです。
その部分についてはmacOSのシステム側の課題であり、いちアプリケーションが独自にUIを足すような部分ではないと考えるのでCotEditorとしては不採用とさせてください。
