### ISSUE TITLE
How to disable data detectors

### ISSUE THREAD

**Issue by Tekl** [coteditor/CotEditor#1054]
When I select text I always get an annoying icon for the macOS's data detector feature when hovering the selection. How can I disable this?

![datadetector](https://user-images.githubusercontent.com/3667947/79840345-13575b00-83b6-11ea-8ad4-49666ab32d48.png)

**Comment by 1024jp** [comment]
Because this is a feature by the macOS system, you should customize it at the system level.
Furthermore, I suppose this is disabled by default, though I'm not sure. 
However, regarding to this feature, CotEditor just follows the system setting.
So, there is no GUI control on CotEditor to customize the behavior of the data detectors.

**Comment by Tekl** [comment]
Well, if someone could help me with informations about disabling the global setting it would be great. 

Other Editors like BBEdit, TextMate 2 or Textastic ignore the data detectors and there they don't get into my way.

Well, in TextEdit, Bean and Script Editor I could disable the data detectors individually in previous macOS versions. But now the options in the edit menu (substitutions) have no effect anymore. So Apple seem to have broken something.

**Comment by Tekl** [comment]
Okay, I digged deeper into this. A new user account won't show the data detector in CotEditor. So where does this setting come from? I already deleted the GlobalPreferences where other text stuff is stored. It does not help?

**Comment by Tekl** [comment]
Hello I've found the solution. That drop down button is not caused by data detectors but by Action extensions. I've disabled the actions from "Things", "Fantastical" and "Cardhop" in category "Actions" of the System preference "Extensions".

![actions](https://user-images.githubusercontent.com/3667947/80128477-03966d00-8596-11ea-8935-f284b352857d.png)
