### ISSUE TITLE
画面を上下分割して、下側のエリアで文字を入力すると、文字色が黒になる

### ISSUE THREAD

**Issue by wanik** [coteditor/CotEditor#1055]
## Environment

- CotEditor: 3.8.12 (400)
- System: macOS Version 10.13.6 (Build 17G12034)
- Language: English

## Short Description

画面を上下分割して、下側のエリアで文字を入力すると、文字色が黒になります。

## Steps to Reproduce the Issue

画面を上下に 2分割した状態で、下側のエリアで文字を入力すると、入力された文字の色が黒になります。（上側のエリアでは問題はありません。）

また、文字は日本語でもローマ字・数字などでも、同じ症状になります。

![cotSplitMojiiro](https://user-images.githubusercontent.com/34469683/80816901-58c42580-8c0b-11ea-8087-7c9e85dc282b.jpg)

動画も添付します。
[cotSplitMojiiro.zip](https://github.com/coteditor/CotEditor/files/4564915/cotSplitMojiiro.zip)

画面分割を解除しても、文字色は黒のままです。

テーマが、Anura (Dark)、Dendrobates (Dark)、Solarized (Dark) の場合に起こるようです。

個人的なマシンの問題か、CotEditorやMacの設定の問題か、何とも分かりかねますので、よろしくお願いいたします。

## Expected Result

上記の症状が解消されると助かります。

**Comment by 1024jp** [comment]
手元の環境 (macOS 10.15) だと発生しないので、古いOS限定のMac側の不具合の可能性もありますね...。いずれにせよ後ほど調べてみます。

**Comment by 1024jp** [comment]
macOS 10.13.6で再現しました👍。修正を試みます。

**Comment by wanik** [comment]
macOS 10.15 だと、症状出ないのですね。
古いOSまわりのことで、恐縮です。

Dark系のテーマを使わなければよいということもありますので、
ムリのない範囲で、よろしくお願いいたします。

**Comment by 1024jp** [comment]
お待たせしました。
条件を揃えたらCatalinaでも発生しました。
修正が終了しましたのでこれからリリースする3.9.0-beta.3に取り込みました。

**Comment by wanik** [comment]
ありがとうございます。

検証してみました。
直ったと言えば直ったのですが、ひとつ問題がありました。

まず、画面分割の前にテーマを変更しておくと、問題は生じませんでした。
しかし、**画面分割をした後にテーマを変更すると、文字色の不具合が生じます**。

Dendrobates の場合、
非ダーク系からダーク系への変更でも、ダーク系から非ダーク系への変更でも、
どちらの場合も、**画面分割をした後にテーマを変更すると**、不具合が生じます。
（全部試してはいませんが、Anura でもなりました。）

![bunkatsuColor](https://user-images.githubusercontent.com/34469683/82125233-839fa380-97df-11ea-86e0-803b971ee335.jpg)

（動画です）
[bunkatsuMojiColor.zip](https://github.com/coteditor/CotEditor/files/4638751/bunkatsuMojiColor.zip)

環境
- CotEditor: 3.9.0-beta.3 (415)
- System: macOS Version 10.13.6 (Build 17G12034)
- Language: English

**Comment by 1024jp** [comment]
おぉ、ありがとうございます

**Comment by wanik** [comment]
さっそく、どうもありがとうございます。

**Comment by 1024jp** [comment]
別件のバグ対応でbeta.4をリリースしたので、そちらにこの修正も含まれています。

**Comment by wanik** [comment]
beta.4 で問題が解消されました。
どうもありがとうございます。

**Comment by 1024jp** [comment]
確認ありがとうございます。
いつもわかりやすいレポート助かってます。
