### ISSUE TITLE
カレントラインの表示が、実際のカーソルの位置から 2行分下にズレる

### ISSUE THREAD

**Issue by wanik** [coteditor/CotEditor#1056]
## Environment

- CotEditor: 3.9.0-beta (411)
- System: macOS Version 10.13.6 (Build 17G12034)
- Language: English

## Short Description

カレントラインの表示が、実際のカーソルの位置から 2行分下にズレます。

## Steps to Reproduce the Issue

新規ファイルを作成すると、カーソルは 1行目にありますが、
カレントラインの表示は 3行目にある状態で作成されます。

改行を打って、カーソル位置を移動すると、カレントラインの表示も 2行分ズレたまま移動します。

![kidouji_cursor_gyo](https://user-images.githubusercontent.com/34469683/80941722-22aabf80-8e1e-11ea-9a67-145a378843ec.jpg)

**Comment by wanik** [comment]
カーソル位置とカレントラインの表示とのズレ量は、ウィンドウの大きさによって変化するようです。

動画
[kidouji_cursor_gyo.zip](https://github.com/coteditor/CotEditor/files/4573385/kidouji_cursor_gyo.zip)

**Comment by 1024jp** [comment]
報告ありがとうございます。修正しました。
位置計算にoverscrollingの値が効いていることを失念していました💦。

**Comment by wanik** [comment]
ありがとうございます。
すぐに直って、よかったです。
