### ISSUE TITLE
不可視文字の表示／非表示の切り替えができない

### ISSUE THREAD

**Issue by wanik** [coteditor/CotEditor#1057]
## Environment

- CotEditor: 3.9.0-beta (411)
- System: macOS Version 10.13.6 (Build 17G12034)
- Language: English

## Short Description

不可視文字の表示／非表示の切り替えが、機能していないようです。

## Steps to Reproduce the Issue

Formatメニュー内の Show invisibles / Hide invisibles が、グレーアウトしたままで、不可視文字の表示／非表示の切り替えができません。

また、ツールバーのボタンも同様です。

![show_hide_invisible](https://user-images.githubusercontent.com/34469683/80944874-7cfb4e80-8e25-11ea-859a-bba7504bf5d6.jpg)

よろしくお願いいたします。

**Comment by 1024jp** [comment]
報告ありがとうございます。助かりました。
これは完璧に間が抜けた話で書き換えた時にbool値を逆にしてました...。

**Comment by wanik** [comment]
さっそく、ありがとうございます。
（... 筆のあやまりですね。）
