### ISSUE TITLE
Display character information in the document inspector / Inspect character で表示される文字情報を Document Inspector でも見たい

### ISSUE THREAD

**Issue by wanik** [coteditor/CotEditor#1059]
## Environment

- CotEditor: 3.9.0-beta (411)
- System: macOS Version 10.13.6 (Build 17G12034)
- Language: English

## Short Description

不可視文字の描画機能の拡充 ( #974 )、どうもありがとうございます。
その関連で、機能追加のリクエスト（提案的なもの）をお願いしてみます。

Inspect character で表示される情報と同じものが、
Document Inspector の Character にも表示されると、
便利になりますので、ありがたいです。

## Expected Result

不可視文字に限りませんが、
Inspect character で表示される情報と同じものが
Document Inspector の Character のエリアにも表示されたら、
便利かと思います。

![inspectChar](https://user-images.githubusercontent.com/34469683/81081695-35f88080-8f2d-11ea-9345-972667824fd2.jpg)

Inspect character で表示するには、
対象文字を選択して、Textメニューから選択するかショートカットを使いますが、
Document Inspector で表示されるようになりますと、
対象文字を選択するだけで、同じ情報を得られるようになります。

同じ代替記号で表示される制御文字等の不可視文字の情報を確認したいときに、
選択するだけなので、とても便利になります。

勝手な希望で恐縮ですが、いかがでしょうか。
よろしくお願いいたします。

**Comment by 1024jp** [comment]
これは以前から考えつつ私の怠惰で付けていませんでした。
検討します。

**Comment by wanik** [comment]
お手間をおかけして恐縮ですが、よろしくお願いいたします。

**Comment by 1024jp** [comment]
お時間頂いていましたが、次のバージョン（CotEditor 5.0.7）で対応しました。
文字インスペクタの方を強化してしまったのもあり、書類インスペクタの方には文字インスペクタの情報をそのまま出すのではなく、単独のUnicodeスカラのときのみいくつかの詳しいUnicode情報を出すのにとどめました。
書類インスペクタの文字セクションはあくまで簡易版で複数のスカラから成り立つ文字の場合は引き続き文字インスペクタの方を使っていただけたらと思います。

<img width="690" alt="Screenshot 2024-12-14 at 3 15 39 PM" src="https://github.com/user-attachments/assets/8b46655d-ca14-4a5b-9b07-b35540bb9031" />
<img width="706" alt="Screenshot 2024-12-14 at 3 15 51 PM" src="https://github.com/user-attachments/assets/e60eef67-267f-44c7-9c89-db063cbe2794" />

**Comment by wanik** [comment]
どうもありがとうございます。
ただ今、まだ Ventura を使っておりまして、年末には Sequoia に上げる予定ですので、CotEditor 5 を使えるようになります。
楽しみです。
