### ISSUE TITLE
 ウィンドウの下端近くの行番号が数行分表示されない

### ISSUE THREAD

**Issue by wanik** [coteditor/CotEditor#1060]
## Environment

- CotEditor: 3.9.0-beta (411)
- System: macOS Version 10.13.6 (Build 17G12034)
- Language: English

## Short Description

ウィンドウの下端近くの行番号が、数行分表示されません。

## Steps to Reproduce the Issue

テキストファイルを開いたとき、ウィンドウの下端近くの行番号が、数行分表示されません。

また、スクロールしたり、ウィンドウのサイズを変えたりしてみても、同じような状況のままとなります。

![line_num1](https://user-images.githubusercontent.com/34469683/81187603-3e18f480-8fef-11ea-858a-dfe14194f9a3.jpg)

![line_num2](https://user-images.githubusercontent.com/34469683/81187623-42451200-8fef-11ea-9a3c-4e896c65023a.jpg)

なお、3.8.12 では、問題ありません。

（#1056 と関係あるかも知れませんが、いちおうご報告いたしておきます。）

## Expected Result

ウィンドウの下端まで行番号が表示されるのが、望ましいです。

よろしくお願いいたします。

**Comment by 1024jp** [comment]
こっちもでした。ありがとうございます！
