### ISSUE TITLE
一部の等幅フォントでずれる / glyphs are not aligned vertically with some monospace fonts

### ISSUE THREAD

**Issue by old-fashion-donut** [coteditor/CotEditor#1061]
# Environment

* CotEditor: 3.8.12
* System: macOS Version 10.15.4
* Language: Japanese

# Short Description

一部の等幅フォントで表示が等幅にならない

# Steps to Reproduce the Issue

初めて書くので失礼があれば申し訳ありません

図の様に文字列が等幅になりません

![2020-05-07 15 38のイメージ](https://user-images.githubusercontent.com/57614053/81262958-c17f2800-9079-11ea-9dd8-e8669947e889.jpg)

もしかすると、テキストエディット.appでも同様なのでOSの仕様かもしれません

# Expected Result

期待される挙動としては、縦の棒線が一直線に表示されることです

同じフォントでターミナル上のvimでは期待通り、縦の棒線が一直線に表示されました

いつも素晴らしいソフトウェアの開発をありがとうございます

**Comment by 1024jp** [comment]
フィードバックありがとうございます。

いただいた件に関しては、まず「仕様です」という答えになります。

## 源ノ等幅の特性

これは以下2つの源ノ等幅 (Source Han Mono)の特性に起因します。

### 1. 半角文字3文字で全角文字2文字分の幅を持つ

私もよく知らなかったので面白いなと思っているのですが、源ノ等幅は一般的な等幅フォントのように全角文字1文字が半角文字2文字分でなく半角文字1.5文字分の幅を持っています (cf. [Source Han Mono Version 1.000 Technical Nuggets](https://blogs.adobe.com/CCJKType/2019/05/source-han-mono-v1000.html))。審美性を優先した結果でしょう。
つまり、逆にいうと全角文字が奇数個連続しているときは期待した列合わせがされません。

<img width="280" alt="Screen Shot 2020-05-07 at 17 09 28" src="https://user-images.githubusercontent.com/1165044/81270311-84209780-9085-11ea-926b-b5a9d27e8bb1.png">

### 2. 絵文字を持っていない

源ノ等幅は絵文字を持っていないため、絵文字に関しては（フォールバックフォントとして）システムに内蔵しているApple Color Emojiが使用されます。よって絵文字部分は源ノ等幅ではなく別のフォントなので、源ノ等幅の文字幅と同じ文字幅規則であることは期待できません。
ただ、手元で検証した限りでは絵文字は半角文字2文字分の幅で描画されているように見えます。

<img width="300" alt="スクリーンショット 2020-05-07 17 20 23" src="https://user-images.githubusercontent.com/1165044/81271445-0d849980-9087-11ea-98c9-b3bc4cd6df03.png">

検証は同じくmacOS 10.15.4環境下で源ノ等幅 Nの最新版 ([Version 1.002](https://github.com/adobe-fonts/source-han-mono/releases/tag/1.002)) を用いて実施しましたが、源ノ等幅のバージョン 1.002でフォントの幅周りのフラグの変更を行っているようなのでバージョン違いに起因する可能性があります（これに関しては検証してないので予想になります）。

## vimについて

> 同じフォントでターミナル上のvimでは期待通り、縦の棒線が一直線に表示されました

vimは計算を単純化するためにすべてのフォントが等幅であると仮定して位置計算をしており、反対にプロポーショナルフォント（文字によって幅が違う）においては期待した文字位置を得られないかと思います。
一方CotEditorはプロポーショナルフォントはプロポーショナルフォントとして扱っています。
これはアプリケーションの設計思想の違いとなります。

**Comment by 1024jp** [comment]
Additional reference (in Japanese): [ntroducing Source Han Code JP](https://blogs.adobe.com/CCJKType/2015/06/source-han-code-jp.html)
> もともと読みやすさの観点から半角欧文はすこしコンデンスすぎると感じていたので、思い切って 2/3（667 ユニット）字幅を採用することにしました。

**Comment by old-fashion-donut** [comment]
早速のお返事をありがとうございます

フォントの仕様は気づきませんでした。ありがとうございます

日本語の等幅フォントでOsakaとM+フォントはきっちり合うのですが、源ノ等幅や欧文等幅フォントのMonaco（+ヒラギノ）やMenlo（+ヒラギノ）、Courier（+ヒラギノ）では合わなくて気持ち悪く感じていたところでした。
