### ISSUE TITLE
CotEditor Script （JXA） 改行コードCRLFファイルでのlineRange領域選択の不具合

### ISSUE THREAD

**Issue by tsuki-fukurou** [coteditor/CotEditor#1062]
**Short Description**
改行コードがCRLFのファイルにて、`.selection.lineRange`で行の選択を行うと、[行数 - 1]分少ない箇所がずれて選択される。
当該ファイルを、改行コード LFに変更したファイルでは正常に選択される。

**Environment**
CotEditor: 3.8.12 (400)
System: macOS Version 10.15.4（19E287）
Language: 日本語

**Comment by 1024jp** [comment]
報告ありがとうございます。これはあるあるなバグですね...。
直します。

**Comment by 1024jp** [comment]
修正しました。この変更は次のバージョンに適用されます。
