### ISSUE TITLE
[bug]Extra character is deleted in vertical editing

### ISSUE THREAD

**Issue by xlighting2017** [coteditor/CotEditor#1063]
# Setup #
CotEditor:  3.8.12(400)
OS: macOS 10.15.4

# Steps to reproduce: #
1. input several lines in CotEditor, for example:
```
https://www.youtube.com/watch?v=1HDneh2wZJQ
https://www.youtube.com/watch?v=2lF6H2X8JWE
```
2. select vertically by holding Opt key on the keyboard, select until "=" in the above text
see screenshot:
![image](https://user-images.githubusercontent.com/25970065/81806414-00681e80-954f-11ea-8013-f1d38021b5b3.png)

3. press "Del" on the keyboard, you will see the "1,2" is deleted too!
see screenshot:
![image](https://user-images.githubusercontent.com/25970065/81806678-6654a600-954f-11ea-8a4b-cf1170d2096b.png)

# Chance to reproduce #
100%

# Extra findings #
1. it won't happen if I use Backspace instead to Del

**Comment by 1024jp** [comment]
Thank you for pointing out the bug.
I've just succeeded in reproducing this under my environment. I'll try to fix it.

**Comment by 1024jp** [comment]
Fixed. The change will be applied to the next CotEdior 3.9.0. Thanks again.
