### ISSUE TITLE
remember last softwrap status(or disable on startup)?

### ISSUE THREAD

**Issue by qokelate** [coteditor/CotEditor#1066]
remember last softwrap status(or disable on startup) please, because it is too slow when paste very long text.

**Comment by 1024jp** [comment]
You can set the default behavior in Preferences > Edit.

<img width="672" alt="Screen Shot 2020-06-19 at 16 59 23" src="https://user-images.githubusercontent.com/1165044/85110726-4a2edd80-b24e-11ea-930d-84f72488e80d.png">

**Comment by qokelate** [comment]
thanks much!
