### ISSUE TITLE
[request]support for typescript

### ISSUE THREAD

**Issue by AdrianDuan** [coteditor/CotEditor#1067]
Hi, wanna know if it's possible to add syntax support for typescript file? Btw when I'm trying to open a typescript file, CotEditor popup a dialog and alert that the file is MPEG-2 streamclip file.
<img width="762" alt="截屏2020-05-22 17 50 13" src="https://user-images.githubusercontent.com/26034046/82655739-3e52fa00-9c55-11ea-9aac-27261e230419.png">
<img width="532" alt="截屏2020-05-22 17 50 24" src="https://user-images.githubusercontent.com/26034046/82655756-4317ae00-9c55-11ea-9f53-d15d9f46cec5.png">

**Comment by marek-benes** [comment]
Hi, could you add syntax support for typescript file, please?
