### ISSUE TITLE
outline interprets shell script inside markdown

### ISSUE THREAD

**Issue by tenox7** [coteditor/CotEditor#1068]
outline (the thing that shows functions and method) interprets markdown headers such as # ## ### inside shell block

example

# head
## paragraph
bla bla bla
```shell
#!/bin/sh
# comment
echo aaa
```

Outline will incorrectly show #!/bin/sh and # comment as items in outline

**Comment by tenox7** [comment]
same for comments

**Comment by 1024jp** [comment]
Thank you for the feedback.
However, I'd close this issue just because it was already reported in #582 

Well anyway, I know I need to re-design the entire syntax parsing algorithm in the (near) future...
