### ISSUE TITLE
ステータスバーの「現在の列」を文字数ではなく半角文字数にして欲しい

### ISSUE THREAD

**Issue by freeak** [coteditor/CotEditor#1069]
ステータスバーに表示できる「現在の列」が、文字数で表示されるため、半角全角混じりの時に、縦ラインを合わせるために利用できません。
「位置」も同様です。

現在ステータスバーに
行数: 文字数: 位置: 行: 列: を表示させていますが、
全行数: 全文字数: 文字位置: 行: 文字数:　の様な表記にし、さらに半角で数えたときの 列: があると嬉しいです。

**Comment by 1024jp** [comment]
フィードバックありがとうございます。
なるほど...、ニーズはわかりますが需要が少なそうなのと設定や管理が煩雑になるので
申し訳ないですが棄却させてください。
