### ISSUE TITLE
Smart Dashes can’t be turned off

### ISSUE THREAD

**Issue by superpixel** [coteditor/CotEditor#1071]
## Environment (Umgebung)

- CotEditor: 3.9.0 (421)
- System: macOS Version 10.15.5 (Build 19F96)
- Language: German

## Short Description (Kurzbeschreibung)

Even if Smart Dashes are turned off in the "Edit" preferences of CotEditor, double hyphens (--) still geting substituted with a dash sign (–).  

## Steps to Reproduce the Issue (Schritte zur Reproduktion)

1. Turn off Smart Dashes under Substitution in the "Edit" prefernces.
2. Try to type a comment in an xml document ("")
3. This will be subsituted to "<!– comment –>" and is not a valid XML comment anymore.

## Expected Result (Erwartetes Ergebnis)

The set preferences sould be respected and "--" not substituted.

**Comment by 1024jp** [comment]
Hmm, it works correctly under my environment, though it's the same as yours (CotEditor 3.9.0, macOS 10.15.5).
Is there any possibility that a 3rd party helper interrupts the input?
Or, are there any additional conditions to reproduce this issue?

<img width="860" alt="Screen Recording " src="https://user-images.githubusercontent.com/1165044/83231851-2506fc00-a1c7-11ea-8d6c-3d0aac28a59a.gif">

**Comment by superpixel** [comment]
I figured out that I had an additional active "replace with" rule active in system preferences → keyboard → Text. I removed it and now the it works like a charm. I am very sorry for the fuzz I created.

**Comment by 1024jp** [comment]
Aha, that's good.
Thanks for the follow-up.
