### ISSUE TITLE
Help windows vanish

### ISSUE THREAD

**Issue by grumpygamer** [coteditor/CotEditor#1072]
## Environment

- CotEditor: 3.9.0 (421)
- System: macOS Version 10.14.6 (Build 18G5033)
- Language: English

## Short Description

After opening a Help window, I switched to another Application (in different Space) and now I can't get any Help window to display. I've tried quitting and the Help window still won't appear.  I suspect that they are opening in an odd screen space due to Spaces.

I don't see any option to set set Windows.

## Steps to Reproduce the Issue

I can't get the Help window back to try and Reproduce.

## Expected Result

Help windows don't vanish.

**Comment by 1024jp** [comment]
Thank you for the feedback.
However, the help window is actually not managed by CotEditor but the macOS system.
CotEditor just provides the contents.
Therefore, sorry, but Apple has the responsibility for this phenomenon, and CotEditor can't help.
