### ISSUE TITLE
Feature Request: Print Selection…

### ISSUE THREAD

**Issue by marc-medley** [coteditor/CotEditor#1075]
Add ability to `Print Selection…` based on the the current active window selection. The `Print Selection…` could be placed on the `File` menu below the existing `Print`.

Line numbers, if printed, should be the same as the selected line numbers.

**Comment by 1024jp** [comment]
Thank you for the feedback.
That sounds interesting and useful.
I'll consider it.

**Comment by 1024jp** [comment]
I thought about the plan of the next CotEditor 3.10 in the last few days and decided to implement this feature to 3.10, which will be released this summer.

**Comment by marc-medley** [comment]
Great! Thank you.

**Comment by 1024jp** [comment]
Sorry, but I'll postpone the implementation of this feature to 4.1.0.
It is actually harder than I thought, thus needs some more time.

**Comment by marc-medley** [comment]
Then I look forward to when 4.1.0 is released. Thank you.
