### ISSUE TITLE
Shift+returnで<br>が出なくなりました。

### ISSUE THREAD

**Issue by taka-fumi-3** [coteditor/CotEditor#1076]
バージョン3.9.0 (421)を使用しています。
前のバージョンまでは「HTML」で書いていると Shift+returnで<br />が出てきたのですが、
今はただの『改行』になってしまいます。
使用しているmacOSは Catalina Ver.10.15.5
Coteditorの設定は以前から変更していません。
ヘルプではデフォルトで『Shift+returnで<br />』とあるのですが、
なにか設定変更しなければいけなかったのでしょうか？

**Comment by 1024jp** [comment]
Shift+Retrunで`<br>`を入力機能は、CotEditorのキーバインドスニペット機能を利用したもので、デモも兼ねて以前からデフォルトで設定していたのですが、HTMLを書かないユーザにとってはあまり有用でなく混乱の元になるので、おっしゃる通りCotEditor 3.9.0でデフォルト設定から削除しました。

再び有効にするには、CotEditorの環境設定 > キーバインド > スニペットの「テキストの挿入0」設定としてキー欄を選択してアクティブな状態でShift+Returnを入力したのち、「挿入文字列のフォーマット」に「`<br>`(改行)」を入力してください。


<img width="620" alt="Snippet key bindings" src="https://user-images.githubusercontent.com/1165044/83715985-9d5b3a80-a669-11ea-8463-d8e4296289be.gif">
__

**Comment by BBmoni** [comment]
すみません、いつも使わせていただいております。現在はCotEditor4.0.8となります。
スニペットのアクションでキーが入力できません。Shift + return　
どのように入れればいいでしょうか？

**Comment by 1024jp** [comment]
@BBmoni コメントありがとうございます。本件（Shift+Returnが弾かれる）バグでした。次バージョンで修正いたしますのでご不便おかけしますがしばしお待ちください。
