### ISSUE TITLE
Cannot save changes to existing or duplicated syntax style

### ISSUE THREAD

**Issue by crankygeologist** [coteditor/CotEditor#1077]
## Environment

- CotEditor: 3.9.0 (421)
- System: macOS Version 10.15.5 (Build 19F101)
- Language: English

## Short Description

Cannot save changes to existing or duplicated syntax style.

## Steps to Reproduce the Issue

Click the button to edit the existing style
Add or change a new string
Click OK
Changes are not made in open documents

## Expected Result

Changes should appear in open documents and the existing syntax style should retain my changes.

**Comment by crankygeologist** [comment]
Problem does not occur when regressing to Version 3.8.12 (400).

**Comment by 1024jp** [comment]
Thank you for the report.
I confirmed the issue.
This must be a bug added to 3.9.0 and needs to fix.

**Comment by crankygeologist** [comment]
Thank you!
