### ISSUE TITLE
縦書とフォントの関係？

### ISSUE THREAD

**Issue by yoshihirotameike** [coteditor/CotEditor#1079]
源ノ角ゴシック，源ノ明朝を使うと，なぜが縦書で文字が表示されません…。

**Comment by 1024jp** [comment]
macOS, CotEditor, フォントのバージョンをそれぞれ教えてください。
また、「文字が表示されない」が具体的にどのような状況かもう少し説明していただけると助かります。
表示されない状況のスクリーンショットも欲しいです。

**Comment by 1024jp** [comment]
なお、現在縦書きは表示範囲の計算がおかしい、というApple側のバグがあります。
ウインドウのサイズや縦横比などを変えてみて、状況が変わるかを確認していただきたいです。

**Comment by yoshihirotameike** [comment]
不十分な投稿をしてしまい申し訳ありませんでした。

macOS 10.15.5
CotEditor 3.9.0(421)
源ノ角ゴシック 1.004
源ノ明朝　1.001

ウィンドウサイズ変えても状況は同じでした。
縦書にしたときのスクリーンショットです。

![スクリーンショット 2020-06-11 15 20 15（2）](https://user-images.githubusercontent.com/66004613/84352116-b2027a00-abf7-11ea-8070-5278676483ae.png)

**Comment by yoshihirotameike** [comment]
自己フォローです。

macOS 10.15.5
CotEditor 3.9.0(421)
源ノ角ゴシック 2.001

で縦書表示可能になりました。
教えていただき，ありがとうございます。

**Comment by 1024jp** [comment]
フォント側の問題だったようですね。
解決してよかったです。フォローありがとうございます。

また何かありましたらお知らせください。
