### ISSUE TITLE
Typewriter scrolling

### ISSUE THREAD

**Issue by hal99** [coteditor/CotEditor#1081]
#request

**Comment by hal99** [comment]
CotEditor: 3.9.1

文字入力をしている時に、改行位置を特定の場所で固定する機能があるとありがたいと思いリクエストします。

いわゆるタイプライタースクロール的な機能で、改行をした時に画面の中央にスクロールから移動しない(または別の位置にあれば中央に移動）するのを想定しています。

**Comment by 1024jp** [comment]
本リクエストはいわゆるタイプライタースクロール（カーソルがエディタに対して縦方向に常に特定の位置に来るように、カーソルが動いたときにスクロール側を調整する）に関するものでしょうか？

**Comment by hal99** [comment]
はい、ご指摘のとおりです。何度か機能が実装されてないか探しているのですが、別名などで実装済でしたら申し訳ありません。

**Comment by 1024jp** [comment]
なるほど理解しました。回答ありがとうございます。

> 別名などで実装済でしたら申し訳ありません。

現時点では実装されていないです。

ニーズとしては存在しているのは知っているのですが、スクロール周りの制御は結構ややこしいのに加え、あまり積極的に実装する理由がないため優先順位が低く、ひとまず保留とさせてください。

**Comment by 1024jp** [comment]
長らく保留としていましたが、この機能は上記のように実装が複雑な上に、CotEditorのような「汎用」テキストエディタに実装するには高度すぎる機能だという結論に達し、実装は見送ることにしました。
お待たせした上にすみません。
