### ISSUE TITLE
start with current tab for save dialog

### ISSUE THREAD

**Issue by wokier** [coteditor/CotEditor#1084]
When i close coteditor and i have multiple unsaved documents,
there is the "do you want to keep this new document" for each unsaved document,
but it starts with the first tab instead of the current tab.
That leads to lost works if you click on 'delete' that you intend to do for the current document but it does it for the first tab document.

CotEditor 3.9.1 on macos 10.14.6

**Comment by 1024jp** [comment]
Thank you for the feedback (and sorry for my very late reply).
However, CotEditor does not prefer modifying the current behavior so far as changing the default behavior by the native framework. I understand your problem but the current one is not *incorrect*. In addition, I am afraid of adding original code to this area of that the framework currently takes care can easily create unwanted side-effects.
