### ISSUE TITLE
Resizing the the editor window

### ISSUE THREAD

**Issue by BillyV2018** [coteditor/CotEditor#1087]
## Environment

- CotEditor: 3.9.2 (425)
- System: macOS Version 10.13.6 (Build 17G13035)
- Language: English

## Short Description

Resizing the the editor window.

## Steps to Reproduce the Issue

Editor starts without Inspector column on the right of the window.
I can resize the editor window on left and right side.
Then I push Inspector button.
Now I cannot resize the window anymore, only the interior bar that separates the text frame from the inspector frame.

Then I opened this template in order to write an issue. The newly opened editor window can be resized as expected. But the first window cannot.

I close the inspector frame in the window I started with. The window can be resized again.

## Expected Result

Ability to resize.

**Comment by 1024jp** [comment]
I suppose this issue was already fixed at some time point.
Please let me know if you still get it.
