### ISSUE TITLE
設定の引き継ぎ / Porting CotEditor's settings to another Mac 

### ISSUE THREAD

**Issue by freeak** [coteditor/CotEditor#1088]
Macから別のMacに CotEditor の設定を引き継ぎたいです。

**Comment by 1024jp** [comment]
ref. #811

**Comment by 1024jp** [comment]
I close this issue just because of duplication #1254.
Although this ticket is older than the duplicated one, #1254, I'd like to prioritize the new one over this ticket because the new one is written in English.
