### ISSUE TITLE
Opening a JSON file without line break takes time to open

### ISSUE THREAD

**Issue by kim-take** [coteditor/CotEditor#1089]
## Environment (環境)

- CotEditor: 3.9.2 (425)
- System: macOS バージョン10.14.6（ビルド18G5033）
- Language: Japanese

## Short Description (簡単な説明)

Takes time opening a 500K Json file with no line break (one line.)

## Steps to Reproduce the Issue (不具合が発生したときに行っていた操作、または再現手順)

Word wrap (エディタの幅に合わせて行を折り返す) on.
Syntax coloring (シンタックスカラーリングを有効にする) on.
Open a 500K Json file.

It took 450 secs for the window to show up.
Opens at once when word wrap and syntax coloring are off.

I did some rough tests with a couple of versions.
Opens at once with syntax coloring off with 3.8.12.
It takes 40 secs with 3.8.0, 3.7.8, 3.7.7, 3.7.6.
Opens at once with 3.7.5, 3.7.0, 3.6.12.

## Expected Result (期待される挙動)

Open at least in a few seconds.

**Comment by 1024jp** [comment]
Thank you for the feedback.
I identified and addressed the bottleneck by soft-wrapping lines.
This change will be released in this weekend 😉.

As for syntax highlighting, it still takes time due to other technical issues that are hard to change immediately.
I'll work on them in the future.

**Comment by kim-take** [comment]
Thanks for the quick fix!
Can't wait for the release!

**Comment by kim-take** [comment]
> Thanks for the quick fix!
> Can't wait for the release!
> 

@1024jp Actually, it was installed already. Thanks again!
