### ISSUE TITLE
Highlights are oddly rendered with the option 選択した文字をハイライト

### ISSUE THREAD

**Issue by superhonya** [coteditor/CotEditor#1090]
いつも開発おつかれさまです。

選択した文字列が改行を含むとき、「選択した文字をハイライト」のハイライトの形状がおかしくなってしまうようです。

CotEditor バージョン3.9.2 (425) / macOS 10.14.6 で確認しました。

![ScreenShot 2020-07-13 7 31 51](https://user-images.githubusercontent.com/45976686/87398774-5c076480-c5f1-11ea-899d-713a230e4a97.png)

**Comment by 1024jp** [comment]
なるほど、これはなんとも立派なバグですね...。
ご報告いただきありがとうございます。修正します。

**Comment by 1024jp** [comment]
修正、というか改行を含むときはハイライトの対象にならないようにしました。
ご報告いただきありがとうございます。
