### ISSUE TITLE
app (3.9.2) hangs while replacing all blank within line with regular expression 

### ISSUE THREAD

**Issue by RainerHinney** [coteditor/CotEditor#1091]
The app hangs while replacing all blank within line with regular expression e.g. \n, \r, \r\n
This works before and I used it very often ...

**Comment by 1024jp** [comment]
Today, I've just released CotEditor 3.9.3 that fixes a performance issue on the large text manipulation.
Please try 3.9.3 and let me know whether it fixes your issue.

**Comment by RainerHinney** [comment]
the new version 3.9.3 fixes the issue
