### ISSUE TITLE
How about document pane of opened files?

### ISSUE THREAD

**Issue by jes303** [coteditor/CotEditor#1093]
After trying many text editors / IDE's on the Mac, I must say I find CotEditor the best! I use it on a daily base for my frontend and PHP development.

One thing that I bump into everytime is the tabs for the opened documents. While it's an OK solution for having a few files opened, it gets fuzzy when say 5 or more files opened, as you can imagine. Reading the filenames horizontally is a pain for the eyes and very time consuming:

![Screenshot 2020-07-25 at 16 50 17](https://user-images.githubusercontent.com/68782044/88459611-f8a1f000-ce96-11ea-870b-aa70f3005f03.png)

May I mention one program which did a perfect job back in the day? Textpad: solved it as simple as this (no complicated nodes are folders that can be folded / unfolded) -- it worked like charm:

![download](https://user-images.githubusercontent.com/68782044/88459535-70bbe600-ce96-11ea-9013-89c12e7c7a4e.jpeg)

Hopefully I'm not the only one thinking this is a time saver!
Thanks and keep up the good work.
Jeroen.

**Comment by helmut72** [comment]
If no folder/project view is coming, please add at least this feature.

**Comment by tenox7** [comment]
The open document list is in Window menu, I think it shouldn't be too hard to make it to a pane.

**Comment by 1024jp** [comment]
After reconsidering, I have come to the conclusion that window tabs should still not behave outside of the macOS standard.
I left this request open for a long time, but I am closing it as unacceptable.

**Comment by helmut72** [comment]
Understand, it's not standard. Because CotEditor is just a (good) editor, but I need some kind of project management for my notes, I've switched from CotEditor to vscode long time ago.
