### ISSUE TITLE
macOS Big Sur icon

### ISSUE THREAD

**Issue by jotapapel** [coteditor/CotEditor#1095]
any ideas?

**Comment by 1024jp** [comment]
Don't worry.
I've already prepared the [new Big Sur style icon](https://github.com/coteditor/CotEditor/blob/e521c07afaf2a315f59fb643a16981257c7a3718/CotEditor/Assets.xcassets/AppIcon.appiconset/icon_512x512%402x.png).
It is just waiting for the release.
