### ISSUE TITLE
【テキスト＞変換】の処理で、選択箇所だけでなく、その次に出現する同じ文字列も変換される

### ISSUE THREAD

**Issue by wanik** [coteditor/CotEditor#1096]
## Environment (環境)

- CotEditor: 3.9.4 (430)
- System: macOS バージョン10.13.6（ビルド17G14019）
- Language: Japanese

## Short Description (簡単な説明)

選択した文字列を大文字にする等の処理を行なうと、選択箇所だけでなく、その次に出現する同じ文字列も変換されます。

## Steps to Reproduce the Issue (不具合が発生したときに行っていた操作、または再現手順)

ラテン字のテキストで、ある文字列を選択します。（複数箇所ではなく、ひと連なりの部分のみの選択です。）

メニューから、【 テキスト ＞ 変換 ＞ 大文字にする 】

を行ないます。

そうすると、**選択箇所だけでなく**、**その次に出現する同じ文字列**も大文字に変換されます。（同一テキスト内の同じ文字列すべてではなく、次に出現する同一文字列だけです。）

【小文字にする】【語頭を大文字にする】でも同様の現象になります。

【全角にする】の場合は、選択部分だけが全角になり、問題ないようです。

【 環境設定 ＞ 一般 ＞ 選択した文字をハイライト 】は、チェックの有無にかかわらず、この現象が出ますので、関係なさそうです。

**図**: 変換前。**選択だけの状態**。

![henkan1](https://user-images.githubusercontent.com/34469683/90132089-239da680-dda8-11ea-9267-628dd98046a6.png)

**図**: 変換後。**1行目の pen と pencil が、PEN と PENcil になります。** （2行目以降の pen は問題なし）

![henkan2](https://user-images.githubusercontent.com/34469683/90132110-2b5d4b00-dda8-11ea-8cc6-86cfcf241787.png)

## Expected Result (期待される挙動)

テキストの変換は、選択部分のみであるか、
あるいは、オプションで、マッチしたものすべてが変換されるか
といった形が望ましいと思います。

**Comment by 1024jp** [comment]
いつも丁寧な報告ありがとうございます。

これは明らかに望んでいない挙動ですね...。
Appleの提供しているAPIを直接使っている箇所だけこの挙動になるようで、
原因不明なのでまずそこを調べるところから始めないといけなそうですが、
いずれにせよ、修正します。

**Comment by 1024jp** [comment]
あ、原因わかりました。
次のリリースに修正を乗せます。

**Comment by wanik** [comment]
原因がわかって、よかったです。
修正もできたようで、次のリリースお待ちしております。
どうもありがとうございます。
