### ISSUE TITLE
PHP Syntax Highlight issue

### ISSUE THREAD

**Issue by abhibeckert** [coteditor/CotEditor#1101]
PHP Syntax highlighting is broken when a string contains a "#" - it will be incorrectly highlighted as a comment:

<img width="482" alt="Screen Shot 2020-08-31 at 16 48 56" src="https://user-images.githubusercontent.com/266088/91690864-ff183b80-eba9-11ea-8c54-144de143b6f2.png">

**Comment by abhibeckert** [comment]
Note: "#" comments are not the standard inline comment for PHP, it's an alternate syntax implemented with a basic regex pattern.

I'm not sure of the best way to fix this?

**Comment by 1024jp** [comment]
I close this issue just because I found it is a duplication of #1007.
