### ISSUE TITLE
About the "Application Scripts" folder on environment of macOS Big Sur.

### ISSUE THREAD

**Issue by knlab** [coteditor/CotEditor#1104]
As you may know... When executing CotEditor 3.9.5 (433) on macOS Big Sur, can't find Application Scripts folder via Script menu (Open Scripts Folder..)

I found is the symlinks in this folder (/Users/{UserName}/Library/Containers/com.coteditor.CotEditor/Data/Library/Application Scripts) are not accessable.

I checked '~/Library/Application Scripts/com.coteditor.CotEditor' in my environment, there was no such directory. 
(If I remember correctly create this folder automatically.)

Maybe apps or os created a directory name like "06DFACB4-9335-4148-B0D9-AE91FCA4E930" instead of "com.coteditor.CotEditor".

So I was able to create the 'com.coteditor.CotEditor' directory myself and solve the problem.

Now, although it is a pre-release version of macOS, it was necessary to confirm the script operation with CotEditor early.
I would appreciate it if hope this problem is fixed quickly.

I hope you will find the report useful.

**Comment by 1024jp** [comment]
Sorry for my late reply and thank you for the report.

I recently published [beta](http://coteditor.com/beta) for CotEditor 4.0.0 that is aim mainly to support up-coming Big Sur.
Is it fixed your issue?

In addition, on CotEditor 3.9.6 (released on 2020-09-13), I fixed the issue that the menu item "Open Scripts Folder" did not actually open the script folder for CotEditor.

**Comment by knlab** [comment]
Thank you for promptly handling the matter with care.

I tried updating to CotEditor 4.0.0 beta in my environment. 
My environment is fixed, now it can open script directory via script menu.

In addition, I updating to the latest version of CotEditor 3.9.x. It's working very well too.

**Comment by 1024jp** [comment]
Thank you for your feedback 🙂.

As it looks fixed, now I close this.
