### ISSUE TITLE
Does not build under Mojave macOS-10.14

### ISSUE THREAD

**Issue by Asc2011** [coteditor/CotEditor#1106]
What was the last version that one could use with XCode 11.3 under Mojave ?
I just want to add one or two language syntaxes - do i need to build the whole project or is there a simpler solution ?

Thx

**Comment by 1024jp** [comment]
If you just wanna add syntax styles, you don't need to build the app.
Just add the definition file (with .yml) to /CotEditor/Syntaxes directory and add file mapping setting to SyntaxMap.json.

**Comment by 1024jp** [comment]
Regarding to the first question:

> What was the last version that one could use with XCode 11.3 under Mojave ?

Sorry, I don't remember exactly...
Version 3.8.12 may work, but not sure whether it's the last.
