### ISSUE TITLE
『新規』を開くと必ず名称が「名称未設定4」から始まってしまいます。

### ISSUE THREAD

**Issue by rio-redstone** [coteditor/CotEditor#1108]
新規書類を作成する時、書類の名称が「名称未設定4」から始まり、「名称未設定5」「名称未設定6」と続きます。
これを、「名称未設定」または「名称未設定1」からに変更する（戻す？）ことはできないでしょうか？

**Comment by 1024jp** [comment]
おそらく1〜3がどこかに残っていますね。
iCloudのCotEditorフォルダの中にないでしょうか？

**Comment by rio-redstone** [comment]
iCloudにありました！
iCloudのものを削除したところ「名称未設定」に戻りました。
お騒がせしました！

**Comment by 1024jp** [comment]
よかったです。
解決したのでcloseしときますね。

**Comment by rio-redstone** [comment]
ありがとうございます！
