### ISSUE TITLE
Search text input on the toolbar / ツールバーに検索欄

### ISSUE THREAD

**Issue by knoajp** [coteditor/CotEditor#1109]
en:
The current search and replace window launched by Cmd+F is a bit too rich interface for most of my usecase.
I do replace or even use regexp feature sometimes, but usually I just want to find a keyword in my text.

If a simple search text input form is on the toolbar, I can search more easily. And it's a rather common feature of text editors in the world, I think. How about you?
(key bindings while current search and replace exists will be a tiny issue though...)

ja:
いまの Cmd+F で出てくる検索と置換のウィンドウは、私のふだんの用途にはインターフェイスがリッチすぎると感じています。
置換することもあるし正規表現を使うこともありますが、多くの場合はテキストの中から検索語を探したいだけなのです。

ツールバーの中に検索用の入力欄がたたずんでくれていると、より気軽に検索できると思いますし、比較的多くのテキストエディタが備える一般的な機能の一つだとも思います。いかがでしょうか？
(既存の検索があるのでキーバインディングの割り当てはちょっと配慮が必要かもしれません)

**Comment by 1024jp** [comment]
Thank you for the feedback.

I have received this kind of request several times, and every time, I wonder what should be the best way to fulfill this demand. If CotEditor implements a search field in the toolbar straightforward, most of the users may just use that one and can't find the normal find panel that has richer features. I am mostly afraid of that. So I need to design it carefully and with thought, if I carry it out. And therefore, I just simply postpone it, until now.

Well, I'll consider it again. But the priority may not be high.

**Comment by gregarios** [comment]
An additional request for the search/replace tool: Can you make it also work with all open documents.
So find/replace all could act on all open documents.

Also the "replace" feature could use a key command (like comand-D possibly) so we can set a find and replace text and just "command-D" or "command-G" (next) through the document replacing certain occurrences as needed.

Sorry to include so many things lol.

**Comment by knoajp** [comment]
@1024jp 
I understand your concern.
If you just put the search input field on the default toolbar item set on future update, a newcomer after that may miss the richer search feature.
But you can silently add the toolbar item like "Simple Find" next to the current "Find" on the toolbar customization panel. If you do so, none of the user find a "Simple Find" item without noticing the current "Find" item on the panel. You can also rename the current "Find" label to "Rich Find" or "Find & Replace".
This can be a solution with no regression.

**Comment by 1024jp** [comment]
Since toolbars in the recent macOS have exhausted the space available for toolbar items, I have decided not to implement the feature to put the search field on the toolbar even if it is optional.

**Comment by knoajp** [comment]
OK, I appreciate your decision.
Although, my toolbar has plenty of space! 😉
![20240629-132654](https://github.com/coteditor/CotEditor/assets/844187/f75ca6ac-2031-472b-b80d-97b18c75f0be)
