### ISSUE TITLE
In CotEditor v4.0.0 beta2, the standard error cannot be displayed on console.

### ISSUE THREAD

**Issue by knlab** [coteditor/CotEditor#1110]
I tried to run the sample script (I called trial.sh) via script menu.

```Shell
#! /bin/sh
# %%%{CotEditorXInput=Selection}%%%
# %%%{CotEditorXOutput=ReplaceSelection}%%%

echo "replace stdout" >&1 # standard out
echo "output stderr" >&2 # standard error
```

<img width="366" alt="Console" src="https://user-images.githubusercontent.com/35491752/95578164-614c4200-0a6e-11eb-902f-846cb0ea5d06.png">

This script can be displayed 'output stderr' on the console in CotEditor v3.9.6.

**Comment by 1024jp** [comment]
Thank you for the report!
I've just fixed it, and it will be fixed in the next beta.
