### ISSUE TITLE
Vertical Selection

### ISSUE THREAD

**Issue by semiroot** [coteditor/CotEditor#1113]
A feature I really miss is 'Vertical Selection' possibility. Its the only reason I occasionally have to use a IDE.
Please consider adding this feature.

**Comment by 1024jp** [comment]
Could you describe more about your "Vertical Selection"?
How it should work?

If you are talking about the rectangular selection (or column selection), CotEditor already has one. Hold the Option key and drag the cursor with the mouse or trackpad.

![Screen Recording 2020-10-19 at 17 12 15](https://user-images.githubusercontent.com/1165044/96419198-c2260800-122e-11eb-8225-2122f056e6cc.gif)

**Comment by semiroot** [comment]
Thank you for you response.

How embarrassing for me. 
Yes, this is exactly what I meant. 
I was so used to another key combination that I did not try this one.

Sorry for bothering you with this.

**Comment by 1024jp** [comment]
> I was trying this key combination, but it does not work.

Hmmm, that's strange...
- Do you use any of the keyboard mappers, such as karabiner?
- What is your input source?
- What happens instead, when you drag the cursor with the Option key?
    - Note that you need to keep pressing the Option key while dragging.
    - First of all, the cursor should turn into a + form when you press the Option key above a CotEditor's editor (See the screencast I posted above).

**Comment by semiroot** [comment]
I have located my issue.

Rectangular selection works like a charm if I press option **before** selecting.
**During** selection it does not; which I was used to. (this could be a slight improvement to the functionality)

Thank you so much for the help! 
And have a great day.

**Comment by 1024jp** [comment]
> During selection it does not; which I was used to from Rider, VS etc. (this could be a slight improvement to the functionality)

Aha, thank you for sharing the point.
This, pressing the Option key only before dragging, is actually the standard behavior in macOS. Therefore, regarding CotEditor that aims to behave natively on macOS, I'll not change the current behavior.

Anyway, I'm glad to hear your issue is now solved.
