### ISSUE TITLE
CotEditor v4 crashed : When opening a console window first time via CotEditor scripting with UNIX scripts.

### ISSUE THREAD

**Issue by knlab** [coteditor/CotEditor#1114]
Issues #1110 was resolved on CotEditor v4 beta3. Thanks.

But as a new issue, I seems a apps crashes when It tried open to console window first time via CotEditor scripting with UNIX scripts.

If I pre-opened the console by Menu, this issue doesn't occur.

This issue has been identified CotEditor v4.0.0 beta 3 on macOS 10.15.7 and 11.0 beta 10.
The UNIX script used for the experiment is the same as #1110.

**Comment by 1024jp** [comment]
Oops, thank you for the report, and sorry for .., yes, this must be a regression in beta.3.

I've just fixed it and will release beta.4 this weekend with some other changes.
