### ISSUE TITLE
OEM 866

### ISSUE THREAD

**Issue by sem174** [coteditor/CotEditor#1119]
Good afternoon, is it possible to add support for DOS OEM 866 for editing old Russian-language scripts bаt and cmd?

**Comment by 1024jp** [comment]
Hi.

According to my brief research, DOS OEM 866 seems to be called as "Russian (DOS)" on macOS and its IANA-charset is `cp866`, right?
Then, I'll add it to the next version ;-)

**Comment by sem174** [comment]
https://en.wikipedia.org/wiki/Code_page_866
Perhaps you are talking about this, then this is what you need.
