### ISSUE TITLE
Hope to add the "Select All  Unfind Matches" function to quickly delete unmatched items at once

### ISSUE THREAD

**Issue by qxs7** [coteditor/CotEditor#1120]
Commands in the main menu

"Show Inspector" = "Show Inspector";
"Hide Inspector" = "Hide Inspector";
"Select All Find Matches" = "Select All Find Matches";

**Hope to add the "Select All Unmatches" function to quickly delete unmatched items at once**

Such as
**`"Select All Unmatches" = "Select All Unmatches";`**

Thanks!

**Comment by 1024jp** [comment]
Thank you for the request.

However, I feel your request is too niche to add.
Instead, I prefer to create your own script to realize that process.
