### ISSUE TITLE
"Replace all" causes the position of the page to move

### ISSUE THREAD

**Issue by ceciliacase** [coteditor/CotEditor#1121]
Fill the following template, and post it on [GitHub Issues](https://github.com/coteditor/CotEditor/issues) or send to <coteditor.github@gmail.com>. Please note that the contents of the sent email can be shared on the Issue page. Please write the contents either in English or in Japanese.

-----------------------------------------------

## Environment

- CotEditor: 4.0.1 (455)
- System: macOS Version 10.15.7 (Build 19H15)
- Language: English

## Short Description

When I do a “replace all” the position of the scrollbar changes.

## Steps to Reproduce the Issue

Move the scrollbar down from the very top. Find something with more than one match, esp. with matches off the screen. Enter something into the replace field and click “replace all.” The position of the page moves far away from wherever you were before. Note that the behavior only happens when the word that is replacing it is a different number of letters. This causes a real problem because now I've lost context and I have to go find where I was originally working all over again. I work with very large files, so this can be a huge time-waster for me. 

Also, when you do a control-z immediately afterward, that moves the scrollbar, too.

## Expected Result

Prior to this very last update, it did not move the position of the page. I expect that when I do a find/replace that the location of my cursor and the page itself should not move. I expect that if the word is longer, that the text may expand a little underneath the page, or contract if the word is shorter, but that should be the only movement that happens. Ideally, the page location should be locked to the cursor location.

[screenrecording.mov.zip](https://github.com/coteditor/CotEditor/files/5562886/screenrecording.mov.zip)

**Comment by 1024jp** [comment]
In CotEditor 4.0.0, the glyph position calculation timing was changed to postpone it as possible so that the processing performance especially on a large document is optimized. Your report would be a side effect of that change.

Well, anyway, I understand your frustration. I'll try to keep the cursor location in the visible area as possible in the next versions.

**Comment by ceciliacase** [comment]
This seems to be fully fixed in 4.2.1! Thank you!!!

**Comment by 1024jp** [comment]
Thank you for your confirmation.
