### ISSUE TITLE
This file make CotEditor crash (memory leak or unlimited loop)

### ISSUE THREAD

**Issue by Toru-Hisatomi** [coteditor/CotEditor#1122]
When I open this file, CotEditor eats unlimited memory and MacOS suggest me to quit CotEditor force.
I zip it to upload github. Please test it with unzipped condition. 
Thanks. I really love CotEditor.

[81171d233fbf138717f711d140dff45f21ac5ee53819827b8b8ff51c6b30dcc6dadf4c76568effeb50d0b534546febbc.zip](https://github.com/coteditor/CotEditor/files/5579401/81171d233fbf138717f711d140dff45f21ac5ee53819827b8b8ff51c6b30dcc6dadf4c76568effeb50d0b534546febbc.zip)

**Comment by Toru-Hisatomi** [comment]
I'm sorry, I attached the version of CotEditor which I use now.
<img width="282" alt="スクリーンショット 2020-11-22 20 45 36" src="https://user-images.githubusercontent.com/74860050/99902786-b59c4000-2d03-11eb-82ae-232194511611.png">

**Comment by Toru-Hisatomi** [comment]
And here's detail of my Mac.
<img width="579" alt="スクリーンショット 2020-11-22 20 46 34" src="https://user-images.githubusercontent.com/74860050/99902812-dbc1e000-2d03-11eb-8e14-ccd2aa632a79.png">

**Comment by 1024jp** [comment]
Hi, thank you for the report.

I checked the file you attached.
It doesn't crash my CotEditor 4.0.1 on Big Sur; however, CotEditor couldn't interpret the file encoding.

So my questions are:
- What kind of files is this file supposed to be?
- What is the correct file encoding of this file?
- Is there any other plain text editor that can open this file? If yes, let me know the name of the editor.

**Comment by Toru-Hisatomi** [comment]
Hi, 
I checked it with bash and it said it was a Zip archive. So I found it shouldn't be opened with CotEditor. I'm sorry that this issue bothers you.

**Comment by gregarios** [comment]
> Hi,
> I checked it with bash and it said it was a Zip archive. So I found it shouldn't be opened with CotEditor. I'm sorry that this issue bothers you.

I seems to me any file should be able to open "as text" without crashing CotEditor. This is how I research many image files without file extensions I receive, by opening them in a text editor to get a clue.

**Comment by 1024jp** [comment]
@Toru-Hisatomi Thank you for the following-up.

@gregarios That's true, crashing is the worst. I should at least improve the pre-check phase before actually opening the document as plain text. Another problem, in this case, is that I can open the file without a crash, though the content is meanless with many control characters. let me see.

**Comment by gregarios** [comment]
> @Toru-Hisatomi Thank you for the following-up.
> 
> @gregarios That's true, crashing is the worst. I should at least improve the pre-check phase before actually opening the document as plain text. Another problem, in this case, is that I can open the file without a crash, though the content is meanless with many control characters. let me see.

Generally it is meaningless but every file has telltale data and indicators at the top that are not meaningless -- even in total binary files there are headers and such that let you know what it is, like "PDF" or "PNG" and such in the actual text of the file. I ignore the control characters and derive very meaningful things from the binary files opened as text!

**Comment by Stolzenhain** [comment]
> [@Toru-Hisatomi](https://github.com/Toru-Hisatomi) Thank you for the following-up.
> 
> [@gregarios](https://github.com/gregarios) That's true, crashing is the worst. I should at least improve the pre-check phase before actually opening the document as plain text. Another problem, in this case, is that I can open the file without a crash, though the content is meanless with many control characters. let me see.

Dear @1024jp – sorry to comment on this ticket again, but I'm experiencing a similar issue resulting in a crash-loop:

1. opening a very large file (like, 1.5GB)
2. laggy CotEditor will parse file, memory full
3. system warning, force-quit app
4. re-open CotEditor; will try to re-open file, probably due to [this restore feature](https://coteditor.com/releasenotes/2.1.0.en)
5. go to 2)

Is there a way to suppress re-opening files in CotEditor, at least in this case?

(also, this is a great tool, thanks for all the effort and maintenace over the years!)

[Edit:] after deleting the file to prevent it being reopened, CotEditor opened with a prompt to check if the file should be re-opened. So I suppose it might be the sheer amount of caching/preprocessing happening in the background that prevented this dialog.
