### ISSUE TITLE
Split Window Misbehaving

### ISSUE THREAD

**Issue by witeshadow** [coteditor/CotEditor#1127]
I don't recall CotEditor doing this in the past, but now (4.01) when I have a document open with split window and type in the top the bottom part will move.  I want it to stay on the section of the document it was before typing in the other split.

**Comment by 1024jp** [comment]
I couldn't reproduce your issue under my environment.

First of all, I'd like to know your macOS version.
In addition, could you take a screencast of this phenomenon?

**Comment by 1024jp** [comment]
No any reply?
If I don't receive any reply related this issue in the next week, I'll just close this ticket.
