### ISSUE TITLE
Sidebar for Document selection

### ISSUE THREAD

**Issue by rpulikool** [coteditor/CotEditor#1129]
I really appreciate for building this beautiful yet lightweight tool its really nice!!

One feature request that i would like to add is document selector at the side bar, I open lot of files if you can add the document selection on the left side will be greatly appreciated

**Comment by rpulikool** [comment]
also one more thing is whenever open a file the option to open it on the next tab instead of opening a new window

**Comment by 1024jp** [comment]
This is one of the popular requests that hasn't be done.
I close the issue as duplication of #278.
I'll do this someday, but not its turn yet.
