### ISSUE TITLE
置換メニューが機能しない

### ISSUE THREAD

**Issue by oyanuki** [coteditor/CotEditor#1130]
## Environment (環境)

- CotEditor: 4.0.1 (455)
- System: macOS バージョン11.0.1（ビルド20B29）
- Language: Japanese

## Short Description (簡単な説明)

メニューの「検索」内の「置換」を押してもエラー音？がなるだけで画面が表示されない

## Steps to Reproduce the Issue (不具合が発生したときに行っていた操作、または再現手順)

メニューの「検索」内の「置換」を押してもエラー音？がなるだけで画面が表示されない

## Expected Result (期待される挙動)

「置換」機能の有効化

**Comment by 1024jp** [comment]
手元の同環境（CotEditor 4.0.1 + macOS 11.0.1）下では本現象が再現されないため以下のことを確認の上状況をお教え願えますか？
1. この現象は常に再現しますか？ それとも特定の条件下のみ or 稀に起こる ですか？
2. 検索ウインドウの設定を確認の上、下のようなスクリーンショットを下さい。
    - 「選択範囲のみ」が有効になっていませんか？
    - 「検索を折り返す」が無効になっていませんか？

<img width="710" alt="スクリーンショット 2020-12-12 11 40 27" src="https://user-images.githubusercontent.com/1165044/101970631-d86ca500-3c6e-11eb-9b9b-c22edf0f8c90.png">

**Comment by oyanuki** [comment]
1 この現象は常に起こる（と思います）

メニューから「置換」を選択してもOSの通知音がなり上記の置換の画面は表示されません
http://freemacsoft.net/appcleaner/
このソフトを使い削除、インストールしても状況は変わらず

発生条件をもう少し絞込ればよいのですが、

どなたか同じ現象の方いませんかね？
![スクリーンショット 2020-12-12 16 31 46](https://user-images.githubusercontent.com/75704053/101978456-75900380-3c98-11eb-9612-93c16c9cd280.jpg)
（スクリーンショットの斜め線は.heifファイルを.jpgに変換すると発生する現象なのです）

**Comment by 1024jp** [comment]
あ、なるほど。失礼しました。
メニュー内の「置換」コマンドは "検索した結果を置換する" コマンドなので、
例えば何も選択されていない状況で「置換」のみを実行しても何も起こらないのは正しい挙動です。
（これはmacOSでの「検索」と「置換」の標準的な振る舞いです）

なので、おそらくご期待の挙動のためには「検索」→「置換」とするか「置換して次を検索」を実行する必要があります。
もしこの回答が該当しない場合は、もう少し細かい再現例（〇〇と書かれたテキストファイルの××の部分を選択してメニューから「△△」コマンドを実行、など）を教えてください。

// まぁとはいえちょっとわかりづらいのは事実なので、もう少しわかりやすくできないかは検討してみます。

**Comment by oyanuki** [comment]
あー、上記の説明で合ってます。了解しました。
なのでこれでクローズします
