### ISSUE TITLE
Scripting Hooks still a thing?

### ISSUE THREAD

**Issue by kour1er** [coteditor/CotEditor#1131]
I was reading with interest about [scripting hooks](https://github.com/coteditor/CotEditor/pull/649) and then was trying to follow along with the example template from [here](https://github.com/coteditor/SampleScripts/tree/master/AppleScript/Template). But I can't seem to get any of the "on document opened" or "on document saved" hooks to work.

Are they still supported in CotEditor 4.0.1 and Big Sur? I've read the [documentation](https://gist.github.com/umireon/9d7a0d48bbd2574407008ab6c121b7ad) but can't seem to get it working, so just wanted to check that it was still a thing that should work :) Any pointers would be very gratefully received.

**Comment by 1024jp** [comment]
Sorry for my super late answer.

You can find a sample script in the following repository (Hook Template):
https://github.com/coteditor/SampleScripts/tree/main/AppleScript/Template

In addition, I've updated the user guide for the scripting hook in the upcoming version of CotEditor 5.0.7, which is scheduled for release within the next few days.
You can find the page by typing "Add scripting hooks" into the help search in the Help menu.
