### ISSUE TITLE
Getting no responce when openning a .srt file

### ISSUE THREAD

**Issue by GloryAlex** [coteditor/CotEditor#1132]
## Environment (环境)

- CotEditor: 4.0.1 (455)
- System: macOS 版本11.0.1（版号20B29）
- Language: Chinese (Simplified)

## Short Description (简单描述)

When I use CotEditor to open a .srt file, it quickly use cpu to nearly 99% and getting no responsed. Ony way to slove it is force quit.

## Steps to Reproduce the Issue (重现问题步骤)

Just open any .chs.srt file. I upload which I use, which is Some Like It Hot(1959).
[download](https://drive.google.com/file/d/1VFBsp2Wr3dBXqmciGqvnmSOZJkzZmk0c/view?usp=sharing)

## Expected Result (期待结果)

Well, it is just 94kb, I think it could be some reason.

**Comment by 1024jp** [comment]
Hi, thank you for the feedback.

> Just open any .chs.srt file. I upload which I use, which is Some Like It Hot(1959).
> download

It seems this file cannot be downloaded without permission.
Could you upload it somewhere else?

**Comment by GloryAlex** [comment]
[srt.zip](https://github.com/coteditor/CotEditor/files/5682757/srt.zip)
sorry for not testing.

**Comment by GloryAlex** [comment]
I found something new. When I open it with coteditor at first, it works with no bug. But when I close coteditor and re-open this file with coteditor, it's getting no responce and only way is to force quit with acitivity manager.

**Comment by 1024jp** [comment]
Thank you for the test file and additional info!
I'll dig into it.

**Comment by 1024jp** [comment]
Sorry for my late reply. But thanks to various improvements in the latest versions of CotEditor, the file you uploaded here is now be able to be opened in CotEditor without freezing.
To open the file correctly, you maybe need to interpret the file in the specific file encoding (maybe Chinese (GB 18030)?).
