### ISSUE TITLE
Improvements to the (perceived) performance of syntax highlighting

### ISSUE THREAD

**Issue by rben01** [coteditor/CotEditor#1136]
## Environment

- CotEditor: 4.0.1 (455)
- System: macOS Version 11.1 (Build 20C69)
- Language: English

## Short Description

When opening large, non-plain-text files (e.g., a few MB large JSON file), CotEditor hangs while it attempts to syntax highlight the entire file. Ideally CotEditor would act more graceful when opening large files. Some ideas for improvements:

- When opening files above a certain size, disable syntax highlighting for the file until the user explicitly turns it on. So when opening my large JSON file, CotEditor would set syntax highlighting to "None" at first, but if I wanted to I could set it back to JSON.
- When opening files above a certain size, perform the syntax highlighting in a background thread. When it's ready to display, apply it to the (potentially updated) current document, then update the syntax highlighting again to take into account edits the user made since opening the file. Probably more complicated to implement but would be a better experience.

My current workaround for this issue is to change the file extension to .txt before opening the file and then to change it back afterwards, but this is subpar.

**Comment by 1024jp** [comment]
Hi, today, I finally found the solution to this long-standing issue! I'm now implementing it and on the next minor update, CotEditor 4.3.0, the time to highlight documents will reduce drastically and almost no rainbow cursor will appear.
According to trials on my environment, the current version takes more than 2 minutes to apply the colors (the process requiring the rainbow cursor) to an appx. 7MB document, but in the next version, it will be done in 1 second. The time doesn't include the parsing time; so it still takes time to highlight but the total time is definitely reduced significantly.
