### ISSUE TITLE
Anura(Dark) theme keeps light background when activated.

### ISSUE THREAD

**Issue by Antisunny** [coteditor/CotEditor#1139]
## Environment (环境)

- CotEditor: 4.0.1 (455)
- System: macOS Big Sur 11.1（Ver. 20C69）
- Language: Chinese (Simplified)

## Short Description (简单描述)

Switching to **Anura Dark** from a "light theme", the editor background is still light. But when switching from a Dark theme, such as **Dendrobates(Dark)**, **Solarized(Dark)** to to **Anura Dark** the background color turns dark. Seems Weird!

https://user-images.githubusercontent.com/2398514/103157503-4d52e980-47ee-11eb-91f9-65f4e596be56.mov

## Steps to Reproduce the Issue (重现问题步骤)

1. Goto Settings -> Appearances, in the theme box, select **Anura**,
2. then select **Anura (Dark)** ####
3. select **Classic**, then select **Anura (Dark)** ####
4. select **Solarized(Dark)**, then select **Anura (Dark)** ####

`####` marks the occurance.

## Expected Result (期待结果)

When select **Anura (Dark)**, the editor background turns dark. ありがとうございます

**Comment by 1024jp** [comment]
Hi, thank you for your report and sorry for taking long to start working on this issue.
Now, I've just fixed it.
So, the change will be shipped with the next version, which will be released this month.
