### ISSUE TITLE
Open CotEditor window without animation, or add that as a user option

### ISSUE THREAD

**Issue by amanvm** [coteditor/CotEditor#1140]
## Environment

- CotEditor: 4.0.1 (455)
- System: macOS Version 11.1 (Build 20C69)
- Language: English

## Short Description

When the editor window opens upon launching the application, it has an animation of expanding from a smaller size. In my humble opinion it adds a perceived delay, making the application appear to launch slower than it is capable of. As a programmer who is used to console editors that open in a split second, this animation is dissatisfying. If possible, please add an option to the application to control the launch behavior for user to select, or change the behavior so it opens without any animation. This will also be inline with the marketing of CotEditor that it is supposed to among the fastest editors out there.

## Steps to Reproduce the Issue

Launch the application: as you know it opens with an animation (as if expanding from a smaller size).

## Expected Result

The window should just appear without any animation/effects. This will improve the real/perceived launch time of application too.

**Comment by 1024jp** [comment]
This is the standard behavior in the macOS world, and therefore, I do not want to change. Sorry.

**Comment by amanvm** [comment]
@1024jp Sure I understand your opinion. Can you please point out where such edit can be made? I can change it for myself, and build it.

**Comment by 1024jp** [comment]
@amanvm Ok, you can change it by selecting __Animation__ from _Document Window_ to _None_ for document window object in DocumentWindow.storyboard in the interface builder.

<img width="1366" alt="Screen Shot 2021-01-01 at 11 32 53" src="https://user-images.githubusercontent.com/1165044/103432612-2a2c9d80-4c25-11eb-8bb5-29efd7f4063b.png">
