### ISSUE TITLE
複数置換の置換条件に日本語を入力する際の不具合

### ISSUE THREAD

**Issue by pneumoniae** [coteditor/CotEditor#1142]
## Environment (環境)

- CotEditor: 4.0.1 (455)
- System: macOS バージョン11.1（ビルド20C69）
- Language: Japanese

## Short Description (簡単な説明)

複数置換の条件に日本語を登録する際、入力中の・入力した文字が入力ボックス内に表示されない（半角英数字は問題なし）。
入力を確定すると表示される。

## Steps to Reproduce the Issue (不具合が発生したときに行っていた操作、または再現手順)

1. メニューから複数置換を選択
2. 右側編集エリアの追加 + ボタンをクリックし、新しい置換条件を追加
3. 置換条件を入力

## Expected Result (期待される挙動)

入力中の・入力した文字が入力ボックス内に表示される。

**Comment by 1024jp** [comment]
ご報告ありがとうございます。症状確認しました。
これは不具合ですので次バージョンまでに修正したいです。

**Comment by pneumoniae** [comment]
検証ありがとうございます。
修正よろしくお願いします。

**Comment by 1024jp** [comment]
こちらmacOS 11.1で新たに発生したmacOSシステム側のバグに由来するものでした。現在迂回策を考えており次リリースでは修正したものをお届けする予定ですが、まだ目処が立っていないので最長1ヶ月くらいかかるかもしれません（最近本業が忙しく、申し訳ない）。

**Comment by pneumoniae** [comment]
ご報告ありがとうございます。お手数おかけしますが、引き続きよろしくお願いします。

**Comment by 1024jp** [comment]
本件、あまり良い迂回方法がなく考えあぐねていましたが、
今日リリースされたmacOS 11.2にてシステム側で修正が入ったので、CotEditor側は特に手を入れないことにします。

あまり普段のようなスピード感のある対応ができなく申し訳ないですが、
これで解決とさせてください。
