### ISSUE TITLE
Multi-tab for open document

### ISSUE THREAD

**Issue by rpulikool** [coteditor/CotEditor#1143]
I really appreciate the light weight tool that you have created.

Can you please add the feature so if there are multiple files, they open as tab rather than new instance of coteditor

Regards,
-Rupesh

**Comment by 1024jp** [comment]
You can change the behavior in the Preferences > Window by setting "Prefer Tabs" to "Always".

<img width="660" alt="Screen Shot 2021-01-15 at 16 08 30" src="https://user-images.githubusercontent.com/1165044/104692806-ed47c700-574b-11eb-82c7-6c0133187727.png">

**Comment by rpulikool** [comment]
Can you please also let me know if there is an option for document selection tab on the left side

**Comment by 1024jp** [comment]
> Can you please also let me know if there is an option for document selection tab on the left side

Unfortunately, no. Sorry for that.

There is already a similar request on #1093 but not implemented. So, I just close this issue due to duplication.
