### ISSUE TITLE
Keybindings for Find & Replace options

### ISSUE THREAD

**Issue by ceciliacase** [coteditor/CotEditor#1144]
I'd love to be able to set up keybindings to set/unset (not toggle, please) the options:

- Regular Expression
- Ignore Case (especially this one!)
- In selection

I'd also love to have the option to force case sensitivity in regular expressions. I use (?i) all the time, but there doesn't seem to be an option to make it use case sensitivity. I'm aware that this is a function of the regex language you are using, but some have (?c) which would work great for me.

As always, amazing job. This program makes my transcription work possible.

**Comment by 1024jp** [comment]
> I'd love to be able to set up keybindings to set/unset (not toggle, please) the options:

This is a reasonable request and easy to implement. I'll do it in the next version.


> I'd also love to have the option to force case sensitivity in regular expressions. I use (?i) all the time, but there doesn't seem to be an option to make it use case sensitivity.

Doesn't work just turning on the "regular expression" and turning off the "ignore case" options?

**Comment by ceciliacase** [comment]
Thank you! I look forward to that feature.

And good question. And it will help, for sure. But I use lots of scripting
to insert complex regex search and replace strings and it would be nice not
to have to imitate a keypress. Using (?i) and (?c) within the regex ensures
that there won't be any timing issues.

Just so you understand my use case, I'm a transcriptionist. I spend a lot
of my time going through and fixing messy auto-transcription. I've built up
a library of search/replace functions to semi-automate the process. I can't
fully automate because I have to make decisions on whether to change them
myself, I can't just leave it to the regex, at least in a good many cases.

Anyway, my case is probably an outlier, and I suspect you're right that the
hotkeys will be usable in my situation. Just wanted to give you more
context. :)

Best Regards,

Cecilia Case
503-704-1640
