### ISSUE TITLE
Feature Request - Command to save all unsaved documents / 保存してないすべてのウインドウを保存、がほしいです

### ISSUE THREAD

**Issue by usaty** [coteditor/CotEditor#1146]
いつも有り難くつかわせて貰ってます。
自分のせいなんですが、名称未設定65とかなってきちゃいました。保存してないすべてのウインドウを保存、を実装していただけませんでしょうか。

**Comment by 1024jp** [comment]
回答が大変遅れて申し訳ないです。
バラバラに存在する複数の書類ウインドウを操作するコマンドというのはmacOSの世界ではあまり自然ではないので、不採用とさせてください。
なお同一のウインドウの中の複数の（タブ化された）書類については、#902にリクエストがあるのでそちらに引き継ぎます。
（採用を約束するものではありません。機能リクエストの整理のためです。）
