### ISSUE TITLE
Long documents are slow to load when mouse-scrolling

### ISSUE THREAD

**Issue by ethinethin** [coteditor/CotEditor#1147]
When I open a large file, if I scroll down with the mouse, the entire document is not loaded and I have to wait a moment for it to load. For example, when I load a 428 line file and scroll down quickly, it stops at line 202 and takes a moment to load, then it stops at 316 and takes a moment to load, then will scroll down to the EOF. Here is an example of the behavior:

https://user-images.githubusercontent.com/30166249/106394809-963d2580-63cc-11eb-8673-5fca59590966.mp4

This is happening on an Intel Macbook Pro (2015) with macOS Catalina (10.15.7). The issue does not happen with Cmd-down keyboard shortcut or function navigator dropdown.

**Comment by x13a** [comment]
Same here :(

**Comment by 1024jp** [comment]
I totally forgot to reply to this ticket, but this issue was resolved on CotEditor 4.2.0, which was released last month.
