### ISSUE TITLE
Find Next / Find Previous でのスクロール状態

### ISSUE THREAD

**Issue by ikuhiromorita** [coteditor/CotEditor#1148]
テキスト検索中に Find Next / Find Previous 機能を使って次/前のヒット場所を探す際、ハイライト部分がウィンドウの中心になるよう縦スクロールされるようになりました。
少し前までは、次のハイライト部分がウィンドウ内に表示されている場合はスクロールしなかったと記憶しています。

以前の動きの方が見やすかったと感じています。
動きを選択できるようにしていただけないでしょうか。
あるいは新しい動きのままでもスムーズにスクロールするようにしていただければ改善するかもしれません。

長いこと便利に使わせていただいております m(\_"\_)m

**Comment by 1024jp** [comment]
本件、レポートいただいてから着手まで時間かかっていましたが、変更済みましたので次バージョン（CotEditor 4.0.6）で対応します。

**Comment by ikuhiromorita** [comment]
対応ありがとうございます！
