### ISSUE TITLE
MATLAB code highlight issue 

### ISSUE THREAD

**Issue by teddychao** [coteditor/CotEditor#1149]
I am using CotEditor to develop some Matlab code. I just met an issue of code highlight for Matlab. It looks like the matrix transposition feature was not recognised here. Could I know if this would be an issue to be fixed in the future? Many thanks.
<img width="384" alt="Screenshot 2021-02-07 at 23 33 06" src="https://user-images.githubusercontent.com/3895146/107162678-d8ea9900-699c-11eb-8854-4424d295bb4a.png">

**Comment by 1024jp** [comment]
Sorry for my late answer. I close this issue because of the duplication of the existing issue #697.

**Comment by 1024jp** [comment]
This issue will be addressed in the next major update, version 7.0.0, which is scheduled to be released late 2026.
