### ISSUE TITLE
箇条書きリストや番号付きリストの自動入力

### ISSUE THREAD

**Issue by 55freak** [coteditor/CotEditor#1150]
macの標準メモアプリで箇条書きリストを作成する場合、
1つ目の箇条書きを入力し、エンターキーで改行すると、自動的に次の行も箇条書きリストになります。

CotEditorにはその機能はありますでしょうか？

P.S.開発ありがとうございます。毎日利用しています。

**Comment by 1024jp** [comment]
> CotEditorにはその機能はありますでしょうか？

この質問への回答となると「いいえ」です。
CotEditorはあくまでプレーンテキストのエディタを志向しておりそのような機能についてはアプリケーションレベルでは対応しない方針を取っております。ご了承ください。
