### ISSUE TITLE
Use Tab Character for Indentation

### ISSUE THREAD

**Issue by MattMicheletti** [coteditor/CotEditor#1152]
Hello,

How does one set the preferences for the entire editor, in all cases, at all times, to always use the tab character for indentation? I cannot seem to find the setting for this or the combination of settings to get this behavior.

Please and thanks.

**Comment by 1024jp** [comment]
Hi.
Try disabling "Expand tabs to spaces" in Preferences > Edit > Indentation.
In addition, you may also need to disable "Detect indent style on document opening" to avoid changing the indentation characters to spaces automatically depending on the file contents.

<img width="682" alt="Screen Shot 2021-02-15 at 16 33 33" src="https://user-images.githubusercontent.com/1165044/107917646-a13aad00-6fab-11eb-84ba-9dd1b44291e3.png">

**Comment by MattMicheletti** [comment]
Disabling "Detect indent style on document opening" looked like the culprit. Once that was off, that looks like it fixed it. Thanks. :)
