### ISSUE TITLE
Script menu icon in Help window is invisible when system is in dark mode

### ISSUE THREAD

**Issue by quark67** [coteditor/CotEditor#1159]
## Environment

- CotEditor: 4.0.1 (455)
- System: macOS Version 11.2.1 (assemblage 20D74)
- Language: French

## Short Description

Script menu icon is black under dark gray background (system in Dark mode):
![image](https://user-images.githubusercontent.com/9338576/111099816-99d4d800-8546-11eb-92fa-18dd1f285124.png)

## Steps to Reproduce the Issue

Be in Dark mode (System preference, General, choose Dark mode for appearance).
Go to Help menu, choose CotEditor Scripting Guide, then About Scripting. The CotEditor Help Window is displayed.

## Expected Result

Script menu icon is white under dark gray background (System in Dark mode).

**Comment by 1024jp** [comment]
Thank you for pointing it out!
It'll be fixed in the next version.
