### ISSUE TITLE
A Japanese word appear in menu Format> Font  under French System

### ISSUE THREAD

**Issue by quark67** [coteditor/CotEditor#1160]
## Environment

- CotEditor: 4.0.1 (455)
- System: macOS Version 11.2.1 (assemblage 20D74)
- Language: French

## Short Description

Missing localization in French in the menu Format > Font > Ligatures. The word Ligatures is in Japanese.

Under a French system:
![image](https://user-images.githubusercontent.com/9338576/111101346-fa194900-8549-11eb-8cc1-bd69a6b557d0.png)

For comparison, the same under an English system:
![image](https://user-images.githubusercontent.com/9338576/111101393-14532700-854a-11eb-86a2-74d2dcc679cf.png)

## Steps to Reproduce the Issue

Use a French system, and choose the menu "Format" > "Police". The Japanese word appear in the sub-menu.

## Expected Result

The Japanese word must be replaced by the French word for the English "Ligatures"; it's also "Ligatures" in French.

**Comment by 1024jp** [comment]
Oh, thank you for pointing it out.
It'll be fixed in the next version.
