### ISSUE TITLE
Improve R style

### ISSUE THREAD

**Issue by nuno-agostinho** [coteditor/CotEditor#1161]
Hey, @1024jp! I have two requests that are quick fixes:

1. The default file extension for R files is `.R` (not `.r` as found in the R settings in CotEditor). CotEditor's extensions are case-sensitive so it does not automatically detect `.R` files as R. I think there are at least two alternatives here:
    - Put both `r` and `R` in the extensions for R (that is what I do in my custom settings and it works perfectly).
    - Allow extensions to be case-insensitive (I am not sure if this makes sense for other languages...)
2. Include R code sections in the outline menu (see below).

As according to this support document on [R code sections](https://support.rstudio.com/hc/en-us/articles/200484568-Code-Folding-and-Sections):

> any comment line which includes at least four trailing dashes (-), equal signs (=), or pound signs (#) automatically creates a code section. For example, all of the following lines create code sections:
>
> `# Section One ---------------------------------`
> `# Section Two =================================`
> `### Section Three #############################`

As such, the outline menu should include the following values:
| Regex string | Description | Menu title pattern | Bold |
|--------------|----|---|--|
| `^#+[\t ]*(.*?)[\t ]*(-\|=\|#){4,}` | `section` | `$1` | Yes* |

\* In **Bold** to easily differentiate sections from R functions (similarly to the behaviour of the outline menu of RStudio).

Feel free to ask for more information, if you need! Cheers!

**Comment by 1024jp** [comment]
Thank you for the suggestion! I'll implement it in the next version.

**Comment by 1024jp** [comment]
Today, I updated the bundled R style based on your suggestion. It'll be shipped with the next version, CotEditor 4.0.3; I'm though not sure when I'll release it).

In terms of the case-insensitivity on the file extension, I changed the file extension check process on the syntax style detection to match also case-insensitive, but prioritize one matching case if multiple styles match.

**Comment by nuno-agostinho** [comment]
Great, thanks @1024jp! 😄
