### ISSUE TITLE
Feature suggestion: command palette

### ISSUE THREAD

**Issue by slavaschmidt** [coteditor/CotEditor#1162]
The CotEditor is already quite awesome but could you please consider adding the 'command palette' feature like in sublime text and vs code at some point? This feature is incredibly useful. Thank you!

**Comment by prc1212** [comment]
Just FYI, [Paletro](https://appmakes.io/paletro) works extremely well with CotEditor. No affiliation, just a happy user of both apps.

**Comment by 1024jp** [comment]
CotEditor implemented the Quick Action bar on version 4.7.0, which was released on 9th Dec, 2023.
You can launch it with the Command-K shortcut.
I suppose this function is similar to the one you requested.
I just missed closing (or mentioning) this ticket when I released 4.7.0.
