### ISSUE TITLE
テキストを選択状態で ⌘F した際はそのテキストが入力された状態で検索ウィンドウが開いてほしい

### ISSUE THREAD

**Issue by hiruandon** [coteditor/CotEditor#1163]
類似機能で「選択部分を検索に使用(⌘E)」がありますが、
「テキストを選択状態で ⌘F した際はそのテキストが入力された状態で検索ウィンドウが開く」ほうが使い勝手がいいです。
⌘E の場合、下記 3 がワンステップ多いイメージです。
1. 検索したいテキストを選択しておく
2. ⌘F で検索ウィンドウを開く
3. ⌘E で選択部分を検索に使用する

よろしくお願いいたします。

**Comment by 1024jp** [comment]
個人的なユースケースとしては理解しますが、macOSの標準的な振る舞いとかけ離れるため不採用とさせてください。

なお、明示的に検索パネルを出す必要がない場合は、⌘E → ⌘G でそのまま選択文字列での検索に移れます。

**Comment by hiruandon** [comment]
@1024jp 
ご確認ありがとうございます！
macOS の振る舞いまで至らず失礼いたしました。
不採用承知いたしました。
検索パネルは欲しいので上記ステップで利用させていただきます。
