### ISSUE TITLE
"Select word" should resume on top of document

### ISSUE THREAD

**Issue by nuno-agostinho** [coteditor/CotEditor#1167]
Hey again @1024jp! I would like to ask for the command "Select word" to select the first instance at the top of the document, after reaching its end (like Sublime Text does). For instance, take this image:

![Screenshot 2021-04-08 at 11 55 14](https://user-images.githubusercontent.com/3199157/114015144-49a91700-9861-11eb-8f8a-242860fbd295.png)

It would be nice if continuing to use "Select word" would select the next instance at the top of the document.

Cheers!

* CotEditor: 4.0.2 (457)
* System: macOS 11.2.2 (20D80)
* Language: English

**Comment by 1024jp** [comment]
Hi. Thank you for the nice suggestion.
I've just implemented it.
The change will be applied to the next version.

**Comment by nuno-agostinho** [comment]
Hey @1024jp, thanks! I just want to say that CotEditor is my favorite code editor and I love how you listen and improve the app based on user feedback. Keep up the great work! ❤️
