### ISSUE TITLE
British English Localisation

### ISSUE THREAD

**Issue by anosidium** [coteditor/CotEditor#1169]
I am British and I would like to contribute by localising it in British English. CotEditor English localisation is in American English. Would you be open to that?

**Comment by 1024jp** [comment]
@anosidium Sorry for my late reply. Today, @AlexNewson made a PR adding British English localisation. The change will be shipped in with CotEditor 4.1.0, which will probably be released pretty soon. Feel free to make PRs if you find some more expressions to localise.
