### ISSUE TITLE
Issue with save permission warnings

### ISSUE THREAD

**Issue by ceciliacase** [coteditor/CotEditor#1170]
I get the attached message fairly often (usually twice or three times a day). It happens when I am NOT trying to save the file. If I then save the file, CotEditor doesn't have any trouble saving; it saves without any errors.
<img width="434" alt="Screenshot2021-04-22 9:07:06 AM" src="https://user-images.githubusercontent.com/887721/115748049-ab31b100-a34a-11eb-8239-460745094716.png">

**Comment by gregarios** [comment]
I've seen this a few times too. Running Big Sur.

**Comment by ceciliacase** [comment]
Ah good point, I should add context, too. I'm running Catalina. I'm running Version 4.0.2 (457) of CotEditor.

**Comment by 1024jp** [comment]
Hi, thank you for the report.
One question. Do you enable the Autosaving with Versions in CotEditor Preferences > General?

**Comment by ceciliacase** [comment]
No, I don't have that enabled. I've found that it slows the program to the
point of making it unusable if I enable that feature.

Best Regards,

Cecilia Case
503-704-1640

**Comment by 1024jp** [comment]
Ok, thank you. I'm not sure, but it can be possible that something goes wrong in the process only for when autosaving is off. I'll look into it.

**Comment by 1024jp** [comment]
Aha, reproduced! Not 100%, but this must be related to the backup process in case of a sudden crash without autosave. Actually, CotEditor just uses a Cocoa feature for it. However, it seems like Cocoa's legacy backup feature broke in the recent systems. I need to find a workaround.
cf. https://stackoverflow.com/questions/62027942/permission-denied-when-autosave-nsdocument

**Comment by ceciliacase** [comment]
Okay, well so far I haven't seen the message, but now it's acting slow and buggy like it did when I used to have the autosave on. The preference is showing as unchecked, but I swear it's the exact same slow typing issue with large files that I would see when autosave was on. I.e. it gets worse the longer I work on the file.

**Comment by 1024jp** [comment]
@ceciliacase Thank you for the feedback.
Hmm, that's weird because I did not change such as saving timing or frequency. Actually, CotEditor saves your document while typing even when the Autosaving is disabled (When the autosaving is disabled, CotEditor doesn't overwrite the actual document but makes a backup in the user container). This feature exists for a long time.
Well, I study the source code again and add some measures to the next version to solve the slowdown.
Feel free to report further issues.

**Comment by ceciliacase** [comment]
I hate to say it, but I just got the error message again. :(

**Comment by 1024jp** [comment]
@ceciliacase Thank you for the following up and sorry that the issue still exists.

However, good news. I finally found the cause of this warning. I've just changed the backup file URL creation timing and the issue must be solved.
I'll ship the next version soon.

**Comment by 1024jp** [comment]
I've just shipped CotEditor 4.0.5.
Let me know if the issue still exists (or any new related issue arises).
