### ISSUE TITLE
Find AllでRegular Expressionで\tでの結果に対して元データの対象文字(\t)が強調表示されない。

### ISSUE THREAD

**Issue by nomprex** [coteditor/CotEditor#1172]
## Environment

- CotEditor: 4.0.2 (457)
- System: macOS Version 10.15.7 (Build 19H524)
- Language: English

## Short Description
掲題の通り。本課題の後半に添付したデータにて発生。

## Steps to Reproduce the Issue
1. 本課題後半に添付したデータを貼り付ける。
2. Find & ReplaceダイアローグでRegular Expressionにチェックする。
3. Find String : \tでFind All。
4. Find & Replaceダイアローグ内の結果（固定\ta0q....）の\tは正常に強調表示されるが、元データの\tは強調表示されない。

## Expected Result
以下の添付データの固定\ta0q....の\tが強調表示される。
-----------------------------------------------------------------------
増税前に契約がないと考え増税後単価で固定	a0q0K000007XJsIQAW
増税前に契約がないと考え増税後単価で固定	a0q0K000007XJskQAG
増税前に契約がないと考え増税後単価で固定	a0q0K000007XJspQAG
増税前に契約がないと考え増税後単価で固定	a0q0K000007XJsuQAG
増税前に契約がないと考え増税後単価で固定	a0q0K000007XJsRQAW
増税前に契約がないと考え増税後単価で固定	a0q0K000007XJrTQAW
増税前に契約がないと考え増税後単価で固定	a0q0K000007XJszQAG
増税前に契約がないと考え増税後単価で固定	a0q0K000007XJt4QAG

**Comment by 1024jp** [comment]
対応遅く申し訳ないです。
こちら手元で再現できず状況が理解しきれていません。
スクリーンショットいただけないでしょうか？

**Comment by nomprex** [comment]
返信ありがとうございます。
上記データの本課題コメントに貼り付けた際に"...で固定"と"a...."の文字列の間の部分がスペースになったようですので、
以下の操作をお願いいたします。

 1. 初回のコメントに貼り付けたテキストデータをCotEditorに貼り付けて、スペース(\N{SPACE})をタブ(\t)に置換。
 2. Find & ReplaceダイアローグでRegular Expressionにチェックする。
 3. Find String : \tでFind All。
 4. Find & Replaceダイアローグ内の結果（固定\ta0q....）の\tは正常に強調表示されるが、元データの\tは強調表示されない。

<img width="1370" alt="Pasted_Image_2021_05_31_15_17" src="https://user-images.githubusercontent.com/13220783/120150595-35144a00-c226-11eb-9fad-e5f20ac37a7a.png">

**Comment by nomprex** [comment]
/hでも同じでした。
元テキストの強調表示はされていて、強調表示の描画部分の幅がダイアローグの結果に対して小さすぎるのかもしれません。
ダイアローグの結果部分の行をクリックすると元テキスト部分も黄色い矩形で一瞬ハイライトされるので。
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/13220783/120155449-ce922a80-c22b-11eb-804a-94a74449c0d2.png">

**Comment by nomprex** [comment]
\Hで検索した結果の強調表示もダイアローグの結果と元データで異なりますが、
元データの強調表示のみ改善いただけると幸いです。
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/13220783/120156144-a48d3800-c22c-11eb-825a-63a22c1ff6d8.png">

**Comment by 1024jp** [comment]
状況理解しました。フォローありがとうございます。

ご指摘の通り本件はタブ幅が大変狭い状況のためハイライトが目視できない状況であり、これは「仕様です」というお答えになってしまいます。テキストエディタにおけるタブの取り扱い（スペースの取り方）としてこれは正常なものであり、ハイライトについても使用しているAPIや描画パフォーマンスの関係もあり、このケースだけのためにこれを超える対応は難しいです。ご了承ください。
