### ISSUE TITLE
Quit after all windows are closed

### ISSUE THREAD

**Issue by sohate** [coteditor/CotEditor#1175]
Hello! It would be great if CotEditor would quit on its own if all application windows are closed. Thanks!

**Comment by 1024jp** [comment]
CotEditor is already designed to quit itself under the following conditions:
1. All windows are closed.
2. __The application, namely CotEditor, goes background__. In other words, another application becomes active.

**Comment by sohate** [comment]
> CotEditor is already designed to quit itself under the following conditions:
> 
> 1. All windows are closed.
> 2. **The application, namely CotEditor, goes background**. In other words, another application becomes active.
> 
> Both conditions must be satisfied.

Open .txt with with CotEditor -> closing .txt file (cmd+w) -> open another app -> Coteditor is still running in background (no windows open).

**Comment by 1024jp** [comment]
Oh.., that's true. I realized that I accidentally removed the flag for that on CotEditor 4.0.0.
Thank you for pointing it out. I appreciate.
This behavior will be reverted in the next version so that the app can terminate with no windows.

**Comment by zcysxy** [comment]
> CotEditor is already designed to quit itself under the following conditions:
> 
> 1. All windows are closed.
> 2. **The application, namely CotEditor, goes background**. In other words, another application becomes active.
> 
> Both conditions must be satisfied.

Hi, does this feature break on 4.1.5? When I closed all windows and switch to another application, CotEditor stays in the dock.
