### ISSUE TITLE
Optimize outline for Swift language

### ISSUE THREAD

**Issue by rijieli** [coteditor/CotEditor#1176]
Hi

In swift language, If a function contains access control syntax, it won't show on outline.

```
func foo() {} // show in outline panel
public func bar() {} // not in outline panel
```

Can cot optimize for this situation, the link below show swift access control syntax
https://docs.swift.org/swift-book/LanguageGuide/AccessControl.html

Thank you
Roger

**Comment by 1024jp** [comment]
Thank you for pointing it out. The Swift style will be updated in the next version.
