### ISSUE TITLE
Syntax Highlighting for Objective-C

### ISSUE THREAD

**Issue by paulduggan** [coteditor/CotEditor#1177]
I see Swift syntax but no Objective-C. 
I assumed Objective-C would be included as it's the predecessor to Swift.

Objective-C syntax would be helpful as my projects haven't moved to Swift.

Thanks for listening

**Comment by 1024jp** [comment]
I close this just because of duplication. Refer the previous discussion in #990.

**Comment by Lessica** [comment]
Objective-C is still used in many places. :-(

**Comment by LeoNatan** [comment]
Hello,

For anyone interested, I’ve recreated the C, C++ & Objective-C syntax, you can find it here:
https://github.com/LeoNatan/CotEditor-ObjCSyntax

Thanks
