### ISSUE TITLE
Syntax highlighter doesn’t recognize exponential notation numbers

### ISSUE THREAD

**Issue by da2x** [coteditor/CotEditor#1178]
## Environment

- CotEditor: 4.0.3 (459)
- System: macOS Version 11.3.1 (Build 20E241)
- Language: English

## Steps to Reproduce the Issue

1. Open a new JavaScript or Ruby document† and type these numbers on a line each: 1000000, 1e6, 1E6, and 1e+6.

† Probably affects more languages, but I only tested these two.

## Expected Result

All four numbers should be styled the same way by the syntax highlighter.

## Actual result

Only the first notation is styled as a number.

**Comment by 1024jp** [comment]
Thank you for pointing out.
I've just updated some syntax style definitions to highlight exponential notation numbers more correctly.
The change will be shipped with the next CotEditor 4.0.4.
