### ISSUE TITLE
incorrect expression

### ISSUE THREAD

**Issue by xiaochong-bu** [coteditor/CotEditor#1186]
## Environment (环境)

- CotEditor: 4.0.5 (463)
- System: macOS 版本11.4（版号20F71）
- Language: Chinese (Simplified)

## Short Description (简单描述)

 “付与执行权限”  is not correct, it should be replaced by“赋予执行权限”.

## Steps to Reproduce the Issue (重现问题步骤)

When save file.

**Comment by 1024jp** [comment]
Thank you for the suggestion. Sounds correct.
However, I am not Chinese native, I'd like to let the current CotEditor's localizer review it.

How do you think, @onevcat?

**Comment by onevcat** [comment]
@xiaochong-bu Thanks for opening this.

They (`付与` and `赋予`) are similar but slightly different. I am against changing it to `赋予`.

`付与` is more about the action "give": anyone can just give anything to another one. It is a normal words without strong motion. While `赋予` is much more serious, it is more about a ritual, say the history will `赋予` someone a mission. (歴史的使命). So it is not quite fit here for a permission.

But indeed, there is a better word, `授予`, exactly means "prompt the permission". @xiaochong-bu  Do you think it would be better?

**Comment by onevcat** [comment]
And try to search the phase, you can find [授予权限](https://www.google.com/search?client=safari&rls=en&q=%E6%8E%88%E4%BA%88%E6%9D%83%E9%99%90&ie=UTF-8&oe=UTF-8) has the most results, and widely used by companies like Apple, Huawei, Facebook and much more.

**Comment by xiaochong-bu** [comment]
Well, you are the boss.
But I suggest a real Chinese people to check it out and listen to his opinions. In Chinese,授予 is often used to authorize someone，means “grant”. Maybe you just want to say “Make the file executable” I think. If so, 添加可执行权限 or 给文件添加可执行权限 is better.

**Comment by onevcat** [comment]
> Well, you are the boss.

No one is the boss and we are discussing to find a better translation.

> But I suggest a real Chinese people to check it out and listen to his opinions. 

Sorry but I am a real Chinese people. 😂

> In Chinese,授予 is often used to authorize someone，means “grant”.

I am sorry that I missed the context here. 

Yes, you are right. `授予` here does sound strange. It is not a thing you grant (such as a service wants to use your location or camera). You just add an attribute to a file and let it executable.

I checked the original version of this sentence, it is "Give execute permission": it is a "give" instead of an "add" at last. 

In fact, I agree that "Adds execute permission" or even "Make executable" would be much natural here. If so, we can translate it to "添加可执行权限" and it matches perfectly. @1024jp What's your opinion?

**Comment by xiaochong-bu** [comment]
无意冒犯你，哥们儿。
In addition，MENU "查找"->"选择全部查找到的匹配"，you mean “选择全部查找结果”？

**Comment by onevcat** [comment]
Hi,

Again, this is basically a respecting to the original sentence: "Select All Find Matches". I guess a more polished translation for it, can be "选择所有匹配项" (which is also used in Visual Studio Code). I am glad if "选择所有匹配项" can be used, but “选择全部查找结果” is a bit far from the original word "Matches".

**Comment by KelvinQQ** [comment]
借楼提问一下，总是遇到让我去授予权限，说文件被锁定，但是我去检查了文件的状态，并没有被锁定，也是读写权限，很奇怪。
CotEditor: 4.2.1 (505)
System: macOS 版本12.1
Language: Chinese (Simplified)
<img width="265" alt="image" src="https://user-images.githubusercontent.com/4057123/168537851-abd3492d-fa27-43a4-94f3-27b3a5067f48.png">

**Comment by 1024jp** [comment]
Sorry, I've left it for a long time.
I close this issue since the text was updated in PR #1420.
