### ISSUE TITLE
Feature Request - Text Filtering

### ISSUE THREAD

**Issue by IanAtSalt** [coteditor/CotEditor#1191]
One of my primary uses for a text editor is viewing logs. Often I'll need to correlate non-consecutive lines based on something like a transaction ID. I'd like to be able to completely hide any lines that do not match a given string. This is ALMOST implemented when I do a search and FIND ALL, but the lines in that little window are truncated.

**Comment by 1024jp** [comment]
For such (minor) usage, I prefer creating a script rather than adding a new feature to CotEditor itself.

**Comment by lolbat** [comment]
Select the document and then under the Find menu select `Select All Find Matches`

I am doing it right now for some files

**Comment by IanAtSalt** [comment]
I think the previous suggestion was probably the right way to go with this.
The documentation for scripting plugins was not super clear to me at first.

Since I can use python, it is easy to pull the document text into a buffer,
popup a search window, search the buffer, and replace the document text
with matching lines. Then when I close out, the original buffer is restored
to the document.

**Comment by foss-** [comment]
TextMate has solved this by allowing users to just `cmd+a` the search results. This can then be copied to a new file.
In CotEditor this is not possible currently. Maybe that would be a nice workaround to implement and resolve this feature request?

**Comment by 1024jp** [comment]
@foss-  CotEditor already has the “Select All Matches” in the Find menu. The command has no keyboard shortcut by default, but you can assign any key combination in Key Bindings settings.

**Comment by foss-** [comment]
Hm, this seems to behave differently than TextMate. In a log after pressing `cmd+f` and entering a search term, results are highlighted in CotEditor. Find all shows the matching strings at the bottom of the Find & Replace dialog.

Were you refering to menubar > Find > Select all Find Matches? When I do that, all matches are selected in CotEditor. But as expected only that term is copied when I copy that to a new file, so that is not helpful.

Is there a way to copy all lines with a matching search term?

**Comment by 1024jp** [comment]
@foss-  
Then, maybe:
1. Find > Select All Find Matches
2. Edit > Select Line
3. Edit > Copy

And now I understand what you suggest. I miss the words "the search results". And, I think it's not a bad idea. Let me think if I can easily implement it.

**Comment by 1024jp** [comment]
> ... allowing users to just `cmd+a` the search results. This can then be copied to a new file.

Ok, I've just implemented it. The feature will be shipped with CotEditor 4.6.0, which will be released soon this month.



![Screen Recording 2023-09-18 at 22 05 46](https://github.com/coteditor/CotEditor/assets/1165044/58a9c15d-d85f-48d1-bc22-0d131c624ad9)

**Comment by foss-** [comment]
Should this be in Version 4.6.0-beta.3 (585) already?

**Comment by 1024jp** [comment]
> Should this be in Version 4.6.0-beta.3 (585) already?

Not yet. I'll release the stable version of 4.6.0 next week.

**Comment by foss-** [comment]
Verified in Version 4.6.0-rc (587)
This is a very welcome change. Thanks so much.

**Comment by 1024jp** [comment]
@foss- It's my pleasure. Thank you for your quick check and feedback.
