### ISSUE TITLE
[Feature Request] Scripts in the Toolbar

### ISSUE THREAD

**Issue by FelipeRearden** [coteditor/CotEditor#1194]
Hello friends!

I’d like to make a feature request:

In [DEVONThink](https://www.devontechnologies.com) there is an option to show an AppleScript in the Toolbar 
![Screen Shot 2021-07-14 at 07 17 51](https://user-images.githubusercontent.com/85180696/125605849-7aec3ef8-af7f-40ea-b85b-f77801f25bec.png)

To do this, there is a folder in the `Script` menu called `Toolbar`.
- if you save a .scpt in this folder, automatically the script appears in the toolbar 

![Screen Shot 2021-07-14 at 07 08 46](https://user-images.githubusercontent.com/85180696/125605950-6a576180-2291-42fb-b89a-7a99e0a98a95.png)

![Screen Shot 2021-07-14 at 07 09 32](https://user-images.githubusercontent.com/85180696/125605976-e25ff144-5a89-4c81-92dd-3c85e700bfca.png)

This feature would be amazing for CotEditor as well :)

Thanks for reading this and have a great day!

**Comment by 1024jp** [comment]
Thank you for the feedback.
Interesting. However, adding such a user-specified function as a Toolbar item might not be a proper design in the macOS world. Therefore, I'd like to reject your request. Sorry for that.
