### ISSUE TITLE
Syntax highlitght: Gemtext

### ISSUE THREAD

**Issue by ghost** [coteditor/CotEditor#1197]
Hi! First of all, thanks for the good job.

I have a (I think) easy feature request. It would be nice if CotEditor had support for Gemtext syntax highlight.

[It is explianed here](https://gemini.circumlunar.space/docs/gemtext.gmi). 

It is similar to basic MarkDown but simpler. It only have # headers (just three levels), => links, > quotes and ```preformated text. 

I wold do it myself but I'm unable to. I tried to duplicate Markdown highlighter and modify it, but I don't understand the strings. 

Thank you for your attention!

**Comment by 1024jp** [comment]
Hmm, I feel Gemtext is not so popular yet to bundle its syntax style to CotEditor.app officially although the grammar looks easy to support.

**Comment by 1024jp** [comment]
I close this request since Gemtext is still not popular enough to bundle to CotEditor.app.
