### ISSUE TITLE
Substitution using a Name-Captured Regex fails. 

### ISSUE THREAD

**Issue by Boxserman** [coteditor/CotEditor#1200]
When using the convention of named capture, 

 `(?<name>regexfoo)`

And then attempting a substitution using the substitution 

`${name}`

The matches are substituted with the literal 

`{name}`

When they should be substituted with the content matched by the regex,

> regexfoo

Therefore the application is not performing according to requirements.     

Reference: 
[My Initiated Discussion on 'Flavors of Regex that CotEditor Supports](https://github.com/coteditor/CotEditor/discussions/1199#discussion-3492240)

**Comment by 1024jp** [comment]
I close this issue because on the [reason I've written in #1199](https://github.com/coteditor/CotEditor/discussions/1199#discussioncomment-1187775). This is Apple's API side matter.

**Comment by Boxserman** [comment]
> I close this issue because on the [reason I've written in #1199](https://github.com/coteditor/CotEditor/discussions/1199#discussioncomment-1187775). This is Apple's API side matter.

Can you confirm whether there is a limit of using the numerical substitution reference ($n) with numbers in the range of 1..9?  

If there is this limitation, please let me know if it is a CotEditor issue or an Apple one?  

Thanks.
