### ISSUE TITLE
Line-comment breaks comment and string parsing for subsequent line

### ISSUE THREAD

**Issue by maxxk** [coteditor/CotEditor#1201]
Line-comment on one line breaks parsing of the comments and strings on the first character of a subsequent line.

Example 1 (Python):
```python
#!
# (this line is not highlighted as a comment)
x# (and if you add a symbol in between, it will be highlighted)
```

![Screen Shot 2021-08-02 at 18 55 26](https://user-images.githubusercontent.com/1191859/127889749-38596fa3-03ac-4ed2-89cd-fa0dd9b00fc0.png)

Example 2 (Swift):
```swift
// comment
// non-comment
```

![Screen Shot 2021-08-02 at 18 56 26](https://user-images.githubusercontent.com/1191859/127889944-130013a9-bf67-4ebd-b7ce-71e0c757fff4.png)

P.S. Thank you for your work, CotEditor is very good.

**Comment by 1024jp** [comment]
Thank you for the report. This is definitely a bug I need to fix.
