### ISSUE TITLE
Version 4.0.6 does not have a `.dmg` file released

### ISSUE THREAD

**Issue by singularitti** [coteditor/CotEditor#1203]
This makes it harder for me to push a new version of `coteditor` to [Homebrew Cask](https://github.com/Homebrew/homebrew-cask).

**Comment by 1024jp** [comment]
Sorry for that.
After releasing on the MAS, I realize that I need to do some special treatment only for the non-AppStore version for this CotEditor 4.0.6. And it is not yet done... Let me have time.

**Comment by 1024jp** [comment]
Sorry for taking the time. Now, I've just released the non-AppStore version CotEditor 4.0.6.
