### ISSUE TITLE
Converting encoding with AppleScript

### ISSUE THREAD

**Issue by tatsy-ymj** [coteditor/CotEditor#1206]
### Description

I try to change line ending and encoding with the following AppleScript (to UTF-8 and LF).

```
tell application "CotEditor"
	tell front document
		set line ending to LF
		convert to "UTF-8" with lossy
	end tell
end tell
```

It changes line ending successfully.
However, it returns result "false" and doesn't convert to "UTF-8".
Why can't it convert to "UTF-8"?

### To Reproduce

1. Open a text file.
2. Run the preceding script.

### CotEditor version

4.0.6

### macOS version

macOS 11.5.2

**Comment by 1024jp** [comment]
Short answer: The encoding name for this command must be in a localized encoding name. So, for UTF-8, you need to set "Unicode (UTF-8)"

Long answer: The above is the current implementation for text encoding conversion with AppleScript.
However, I feel this is not a good design because it depends on the user's language setting. I'll change it somehow in the next version.

**Comment by tatsy-ymj** [comment]
Thanks! The script works!
However, the localized encoding name was "Unicode (UTF-8) "(it needs a space at the end), not "Unicode (UTF-8)"... :smile:

> I'll change it somehow in the next version.

I'm counting on it! The current specification is a bit tricky.

**Comment by 1024jp** [comment]
I've changed the implementation. From the next version on, `convert` and `reinterpret` commands also accepts an IANA charset name that is always the same regardless of the localization.

**Comment by tatsy-ymj** [comment]
Is there any way to convert from "Unicode（UTF-8）BOM付き" to "Unicode（UTF-8）"?
When I set charset as "UTF-8" or "Unicode（UTF-8）", it doesn't work.

**Comment by 1024jp** [comment]
Aha, currently, there isn't such an API in AppleScript.
I need to implement it additionally.
I'll try it in the next version.

**Comment by 1024jp** [comment]
Created a new ticket for your additional request as my reminder #1210.

**Comment by 1024jp** [comment]
In the next CotEditor 4.1.0, new parameter and option about BOM will be added. ref. #1210
