### ISSUE TITLE
保存時に「このファイルは、別のアプリケーションによって変更されました。」が頻発する

### ISSUE THREAD

**Issue by shiro-t** [coteditor/CotEditor#1209]
### Description

macOS を Mojave より Big Sur にアップグレードして以降、ファイルの保存時に「書類 xx を保存できませんでした。このファイルは、別のアプリケーションによって変更されました。」のパネルが表示され、"このまま保存"を押すまで保存されないことが頻発しております。

環境: 
MacBook Pro (13inch 2020) : macOS Big Sur (11.5.2)
CotEditor : MacAppStore より入手、現在 4.0.6
OneDrive : 21.160.0808

以下 To Reproduce に記載の通り、OneDrive にて同期を取っているフォルダの中のテキストファイルのため、OneDrive 側の挙動にてファイルの属性か何かに変化があり、そのため該当のパネルが表示されるのではないかと思われます。
ただ、以前 Mojave を使用していた頃(1ヶ月ほど前)には生じておらず、macOS のアップグレード以降から頻発している次第です。

macOS や他ソフトの絡む事象のため CotEditor 側での対処は難しいのかも知れませんが、ご確認を頂けますと幸いです。

### To Reproduce

1. OneDrive ないしは OneDrive for Business により同期が取られているフォルダ内にテキストファイルを作成する
2. テキストファイルに対して、編集と保存を何度か繰り返す
3. 数度目に「書類 xx を保存できませんでした。このファイルは、別のアプリケーションによって変更されました。」が発生する

### Expected behavior

1. 特にパネルが表示されることなく保存される

### CotEditor version

4.0.6

### macOS version

macOS Big Sur (11.5.2)

### Additional context

設定の一般: 書類の保存にて「オートセーブとバージョンを有効にする」のチェックの有無にかかわらず、どちらの状態でも事象は発生します。
「書類が他のアプリケーションによって変更されたとき:」については「CotEditor の編集内容を保持」を設定しております。

**Comment by 1024jp** [comment]
わかりやすいご報告ありがとうございます（Additional contextは大変助かりました）。基本的にはAppleが提供するフレームワーク内での問題でCotEditor実装部分ではない現象になりますね。
ちょっと手元で再現できなかったのでなんとも言い難い部分もあるのですが、すぐに原因特定→修正とはいかなそうです。
もう少し調べてみます。

**Comment by 1024jp** [comment]
メモ：この辺全部同根の問題っぽいです。
- https://answers.microsoft.com/en-us/msoffice/forum/all/onedrive-cannot-edit-pdfs-anymore-on-osx-file-has/f82c50b2-1a5c-477a-9f47-27bb4197188e
- https://onedrive.uservoice.com/forums/913525-onedrive-on-mac/suggestions/36763975-the-error-message-at-file-on-demand-for-iwork-apps
- https://intellij-support.jetbrains.com/hc/en-us/community/posts/360006396420-Xcode-Workspace-has-been-modified-by-another-application-

**Comment by shiro-t** [comment]
ご連絡ありがとうございます。

OneDrive の方は調べたつもりでしたがかなり抜けていたようです。すみません。
ここまでの話よりこれは CotEditor 側の問題ではなく、OneDrive の事象でマイクロソフトの修正を待つべきと承知しました。

おさわがせしてすみません。

**Comment by 1024jp** [comment]
Microsoftか、もしくはAppleのフレームワーク側の問題に思えるので、そのどちらかの対応を待ちたい気持ちです。
CotEditorのファイル管理周りのソースも改めてみてみたのですが、
みた限りは原因となるところや迂回方法は思い浮かばず。
OneDriveは私も使用しているので今後同様の状態が再現したら改めて見てみます。
一旦取り下げいただきありがとうございます。

**Comment by shiro-t** [comment]
Closed なチケットへの報告ですみません。

昨日(2/20)、mac OS を BigSur (11.6.4) から Monterey (12.2.1)へアップグレードを行ったところ、ご連絡の事項が解消していることを確認しました。

少なくとも 2/18 までは回避策として使用中は OneDrive にて「同期の一時停止」を行っていたのですが、現在(2/21)の以下環境にてこの「同期の一時停止」を行わずとも 「このファイルは、別のアプリケーションによって変更されました。」が出ずに保存ができております。

MacBook Pro (13inch 2020): macOS Monterey 12.2.1
CotEditor : MacAppStore より入手、4.1.2 (481)
OneDrive : 22.012.0117.0003

今朝 CotEditor が再起動してどうもバージョンが上がったらしいこと、OneDrive については時々アップデートされていたため Monterey へのアップグレードによるものかは定かではないのですが、いずれにせよ問題が解消しているためご連絡をさせていただければと存じます。

**Comment by 1024jp** [comment]
丁寧な経過連絡ありがとうございます。
この手の保留になったイシューはその後の追跡がしづらいので大変ありがたいです。
また、現在解消しているとのこと安心いたしました。
今後もこのイシューに限らず不具合等ありましたら気軽に報告ください。
