### ISSUE TITLE
Expect tab to tab all rows.

### ISSUE THREAD

**Issue by wenbingzhang** [coteditor/CotEditor#1211]
Expect tab to tab all rows.

https://user-images.githubusercontent.com/13162606/133708308-db4dbf7e-230e-49ac-9e00-7b17a958c5dd.mov

**Comment by 1024jp** [comment]
Please elaborate more about your issue. Otherwise, I don't grasp what is the matter of you.

Maybe, you are looking for this option?

<img width="682" alt="Screen Shot 2021-09-17 at 10 54 49" src="https://user-images.githubusercontent.com/1165044/133711433-6051438b-3851-4f4b-a2a7-4eee80008251.png">

**Comment by wenbingzhang** [comment]
Yes, that's it.
