### ISSUE TITLE
ヘルプの'スクリプトについて'が開けません。

### ISSUE THREAD

**Issue by GreenHelmetA** [coteditor/CotEditor#1213]
### Description

I can not open ’ヘルプ>CotEditorスクリプトガイド>スクリプトについて’.

### To Reproduce

1. Go to 'ヘルプ'
2. Scroll down to 'CotEditorスクリプトガイド'
3. Click on 'スクリプトについて'
4. See error 'このコンテンツを開けません。'

### Expected behavior

'CotEditorスクリプトガイド’ will open.

### CotEditor version

CotEditor: 4.0.8 (471)

### macOS version

System: macOS バージョン11.6（ビルド20G165）

### Additional context

Language: Japanese
M1 MacBook Air

**Comment by 1024jp** [comment]
Thank you for the feedback.

Actually, this is one of the long-standing issues that Apple should fix. It happens sometimes randomly. I'll look into it again later, but I suppose, CotEditor implements correctly and something goes wrong on the Apple side...

**Comment by GreenHelmetA** [comment]
"long-standing issues"
Oh, thank you.

**Comment by 1024jp** [comment]
I close this ticket because CotEditor has nothing to do.

**Comment by GreenHelmetA** [comment]
Now, it works very well.
Thank you.
