### ISSUE TITLE
初めて保存するときのファイル名に1行目の内容を自動で設定して欲しい。

### ISSUE THREAD

**Issue by ichigohead** [coteditor/CotEditor#1214]
初めて保存するときのファイル名に
1行目の内容を自動で設定するオプションが欲しいです。

よろしくお願いします。

**Comment by 1024jp** [comment]
フィードバックありがとうございます。
CotEditorはオートセーブが効いた状態での振る舞いを基調として設計されている関係もあり、「初めて保存するとき」の概念が希薄です。
ある利用条件下では有用な機能であることは理解するのですが、オプションでの提供も煩雑さが増すと考えるので不採用とさせてください。
