### ISSUE TITLE
Split words into new lines

### ISSUE THREAD

**Issue by Juned-H2** [coteditor/CotEditor#1215]
When pasting a large amount of binary data or inputs it would be useful to have a word wrap function after X words.
e.g. Break word/wrap into new line after every 50 chars.

Like this online feature:
https://www.textcompare.org/text/split-text/

_* split by length in particular_

**Comment by 1024jp** [comment]
CotEditor doesn't prefer adding such a function that edits text in a specific way. Instead, please write your own script.
