### ISSUE TITLE
ひらがなモードで入力時、SHIFT+英数字を入力すると、1文字目で変換が確定されてしまう。

### ISSUE THREAD

**Issue by hibernatr** [coteditor/CotEditor#1217]
### Description

例えば、ひらがなモードのまま「CotEditor」と入力したい場合、

(SHIFT+)cot(SHIFT+)editor

でCotEditorとなるはずですが、
実際Cot Editorで入力しますと、

CおtEditor

のような入力になってしまいます。
挙動としては、SHIFT+英数字を入力すると、
最初の1文字目が入力した瞬間確定されてしまい、
2文字目以降がひらがなモードに戻ってしまうようです。
何か対処法はございますでしょうか、よろしくお願いいたします。

### To Reproduce

ことえりのひらがなモードで、SHIFTを押しながら英数字を入力する

### CotEditor version

4.0.8 (471)

### macOS version

macOS バージョン12.0（ビルド21A5552a）

### Additional context

- Language: Japanese
- IME: ことえり

**Comment by 1024jp** [comment]
返信遅くなり申し訳ないです。

本件手元の環境では発生しないのですが、
macOS 12.0.1でも引き続き発生しますでしょうか？
もし発生する場合、念のため「Shiftキーの動作」と「ライブ変換」の設定を教えていただけないでしょうか（とはいえこれらは本件には直接影響しないようですが...）。

<img width="780" alt="Screen Shot 2021-11-12 at 13 28 01" src="https://user-images.githubusercontent.com/1165044/141409632-1204aa42-0fba-4533-b200-63f22127974f.png">

**Comment by hibernatr** [comment]
すみません、お忙しいところご返信ありがとうございます！

本件なのですが、M1 Max MBPにインストールしたところ、起きなくなりました……。
特に設定などに触っていないのですがなぜか再現しなくなったため、
こちらのスレッドはクローズにさせていただきます、
大変お手数とご迷惑をおかけしてしまい申し訳ございませんでした。

これまでもこれからもずっと使い続けたいとても素敵なエディタです、
いつもお世話になっております、ありがとうございます。
