### ISSUE TITLE
App not responding when changing to new text encoding

### ISSUE THREAD

**Issue by gingerbeardman** [coteditor/CotEditor#1218]
### Description

- app becomes unresponsive when choosing a new text encoding and choosing Convert, Change Encoding

### To Reproduce

1. Open attached file [NIKKEI-CD-1994-2-17.txt](https://github.com/coteditor/CotEditor/files/7403838/NIKKEI-CD-1994-2-17.txt)
2. in status bar change encoding to "Japanese (Mac OS)"
3. choose Convert
4. choose Change Encoding
5. wait (app becomes unresponsive)
6. process does eventually complete

Activity Monitor Sample: [Sample of CotEditor.zip](https://github.com/coteditor/CotEditor/files/7403835/Sample.of.CotEditor.zip)

Screen recording:

https://user-images.githubusercontent.com/49612/138574811-ae323cbe-aad3-4517-a088-9f838b23f7fe.mov

### Expected behavior

- app should not become unresponsive

### CotEditor version

4.0.8 (Mac App Store)

### macOS version

11.6 (20G165)

**Comment by 1024jp** [comment]
Thank you for the report. I succeed in reproducing the issue under my environment.
I'll try fixing it.
