### ISSUE TITLE
動作していたスクリプトをCotEditor自身で開いて保存すると、動作しなくなる

### ISSUE THREAD

**Issue by heppoko-komi** [coteditor/CotEditor#1222]
## Environment (環境)

- CotEditor: 4.0.8 (471)
- System: macOS バージョン12.0.1（ビルド21A559）
- Language: Japanese

## Short Description (簡単な説明)

動作していたスクリプトをCotEditor自身で開いて保存すると、動作しなくなる.
具体的には、テキストが全てクリアされてしまう。

## Steps to Reproduce the Issue (不具合が発生したときに行っていた操作、または再現手順)

それまで動作していたpythonのスクリプトをCotEditor開き、影響のない箇所に改行を入れ、保存する。
その後、スクリプトメニューから実行すると、その直前まで動作していたものが正しく動作しなくなる。

## Expected Result (期待される挙動)

python のスクリプトが正常に実行されること。

### To Reproduce

(1)それまで動作していたpythonのスクリプトをCotEditor開く
(2)影響のない箇所に改行を入れ、保存する。
(3)スクリプトメニューから実行すると、その直前まで動作していたものが正しく動作しなくなる。

### CotEditor version

4.0.8

### macOS version

12.0.1

**Comment by 1024jp** [comment]
こちら #1216 と同根のバグかと思います。
現在原因を調査中で、macOS 12でのなんらかの暗黙的なシステム変更に関連すると思われるのですがどうもまだ突き止められておらずおります。ご迷惑おかけしております。
ただ、
> 具体的には、テキストが全てクリアされてしまう。
というのが気になります。
保存すると保存したファイルの内容が全て消えてしまうということでしょうか？

またその場合、オートセーブを有効にしているか否か（環境設定 > 一般で設定できます）を教えていただけますか？

**Comment by heppoko-komi** [comment]
> またその場合、オートセーブを有効にしているか否か（環境設定 > 一般で設定できます）を教えていただけますか？

確認しましたところ、オートセーブは有効になっておりました。

**Comment by 1024jp** [comment]
#1216にイシューを一本化するため、こちらはクローズさせてください。
