### ISSUE TITLE
Options for dismissing save dialog with keyboard

### ISSUE THREAD

**Issue by gingerbeardman** [coteditor/CotEditor#1226]
**Is your feature request related to a problem? Please describe.**

I like to use the keyboard as much as possible, including navigating and dismissing dialogs and alerts. With the file selector in CotEditor two of the three options can only be accessed using the mouse.

**Describe the solution you'd like**

Support for standard macOS keyboard conventions:
- Cmd+S or Enter = Save (already works)
- Cmd+Esc = Cancel
- Cmd+Del = Delete

**Describe alternatives you've considered**

- Use the mouse
- Use Keyboard Maestro to add hotkey shortcuts/macros

**Additional context**

![Screen shot 2021-11-09 at 11 30 46](https://user-images.githubusercontent.com/49612/140916553-5f7c2ef9-4636-46ab-a52a-3b1330240994.png)

Apologies if this is a macOS issue.

**Comment by 1024jp** [comment]
From the viewpoint of security, 3rd party developers have limitations to control the save/open panels on macOS. So adding such an original keyboard shortcut for them is technically impossible.

> Support for standard macOS keyboard conventions:
> 
> - Cmd+S or Enter = Save (already works)
> - Cmd+Esc = Cancel
> - Cmd+Del = Delete

By the way, I suppose these shortcuts are already supported in CotEditor. The shortcut for cancelling is just Esc key instead of Cmd+Esc, though.
If you cannot use these, there may be some other issues.

**Comment by gingerbeardman** [comment]
I could not find the shortcut for Delete, is there one?

So I implemented my own using Keyboard Maestro.

**Comment by 1024jp** [comment]
> Cmd+Del = Delete

Hmm, this works under my environment (macOS 12.0.1 (21A559), Apple Magic keyboard US).

**Comment by gingerbeardman** [comment]
Cmd+Backspace = OK
Cmd+Delete = nothing

Interesting!

**Comment by 1024jp** [comment]
CotEditor do nothing for keyboard shortcuts for open/save panels and just follows the systems standard behavior. Thus, the behavior under your environment (using Backspace instead of Delete) may be affected by the key mapper or something.
