### ISSUE TITLE
Application stops responding when selecting text

### ISSUE THREAD

**Issue by gingerbeardman** [coteditor/CotEditor#1227]
### Description

Application stops responding when selecting text that contains certain invisible Unicode characters/bytes

### To Reproduce

1. Open UTF-8 file [HYPERLIB-1994-3-CD1.txt](https://github.com/coteditor/CotEditor/files/7541113/HYPERLIB-1994-3-CD1.txt)
2. Position cursor at end of file
3. Press Alt+Shift+Left cursor (to extend selection by word)
4. App becomes unresponsive 

### Expected behavior

- Selection should be extended without issue

### CotEditor version

- 4.0.8 (471)

### macOS version

- 11.6 (20G165)

**Comment by 1024jp** [comment]
Thank you for the report.
I confirmed the issue. It causes only when control characters are not made visible.
Anyway, this must be a bug to be fixed.
Let me have time.

**Comment by 1024jp** [comment]
The bug will be fixed in the next version, 4.0.9.

**Comment by gingerbeardman** [comment]
Thanks!
