### ISSUE TITLE
Syntax Highlighting: protocol buffers

### ISSUE THREAD

**Issue by uechoco** [coteditor/CotEditor#1228]
Thanks for the useful editor.

**Is your feature request related to a problem? Please describe.**
Protocol Buffers is one of the major IDLs(Interface Definition Language), especially the case used in gRPC is famous.
Many programming editors support its syntax highlighting.
I think it would be useful to use CotEditor with syntax-highlighting when writing a little note-writing protobuf.

**Describe the solution you'd like**
[Protocol Buffers Version 2 Language Specification](https://developers.google.com/protocol-buffers/docs/reference/proto2-spec)
[Protocol Buffers Version 3 Language Specification](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec)
And some OSS editors support its syntax highlighting.

**Describe alternatives you've considered**
I have no idea.

**Additional context**

**Comment by 1024jp** [comment]
Thank you for the request.
It sounds like worth to add.
Let me have time.
(I maybe need to ask to the guy who made PR #1235 at first.)

**Comment by 1024jp** [comment]
Added to CotEditor 4.1.0, which will be released in this month.

**Comment by uechoco** [comment]
I'm glad you support this. Thank you. I'm looking forward to the release.
