### ISSUE TITLE
Setting for line wrapping by default

### ISSUE THREAD

**Issue by acutchin-bitpusher** [coteditor/CotEditor#1234]
**Is your feature request related to a problem? Please describe.**
I have to manually select Format / Wrap Lines every time I create or open a document

**Describe the solution you'd like**
Setting for optional line wrapping by default

**Describe alternatives you've considered**
none

**Additional context**
seems pretty straightforward

**Comment by 1024jp** [comment]
Sorry for my late reply.
You can set the default behavior for line wrapping by turning on the "Wrap lines to editor width" option in CotEditor's Preferences > Edit pane > Line wrapping.

<img width="682" alt="Screen Shot 2022-01-18 at 12 52 24" src="https://user-images.githubusercontent.com/1165044/149868035-55e19b1c-da11-44e9-ab3c-b1aa1911a522.png">
