### ISSUE TITLE
Closing with red x doesn't reopen files

### ISSUE THREAD

**Issue by ari62** [coteditor/CotEditor#1237]
### Description

When I right click on the icon in the dock and quit, then reopen CotEditor, my previously opened files are opened again. When I close with the red x button, which i think doesn't fully quit, then reopen by clicking on the CotEditor icon in the dock, my previously opened files are not opened and I have a new untitled file opened instead.

I am using and 2021 macbook pro 16-inch with macOS Monterey Version 12.1

### To Reproduce

Close by clicking red x and reopen CotEditor.

### Expected behavior

I expect previously opened files are reopened when editor is reopened no matter how it is closed.

### CotEditor version

4.0.9

### macOS version

12.1

### Additional context

I am seeing this same issue on another text editor I am trying.

**Comment by jadomski** [comment]
What you have described is the correct behaviour for closing windows vs quitting applications for multi-windowed applications.

My interpretation of the HIG, which appears to be the standard interpretation, is that the behaviour you’re expecting should only be present in a single-windowed application.

**Comment by 1024jp** [comment]
As @jadomski explained, this is the correct behavior for macOS applications.
