### ISSUE TITLE
Incorrect line 1

### ISSUE THREAD

**Issue by CosmicMango** [coteditor/CotEditor#1239]
### Description

In the bottom left line number is shown, at the start line 1 is shown as line one, however when you move to from location 1 and then back, line 1 is shown in the bottom left as line 0.

### To Reproduce

1. Go to 'line 1 location 1'
2. Move to a different line or location
3. Go back to line 1 location 1
4. See in the bottom left that "Line: 0"
<img width="248" alt="Screenshot 2022-01-19 at 17 37 08" src="https://user-images.githubusercontent.com/98047487/150184315-15af5ed5-0b23-4d65-9f60-98d5e5c91e5d.png">
<img width="252" alt="Screenshot 2022-01-19 at 17 36 59" src="https://user-images.githubusercontent.com/98047487/150184321-2185f44e-3e42-4585-9185-705d293ca61e.png">

### Expected behavior

Line 1 Location 1 should be seen as Line 1 Location 1 not Line 0 Location 1

### CotEditor version

4.0.9

### macOS version

10.15.7

**Comment by 1024jp** [comment]
Thank you for the feedback.
However, I could not reproduce your issue.
Could you describe more step-by-step how you moved your cursor (e.g. by clicking the location, pressing the down arrow key, etc)

**Comment by AlexNewson** [comment]
I can reproduce this issue, I've submitted a pull request (#1244) which seems to fit it.

**Comment by 1024jp** [comment]
@AlexNewson Oh, I missed something. thank you for the PR with a detailed description.
