### ISSUE TITLE
Disabling smart quotes

### ISSUE THREAD

**Issue by ZahraBehfar** [coteditor/CotEditor#1248]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ZahraBehfar** [comment]
Hello.
I was typing a source code in CPP and noticed every time I type  a simple " "  the CotEditor change that into a smart “  ” code which creates a syntax error.
Hope this can be fixed. I could not find anyway to fix it myself.
Thanks for this wonderful free app.
zahrabehfar@gmail.com

**Comment by AlexNewson** [comment]
Within CotEditor, go to `Preferences > Edit` and make sure Smart Quotes and Dashes are both unticked.

Then within macOS, go to `System Preferences > Keyboard > Text` and untick "Use smart quotes and dashes".

You then should be able to type `""` without it being automatically changed.

**Comment by ZahraBehfar** [comment]
Thank you very much Alex,
That saved my day!!
Best Regards,
Z
