### ISSUE TITLE
Looking for new maintainer for Portuguese (Brazil) localization

### ISSUE THREAD

**Issue by 1024jp** [coteditor/CotEditor#1251]
We are now looking for a new maintainer for Portuguese (Brazil) localization. Please read the [Localization section in CONTRIBUTING.md](https://github.com/coteditor/CotEditor/blob/develop/CONTRIBUTING.md#localization) and let us know if you would be interested in. Please note that all the CotEditor's localization maintainers are volunteer-based and unpaid.

One-time pull-request for unlocalized strings is also welcome. You can find all the strings to be localized with `FIXME:` tag.

**Comment by unnamedd** [comment]
Hey @1024jp, I will give a check on your contributing code, but I guess I will be able to help here in case no one else can.

**Comment by 1024jp** [comment]
@unnamedd Thank you for the kind offer. It would be great if you can maintain our app.
Currently, there are about 14 string lines waiting for localization to Portuguese with `FIXME:` tags. They should be localized at any moment.
Regarding future maintenance, I'll call localization maintainers by creating an issue,  just like #1250, when CotEditor has new strings to be localized. This kind of update can happen about once per few months.

**Comment by unnamedd** [comment]
Sounds great @1024jp, I will have a look over the weekend and should submit a PR as soon as possible! ;)

**Comment by 1024jp** [comment]
@unnamedd Hi, do you still have an interest to localize CotEditor in Portuguese? I am now preparing to release the next minor update, CotEditor 4.2.0. So, it would be great if the Portuguese localization could be updated before the release.

**Comment by unnamedd** [comment]
Hey @1024jp, sorry for my absence! Had no time during the last few weeks! 
Yes, I'm still interested in helping CotEditor in the Brazilian Portuguese translation.

I'm going to check your instructions right now!

**Comment by 1024jp** [comment]
Thank you very much. No worry.
Then, I'll call you in the future when localization should be updated, like in #1291.
