### ISSUE TITLE
tab key not work on selection

### ISSUE THREAD

**Issue by xendia100** [coteditor/CotEditor#1255]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

editor have to add indent using tab key on selection. but it is not work.
- it does not work on selection indent with tab key

![Screen Capture 2022-02-06 at 21 54 58](https://user-images.githubusercontent.com/96650095/152681760-de2170f6-10d8-4063-a68a-6289efa9e89f.gif)
![image](https://user-images.githubusercontent.com/96650095/152681935-910d3d93-ff34-4e34-b749-fc428e0e759b.png)
![Screen Capture 2022-02-06 at 21 59 21](https://user-images.githubusercontent.com/96650095/152681961-0ec1f223-2614-4db8-bbb0-9befab99aaff.gif)

**Comment by 1024jp** [comment]
Could you describe it step-by-step and clarify what is expected, and what the current behavior is?

CotEditor has an option in Preferences > Edit that toggles the behavior for the tab key. Is that solve your issue?

<img width="682" alt="Screen Shot 2022-02-07 at 10 08 36" src="https://user-images.githubusercontent.com/1165044/152710169-b49f8351-abe4-4ba8-a0f6-4132f9bae380.png">

**Comment by 1024jp** [comment]
I close this ticket because of no reply.
