### ISSUE TITLE
Keybindings broken

### ISSUE THREAD

**Issue by ceciliacase** [coteditor/CotEditor#1259]
### Description

In the new version, I noticed my custom keybindings weren't working. So I went and looked, and it looks like they've been reset, and there's a box with a question mark showing for all of them, so I can't tell what the bindings are anymore. How can I restore my keybindings and fix the problem?

<img width="570" alt="Screenshot2022-02-15 10:25:00 AM" src="https://user-images.githubusercontent.com/887721/154125633-276674cb-6a64-4ce7-9d84-c31fd409b9b5.png">

### To Reproduce

For custom keybinding:
1. Try a custom keybinding
2. It doesn't work.

For Preferences problem:
1. Go to Preferences
2. Click on Key Bindings
3. Open one of the Actions

### CotEditor version

4.1.0

### macOS version

11.6.2 (20G314)

### Additional context

I back up my preferences folder. Is there a way of restoring my keybindings from there?

**Comment by 1024jp** [comment]
Thank you for the report and sorry for the silly bug.
This bug was already fixed on CotEditor 4.1.1 that released today.

duplicated: #1258

**Comment by ceciliacase** [comment]
Thank you so much. Updated and everything is fine now!
