### ISSUE TITLE
Editor scrolls oddly when typing the Space key.

### ISSUE THREAD

**Issue by 1024jp** [coteditor/CotEditor#1260]
### Description

This is a report received by users per e-mail.

> 漢字変換のためスペースバーを押すと勝手に画面がスクロールする。

translation: The editor scrolls oddly when typing the Space key to select the Japanese character candidates.

The report above says it happens when typing the Space key for character selection, but another report says it happens also just inputting a space (both by the normal one and full-width one).

### To Reproduce

1. Open a file that is long enough to have a vertical scroll bar.
2. Input a space by stroking the Space key.

### Expected behavior

Not to scroll.

### CotEditor version

4.1.1

### macOS version

12.2.1

### Additional context

Although I received multiple reports on this phenomenon, I could not reproduce it.
Please let me know if you find hidden conditions to reproduce it.

**Comment by 1024jp** [comment]
Another report, report 3, says:

- Input method: standard macOS IM
- Keyboard layout: US
- macOS version: 11.6.3

cite: https://twitter.com/cortyuming/status/1493735151222034433?s=21

**Comment by 1024jp** [comment]
@yuriy-makhin Thank you for the additional information with the actual sample file.
However, I still cannot reproduce it even using following your instruction.
Maybe some conditions are missing.

One question just in case: does the same phenomenon appear if you do the same steps in the TextEdit.app by Apple?

**Comment by 1024jp** [comment]
It would be great if someone shares a screencast shooting this phenomenon.

**Comment by yuriy-makhin** [comment]
> Maybe some conditions are missing.
I could attach my settings files if that might help.

> One question just in case: does the same phenomenon appear if you do the same steps in the TextEdit.app by Apple?
No, I can't reproduce it anywhere but in CotEditor.

**Comment by yuriy-makhin** [comment]
> It would be great if someone shares a screencast shooting this phenomenon.

Attached.

https://user-images.githubusercontent.com/3327828/154796528-12b68808-afbb-493d-a77a-b7b9e0be0ac6.mov

**Comment by 1024jp** [comment]
@yuriy-makhin 

>> Maybe some conditions are missing.
>
> I could attach my settings files if that might help.

That would be great.
I'd like to have screenshots of the General, Window, Appearance, and Edit pane of the CotEditor's preferences.

>> One question just in case: does the same phenomenon appear if you do the same steps in the TextEdit.app by Apple?
>
> No, I can't reproduce it anywhere but in CotEditor.

Good. That's a helpful information, because I observed a similar issue on it (already reported to Apple) but not sure if it's related to this issue.

**Comment by 1024jp** [comment]
I'm also interested does the behavior change if you close the outline view on the right side.

**Comment by yuriy-makhin** [comment]
Attaching settings. Outline does not seem to impact it, nor changing the syntax language (I'm using a custom one usually).
Thank you for looking into this, it's driving me nuts.
Also, only seen it in the last few days, so… this regression must be recent.
<img width="682" alt="Screenshot 2022-02-19 at 12 42 51" src="https://user-images.githubusercontent.com/3327828/154797615-2db0b769-992c-4f14-8524-f87aac4c8162.png">
<img width="682" alt="Screenshot 2022-02-19 at 12 43 02" src="https://user-images.githubusercontent.com/3327828/154797618-cdc6ac79-d643-418f-a4b5-55a4e830e736.png">
<img width="682" alt="Screenshot 2022-02-19 at 12 43 07" src="https://user-images.githubusercontent.com/3327828/154797621-be647c79-b4ad-4a2b-a460-434b1978a414.png">
<img width="682" alt="Screenshot 2022-02-19 at 12 43 11" src="https://user-images.githubusercontent.com/3327828/154797622-d12eccc9-dc3d-4a7b-be23-ecd22ddd334f.png">

**Comment by 1024jp** [comment]
@yuriy-makhin Thank you very much. I'll research it later.

**Comment by 1024jp** [comment]
Reproduced! Great!
The hidden key was the setting "Link URLs in document" in the General pane.
This finding makes me really easy to debug. Thank you again @yuriy-makhin.

---

That is, if you guys currently struggle with this bug, please turn off the option until the release of the bug fix.

**Comment by yuriy-makhin** [comment]
> Reproduced! Great! The hidden key was the setting "Link URLs in document" in the General pane. This finding makes me really easy to debug. Thank you again @yuriy-makhin.
> 
> That is, if you guys currently struggle with this bug, please turn off the option until the release of the bug fix.

Awesome! Thank you so much for working it out!

**Comment by 1024jp** [comment]
I've just submitted the new version fixing this issue to the MAS. As long as the submission is not rejected, it will be released tomorrow.

Fixing the bug, I realized this issue is actually based on a bug on the framework side. I'll report it to Apple.
@yuriy-makhin, Can I send the sample file you attached to this thread [here](https://github.com/coteditor/CotEditor/issues/1260#issuecomment-1045562875) to Apple to explain how the issue can be reproduced? The report is not public space but only share with me and the people in Apple.

**Comment by yuriy-makhin** [comment]
> I've just submitted the new version fixing this issue to the MAS. As long as the submission is not rejected, it will be released tomorrow.
> 
> Fixing the bug, I realized this issue is actually based on a bug on the framework side. I'll report it to Apple. @yuriy-makhin, Can I send the sample file you attached to this thread [here](https://github.com/coteditor/CotEditor/issues/1260#issuecomment-1045562875) to Apple to explain how the issue can be reproduced? The report is not a public space but only share with me and the people in Apple.

Sure, send it, no problem.

**Comment by 1024jp** [comment]
@yuriy-makhin Thanks!

**Comment by 1024jp** [comment]
Released CotEditor 4.1.2 fixing this issue has been released.
