### ISSUE TITLE
Open a Folder with CotEditor

### ISSUE THREAD

**Issue by chandrapol** [coteditor/CotEditor#1262]
**Is your feature request related to a problem? Please describe.**
CotEditor has become my everyday application. Love it. Because it can syntax highlight of many languages, and we review/eyeball/quick-edit projects, I thought it could be a great feature if CotEditor has file manager. 

**Describe the solution you'd like**
A side view just like "Show Document Information", a file manager on left or right side would be great feature. 

**Describe alternatives you've considered**
I could not think of any better alternative for this.

**Additional context**
![Screen Shot 2022-02-28 at 10 51 14 AM](https://user-images.githubusercontent.com/87336521/156041296-97eb4db5-b9d2-4d80-a26d-dc5090aea233.png)

**Comment by 1024jp** [comment]
Thank you for the feedback.
Just because this is a request that already exists, I close this. #278
I understand it's a popular request. But due to limited time resources, there is no concrate plan yet.
