### ISSUE TITLE
新規ファイルが保存（別名で保存も）できません。

### ISSUE THREAD

**Issue by tomg25** [coteditor/CotEditor#1263]
### Description

新規の名称未設定ファイルを保存または別名で保存しようとしても保存されない。
いずれの操作（保存または別名で保存）時もMacのレインボーカーソルはしばらく（5〜10秒程度）表示され回るが、そこから何も起こらない。

### To Reproduce

1. 新規の名称未設定ファイルを開く
2. その名称未設定ファイルに入力する
3. 保存または別名で保存する
4. Macのレインボーカーソルはしばらく（5〜10秒程度）表示され回るが、保存先の参照ダイアログウィンドウも開かず、ファイルは保存されない。

### CotEditor version

4.1.2 (481)

### macOS version

12.2.1（ビルド21D62）

### Additional context

いつもありがとうございます。
よろしくお願いします。

**Comment by 1024jp** [comment]
手元の環境で再現ができないため、この情報だけでは特定が難しいです。類似のレポートも今のところもらっていません。
以下の情報を教えていただけませんか？

1. いつから発生する不具合か
CotEditor 4.1.2で発生するとのことですが、以前のどのバージョンまで正常に動きますか？
（なお現在のCotEditor最新版は4.1.3になります。まずはそちらをお試しください。）

2. 


> 3. 保存または別名で保存する

どのような操作で保存を実行しましたか。⌘Sでしょうか、メニューから「保存」を実行？

> 4. Macのレインボーカーソルはしばらく（5〜10秒程度）表示され回るが、保存先の参照ダイアログウィンドウも開かず、ファイルは保存されない。

この後はどうなりますか？

**Comment by tomg25** [comment]
いつもお世話になっております。
早速のご解答ありがとうございます。

結論から申しますと、自己解決を致しました。
復旧方法は以下のとおりです。
一旦アプリを削除し、Application Support内のCotEditoフォルダを退避させてから、再インストール。

お手数をおかけいたしまして申し訳ございませんでした。

なおご参考までに、
1.いつから発生する不具合か
→ こちらについては、明確ではないのですが、おそらくMacOSを12.2としたころからですので2月上旬頃です。

2.保存または別名で保存する
→ こちらについては、⌘Sなどショートカットでも、メニューから保存を実行でも同様に保存できませんでした。

3.Macのレインボーカーソルはしばらく（5〜10秒程度）表示され回るが、保存先の参照ダイアログウィンドウも開かず、ファイルは保存されない。
この後はどうなりますか？
→ こちらについては、その後は何も起こりませんでした。名称未設定ファイルもデスクトップ上に開いて表示されたままとなりました。

2022年3月9日(水) 14:08 1024jp ***@***.***>:

**Comment by 1024jp** [comment]
経過報告ありがとうございます。
再インストールで無事直ったとのこと、Application Support内のどこかでファイルが壊れていた可能性も考えられますが、類似事例の報告もないため本件クローズさせていただきます。
レポートありがとうございました。
