### ISSUE TITLE
Cannot Open Haskell Files

### ISSUE THREAD

**Issue by JoshuaScurr** [coteditor/CotEditor#1264]
### Description

Attempting to open Haskell (`.hs`) files results in 'The document “Main.hs” could not be opened. CotEditor cannot open files in the “Haskell script” format.'
Before a recent update (couldn't be certain of exactly which one, but it was working about a month ago), it would open them fine, but now refuses, despite having Haskell syntax highlighting, and allowing me to create and save new `.hs` files (but I can't then reopen them).

### To Reproduce

1. Attempt to open a `.hs` file

### Expected behavior

Expected behaviour: file opens (and displays with highlighting)

### CotEditor version

2.9.2

### macOS version

12.3 Beta (21E5212f)

**Comment by 1024jp** [comment]
Thank you for the report. I confirmed the issue and also think this is a bug to fix. Let me have a time.

**Comment by 1024jp** [comment]
Fixed on the next CotEditor 4.1.4.

**Comment by 1024jp** [comment]
Today, CotEditor 4.1.4 fixing this issue was released. Let me know if the bug still exists.

**Comment by JoshuaScurr** [comment]
Thanks - it now works for me
