### ISSUE TITLE
Feature like Rainbow CSV in VSCode / Rainbow CSV のような機能

### ISSUE THREAD

**Issue by tn3141** [coteditor/CotEditor#1270]
よく利用させていただいており、ありがとうございます。
要望ですが、VSCode の Rainbow CSV のような機能が
あると嬉しいです。

カラム指定のソートとかができると最高ですが、
とりあえずカラー表示だけでも助かります。

**Comment by 1024jp** [comment]
ソート機能については、すでにCotEditorにある「条件で並び替え (Sort by Pattern)」機能で実現するかと思います。
カラムごとに色が異なる設定については簡易なものであれば正規表現で実現できそうなのでシンタックススタイルを作成すれば叶いそうではあるのですが、ちょっと標準で実装には癖があるように思うので、本体への実装は控えようと思います。もし興味がありましたら、独自のシンタックス定義を作成しお試しください。

<img width="1060" alt="Screen Shot 2022-03-19 at 11 10 34" src="https://user-images.githubusercontent.com/1165044/159102918-62782714-c6d6-40f1-a72a-d828bed14347.png">

**Comment by tn3141** [comment]
ご回答、ありがとうございました。
csv用のシンタックス定義を試してみたいと思います。
