### ISSUE TITLE
HTML内のJavaScriptに'='があると以降の色付けが正しくない

### ISSUE THREAD

**Issue by MakotoYamanaka** [coteditor/CotEditor#1272]
### Description

HTML内のJavaScriptのシングルクォートで囲った文字列が半角イコールで終わっていると、文字列の閉じと判定されておらず、次のシングルクォートまで文字列の色になっています。

### To Reproduce

1. 新規書類を作成。
2. シンタックスをHTMLにする。
3. 以下の内容をペーストする。
```
<!DOCTYPE html>
<html>
<script type="text/javascript">
function search(arg){
	var str = 'https://site.com?search=' + arg;
	window.open(str,'_blank');
}
</script>
</html>
```

### Expected behavior

ペーストした5行目の「search='」で文字列の色付けが終わるべきと思います。
が、6行目の「'_blank」のシングルクォートまで文字列の色付けが続いてしまっています。

### CotEditor version

4.1.4 (485)

### macOS version

11.6.5（ビルド20G527）

### Additional context

正しい動作（私のHTML/JavaScriptの理解が正しくないだけ）だったらすみません。

**Comment by 1024jp** [comment]
CotEditorでは複数の言語が混在する書類の試ンタックスハイライトをサポートしていないため、基本的には「仕様です」という回答となるのですが、ご指摘部分に関してはもうちょっとマシにできる気がするので次バージョンで改善します。

**Comment by MakotoYamanaka** [comment]
ありがとうございます。よろしくお願い致します。
