### ISSUE TITLE
リンクされたURLに下線以外のスタイルを付けたい / Style linked URLs without underline

### ISSUE THREAD

**Issue by MakotoYamanaka** [coteditor/CotEditor#1273]
**Is your feature request related to a problem? Please describe.**
環境設定＞一般＞「書類中のURLをリンク」をオンにした場合、現状URLには下線が付き、色付けはテーマのシンタックスに沿った色。

**Describe the solution you'd like**
リンク部分の文字色と下線の有無を設定できると嬉しいです。（例：青色で下線無し）

**Describe alternatives you've considered**
なし。

**Additional context**
なし。

**Comment by 1024jp** [comment]
ニーズとしてはわからなくもないのですが、URLの抽出とシンタックスハイライトが別の仕組みのため、またニーズが少なく現行の仕様でも利便性を大きく即なうことはないと考えているため、提案は棄却させてください。
