### ISSUE TITLE
Character Wrapで行を折り返す表示にしたい

### ISSUE THREAD

**Issue by MakotoYamanaka** [coteditor/CotEditor#1274]
**Is your feature request related to a problem? Please describe.**
環境設定＞編集＞「エディタの幅に合わせて行を折り返す」がオンの場合、現状Word Wrap固定。

**Describe the solution you'd like**
Character Wrapに設定できると嬉しいです。

**Describe alternatives you've considered**
なし。

**Additional context**
なし。

**Comment by 1024jp** [comment]
個人的にあまり必要ないと考えていたのですが、過去にもニーズを観察したことがあるので、改めて検討してみます。

**Comment by MakotoYamanaka** [comment]
ありがとうございます。よろしくお願い致します。

**Comment by 1024jp** [comment]
ちなみに、どのようなケースでの利用を想定されているか伺っても良いですか？

**Comment by MakotoYamanaka** [comment]
例えば長いコードをコメントアウトした場合のように、短いWord＋長いWord、となる行だと、行頭近くでWrapされてしまいます。
そういう行が連続すると、Word WrapよりCharacter Wrapのほうが見やすく感じます。
<img width="826" alt="1" src="https://user-images.githubusercontent.com/3773571/161123919-f371b092-e9c2-4a54-b62e-6640b5ab22d0.png">

**Comment by 1024jp** [comment]
回答ありがとうございます。
この点が課題だとすると、オプションを増やすよりも記号等での折り返しを調整した方が有用そうですね。
考えます。

**Comment by MakotoYamanaka** [comment]
>記号等での折り返しを調整

はい、それでもいいと思います。ありがとうございます。よろしくお願い致します。

**Comment by 1024jp** [comment]
こちら何回か検討したのですが、
自然な挙動を再現するにはAPIが足らず、かといって設定オプションを追加するのは過剰に思うので、
本リクエストはリジェクトさせてください。
ご期待に添えず申し訳ないです。
