### ISSUE TITLE
Snippets insertion format relative indentation

### ISSUE THREAD

**Issue by scoskey** [coteditor/CotEditor#1275]
**Is your feature request related to a problem? Please describe.**
When I insert a snippet with several lines, the subsequent lines begin at column 0 rather than at the current indentation

**Describe the solution you'd like**
I would like to insert several lines of text, all at the current indentation level (or deeper by putting spaces or tabs at the beginning)

**Describe alternatives you've considered**
I am usually at the first nonzero indentation level, so I currently manually write my snippet with the correct number of initial spaces. However at times when I'm at a different indentation level, the result is not as expected.

**Additional context**
My snippet is a common Latex expression and should look like:
```
\begin{itemize}
  \item <<<CURSOR>>>
\end{itemize}
```
However it often comes out looking like
```
  \begin{itemize}
  \item <<<CURSOR>>>
\end{itemize}
```
or whatever.

**Comment by 1024jp** [comment]
That's an interesting idea and sounds quite easy to implement.
I'll try it in CotEditor 4.2.0 that is planned to be released this early summer.

**Comment by scoskey** [comment]
Awesome!

**Comment by scoskey** [comment]
This feature was addressed in 4.2.0 but it doesn't always work. I can't use my snippets when at 0 indentation.

**Comment by 1024jp** [comment]
Thank you for confirming.

>  but it doesn't always work. I can't use my snippets when at 0 indentation.

CotEditor 4.2.1, which fixes this issue, was just released yesterday. Please try it.

**Comment by scoskey** [comment]
Ah, will do! Thank you :)
