### ISSUE TITLE
Ability to put navigation dropdown menu in the status bar

### ISSUE THREAD

**Issue by scoskey** [coteditor/CotEditor#1277]
**Is your feature request related to a problem? Please describe.**
My status bar is rarely very full. I typically keep several of the available items unchecked. At the same time, my navigation bar is also not very full, as it contains only one dropdown menu and the split window button.

**Describe the solution you'd like**
Option to put the navigation dropdown menu in the status bar (and possibly also the split window button in the status bar). This would thus eliminate the need for two separate bars, at least for those who don't need as much space.

**Describe alternatives you've considered**
Keep both the status bar and navigation bar shown. Sometimes hide one or the other and re-show it when needed.

**Additional context**
N/A

**Comment by 1024jp** [comment]
Although I understand your demand, I need to say I'll not implement this request to make the UI clear. Implementing the same things in different areas is a kind of messy. Sorry, but thank you for the feedback.

**Comment by scoskey** [comment]
Understood!

**Comment by scoskey** [comment]
Maybe it could all just be in one place?

**Comment by 1024jp** [comment]
> Maybe it could all just be in one place?

Hmmm, sorry but also no. They have different purpose.
