### ISSUE TITLE
Cot Editor Indention button icons are backwards

### ISSUE THREAD

**Issue by IanAtSalt** [coteditor/CotEditor#1278]
### Description

In CotEditor, the indention button icon in the tool bar shows an arrow pointing right indicating that it will move text to the right. This is the opposite of what it does. The same behavior goes for the outdent button. Please swap the icons!

### Expected behavior

Button showing indent icon will indent selected text.

### CotEditor version

414

### macOS version

12.2.1

**Comment by 1024jp** [comment]
Oh, thank you for notifying me.
I did not realize it for more than one year.
It'll be fixed in the next version.
