### ISSUE TITLE
Error: bash shell script syntax

### ISSUE THREAD

**Issue by valord577** [coteditor/CotEditor#1287]
### Description

<img width="819" alt="Screen Shot 2022-04-22 at 14 05 29" src="https://user-images.githubusercontent.com/30427460/164613498-9b82d37a-a154-41c9-8a29-375a866c03e9.png">

### To Reproduce

Just see `Description`.

### CotEditor version

Version 4.1.5 (487) - From app store

### macOS version

Version 12.3.1 (21E258)

**Comment by 1024jp** [comment]
Closed the wrong issue.
