### ISSUE TITLE
Cant change file name after it is saved

### ISSUE THREAD

**Issue by Qrishna** [coteditor/CotEditor#1288]
### Description

Once you create a file and save it with some filename.extension, later on you cant change the extension of the file from the title bar. 

### To Reproduce

create and save a file as test.py
try to rename the file to test.c
you will see that it renames the file to test.c.py which is not what we want.

### Expected behavior

rename it to test.c from the title bar without appending file extensions

### CotEditor version

Version 4.1.5 (487)

### macOS version

Monterey 12.3.1 (21E258)

**Comment by 1024jp** [comment]
Close due to duplication of #1123.
