### ISSUE TITLE
Warning dialog of 4.2 can't be read in dark mode

### ISSUE THREAD

**Issue by tatsy-ymj** [coteditor/CotEditor#1293]
### Description

Warning dialog of 4.2 can't be read in dark mode
<img width="683" alt="スクリーンショット 2022-05-03 11 32 29" src="https://user-images.githubusercontent.com/4995795/166396807-76590dcc-503f-4d4b-a3f4-716900b7cb1e.png">

### To Reproduce

Run CotEditor 4.2 rc.

### CotEditor version

4.2.0-rc

### macOS version

12.3.1

**Comment by 1024jp** [comment]
Ooooops, thank you! I've just released rc.2.

**Comment by 1024jp** [comment]
Note: Because this panel is designed to appear one time only, you'll not get it on the 4.2.0-rc.2. So don't worry, it's not a bug but by design.
