### ISSUE TITLE
Unexpected css `addition` style in dark style

### ISSUE THREAD

**Issue by sidepelican** [coteditor/CotEditor#1295]
### Description

Cannot read some texts in help window using OS dark style.
<img width="514" alt="スクリーンショット 2022-05-09 15 23 36" src="https://user-images.githubusercontent.com/19257572/167351998-66237f9b-677f-445f-b0f9-cb8219867985.png">

### To Reproduce

in japanese environment, and use OS dark style
1. Go to `ヘルプ` in menu bar
2. Type `CotEditor 4.2での重要な変更` in search bar
3. Click top hit
4. See 吹き出し

### Expected behavior

texts in `addition` is readable

### CotEditor version

バージョン4.2.0 (502)

### macOS version

12.3.1（21E258）

**Comment by 1024jp** [comment]
Oops. Thank you for the report!
