### ISSUE TITLE
Open iCloud Drive files do not update and CotEditor hangs

### ISSUE THREAD

**Issue by matzepf** [coteditor/CotEditor#1296]
### Description

I have CotEditor running all the time, in the office and at home. Both Macs are on all the time. I have some files open (~5 tabs) in both editors that are stored on iCloud Drive. When I change a file on one Mac and go to the other, the changes are not updated. (That is not problem; it is ok if an interaction is needed. In preferences I selected to update to new version if a file was changed.) But as soon as I want to start working, e.g. change a file, opening a new file to edit, CotEditor hangs (spinning beach ball) and needs to be killed. (Still the changes are not updated.)

### To Reproduce

See description

### CotEditor version

4.1.5

### macOS version

12.3.1

**Comment by matzepf** [comment]
Maybe it is important to know that 2 of the files are huge, easily > 100,000 lines.

**Comment by 1024jp** [comment]
Thank you for the report.
Today, 2022-05-09, CotEditor 4.2.0 has just been released.
Does the issue you reported occur after this update or since a day before?

> Maybe it is important to know that 2 of the files are huge, easily > 100,000 lines.

This additional information seems important.
Let me have time to find the cause.

**Comment by 1024jp** [comment]
Sorry for taking the time. But I finally added a measure against this issue and released CotEditor 4.3.3 which includes the fix today.
I suppose now it works but if some problem still exists, feel free to let me know.

**Comment by matzepf** [comment]
Works fine for me now. Thanks a lot.

**Comment by matzepf** [comment]
I am sorry to say, I think the fix introduced a new problem. Today, when I came in the office, I was greeted by this (see screenshot) in my process list …
<img width="317" alt="CotEditor Mem Leak" src="https://user-images.githubusercontent.com/36540028/187906495-a87e7f5d-3313-40c2-9750-c6b41d302e29.png">
