### ISSUE TITLE
フルスクリーン表示時に、表示する列に合わせて入力エリアを中央に寄せたい / Center input area on fullscreen mode

### ISSUE THREAD

**Issue by kryu2** [coteditor/CotEditor#130]
現在フルスクリーン表示を行うと、
表示する列の幅に関係無く左側へ入力エリアが寄って表示されます。

広い画面でフルスクリーン表示すると
視点がかなり偏ってしまうので、

表示する列に合わせて入力エリアを
中央に寄せる機能があれば良いなと思いました。

**Comment by 1024jp** [comment]
行番号等々や折り返しの諸条件を考えると、なかなか折り合いをつけるのが難しいと感じるので、ずっと開けていたリクエストではありますが、非対応でクローズします。
