### ISSUE TITLE
Additional text selection after word selection is not correct

### ISSUE THREAD

**Issue by shinyaohtani** [coteditor/CotEditor#1302]
### Description

When selecting text, `Shift`+`Option`+`←` and then `Shift`+`←` to select one more character to the left, instead of selecting the character to the left of the left edge, deselects the character at the right edge of the selection area.

### To Reproduce

1. Type, for example, "app-name" in the normal editor window. The cursor will be at the right side of the last "e".
2. Press `Shift`+`Option`+`←` to select a word "name"
3. Then, in that state, press `Shift`+`←` to further select the "-" on the left too.
4. See error. The "-name" is not selected, but "nam" is selected.

### Expected behavior

In the above example, the expected behavior is that "-name" is selected among "app-name".

### CotEditor version

CotEditor: 4.2.0 (502)

### macOS version

System: macOS バージョン12.3.1（ビルド21E258）

### Additional context

Language: Japanese

**Comment by HatsumeAizawa** [comment]
I encountered the same problem.

**CotEditor version**
CotEditor: 4.2.1

**macOS version**
System: macOS 12.3.1

**Additional context**
Language: Japanese
