### ISSUE TITLE
After Update CotEditor problems

### ISSUE THREAD

**Issue by ruelio** [coteditor/CotEditor#1303]
I wish I had more technical details, but, when I launch CotEditor after this past update, it hangs and doesn't load any of my files/tabs. I can sometimes get a file to open but it disappears after some time. Switching to the app doesn't work (Command+Tab). I have to right click it from the dock and select "Open". It shows my files open in the "Window" drop down, but, I still can't get the editor to show them.

I am on Big Sur 11.6.4 and my current version of CotEditor is 4.2

**Comment by 1024jp** [comment]
This issue was fixed on CotEditor 4.2.1. Please update.
