### ISSUE TITLE
"Current Line" in theme setting does not work

### ISSUE THREAD

**Issue by doraTeX** [coteditor/CotEditor#1306]
### Description

The "Current Line" item in the theme setting seems not to work.

<img width="1488" alt="スクリーンショット 2022-05-20 10 40 47" src="https://user-images.githubusercontent.com/6186180/169431787-50510205-e8d9-4d1c-b26a-58a0ec731a74.png">

### To Reproduce

1. Go to Preferences panel and show Appearance view.
2. Select a theme and change "Current Line" color.
3. The setting does not take effect.

### Expected behavior

The background color of the current line changes according to the setting.

### CotEditor version

4.2.1

### macOS version

12.4

**Comment by 1024jp** [comment]
You need to turn the "Change background color" option above on.

**Comment by doraTeX** [comment]
Sorry, I overlooked the item. Thank you!
