### ISSUE TITLE
マルチカーソル中の日本語入力がしたい / Enable multi-cursor input also in Japanese

### ISSUE THREAD

**Issue by hazi** [coteditor/CotEditor#1307]
マルチカーソル実行中に日本語を入力しようすると、マルチカーソルが解除されてしまいます。

対処法として、複数箇所に日本語入力を行いたい時は一旦ほかで書いたものをコピーして、マルチカーソルを配置し、貼り付けています。
Xcodeのようにマルチカーソル中にも日本語入力ができるようになると、この手間が省けるのでとても助かります。

ご検討の程よろしくお願いいたします。

**Comment by 1024jp** [comment]
これは現状、（現在使用しているNSTextViewを使う限り）技術的に無理だという結論に至っています。Appleの人にも前に相談したのですが、できないという回答をもらっています。
なんとか抜け道を見つけたくはあるので諦めたわけではないのですが、すぐには対応できないという回答とさせてください。

**Comment by hazi** [comment]
ご回答ありがとうございます。

何か理由があっての現在の形なんだろうなということは想像していましたが、具体的なご回答をいただけて嬉しいです。
何か解決のきっかけがあるといいのですが、今の私にはその能力はなさそうなので気長に待たせていただきます。

**Comment by 1024jp** [comment]
I close this issue just because of the duplication of #1083.
