### ISSUE TITLE
Outline columns in inspector not resizable

### ISSUE THREAD

**Issue by philip-iii** [coteditor/CotEditor#1310]
### Description

Outline columns in inspector not resizable.

### To Reproduce

1. Open the inspector, 
2. switch to the outline (middle-icon), 
3. try to resize the first column (Title). 

It is usually too narrow and outline titles are correspondingly truncated. There is an indicator that seems to suggest resizing is possible but it does not seem to work.

### Expected behavior

There seem to be no further columns so either the indicator shall be removed and the title shall take all the available space, or the indicator shall work as expected and allow column resizing, ideally taking the whole width of the inspector if there is nothing in the second column.. 

### CotEditor version

4.2.1 (505)

### macOS version

12.3.1 (Build 21E258)

### Additional context

It seems that if the inspector is resized to a size smaller than the first column and then resized to a larger size again, the column indicator disappears and the title column takes up the entire width of the inspector, which is how it show up in the first place.

**Comment by 1024jp** [comment]
Thank you for the feedback. I tried removing such behavior on CotEditor 4.2.0, but it seems to remain in some cases. I adjusted it again to avoid the horizontal scrollor.

Let me know if this issue still exists in the next version, v4.2.2, that will be released in the next week.
