### ISSUE TITLE
Highlight changed line

### ISSUE THREAD

**Issue by sohate** [coteditor/CotEditor#1312]
Hello! Can you add a feature to highlight line that have been changed so a user can see what's line was changed. Thanks!

**Comment by 1024jp** [comment]
Hi, do you mean the change from the last save or the change from the last commit in git or something?

If you meant the first one, finding diff in large documents is heavy loading that I want to avoid. Furthermore, CotEditor prefers autosaving (although you can disable it), thus managing unsaved points is less important. 

If you meant the latter one, we already received the same request in #1276. So this ticket is a duplicate.

**Comment by 1024jp** [comment]
I close this ticket because of no reply. Anyway, as I mentioned above, this request is either not to implement or duplicate.
