### ISSUE TITLE
Syntax style information in scripting environment

### ISSUE THREAD

**Issue by lsundman** [coteditor/CotEditor#1314]
Hi!

I hope this is not a duplicate!

I was trying out the CotEditor scripting capabilities today for formatting JavaScript files using Prettier and Python files using Black.

Making a Bash script to format the frontmost document is straightforward, but at this time it seems you have to make a new script for each language you are using in order to call the right tool. Is there any way to get information about which language CotEditor has parsed the file as in either the Unix or AppleScript environment?

As an example, my workflow in BBEdit is to have a single Bash script for formatting, bound to e.g. <kbd>⌃</kbd> +  <kbd>⇧</kbd> + <kbd>f</kbd>, that formats the document regardless of the language. BBEdit supplies the script environment with a variable `$BB_DOC_LANGUAGE` containing the language of the file and the formatting script can adapt to that to choose the right tool.

Having a single script to do this is nice since you can always just hit the same key combination and format the file no matter the language.

Thanks for making a cool editor! 🙂

**Comment by 1024jp** [comment]
Hi. Thank you for the request.
I found your request good, but it seems Apple does not provide any API to set environment variables in the Sandboxed setting.
Therefore, the implementation might unfortunately be tough.

**Comment by lsundman** [comment]
Ah, I see, that's a shame! Thanks for taking a look at it. 🙂
