### ISSUE TITLE
Color identifier in text

### ISSUE THREAD

**Issue by tosbsas** [coteditor/CotEditor#1316]
I am looking for an option to resolve as a colored dot hex colors in coteditor.

For example #000000 would carry a "black" color dot before the number (or after)
# ffffff a "white" color dot.

I am designing themes for telegram and that would be really helpful as their web editor s***ks

**Comment by 1024jp** [comment]
Sorry, I don't know what the "color(ed) dot" means.

CotEditor has the color code panel, which you can open from Text > Edit Color Code in the menu. Does it help your issue?

<img width="322" alt="Screen Shot 2022-05-31 at 8 35 54" src="https://user-images.githubusercontent.com/1165044/171068234-6f7c2e78-681c-4c55-9b64-20bd3d9626f3.png">

**Comment by 1024jp** [comment]
Maybe, now I understand what you meant.
Your request is to add color sample tips just after every color code in the document indicating the color of the color code. Right?

I have seen a SIMBL plug-in for CotEditor realizing such a feature by a user a long time ago, but couldn't find it anymore (and SIMBL might not work under modern macOS).

I don't prefer implementing such a feature only for specific languages to CotEditor natively to keep CotEditor simple and clean.
So sorry, I need to reject your request.

**Comment by tosbsas** [comment]
Took a picture /-) 






______________________________
Ruben Gutknecht
Lima, Perú  🇵🇪 
Cel: +51-99349-1515
Voice/Fax: 49 (0) 721-151-379204
http://telegram.me/tosbsas
paypal.me/RubenGutknecht
***@***.***
