### ISSUE TITLE
Store temporary files somewhere else than the current file folder

### ISSUE THREAD

**Issue by ceyquem** [coteditor/CotEditor#1319]
**Is your feature request related to a problem? Please describe.**
I am using CotEditor to develop a website in PHP. When synchronizing the code, I am seeing all files including temporary files that CotEditor is storing (e.g. for index.php there is an ._index.php created in the same folder). It is annoying as it makes it difficult to see what are the real files to sync from the rest.

**Describe the solution you'd like**
It would be great if these temp files could be stored somewhere else, in a common temp folder of the application itself.

**Describe alternatives you've considered**
I was using Notepad++ for Windows before, I want to switch to a native MacOS solution and CotEditor seems the best alternative. There is just this frustrating temp file thing that NP++ does not have :-).

**Comment by 1024jp** [comment]
Thank you for the feedback.

But sorry, I can't get what you say very well. In general, CotEditor doesn't save temporary files, except for the files that exist only while saving the document in CotEditor; it takes only a few seconds. Do you talk about that, or something else?
Could you elaborate on what those temporary files mean? It would be great if you attach screenshots indicating such a file.

> (e.g. for index.php there is an ._index.php created in the same folder)

CotEditor does not create such files. Maybe, some other program does.

**Comment by 1024jp** [comment]
I close this ticket because this issue seems not related CotEditor. But feel free to let me know if you have further information.
