### ISSUE TITLE
Add SJIS bytes to Info/Count/Characters 

### ISSUE THREAD

**Issue by shiontamura** [coteditor/CotEditor#1322]
**Is your feature request related to a problem? Please describe.**
No. 

**Describe the solution you'd like**
-  リクエスト：Info > Count > Characters 欄で選択部分のSJIS bytes（半角換算文字数）も確認できると良い
- 理由：Google Adなど、半角文字数にて制限が設定されたテキスト作成時、日本語、半角英数字のまざった文章の半角換算合計文字数をリアルタイムに確認するため

**Describe alternatives you've considered**
上記理由により、Google Adテキスト作成時は、選択部分のSJIS bytesが確認できるJedit Ωを使っています。

**Comment by 1024jp** [comment]
リクエストありがとうございます。
文字のカウント方法はかなり多岐にわたたり、この辺を整理して新しく文字カウント機能を導入したい気持ちはあるので、具体的なスケジュールは切っていないのですぐにとは言えないのですが暫しお待ちください。SJISの数え方はそのようなユースケースがあるとは知らずあまり考慮に入れていなかったので、新しい文字カウント機能の実装の際は取り込みたいと思います。ご説明ありがとうございます。

**Comment by 1024jp** [comment]
次バージョンであるCotEditor 4.4.0で「高度な文字カウント」という新しい機能を追加するのですが、その中で各エンコードのバイト長のカウントもリアルタイムでできるようにオプションを作りました。
高度な文字カウントはあえてオプションで明示的にカウンターを表示させる形式を取っているので、元のリクエストにあった書類インスペクタでのカウント表示とは少々異なりますが、ニーズは満たせたかと思います。

<img width="624" alt="Screen Shot 2022-07-17 at 17 08 45" src="https://user-images.githubusercontent.com/1165044/179391811-befad131-31e2-4c0f-b65b-27662b169f4b.png">


CotEditor 4.4.0はmacOS 13 Ventureと合わせてリリースにしようと考えているのでこの秋にリリース予定です。
手前でβテストをするので、またその時に連絡します。

**Comment by shiontamura** [comment]
素晴らしいアップデート、ありがとうございます。添付画像の通り日本語、半角英数字混合文にて合計バイト数の確認ができれば、Google Adなどのテキスト作成には十分です。

私は添付画像の通りで全く問題ありませんが、他のユーザーの混乱、無用なサポート業務を避けるには、単位にて「バイト」を選択したときは「9バイト」と表示されるなど、選択単位に応じて表示も変わると良いかもしれません。

**Comment by 1024jp** [comment]
なるほど！ 確かにバイトの時は単位も「バイト」の方がわかりやすいですね。提案ありがとうございます。変更します。
