### ISSUE TITLE
Open file in new tab after drag & drop

### ISSUE THREAD

**Issue by cgm-aw** [coteditor/CotEditor#1323]
**Is your feature request related to a problem? Please describe.**
It would be great to open a file that was dropped into the editor in a new tab (as recommended in https://github.com/coteditor/CotEditor/issues/967)

**Describe the solution you'd like**
I would like to have a variable in the file drop menu like `<<<FILECONTENT IN NEW TAB>>>`. When selected, a file dropped into the editor will open a new tab and show the contents of the file.

Best regards

**Comment by 1024jp** [comment]
This is actually a pretty popular request over years. However, so far, I don't implement it because it is not a natural behavior on Mac. Sorry.

**Comment by ADTC** [comment]
Please give us a choice in Settings. It's not about what's natural on Mac, but about what's productive for the user. Indeed, the fact that it's "a pretty popular request over years" shows that many users find it productive and desire it, even if it's not a default behavior or the "Apple way" of doing things. Kindly consider it. VSCode does this wonderfully, and I really dislike that many "Mac-natural" text editors do not. TextMate developer refused this as well, and I'm sad if you would too.

Also see: https://github.com/coteditor/CotEditor/issues/1771#issuecomment-2520370650

**Comment by ADTC** [comment]
At least, holding Shift key when dropping could do it?

**Comment by 1024jp** [comment]
No, I won't do it.
Read the [Document-Based App Programming Guide for Mac](https://developer.apple.com/library/archive/documentation/DataManagement/Conceptual/DocBasedAppProgrammingGuideForOSX/Introduction/Introduction.html) through and you’ll know how document-based macOS apps are designed.

**Comment by ADTC** [comment]
Apple is not the Bible of UIUX. It's merely an opinion and it's a shame if one blindly follows that opinion and worships it as an infallible ideology.

Anyway, to each his own. I will keep searching for an editor that's better fit for my needs. Thank you for your time.

**Comment by russeg** [comment]
First thing I did when was to drag a text file from the desktop.  It did something weird to modern mac users.

Deleted this editor immediately.

**Comment by ADTC** [comment]
@russeg good job 🤪
