### ISSUE TITLE
Line Endings for macOS Not Correct

### ISSUE THREAD

**Issue by gregarios** [coteditor/CotEditor#1324]
### Description

All returns are now "\r\n" instead of just "\n" in documents.

This is a change in behavior.

### To Reproduce

I open documents trhat AppleScript was previously able to replace "\n" characters but now to replace returns in Applescript I must use "\r\n" every time -- even if i do a find/replace and try to change them all to plain "\n" earlier in the script.

### Expected behavior

All my documents should use unix and Mac style "\n" for returns in documents, not the old carriage return and line feed combination -- especially when the settings are set to macOS/Unix (LF) style line endings.

### CotEditor version

4.2.3 (510)

### macOS version

12.4 (Build 21F79)

**Comment by 1024jp** [comment]
CotEditor changed how it handles line endings in version 4.2.0, which was released last month. Is that the case you face? (cf. [Important changes on CotEditor 4.2](https://coteditor.com/news/2022/CotEditor_4.2.0))
Please check your scripts if it works with the new specification.

> All my documents should use unix and Mac style "\n" for returns in documents, not the old carriage return and line feed combination -- especially when the settings are set to macOS/Unix (LF) style line endings.

If the document has LF line endings, CotEditor must pass strings with LF to the AppleScript as-is.

At least in my environment, the latest CotEditor seems to be able to handle line endings properly.

<img width="730" alt="Screen Shot 2022-06-16 at 9 20 52" src="https://user-images.githubusercontent.com/1165044/173963743-07d3ebf0-9900-4cbb-8cdf-17b210f2aa40.png">


If CotEditor still creates the wrong "\r\n" somewhere in the process, provide a sample script with a target document file that can reproduce your issue. Then, I'll look into it further.

**Comment by gregarios** [comment]
Ah I see the problem now. For some reason when I open a plain text document from a friend it somehow senses that the document has "CRLF" line endings instead of "LF" that my script needs.
I have added "set line ending to LF" to my AppleScript to remedy this.
