### ISSUE TITLE
Context sensitive commands

### ISSUE THREAD

**Issue by persquare** [coteditor/CotEditor#1330]
Hi, 
first of all thanks for an excellent open source editor!

When you have lots of scripts, it would be nice to be able to assign the same key combo to scripts that perform the same action but in different contexts. As an example, the boilerplate code request from #1166 could be handled by letting e.g. ⌘B invoke different scripts depending on file type (LaTeX/HTML/Python/etc). Similarly, ⌘⌥P could invoke different preview scripts for HTML and LaTeX. Such an approach makes it easier to rely on muscle memory :)

I guess what would be needed is to add something like `%%%{CotEditorScope=LaTeX}%%%` to the script and use that when selecting what script to pick for a key combo.

Just my 2¢,
Per

**Comment by 1024jp** [comment]
Thank you for the feedback.

I also thought about this kind of idea before when I adopted this project. So I understand your demand.

One problem with your approach is scanning all user scripts every time on the application launch is a bit high cost.
So, how about the approach to using subfolders to prioritize specific scripts for keyboard shortcuts.

First, let's say you have the following folder structure in the Script Folder:
- Script Folder
    - Preview (⌘R)
    - HTML
        - Reload Browser (⌘R)
        - ...
    - Markdown
        - Preview (⌘R)
        - ...

You can see there are multiple scripts having ⌘R for keyboard shortcuts. Then, in this situation, if the syntax style of the frontmost document is Markdown and the user press ⌘R, the Preview script in the Markdown will be performed. Likewise, if the syntax style of the document is HTML, the Reload Browser will be performed. Finally, the Preview script in the root will be performed only when there is no shorcut competitor in the subfolders.
The disadvantage of this subfolder approach is, however, users need to have multiple same files if they want to priotarize a specific script for multiple syntax style. Addmiting that, I think it works in most cases.

What do you think? Is this approach solve your issue? If it seems reasonable, I'll implement it.

![Image 2022-07-06 at 12 45](https://user-images.githubusercontent.com/1165044/177463741-c329dd96-5c75-4d36-b48e-e8c2bc7e8078.jpg)

**Comment by persquare** [comment]
Sounds like a clean, straightforward solution to me. Thanks!
