### ISSUE TITLE
And a switcher of banning the checking of the newline character when open any doc

### ISSUE THREAD

**Issue by jqorz** [coteditor/CotEditor#1331]
When I open a file, it always tell me to convert all newline character, it bother me, so I want to add a switcher to close the checking

**Comment by 1024jp** [comment]
First, please use the [template](https://github.com/coteditor/CotEditor/issues/new?assignees=&labels=request&template=feature_request.md&title=) when posting a feature request.

I do not prefer to add a GUI setting for this.
Instead, how about storing the state of the “Don’t ask again for this document” option in the document file as metadata and respecting the state also for future opens?

<img width="310" alt="Screen Shot 2022-07-07 at 18 52 40" src="https://user-images.githubusercontent.com/1165044/177746013-7c117c12-b9bb-4612-a500-8d87aec2bd23.png">

**Comment by 1024jp** [comment]
I also added a default key named `suppressesInconsistentLineEndingAlert` but without GUI. On CotEditor 4.4.0, which will be released this fall, you can turn off the future entirely when you run the following command in the terminal: `defaults write com.coteditor.CotEditor suppressesInconsistentLineEndingAlert -bool YES`.
