### ISSUE TITLE
Scroll past last line

### ISSUE THREAD

**Issue by underdog681** [coteditor/CotEditor#1336]
It would be nice to be able to scroll past the last line like your able to in other editors.

**Comment by 1024jp** [comment]
Do you mean the overscroll option in Preference > Window?

<img width="682" alt="Screen Shot 2022-07-22 at 10 18 54" src="https://user-images.githubusercontent.com/1165044/180341088-88ca1ebc-2087-412e-a1b5-4e5915441e5a.png">

**Comment by underdog681** [comment]
Have not seen it as a setting like this in other editors and google turned up nothing. Sorry to trouble you but thank you for the help
