### ISSUE TITLE
Tab width set via format menu is not respected when printing

### ISSUE THREAD

**Issue by boeckmann** [coteditor/CotEditor#1338]
### Description

Tab width defaults to 4 when printing even if tab width is set to 8 via format menu.

### Expected behavior

Printing should respect tab format set via menu.

### CotEditor version

4.3.1

### macOS version

12.4

**Comment by 1024jp** [comment]
Do you use the same font as the editor for printing?
Please provide the screenshots of the Appearance pane and the Print pane like the following.
<img width="682" alt="Screen Shot 2022-07-29 at 22 30 47" src="https://user-images.githubusercontent.com/1165044/181770907-0f60421d-859e-402c-a2c0-cfbca30c9573.png">
<img width="682" alt="Screen Shot 2022-07-29 at 22 30 44" src="https://user-images.githubusercontent.com/1165044/181770942-5edfde90-de81-456f-b0b7-64090b7952dc.png">

**Comment by 1024jp** [comment]
Thank you for the report. I confirmed the issue.
I'll release the fix soon.

**Comment by boeckmann** [comment]
Indeed the printing font is not the display font
<img width="545" alt="Bildschirmfoto 2022-07-29 um 15 34 44" src="https://user-images.githubusercontent.com/6333969/181771822-adf823d0-8365-4a48-89a7-ce28f8b7d955.png">
<img width="549" alt="Bildschirmfoto 2022-07-29 um 15 34 17" src="https://user-images.githubusercontent.com/6333969/181771829-07e12045-a411-4450-9bb2-ca39d1d3c7a4.png">
.

**Comment by 1024jp** [comment]
I've just released CotEditor 4.3.2 which fixes this issue.
Please let me know if there still is some issue.

**Comment by boeckmann** [comment]
Thanks! It is now working as expected :-)
