### ISSUE TITLE
Add shell syntax 

### ISSUE THREAD

**Issue by aretrace** [coteditor/CotEditor#1344]
Add Z shell (Zsh) / Bash syntax highlighting.

**Comment by 1024jp** [comment]
Is the normal Shell syntax style not enough?

**Comment by aretrace** [comment]
Originally Cot was not recognizing my zsh files but a quick reinstall seemed to fix it, closing issue.

**Comment by 1024jp** [comment]
Ok, that's good to hear. Thank you for the following up.
