### ISSUE TITLE
add groovy syntax

### ISSUE THREAD

**Issue by bayanijulian** [coteditor/CotEditor#1347]
Syntax highlighting/support for [groovy](https://groovy-lang.org/syntax.html). 

Groovy is syntactically similar with Java syntax.

Besides groovy files, other common file types use groovy for implementing a DSL - Jenkins _(Jenkinsfile)_, gradle _(gradle.build, settings.gradle_.

**Comment by 1024jp** [comment]
I feel Groovy is not popular enough to bundle to CotEditor.app. I prefer to create a syntax style by yourself and share it somewhere, like the ones in [Additional Syntax Styles](https://github.com/coteditor/CotEditor/wiki/Additional-Syntax-Styles).
