### ISSUE TITLE
Multi cursor affects wrapped around lines

### ISSUE THREAD

**Issue by BorjaLL** [coteditor/CotEditor#1348]
### Description

When using multi cursor ^⇧↑ and ^⇧↓ wrapped around lines are affected

<img width="86" alt="image" src="https://user-images.githubusercontent.com/3930245/185594271-68285cfa-32e0-4cb7-a058-255dc700e874.png">

in the above screenshot the middle of line 8 is selected
If I hit delete, P, M and P are deleted

<img width="94" alt="image" src="https://user-images.githubusercontent.com/3930245/185594429-2c9e0b8d-d620-4be5-8aeb-898ccdc62ced.png">

The expected behaviour would be to only affect the main lines

### To Reproduce

1. Go to any text document with wrap around lines
2. Select multiple lines with the multi cursor
3. hit delete

### Expected behavior

only the main lines should be affected by the multi cursor

### CotEditor version

4.3

### macOS version

12.5

**Comment by 1024jp** [comment]
This is by design. For instance, Xcode behaves in the same manner.
