### ISSUE TITLE
Unsaved Changes Indicator

### ISSUE THREAD

**Issue by dtoniolo** [coteditor/CotEditor#1349]
First of all, thanks for this amazing editor. I come from Atom and CotEditor is much faster, lighter on memory and better integrated with the OS.

In order to avoid saving experimental changes, I prefer to run CotEditor with automatic saving disabled. My workflow frequently involves making changes with CotEditor and then running the program I just modified from the terminal. However, I often forget to to save the file before running (my bad, but with many open files it can happen!) and CotEditor is currently lacking a visual indicator for the presence of unsaved modification.

I'd love to see this feature added, maybe with a dot next to the file name, like Atom does.

Thanks again and congrats!

**Comment by 1024jp** [comment]
Not only on CotEditor but also on every (well-designed) macOS applications have the saving indicator already in the close button. When the document has unsaved state, a dot appears in the close button (see the screencast below). So you can check it to know the state. In addition, from the next version of CotEditor, which will be released this fall, I'll add the same kind of indicator for window tabs #904.

https://user-images.githubusercontent.com/1165044/186053823-d590b995-0e5f-4655-bf6d-b8b64d791f84.mov

**Comment by dtoniolo** [comment]
I had never noticed this, thank you! Sorry for opening this issue then🙌🏻
