### ISSUE TITLE
CotEditor non-AppStore version 4.3.4 is not available for download

### ISSUE THREAD

**Issue by DAnn2012** [coteditor/CotEditor#1351]
### Description

Hello @1024jp 

CotEditor non-AppStore version 4.3.4 is not available for download

Thanks.

### To Reproduce

1. Go to https://coteditor.com/archives
2. Click on 'CotEditor 4.3.4' https://github.com/coteditor/CotEditor/releases/download/4.3.4/CotEditor_4.3.4.dmg
3. See error 404

But the update via Sparkle within CotEditor 4.3.3 also doesn't work

### Expected behavior

The ability to download CotEditor non-AppStore version 4.3.4

### CotEditor version

4.3.4

### macOS version

12.5.1

**Comment by 1024jp** [comment]
Aaah! Thank you for pointing it out.
I totally forgot to make the release public.
Now it should work.

https://github.com/coteditor/CotEditor/releases/tag/4.3.4
