### ISSUE TITLE
Add syntax highlighting for .s assembly files

### ISSUE THREAD

**Issue by Thenlie** [coteditor/CotEditor#1352]
It appears that assembly code is not supported at this point. It would be great to add that in!

**Comment by 1024jp** [comment]
Sounds interesting. I'll try it.

**Comment by 1024jp** [comment]
The Assembly syntax will be added on the next minor update, which will be released this autumn.

**Comment by Thenlie** [comment]
Thank you @1024jp! Appreciate your continued work on this project and looking forward to the update. <3
