### ISSUE TITLE
Saving a new file fails on a volume mounted using Cryptomator / macFUSE

### ISSUE THREAD

**Issue by mzinner** [coteditor/CotEditor#1353]
### Description

When trying to save a newly created file on a volume I mounted with Cryptomator 1.6.14 (that uses macFUSE 4.4.1 on the backend), CotEditor errors out with the following error statement.

The document "Untitled" could
not be saved as "Test.txt".
Operation not permitted

Strange thing is that the file actually gets stored correctly on the volume using the given name. Opening that file and storing that file also does work.

It is just the initial save operation that fails.

<img width="1462" alt="Screenshot 2022-09-02 at 17 28 35" src="https://user-images.githubusercontent.com/37372663/188191348-331c7eb3-89ea-49eb-9fd4-f8d489fa0f7d.png">

### To Reproduce

1. Download and install the latest macFUSE from [https://osxfuse.github.io/](https://osxfuse.github.io/) and Cryptomator from [https://cryptomator.org/downloads/](https://cryptomator.org/downloads/)
2. Create a new Cryptomator volume and mount it.
3. Start CotEditor, type in some text and select File -> Save As ..., select the Cryptomator volume and enter a file name "Test.txt". 
4. Press Save and see the error:
The document "Untitled" could
not be saved as "Test.txt".
Operation not permitted
5. Verify that the file has been written properly onto the Cryptomator volume and open it, modify it and change it without issues.

### Expected behavior

The save operation should not fail when storing a new file onto a Cryptomator volume.

### CotEditor version

4.3.4

### macOS version

12.5.1

**Comment by 1024jp** [comment]
Thank you for the feedback.
However, I prefer not to install such software in my development environment to confirm the issue, although I don't think they are dangerous.
CotEditor is designed to work with the standard macOS environment; so this is out of our target.
Sorry.

Please let me know if you can reproduce the issue without a specific setup.
Also, I welcome PRs to fix the issue.
