### ISSUE TITLE
Width of line numbers column not adjusted when file grows on disk

### ISSUE THREAD

**Issue by matzepf** [coteditor/CotEditor#1356]
### Description

The width of line numbers column is not adjusted when file grows on disk.

<img width="175" alt="LineNumbers1" src="https://user-images.githubusercontent.com/36540028/189287298-5d528f32-17eb-4924-a046-4294f0832ee9.png">

<img width="199" alt="LineNumbers2" src="https://user-images.githubusercontent.com/36540028/189287330-faa76b9c-2b33-4b64-9638-201c382dc1f2.png">

### To Reproduce

1. Have a file open in CotEditor with line numbers visible and CotEditor automatically update when the file changes on disk.
2. Grow the file on disk so the number of digits in the line numbers increase.
3. Close and re-open the file to fix the problem.

### CotEditor version

4.3.4

### macOS version

12.5.1

**Comment by 1024jp** [comment]
Thank you for the report!
I'll fix it in CotEditor 4.4.0.

**Comment by 1024jp** [comment]
Today, I released CotEditor 3.4.5, which fixes this issue.
