### ISSUE TITLE
The default width of the outline columns is narrow and the margins are large.

### ISSUE THREAD

**Issue by ksota0133** [coteditor/CotEditor#1365]
### Description

 The default width of the outline columns is narrow and the margins are large.

### To Reproduce

The initial width of the outline columns is narrower relative to the outline sidebar, resulting in larger margins in the sidebar.

Workaround:
If the outline sidebar width is narrowed below the outline column width and then stretched, the outline column width will follow and expand.

### Expected behavior

I would like the outline column to always be the same width as the sidebar.

### CotEditor version

CotEditor: 4.3.2 (522)

### macOS version

System: macOS Version 12.4 (Build 21F79)

**Comment by 1024jp** [comment]
Thank you for the feedback. I confirmed the issue.
I'll try to fix it in the next minor update.

**Comment by 1024jp** [comment]
I looked into it and found this would be a long-standing bug in AppKit.
cf. https://twitter.com/icanzilb/status/973174639454191617

Anyway, I added a workaround to the next version.

**Comment by 1024jp** [comment]
Today, I released CotEditor 3.4.5, which fixes this issue.

**Comment by ksota0133** [comment]
Thanks for the quick fix!
