### ISSUE TITLE
a selection is copied to the clipboard with quotation marks added at the beginning of selection each line.

### ISSUE THREAD

**Issue by stein2nd** [coteditor/CotEditor#1366]
We would like the feature where a selection is copied to the clipboard with quotation marks added at the beginning of selection each line, like Sakura Editor.

Sakura Editor に搭載されている様な、選択範囲の各行頭に、引用符を付加した状態で、クリップボードにコピーされる、という機能がCotEditorにも搭載されることを希望します。

**Comment by 1024jp** [comment]
To keep the user interface clean and minimal, I suppose general text editors like CotEditor should not implement such a very specific feature.

Instead, I recommend writing your own script to realize. In CotEditor scripting, you can use the keyword `%%%{CotEditorXInput= Selection}%%%` to obtain the selected text and `%%%{CotEditorXOutput= Pasteboardputs}%%%` to set modified text to the pasteboard. See the help bundled for the detail of how to script CotEditor.
