### ISSUE TITLE
AutoSave in to Custom Folder

### ISSUE THREAD

**Issue by vlad-infra-admin** [coteditor/CotEditor#1373]
There is an option Enable Auto Save with Versions. It saves files in to iCloud Drive>CotEditor.
I don't want them there. I can't change it to custom folder. 

It would be great if I can change auto save folder to my own in Settings > General .

**Comment by 1024jp** [comment]
Sorry, but I have no plans to implement such a feature at the moment in order to avoid the file-managing architecture being more complex.
