### ISSUE TITLE
Hang when using keyboard to select text of certain pattern

### ISSUE THREAD

**Issue by gingerbeardman** [coteditor/CotEditor#1386]
### Description

- hard crash when using keyboard to select text of certain pattern

### To Reproduce

1. Open file [crash.txt](https://github.com/coteditor/CotEditor/files/9841451/crash.txt)
2. Select text using keyboard alt+shift+cursor
3. When cursor gets between `~` and `\` the app hangs

### Expected behavior

- should not hang

### CotEditor version

4.3.6

### macOS version

12.6 (21G115)

### Additional context

text at that location (viewed in Sublime Text)

![Screen shot 2022-10-21 at 19 24 36](https://user-images.githubusercontent.com/49612/197264135-54f74237-a54f-4888-8971-ca679d018d57.png)

- crash reports
  - [CotEditor_2022-10-21-191913_matt.cpu_resource.diag.zip](https://github.com/coteditor/CotEditor/files/9841503/CotEditor_2022-10-21-191913_matt.cpu_resource.diag.zip)
  - [CotEditor_2022-10-21-192118_matt.wakeups_resource.diag.zip](https://github.com/coteditor/CotEditor/files/9841523/CotEditor_2022-10-21-192118_matt.wakeups_resource.diag.zip)
  - [CotEditor_2022-10-21-192157_matt.hang.zip](https://github.com/coteditor/CotEditor/files/9841529/CotEditor_2022-10-21-192157_matt.hang.zip)
- screen recording
  - beachball cursor is not shown due to Quicktime recording capability
  - https://user-images.githubusercontent.com/49612/197262971-b4f5b400-d444-409d-883b-3cca4bc741c8.mov

**Comment by 1024jp** [comment]
Thank you for the report.
I succeed in reproducing the issue in my environment.
I found an additional condition that it happens only when the invisible control characters between `~` and `\` are hidden.
I'll try to fix it in CotEditor 4.4.1.
