### ISSUE TITLE
Concordance Feature

### ISSUE THREAD

**Issue by Berovowilare** [coteditor/CotEditor#1388]
Hello 

I would love to have a concordance feature. 
Either over all and/or we can select a part and press the button or an option on the right click.. Another window is opened and displays the results. 

The output should be able to filter count up, count down, alphabetical.

Cool would be if we can double click on each word and it leads automatically to the hits in the text (main window). For example it shows all the lines with the hits (Find all).

Today I have always first to import it in another app to get the results. I add a screenshot of what I mean.

<img width="644" alt="Bildschirm­foto 2022-10-23 um 10 26 12" src="https://user-images.githubusercontent.com/36891575/197382232-e6d46093-ce90-4267-b0ed-c37dbdbc3df2.png">
<img width="643" alt="Bildschirm­foto 2022-10-23 um 10 26 23" src="https://user-images.githubusercontent.com/36891575/197382238-d68128fb-0d9a-427b-9eb4-fb1e3d51c516.png">

In English
<img width="644" alt="Bildschirm­foto 2022-10-23 um 10 37 05" src="https://user-images.githubusercontent.com/36891575/197382670-f116127e-5b28-4ab2-b1c1-3098f87107c0.png">
<img width="644" alt="Bildschirm­foto 2022-10-23 um 10 37 14" src="https://user-images.githubusercontent.com/36891575/197382679-3adc87f6-7f98-4483-b471-6e16b0107a8e.png">

As you are from Japan/Nippon
<img width="641" alt="Bildschirm­foto 2022-10-23 um 10 38 37" src="https://user-images.githubusercontent.com/36891575/197382734-1776b412-d78b-47d5-bc24-6b4ae4b2f41c.png">
<img width="647" alt="Bildschirm­foto 2022-10-23 um 10 38 43" src="https://user-images.githubusercontent.com/36891575/197382739-450cd671-aa4c-4658-8baa-f877372b843a.png">

An image after double click. It shows all the lines with the hits.
<img width="1360" alt="Bildschirm­foto 2022-10-23 um 10 40 58" src="https://user-images.githubusercontent.com/36891575/197382820-784d8874-e801-4109-8e41-0254e8fba842.png">

The problem is, I cannot edit them in this app. So I would love if your app would be able to do this too.

Thanks

**Comment by 1024jp** [comment]
Thank you for the request.
However, I feel it would be better to make your script instead of implementing it to CotEditor itself to avoid the CotEditor's menu becoming messed up due to minor commands.
