### ISSUE TITLE
[v4.4.0] 繁体中国語の翻訳についてですが。

### ISSUE THREAD

**Issue by ShikiSuen** [coteditor/CotEditor#1391]
### Description

<img width="471" alt="image" src="https://user-images.githubusercontent.com/3164826/198348475-7fd52131-cf2b-4578-bfb5-a3dc4c9ad977.png">

Find All = 檢索全部
Select All = 選擇全部

### To Reproduce

Press "Command+F".

### CotEditor version

4.4.0

### macOS version

Ventura 22A380

### Additional context

署名についてですが、簡体中国語の翻訳に基づいてから完成したものであるため、
私だけでなく、@onevcat さんの名前も一緒に署する必要があると思いますが。
それについて onevcat さんのご意見（特に異存の有無）も伺う必要があると思います。

<img width="299" alt="image" src="https://user-images.githubusercontent.com/3164826/198348864-f9fd67c1-be63-4132-861a-3484ae753088.png">

**Comment by ShikiSuen** [comment]
タグ間違くてすみません。けどこちらはタグを編集する権限はなさそうです。

**Comment by 1024jp** [comment]
Thank you for the report!

Regarding the first issue, some text in the new Replace All button are not localized, it is my fault. I totally forgot to ask people to localize the line that was added in the very last phase of release of 4.4.0.

> 署名についてですが、簡体中国語の翻訳に基づいてから完成したものであるため、
> 私だけでなく、@onevcat さんの名前も一緒に署する必要があると思いますが。
> それについて onevcat さんのご意見（特に異存の有無）も伺う必要があると思います。

You are right. I'll add it.

**Comment by 1024jp** [comment]
Updated in 950b99475288559d6d0447b2c624ed7b16222655.

**Comment by 1024jp** [comment]
@ShikiSuen 
> Find All = 檢索全部
> Select All = 選擇全部

これは「全部檢索」と「全部選擇」にした方が他項目と合うと思いますがいかがでしょうか？

**Comment by ShikiSuen** [comment]
@1024jp そうしましょう。

**Comment by 1024jp** [comment]
ありがとうございます！
