### ISSUE TITLE
[4.4.0] Behavior about scripts has changed

### ISSUE THREAD

**Issue by tatsy-ymj** [coteditor/CotEditor#1392]
## Environment (環境)

- CotEditor: 4.4.0 (540)
- System: macOS バージョン13.0（ビルド22A380）
- Language: Japanese

## Short Description (簡単な説明)

Behavior about scripts has changed in CotEditor 4.3.6 and 4.4.0, and scripts that used to work no longer work.

## Steps to Reproduce the Issue (不具合が発生したときに行っていた操作、または再現手順)

1. In CotEditor 4.3.6, process the following sample text.

```
見出し1

ダミー文章ダミー文章ダミー文章ダミー文章。
ダミー文章ダミー文章ダミー文章ダミー文章。

# 見出し2

ダミー文章ダミー文章ダミー文章ダミー文章。
ダミー文章ダミー文章ダミー文章ダミー文章。
```

<img width="832" alt="スクリーンショット 2022-10-30 14 51 15" src="https://user-images.githubusercontent.com/4995795/198865160-0f74ee96-9971-44a1-b04c-31a90c342ca8.png">

2. With the cursor on the first line of the sample text, run the following script from the AppleScript editor. This script is for changing the heading level in Markdown.

```
tell application "CotEditor"
	if exists front document then
		tell front document
			if coloring style is not in {"Markdown"} then
				quit
			end if
			
			-- get selection's positional data
			set {locLength, selectionLength} to range of selection
			set {locLines, selectionLines} to line range of selection
			set looseSelect to 0
			-- whole lines select
			if (selectionLines is greater than or equal to looseSelect as number) then
				set line range of selection to {locLines, selectionLines}
				set {locLength, selectionLength} to range of selection
			end if
			
			-- ignore last line break
			if contents of selection ends with "
" then set range of selection to {locLength, selectionLength - 1}
			
			-- get contents
			set theSelection to contents of selection
			if rich text 1 of theSelection is equal to "#" then
				set contents of selection to "#" & theSelection
			else
				set contents of selection to "# " & theSelection
			end if
		end tell
	end if
end tell
```

<img width="931" alt="スクリーンショット 2022-10-30 15 11 32" src="https://user-images.githubusercontent.com/4995795/198865189-0188bd5c-1691-4ddf-af49-603cbb0fbc01.png">

3. A "#" is added to the beginning of "見出し1" to make it a heading.

<img width="832" alt="スクリーンショット 2022-10-30 14 51 29" src="https://user-images.githubusercontent.com/4995795/198865198-43f0e004-f6cc-44bf-baa0-f02c456097e3.png">

4. When I perform the same process on CotEditor 4.4.0, I get the following results.

```
# 見出し1

ダミー文章ダミー文章ダミー文章ダミー文章。
ダミー文章ダミー文章ダミー文章ダミー文章。

# 見出し2

ダミー文章ダミー文章ダミー文章ダミー文章。
ダミー文章ダミー文章ダミー文章ダミー文章。




ダミー文章ダミー文章ダミー文章ダミー文章。
ダミー文章ダミー文章ダミー文章ダミー文章。

# 見出し2

ダミー文章ダミー文章ダミー文章ダミー文章。
ダミー文章ダミー文章ダミー文章ダミー文章。


```

<img width="832" alt="スクリーンショット 2022-10-30 14 52 42" src="https://user-images.githubusercontent.com/4995795/198865203-d2f581fa-374f-4a8d-bc29-258cc6d27e33.png">

Lines after the first line have been copied and added to the end of the file.

Was there a change in the handling of line breaks in the upgrade from 4.3.6 to 4.4.0?

### CotEditor version

CotEditor: 4.4.0 (540)

### macOS version

macOS バージョン13.0（ビルド22A380）

**Comment by 1024jp** [comment]
Oops. Thank you for the report.
This is definitely a bug on 4.4.0.
I've just updated the code so it will be fixed in the next CotEditor 4.4.1.
