### ISSUE TITLE
An odd bahavior on searching with only selection

### ISSUE THREAD

**Issue by tatsy-ymj** [coteditor/CotEditor#1393]
### Description

When I attempt to search only a selection, strange behavior is observed.

### To Reproduce

1. Select characters with the following text.

<img width="737" alt="スクリーンショット 2022-11-02 17 54 39" src="https://user-images.githubusercontent.com/4995795/199444525-9ea1f5f0-f000-4844-8dca-621d0d07ba93.png">

2. Search "ある" with the selection.
<img width="689" alt="スクリーンショット 2022-11-02 17 55 36" src="https://user-images.githubusercontent.com/4995795/199445115-af875f3f-7171-41a3-bcfb-2cc9f3833c0e.png">

3. Click ">" in the search panel. Although there are three "ある" in the selection, a cursor doesn't move to the next "ある". When I close the search panel, the selection is released.

### Expected behavior

When searching with a selection, the selection should be maintained.

### CotEditor version

4.4.0 (540)

### macOS version

Ventura 13.0

**Comment by 1024jp** [comment]
This is by design.
After the first "ある" is selected, the selection is changed from the initial selection to only the first "ある". Therefore, if you perform the Find Next again with the selection only option, the find panel selects the search string "ある" in the current selection, namely the first "ある."

**Comment by tatsy-ymj** [comment]
I understand that it is a specification.
However, what shoud I do, if I want to check the search string and replace it within a specific range?

**Comment by 1024jp** [comment]
I recommend once performing "Seach All" (or Highlight All), checking, and then performing Replace All.

**Comment by tatsy-ymj** [comment]
> I recommend once performing "Seach All" (or Highlight All), checking, and then performing Replace All.

I see, I will try it that way.
However, I still feel a bit uncomfortable with the behavior of the "<" and ">" buttons in a search with a selection......

**Comment by 1024jp** [comment]
> However, I still feel a bit uncomfortable with the behavior of the "<" and ">" buttons in a search with a selection......

I understand personally your discomfort. Nevertheless, this is the only correct behavior for the next match with the "in selection" option when the selection has already moved to the first match from the initial selection. For instance, Textmate behaves with the same manner.

**Comment by 1024jp** [comment]
Another option may be to introduce a kind of in-search mode to focus on the current search state until the user explicitly escapes this mode. Some editors adopt similar approaches. However, this makes the thing complex and takes time to implement. I prefer to avoid it (at least at this time point).
