### ISSUE TITLE
contents of selection returns entire text

### ISSUE THREAD

**Issue by ceciliacase** [coteditor/CotEditor#1395]
Description
I just upgraded to a MacBook Air M1 on Monterey, and now my Applescripts that use contents of selection return the entire text instead of just the selection.
<img width="1328" alt="Screenshot2022-11-05 10:02:10 AM" src="https://user-images.githubusercontent.com/887721/200132221-396263e6-5f33-44b5-9bc0-bce846421ea8.png">

To Reproduce
Use Applescript to get contents of selection
contents of selection will return the entire text instead of just the selection

CotEditor version
Version 4.4.0 (540)

macOS version
12.5.1 (21G83)

Additional context

**Comment by 1024jp** [comment]
Thank you for your report and sorry for the bug.

This issue has already been reported at #1392 and fixed in CotEditor 4.4.1, which will be released soon. Please be patient for a while.

**Comment by ceciliacase** [comment]
Ah, sorry for the duplicate! I did a search but didn't find it. Thank you for your hard work!
