### ISSUE TITLE
File extensions always added on MacOS, can't rename

### ISSUE THREAD

**Issue by 2bits** [coteditor/CotEditor#1396]
### Description

- Cot Editor 4.4.0 (540)
- Mac Studio M1
- macOS 12.6.1 (Monterey)

After searching GHI and reading the Help files, I continue to get unexpected behavior naming a new file and renaming.
1. No matter what the setting for Default Syntax Style, a file extension is automatically added.
2. If I set the default style to `None` it still adds `.txt`
3. I can't rename `file.txt` to `file` where it respects the change.
4. No manner of quoting in the file name affects this.

### To Reproduce

1. On MacOS go into Cot Preferences -> Format -> Default Syntax Style
2. Set it on `None`
3. Restart Cot editor.
4. Open a new file.
5. Give it any name and press `Return`
6. It adds `.txt`
7. Attempt to rename it without the `.txt`
8. It puts `.txt` back
9. Try surrounding the filename in single or double quotation marks.
10. It puts those characters in the name.
11. No other Default Syntax Style get me files with unchanged names.

### Expected behavior

I never expect to see the program change my file names.
Cot is not creating its own unique file type, like Apple does with `.pages` and is not expected to change anything.
I only expect Cot to take hints from a file extension, not enforce it.
If I tell Cot that a file called `Banana.daiquiri` is shell script, so what?

### CotEditor version

4.4.0 (540)

### macOS version

12.6.1 (Monterey)

### Additional context

I never got a chance beyond my app store 5-star rating to say this is the greatest code editor I've used.
 I could go on for a long time praising this, and that's worth repeating. But this file renaming thing drives me nuts. :shrug:

**Comment by 1024jp** [comment]
Sorry for my late reply. I added a measure to CotEditor 4.4.2 which was released last year.
Does it work for you?

**Comment by 1024jp** [comment]
@dimitrik-fr This is the current restriction on macOS.
I asked an engineer at Apple about it last year, but it seemed there is no workaround regrettably.

**Comment by M77J** [comment]
> ### Description
> 
> 
> 
> - Cot Editor 4.4.0 (540)
> 
> - Mac Studio M1
> 
> - macOS 12.6.1 (Monterey)
> 
> 
> 
> After searching GHI and reading the Help files, I continue to get unexpected behavior naming a new file and renaming.
> 
> 1. No matter what the setting for Default Syntax Style, a file extension is automatically added.
> 
> 2. If I set the default style to `None` it still adds `.txt`
> 
> 3. I can't rename `file.txt` to `file` where it respects the change.
> 
> 4. No manner of quoting in the file name affects this.
> 
> 
> 
> ### To Reproduce
> 
> 
> 
> 1. On MacOS go into Cot Preferences -> Format -> Default Syntax Style
> 
> 2. Set it on `None`
> 
> 3. Restart Cot editor.
> 
> 4. Open a new file.
> 
> 5. Give it any name and press `Return`
> 
> 6. It adds `.txt`
> 
> 7. Attempt to rename it without the `.txt`
> 
> 8. It puts `.txt` back
> 
> 9. Try surrounding the filename in single or double quotation marks.
> 
> 10. It puts those characters in the name.
> 
> 11. No other Default Syntax Style get me files with unchanged names.
> 
> 
> 
> ### Expected behavior
> 
> 
> 
> I never expect to see the program change my file names.
> 
> Cot is not creating its own unique file type, like Apple does with `.pages` and is not expected to change anything.
> 
> I only expect Cot to take hints from a file extension, not enforce it.
> 
> If I tell Cot that a file called `Banana.daiquiri` is shell script, so what?
> 
> 
> 
> 
> 
> 
> 
> ### CotEditor version
> 
> 
> 
> 4.4.0 (540)
> 
> 
> 
> ### macOS version
> 
> 
> 
> 12.6.1 (Monterey)
> 
> 
> 
> ### Additional context
> 
> 
> 
> I never got a chance beyond my app store 5-star rating to say this is the greatest code editor I've used.
> 
>  I could go on for a long time praising this, and that's worth repeating. But this file renaming thing drives me nuts. :shrug:
