### ISSUE TITLE
Unstable behavior about scripting clipboard

### ISSUE THREAD

**Issue by tatsy-ymj** [coteditor/CotEditor#1397]
### Description

Behavior of scripts which uses clipboard is very unstable on 4.4.1.

### To Reproduce

1. The following URL is a sample text.

https://www.dropbox.com/s/iesli5ot396dx3w/sample_long.md?dl=0

2. Run the following script via "Script" menu of CotEditor 4.3.6.

```#! /bin/sh

#%%%{CotEditorXInput=AllText}%%%
#%%%{CotEditorXOutput=Pasteboard}%%%

cat - | /usr/local/bin/pandoc -f markdown+hard_line_breaks -t html
```

The result is "result_long_436_1.html".

https://www.dropbox.com/s/9uj80b4rrky7eax/result_long_436_1.html?dl=0

3. Run the same script on CotEditor 4.4.1.

The result is "result_long_441_1.html".

https://www.dropbox.com/s/nj9mtr7t1eamyxl/result_long_441_1.html?dl=0

4. Run the same script on CotEditor 4.4.1 again.

The result is "result_long_441_2.html".

https://www.dropbox.com/s/k2f7n279q47y5k8/result_long_441_2.html?dl=0

5. Take the difference between "result_long_436_1.html" and "result_long_441_1.html".

There is no difference.

6. Take the difference between "result_long_441_1.html" and "result_long_441_2.html".

There are many differences. 

https://www.dropbox.com/s/1an0wvblxid6uek/result_long_441_1.html%20%7C%20result_long_441_2.html%20%E2%80%93%205%20Additions%2C%207%20Deletions%2C%2015%20Changes.patch?dl=0

It seems that a feature about clipboard of 4.4.1 is very unstable.

### CotEditor version

4.4.1

### macOS version

macOS 13 Ventura

**Comment by 1024jp** [comment]
Thank you for the feedback. However, because I don't use `pandoc`, I cannot find where the difference come from.

Is it because:

1. Some lines are not processed by the script?
2. Some of the input text was cut off or lost?
3. Some of the output text was cut off or lost?

Can you create a sample case not using such commands not bundled to macOS?
In addition, does it happen only when the output destination is the pasteboard?

**Comment by tatsy-ymj** [comment]
> 1. Some lines are not processed by the script?
> 2. Some of the input text was cut off or lost?
> 3. Some of the output text was cut off or lost?

The image below compares HTML that was converted successfully (4.3.6) with HTML that was not converted successfully (4.4.1). Some characters are not processed or lost.
The results with 4.3.6 are always the same, while those with 4.4.1 differ every time.

<img width="1508" alt="スクリーンショット 2022-12-01 17 32 24" src="https://user-images.githubusercontent.com/4995795/205005725-b47ebdcf-a59e-4439-88c5-ab896fd59fba.png">

> Can you create a sample case not using such commands not bundled to macOS?

I tried to find another case, but I couldn't.

I tried A [markdown-to-html in pure awk](https://github.com/knazarov/markdown.awk) instead of pandoc, however, there was nothing wrong with the result with 4.4.1.
Oddly enough, so far this has only happened in pandoc. (I will use something other than pandoc for markdown conversion.)

**Comment by tatsy-ymj** [comment]
> In addition, does it happen only when the output destination is the pasteboard?

It happened in the case of "ReplaceAllText", too.

**Comment by 1024jp** [comment]
Hmmm, thank you for the answer. I'll look into the code again.

**Comment by 1024jp** [comment]
I've just updated the point that can affect this issue, but not sure it is fixed.
Let me release CotEditor 4.4.2 this weekend and please try it again under your environment.
If it is not fixed yet, I'll investigate further.

**Comment by 1024jp** [comment]
I've just released CotEditor 4.4.2 addressed this issue.
(It may take a few more hours to be visible in the MAS.)

Could you test whether your issue was fixed in this version?

**Comment by tatsy-ymj** [comment]
4.4.2 works fine. Thank you!

**Comment by 1024jp** [comment]
That's great to hear! Thank you for the test and the quick response.
