### ISSUE TITLE
Column of Line numbers shows only last four digit

### ISSUE THREAD

**Issue by jpachta** [coteditor/CotEditor#1398]
### Description

The line number does not fit to the column. Right now I edit document with 144263 lines and I can see only the last four digit 4263 of the line number.

### To Reproduce

Open new file, 
Press and hold Enter key for a while
Watch the increasing number of lines in the document overcoming  value 9999 and then you will see only four zeros with missing first number.

### Expected behavior

Column with line number will show full value of the line number, ie. the  column with line numbers will dynamically enlarge or so.

### CotEditor version

4.4.1 (542)

### macOS version

macOS Version 12.6.1 (Build 21G217)

**Comment by jpachta** [comment]
I just noticed after some text modifications (find and replace) and window resizing (aka maximallized and restored) that the column with line number is changing its width somehow. Actually my document decreased to 69.875 lines and I can see all five digits in the Line number column.

**Comment by jpachta** [comment]
A screenshot of the column with line numbers where are visible only last four digits. The cursor is on line number 10.000 as you can see on the bottom Status bar:
![image](https://user-images.githubusercontent.com/3779336/203721407-4ace42dd-cd6a-45be-891d-395ccd31bb12.png)

**Comment by 1024jp** [comment]
Thank you for the report. The fix will be shipped with CotEditor 4.4.2!
