### ISSUE TITLE
CotEditor cannot open files from Finder

### ISSUE THREAD

**Issue by GaryElshaw** [coteditor/CotEditor#1400]
### Description

CotEditor has to be open to open files from Finder. If the application is closed, 'open with' does not work unless CotEditor is open already.

### To Reproduce

1. Go to a text file
2. Click on a text file and select 'open with'
3. Select CotEditor
4. CotEditor opens, but does not open the selected file

### Expected behavior

The selected file is opened on CotEditor launch

### CotEditor version

4.4.1

### macOS version

Ventura 13

**Comment by 1024jp** [comment]
Thank you for the report. However, it works as expected under my environment (CotEditor 4.4.1 + macOS 13 Ventura 13.0.1).

Thus, I feel there is nothing to do about this phenomenon in CotEditor but on the Apple-side.
Have you checked if CotEditor is selected as the default editor for your documents? You can check it in the Finder from the Get Info command:
<img width="377" alt="Screenshot 2022-11-27 at 14 02 18" src="https://user-images.githubusercontent.com/1165044/204120020-15a88b1a-8c1f-4720-882e-03b3d15b0a42.png">

**Comment by GaryElshaw** [comment]
Yes, it's a very strange bug that seems to have all but disappeared in Ventura 13.0.1. I will close it. By the way, i mostly absolutely love this application and have done since its inception. Thank you very much for your work. If i can help at all, i'd love to. Any text/communications/web work.

**Comment by 1024jp** [comment]
@GaryElshaw Thank you for the further information. I grad to hear that it was fixed on macOS 14.0.1.
