### ISSUE TITLE
"Multiple Replace" dialog is corrupted

### ISSUE THREAD

**Issue by tatsy-ymj** [coteditor/CotEditor#1402]
### Description

"Multiple Replace" dialog is corrupted when a new set is added.

### To Reproduce

1. Select "Find" -> "Multiple Replace"
2. Add a new set ("test1")
<img width="748" alt="スクリーンショット 2022-11-23 16 36 59" src="https://user-images.githubusercontent.com/4995795/203494558-acda44ce-6d75-4895-9c4c-1bede5413f9b.png">

3. Add another set("test2")
4. When "test1" is selected, the list is corrupted

<img width="748" alt="スクリーンショット 2022-11-23 16 37 16" src="https://user-images.githubusercontent.com/4995795/203494606-e45b7a13-822f-4235-9ae7-0d3d65d86e0f.png">

### CotEditor version

4.4.1 and 4.3.6

### macOS version

macOS 13 Ventura 13.0.1

**Comment by 1024jp** [comment]
Thank you for the report of such a strange issue. I guess this was caused by an Apple-side issue. Anyway, the fix will be shipped with CotEditor 4.4.2!
