### ISSUE TITLE
An execution error with AppleScript in 4.4.2

### ISSUE THREAD

**Issue by tatsy-ymj** [coteditor/CotEditor#1407]
### Description

An AppleScript script that works well in CotEditor 4.3.6 can't run in 4.4.2.

### To Reproduce

1. Open a markdown file.
2. Run the following script. This script reopens an markdown text in [Marked 2](https://marked2app.com/).
```
tell application "CotEditor"
	if exists front document then
		tell front document
			if coloring style is in {"HTML", "HTML5", "CSS", "JavaScript", "PHP", "SVG"} then
				-- reload Safari
				tell application "Safari" to do JavaScript "location.reload(true);" in document 1
			else if coloring style is "Markdown" then
				-- launch Marked
				set thePath to «class ppth»
				tell application "Marked 2" to open thePath
			end if
		end tell
	end if
end tell
```

3. CotEditor 4.4.2 says:
> [2022-12-06 04:26:22] Preview
> 操作を完了できませんでした。/Users/tyamaji/Library/Application Scripts/com.coteditor.CotEditor/Preview.@$r.scpt: execution error: CotEditorでエラーが起きました: «class ppth» of document 1を取り出すことはできません。 (-1728)

<img width="406" alt="スクリーンショット 2022-12-06 13 26 48" src="https://user-images.githubusercontent.com/4995795/205814440-9891543c-f98e-4518-9145-444219703ac9.png">

Has 4.4.2 changed some behavior in AppleScript?

### CotEditor version

4.4.2

### macOS version

macOS 13 Ventura 13.0.1

**Comment by 1024jp** [comment]
I guess the issue is caused by the same as #1389.

**Comment by tatsy-ymj** [comment]
I changed the following line:

(old)
```
set thePath to «class ppth»
```

(new)
```
set thePath to file of it
```

Now it works again. Thank you!
