### ISSUE TITLE
Syntax Highlighting for Bunch files

### ISSUE THREAD

**Issue by Tekl** [coteditor/CotEditor#1408]
It would be great, if CotEditor could support the Syntax of Bunch-files for the free App [Bunch](https://bunchapp.co). Maybe there's a way to convert the existing syntax definitions for Editors like TextMate, Sublime or Atom: https://bunchapp.co/docs/integration/ide-packages/

**Comment by 1024jp** [comment]
We have a policy to bundle only languages that are relatively widely used. Instead, you can make your own CotEditor's syntax highlight definition and share it somewhere.
