### ISSUE TITLE
Auto switch to dark theme when system goes to dark mode

### ISSUE THREAD

**Issue by woshiniming007** [coteditor/CotEditor#1414]
Now only the titile bar or setting window's color can follow the theme of system. Can we make that, for example, switching between Anura and Anura(Dark) when the system theme changes? Thank you.

**Comment by 1024jp** [comment]
When you select the "Automatically" option in the CotEditor's Appearances pane (as shown below in screenshot 1) and use a paired theme (screenshot 2), the theme should automatically change when the system appearance changes.

If it doesn't work somehow, try re-select the theme in the Appearance pane. Nevertheless, if it doesn't work for you, it can be a bug. Then let me know a more detailed situation, such as the specific theme name.


<img width="682" alt="Screenshot 2023-01-11 at 8 40 38" src="https://user-images.githubusercontent.com/1165044/211688368-a2c5f42c-a4b6-4449-833d-38de4ab6c008.png">

<img width="610" alt="Screenshot 2023-01-11 at 9 11 35" src="https://user-images.githubusercontent.com/1165044/211688952-fcdd12da-0b66-425d-a6ea-4e8a64f8e4d9.png">

**Comment by woshiniming007** [comment]
Thank you very much! I used a theme not paired so it doesn't work. No bug!
