### ISSUE TITLE
Search option: Automatically fetch the highlighted word/region to the search box.

### ISSUE THREAD

**Issue by 50705** [coteditor/CotEditor#1415]
If I press Ctrl + F, or If I select a word/region and press Ctrl + F,  the last searched word appears highlighted in the search box.

I want to select a word/region and press Ctrl + F and that word/region should automatically be placed in the search box.

Otherwise, I have to copy the selected word and paste it to the search box (my clipboard is usually busy with something else).

**Comment by 1024jp** [comment]
In the macOS world, the Command-E shortcut is used to use the current selection as the search string.
