### ISSUE TITLE
CotEditor doesn't remember window position correctly or position is drifting 

### ISSUE THREAD

**Issue by LostInCompilation** [coteditor/CotEditor#1416]
### Description

Remembering the window position after quitting or just closing is extremely inconsistent.

**1.)** The window position is seemingly only being saved when saving a file. Moving and then closing Cot without saving changes to a file will also discard the current window position. However this does not happen every time. It appears very random.

But the second issue is more problematic:
**2.)** Even when the window position has been saved, opening Cot after quitting it restores the window slightly above the previous position, resulting in Cot being completely at the top display border after a few quits and reopens. However this is also very inconsistent and random. Sometime it happens with every reopen, sometime only with every second reopen, sometime it works for a few times.

It is a really strange thing. The size of Cot is working fine always.
This is something which drives me really crazy constantly. A fix for that is highly appreciated :)

**Here is a video example for issue (2)**: https://youtu.be/puSPCZ0uyMQ

### Expected behavior
**For issue (1):** Always save and restore the current window position, even when not saving a file or even having a file opened (like it is handled with the window size, which works fine with saving/restoring)

**For issue (2):** Fixing that opening Cot results in a restored position that is drifting to the top with most quits/reopens.

### To Reproduce
1) Open a text file
2) Quit
3) Go to 1)

### CotEditor version
4.4.4 (548)

### macOS version
macOS 13.1 (Apple Silicon)

**Comment by 1024jp** [comment]
Thank you for the report.
I understand it is annoying.
However, I need to say this is caused by a known bug on the Apple side...
I have taken multiple measures for the initial window position and size so far, but could not achieve the perfect solution.
Because it happens randomly (as you reported), I cannot control it.
I'll keep finding the way, but I feel it is better to wait for Apple to fix it. I've already reported the issue to Apple last year.

One piece of advice I can give is: Setting the window width/height blank may be able to detour this issue.

**Comment by LostInCompilation** [comment]
How about just always center the window as a workaround? Since it is popping up at random positions anyway, just pinpoint it to the center.
But NSWindow::center is buggy too, I can provide you with a small function to properly center the window.

**Comment by LostInCompilation** [comment]
When creating the window call a custom center function:
```
self.positionCenter()


// Implementation of positionCenter()
private func positionCenter() {
         self.setFrameOrigin(NSPoint(
             x: (NSScreen.main!.frame.width - CotWindow.size.width)/2,
             y: (NSScreen.main!.frame.height - CotWindow.size.height)/2
         ))
     }
```

**Comment by 1024jp** [comment]
> How about just always centering the window as a workaround? Since it is popping up at random positions anyway, just pinpoint it to the center.

I don't think this is the right way.
Document windows on macOS applications should cascade.

**Comment by LostInCompilation** [comment]
> Document windows on macOS applications should cascade.
Yes totally. But with the current bug, they don't. Opening multiple windows sometimes overlap completely, sometime the new window is shifted a bit to the top.
Centering would be a workaround to at least get _defined_ behaviour for all cases until Apple fixed the issue.

**Comment by 1024jp** [comment]
I completely changed the creation of document windows In the next minor update, which will be released when macOS 14 is released.
I believe this change will solve this issue too (or, at least it becomes easier to dig the cause).
