### ISSUE TITLE
vertical line cannot be removed

### ISSUE THREAD

**Issue by anyuzu99** [coteditor/CotEditor#1418]
### Description

vertical line cannot be removed

![Screenshots 2023-01-14 at 20 29 06](https://user-images.githubusercontent.com/16492117/212472878-92bcc2ee-60f1-4b78-93db-7090750fcbcb.jpg)

### To Reproduce

1. remote inspector
2. See error

### Expected behavior

all toolbar item should be removable

### CotEditor version

4.4.4

### macOS version

13.1

**Comment by 1024jp** [comment]
I understand it is annoying, but there is no way to remove it by the user at the framework level.
