### ISSUE TITLE
Feature Request: add 'Modified Date' as a print format option

### ISSUE THREAD

**Issue by marc-medley** [coteditor/CotEditor#1421]
Please add a `Modified Date` (or `Last Saved Date`) to the print header/footer selections:

<img width="148" alt="ModifiedDate" src="https://user-images.githubusercontent.com/15098151/214966165-8282f484-737f-499e-8675-822aafe115c9.png">

Sometimes it is useful to have the "last modified" date present on a print out.

**Alternatives**

When printing selected text of various modification (file saved) dates, I use a different editor which allows the following print format setting:

![Screenshot 2023-01-26 at 2 36 44 PM](https://user-images.githubusercontent.com/15098151/214966551-54745872-1acf-488f-9bdd-9f09eb1046e9.png)

**Comment by 1024jp** [comment]
Thank you for the request.
The request sounds reasonable.
As you recommended, I also prefer just adding the new last modified date option rather than the new time stamp option field.
I'll implement it in the next version.

**Comment by 1024jp** [comment]
Implemented to CotEditor 4.4.5.
