### ISSUE TITLE
Bug: Print Header|Footer placement options do not match the selected settings

### ISSUE THREAD

**Issue by marc-medley** [coteditor/CotEditor#1423]
### Description

The Right|Center|Left placement in the Header|Footer section do not match the Print… > CotEditor selected settings.

<img width="727" alt="RightOnLeft" src="https://user-images.githubusercontent.com/15098151/214970974-c63de2d4-d43a-4b9b-94fd-b0bdedb3e05b.png">

<img width="764" alt="DateAlignment" src="https://user-images.githubusercontent.com/15098151/214970994-a9b4e3e8-f8a3-462d-8d81-d4e75f2208ac.png">

### To Reproduce

1. `File` > `Print…`
2. expand and set various CotEditor options on the print dialog.

### Expected behavior

Expected behaviors:

* the header|footer element placement match the right…center…left control selection
* _if-and-only-if_ the two elements have the same right…center…left placement are two lines used. Otherwise, any non-conflicting placement would place be on the same line.

### CotEditor version

Version 4.4.4 (548)

### macOS version

Venture 13.1 (22C65)

**Comment by 1024jp** [comment]
This must be a bug.
Thank you for the report!
It'll be fixed in the next update.
