### ISSUE TITLE
Adjustments on the software icon

### ISSUE THREAD

**Issue by holton-jiang** [coteditor/CotEditor#1424]
Can the pen on the CotEditor software icon be shrunk so that the pen on the icon does not extend beyond the border of the rounded square.
<img width="105" alt="截屏2023-01-27 20 09 52" src="https://user-images.githubusercontent.com/88922715/215083785-570a49f6-4cdc-424f-aeec-b8e2e5aa883f.png">

**Comment by 1024jp** [comment]
FYI: it is a recommendation by Apple in the Human Interface Guidelines.
https://developer.apple.com/design/human-interface-guidelines/foundations/app-icons
