### ISSUE TITLE
Missed localization in "find and replace" window.

### ISSUE THREAD

**Issue by ShikiSuen** [coteditor/CotEditor#1425]
### Description

You can see "Find" and "Replace with".

<img width="608" alt="image" src="https://user-images.githubusercontent.com/3164826/215393155-957bfc79-7ebb-485c-bf83-11e4592a498b.png">

### To Reproduce

1. Open any document.
2. Press CMD+F.

### CotEditor version

4.4.4 (548)

### macOS version

13.2

**Comment by 1024jp** [comment]
Thank you!
