### ISSUE TITLE
The alert of inconsistent line endings is annoying

### ISSUE THREAD

**Issue by woshiniming007** [coteditor/CotEditor#1427]
Currently when the app finds inconsistent line endings, it informs user to choose between "convert" and "check". If user don't want to convert, he has to choose "check". But when "check" clicked, the app will show the "InspectorView" panel (I'm not sure what it is called in English). Once the panel is opened, user has to follow "View"->"Inspector"->"Show Inspector" to disable it again, which is annoying.

Can we have a third option "Ignore", not to show the "Inspector", so user doesn't need to close it again and again? Thanks!

Here is a test file, just for convenience.
https://easyupload.io/nln65o

**Comment by 1024jp** [comment]
Thank you for the request. It sounds reasonable.
I've just added the option to the next version.

<img width="587" alt="Screenshot 2023-02-04 at 10 36 12" src="https://user-images.githubusercontent.com/1165044/216739431-a160f6dd-daed-4a78-806c-9623f065f84e.png">
