### ISSUE TITLE
CotEditor cannot use the squirrel input method to input Chinese

### ISSUE THREAD

**Issue by TingTing1990** [coteditor/CotEditor#1429]
### Description

CotEditor cannot use the squirrel input method to input Chinese

https://github.com/rime/squirrel

### To Reproduce

1. Download the latest version of CE from the Mac store
2. Download the input method linked above to use the Chinese input method
3. Switch to the squirrle input method in CE, and the input is directly in English

### CotEditor version

4.4.4

### macOS version

13.2

**Comment by 1024jp** [comment]
Sorry, but I don't know how squirrel works and have no motivation to support it.
CotEditor just accepts the standard text input in macOS (like TextEdit.app), so maybe it's better to ask a maintainer of squirrel.
