### ISSUE TITLE
Markdown and general editing token pairings

### ISSUE THREAD

**Issue by blewvest** [coteditor/CotEditor#1430]
I think that it would be nice for markdown editing to have the tokens important to Markdown syntax to pair automatically. For example, pressing CMD + I should result in ** and CMD + B should result in ****.

Another way of implementing this that I would be when a word is highlighted, and then an asterisk is inputed, it would appear at the beginning and end of the highlighted word. This behavior is already implemented for brakcets. I think it should be expanded to other commonly used tokens.

Thank you very much for considering this!

**Comment by 1024jp** [comment]
Hi.
In general, CotEditor doesn't prefer adding features for specific languages even for Markdown.

However, for good news, CotEditor will renew the snippet feature in the next version, and with this new snippet feature, you can assign your own commands for such text modification. You may like it.

<img width="682" alt="Screenshot 2023-03-11 at 16 32 59" src="https://user-images.githubusercontent.com/1165044/224471568-2a566b9f-4ec4-4372-84ea-990ad6f8a4d5.png">

The new snippet feature will be shipped with CotEditor 4.5.0, which is currently [in beta](https://coteditor.com/beta) and will be released late this month.

**Comment by 1024jp** [comment]
I close this request since now it can be realized with the new snippet feature.
