### ISSUE TITLE
Unable to modify some Menu Item key bindings

### ISSUE THREAD

**Issue by creaky** [coteditor/CotEditor#1431]
### Description

Keybindings for Show Previous Tab and Show Next Tab can not be changed.

### To Reproduce

1. Go to CotEditor Menu Item
2. Go to Settings...
3. Click on Key Bindings
4. Under Menu Items expand Window
5. Unable to find entries for "Show Previous Tab" and Show Next Tab"

### Expected behavior

Expected to find Show Previous Tab and Show Next Tab entries and then can set customized key combination.

### CotEditor version

4.4.5 (550)

### macOS version

13.2 (Build 22D49)

### Additional context

Thanks for creating a very useful editor!

**Comment by 1024jp** [comment]
This is actually by design that the menu items dynamically added by the system cannot be customized.

But because I'm recently improving the key binding customization feature for the next minor update (CotEditor 4.5.0), I'll review again whether there is a possibility to change this specification (please keep in mind this doesn't mean promising the change.

**Comment by creaky** [comment]
Understand and thank you for looking into seeing if it is a possibility.

**Comment by 1024jp** [comment]
I have looked into the code again and concluded there is no smart implementation to customize the Show Previous/Next Tab commands' shortcut keys.
So, sorry, but I will not change the current implementation.

**Comment by creaky** [comment]
For anyone else who wish to customise these special shortcut keys, the following instructions work.

They will replace the show previous tab, show next tab shortcuts just for CotEditor. This changes the shortcuts to left command + left arrow, left command + right arrow for show previous tab, show next tab respectively. Easy to adjust to one's preference.

* Install Karabiner-Elements from https://github.com/pqrs-org/Karabiner-Elements.
* In the **Modifications** section click on **Complex Modifications**.
* Click the button labelled **Add your own rule**.
* Replace the example code with the following:
```json
{
    "description": "CotEditor Tab Shortcuts",
    "manipulators": [
        {
            "conditions": [
                {
                    "bundle_identifiers": [
                        "^com\\.coteditor\\.CotEditor$"
                    ],
                    "type": "frontmost_application_if"
                }
            ],
            "from": {
                "key_code": "left_arrow",
                "modifiers": { "mandatory": ["left_command"] }
            },
            "to": [
                {
                    "key_code": "tab",
                    "modifiers": ["left_control", "left_shift"]
                }
            ],
            "type": "basic"
        },
        {
            "conditions": [
                {
                    "bundle_identifiers": [
                        "^com\\.coteditor\\.CotEditor$"
                    ],
                    "type": "frontmost_application_if"
                }
            ],
            "from": {
                "key_code": "right_arrow",
                "modifiers": { "mandatory": ["left_command"] }
            },
            "to": [
                {
                    "key_code": "tab",
                    "modifiers": ["left_control"]
                }
            ],
            "type": "basic"
        }
    ]
}
```

* Click **Save**.
* Enjoy the shortcuts.

**Comment by creaky** [comment]
For a completely MacOS native solution.

* Open **System Settings** from the Apple menu.
* Go to **Keyboard**
* Click **Keyboard Shortcuts...**
* Go to **App Shortcuts**
* Click the + sign and complete as follows

| Item | Value |
|-|-|
| Application | CotEditor |
| Menu Title | Show Previous Tab |
| Keyboard shortcut | Desired Key Combo |

* Click **Done**
* Click the + sign and complete as follows

| Item | Value |
|-|-|
| Application | CotEditor |
| Menu Title | Show Next Tab |
| Keyboard shortcut | Desired Key Combo |

* Click **Done**
* Click **Done** again
* Go to CotEditor
* Under the Window menu item, confirm the shortcuts for **Show Previous Tab** and **Show Next Tab** have changed to the desired combo.
