### ISSUE TITLE
Add syntax highlighting for nushell

### ISSUE THREAD

**Issue by hustcer** [coteditor/CotEditor#1432]
Thanks for the great work! 

BTW, There is no default support for [nushell](https://github.com/nushell/nushell) files

It would be great to have nushell files highlighted at the same way as everything else, thanks again.

**Comment by 1024jp** [comment]
Currently, CotEditor does't provide any shell dialects even bash or zsh.
I have no plan yet, but if I bundle some shell dialects in the future, I should start with more major ones.
So, I will not bundle nushell to CotEditor at least in the near future.
Let me once close this ticket. Sorry.
