### ISSUE TITLE
Unable to customize toolbar on Apple Silicon Chip

### ISSUE THREAD

**Issue by saibane** [coteditor/CotEditor#1433]
## Environment

- CotEditor: 4.4.5 (550)
- System: macOS Version 13.2 (Build 22D49)
- Language: English (UK)

## Short Description

Unable to customize toolbar on Apple Silicon Chip

## Steps to Reproduce the Issue

Click on View --> Customise Toolbar --> Try to drag & drop item in toolbar

## Expected Result

Item should get added to toolbar

**Comment by 1024jp** [comment]
With the same condition (CotEditor 4.4.5, macOS 13.2, and Apple Silicon), I can add (and remove) toolbar items.
Therefore, Apple Silicon would not be the matter, at least.
Could you upload a screencast indicating how toolbar items cannot be added?

**Comment by saibane** [comment]
It is working today. Closing this ticket now.
