### ISSUE TITLE
Feature Request: Add Option To Rename Tab Name for Unsaved Document

### ISSUE THREAD

**Issue by denevin** [coteditor/CotEditor#1436]
**Is your feature request related to a problem? Please describe.**
Currently each new unsaved tab in the CotEditor is named Untitled xxx.

**Describe the solution you'd like**
Add ability to right click and rename the tab name without saving the document, just like notepad++ currently does. This would make it easier to distinguish between currently opened tabs that have not been saved yet.

Here's a screenshot of this implementation in notepad++
https://code2care.org/q/how-to-rename-a-tab-in-notepad-plus-plus

**Describe alternatives you've considered**
I understand that it's possible to save the document and then rename it, however with my workflow I keep a lot of unsaved documents temporary and then close them after I'm done without saving.

**Comment by 1024jp** [comment]
Sorry, but I don't adopt your suggestion because it doesn't standard macOS applications behavior.
