### ISSUE TITLE
Can't convert Tab to spaces

### ISSUE THREAD

**Issue by shaoyihao** [coteditor/CotEditor#1439]
### Description

I have checked the "convert Tab to spaces" setting, but it just doesn't work.

### To Reproduce

1. Go to 'edit settings'
2. Click on 'Convert Tab to spaces'
3. but it doesn't work

### Expected behavior

Could you please fix this bug? I'll be really appreciated.

### CotEditor version

4.4.5

### macOS version

13.1

**Comment by 1024jp** [comment]
The option does not convert the existing tabs in documents but inserts a sequence of spaces instead of a tab when typing the Tab key.
If you need to convert existing tabs to spaces, just use the find & replace feature.

**Comment by shaoyihao** [comment]
> The option does not convert the existing tabs in documents but inserts a sequence of spaces instead of a tab when typing the Tab key. If you need to convert existing tabs to spaces, just use the find & replace feature.

Thanks for your reply! However it just can't insert spaces when I type the Tab key actually. Is this just a problem that only I meet?

**Comment by 1024jp** [comment]
Thank you for the reply.

> However it just can't insert spaces when I type the Tab key actually. Is this just a problem that only I meet?

That must be unwanted behavior, but I cannot reproduce it in my environment.
Then, could you please tell me the followings:

1. What exactly happens when you press the Tab key? It just inserts a normal tab character, nothing is inserted,  or else?
2. Share the screenshot of your Edit preferences pane of CotEditor.

**Comment by shaoyihao** [comment]
> Thank you for the reply.
> 
> > However it just can't insert spaces when I type the Tab key actually. Is this just a problem that only I meet?
> 
> That must be unwanted behavior, but I cannot reproduce it in my environment. Then, could you please tell me the followings:
> 
> 1. What exactly happens when you press the Tab key? It just inserts a normal tab character, nothing is inserted,  or else?
> 2. Share the screenshot of your Edit preferences pane of CotEditor.

Thanks for your reply! I really appreciate that.

This is sooooo embarrassing! I found that "Convert Tab to spaces" worked just now. But it really wasn't functional a day ago, I swear. Maybe there is something wrong with my environment. I'm really sorry for wasting your precious time.

By the way, thank you for developing such a brilliant App ! It really helps me a lot !

**Comment by 1024jp** [comment]
That's anyway good to hear that your issue is solved!
And, thank you for the further information.
Feel free to send us feedback in the future if you have any issues again.
