### ISSUE TITLE
Auto scroll down when reaching bottom should respect the overscroll settings

### ISSUE THREAD

**Issue by tempapy** [coteditor/CotEditor#1440]
### Description

Hello,

Right now when you set the overscroll setting to something more than 50%, when you reach the bottom of the window while typing, the automatic scroll down (which is a great feature!) does not scroll all the way down but only to the default 50% overscroll. 

### To Reproduce

1. Set overscroll setting above 50% (I use 80%). 
2. Type until the cursor is at the bottom of the window.
3. When the cursor goes out of the window, there is automatic scroll down but only to 50% (half the window), so you have to scroll manually to scroll down completely. 

### Expected behavior

Automatic scroll down should scroll all the way down according to the overscroll and not stop arbitrary at 50%, it is a much more intuitive behavior I think. 

Thank you

### CotEditor version

4.4.5

### macOS version

13.2

**Comment by 1024jp** [comment]
Thank you for the feedback.
However, I suppose the current behavior is consistent and should not change.

In the current behavior, when the cursor goes out of the visible area, the editor scrolls to make the cursor in the middle of the visible area. This behavior is valid also when the cursor does not locate at the end of the document. Furthermore, this is the standard behavior in the macOS system.
Therefore, sorry, but I will reject your request.

**Comment by tempapy** [comment]
I understand the current behavior is the expected behavior most of the time, but not when reaching end of file while using a high overscroll setting, because the only usage of a high overscroll is to be able to scroll down until the end of file appears on the top of the window (and not just the middle), so it is strange that the automatic behavior stops at the middle when reaching end of file. 

But I understand that it may not be how you intended it to be.
