### ISSUE TITLE
Feature Request: Show a "flag" for unsaved files in TabBar (instead of TitleBar)

### ISSUE THREAD

**Issue by dimitrik-fr** [coteditor/CotEditor#1441]
Currently CotEditor is only showing "unsaved" sign for unsaved files in TitleBar, which is very confusing, since you need to switch each time to the given File Tab to check if it was already saved or not yet.

Much more convenient would be to show "unsaved" sign in the TabBar (near the File Name in TabBar), to make it visually easier to see and to switch.

**Comment by 1024jp** [comment]
Firstly, it depends on whether you enable the Auto Save feature or not. which setting are you using?
If you disable the Auto Save, then you can know the saving state by the dot indicator on the right side of each tab (ref. #904).

If not, there is currently no correspondent indicator for tabbed windows with the "Edited" label in the window title bar under the document name.
With Auto Save enabled, the "Edited" label appears when autosaving has been done (so no dot in the close button) but the change has not been explicitly done by the user.
I personally suppose the edited indicator for tabs with Auto Save is not necessary, but I'll hear use cases from users.

**Comment by dimitrik-fr** [comment]
Indeed, Auto Save was enabled, and that's why the "dots" in Tabs for unsaved files were absent, according to the explained design. Probably makes sense then, since I was not aware about this Auto Save feature ;-))

**Comment by 1024jp** [comment]
Ok, then I close this thread.

**Comment by auxbuss** [comment]
HI, I too am missing an indicator for unsaved changes. My relevant settings are Open documents in tabs: Always, and Auto Save: Off.

When there are two or more tabs open, the indicator is present for each tab. But when only one document is open – so, in effect, one tab – there is no indicator. I would like an indicator to be present in the latter case.

macOS: 15.7.7
CotEditor: 7.0.6

**Comment by 1024jp** [comment]
@auxbuss As I mentioned in my previous reply in this thread, you can tell whether a document has unsaved changes by the dot displayed in the window's close button. This is standard behavior shared by macOS applications.

<img width="250" height="140" alt="Image" src="https://github.com/user-attachments/assets/12bc3d19-16f9-48d6-a401-8db1e596bd59" />

**Comment by auxbuss** [comment]
@1024jp I've never seen that before. I checked Pages, Keynote, Numbers, and TextEdit and none of then have that indicator.

Regardless, it should suffice in my case, whatever my preference.

**Comment by 1024jp** [comment]
@auxbuss 

> I checked Pages, Keynote, Numbers, and TextEdit and none of then have that indicator.

They don’t have the indicator since they adopt the auto save feature.
In the current version of macOS, document-based apps that do not use auto-save are actually rare.
