### ISSUE TITLE
Feature Request: Allow to set Custom Colors for Outline

### ISSUE THREAD

**Issue by dimitrik-fr** [coteditor/CotEditor#1442]
Outline is a great feature in CotEditor !! -- however, the default colors it's using are not always "optimal" for eyes (specially when you're using Dark Mode). This could be solved by allowing custom colors settings for Outline:

* it can be global default "foreground" (font) color for Outline
* or additional option within Outline configuration (currently you already have font options -- Bold, Italic, Underline, so you can just add one more for Color to make it just fine ! ;-))
* and additionally option for "Filter" Color -- because this Filter feature is very useful, but by default using yellow marker for selection, which is making selections unreadable in the Dark Mode.. -- another "workaround" could be to use already configured "Selection Color" provided by used Theme

Hope it's not complicate to implement and can be delivered soon. Thanks a lot for your great work !

**Comment by 1024jp** [comment]
To keep the simplicity, I will not add color option for outline. Sorry.

> and additionally option for "Filter" Color -- because this Filter feature is very useful, but by default using yellow marker for selection, which is making selections unreadable in the Dark Mode.

I see this is illegible. So, in the next version, I change the text color to be inverted when they are highlighted, just like text view does for the found highlight.

<img width="320" alt="Screenshot 2023-02-27 at 18 51 31" src="https://user-images.githubusercontent.com/1165044/221530919-1c164797-9171-4760-b221-5bbcba81d6d6.png">

**Comment by dimitrik-fr** [comment]
Good workaround for Filter feature. However the problem with default text color in Outline when Dark Mode is used -- is that it's too bright comparing to the rest of the text, which becomes painful over a long daily usage..

**Comment by 1024jp** [comment]
The text color (and background color) for the outline list in Dark Mode is the standard color for the Dark Mode. Therefore, I will not change it. Sorry.

**Comment by dimitrik-fr** [comment]
What about to add a single letter "label" in Outline to make its context more readable "visually" -- like in the following extension for ex. : https://github.com/7ute/symbols-list

**Comment by 1024jp** [comment]
Maybe, this old ticket #541 relates.
I keep it opens but no plan actually.
