### ISSUE TITLE
Find & Replace: Button Replace does not jump to next occurrence anymore

### ISSUE THREAD

**Issue by matzepf** [coteditor/CotEditor#1445]
### Description

Button Replace does not jump to next occurrence anymore.

### To Reproduce

1. Open Find & Replace
2. Type some search text (that is in the text multiple times)
3. Replace by nothing (empty text)
4. Button 'Replace' does not jump from occurrence to occurrence

### CotEditor version

4.4.5 (550)

### macOS version

13.2.1 (Build 22D68) (German)

**Comment by 1024jp** [comment]
Thank you for the report. I've just confirmed and fixed the issue.
The change will be shipped with next CotEditor 4.5.0, which will be released this month.
