### ISSUE TITLE
未保存のドキュメントを閉じようとすると反応しなくなることがある

### ISSUE THREAD

**Issue by wp-wakahara** [coteditor/CotEditor#1446]
### Description

まだ保存していないドキュメントを左上のバツボタンから閉じようとした際に確認ダイアログが表示されるが、ボタンが一切反応しなくなることがある。

![スクリーンショット 2023-03-03 11 31 47](https://user-images.githubusercontent.com/12187439/222617063-9e54d62e-d7ed-47e7-9342-22c50a617fc7.png)

### To Reproduce

1. 新規ウィンドウを開く
2. テキストを入力する
3. 左上の赤いバツボタンからウィンドウを閉じようとする
4. 確認ダイアログが出る
5. 削除およびキャンセルボタンが反応しない、保存ボタンもグレーアウトされている

### CotEditor version

4.4.5

### macOS version

12.6.2

**Comment by 1024jp** [comment]
duplicated #1377

**Comment by 1024jp** [comment]
本件バグとして認識しておりますが、macOS側のバグでこちらからの修正の手立てがなく、かつmacOS 13で修正されているためCotEditorとしての対応はしないことにしています。詳しくは#1377をご覧ください。
