### ISSUE TITLE
Add syntax highlighting for Nextflow and Groovy

### ISSUE THREAD

**Issue by nuno-agostinho** [coteditor/CotEditor#1448]
[Nextflow](https://www.nextflow.io) is a popular DSL for scientific workflows based on [Groovy](https://groovy-lang.org).
* Nextflow has an official syntax highlighter for Atom: https://github.com/nextflow-io/atom-language-nextflow
* Multiple IDEs support Groovy syntax (here's a [list](https://groovy-lang.org/ides.html) that links to their implementations), including for TextMate: https://github.com/textmate/groovy.tmbundle

If you want, I can create a PR with these additions or export a file from CotEditor with my syntax styles for both languages.

Thanks!

Best,
Nuno

**Comment by 1024jp** [comment]
Thanks for the offer. Sounds good.

> If you want, I can create a PR with these additions or export a file from CotEditor with my syntax styles for both languages.

Yes, please. I'll wait for your PR.

**Comment by richardtop** [comment]
Looking forward to groovy highlighting feature too. Thanks.

**Comment by 1024jp** [comment]
@nuno-agostinho Any update? It took more than one year. If I don't receive any reply in the next week, I'll close this ticket.

**Comment by 1024jp** [comment]
@nuno-agostinho Thank you for the reply. I am in no hurry at all, so please make a PR when you have time.

**Comment by 1024jp** [comment]
Since there is nothing to do on our side, I’ll close this ticket for now to organize issues.
Feel free to create a pull request anytime to add Nextflow and Groovy. I’d appreciate it.
