### ISSUE TITLE
automatic capitalization?

### ISSUE THREAD

**Issue by clayton256** [coteditor/CotEditor#1450]
### Description

What have I done! The first letter in a line of code is getting capitalized! I'm not seeing an option under setting. 
Thanks!

### To Reproduce

1. Start typing on any blank line.
2. Hit the space bar
3. The first later is change from lower case to upper case

### Expected behavior

I'd really like a way to turn this off.

### CotEditor version

4.4.5

### macOS version

ventura

**Comment by 1024jp** [comment]
It is not a feature of CotEditor but the macOS system.

You can turn it off by turning off the "Capitalize words automatically" option in System Settings > Keyboard > Text Input > Input Sources > "Edit" button.

The option label can be different depending on your input source.

<img width="827" alt="Screenshot 2023-03-11 at 11 34 28" src="https://user-images.githubusercontent.com/1165044/224460550-a75bde39-430b-4a76-b8e1-95ffbd798bec.png">

**Comment by clayton256** [comment]
Thank you! thank you!
