### ISSUE TITLE
Sparkle shows that the latest version available is 4.3.6

### ISSUE THREAD

**Issue by DAnn2012** [coteditor/CotEditor#1451]
### Description

Sparkle shows that the latest version available is 4.3.6 because in the file at this URL: https://coteditor.com/appcast.xml the last available stable version reported before CotEditor 4.5.0-beta.2 is this one

### To Reproduce

![Schermata 2023-03-12 alle 12 53 18](https://user-images.githubusercontent.com/1197819/224543086-17fb49a2-c675-413e-9db2-7c8258eafcc0.png)

### Expected behavior

The fix https://github.com/coteditor/coteditor.github.io/commit/f65e733e1c28fbb884b0c86a8f754fa54860ede0 was made to file **appcast-beta.xml** instead of file **appcast.xml**

### CotEditor version

4.4.5 (550)

### macOS version

12.6.3 (21G419)

**Comment by 1024jp** [comment]
Oops, thank you for pointing it out!
I've just updated the appcast.xml in https://github.com/coteditor/coteditor.github.io/commit/e7dd658005fe9bf84a7bde8016511f225c6e002c.
Was it fixed?

**Comment by DAnn2012** [comment]
Hi @1024jp 

It's all right now!

Thanks.

![Schermata 2023-03-12 alle 20 32 28](https://user-images.githubusercontent.com/1197819/224568672-c4b60601-9172-49bc-8e46-35b897cb1055.png)

**Comment by bbsixzz** [comment]
This is happening with 4.5.6 saying it's the latest version when [4.5.7](https://github.com/coteditor/CotEditor/releases/tag/4.5.7) is available.

**Comment by DAnn2012** [comment]
Hi @1024jp 

I already reported it here two days ago: https://github.com/coteditor/coteditor.github.io/issues/29

Thanks.
