### ISSUE TITLE
Merge windows: Shortcut request

### ISSUE THREAD

**Issue by kingmath** [coteditor/CotEditor#1452]
**Is your feature request related to a problem? Please describe.**
I have the problem that several files are opened in separate windows. All windows can be merged via the menu. For this I have to work with the mouse.

**Describe the solution you'd like**
Merging should also be possible via a keyboard shortcut. It is faster (for me).

**Describe alternatives you've considered**
I was looking in the app to see if I could set a keyboard shortcut. Unfortunately, I have not found anything corresponding.

**Additional context**
Thanks for the very good work to the editor. I like to use it very much.

**Comment by 1024jp** [comment]
Unfortunately, shortcuts for some menu commands provided by the system cannot be customized in CotEditor.

However, instead, you can set it in the System Settings.
Go:
  System Settings (or System Preferences in macOS 12) > Keyboards > Keyboard Shortcuts > App Shortcuts 
and assign your favorite shortcut for "Merge All Windows".

<img width="827" alt="Screenshot 2023-03-13 at 13 22 47" src="https://user-images.githubusercontent.com/1165044/224607750-70cffe27-57b5-49a0-8673-82b547edfcc2.png">
