### ISSUE TITLE
Find & Replace UI wrong position

### ISSUE THREAD

**Issue by woshiniming007** [coteditor/CotEditor#1454]
### Description

<img width="497" alt="截屏2023-03-13 14 53 27" src="https://user-images.githubusercontent.com/55045806/224628831-1e2074d9-ec21-483e-84bd-9ad7bab478a8.png">

The button "Replace" and "<" are not in the same line.

### To Reproduce

command+f open "Find & Replace"

### CotEditor version

4.4.5

### macOS version

12.6

**Comment by 1024jp** [comment]
Thank you for the report.
I'll be fixed in the next version.
