### ISSUE TITLE
Add "Save Window" Feature

### ISSUE THREAD

**Issue by dimitrik-fr** [coteditor/CotEditor#1456]
I saw there were several demands to implement "Project" support and "Folder view" panes, etc. -- and this all is not planned, as it's not a simple story to implement and will take a time, etc. etc.

However, opening many files in CotEditor is eating a lot of RAM (I could even suspect an overall memory leak, but need to be really sure about to file a bug ;-))  -- but in any case, working with few Windows with few Tabs each is the most simple. After what it's "naturally" coming a wish to be able to save the given Window with its opened Tabs and close it. And then, few days (or months) later to be able to re-open the same Window again with the same files in its Tabs -- this could be a kind of "Workspace-like" / "Project-like" approach, limited to one Window, but allowing to restore required "environment" for a given task, etc.

A "hack-ish" solution could be simply to add a Menu entry "Save Window", where CotEditor may just generate AppleScript with the list of opened files to allow to re-open all of them in a new CotEditor Window any time later, on demand:

```
tell application "System Events" to tell process "CotEditor"

	click menu item "New Window" of menu "File" of menu bar 1
	
	tell application "CotEditor"
		open "/path/to/file1"
	end tell

	tell application "CotEditor"
		open "/path/to/file2"
	end tell

        ...
end tell
```
e.g. CotEditor can auto-generate such a script with file names and save it under provided "Window Name" in "Save Window" dialog. After what clicking on such a script in Finder will re-open a new CotEditor Window with given lite of files, etc.

But of course more simple would be if CotEditor was just saving such a "Window backup" file itself and assign itself as Application for opening this kind of files:
- currently we already have for ex. files with `.cottheme` extensions for Themes
- why not to introduce, say, `.cotwindow` (or whatever else) file extension for saved Windows ?
- such a file can have a very simple format (just a list of filenames, maybe also with line position in file)
- clicking on such "cotwindow" file would involve CotEditor to start and open the given list of files in a New Window
- additionally, there could be also a Menu item about "Recent Windows" or similar for quick Windows re-opening, etc..
- such a feature could provide a minimalistic Project-like solution and made CotEditor yet more attractive !!

What do you think ?

**Comment by dimitrik-fr** [comment]
I understand all your points, np ;-))

However, I need anyway a feature allowing me to reopen later any given Window with exactly the same files I was editing in the past. So, I see I can "manually" implement this by writing Apple-Script myself and then involve this script from CotEditor Script Menu.

```
tell application "CotEditor"
   open "/path/to/file1"
   open "/path/to/file2"
   open "/path/to/file3"
end tell
```

but maybe I could automate such Scripts creation ? -- is there any way to get a list of the opened files in CorEditor Window via Apple Script ? maybe you can provide some insights ?..

**Comment by 1024jp** [comment]
> is there any way to get a list of the opened files in CorEditor Window via Apple Script ? maybe you can provide some insights ?..

Yes. It is a very fundamental feature in AppleScript rather than CotEditor's own API.
You can access them as `documents` objects in the application.
If you read any introductory guide for AppleScript you'll find it.

**Comment by dimitrik-fr** [comment]
I see that many "native" apps in MacOS are providing some more specific extensions for AppleScript (like access to Tabs in Safari, etc) -- is it anything similar or other provided by CotEditor ? and if yes, do you have any docs / wiki about ?

also, in case you already have an answer -- is there any simple way to open a file in a new Window (rather in a new Tab) in CotEditor via AppleScript ?

**Comment by 1024jp** [comment]
The structure that CotEditor adopts is called document-based.

>  is it anything similar or other provided by CotEditor ?
For instance, TextEdit.app and Pages.app, both by Apple, are also the document-based app.

> and if yes, do you have any docs / wiki about ?
Hmm, I'm not sure about specific documents.
You maybe good to study fundamental things about AppleScript
and know how to read AppleScript libraries in Script Editor.app.

In addition, the following sample scripts for CotEditor may help you.

Sample scripts provided by our project.
https://github.com/coteditor/SampleScripts

Very powerful sample scripts by a user (the landing page is in Japanese, but you may be able to find the download link)
http://www.piyocast.com/?page_id=44

**Comment by dimitrik-fr** [comment]
Thank you for all this stuff !! -- indeed, very interesting reading ! but unfortunately, not helping in my case ;-))

All in all, seems like OSX design implementation is document-centric only, and makes no difference between Tabs and Windows -- each file is just a "document" and that's all..

So, seems the best I can do is the following `SaveCurrentSession.scpt` script :

```
# Save the Filenames List of all opened files in CotEditor 
# into "LastSaved" AppleScript for further re-opening..

set Fname to POSIX path of (path to home folder) & "/Library/Application Scripts/com.coteditor.CotEditor/LastSaved.scpt"

open for access Fname with write permission
set eof of Fname to 0
write ("tell app \"CotEditor\"" & linefeed) to Fname starting at eof

tell application "CotEditor"
	repeat with i in documents
		set FilePath to file of i
		set FilePath to POSIX path of FilePath
		write ("  open POSIX file \"" & FilePath & "\"" & linefeed) to Fname starting at eof
	end repeat
end tell

write ("end tell" & linefeed) to Fname starting at eof
close access Fname
```

- after what I'm placing this script into CotEditor's Scripts folder
- and this script becomes then "visible" via CotEditor menu as "SaveCurrentSession"
- once clicking on it, it'll generate a `LastSaved.scpt` file within CotEditor Scripts folder
- this file will contain AppleScript orders for CotEditor to re-open the given list of files again
- via the same CotEditor Script menu I can open Scripts folder in Finder and rename "LastSaved" to something else
- thus I'm obtaining "named" scripts for different collections of files to work with
- which is allowing me to easily switch from one "project" to another
- particularly when I need to restore the same "environment" (working files) as it was a long time ago ;-))

NOTE : all the files from the saved list will be opened in the current open Window in new Tabs, so if it should be a new Window -- you need to open a new Window first, and then involve a Script.

Maybe having such a Script would be also useful for other people, and then you can just ship it bundled with CotEditor ? -- I saw many requests in the past and even now to have something similar, and I understand it's not in your plans. But having the given "workaround" solution is still better than nothing ;-))

**Comment by 1024jp** [comment]
Sorry, but here is not the place to support general AppleScript knowledge.
I haven't tested your description step-by-step, but CotEditor cannot do things when they are not defined in .sdef file.
In addition, I will anyway not implement extra AppleScript APIs that brake the standard document-based design.

If you feel something is really a _bug_ in CotEditor, then create another issue with organized description.

**Comment by dimitrik-fr** [comment]
It's definitively not a "bug" in CotEditor, so np ;-))  -- I'll share my script in my github repo in case some one else will be interested..

Thank you for all your work and your time !
