### ISSUE TITLE
Add Syntax Highlighting: BBCode

### ISSUE THREAD

**Issue by systemresearch** [coteditor/CotEditor#1457]
[BBCode syntax](https://en.wikipedia.org/wiki/BBCode) is a lightweight markup language which is use in various Internet forums and message boards.

* [BBCode users guide](https://www.bbcode.org/)
* [phpBB BBCode guide](https://www.phpbb.com/community/help/bbcode) (my use case is a phpBB bulletin board)

**Comment by 1024jp** [comment]
Implemented to the next version.
