### ISSUE TITLE
Add Syntax Hightlighting: MediaWiki

### ISSUE THREAD

**Issue by systemresearch** [coteditor/CotEditor#1458]
[MediaWiki syntax](https://www.mediawiki.org/wiki/Help:Formatting) is useful for writing text content for places like [Wikipedia](https://en.wikipedia.org/wiki/MediaWiki).

**Comment by 1024jp** [comment]
Thank you for the request but CotEditor bundles only syntax styles that are popular. I suppose MediaWiki is not in that level, even (of course) I know it.
I recommend to make you own one and distribute somewhere if you want to give it others.
