### ISSUE TITLE
Improve Comment Out / Uncomment

### ISSUE THREAD

**Issue by dimitrik-fr** [coteditor/CotEditor#1459]
Currently CotEditor when commenting out a given line (or selected block) will place the beginning of the comment to the first column of the line. While a more "common" way would be to start the comment from the first position of the **text** in the given line (which also gives a better overall "readability" of the text / code / document)..

Additionally I'd propose to have just a "Toggle Comment" in Menu (instead of keeping both "Comment Out" and "Uncomment") -- this would simplify Menu entries and also simplify Key Binding (a single key to Comment / Uncomment a line or selected block). Except if there are some special use cases in favor for the current implementation -- then it would be great to know about.

**Comment by 1024jp** [comment]
1. Please use one of the issue templates if you create one.
2. Open issue topic-by-topic.

**Comment by 1024jp** [comment]
As I posted above.
This request is already given in #924 (Yeah, it's written in Japanese, but the topic is the same thing).
So, I close this as duplication to manage issue tickets.

> Additionally I'd propose to have just a "Toggle Comment" in Menu (instead of keeping both "Comment Out" and "Uncomment")

The first command in the Text > Comment submenu is already the command toggling comment.
Just the label is changed depending on the state of the selection to represent what it actually do if it performed now.
(This is one of the standard UI design in macOS to change command label depending on the state.)
Instead, the other commands there do always the same action.
Therefore, in the Key Bindings pane to customize shortcut, the toggling command is labeled as "Toggle Comment."

**Comment by dimitrik-fr** [comment]
Interesting..
- when CotEditor just started, I can see "Toggle Comment" in Key Binding 
- but then it's later changed to "Comment Out" (in the same Key Binding Preference Menu)

Also, additionally any key binding assignment for Comment Out / Uncomment via Key Binding Preferences is not working for me, and only working if I'll assign it via MacOS Apps Key bindings in System Preferences..

Then, regarding #924 issue -- I think ths was mainly about "indented comments" (unfortunately I could not properly translate the text to be sure, but I can suppose this from the code examples) -- and indeed, I understand the hidden complexity here, since the design implementation must work for any kind of text, etc. And then I may only agree with you..

However, there is still another option -- what about improving "Block Comment" ?
- currently it's designed to Comment Out a given text selection
- and if no text selected, it'll insert Block Comment string in the current cursor position
- but what if instead it'll self-select the text of the current line and comment it out ?

**Comment by 1024jp** [comment]
> - when CotEditor just started, I can see "Toggle Comment" in Key Binding
> - but then it's later changed to "Comment Out" (in the same Key Binding Preference Menu)

That's in spec. I don't care the consistency of labels there.

> Also, additionally any key binding assignment for Comment Out / Uncomment via Key Binding Preferences is not working for me, and only working if I'll assign it via MacOS Apps Key bindings in System Preferences..

I don't understand what "not working" means.
Anyway, some shortcuts will be overwritten by other action, especially in text input, for instance inputting a character with an accent mark.
It's depends on environments, such as the input method or keyboard.  

> Then, regarding https://github.com/coteditor/CotEditor/issues/924 issue -- I think ths was mainly about "indented comments"

Yes, right.
I understood your statement below so:
> start the comment from the first position of the **text** in the given line

> I understand the hidden complexity here, since the design implementation must work for any kind of text, etc.

That's actually true. Commenting calculation is one of the most complex thing in text editor. That's also why #924, an old request, is still open although in my to-do list.
Maybe, one day, I'll improve it.

> However, there is still another option -- what about improving "Block Comment" ?

I suppose it doesn't work well.
This is not about correct vs. wrong but about preference.
CotEditor already provides the "Always from line head" option in Comment settings and it would be enough.

**Comment by dimitrik-fr** [comment]
Let me show then how Comment Key Binding is not working : 
- CotEditor v.4.5.1
- start CotEditor
- open Key Binding Preferences and assign F1 to Text => Comment => Toggle Comment
- close Preferences
- pressing F1 in the current line in opened file => line is commented out (as expected)
- pressing F1 again => nothing happens
- moving to another line without comments, press F1 => nothing happens

is it only for me ?..

**Comment by 1024jp** [comment]
Hi. As mentioned in #1473, I released CotEditor 4.5.3 which addressed the issue today.
I hope it also fixes your issue.

Let me know if it still doesn't work well.

**Comment by dimitrik-fr** [comment]
Thanks a lot !!! -- currently it "just works" fine and I afraid even touch anything as long it's working ;-)) -- if later I'll discover some problems, I'll open another issue, no problem. But for now it's all good ! ;-))

Thanks again !!
