### ISSUE TITLE
Inconsistent Select Word (Cmd+D)

### ISSUE THREAD

**Issue by dimitrik-fr** [coteditor/CotEditor#1460]
Currently if we select a word in CotEditor with Cmd+D and continue to press Cmd+D again to select next same word -- if you then press Esc, you'll cancel words selection, and your cursor will be back to the first selected word (as expected).

However:

- if during further word selection your screen was scrolled down, on Esc your cursor will be back to the first word, but not your screen ! -- unless you'll not mind to press Left/Right keys to move your cursor and bring editor screen back to the cursor position.. -- having screen moved back to cursor position on Esc would be more natural implementation, should be an easy fix.

- then, if you continue to press Cmd+D to select next words and your screen will be scrolled up to select same words on higher lines from your initial position, then on Esc your cursor will be no more moved back to the first selected word, but rather stay on the most top-level word appearance in the text ! -- and this more sounds like a bug. Hope it should be easy to fix as well, as it's very confusing behavior.

**Comment by 1024jp** [comment]
Please use one of the issue templates if you create one.

**Comment by 1024jp** [comment]
The suggestion seems reasonable.
Since I already closed the updates for CotEditor 4.5.0, I'll change in 4.5.1.

**Comment by 1024jp** [comment]
> - then, if you continue to press Cmd+D to select next words and your screen will be scrolled up to select same words on higher lines from your initial position, then on Esc your cursor will be no more moved back to the first selected word, but rather stay on the most top-level word appearance in the text ! -- and this more sounds like a bug. Hope it should be easy to fix as well, as it's very confusing behavior.

Well, despite your feeling, the second one is by design than a bug.
Due to the implementation, the editor doesn't remember the original selection.
In addition, I will not change the current design.
That is, I don’t want to make the current editor implementation more complicated because CotEditor needs to migrate to the new text framework in the next few years.

**Comment by dimitrik-fr** [comment]
But it's not about "selection", but just initial cursor position.. -- no way to save it when Cmd+D is pressed and then restore it on Esc ?

**Comment by 1024jp** [comment]
Haha, a selection and a cursor position are the same in the code. A zero-width selection is a cursor position.

> no way to save it when Cmd+D is pressed and then restore it on Esc ?
It's not such an easy thing. I need to consider many other cases. In addition, I don't wanna add a property for a trivial case.
Not all requests are adopted, even the user or I think it is right.
