### ISSUE TITLE
CotEditor unexpectedly using 100% CPU

### ISSUE THREAD

**Issue by dimitrik-fr** [coteditor/CotEditor#1461]
### Description

CotEditor for some strange reasons started to use 100% CPU. Additionally 100% CPU usage reported for com.apple.appkit.xpc.openAndSavePanelService (CotEditor) -- which is probably the main reason for observed issue. After restarting CotEditor the issue is gone.

### To Reproduce

No idea how to reproduce it, all I could do is to trace both processes while they are using 100% CPU and share these traces here, in hope these traces could clarify something..

[Sample of com.apple.appkit.xpc.openAndSavePanelService (CotEditor).txt](https://github.com/coteditor/CotEditor/files/11010738/Sample.of.com.apple.appkit.xpc.openAndSavePanelService.CotEditor.txt)
[Sample of CotEditor.txt](https://github.com/coteditor/CotEditor/files/11010739/Sample.of.CotEditor.txt)

### CotEditor version

4.5.1

### macOS version

Monterey 12.6.3

**Comment by dimitrik-fr** [comment]
Ok, I finally found how to reproduce the problem :
- press Cmd+O to open a file
- now, instead of clicking on a file, go to the "Search" field and type few letters
- search results will appear in the file list, but on the same time 100% CPU usage for CotEditor
- after selecting a file or pressing Cancel, 100% CPU usage remains for CotEditor

It looks like the initial reason "why" this problem appears is related to MacOS itself
- I tested with TextEditor and other apps, they will also hit 100% CPU if Search is used
- so, seems like MacOS is doing something odd here
- however, the main difference is that all other apps are stopping such CPU usage once the file is opened or Cancel was pressed
- while CotEditor continues to loop with 100% CPU

And that's why it points on the bug in CotEditor itself.

**Comment by 1024jp** [comment]
Thank you for the report with a clear description!

I found this issue occurs only on macOS 12 and have just fixed it.
As you mentioned, the CPU usage during opening the open window is still 100% but when closing it, the usage reverts to a stable number.
In addition, this issue doesn't appear on macOS 13.
The change will be shipped with the next version, CotEditor 4.5.2.
