### ISSUE TITLE
Show soft hyphen

### ISSUE THREAD

**Issue by MaHi84** [coteditor/CotEditor#1462]
Conditional hyphens (soft hyphen: U+00AD) are not visible in the editor.

Example: »TE­ST«

![Screenshot](https://user-images.githubusercontent.com/11874528/226210480-c13eda1b-acee-4bea-9145-c48af69b7236.png)

I would like to see an option to show them.

**Comment by 1024jp** [comment]
Thank you for the feedback.
I investigated the way but it seems technically hard to implement it with the TextKit framework that CotEditor uses.
