### ISSUE TITLE
Crashes when pressing ¨ and <Return> buttons at the same time.

### ISSUE THREAD

**Issue by j1441** [coteditor/CotEditor#1470]
### Description

The app consistently crashes when pressing ¨ key.

### To Reproduce

1. Open Coteditor
2. Press ¨
3. App crashes

### Expected behavior

¨ symbol should appear in text.

### CotEditor version

4.5.2 (562)

### macOS version

13.3

**Comment by 1024jp** [comment]
Could you tell me the keyboard (layout) you use and how to input the character `¨` with it.

**Comment by 1024jp** [comment]
At leaset, there is no issue in my current environment to input `¨` with Option-U.

Environment:
Keyboard: build-in keyboard with MacBook Pro M1 2020 13-inch
Input Source: ABC
macOS: 13.3
CotEditor: 4.5.2

**Comment by j1441** [comment]
Ahh yes forgot to add that, keyboard layout is Norwegian. So it is the key immediately to the left of the return key.
1. Keyboard: norwegian built-in keyboard. Character is input by pressing the ¨ key (no modifiers) left of the return key.
2. TextEdit works correctly when inputting the character.
3. Crash report:
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               CotEditor [67733]
Path:                  /Applications/CotEditor.app/Contents/MacOS/CotEditor
Identifier:            com.coteditor.CotEditor
Version:               4.5.2 (562)
App Item ID:           1024640650
App External ID:       856026758
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-04-05 09:37:58.3605 +0200
OS Version:            macOS 13.3 (22E252)
Report Version:        12
Anonymous UUID:        B6D706A2-AFE0-89C9-7F34-69A58D694AD6

Sleep/Wake UUID:       114F7559-FCD2-4F60-802F-8878F290238F

Time Awake Since Boot: 81000 seconds
Time Since Wake:       1755 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x000000010492148c

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [67733]

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   CotEditor                     	       0x10492148c 0x104760000 + 1840268
1   CotEditor                     	       0x10491d3e8 0x104760000 + 1823720
2   CotEditor                     	       0x1047f4304 0x104760000 + 606980
3   CotEditor                     	       0x1047f4420 0x104760000 + 607264
4   AppKit                        	       0x19e935150 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 480
5   AppKit                        	       0x19e934d9c -[NSWindow(NSEventRouting) sendEvent:] + 284
6   AppKit                        	       0x19e9340e0 -[NSApplication(NSEvent) sendEvent:] + 1556
7   AppKit                        	       0x19eb840f0 -[NSApplication _handleEvent:] + 60
8   AppKit                        	       0x19e7fb57c -[NSApplication run] + 500
9   AppKit                        	       0x19e7d29a8 NSApplicationMain + 880
10  CotEditor                     	       0x104762a18 0x104760000 + 10776
11  dyld                          	       0x19b1b3f28 start + 2236

Thread 1:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x19b4cbf14 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x19b4de240 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x19b4d4b78 mach_msg_overwrite + 604
3   libsystem_kernel.dylib        	       0x19b4cc290 mach_msg + 24
4   CoreFoundation                	       0x19b5ea8b8 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x19b5e9198 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x19b5e858c CFRunLoopRunSpecific + 612
7   AppKit                        	       0x19e932508 _NSEventThread + 172
8   libsystem_pthread.dylib       	       0x19b50bfa8 _pthread_start + 148
9   libsystem_pthread.dylib       	       0x19b506da0 thread_start + 8

Thread 2:
0   libsystem_pthread.dylib       	       0x19b506d8c start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x19b506d8c start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x19b506d8c start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	       0x19b506d8c start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	       0x19b506d8c start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	       0x19b506d8c start_wqthread + 0


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0xe000000000000000   x2: 0x0000000000000001   x3: 0x0000000000000000
    x4: 0x5000000138645ba0   x5: 0x000000012ee3a8b0   x6: 0x0000000000000002   x7: 0x0000000000000000
    x8: 0x0000000000000000   x9: 0x0000000000000000  x10: 0x0000000124a8f6f0  x11: 0x000000000000007f
   x12: 0x0000000000000028  x13: 0x0000000139114e70  x14: 0x00000001f69805d8  x15: 0x00000001f69805d8
   x16: 0x000000019b57a55c  x17: 0x000000019b57a550  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x0000000000000000  x21: 0x0000000000000000  x22: 0x0000000000000000  x23: 0x0000000000000064
   x24: 0x40000001f8840110  x25: 0xe100000000000000  x26: 0x0000000138144e80  x27: 0xc000000000000000
   x28: 0xe100000000000000   fp: 0x000000016b69f200   lr: 0x9264800104921280
    sp: 0x000000016b69f030   pc: 0x000000010492148c cpsr: 0x00001000
   far: 0x000000010ba00000  esr: 0xf2000001 (Breakpoint) brk 1

Binary Images:
       0x104760000 -        0x104a93fff com.coteditor.CotEditor (4.5.2) <9287d147-4870-3622-90c5-5eda3690faa4> /Applications/CotEditor.app/Contents/MacOS/CotEditor
       0x114aa4000 -        0x114ac3fff com.apple.security.csparser (3.0) <862735d9-d84d-31b0-bfa8-d75e2271af1a> /System/Library/Frameworks/Security.framework/Versions/A/PlugIns/csparser.bundle/Contents/MacOS/csparser
       0x116158000 -        0x116163fff libobjc-trampolines.dylib (*) <80f14f3d-d099-3693-a8e0-eb9a526b1790> /usr/lib/libobjc-trampolines.dylib
       0x116378000 -        0x11637ffff com.apple.CloudDocsFileProvider (1.0) <26e33c5a-f76f-3570-8782-d0dc2d61ff00> /System/Library/Frameworks/FileProvider.framework/OverrideBundles/CloudDocsFileProvider.bundle/Contents/MacOS/CloudDocsFileProvider
       0x116390000 -        0x116397fff com.apple.FileProviderOverride (855.100.378) <782f062d-b9d5-3e62-9ce7-b68d197712a2> /System/Library/Frameworks/FileProvider.framework/OverrideBundles/FileProviderOverride.bundle/Contents/MacOS/FileProviderOverride
       0x116430000 -        0x11644ffff com.apple.findersync.fileprovideroverride.FinderSyncCollaborationFileProviderOverride (13.3) <99856966-e77f-3294-a16a-e59a7e494572> /System/Library/Frameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride
       0x19e7cf000 -        0x19f6ddfff com.apple.AppKit (6.9) <0218f27e-98c0-3af4-809a-138a01479f4c> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x19b1ae000 -        0x19b23c53b dyld (*) <6f2c2bb8-4bbc-3b64-b927-d3f3193b6295> /usr/lib/dyld
       0x19b4cb000 -        0x19b504fe7 libsystem_kernel.dylib (*) <7acbd9bc-d056-310e-858d-81b116cf6d28> /usr/lib/system/libsystem_kernel.dylib
       0x19b56b000 -        0x19ba44fff com.apple.CoreFoundation (6.9) <b4fdaece-9727-3969-b014-27f7f24c8e01> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x19b505000 -        0x19b511fff libsystem_pthread.dylib (*) <b401cfb3-8dfe-32db-92b3-ba8af0f8ca6e> /usr/lib/system/libsystem_pthread.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.5G resident=0K(0%) swapped_out_or_unallocated=1.5G(100%)
Writable regions: Total=440.6M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=440.6M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               256K        2 
Activity Tracing                   256K        1 
CG backing stores                 4032K        4 
CG image                          2112K       41 
ColorSync                          608K       27 
CoreAnimation                     98.3M       92 
CoreGraphics                        32K        2 
CoreImage                           48K        3 
CoreUI image data                 2752K       22 
Dispatch continuations            80.0M        1 
Foundation                          48K        2 
Kernel Alloc Once                   32K        1 
MALLOC                           131.4M       68 
MALLOC guard page                  192K       10 
MALLOC_MEDIUM (reserved)         112.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.1M        8 
Stack                             11.7M        8 
VM_ALLOCATE                       1200K       12 
__AUTH                            2566K      428 
__AUTH_CONST                      32.0M      664 
__CTF                               824        1 
__DATA                            14.9M      654 
__DATA_CONST                      32.3M      671 
__DATA_DIRTY                      2134K      248 
__FONT_DATA                        2352        1 
__INFO_FILTER                         8        1 
__LINKEDIT                       801.1M        7 
__OBJC_RO                         66.2M        1 
__OBJC_RW                         2011K        1 
__TEXT                           702.4M      693 
dyld private memory                272K        2 
mapped file                      251.8M       74 
shared memory                      928K       17 
===========                     =======  ======= 
TOTAL                              2.4G     3768 
TOTAL, minus reserved VM space     2.2G     3768 



-----------
Full Report
-----------

{"app_name":"CotEditor","timestamp":"2023-04-05 09:37:59.00 +0200","app_version":"4.5.2","slice_uuid":"9287d147-4870-3622-90c5-5eda3690faa4","adam_id":"1024640650","build_version":"562","platform":1,"bundleID":"com.coteditor.CotEditor","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.3 (22E252)","roots_installed":0,"name":"CotEditor","incident_id":"7AC42265-DF47-42F2-8667-F579FC68A2BA"}
{
  "uptime" : 81000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,1",
  "coalitionID" : 6778,
  "osVersion" : {
    "train" : "macOS 13.3",
    "build" : "22E252",
    "releaseType" : "User"
  },
  "captureTime" : "2023-04-05 09:37:58.3605 +0200",
  "incident" : "7AC42265-DF47-42F2-8667-F579FC68A2BA",
  "pid" : 67733,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-04-05 09:22:19.6789 +0200",
  "procStartAbsTime" : 1931192386515,
  "procExitAbsTime" : 1953720531626,
  "procName" : "CotEditor",
  "procPath" : "\/Applications\/CotEditor.app\/Contents\/MacOS\/CotEditor",
  "bundleInfo" : {"CFBundleShortVersionString":"4.5.2","CFBundleVersion":"562","CFBundleIdentifier":"com.coteditor.CotEditor"},
  "storeInfo" : {"storeCohortMetadata":"10|date=1654095600000&sf=143457&pgtp=Search&pgid=osx&prpg=Genre_29762&ctxt=Search&issrch=1&imptyp=card&kind=macSoftware&lngid=2","itemID":"1024640650","deviceIdentifierForVendor":"B4590524-CBC6-5D42-B919-9508CEFD194D","thirdParty":true,"softwareVersionExternalIdentifier":"856026758"},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.coteditor.CotEditor",
  "crashReporterKey" : "B6D706A2-AFE0-89C9-7F34-69A58D694AD6",
  "throttleTimeout" : 2147483647,
  "codeSigningID" : "com.coteditor.CotEditor",
  "codeSigningTeamID" : "HT3Z3A72WZ",
  "codeSigningFlags" : 570520337,
  "codeSigningValidationCategory" : 4,
  "codeSigningTrustLevel" : 0,
  "wakeTime" : 1755,
  "sleepWakeUUID" : "114F7559-FCD2-4F60-802F-8878F290238F",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000001, 0x000000010492148c","rawCodes":[1,4371649676],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":67733},
  "os_fault" : {"process":"CotEditor"},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":1629478,"threadState":{"x":[{"value":0},{"value":16140901064495857664},{"value":1},{"value":0},{"value":5764607528275303328},{"value":5081639088},{"value":2},{"value":0},{"value":0},{"value":0},{"value":4910020336},{"value":127},{"value":40},{"value":5252402800},{"value":8432125400,"symbolLocation":0,"symbol":"__CFConstantStringClassReference"},{"value":8432125400,"symbolLocation":0,"symbol":"__CFConstantStringClassReference"},{"value":6901179740,"symbolLocation":204,"symbol":"_CFStringGetCStringPtrInternal"},{"value":6901179728,"symbolLocation":192,"symbol":"_CFStringGetCStringPtrInternal"},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":100},{"value":4611686026891755792},{"value":16212958658533785600},{"value":5235822208},{"value":13835058055282163712},{"value":16212958658533785600}],"flavor":"ARM_THREAD_STATE64","lr":{"value":10548696969068548736},"cpsr":{"value":4096},"fp":{"value":6097072640},"sp":{"value":6097072176},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":4371649676,"matchesCrashFrame":1},"far":{"value":4490002432}},"queue":"com.apple.main-thread","frames":[{"imageOffset":1840268,"imageIndex":0},{"imageOffset":1823720,"imageIndex":0},{"imageOffset":606980,"imageIndex":0},{"imageOffset":607264,"imageIndex":0},{"imageOffset":1466704,"symbol":"-[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:]","symbolLocation":480,"imageIndex":6},{"imageOffset":1465756,"symbol":"-[NSWindow(NSEventRouting) sendEvent:]","symbolLocation":284,"imageIndex":6},{"imageOffset":1462496,"symbol":"-[NSApplication(NSEvent) sendEvent:]","symbolLocation":1556,"imageIndex":6},{"imageOffset":3887344,"symbol":"-[NSApplication _handleEvent:]","symbolLocation":60,"imageIndex":6},{"imageOffset":181628,"symbol":"-[NSApplication run]","symbolLocation":500,"imageIndex":6},{"imageOffset":14760,"symbol":"NSApplicationMain","symbolLocation":880,"imageIndex":6},{"imageOffset":10776,"imageIndex":0},{"imageOffset":24360,"symbol":"start","symbolLocation":2236,"imageIndex":7}]},{"id":1629569,"name":"com.apple.NSEventThread","frames":[{"imageOffset":3860,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":8},{"imageOffset":78400,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":8},{"imageOffset":39800,"symbol":"mach_msg_overwrite","symbolLocation":604,"imageIndex":8},{"imageOffset":4752,"symbol":"mach_msg","symbolLocation":24,"imageIndex":8},{"imageOffset":522424,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":9},{"imageOffset":516504,"symbol":"__CFRunLoopRun","symbolLocation":1208,"imageIndex":9},{"imageOffset":513420,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":9},{"imageOffset":1455368,"symbol":"_NSEventThread","symbolLocation":172,"imageIndex":6},{"imageOffset":28584,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":10},{"imageOffset":7584,"symbol":"thread_start","symbolLocation":8,"imageIndex":10}]},{"id":1648532,"frames":[{"imageOffset":7564,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":10}]},{"id":1648750,"frames":[{"imageOffset":7564,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":10}]},{"id":1648838,"frames":[{"imageOffset":7564,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":10}]},{"id":1648839,"frames":[{"imageOffset":7564,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":10}]},{"id":1648841,"frames":[{"imageOffset":7564,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":10}]},{"id":1649069,"frames":[{"imageOffset":7564,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":10}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4369809408,
    "CFBundleShortVersionString" : "4.5.2",
    "CFBundleIdentifier" : "com.coteditor.CotEditor",
    "size" : 3358720,
    "uuid" : "9287d147-4870-3622-90c5-5eda3690faa4",
    "path" : "\/Applications\/CotEditor.app\/Contents\/MacOS\/CotEditor",
    "name" : "CotEditor",
    "CFBundleVersion" : "562"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4641669120,
    "CFBundleShortVersionString" : "3.0",
    "CFBundleIdentifier" : "com.apple.security.csparser",
    "size" : 131072,
    "uuid" : "862735d9-d84d-31b0-bfa8-d75e2271af1a",
    "path" : "\/System\/Library\/Frameworks\/Security.framework\/Versions\/A\/PlugIns\/csparser.bundle\/Contents\/MacOS\/csparser",
    "name" : "csparser",
    "CFBundleVersion" : "60420.101.4"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4665475072,
    "size" : 49152,
    "uuid" : "80f14f3d-d099-3693-a8e0-eb9a526b1790",
    "path" : "\/usr\/lib\/libobjc-trampolines.dylib",
    "name" : "libobjc-trampolines.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4667703296,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.CloudDocsFileProvider",
    "size" : 32768,
    "uuid" : "26e33c5a-f76f-3570-8782-d0dc2d61ff00",
    "path" : "\/System\/Library\/Frameworks\/FileProvider.framework\/OverrideBundles\/CloudDocsFileProvider.bundle\/Contents\/MacOS\/CloudDocsFileProvider",
    "name" : "CloudDocsFileProvider",
    "CFBundleVersion" : "1553.100.384"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4667801600,
    "CFBundleShortVersionString" : "855.100.378",
    "CFBundleIdentifier" : "com.apple.FileProviderOverride",
    "size" : 32768,
    "uuid" : "782f062d-b9d5-3e62-9ce7-b68d197712a2",
    "path" : "\/System\/Library\/Frameworks\/FileProvider.framework\/OverrideBundles\/FileProviderOverride.bundle\/Contents\/MacOS\/FileProviderOverride",
    "name" : "FileProviderOverride",
    "CFBundleVersion" : "855.100.378"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4668456960,
    "CFBundleShortVersionString" : "13.3",
    "CFBundleIdentifier" : "com.apple.findersync.fileprovideroverride.FinderSyncCollaborationFileProviderOverride",
    "size" : 131072,
    "uuid" : "99856966-e77f-3294-a16a-e59a7e494572",
    "path" : "\/System\/Library\/Frameworks\/FileProvider.framework\/OverrideBundles\/FinderSyncCollaborationFileProviderOverride.bundle\/Contents\/MacOS\/FinderSyncCollaborationFileProviderOverride",
    "name" : "FinderSyncCollaborationFileProviderOverride",
    "CFBundleVersion" : "1563.5.2"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6953955328,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15790080,
    "uuid" : "0218f27e-98c0-3af4-809a-138a01479f4c",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2299.50.120"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6897197056,
    "size" : 582972,
    "uuid" : "6f2c2bb8-4bbc-3b64-b927-d3f3193b6295",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6900461568,
    "size" : 237544,
    "uuid" : "7acbd9bc-d056-310e-858d-81b116cf6d28",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6901116928,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5087232,
    "uuid" : "b4fdaece-9727-3969-b014-27f7f24c8e01",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1971"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6900699136,
    "size" : 53248,
    "uuid" : "b401cfb3-8dfe-32db-92b3-ba8af0f8ca6e",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  }
],
  "sharedCache" : {
  "base" : 6896533504,
  "size" : 3539501056,
  "uuid" : "581a6955-d455-3735-973b-5233bd5dd16e"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.5G resident=0K(0%) swapped_out_or_unallocated=1.5G(100%)\nWritable regions: Total=440.6M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=440.6M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               256K        2 \nActivity Tracing                   256K        1 \nCG backing stores                 4032K        4 \nCG image                          2112K       41 \nColorSync                          608K       27 \nCoreAnimation                     98.3M       92 \nCoreGraphics                        32K        2 \nCoreImage                           48K        3 \nCoreUI image data                 2752K       22 \nDispatch continuations            80.0M        1 \nFoundation                          48K        2 \nKernel Alloc Once                   32K        1 \nMALLOC                           131.4M       68 \nMALLOC guard page                  192K       10 \nMALLOC_MEDIUM (reserved)         112.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.1M        8 \nStack                             11.7M        8 \nVM_ALLOCATE                       1200K       12 \n__AUTH                            2566K      428 \n__AUTH_CONST                      32.0M      664 \n__CTF                               824        1 \n__DATA                            14.9M      654 \n__DATA_CONST                      32.3M      671 \n__DATA_DIRTY                      2134K      248 \n__FONT_DATA                        2352        1 \n__INFO_FILTER                         8        1 \n__LINKEDIT                       801.1M        7 \n__OBJC_RO                         66.2M        1 \n__OBJC_RW                         2011K        1 \n__TEXT                           702.4M      693 \ndyld private memory                272K        2 \nmapped file                      251.8M       74 \nshared memory                      928K       17 \n===========                     =======  ======= \nTOTAL                              2.4G     3768 \nTOTAL, minus reserved VM space     2.2G     3768 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "d6b396b4ff3ed5254c3453ae39545cbd29655e10",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "639124e81d92412bfb4880b3",
      "factorPackIds" : {

      },
      "deploymentId" : 240000004
    },
    {
      "rolloutId" : "63582c5f8a53461413999550",
      "factorPackIds" : {

      },
      "deploymentId" : 240000002
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "c28e4ee6-1b08-4f90-8e05-2809e78310a3",
      "experimentId" : "6317d2003d24842ff850182a",
      "deploymentId" : 400000013
    }
  ]
}
}

Model: MacBookPro18,1, BootROM 8422.100.650, proc 10:8:2 processors, 32 GB, SMC 
Graphics: Apple M1 Pro, Apple M1 Pro, Built-In
Display: Color LCD, 3456 x 2234 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Mar  8 2023 18:27:05 version 20.96.27.0.8.7.144 FWID 01-ec2ac09e
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

**Comment by 1024jp** [comment]
Thank you for the additional information!

I could not reproduce the crash in my environment (I guess I need a real Norwegian keyboard); however, thanks to your crash log, I could point out the cause.
It helped a lot.
I suppose I theoretically succeeded in fixing it in the next version.

**Comment by 1024jp** [comment]
Today, I released CotEditor 4.5.3 which addressed this issue.
Let me know if the issue still exists.
