### ISSUE TITLE
Swift syntax highlighting issue with "/" character

### ISSUE THREAD

**Issue by Pash237** [coteditor/CotEditor#1471]
### Description

Is it just me or CotEditor is confused with slash character `/` in Swift highlighting?
Seems like it's treated like start/end of block comment `/*`, even in line comments — see attached screenshot.

### To Reproduce
Create a following file with .swift extension and open in CotEditor:

MyClass.swift
```swift
class MyClass {
	var computedProperty: Double {
		return x / y
	}
	
	func func() -> Double {
		return a / b
	}
	
	var anotherProperty: Double {
		return 4 / 2
	}
	
	// Some comment here
	var string: String
}
```
Is highlighting this way:  
<img width="499" alt="image" src="https://user-images.githubusercontent.com/277626/230477791-825eef1b-7eb7-42c6-9ab5-62caa319f749.png">

### CotEditor version

4.5.2 (562)

### macOS version

13.2.1

**Comment by 1024jp** [comment]
Thank you for the report!
