### ISSUE TITLE
Toggle comment key binding not working

### ISSUE THREAD

**Issue by ObliviousMonkey** [coteditor/CotEditor#1473]
### Description

Using the default assigned key binding for toggling comments (<kbd>cmd</kbd> + <kbd>:</kbd>) does nothing, and the default mac alert/error sound can be heard.

Clicking manually through the menu <kbd>Text</kbd> > <kbd>Comment ></kbd> > <kbd>Comment Out/Uncomment</kbd> works fine.

### To Reproduce

Trying to reassign the default key binding by going to settings (<kbd>cmd</kbd> + <kbd>,</kbd>) > <kbd>Key Bindings</kbd> > <kbd>Text</kbd> > <kbd>> Comment</kbd> > <kbd>Comment Out/Uncomment</kbd>:
- in case it's a keyboard issue, "reassigning" to <kbd>cmd</kbd> + <kbd>:</kbd> produces the correct output, meaning the keys pressed are correctly recognized, but nothing changes in the behaviour.
- trying to remap to <kbd>cmd</kbd> + <kbd>shift</kbd> + <kbd>:</kbd> (**no warning** of already used keybinding): maps to <kbd>cmd</kbd> + <kbd>/</kbd> on my keyboard. Exiting settings and trying it in the editor opens the Help dropdown menu, with focus in the Help searchbar (even though no such key binding is listed for Help ?)
    - interestingly, going back into the key bindings settings shows that it reverted back to <kbd>cmd</kbd> + <kbd>:</kbd>.
<img width="400" alt="image" src="https://user-images.githubusercontent.com/43589586/231474722-04d97b94-a38c-415b-8c55-d9279847e9e9.png">

- trying to remap to <kbd>cmd</kbd> + <kbd>option</kbd> + <kbd>:</kbd>: no warning that keybinding is already used, exiting settings to try it on text does nothing (but no error sound).
    - going back into the settings shows that it's replaced by <kbd>cmd</kbd> + <kbd>option</kbd> + <kbd>°</kbd> and this works, but to produce it with my keyboard I have to actually press <kbd>cmd</kbd> + <kbd>option</kbd> + <kbd>shift</kbd> + <kbd>)</kbd> which is not practical.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/43589586/231476507-0dc431a8-a5ec-4c95-9e2d-e8ce5be8424c.png"> <img width="400" alt="image" src="https://user-images.githubusercontent.com/43589586/231476659-8b939252-f87b-4eea-84ea-3913ea80c716.png">

### Expected behavior

I want to be able to use the default key binding, or <kbd>cmd</kbd> + <kbd>/</kbd> (which is what I use in VSCode for instance)

### CotEditor version

4.5.2 (562)

### macOS version

13.3.1

### Additional context

Whole system/OS is in English, keyboard is French AZERTY, for reference here is my exact keyboard:

[<img width="400" alt="image" src="https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/mbp-spacegray-select-202206_GEO_EMEA_LANG_FR?wid=1280&hei=1190&fmt=jpeg&qlt=90&.v=1664497359213">](https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/mbp-spacegray-select-202206_GEO_EMEA_LANG_FR?wid=1280&hei=1190&fmt=jpeg&qlt=90&.v=1664497359213)

**Comment by 1024jp** [comment]
Thanks for the report.
It seems this issue depends on the keyboard layout...

@dimitrik-fr What kind of keyboard do you use?

**Comment by dimitrik-fr** [comment]
Well, finally just for testing, I've assigned F1 as Toggle Comment and can test it with Lua, C, C++, etc. -- the problem remains everywhere. Pressing F1 randomly works or not. 

I did not try initial defaults since there are many habits already coming from other code editors (Sublime, Atom, VS Code) where CMD+/ is default key combination for Comments toggling, which I would prefer, but it's not working either, same as in your case ;-))

**Comment by ObliviousMonkey** [comment]
Hm. I just tested it and F1 is working fine here, see [gif](https://s119.convertio.me/p/tNcG0nR4YnZwoyOf9Oo5fQ/ffe7ab04a8abed0973573fc9ec4ec619/Screen-Recording-2023-04-12-at-17.11.17.gif)

**Comment by dimitrik-fr** [comment]
Ok, now restart CotEditor and see if it'll still work again.

**Comment by ObliviousMonkey** [comment]
It does, no issue for me on this part. Our issues do not seem to overlap.

**Comment by 1024jp** [comment]
> @1024jp are you able to reproduce any of this ?

Yes, yes. I've just tried the French (AZERTY) keyboard layout and then reproduced this phenomenon!
Actually, I set the default shortcut for the comment toggling as `Command`-`\` in CotEditor, but the system maybe automatically changed (localized) it for the French layout and it would cause this issue.
I'll investigate further this weekend.

**Comment by 1024jp** [comment]
Apple introduced the keyboard shortcut localization in macOS 12. This is probably the cause in this case. https://developer.apple.com/documentation/appkit/nsmenuitem/3787554-allowsautomatickeyequivalentloca

**Comment by ObliviousMonkey** [comment]
Hm, I'm not sure, because on my machine the default shortcut is <kbd>cmd</kbd> + <kbd>:</kbd>, so it would seem like the mapping _is_ automatically remapped as per the default `True` value of Apple's `allowsAutomaticKeyEquivalentLocalization`. The issue here is that this combination is somehow not recognized by CotEditor. Even when you manually reinput the same combination (meaning pressing those 2 keys <kbd>cmd</kbd> + <kbd>:</kbd> to assign them to comment toggling), it's displayed the same way as the default, and it's also not recognized because the same error sound gets played.

Thanks for investigating!

<img width="682" alt="image" src="https://user-images.githubusercontent.com/43589586/231685409-a9f6fb60-95e7-41ee-b950-038b48e07821.png">

**Comment by ObliviousMonkey** [comment]
Oh wow, I unlocked something! Ok, so I finally got what I wanted, but not the way it's supposed to work.

Steps to reproduce:
1. There is a system shortcut using <kbd>cmd</kbd> + <kbd>shift</kbd> + <kbd>/</kbd> mapped to opening `Help` menu for all apps, useless to me. **Disabled it**
<img width="400" alt="image" src="https://user-images.githubusercontent.com/43589586/231688049-cb766c51-0146-40e7-af18-d622dd68b7d2.png">

2. Set <kbd>cmd</kbd> + <kbd>shift</kbd> + <kbd>/</kbd> as comment toggling key binding: this doesn't work BUT <kbd>cmd</kbd> + <kbd>:</kbd> works! 🥳 
3. Closing and reopening the settings shows that <kbd>cmd</kbd> + <kbd>shift</kbd> + <kbd>/</kbd> has been reassigned to <kbd>cmd</kbd> + <kbd>:</kbd>.  
However this must not reflect exactly what is behind the scenes, since the displayed _default_ <kbd>cmd</kbd> + <kbd>:</kbd> does not work, and the _manually reassigned_ <kbd>cmd</kbd> + <kbd>:</kbd> does not work either.

So nothing is working as intended, but in the end I can use <kbd>cmd</kbd> + <kbd>:</kbd> (which is what I wanted) by setting <kbd>cmd</kbd> + <kbd>shift</kbd> + <kbd>/</kbd>.  
This is a working workaround until you have the time to properly investigate this. I'm guessing this would probably reoccur for other keybindings, but I personally plan to use CotEditor for very basic stuff so I won't run into this again. I hope this helps you investigate.

I only want a lightweight text editor with syntax highlight, comment toggling and so far CotEditor fits the bill perfectly. If I need something more involved, then I can bust out VSCode.

Thanks for your work!

**Comment by 1024jp** [comment]
Thank you for your detailed reports. They help me a lot.

I've just updated the behavior to assign shortcuts to reduce this kind of issue in customizing menu command shortcuts with shortcut key localization.
I hope it works.
I'll release the new version soon (maybe within a few days).
Please be patient for a while.

> 1. There is a system shortcut using <kbd>cmd</kbd> + <kbd>shift</kbd> + <kbd>/</kbd> mapped to opening `Help` menu for all apps, useless to me. **Disabled it**

This procedure seems to be required at least with a French keyboard. I could not find a way to override this in an application and at the same time feel it is better to leave it as is.

**Comment by 1024jp** [comment]
Today, I released CotEditor 4.5.3 which addressed this issue.
I hope it fixes the issue with your keyboard.

Let me know if it still doesn't work well.

**Comment by ObliviousMonkey** [comment]
Updated, reset shortcuts to default, and the default shortcut now works great out of the box for me, thanks!
