### ISSUE TITLE
ファイルサイズ表示の粒度が荒くなっている

### ISSUE THREAD

**Issue by aitch-u** [coteditor/CotEditor#1474]
### Description

ステータスバーに表示されている現在のファイルサイズ（1.23kb等）が小数点以下を表示しないようになってしまっているようです。
4.4.4までは1.23kbと表示され、4.4.5以降は1kbと表示されるようです。

### To Reproduce

保存済みのファイルを開いてステータスバーを確認すると再現されます。

### CotEditor version

4.4.5

### macOS version

13.2.1

**Comment by 1024jp** [comment]
現象としては確認しました。これは指摘のCotEditorバージョンで、ファイルサイズ計算を新しいAPIに変更したことに起因しています。
改めて確認しましたが、現状新しいファイルサイズ計算のAPIがこの辺の小数点以下の表示に対応していません。
メンテナンス性を鑑みると、これのために古いAPIに戻るのはCotEditorの開発方針を合わないため実装を見送らせてください。
Finderでのファイルサイズの表示精度も現行のCotEditorと同レベルなので、誤りと呼ぶほどではないかと考えます。
一方意図して数字を丸めているわけでもなく、用途によっては不便なことは理解できるので、別途Appleには要望を出しておこうと思います。

cf. https://fuckingformatstyle.com/byte-count-style/
