### ISSUE TITLE
Key bindings won't save

### ISSUE THREAD

**Issue by ceciliacase** [coteditor/CotEditor#1476]
### Description

My "Replace All" key binding got deleted, so I went in to re-add it. It will not save the key binding.

### To Reproduce

1. Go to GotEditor > Settings > Key Bindings.
2. Go to Find and find "Replace All".
3. There is no key binding entered.
4. Double-click on the field to enter the key binding
5. Use the binding control + command + G.
6. The key binding is entered.
7. Go to one of the other menu items like "Snippets", then go back to "Key Bindings"
8. The binding has disappeared.

### Expected behavior

I expect the key binding to be saved

### CotEditor version

Version 4.5.3 (564)

### macOS version

13.2.1 (22D68)

**Comment by 1024jp** [comment]
Thank you for the report.
CotEditor 4.5.4, which fixes this issue, has just been released today (on the MAS, and the non-AppStore version will be released within a day).
Let me know again when it is not released in the new version.
