### ISSUE TITLE
"Keep on Top" feature blocks all windows from coming back to the foreground in certain cases

### ISSUE THREAD

**Issue by mtj0928** [coteditor/CotEditor#1478]
### Description

Hello, thank you for the tool, and I love the new feature, "Keep on Top".

By following a few steps, all windows, including those from other apps, become unable to come back to the foreground when using the Stage Manager and the "Keep on Top" feature.

### To Reproduce

1. Activate Stage Manager
2. Activate "Keep on Top"
3. Click the yellow button to minimize the window

https://user-images.githubusercontent.com/12427733/232928653-c729adb9-88c8-4e0f-b519-bb078990b589.mp4

### Expected behavior

All windows can come back to the foreground even after the window has been minimized.

### CotEditor version

4.5.4 (566)

### macOS version

13.2.1

**Comment by mtj0928** [comment]
After the issue occurs, all windows become unavailable. 
To recover, by deactivating StageManager, all windows can come back to the foreground.

**Comment by 1024jp** [comment]
Thank you for the report. I confirmed the phenomenon.
However, at the same time, I found this is an issue on the macOS side since exactly the same thing happens also in Notes.app by Apple.
I'll report it to Apple later.
In addition, I`ll add a workaround of this issue in the next version.

**Comment by 1024jp** [comment]
> I'll report it to Apple later.

Reported: FB12129976
