### ISSUE TITLE
Automatically change extension with syntax highlighting selection

### ISSUE THREAD

**Issue by I7T5** [coteditor/CotEditor#1480]
### Problem
I use txt all the time. When I don't add the file extension to my document name, CotEditor saves it as a document with no extension, which is not super convenient. 

### Solution
Automatically change extension with syntax highlighting selection upon last save. 

### Alternatives
Manually adding extensions.

**Comment by 1024jp** [comment]
This request is based on the same issue as #1542 and this will be solved in the next version CotEditor 4.8.5.
