### ISSUE TITLE
Maintain highlighting on matching braces

### ISSUE THREAD

**Issue by TravellingGuy** [coteditor/CotEditor#1482]
﻿**Is your feature request related to a problem? Please describe.**
On longer files, it's difficult to find/see matching braces if they are not visible in the current window view. When you click on a brace, it highlights the matching brace for a second or two, but on longer documents, this isn't useful.

**Describe the solution you'd like**
When your cursor is on a brace, maintain some sort of highlighting on the matching brace so you can scroll up/down in the document to find the matching brace easily. As well, a menu option and/or shortcut to jump to the matching brace.

**Describe alternatives you've considered**
The alternatives I've considered are trying to scroll really, really fast before the current highlight disappears. This didn't work. :-)

**Additional context**
Nuthin.

**Comment by 1024jp** [comment]
FYI, you can select the content of matching braces by double clicking a brace.

**Comment by georgesnow** [comment]
@1024jp  is there a keyboard shortcut to highlight and select the text within the braces? So if the cursor is within a brace i want to select that bracket like double clicking the brace.

**Comment by 1024jp** [comment]
In the next major update to be released this fall, a command named "Select Enclosing Symbols" will be added.

<img width="590" alt="Screenshot 2024-06-29 at 12 08 29" src="https://github.com/coteditor/CotEditor/assets/1165044/ceca9393-7365-492a-a181-8ee1a0882c97">
