### ISSUE TITLE
JSON編集時、総文字数が50万字を超えたあたりから、一文字を追加、削除するのに10数秒かかる。

### ISSUE THREAD

**Issue by Kota1021** [coteditor/CotEditor#1488]
### Description

タイトルの通り、JSONで50万文字を超えたあたりから、動作が急に怪しくなります。
また、100万文字を超えるとフリーズ、強制終了することが多いです。

素晴らしいアプリを公開していただきありがとうございます。起動が一瞬でUIはシンプルなのに、正規表現での検索に対応しているなど多機能で、いつもありがたく使わせていただいています。
あまりにも大量の文字数なので、仕方ないのかもしれないですが、もしご改善いただけたらより一層素晴らしいものになると思いご報告させていただきました。

### Expected behavior

字数がパフォーマンスに影響しない

### CotEditor version

4.5.5 (569)

### macOS version

13.1 Ventura 

### Additional context

MacBook Air M1, 2020 16GB memory

**Comment by 1024jp** [comment]
> 字数がパフォーマンスに影響しない

お察しの通り、これに関しては現実的には全く影響しないというのは難しいです。
ただ、特定の操作が影響していてそこは迂回できる、ということはあるかもしれないので、
もう少し詳しい状況を知りたいです。

> タイトルの通り、JSONで50万文字を超えたあたりから、動作が急に怪しくなります。

JSON以外のシンタックス（例えばXML）にしたときはこの問題は発生しないですか？
できればその状態が実際に再現できるファイルを提供いただけると幸いです。

> また、100万文字を超えるとフリーズ、強制終了することが多いです。

もしクラッシュログありましたらこちらもいただけると幸いです。

**Comment by 1024jp** [comment]
本件お時間かかっており恐縮です。
今日改めて調査したところ、現行の実装だと、改行のない長大なテキストの処理に著しく時間がかかる箇所があることがわかりました。
この処理自体はこれ以上詰められないので仕方ないにせよ、ユーザの操作をブロックしないようにできないかは検討の余地がありそうです。ただ、わりと根深い箇所でもあるので、中長期的な課題にさせてください。

**Comment by 1024jp** [comment]
dev note: [This line](https://github.com/coteditor/CotEditor/blob/38873f69bfd6023c3ca9d42111278421fc377e80/CotEditor/Sources/LineRangeCacheable.swift#L160) takes enormous time when the string has just few line endings.

**Comment by 1024jp** [comment]
なお、迂回方法としては、「編集」設定の「折り返した行のインデント」をオフにすると大幅に時間が短縮されます。

**Comment by Kota1021** [comment]
ご多忙な中改めて調査していただき、ありがとうございます。
いただいたヒントの通り、「折り返した行のインデント」をオフにすると2、3秒で反映されました。
私もSwiftを書くので（初学者ですが…）プロジェクトファイルをみて勉強し、できるところはPR出して貢献したいと思いました！

**Comment by 1024jp** [comment]
ご連絡漏れていましたが、本件、今月前半にリリースしたCotEditor 4.6.5で修正できたのではないかなと期待しています。いかがでしょうか？

**Comment by Kota1021** [comment]
ご対応、ご連絡ありがとうございます。
CotEditor 4.6.5では長大な文章でも数秒で置き換えができるようになりました。ありがとうございます！
