### ISSUE TITLE
Antialias strange behavior

### ISSUE THREAD

**Issue by bbsixzz** [coteditor/CotEditor#1491]
### Description

Antialias on gives the appearance of antialias off in Terminal.app, antialias off makes text blocky and bold.

Antialias on:
<img width="1161" alt="1" src="https://github.com/coteditor/CotEditor/assets/47334163/1be220e7-5107-4ad1-b336-bb26a832e8e9">

Antialias off:
<img width="1161" alt="2" src="https://github.com/coteditor/CotEditor/assets/47334163/4f66e50b-9667-4c9e-b2a7-e8600d0f0396">

### To Reproduce

Turn antialias on/off.

### Expected behavior

To work as in Terminal.app

### CotEditor version

Version 4.5.6 (571)

### macOS version

macOS 13.4 (22F66)

### Additional context

iMac M1

Font smoothing disabled with `defaults -currentHost write -g AppleFontSmoothing -int 0`

**Comment by 1024jp** [comment]
Please let me know the font your are using.

**Comment by bbsixzz** [comment]
SF Mono Regular 12 but it doesn't matter; same thing happens with Menlo, Monaco.

**Comment by bbsixzz** [comment]
Here's a comparison with both windows at the same time:

<img width="942" alt="Screenshot 2023-07-30 at 10 36 30" src="https://github.com/coteditor/CotEditor/assets/47334163/2a45d917-8180-4ebc-a281-a4e2ccefdabf">

**Comment by 1024jp** [comment]
Thank you. I'll dig it.

**Comment by 1024jp** [comment]
I studied Terminal.app and realized that Terminal antialias text regardless of the user's setting of "Antialiases Text" when the physical display is Retina. That is, Terminal actually antialias text in your screenshot.
In term of CotEditor, I suppose the editor should turn off the antialiasing even with Retina display if the user set so.
Therefore, I'll not change the current setting.

Screenshot with a Retina display
<img width="1170" alt="Screenshot 2023-08-21 at 8 41 52" src="https://github.com/coteditor/CotEditor/assets/1165044/e689277b-1375-44c3-add1-f81bd4ce42cb">


Screenshot with a non-Retina display
![Screenshot 2023-08-21 at 8 41 24](https://github.com/coteditor/CotEditor/assets/1165044/4f35d596-8f14-4e47-b56e-1847f1ef43c0)

**Comment by bbsixzz** [comment]
Are you sure, why does Terminal.app show the font differently with AA on and AA off?

SF Mono Regular 12 in both cases. 

![1](https://github.com/coteditor/CotEditor/assets/47334163/103317fb-5fb3-4670-a76f-6ad08882934b)

**Comment by kim-take** [comment]
I don't know why, but Terminal changes spacing when the font size is below 13.
If I set the font size to 13, I don't see changes other than the antialiasing.
