### ISSUE TITLE
Promptメモ用の使い捨てのエディターとして使えたら最高に嬉しい

### ISSUE THREAD

**Issue by zntrimi** [coteditor/CotEditor#1492]
**Is your feature request related to a problem? Please describe.**
生成AIの文脈として、Promptのメモ書きとしてCoteditorを重宝しています。強力な置き換え機能やPlain Textとして扱えるなどただのメモ帳やテキストフィールドよりもずっと使いやすいです。しかし、一つだけ不便な点があります。Prompt生成のメモでは、あとに保存して文章を残しておきたいような場面はあまりないので、書き終わったら文章を保存せずに使い捨てたいです。一方で、現在の仕様では保存ダイアログが出ずに⌘Qはできると思いますが、再度開くと今までのwindowが復活してしまいます。（これは通常であれば非常に便利だと思います。

**Describe the solution you'd like**

設定のトグルなどで、Disposalモードをオンにしている間は⌘Qでアプリを閉じれば作業中のテキストは破棄されるような設定にする。

**Describe alternatives you've considered**

Appleのスティッキーノートや自作でのノートアプリの作成などは行いましたが、どれもCot Editorの軽快さや便利さには敵わないので、ぜひお願いしたいです。

**Additional context**
Prompt以外にもDisposalなメモ帳としてのニーズは非常に高いと思います！ぜひご検討お願いします。

**Comment by 1024jp** [comment]
ニーズはわからなくもないのですが、取り入れるかは慎重になった方が良い機能かと思うので、検討に時間をください。

**Comment by 1024jp** [comment]
検討したのですが、opt-inであったとしても、やはりユーザの作成したデータを予告なく削除することには抵抗があるので、このリクエストは棄却させてください。

アドバイスとしては、CotEditorは未保存の書類のウインドウを閉じるときにその内容が空ならばダイアログを出さずに勝手に閉じる（消える）ようになっているので、いらない書類を閉じるときは⌘A → 削除 → ⌘Wという操作をするようにクセづけておくと、ダイアログ選択を飛ばせます。
