### ISSUE TITLE
CotEditor for iOS and/or iPadOS?

### ISSUE THREAD

**Issue by I7T5** [coteditor/CotEditor#1493]
### Problem
I need a text editor that's fast, lightweight, and native, with good UI/UX like CotEditor for iOS/iPadOS when I want to work on the go, but there are no such text editor. 

### Proposed Solution
CotEditor for iOS and/or iPadOS

### Alternatives
Looked through App Store but wasn't quite satisfied.

**Comment by 1024jp** [comment]
Close this for duplication of #1094.
Although I understand the demand, it is still quite hard to port CotEditor to iOS/iPadOS since it fully relies on AppKit framework.
