### ISSUE TITLE
Can't hide tab bar though there's an option to hide

### ISSUE THREAD

**Issue by Basharath** [coteditor/CotEditor#1494]
### Description

From menu bar, view option > Hide tab bar (⌘ + Shift + T) 

I can't hide the tab and the option is faded. I'm not sure why it is. 

I want to hide the tab bar with multiple tabs opened but shouldn't be seen.

### To Reproduce

1. Open two or three text files in the Cot Editor
2. Click the `View` in menu bar
3. Select the first option `Hide Tab Bar (⌘ + Shift + T)`
4. See error, you can't click that option, it's faded

### Expected behavior

I want the tabs to be hidden in the cot editor.

### CotEditor version

4.5.6 (571)

### macOS version

13.4

**Comment by 1024jp** [comment]
This is by design.
Apple prevent hiding tab bar when the window has multiple tabs.
I will not change the current behavior.
