### ISSUE TITLE
Find & Replace のハイライトする色の変更

### ISSUE THREAD

**Issue by kkensuke** [coteditor/CotEditor#1495]
設定の Appearance のページの Slection で選んだ色と同じ色を、Find & Replace のハイライトにも適用してくださると嬉しいです。

**Comment by 1024jp** [comment]
文字の選択とハイライトは異なる状態なので同じ色を当てるのは不合理だと考えます。
ハイライトの色を別途選択できるようにするのが正しいかとは思いますが、一方でテーマの設定色を安易に追加したくないのもあり、現時点では不採用とさせてください。
