### ISSUE TITLE
Alternative beep sound for successful find/replace operation

### ISSUE THREAD

**Issue by gingerbeardman** [coteditor/CotEditor#1499]
**Is your feature request related to a problem? Please describe.**
When using search/replace the dialog beeps on success, but it sounds like an error.
It is silent on failure.

**Describe the solution you'd like**
- two different beeps
1. failure (error style beep)
2. success

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by rben01** [comment]
Agree, I think a beep on no matches and no sound on at least 1 match would be preferable.

**Comment by gingerbeardman** [comment]
Yes, current behaviour seems opposite to expected.

Every time I do a replacement I think something has gone wrong and have to double check.

**Comment by 1024jp** [comment]
Aha, you mention about the beep sound on the Replace All command.
I agree that feels weird and confusing. You are right.
I'll simply remove the sound of successful replacement.
Thank you for the feedback.

**Comment by 1024jp** [comment]
I've just shipped this fix with CotEditor 4.5.8.
