### ISSUE TITLE
テキストファイルをスクリプトファイルとして使用したい / Treat plain-text as CotEditor scripting file

### ISSUE THREAD

**Issue by usami-k** [coteditor/CotEditor#15]
（http://sourceforge.jp/ticket/browse.php?group_id=1836&tid=24183 から移動）

ヘルプ項目「スクリプトメニューをカスタマイズする」に「CotEditor は次の拡張子を持つファイルをスクリプトファイルとして認識します：.applescript .scpt .sh .pl .php .rb .py」との記述があります。
単純に定型文を現在の挿入キャレットの位置に流し込むためにスクリプトを使用することも少なくありません。願わくば、.textClipping および .txt のファイルについては単純に「%%%{CotEditorXOutput=InsertAfterSelection}%%%」と同じ挙動をするようにしていただけると助かります。

**Comment by 1024jp** [comment]
ずっとこのイシューは開けっぱなしにしていましたが、やはりこれをスクリプトとして実装するのは悪手だと思うので、クローズします。
スニペット自体はいつの日か改良したい気持ち（全然手をつけられていないですが。
