### ISSUE TITLE
Sparkle shows that the latest version available is 4.5.6

### ISSUE THREAD

**Issue by DAnn2012** [coteditor/CotEditor#1503]
### Description

Hi @1024jp 

Sparkle shows that the latest version available is 4.5.6 because the file at this URL: https://coteditor.com/appcast.xml is not updated

### To Reproduce

![coteditor-sparkle-update](https://github.com/coteditor/CotEditor/assets/1197819/95b29475-8c25-462b-b3c4-90adc869c817)

### Expected behavior

Update to the latest version 4.5.7

### CotEditor version

4.5.6 (571)

### macOS version

12.6.8 (21G725)

### Additional context

Hi @1024jp

I already reported it here three days ago: https://github.com/coteditor/coteditor.github.io/issues/29

Thanks.

**Comment by 1024jp** [comment]
Sorry for taking the time to update the non-AppStore version.
Now, you can update through the updater.
