### ISSUE TITLE
Add settings to suppress the inconsistent line-ending warning pop-up

### ISSUE THREAD

**Issue by czack810150** [coteditor/CotEditor#1507]
**Is your feature request related to a problem? Please describe.**
As a software developer, I've used CotEditor to open all sorts of logs files all the time and many of them have inconsistent line endings. Every time I open such file, I get a pop-up message saying "The document has inconsistent line endings." and whether I want to convert them. I constantly had to click on ignore for any new files I open which becomes annoying after a few times. 

Can we have a settings to permanently suppress this inconsistent line ending message? This would save people who don't care about line ending a somewhat annoying click.

**Describe the solution you'd like**
Add a check box or something that suppress the inconsistent line ending pop-up when a file is opened. With that check box checked, the pop-up does not show.

**Describe alternatives you've considered**
No alternative

**Additional context**
![image](https://github.com/coteditor/CotEditor/assets/17039493/9740fd5d-8944-4b37-962f-de87337df47b)

**Comment by 1024jp** [comment]
Thank you for sharing your use case.

Actually CotEditor already has a hidden setting `suppressesInconsistentLineEndingAlert` for it. (cf. #1331)
Running the follow command in Terminal suppress the dialog entirely.
```shell
defaults write com.coteditor.CotEditor suppressesInconsistentLineEndingAlert -bool YES.
```

Let me consider further to add a GUI setting for it.
I've thought the demand is a kind of rare case. But if there are specific number of people need this option, it's reasonable to add.

**Comment by czack810150** [comment]
@1024jp thanks for pointing me to the hidden settings. Is there a doc where I can read about all these hidden settings?

**Comment by 1024jp** [comment]
> Is there a doc where I can read about all these hidden settings?

Sorry, but not. I knew it was better to have it, but at the same time, I was too lazy to do it.
In addition, because most of them are just for maintenance or trivial usage, they can be removed suddenly without any announcement.

You can see some of them in the code below and guess from the name... 
https://github.com/coteditor/CotEditor/blob/250072c6e344a4422d1b1ee0070c02b38840074f/CotEditor/Sources/DefaultKeys.swift#L167-L175

**Comment by 1024jp** [comment]
I've added the GUI to suppress the inconsistent line endings warning entirely to the next version.

<img width="712" alt="Screenshot 2023-08-29 at 22 56 54" src="https://github.com/coteditor/CotEditor/assets/1165044/6dfbdf6b-330e-41fc-a24b-5693969b189e">
