### ISSUE TITLE
Make the size of close/maximize/minimize buttons in MacOS consistent

### ISSUE THREAD

**Issue by czack810150** [coteditor/CotEditor#1508]
**Is your feature request related to a problem? Please describe.**
The size of close/maximize/minimize buttons are extremely tiny in the pop-up windows that opened in CotEditor such as the Find & Replace window. It makes it hard to look at and click on, also the inconsistency in buttons size is not very aesthetically pleasing.
<img width="595" alt="image" src="https://github.com/coteditor/CotEditor/assets/17039493/484d24f9-ebd2-44c4-a4dd-c9c4187fd5b8">

**Describe the solution you'd like**
Make the header bar a bit bigger and make the size of the three buttons same as the main window for consistency and perhaps even better accessibility for people with eye or coordination issues.

**Describe alternatives you've considered**
N/A

**Additional context**
<img width="538" alt="image" src="https://github.com/coteditor/CotEditor/assets/17039493/2ed31fea-9e96-4a33-bb67-5527464ee0a1">

**Comment by 1024jp** [comment]
The Find & Replace window in CotEditor is one of a so-called *panels* in the macOS interfaces.
cf. [Panels -Apple Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/panels)
Regarding the panels, small title bar (including small buttons) is used by default for utility panels.
That means, by the way, not all panels should use small title bars. For instance, Settings windows (formerly Preferences windows) are also one of the panel but they use the standard size title bar.
On the other hand, find widows are “[utility panel](https://developer.apple.com/documentation/appkit/nswindow/stylemask/1644672-utilitywindow)” that are used subsidiary with the main document windows to fulfill a specific task: finding and replacing text.
Thus, CotEditor uses the small title bar purposely to conform to the proper macOS application design.

For example, Pages.app by Apple uses the same strategy (utility panel type title bar + regular size controls).
<img width="566" alt="Screenshot 2023-08-15 at 12 58 56" src="https://github.com/coteditor/CotEditor/assets/1165044/00330240-02c7-43c5-a5ab-2151ade48236">

In addition, FYI, if you feel hard to point the close button, you can use Esc key to close the window (This is one of a typical behavior in panels).
