### ISSUE TITLE
Editing huge file fails

### ISSUE THREAD

**Issue by matzepf** [coteditor/CotEditor#1509]
### Description

It is me again, the guy with the huge files: 12.3 MB, 880k lines. With the current version I cannot go below line 606060.

### To Reproduce

1. Create a file with > 610k lines; each line has 13 characters in my case.
2. Open file
3. Type Command Down Arrow
→ Status bar says current line ~880k but start of file is shown (see fig 1)
Drag scroll bar all down
→ View ends with line 606060 (see fig 2)
<img width="434" alt="HugeFile1" src="https://github.com/coteditor/CotEditor/assets/36540028/34bd8b6f-5f3b-4ba0-a621-f0dc7361b3aa">
<img width="415" alt="HugeFile2" src="https://github.com/coteditor/CotEditor/assets/36540028/8e5b0ac2-8109-41e6-8ef2-1ef46b7582af">

### CotEditor version

4.5.8 (574)

### macOS version

13.5 (Build 22G74)

### Additional context

Installed the update 4.5.8 today; worked fine yesterday.

**Comment by matzepf** [comment]
Re-checking on another machine with 4.5.7: Works fine.

<img width="439" alt="Old" src="https://github.com/coteditor/CotEditor/assets/36540028/e1b9a36d-dfe0-4297-bddb-5b270e351d92">

**Comment by matzepf** [comment]
Problem seems to fixed in Version 4.6.1 (591).

**Comment by 1024jp** [comment]
Thank you for the update.
Since I've tweaked the editor on CotEditor 4.6.0 and also Apple improved the text component in macOS 14 SDK, the issue can disappear on CotEditor 4.6.0.
However, feel free to post again if you face that issue again.
