### ISSUE TITLE
CotEditor setting file 

### ISSUE THREAD

**Issue by 25ThirtySix** [coteditor/CotEditor#1511]
### Description

CotEditor changes the file icon for every file type it edits (.txt and .md in my case) from the default macOS icon to a CoTEditor icon.
![grab1](https://github.com/coteditor/CotEditor/assets/142390135/e420643f-2767-46f9-a563-05ddf67157f1)

### To Reproduce

1. Simply open a new or existing file with CotEditor. There does not seem to be a setting to stop this behaviour.

### Expected behavior

**CotEditor is a really good text editor.** I would like to use it for Markdown text editing on my Mac (replacing BBEdit which is probably over the top for my needs) but I find this automatic changing of file icons to be really, really annoying.

BBEdit and Taio (the two text/Markdown editors I currently use do not have this annoying "feature".

CotEditor SHOULD NOT change file icons without the user's permission.

### CotEditor version

4.5.8

### macOS version

13.5.1

**Comment by 1024jp** [comment]
No.
First of all, that's not an icon provided by CotEditor.
File mapping is a task of the macOS system.
CotEditor does nothing for it.
CotEditor just provides the file types that it can process, and macOS decides the icon for document files and with which application to open.
