### ISSUE TITLE
The automatic encoding guessing feature in Windows BAT/VBS file may guess wrong language.

### ISSUE THREAD

**Issue by wbsdty331** [coteditor/CotEditor#1512]
### Description

I have several Windows BAT/VBS files that contain Chinese characters. However, when I open them with CotEditor, the encoding is guessed as Japanese (EUC、ISO 2022-JP and so on). so I have to manually switch to Simplified Chinese (GB2312) every time.

![image](https://github.com/coteditor/CotEditor/assets/4280572/a18da1dd-dde7-445b-86cd-27ff470944b7)

demo file: 
[demofile.zip](https://github.com/coteditor/CotEditor/files/12459973/demofile.zip)

### To Reproduce

just use CotEditor to open these files.

### Expected behavior

CotEditor should guess the correct encoding for these file , like vscode:
![image](https://github.com/coteditor/CotEditor/assets/4280572/c5c82d38-f4f6-442e-9d14-436555fd938d)

### CotEditor version

4.5.8

### macOS version

13.5.1

**Comment by 1024jp** [comment]
This is not a bug. Sometimes, a file can be decoded with multiple file encodings, leaving aside whether the encoding is correct for humans.

CotEditor is capable of customizing the priority of file encodings for encoding detection.
Go to the Format settings pane, press the Edit List button for the priority of encodings, and drag the encodings in the list to make encodings of your language higher than Japanese ones.

<img width="682" alt="Screenshot 2023-08-29 at 22 50 27" src="https://github.com/coteditor/CotEditor/assets/1165044/ffc812c4-14c5-4f09-a2ae-31e9d975b1ad">

**Comment by wbsdty331** [comment]
Thank you very much!
