### ISSUE TITLE
Editor opacity does not persist and resets to fully opaque

### ISSUE THREAD

**Issue by qxrv** [coteditor/CotEditor#1513]
### Description

The "Change Editor's Opacity" option from the 'View' menu does not persist.

### To Reproduce

1. Go to 'View'
2. Click on 'Change Editor's Opacity...'
3. Adjust opacity setting to your liking
4. Quit application
5. Start application
6. Opacity setting reset to 100 (fully opaque)

### Expected behavior

Opacity setting persists and is configured permanently unless changed again manually.

### CotEditor version

5.4.8

### macOS version

13.5.1

**Comment by 1024jp** [comment]
It is not a bug but by design.
The Change Editor's Opacity command in the menu bar (and toolbar) is designed to change the opacity of the frontmost editor temporarily. If you want to set it persistently, Go to CotEditor's Settings > Window settings, and change the editor's opacity there.
