### ISSUE TITLE
Can't open big JSON file

### ISSUE THREAD

**Issue by VadimMuhtarov** [coteditor/CotEditor#1515]
### Description

Hi! I can't open big JSON (8.6 MB) on my Air M2, the process is not responded. 

### To Reproduce

1. Open the attached JSON file in CotEditor

### CotEditor version

4.5.8 (574) 

### macOS version

macOS 14.0 (Build 23A5337a)

### Additional context

<img width="1058" alt="Screenshot 2023-09-05 at 13 03 05" src="https://github.com/coteditor/CotEditor/assets/17072773/1859b74c-0802-4ccf-8488-d951667c64f1">
[Sample of CotEditor.txt](https://github.com/coteditor/CotEditor/files/12522271/Sample.of.CotEditor.txt)
[File.json.zip](https://github.com/coteditor/CotEditor/files/12522280/File.json.zip)

**Comment by 1024jp** [comment]
Thank you for the report.
Now that I've identified the cause of the time-consuming part, I believe this issue will be greatly improved in the next version, CotEditor 4.6.5.
