### ISSUE TITLE
Disable "Correct Spelling Automatically" Globally

### ISSUE THREAD

**Issue by hophead929** [coteditor/CotEditor#1516]
**Is your feature request related to a problem? Please describe.**
I mostly use CotEditor to take notes, and noticed it will "auto-correct" words and acronyms I don't want or need changed.

**Describe the solution you'd like**
I can disable "Correct Spelling Automatically", but only per file. 

**Describe alternatives you've considered**
In Setting or Preferences, there should be a way to disable "Correct Spelling Automatically" globally or at least as a default for new files.

**Additional context**

**Comment by 1024jp** [comment]
Currently, CotEditor respects the user setting in the System Settings: System Settings > Keyboard > Input Sources > All Input Sources.

<img width="827" alt="Screenshot 2023-09-13 at 10 56 42" src="https://github.com/coteditor/CotEditor/assets/1165044/b1760097-95a8-46bc-aea9-9fefb13f59a3">


Do you think you need the option for CotEditor to override the system setting in the app?


Actually, I'm planning to change these options in the near future. I'll take your request into account.

**Comment by hophead929** [comment]
Hello,

I never thought to check keyboard settings for correct spelling automatically. I'll give that a try and see how I like it; it might save me from auto-correct mistakes in email, so that would be a bonus. Thank you!

On Sep 12, 2023, at 9:04 PM, 1024jp ***@***.***> wrote:


Currently, CotEditor respects the user setting in the System Settings: System Settings > Keyboard > Input Sources > All Input Sources.

 <https://user-images.githubusercontent.com/1165044/267512342-b1760097-95a8-46bc-aea9-9fefb13f59a3.png>
Do you think you need the option for CotEditor to override the system setting in the app?

Actually, I'm planning to change these options in the near future. I'll take your request into account.

**Comment by 1024jp** [comment]
From CotEditor 4.8.0, which will be released in this spring, this option becomes to be able to set in individual CotEditor setting 😉.
