### ISSUE TITLE
A problem about behavior of "Outline" sidebar 

### ISSUE THREAD

**Issue by tatsy-ymj** [coteditor/CotEditor#1521]
### Description

I posted the following issue 2023/09/08.

> Description
> When a window is closed and the same file is reopened, the inspector state is not saved.
> 
> To Reproduce
> Create a file. Show "Inspector". Save the file.
> Quit CotEditor, and then open the file again. There is no problem.
> However, close the file window (not "Quit") and reopen the file, the inspector state is not saved.

I thought the problem was resolved, but that was my mistake (the reason for my mistake was that I reinstalled 4.5.9), and I post again because the same problem occurs with 4.6.0 beta3.

1. Create a file, "View"->"Inspector"->"Outline"
<img width="837" alt="スクリーンショット 2023-09-13 15 30 34" src="https://github.com/coteditor/CotEditor/assets/4995795/9ea68c73-a1d4-435f-9a15-cac77931f5bc">

2. Close the above window (not "Quit").

3. Reopen the file. "Outline" sidebar doesn't appear.
<img width="837" alt="スクリーンショット 2023-09-13 15 30 50" src="https://github.com/coteditor/CotEditor/assets/4995795/eae4b25b-ebcf-42d3-81a7-9ba4be96d456">

4. "View"->"Inspector"->"Outline", Quit CotEditor
<img width="837" alt="スクリーンショット 2023-09-13 15 31 05" src="https://github.com/coteditor/CotEditor/assets/4995795/d22b485b-acc2-42ef-bc63-2c9556570ee9">

5. Reopen the file. "Outline" sidebar appears.
<img width="837" alt="スクリーンショット 2023-09-13 15 31 17" src="https://github.com/coteditor/CotEditor/assets/4995795/c72d5a57-f4c6-4232-a3fb-c6d488861b50">

The "Outline" sidebar behaves differently when closing the document window and when exiting CotEditor.

### CotEditor version

4.6.0-beta.3 (585)

### macOS version

13.5.2（22G91）

**Comment by 1024jp** [comment]
Ok, now I understand.
The issue is the initial visibility of the inspector for a document does not take over from the last document.
Then, that's not what I designed, and I confirmed it doesn't work in the latest beta.
Let me have some time to fix it.

**Comment by 1024jp** [comment]
Fixed.
