### ISSUE TITLE
CotEditor 4.6.0 "Settings -> General -> On startup -> When nothing else is open:" is broken.

### ISSUE THREAD

**Issue by suishouen** [coteditor/CotEditor#1525]
### Description

CotEditor 4.6.0 "Settings -> General -> On startup -> When nothing else is open:" is broken.
1) "Show open dialogue" doesn't work.
2) "Do nothing" option is missing.

So every time I start CotEditor 4.6.0 opens a new window.

### To Reproduce

1) Open "Settings -> General -> On startup -> When nothing else is open:"
2) Set "Show open dialogue".
3) You see  "Do nothing" option is missing.

### Expected behavior

"Settings -> General -> On startup -> When nothing else is open:" works as 4.5.9.
1) Setting "Show open dialogue" opens "Open Dialogue".
2) Seting "Do nothing" opens no window.

### CotEditor version

4.6.0

### macOS version

13.6 Ventura

**Comment by 1024jp** [comment]
Thank you for the report!

> "Show open dialogue" doesn't work.

Oh, that's definitely a bug to be fixed.
I'll release CotEditor 4.6.1 to fix this issue tomorrow.

> "Do nothing" option is missing.

That's an intentional change on CotEditor 4.6.0 described in the release notes.
