### ISSUE TITLE
Objective-C  support

### ISSUE THREAD

**Issue by mike1023** [coteditor/CotEditor#1526]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
when I paste some code written by objective-c, it shows like 'text'. So, can you add some highlight support for objective-c?

**Describe alternatives you've considered**

**Additional context**

**Comment by 1024jp** [comment]
Close the issue as this is a duplicated request. The syntax style for Objective-C is intentionally not bundled. See #990.
