### ISSUE TITLE
 The `Do Nothing' Startup Option is no longer available.

### ISSUE THREAD

**Issue by herbs** [coteditor/CotEditor#1527]
### Description

I can only choose `Open New Document' or `Show Open Dialog' at Startup if I don't open previous documents. In earlier versions of CotEditor I was able to choose `Do Nothing'. I prefer that so I can just have it sit in the background.

### To Reproduce

1. Go to 'CotEditor->Settings'
2. Click on `When nothing eldse is open:' option popup
3. See lack of `Do Nothing; option

### Expected behavior

In earlier versions of CotEditor I could choose my preferred `Do Nothing' at startup.

### CotEditor version

4.6.1

### macOS version

14.0

**Comment by 1024jp** [comment]
Yes. That's an intentional change on CotEditor 4.6.0 described in the release notes.
