### ISSUE TITLE
^\n is crashing the app on the Find & Replace panel

### ISSUE THREAD

**Issue by crashdu** [coteditor/CotEditor#1529]
### Description

^\n is crashing the app on the Find & Replace panel
<img width="606" alt="Screenshot 2023-10-02 at 22 26 38" src="https://github.com/coteditor/CotEditor/assets/136755131/e857b2a8-3d0c-4c84-a590-71f2fb5457d3">

### To Reproduce

1. On any document with more than one return
2. Invoke Find & Replace
3. type ^\n in the search field
4. Check “Regular Expression” 
5. Click “Find All” 

### Expected behavior

Not a crash

### CotEditor version

4.6.1 (591)

### macOS version

14.0

**Comment by 1024jp** [comment]
Thank you for the report.
This issue fixed on CotEditor 4.6.2, which I've just submitted.
