### ISSUE TITLE
Hang whilst opening large SVG file where data is all on one line

### ISSUE THREAD

**Issue by gingerbeardman** [coteditor/CotEditor#1532]
### Description

Hang whilst opening 5.6MB SVG file where data is all on one line.

### To Reproduce

1. Expand this zip [image.svg.zip](https://github.com/coteditor/CotEditor/files/12833548/image.svg.zip)
2. Open SVG in CotEditor
3. Hang [crash.txt.zip](https://github.com/coteditor/CotEditor/files/12833566/crash.txt.zip)

### Expected behavior

- should not hang

### CotEditor version

4.5.9

### macOS version

12.7

### Additional context

- SublimeText opens the file just fine

**Comment by 1024jp** [comment]
Thank you for the report.
I know that CotEditor has terrible performance when the editor has a long long line that has no line breaking in-between.
It stems from the implementation of TextKit, how it calculates the line fragment box.
So far, I feel it is hard to get around.
I look it again later but I need to say I maybe not be able to fix it right away.

**Comment by gingerbeardman** [comment]
No worries.

It would be good to first figure out what line length it begins to happen at. My example here is very long, but it happens also in a much smaller example.

**Comment by 1024jp** [comment]
Now that I've identified the cause of the time-consuming part, I believe this issue will be greatly improved in the next version, CotEditor 4.6.5.
