### ISSUE TITLE
「行の折り返し」のツールバー・アイコンの説明表示

### ISSUE THREAD

**Issue by wanik** [coteditor/CotEditor#1533]
### Description

ツールバーのアイコンにカーソルを当てると説明が表示されます（「アイコンのみ」の表示を選択した場合）。
「行の折り返し」のアイコンには、【する／しない】の2つのモードがありますが、折り返しをさせない場合の斜線付きアイコンの場合にも、「行を折り返す」という説明が表示されます。

モードに合わせて、「行を折り返す」／「行を折り返さない」といった内容に表示が切り替わるほうがより適切と思われます。

### To Reproduce

1. ツールバーのカスタマイズ設定で、「アイコンのみ」の表示を選択します。
2. 「行の折り返し」のアイコンをクリックし、モードを切り替えます。
3. どちらの場合も「行を折り返す」という説明が表示されます。

下図の右側、赤いマーキング部分。
（青いほうは、不可視文字の表示／非表示の切り替えの事例です。）

![gyo_orikaeshi](https://github.com/coteditor/CotEditor/assets/34469683/8647565b-60df-49d1-8f62-5902562f692d)

### Expected behavior

アイコンに斜線が付くモードでは、「行を折り返さない」などの説明が表示されるほうがより適切と思われます。

### CotEditor version

CotEditor: 4.6.2 (594)

### macOS version

System: macOS バージョン13.3.1（ビルド22E261）

**Comment by 1024jp** [comment]
フィードバックありがとうございます。
ご指摘ごもっともだと思いますので、次バージョンで変更します。

**Comment by wanik** [comment]
どうもありがとうございます。

念のための追記です。
不可視文字の表示／非表示のほうですが、
ツールバーを「テキストのみ」にした場合、
ツールバー上の表示が「不可視文字を非表示」のままで
「表示／非表示」のように切り替わらないようです。
こちらもご確認をいただけますと助かります。
（機能は問題ありません。あくまでツールバー上の表示の問題です。）

**Comment by wanik** [comment]
さらに、追加でスミマセン。
ツールバーを「アイコンとテキスト」にした場合、
行の折り返しのほうは、「折り返す／折り返さない」のように切り替わりますが、
不可視文字のほうは、「不可視文字」と表示されるだけで、
モードの違いが表示されないようです。
統一感があったほうがよいかと思われました。
