### ISSUE TITLE
Combining Diacritical Marks を複数入力した場合、ベースの文字の横に並んで表示される

### ISSUE THREAD

**Issue by wanik** [coteditor/CotEditor#1535]
### Description

合成可能なディアクリティカルマーク Combining Diacritical Marks を**複数**入力した場合、
それらが縦に重ならずに、ベースとなる文字の横に並んで表示されます。

### To Reproduce

（以下の画像もご参照下さい。）

1. ‘fam’ と打ってから a の後ろにカーソルを戻して、U+0304 を入力
        ==> 合成可能なディアクリティカルマークが 1つの場合は、問題ありません。

2. ‘fam’ と打ってから a の後ろにカーソルを戻して、U+0306 を入力
        ==> 合成可能なディアクリティカルマークが 1つの場合は、問題ありません。

3. ‘fam’ と打ってから a の後ろにカーソルを戻して、U+0304、U+0306 を入力
        ==> 合成可能なディアクリティカルマークが 2つの場合は、
            **2つめが、ベースとなる文字の横に表示されます。**

4. ‘fam’ と打ってから a の後ろにカーソルを戻して、U+0304、U+0306、U+0301 を入力
        ==> 合成可能なディアクリティカルマークが 3つの場合も、
            **2つめ以降が、ベースとなる文字の横に表示されていきます。**

5. ‘fam’ と打ってから a の後ろにカーソルを戻して、、U+0304、U+0306、U+0301 を入力し、
    次に m の後ろにカーソルを移して、U+0303 を入力
        ==> 合成可能なディアクリティカルマークが 2つ以上の場合に、
            **直後にある**合成可能なディアクリティカルマークのない文字に対して
            合成可能なディアクリティカルマークを入力すると、
            横に並んだディアクリティカルマークが縦に重なります。
            （直後の文字の場合でないと、効き目がないようです。
            fam を fame にして、e に対してクリティカルマークを入力しても、
            a に対するディアクリティカルマークには変化がありません。）

![cdm_cot](https://github.com/coteditor/CotEditor/assets/34469683/69363e22-3b92-45e6-86a5-04e23a96f08d)

なお、フォントは、等幅に Menlo Regular 16 （アンチエイリアスに✓）、行の高さ1.4倍です。

因みに、CotEditor 3.9.7 (437)、macOS 10.13.6 という古い環境では、
合成可能なディアクリティカルマークを複数入力しても、
ベースとなる文字の上下に重なって表示され、問題ありませんでした。
（フォントの設定は、上と同じです。）

### Expected behavior

仕様とかフォントの問題でなければ、
合成可能なディアクリティカルマークが、ベースとなる文字の上下に重なって表示される
のが望ましいと思われます。

### CotEditor version

CotEditor: 4.6.2 (594)

### macOS version

macOS バージョン13.3.1（ビルド22E261）

**Comment by wanik** [comment]
**等幅フォント**を設定すると、こうなるようですね。
Times New Roman などですと、上記の事象は発生しませんでした。

そういう意味では、仕様なのかもしれませんが、
等幅フォントの場合でも、合成可能なディアクリティカルマークが重ね打ちできるほうがありがたいです。

**Comment by 1024jp** [comment]
レポートありがとうございます。
状況は理解しました。
が、追加のコメントでもある通り、フォント側に起因する仕様となり、CotEditorでは手を加えていない箇所なので、現状のママとしたいです。
（TextKit 2でも試してみましたが、状況は変わらずです）
時間があるときにApple側にフィードバックとして挙げておきます。

**Comment by wanik** [comment]
ありがとうございます。
確かに、フォントに起因するようですね。

等幅 vs. プロポーショナル ということでもなくて、
プロポーショナル系でも、現象が出るものと出ないものがありました。

また、テキストエディットなど、他のエディタやワープロアプリでも
同じような状況となりました。
異なるアプリ間でコピペしても同じでした。

一方で、上記 5. の現象は、フォント側も問題としても、不可解な感じもします。

今後の Apple側のアップデートで改善があるかも知れませんので、
引き続きどうぞよろしくお願いいたします。

**Comment by ShikiSuen** [comment]
@wanik 横から失礼しますが、このフォントも同じ支障かどうかご確認いただけませんか……
https://github.com/be5invis/Sarasa-Gothic
（Sarasa Fixed Slab J はこのフォントの日本語バージョンです。）

**Comment by wanik** [comment]
Sarasa-Gothic (iosevka-n-fixed-slab-regular.ttf) で試してみました。
上記と同じ事例を入力してみましたが、3.〜 5. においても問題はありませんでした。

![sarasa_iosevka_font_fixed](https://github.com/coteditor/CotEditor/assets/34469683/5dc9cf5a-581b-436c-916f-6de7f2a581c2)
