### ISSUE TITLE
現在の行の背景色に設定した色が付かない

### ISSUE THREAD

**Issue by snycainzokmy** [coteditor/CotEditor#1537]
### Description

”設定画面ー外観ー現在の行”で設定した色が表示されない。

### To Reproduce

- 設定画面ー外観
<img width="603" alt="設定ー外観" src="https://github.com/coteditor/CotEditor/assets/146687245/02ec7674-da8d-4836-b9eb-611887a36eba">

- 設定画面ーウィンドウの”現在の行：背景カラーを変更”を選択
<img width="598" alt="設定ーウィンドウ" src="https://github.com/coteditor/CotEditor/assets/146687245/c7b411dc-b535-4029-8db4-49f008eb0763">

- ↓はカーソルが２行目にある状態です。
<img width="999" alt="lineno2" src="https://github.com/coteditor/CotEditor/assets/146687245/567ea934-09c9-4d16-839b-b5f81d1fd17d">

### Expected behavior

現在の行の背景色に設定した色が表示されること。

### CotEditor version

4.6.2 (594)

### macOS version

macOS バージョン13.6（ビルド22G120）

### Additional context

Language: Japanese

<img width="271" alt="macbookpro" src="https://github.com/coteditor/CotEditor/assets/146687245/9153bfd8-c18e-498d-85b6-db12029cccd1">

- Apple M1チップのMacBook Pro（macOSのバージョンは同じ）ではこの現象は起きていません。

**Comment by 1024jp** [comment]
レポートありがとうございます。本件CotEditor 4.6.0でのバグです。
次バージョンで修正します。
