### ISSUE TITLE
Highlight current line does not work

### ISSUE THREAD

**Issue by Andreas0602** [coteditor/CotEditor#1539]
### Description

The background of the current line is not shown in the configured color.

### To Reproduce

Turn on the option to highlight the current line.

### Expected behavior

The current line will be highlighted.

### CotEditor version

4.6.2 (594)

### macOS version

macOS Version 14.0 (Build 23A344)

### Additional context

Further problem: When you turn on the option to highlight the current line and then re-start CotEditor, the option will be turned off. In other words: CotEditor forgets the setting of that option.

**Comment by 1024jp** [comment]
Thanks for the report.
This issue will be fixed in the next version.

**Comment by 1024jp** [comment]
duplicate #1537
