### ISSUE TITLE
.txt not added to Plain Text files

### ISSUE THREAD

**Issue by FirasAleem** [coteditor/CotEditor#1542]
### Description

Hello,

I have Plain Text set as the default format, and it shows up on the top right as "Plain Text", however when I save the file, it saves with no extension. I have to add .txt manually for it to show up. I’ve tried changing the default format to something else, like C and it saves with .c but refuses to with a plain text file

### To Reproduce

1. Open CotEditor
2. Save file with default set as plain text
3. File saves without .txt extension

### CotEditor version

4.6.3

### macOS version

14.0

**Comment by 1024jp** [comment]
Sorry for taking the time to reply.

The Save dialog on macOS has a feature to toggle hide file extension.
This option became hard to find in modern operating systems, but it is in a menu on the Save dialog.
Does this situation apply to you?

<img width="505" alt="Screenshot 2024-05-28 at 9 22 28" src="https://github.com/coteditor/CotEditor/assets/1165044/d659ab18-eac2-42b4-bb20-72561e949772">


If so, I recently found the file extension is completely removed when the option is turned on.
I'll fix this issue on the next version by just disabling the option.
(It is of course better if I could fix it without disabling it. However, this seems not easy on CotEditor...)

**Comment by FirasAleem** [comment]
Hey, no worries! This seems to have fixed it, thanks!
