### ISSUE TITLE
Review Spanish localization since CotEditor 4.6.0

### ISSUE THREAD

**Issue by 1024jp** [coteditor/CotEditor#1543]
@techagus In CotEditor 4.6.0, I updated the Spanish localization by myself by using machine translation in https://github.com/coteditor/CotEditor/commit/761b7cb9b00202c94af6c6c162da1c52ba15bbce.
CotEditor 4.6.0 has already been released on 25 Sep. 2023, but I'm still not sure whether my change is acceptable as Spanish localization.
So, when you have time, please review them to see whether they have any odd translations.

_Originally posted by @1024jp in https://github.com/coteditor/CotEditor/issues/1519#issuecomment-1732270543_

**Comment by 1024jp** [comment]
Added translation for CotEditor 4.7.0 in #1553.

**Comment by 1024jp** [comment]
Added translation for CotEditor 4.7.2 in a8b4062a764f3393a1df75a0a7c45ce5da7c04de (cf. https://github.com/coteditor/CotEditor/issues/1573) and also c523f941dfc8b1317928a45d58b149456f1d971c.

**Comment by 1024jp** [comment]
Because all the localizable strings were migrated to new String Catalog format, the previous diff may not work anymore.
So please work directory in Xcode. The status of all the Spanish strings requiring native check are marked as "NEEDS REVIEW" in the Xcode string catalog editor.

If you have further questions about the new String Catalog, feel free to let me know.

**Comment by bucanero** [comment]
hi @1024jp , I'm a native Spanish speaker, so if this is still open I can help and review the translation

**Comment by 1024jp** [comment]
@bucanero  Thank you for the kind offer!

I actually have just decided to find a new maintainer for the Spanish localization recently.
Therefore, I have to find a new maintainer for the Spanish localization anyway.
But one-time review is also helpful in this situation.
(If you are interested also in being the maintainer, let me know.)

cf. [Localization maintenance instruction for CotEditor project](https://github.com/coteditor/CotEditor/blob/main/CONTRIBUTING.md#localization)

Well, have you experienced localizing applications for Apple products using Xcode?
If yes, the process would be simple follow the guidance below.
If no, I'll share a localization template only for Spanish localization so that you can work easily. Let me know.

### Reviewing process for existing localization strings

Fork the CotEditor repo (this one) and open `CotEditor.xcodeproj` in Xcode.
Under the Resources section, there are the Storyboard and Localizables subsections.
In those sections, there are multiple files for the localization.
In each localization file, you can see the percentage of the completion.
If the Spanish is not 100%, it means there are some strings to be reviewed.

<img width="1552" alt="Screenshot 2024-04-28 at 20 00 11" src="https://github.com/coteditor/CotEditor/assets/1165044/01cb8357-0889-4ba3-ae9d-363bf0afc931">

All strings to be reviewed are marked as `NEEDS REVIEW` with an orange badge.
When you edit the string, it will turn into `Reviewed` (with a green checkmark).
If there is nothing to change, just mark them as `Reviewed` via the context menu on each table row.
<img width="280" alt="Screenshot 2024-04-28 at 20 03 10" src="https://github.com/coteditor/CotEditor/assets/1165044/16694c13-b348-41aa-b53f-62019616a40b">

Repeat the process for all localizable files.

The current Spanish strings to be reviewed are written by me using machine translation and my poor knowledge of Spanish.
So, it would contain a lot of odd expressions for native speakers.

If you have any question, feel free to ask me.

**Comment by 1024jp** [comment]
I close this issue to transfer the recruitment to #1709

**Comment by 1024jp** [comment]
@bucanero Please let me know whether you are still interested in reviewing. Just a one-time reviewing the existing strings is also helpful.
