### ISSUE TITLE
Add keyboard shortcut to add additional cursor on line below

### ISSUE THREAD

**Issue by rben01** [coteditor/CotEditor#1545]
**Is your feature request related to a problem? Please describe.**
VSCode has the shortcut ⌘⌥↓ to add an additional cursor at the same horizontal position on the line below. (And similarly for up-arrow and the line above.) This would be great to add to CotEditor.

**Describe the solution you'd like**
Add keyboard shortcuts to add a cursor below or above.

**Describe alternatives you've considered**
Command-clicking to create multiple cursors (less convenient).

**Additional context**
None

**Comment by 1024jp** [comment]
In CotEditor, those shortcuts are Control-Shift-↓ and Control-Shift-↑.

**Comment by rben01** [comment]
Thanks. Is this documented anywhere, or present in the menu bar? Those would be good changes.

**Comment by 1024jp** [comment]
> Is this documented anywhere, or present in the menu bar?

It doesn't present in the menu bar, but documented in the CotEditor User Guide, which can be accessed from the Help > CotEditor Help.

<img width="744" alt="Screenshot 2023-11-23 at 20 02 30" src="https://github.com/coteditor/CotEditor/assets/1165044/654b87f5-cf96-49c6-b628-41c52a811ef0">
