### ISSUE TITLE
Increas number of recent files, or make it configurable

### ISSUE THREAD

**Issue by rovf** [coteditor/CotEditor#1547]
Currently, it seems that the numer of recent files (i.e displayed in File/OpenRecent) is limited to 15, which I find pretty small. Please increase this limit (32 would sound good to me), or put an option into the Preferences, where one can define the numer of recent files to be remembered.

- CotEditor: 4.5.4 (566)
- System: macOS Version 12.6.9 (Build 21G726)

**Comment by rovf** [comment]
I don't have this "control center" in my System Preferences:

<img width="780" alt="Screenshot 2023-11-23 at 01 32 59 PM" src="https://github.com/coteditor/CotEditor/assets/6795665/accf9e6a-004f-4c96-ae24-a755dd5aa407">

**Comment by 1024jp** [comment]
Aha, then you can find the same option in the General settings (if I remember correctly).

**Comment by rovf** [comment]
Indeed!! There it is!!!! Thanks a lot. I find it bizarre to have such an option configurable at the system level, but if Apple decided to have it, it makes of course sense if applications honour it. Nevertheless, configuring it for each application separately would make more sense to me.

**Comment by 1024jp** [comment]
That's good to hear :)

> Nevertheless, configuring it for each application separately would make more sense to me.

Yeah, that's reasonable. However, CotEditor has a policy to have less configurable options as much as possible to avoid messy setting options. It's just my decision.
