### ISSUE TITLE
4.6.5 crashing on launch on ARM-64 mac 14.1.1 

### ISSUE THREAD

**Issue by mayel** [coteditor/CotEditor#1551]
### Description

The app used to work great but not able to launch it for a while now. Some details below:

```
Process:               CotEditor [35267]
Path:                  /Applications/CotEditor.app/Contents/MacOS/CotEditor
Identifier:            com.coteditor.CotEditor
Version:               4.6.5 (601)
App Item ID:           1024640650
App External ID:       861390420
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-11-19 16:24:23.2007 +0000
OS Version:            macOS 14.1.1 (23B81)
Report Version:        12

Time Awake Since Boot: 170000 seconds
Time Since Wake:       2633 seconds

Crashed Thread:        11  Dispatch queue: NSDocumentController Opening (QOS: UNSPECIFIED)

Exception Type:        EXC_BAD_ACCESS (SIGBUS)
Exception Codes:       KERN_MEMORY_ERROR at 0x000000010f558000
Exception Codes:       0x000000000000000a, 0x000000010f558000

Termination Reason:    Namespace SIGNAL, Code 10 Bus error: 10
Terminating Process:   exc handler [35267]

VM Region Info: 0x10f558000 is in 0x10f558000-0x10f55c000;  bytes after start: 0  bytes before end: 16383
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      Accelerate framework        10f538000-10f558000    [  128K] rw-/rwx SM=PRV  
--->  mapped file                 10f558000-10f55c000    [   16K] r--/rw- SM=COW  ...t_id=dcfa16f5
      mapped file                 10f55c000-10f560000    [   16K] r--/rw- SM=COW  ...t_id=d72f8af5

Kernel Triage:
VM - (arg = 0x0) Filesystem pagein returned an error in vnode_pagein
VM - (arg = 0x0) Page has error bit set

```
### To Reproduce

I did try uninstalling (including Library files) and reinstalling to no effect.

### CotEditor version

4.6.5 

### macOS version

14.1.1

**Comment by 1024jp** [comment]
Thank you for the report.
However, I could not specify the cause of your crash.
Could you provide the entire crash log?

In addition, try removing the file at `/Library/Containers/com.coteditor.CotEditor/Data/Library/Autosave Information/com.coteditor.CotEditor.plist` and relaunch CotEditor.

**Comment by mayel** [comment]
Thanks I tried that with no result but then I deleted the entire `~/Library/Containers/com.coteditor.CotEditor` and now it works :) I guess those files weren't included in what AppCleaner deleted when I tried uninstalling the app.

**Comment by 1024jp** [comment]
> Thanks I tried that with no result 

Thank you for the further information.
I guessed something went wrong during reopening a document, but I suppose I was wrong. Probably, a setting was broken somehow.

Anyway, it seems your issue has been solved. That is good in any case.
But feel free to let me know if you have the same (or another) issue again in the future.
