### ISSUE TITLE
Key binding "Cmd+Ctrl+Forward Delete" becomes "Cmd+Ctrl+Backspace"

### ISSUE THREAD

**Issue by andylima** [coteditor/CotEditor#1552]
### Description

I've set up this key binding — "Cmd+Ctrl+Forward Delete" for Delete Line command:

<img width="648" alt="Screenshot 2023-11-22 at 14 30 35" src="https://github.com/coteditor/CotEditor/assets/8843505/98504b64-dd3f-4493-9849-0de06bb6570f">

### To Reproduce

1. Define the key binding as per the attached screenshot.
2. Try to use it in the text editor — Doesn't work!
3. ..."Cmd+Ctrl+Backspace" is working instead.

### Expected behavior

Key binding "Cmd+Ctrl+Forward Delete" should work.

### CotEditor version

CotEditor: 4.6.5 (601)

### macOS version

macOS Version 14.1.1 (Build 23B81)

### Additional context

Language: English

**Comment by 1024jp** [comment]
Thank you for the report!
I confirmed and fixed the issue.
The change will be shipped in CotEditor 4.7.0, which will be released this December.
