### ISSUE TITLE
Quick Action bar doesn't show correct keyboard shortcut for “find previous”

### ISSUE THREAD

**Issue by rben01** [coteditor/CotEditor#1557]
### Description

The default keyboard shortcut for the “find previous” command is ⌘⇧G. However, in the Quick Action bar, it is listed as ⌘G, the same as “find next”
<img width="491" alt="3E2B2461-4244-40BC-86BF-680BDFAB49C4" src="https://github.com/coteditor/CotEditor/assets/766670/4cf9e2e4-8149-4ced-be0e-bd22b26da874">

### To Reproduce

1. ⌘K to show action bar
2. Type “find”
3. See incorrect shortcut shown for “find previous”

### Expected behavior

Should show ⌘⇧G

### CotEditor version

Version 4.7.0 (621)

### macOS version

14.1.2 (23B92)

**Comment by 1024jp** [comment]
Thank you for the report!
This will be fixed in the next version.
