### ISSUE TITLE
Search Window automatically pastes Selected Text

### ISSUE THREAD

**Issue by Kalopsia-dev** [coteditor/CotEditor#1558]
**Is your feature request related to a problem? Please describe.**
I often find myself opening the search window, then closing it again just to copy my currently selected text, open the search window again and paste it. It'd be a big quality of life improvement if this was done automatically.

**Describe the solution you'd like**
I'd like the currently selected text to automatically be pasted into the search text box when opening the search window (via cmd+F). Other code editors like VS Code or Notepad++ (on Windows) also do this and it really helps speed things up.

**Comment by 1024jp** [comment]
Hmmm. That's not the manner in macOS. So, CotEditor won't adopt it. Sorry.

FYI, you can use the "Use Selection for Find" command (Command+E) to use the selection for search text even among applications (if another application implements it correctly).

<img width="440" alt="Screenshot 2023-12-10 at 17 07 51" src="https://github.com/coteditor/CotEditor/assets/1165044/6b3f8eac-9bad-4acb-b705-8c78c39d2b29">

**Comment by Kalopsia-dev** [comment]
Thanks, I didn't know the cmd+E shortcut existed. This actually solved the issue for me, as I was able to use Karabiner-Elements to map cmd+F to a cmd+F -> cmd+E sequence while CotEditor is in the foreground.

Here's the corresponding json snippet, if anyone needs it:
```json
{
    "description": "CotEditor: Search window automatically pastes selection",
    "manipulators": [
        {
            "conditions": [
                {
                    "bundle_identifiers": [
                        "com.coteditor.CotEditor"
                    ],
                    "type": "frontmost_application_if"
                }
            ],
            "from": {
                "key_code": "f",
                "modifiers": {
                    "mandatory": [
                        "command"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "f",
                    "modifiers": [
                        "left_command"
                    ]
                },
                {
                    "key_code": "e",
                    "modifiers": [
                        "left_command"
                    ]
                }
            ],
            "type": "basic"
        }
    ]
}
```

**Comment by ADTC** [comment]
This is one of the things I really miss from non-Mac text editors. TextMate dev also refused to do this. At least there could be an option in Settings, say to "Automatically Use Selection For Find" so when I press Cmd-F it does both Cmd-E and Cmd-F to copy the text while opening Find.
