### ISSUE TITLE
クイックアクション機能でスクリプトが作動しない

### ISSUE THREAD

**Issue by pneumoniae** [coteditor/CotEditor#1559]
### Description

クイックアクション機能でスクリプトフォルダに入れたスクリプトが作動しない。

### To Reproduce

1. Command + Kでコマンドバーを表示させる。
2. 当該スクリプトを選択する。
3. Returnキーを押してアクションを実行する。

### Expected behavior

スクリプトが作動する。

### CotEditor version

4.7.0 (621)

### macOS version

macOS バージョン14.1.2（ビルド23B92）

**Comment by 1024jp** [comment]
レポートありがとうございます。
今週リリースするCotEditor 4.7.1で修正します。

**Comment by pneumoniae** [comment]
よろしくお願いします。
