### ISSUE TITLE
CotEditor 4.7.0 stopped updating a file that changes on disk

### ISSUE THREAD

**Issue by andylima** [coteditor/CotEditor#1560]
### Description

CotEditor used to reload a file when it was changed on disk — and it had no unsaved edit changes. As of this new version (4.7.0), this is no longer the behavior.

CotEditor doesn't update a file anymore.

The current behavior is much worse. Can you please revert to the previous behavior? Thank you so much.

### To Reproduce

It happens when the underlying file on disk is changed. The file in the editor is not updated, even though it wasn't edited by the user.

### CotEditor version

4.7.0

### macOS version

14.1.2 (23B92)

**Comment by 1024jp** [comment]
Thank you for the report.
This must be a regression on CotEditor 4.7.0 when I removed a workaround for an issue on macOS 12 that isn't supported anymore.
I'll fix it in CotEditor 4.7.1, which will be released whithin this week.
