### ISSUE TITLE
macOS 12 support?

### ISSUE THREAD

**Issue by gingerbeardman** [coteditor/CotEditor#1561]
**Is your feature request related to a problem? Please describe.**
Since 4.6.0 minimum macOS is 13.

**Describe the solution you'd like**
I'm still using macOS 12.

**Describe alternatives you've considered**
I'll keep using the old version.

**Additional context**
Forgive me if you are using features of macOS 13. I'm unaware.

**Comment by 1024jp** [comment]
The CotEditor project has a policy to support only the latest two versions of the system to focus on implementing new features in the latest systems. This policy also has an advantage for users who use an old version. That is, they can use a stable version of CotEditor for the system they use. When an application supports a wide range of system versions, it increases the risk of mingling issues only on old systems.

As you mentioned, you can use old versions provided in [our web site](http://coteditor.com/archives).

**Comment by gingerbeardman** [comment]
Thanks, what new features are you using?

**Comment by 1024jp** [comment]
> Thanks, what new features are you using?

Most are small APIs not worth enumerating and they differ every year.
