### ISSUE TITLE
ウィンドウの幅を狭めるとファイル名とツールバーのツールが隠れてしまいます

### ISSUE THREAD

**Issue by wanik** [coteditor/CotEditor#1566]
### Description

ウィンドウの幅を狭めると、ファイル名が隠れるとともに、ツールバー上のツールも隠れてツールが使えなくなります。

### To Reproduce

ウィンドウの幅を狭めていくと、
- ファイル名が隠れて見えなくなります。
- ツールバー上のツールも隠れていきますが、隠れてしまったツールをクリックすることができなくなるため、ツールが使えなくなります。

動画を添付いたします。
ご参考まで、別のワープロ・アプリ（Nisus Writer Pro）の挙動も収録いたしてあります。

https://github.com/coteditor/CotEditor/assets/34469683/0cf92d9c-2769-45fe-8646-a7802814e959

### Expected behavior

ウィンドウの幅を狭めても、ファイル名が隠れず、また、ツールバー上のツールも使えることが望ましく思われます。

### CotEditor version

CotEditor: 4.7.1 (623)

### macOS version

System: macOS バージョン13.3.1（ビルド22E261）

**Comment by 1024jp** [comment]
macOS 13で試しましたが再現しませんでした。
macOS 13の現行最新バージョンは13.6.2なので、OSをアップデートしてから同様のことが起こるか試してみてください。

いずれにせよ、ここの箇所はあまりCotEditorの関与するところではないので、システム側のバグを疑います。

https://github.com/coteditor/CotEditor/assets/1165044/85feb9a9-0f91-42ee-a400-ee57ffa3f736

**Comment by wanik** [comment]
ありがとうございます。
OSを Ventura 13.6.3 にアップデートしてみましたが、状況はそのままで、改善されませんでした。
（他に何か気がつきましたら、またお知らせいたしますので、引き続きよろしくお願いいたします。）

- CotEditor: 4.7.1 (623)
- System: macOS バージョン13.6.3（ビルド22G436）
- Language: Japanese


https://github.com/coteditor/CotEditor/assets/34469683/8b0e7edb-5a21-4148-8875-b47804c69a80

**Comment by 1024jp** [comment]
OSアップデート後の検証ありがとうございます。変わらなかったですか。私の手元で再現できないので、理由特定が難しいですね。何か条件見つけたらまた教えていただけると幸いです。
（ツールバーの設定をいったんデフォルトに戻したらどうなるかには興味があります）

**Comment by wanik** [comment]
ありがとうございます。
ツールバーの設定をいったんデフォルトに戻したら、治りました！！

↓以下の動画は、ツールバーをデフォルトに戻したあと、適当に項目を追加してみたものです。

https://github.com/coteditor/CotEditor/assets/34469683/949e95a3-46d0-4e78-b13b-8bc45b49bfd0

- CotEditor: 4.7.2 (625)
- System: macOS バージョン13.6.3（ビルド22G436）
- Language: Japanese

**Comment by 1024jp** [comment]
解決したようでよかったです！
昨年リリースしたCotEditor 4.6.0で一度ツールバー設定を刷新してユーザ設定をリセットしてるのですが、もしかしたらその時にリセットがうまく行かず（β使っていた場合は切り替えがうまく行かないケースがあったかも…）、以前の動かないツールバー項目が紛れていたのかもしれません。

今から手を入れる類のものではなく、一般的には起こらない事象のはずのため、本件はこのままクローズしますね。

**Comment by wanik** [comment]
どうもありがとうございます。
ツールバーをリセットすることは思いつきませんでしたが、
治って助かりました。
