### ISSUE TITLE
Reset Settings Button

### ISSUE THREAD

**Issue by herry23xet** [coteditor/CotEditor#1570]
Could you add a button in the settings that resets all changed settings? So that, if you want to experiment, you can reset them again without any effort.
If you then press the reset button, the settings are then restored as with a fresh installation.

**Comment by 1024jp** [comment]
Due to the same reason that I mentioned in https://github.com/coteditor/CotEditor/issues/1571#issuecomment-1888395949, I will not add a button to reset all settings at once.
