### ISSUE TITLE
Clean Uninstallation

### ISSUE THREAD

**Issue by herry23xet** [coteditor/CotEditor#1571]
It would be nice if it's shown where all the files and folders of this app are located so that it can be uninstalled without leaving any residue.
Unfortunately, I couldn't find anything like that described. Even a „simple“ uninstall from apps from the app store leaves files and folders behind.
I don't want to uninstall the app, but I think it's useful just in case.
Could you please add this?

**Comment by 1024jp** [comment]
CotEditor behaves well in the macOS universe. So, you can remove all settings data if you follow the standard way for other macOS apps.
Namely, removing the directory `~/Library/Containers/com.coteditor.CotEditor/
~/Library/Application Scripts/com.coteditor.CotEditor/` as @Haprus suggested (thank you!).

> Could you please add this?

No. Implementing a command to uninstall the app itself in macOS apps is not normal. See apps by Apple or other proper ones, they do not have such a command.

You can find the guidance about uninstalling CotEditor in the CotEditor User Guide.
<img width="672" alt="Screenshot 2024-01-12 at 12 51 41" src="https://github.com/coteditor/CotEditor/assets/1165044/1bfd09b7-ff6e-4a4e-a539-44c8f36fcfc8">

**Comment by herry23xet** [comment]
@1024jp Thanks, I didn't know there was a "CotEditor User Guide" that also shows the folders you need to delete to uninstall. Nonetheless, I would welcome a button that resets the settings and also deletes any themes you have added.
