### ISSUE TITLE
two outline issues

### ISSUE THREAD

**Issue by mer60** [coteditor/CotEditor#1574]
### Description

As you can see the Outline Menu shown in the Navigation Bar shows all items; the Outline inspector shows nothing ...

<img width="743" alt="Bildschirmfoto 2024-01-15 um 16 35 36" src="https://github.com/coteditor/CotEditor/assets/39723252/822475dc-d080-428b-a7dd-3a92cd03f765">

also the style definition underline (namespace) is not recognized

<img width="681" alt="Bildschirmfoto 2024-01-15 um 16 36 52" src="https://github.com/coteditor/CotEditor/assets/39723252/6fa1fb92-7d21-4fd5-8f25-2332f6acf08a">

extract from python.yml

<img width="385" alt="Bildschirmfoto 2024-01-15 um 16 38 10" src="https://github.com/coteditor/CotEditor/assets/39723252/4a23bcb3-2eff-4fd0-b44a-ae0c823becdf">

### Expected behavior

show all items in the Outline inspector

recognize all style definitions

### CotEditor version

4.7.2 (625)

### macOS version

13.6.3

**Comment by 1024jp** [comment]
Thank you for the report.
The first issue was confirmed and fixed.
The change will be shipped with CotEditor 4.7.3.

> also the style definition underline (namespace) is not recognized

The third outline definition for the namespace is not defined in the bundled version of Python syntax.
Therefore, CotEditor has nothing to do.
