### ISSUE TITLE
CotEditor non-AppStore version 4.7.3 (627) no longer has "Check for Updates..."

### ISSUE THREAD

**Issue by DAnn2012** [coteditor/CotEditor#1578]
### Description

Hello @1024jp 

CotEditor non-AppStore version 4.7.3 (627) no longer has "Check for Updates..." in the "CotEditor" menu

### To Reproduce

![coteditor-menu](https://github.com/coteditor/CotEditor/assets/1197819/56aab749-38fa-4f5c-ac92-29abcefe25b5)

### Expected behavior

"Check for Updates..." in the "CotEditor" menu

### CotEditor version

4.7.3 (627)

### macOS version

13.6.3 (22G436) Italian

**Comment by 1024jp** [comment]
OMG! Thank you for notifying me...
I mistakenly put the build for the App Store that did not include the Sparkle framework, which manages the version update for non-AppStore versions.
I've just quickly updated the binary to 4.7.3 (628), the same semantic version but an incremented build number with Sparkle.
Sorry, but please download and replace the current version (627) with it manually.

- [CotEditor 4.7.3 -Releases](https://github.com/coteditor/CotEditor/releases/tag/4.7.3)

**Comment by 1024jp** [comment]
### For the users who updated to non-AppStore version of CotEditor 4.7.3 (627)

The CotEditor 4.7.3 (627) distributed outside of the App Store did mistakenly not include the framework for updates. This build version **cannot notify future new versions and update to them**. The currently distributed CotEditor 4.7.3 (628) has already been replaced with the new build, 628, which can be updated to future versions without problems.

If you have already updated to CotEditor 4.7.3 (627), Please *manually* download CotEditor 4.7.3 (628) again from the page below and replace the 627 with it.

- [CotEditor 4.7.3 -Releases](https://github.com/coteditor/CotEditor/releases/tag/4.7.3)

You can check the build version from the menu CotEditor > About CotEditor. CotEditor 4.7.3 (627) was released from 2024-01-21 10:11 JST to 2024-01-21 22:23.

<img width="396" alt="Screenshot 2024-01-21 at 22 57 52" src="https://github.com/coteditor/CotEditor/assets/1165044/a881a353-d1e6-4259-8ae1-c1bda21f92ce">
