### ISSUE TITLE
The strings in the Snippets panel of the Settings are not translated

### ISSUE THREAD

**Issue by DAnn2012** [coteditor/CotEditor#1579]
### Description

Hello @1024jp 

The strings in the Snippets panel of the Settings are not translated (excluding the string "Select a snippet to edit.")

### To Reproduce

![snippet-settings](https://github.com/coteditor/CotEditor/assets/1197819/231e1dad-e4af-4e90-b902-06e7a0248aae)

![snippet-settings-2](https://github.com/coteditor/CotEditor/assets/1197819/46e4568d-20e8-49c8-a7d2-350462ffe898)

### Expected behavior

All the strings in the Snippets panel of the Settings are translated

### CotEditor version

4.7.3 (627)

### macOS version

13.6.3 (22G436) Italian

**Comment by 1024jp** [comment]
@DAnn2012 Thank you! I've just fixed it.
The change will be applied to the next version, CotEditor 4.7.4.
