### ISSUE TITLE
タブ幅のカスタム設定で上下の向きのボタンが最初の1回しか効かない

### ISSUE THREAD

**Issue by wanik** [coteditor/CotEditor#1581]
### Description

タブ幅のカスタム設定で数値を変更しようとする際、
上下の向きのボタンが最初の1回しか効きません。

### To Reproduce

ツールバーから　「タブスタイル ＞ カスタム」　を選ぶか、あるいは
メニューから　「フォーマット ＞ タブ幅 ＞ カスタム」　を選び、
数値入力欄の右側にある上下の向きのボタンを押します。

最初に1回は、数値が変りますが、
それ以降は、ボタンを押しても変化がなく、無効となっています。

https://github.com/coteditor/CotEditor/assets/34469683/cd1b5718-3c29-4afd-a3c4-0c91e27f7ae6

### Expected behavior

タブ幅のカスタム設定で、上下の向きのボタンが正しく機能することが望まれます。

### CotEditor version

CotEditor: 4.7.3 (627)

### macOS version

System: macOS バージョン13.6.3（ビルド22G436）

**Comment by 1024jp** [comment]
レポートありがとうございます。
本件macOS 13系でのみ発生する不具合のようです。
迂回コードを追加したので、次バージョン以降は上下ボタンも正しく動作するようになるはずです。

**Comment by wanik** [comment]
さっそく、どうもありがとうございます。
Ventura のみで発生とのこと、macOS もやっかいなところがありますね。
