### ISSUE TITLE
Tab-cycling in Find & Replace dialog window

### ISSUE THREAD

**Issue by sindlarv** [coteditor/CotEditor#1584]
### Description

Tab-cycling in Find & Replace dialog window doesn't work as expected. When this window gets opened, it's not possible to change from the text field which is activated by default (=Find) to the next one (=Replace) with Tab key.
When I try Shift-Tab, it allows me to activate all the dialog elements backwards, i.e. buttons Replace, Replace All, ... till Regular Expression switch. And then it stops, i.e. Replace text field can't be navigated not even in reverse order.

### To Reproduce

1. Use keyboard shortcut Command-F open Find & Replace window
2. Type in a text into Find text field
3. Hit "Tab" key to activate the next text field, to be able to type in text to replace with -> it's doesn't work.

### Expected behavior

Users should be able to select individual UI elements just by using keyboard.

### CotEditor version

4.7.3

### macOS version

Ventura 13.6.3 (MacBook Air M1)

**Comment by sindlarv** [comment]
I'm not sure what has changed but as of this time (with CotEditor 4.8.2, MacOS 13.6.6), I can only confirm that I'm not able to reproduce the problem anymore. It makes me happy, thanks :)

**Comment by 1024jp** [comment]
Thank you for the reply.
As at least the current version seems to have no problems, I close this issue.
Feel free to report if it occurs again.
