### ISSUE TITLE
Jump to search result is not works

### ISSUE THREAD

**Issue by ANNotunzdY** [coteditor/CotEditor#1586]
## Environment (環境)

- CotEditor: 4.7.3 (627)
- System: macOS バージョン13.6.3（ビルド22G436）
- Language: Japanese

## Short Description (簡単な説明)

「検索と置換」ウィンドウの「すべてを検索」の結果の行を選択してもジャンプしなくなった

## Steps to Reproduce the Issue (不具合が発生したときに行っていた操作、または再現手順)

・「検索と置換」ウィンドウにて「すべてを検索」を実施する
・任意の行を選択する

## Expected Result (期待される挙動)

・選択した行にジャンプする

### To Reproduce

1. Keystroke Cmd + F
2. Click on 'すべてを検索'
3. Click any line
4. Not works

### CotEditor version

4.7.3 (627)

### macOS version

macOS バージョン13.6.3（ビルド22G436）

**Comment by 1024jp** [comment]
手元の環境で再現ができなかったのですが、100％発生する事象でしょうか？ また特定の条件はありますか？

**Comment by 1024jp** [comment]
返信がないのでクローズします。
また何か情報がありましたら追記ください。
