### ISSUE TITLE
More readable auto-naming for unsaved tabs

### ISSUE THREAD

**Issue by fffedor** [coteditor/CotEditor#1587]
Hi.

Thanks for the great editor. I would like to suggest a feature for more readable names for new tabs. 

It was previously [suggested](https://github.com/coteditor/CotEditor/issues/1436) here to make it possible to edit new tab names and the feature was cancelled due to non-standard behaviour. 

I would like to propose to do similar to Sublime Text editor, where the **name of a new unsaved tab is taken from the first line of content** (see screenshot). I think it would make it easier to recognise new tabs and more convenient. What do you think?

<img width="485" alt="Screenshot 2024-01-27 at 18 49 46" src="https://github.com/coteditor/CotEditor/assets/103065156/5ea5c7fe-2218-4d8a-9df3-32dffc3656fc">

**Comment by 1024jp** [comment]
Hi, thank you for the request.

Last months, I have been pondering over your request and have come to the conclusion that we should still not adopt it.
I know some apps (incl. Notes.app) have this feature, but I suppose it is too much for a general-purpose plain text editor that aims for simple operations like Coteditor.

Furthermore, renaming a file means moving the file on the system (even when they are **unsaved** documents).
Given the stability of the application, we should be cautious about reading and writing files.
Sorry.
