### ISSUE TITLE
ctrl + shift + downKey also selects wrapped lines

### ISSUE THREAD

**Issue by sa3hin** [coteditor/CotEditor#1588]
### Description

ctrl + shift + downKey also selects wrapped lines

### To Reproduce

https://github.com/coteditor/CotEditor/assets/141723556/169ce2e8-e36e-4088-a954-945e6de0a962

### Expected behavior

ctrl + Shift + downKey should not select wrapped lines

### CotEditor version

4.7.3 (627)

### macOS version

macOS Sonoma 14.2.1

**Comment by 1024jp** [comment]
I'd say this behavior is by design, currently. But I understand what you mean.
Cursor location calculation is extremely complex. Let me have time.

**Comment by sa3hin** [comment]
okay thank you

**Comment by sa3hin** [comment]
ok thank you

**Comment by gingerbeardman** [comment]
This is similar or related to #1585

**Comment by 1024jp** [comment]
I've updated the behavior of Control-Shift-↑/↓ in the next version, CotEditor 5.0.6.

**Comment by hackersthan** [comment]
I will check and let you know.

**Comment by gingerbeardman** [comment]
Works for me.

**Comment by hackersthan** [comment]
Hi @1024jp 

Works fine. Thanks for the your amazing work. <3 CotEditor

**Comment by 1024jp** [comment]
@gingerbeardman , @hackersthan Thank you for the confirmation!
