### ISSUE TITLE
It would be great to support block editing.

### ISSUE THREAD

**Issue by Ayicen** [coteditor/CotEditor#1591]
Whenever you insert the same content in multiple lines, you always need to operate line by line. If it can support block editing, it can improve the efficiency. It's also possible that I'm not utilizing CotEditor's features correctly.

**Comment by 1024jp** [comment]
CotEditor already has the block editing feature.
You can find the details in the bundled user guides.
Open it from Help > CotEditor Help in the app menu and then move to:
Table of Contents > Edit Text > Edit multiple points

<img width="869" alt="Screenshot 2024-02-05 at 13 57 05" src="https://github.com/coteditor/CotEditor/assets/1165044/4cc2148d-9ab8-4b17-8cd3-340692b22d10">
