### ISSUE TITLE
Extreme RAM consumption (more then 8 GB)

### ISSUE THREAD

**Issue by guthipp** [coteditor/CotEditor#1592]
### Description

Hello Team CotEditor,

my MacBook Pro M1 has 16 GB RAM and CotEditor needs more then 8 GB RAM. But why? I can't believe, that this is intentional. It makes my MacBook noticeably slower.

It's not just since yesterday. I really hope, you can fix this bug.

PS: I have to say, I have round about 30 Tabs .txts open. But not books... the most .txts have just a few lines and no one is longer than 10000 characters pure text maximal.

Thanks in Advance.

### To Reproduce

Its not immediately.. its when the CotEditor is open a few weeks... it getting more and more. And: I have to say, I have round about 30 Tabs .txts open. But not books... the most .txts have just a few lines and no one is longer than 10000 characters pure text maximal.

### Expected behavior

RAM use not higher than 1 GB ... I mean... its just text!!

### CotEditor version

4.7.3

### macOS version

14.3 (23D56)

**Comment by 1024jp** [comment]
I will close this issue since there seem to be no reports of issues with the latest versions.
If you face a similar issue with a future version, please make a new one.

**Comment by guthipp** [comment]
Its not solved - I still have the RAM problem at 4.8.4.

<img width="854" alt="Bildschirmfoto 2024-06-01 um 20 32 12" src="https://github.com/coteditor/CotEditor/assets/69152563/bb931102-0600-4d0c-9d0c-b28898dd3da0">
