### ISSUE TITLE
Make `Prefer font using` configurable by syntax

### ISSUE THREAD

**Issue by toobuntu** [coteditor/CotEditor#1593]
**Is your feature request related to a problem? Please describe.**
Markdown is basically code and I think it is more readable in `Monospaced` while editing. Coteditor does not provide a Markdown preview function, where `Standard` would be preferred. I have the font preference set to `Automatically`.

Can this be configured by the user per-syntax or is there any consensus for changing the default for Markdown specifically?

**Describe the solution you'd like**
Make `Prefer font using` configurable by syntax.

**Describe alternatives you've considered**
Alternatively, change the default for Markdown to `Monospaced`.

**Additional context**
It's currently possible to change the font type per-file from the Format menu, but this is required for every file and is not automatic.

**Comment by 1024jp** [comment]
This feature request will be implemented in CotEditor 4.8.0, which is planned to be released in this April.

**Comment by 1024jp** [comment]
The implementation is done.
