### ISSUE TITLE
Is it on the roadmap to add jq as a language?

### ISSUE THREAD

**Issue by podfeet** [coteditor/CotEditor#1595]
I'm starting to use jq to query json files quite a bit and as CotEditor is my editor of choice, I'd love it if I could get syntax highlighting for jq.

Thanks for any consideration!

**Comment by 1024jp** [comment]
Currently not.
CotEditor currently has a policy of including only syntax for well-known enough language and is cautious about adding new ones.

However, I feel [./jq](https://jqlang.github.io/jq/) is now quite popular.
I can't say I would adopt it right away, but I feel it would be a shame to reject it so soon.
Let me see how it goes for a while longer. I keep this open.

**Comment by podfeet** [comment]
thanks for the consideration!

**Comment by 1024jp** [comment]
The syntax for jq will be added to the next version, CotEditor 4.8.5.

**Comment by podfeet** [comment]
Excellent!Allison SheridanNosillaCast Apple Podcasthttps://podfeet.comOn May 27, 2024, at 2:42 AM, 1024jp ***@***.***> wrote:﻿
The syntax for jq will be added to the next version, CotEditor 4.8.5.
