### ISSUE TITLE
Syntax for Duckyscript

### ISSUE THREAD

**Issue by Laconeno** [coteditor/CotEditor#1598]
Would be nice to have a syntax for Duckyscript, any change this gets on the roadmap?

**Comment by 1024jp** [comment]
We don't have a plan for it.
CotEditor currently will add new syntaxes to bundle only for enough major ones.
I recommend making it in the community and sharing it somewhere separately.

cf. [Adding a new bundled syntax -CONTRIBUTING.md](https://github.com/coteditor/CotEditor/blob/main/CONTRIBUTING.md#adding-a-new-bundled-syntax)
