### ISSUE TITLE
スクリプト実行後の選択範囲 / Selection after executing script

### ISSUE THREAD

**Issue by usami-k** [coteditor/CotEditor#16]
（http://sourceforge.jp/ticket/browse.php?group_id=1836&tid=24184 から移動）

スクリプトメニューから実行する UNIX スクリプトの実行結果で、実行後の挿入キャレットの位置（あるいは選択範囲）を操作できないでしょうか。AppleScript を使うという手も勿論あるのですが、まどろっこしいというか...。
UNIX スクリプトの結果（つまり標準出力）に含まれる特定のキーワードで選択範囲を決めるなど。スクリプト結果のイメージでは下記のようになりますが、伝わりますでしょうか？

【例１：HTML の title タグを出力するスクリプト（の結果標準出力）】
<title>%%%{CotEditorSetSelectionStart}%%%ページのタイトルを書きます%%%{CotEditorSetSelectionEnd}%%%</title>

**Comment by 1024jp** [comment]
CotEditor 4.5.0で実装されたスニペットの`<<<SELECTION>>>`である程度欲している機能は実現されたと考え、このチケットはクローズします。
