### ISSUE TITLE
High Memory usage (> 700MB) with (7 non-code text-only files open) on CotEditor: 4.7.4 (630)

### ISSUE THREAD

**Issue by ybugroup** [coteditor/CotEditor#1600]
### Description

On startup, CotEditor: 4.7.4 (630) takes over 600MB of memory (according to Activity Monitor) rising to 798MB after some light usage.
I have 7 tabs open to simple text documents, but have not navigated to any of the tabs other than the single tab open by default.  
I have NO development file, e.g. no CSS, no code, no JSON files.
Could the high memory usage be caused by the syntax highlighting functionality?  If yes, can I turn this functionality off?
I have only 8GB of RAM on my MacBook Air M2 15 inch, and I was surprised that CotEditor was the highest memory process in Activity Monitor.

### To Reproduce

Run CotEditor with 7 tabs, open Activity Monitor, sort by Memory

### Expected behavior

Lower memory usage than browsers, e.g. under 400MB, ideally lower.

### CotEditor version

CotEditor: 4.7.4 (630)

### macOS version

macOS Version 14.4 (Build 23E214)

### Additional context

MacBook Air M2 15 inch, 8GB RAM, 512GB SSD
Language: English

**Comment by ybugroup** [comment]
Thank you for looking into the memory issues.  I reinstalled CotEditor and it now uses approx 400mb of memory which is better. Since, I only need a plain text editor with tabs with low memory usage, I have moved TextMate (which has not been updated in a while) but uses less than 100mb of memory.I will switch back to CotEditor if/when syntax highlighting can be disabled and memory usage reduced further.

BTW, the reason I am so focused on RAM is because I have a Macbook M2 with 8GB RAM.  I am sure there are many Mac users with low memory configuration that would love for a native plain text editor like CotEditor without syntax highlighting.

Thanks,
Michael

**Comment by 1024jp** [comment]
Thank you for the reply and for the effort to reinstall and check it.
It is good news that memory usage has decreased, but I understand that 400 MB is still a lot.

I'm still on the fence about adding an option to disable syntax highlighting, so I can't do it right away, but I will consider the need.
Thanks.
