### ISSUE TITLE
Syntax editor window resizing

### ISSUE THREAD

**Issue by little-flag** [coteditor/CotEditor#1601]
I am really enjoying 4.8.0-beta, these are fantastic improvements.

Regarding the new syntax editor: it would be nice if the window remembered its dimensions from the last time it was resized. I find it a little bit annoying having to click and drag to resize it each time I open the editor (I find it a bit small and not all regex patterns are visible).  

Huge improvement overall, though.

**Comment by 1024jp** [comment]
Thank you for the feedback to the beta release!
I really like your recommendation to restore window size of the syntax editor.
However, according to my investigation, there is no straightforward API to do that.
I'll research further, but still not sure whether I can or not.
Let me have time.
