### ISSUE TITLE
Formatting preview for Markdown

### ISSUE THREAD

**Issue by TS6ix2GaH3q679h5** [coteditor/CotEditor#1603]
**Is your feature request related to a problem? Please describe.**
When writing a markdown file, I need some way to preview/view the formatted text, so that I can copy it and paste it into a word processor with all markdown-generated formatting intact. In other words, for example, all of the markdown headings (#, ##, ###) should appear, and be copy-able, so that I can paste into word processor and it will appear with headings, bold, etc. 

For example, TextMate has this feature in a pop-up window:

<img width="991" alt="image" src="https://github.com/coteditor/CotEditor/assets/74590442/a8948469-fc7c-46f0-a09b-f38587f506cc">

**Describe the solution you'd like**
An option in the menus to view the markdown in a formatted way. Like the image above, where the formatting appears in a pop-up window. Or some sort of toggle switch to toggle between "markdown syntax" and "formatted view". Something that lets me copy the document to clipboard and paste to a word processor with formatting intact. 

**Describe alternatives you've considered**
I'm just using other editors (TextMate for example).

**Additional context**
Screenshot shows basically what I'm hoping for. 
Is this possible in CotEditor already and I just have not noticed it?

**Comment by 1024jp** [comment]
CotEditor is not a markdown editor but a general plain text editor.
Therefore, it is our policy not to add language-specific features.

ref. #722
