### ISSUE TITLE
Is it possible to add shortcut keys for syntax selection?

### ISSUE THREAD

**Issue by geoconst** [coteditor/CotEditor#1604]
Then, I can operate entirely with the keyboard without needing to use the cursor.

**Comment by 1024jp** [comment]
CotEditor doesn't provide a keyboard shortcut customization for syntax change, but you can use the Quick Action feature (⌘K).
Type ⌘K and type a syntax name you want to change in the Quick Action field.
Then you can change the syntax without leaving your hands on the keyboard.
