### ISSUE TITLE
Recent Filters in outline inspector not applying correctly

### ISSUE THREAD

**Issue by dannyow** [coteditor/CotEditor#1606]
### Description

In essence all the phrases from Recent Filters menu of the outline inspector can't be re-used.

Here's a brief screencast for reference:

https://github.com/coteditor/CotEditor/assets/210317/f454eebf-45dd-44b6-9f30-4f188f5f547c

### To Reproduce

1. Launch any document long enough to have a functioning outline inspector.
2. Input any term into the outline search field and hit enter (this will add it to the Recent Filters menu).
3. Clear the search field.
4. From the Recent Filters menu, select the phrase you recently used.
5. Notice that the phrase is appropriately copied into the search field and highlighted, but it's not utilized for filtering.

### Expected behavior

When a user selects a phrase from the Recent Filters, it should not only be displayed in the search field but should also immediately be applied to filter the content in the outline inspector list.

### CotEditor version

4.7.4, 4.8.0-beta.3

### macOS version

13.6.4, 14.4

**Comment by 1024jp** [comment]
Thank you for the report.
I agree the behavior you suggested is more natual.
I've made a change and it will be applied to the next releease.
