### ISSUE TITLE
Line numbers in vertical orientation are too squeezed to be readable in longer documents

### ISSUE THREAD

**Issue by dannyow** [coteditor/CotEditor#1608]
### Description

Drawing every 5th number works well till we hit 100th line, after line numbers are too close to each other to be readable.

It's ok here: 
<img width="142" alt="image" src="https://github.com/coteditor/CotEditor/assets/210317/8f32feb9-823a-4803-8e21-4fc551844ab0">

Here is getting messy:
<img width="124" alt="image" src="https://github.com/coteditor/CotEditor/assets/210317/9901519e-0165-46dd-92e7-346326293ae5">

**Possible solutions:**

1. use smaller font size for numbers between the 5th markers - sufficient till 1000th line I guess 
2. display only the last two digits of the line number: e.g., 100, ·01, ·02, ·03, ·04, 105

### To Reproduce

Open document with vertical orientation...

### CotEditor version

4.7.4, 4.8.0-beta.3

### macOS version

13.6.4, 14.4

**Comment by dannyow** [comment]
I made a quick and dirty prototype, with using only last two digits and shifting the baseline - just to see how it looks.

Results:

* for 3-digits
<img width="122" alt="image" src="https://github.com/coteditor/CotEditor/assets/210317/88d946d1-f777-401b-9001-c8b1011ac011">

* for 4-digits
<img width="137" alt="image" src="https://github.com/coteditor/CotEditor/assets/210317/db8676b5-1d9d-43d9-b048-80fe96719444">

Not perfect, but usable. 

@1024jp WDYT?

**Comment by 1024jp** [comment]
Actually, this part has been on my mind for a long time, but I've been putting it off.
Thank you for the feedback.
After your post, I reviewed again the code around the line number view and feel I also should refactor there a bit.
I'll make it somehow better in the next version.

Your idea to display only the last digits is interesting (maybe the last one digit is enough, though).
I'll also consider whether there is a better way. Let me think.

**Comment by 1024jp** [comment]
Still not perfect, but I suppose now it becomes better.

https://github.com/coteditor/CotEditor/assets/1165044/a1d2fea5-33dc-47c5-a059-b0185bd75949

**Comment by dannyow** [comment]
Looks good enough :) I mean there is still the edge case when you pointing out the line number next to the one already visible (eg. 5654) 
<img width="102" alt="image" src="https://github.com/coteditor/CotEditor/assets/210317/ac2e68ab-304c-4c88-a884-62beb350b632">
