### ISSUE TITLE
Recognize GNUmakefile as Makefile

### ISSUE THREAD

**Issue by marrus-sh** [coteditor/CotEditor#1609]
**Is your feature request related to a problem? Please describe.**
CotEditor does not recognize files named `GNUmakefile` as makefiles by default. Although `Makefile` is the more common name, authors might use the name `GNUmakefile` when the makefile requires specifically the GNU version of Make; see [What Name to Give Your Makefile](https://www.gnu.org/software/make/manual/html_node/Makefile-Names.html) in the GNU Make manual.

**Describe the solution you'd like**
`GNUmakefile`, `Makefile`, and `makefile` are all automatically recognized as being Makefile syntax.

**Describe alternatives you've considered**
It is possible to manually add this filename, but it would be best if it was recognized by default.

**Comment by 1024jp** [comment]
Thank you for the suggestion. I'll add them to the next version.
