### ISSUE TITLE
Probably a bug with document icons

### ISSUE THREAD

**Issue by jsx97** [coteditor/CotEditor#1612]
### Description

I don't know why, but if I have CotEditor installed, and I have set "Open with = TextEdit or Xcode > Change All" for Lua files, Lua files still have CotEditor-styled icon. I have tried to clear Finder icon cache using a script and to rebuild launch services database using OnyX, but still cannot get rid of it. Wrong icons bother me a lot.

<img width="393" alt="image" src="https://github.com/coteditor/CotEditor/assets/129062294/3f606d4b-3dc8-4d39-9227-1673a3b99bfa">

### To Reproduce

see above

### CotEditor version

4.7.4 (630)

### macOS version

14.4.1

**Comment by 1024jp** [comment]
Sorry for my late reply. I've also read [your post on Ask Different](https://apple.stackexchange.com/questions/471697/to-understand-how-finder-uses-icons).

CotEditor actually does not do any special things to prioritize the document file icons.
We just define the document types to handle in CotEditor and specify the document icon images for them in the Info.plist file, which is the definition file for general application settings on Cocoa applications.

https://github.com/coteditor/CotEditor/blob/main/CotEditor/Info.plist

Each app that provides original document icons does the same thing (as people discuss in the Ask Different).
Then, with these as a reference, **the macOS system determines** which icon to display for which file.
I understand that file icon mapping by the system nowadays is sometimes frustrating, but I suppose, CotEditor has nothing to do.

If you have a concrete suggestion at the code level, I am welcome to hear that.
