### ISSUE TITLE
Support for illegal syntax in custom syntax

### ISSUE THREAD

**Issue by chrissy-dev** [coteditor/CotEditor#1613]
I'd like to create a custom syntax for `^x.*$` that puts a line through the full line if the line starts with `x`.  I'm currently doing this with the regex mapped to comments but just wondering if there's a better way?

This is just a personal thing but I have a personal syntax I use for my plain text todo list. 

Feel free to close this issue if there's not a way to do it, I just wanted to ask.

Thanks again for CotEditor.

<img width="679" alt="image" src="https://github.com/coteditor/CotEditor/assets/6320793/d7faca53-ad46-4ca5-b0f9-5044a780a246">

**Comment by 1024jp** [comment]
Highlighting types in the CotEditor's syntax definition is actually just a label and definition of the priority to apply highlights.
So, if you make your custom syntax definition and you are satisfied with the result, I think it is ok.
