### ISSUE TITLE
When a new row is selected, the old selected state does not disappear.

### ISSUE THREAD

**Issue by raisin8010** [coteditor/CotEditor#1616]
### Description

As described in the title. When I select a new row, when the left mouse button is pressed down, the green background of the old selection does not disappear until left mouse button released. This doesn't always happen, as in the video which sometimes behaves normally (old selection disappear immedietly when mouse down). I have not found a definite pattern.

video:
https://github.com/coteditor/CotEditor/assets/55045806/6649e3a2-89c6-446e-8427-1c5f50a8a436

### To Reproduce

1. from right to left, select a row
2. from right to left, select a new row. 

### CotEditor version

all ver

### macOS version

14 all ver

**Comment by 1024jp** [comment]
Thank you for the report.

It appears that the highlighting for the same word (the “Highlight instances of selected text” option) was not updating properly under certain conditions.
I've just fixed the code and the change will be applied to the next version.
