### ISSUE TITLE
アプリケーション終了時の動作について

### ISSUE THREAD

**Issue by shiro-t** [coteditor/CotEditor#1617]
おそらく CotEditor 4.8.0 からかと思われますが、CotEditor のアプリケーション終了時に名称未設定のテキストに関して保存を問うパネルが表示されるようになっております。
これは以前は表示されずそのまま終了され、次回の CotEditor の起動時に 名称未設定のテキストのまま再度開かれたかと思われます。

一時的なメモなどをこの名称未設定のテキストに記載、終わったら保存せず削除という使い方をしておりました。
が、上記の挙動の変化のため、たとえば macOS のアップグレードなどで再起動が行われる際に保存を問われることでそれが中断される状態になっております。

この終了時の挙動について、以前と同じ動作(Option を押して表示される「終了(ほかのウィンドウは保持)」) をデフォルトの挙動にする選択肢をご用意頂けないか、ご検討を頂けると助かります。

なお、現在は、CotEditor の設定より「CotEditor を終了」の項目に対する Command-Q のショートカットを削除、macOS のシステム設定のキーボードのショートカットの設定にて CotEditor に対してアプリのショートカットで「終了(ほかのウィンドウは保持)」」に Command-Q を割り当てる事を行っております。その上で macOS の再起動などの際には先に Command-Q を押して事前に終了をさせて回避策としております。
が、この方法だと事前の終了を忘れることもありまして、やはり CotEditor 側に正規の選択肢があると助かる次第です。

以上、よろしくお願いします。

**Comment by 1024jp** [comment]
> おそらく CotEditor 4.8.0 からかと思われますが、CotEditor のアプリケーション終了時に名称未設定のテキストに関して保存を問うパネルが表示されるようになっております。
> これは以前は表示されずそのまま終了され、次回の CotEditor の起動時に 名称未設定のテキストのまま再度開かれたかと思われます。

こちらについて、CotEditor側では特に変更をしておりません。

CotEditorには「最後のセッションのウインドウを開く」というオプションがあります。
このオプションが有効になっているときは、4.8.0でも前回のセッションの書類が自動的に再度開かれるはずです。

また「オートセーブとバージョンを有効」にしているかも書類保存の振る舞いに大きく影響します。

<img width="712" alt="Screenshot 2024-04-20 at 13 42 56" src="https://github.com/coteditor/CotEditor/assets/1165044/4fb9810a-b25a-4356-b00a-ec3c67dc655a">

まずは状況確認のために設定ウインドウの「一般」のスクリーンショットをいただけると幸いです。

**Comment by shiro-t** [comment]
ご連絡ありがとうございます。確認したところ、「最後のセッションのウインドウを開く」のチェックが外れておりました。
「最後のセッションのウインドウを開く」にチェックをしたところ、期待通りの動作となりました。ありがとうございます。

何故チェックが消えたかは分からないのですが、念のため今後は defaults read com.coteditor.CotEditor の結果をバックアップで残しておくようにしておきます。

また次回もし類似の問い合わせの際には 設定パネルについてスクリーンショットを添付するようにいたします。

**Comment by shiro-t** [comment]
私の問題は解決したのでクローズをいたします。

**Comment by 1024jp** [comment]
解決したようでよかったです。経過報告ありがとうございます。
