### ISSUE TITLE
Custom made format fails since last update 

### ISSUE THREAD

**Issue by xq369** [coteditor/CotEditor#1619]
### Description
My custom made syntax format was no longer automatically recognised since the latest update.
When selected manually, the syntax format was no longer applied.

### To Reproduce
1. Go to (settings / available syntaxes / ... custom made syntax)

### Expected behavior
When looking for root causes, it appeared the new update is extremely unforgiving in the way the format is typed.
A single typo will cause total rejection of the syntax and it will refuse to upload the format file.
Previous versions worked fine.

### CotEditor version
4.8.2

### macOS version
14.4.1

### Additional context
commands/values that contain other characters than abc...ZZ now have to between '' brackets
this was not required in previous versions

**Comment by xq369** [comment]
see settings / available syntaxes / ... custom made syntax

**Comment by xq369** [comment]
[myownsyntax.txt](https://github.com/coteditor/CotEditor/files/15044380/myownsyntax.txt)

it appears something in the old .yml file makes the syntax crash
see attached file (is .yml, had to change to .txt as github does not upload .yml)
it crashes when uploading
i tried to clean to find what it the file makes it crash, comparing it to new files, but can not find 

*** with all previous Coteditor versions this syntax worked fine ***

**Comment by 1024jp** [comment]
Thank you for the report.
Could you please share that problematic syntax definition of yours?

> CotEditor version
> 4.8.2

The latest version of CotEditor is still 4.8.0. Is this a typo?

**Comment by xq369** [comment]
thanks so much for swift response !

￼￼

> On 20 Apr 2024, at 06:50, 1024jp ***@***.***> wrote:
> 
> 
> Thank you for the report.
> Could you please share that problematic syntax definition of yours?
> 
see attached
A original now fails.yml    no longer works, while all previous versions it was ok (i made it with the buildin CotEditor yml editor)
A.yml    is now working - i had to put everything within ' '     - removing the brackets will make it fail (i edited this manually with Cot)

> CotEditor version
> 4.8.2
> 
> The latest version of CotEditor is still 4.8.0. Is this a typo?
> 
oh sorry yes, it is 4.8.0

**Comment by 1024jp** [comment]
@xq369 Thank you for sharing! However, it seems that file attachments are not available for the GitHub Issues thread. Could you send them again to coteditor.github@gmail.com ?

**Comment by xq369** [comment]
￼￼


On 20 Apr 2024, at 12:16, 1024jp ***@***.***> wrote:


@xq369 <https://github.com/xq369> Thank you for sharing! However, it seems that file attachments are not available for the GitHub Issues thread. Could you send them again to ***@***.*** ***@***.***> ?

**Comment by 1024jp** [comment]
Thank you for sharing.
Thanks to this, I was able to pinpoint the cause.
The fix will be shipped with CotEditor 4.8.1 to be released next week.
