### ISSUE TITLE
syntax covering full words, not only 'starting with'

### ISSUE THREAD

**Issue by xq369** [coteditor/CotEditor#1622]
**Is your feature request related to a problem? Please describe.**
the syntax specifications require to define the 'starting with' string for each word
when using short words that get repeated in other words, the syntax of both words gets mixed up

**Describe the solution you'd like**
specify the string for the full word, not "starting with", so words do not get mixed up

**Describe alternatives you've considered**
i've tried "ending with" but it does not bring any change

**Additional context**
in this example there are 2 syntaxes mixed up:
* the word 'dwarfBox', which is light green
* and the word 'x', which is purple

<img width="154" alt="Screenshot 2024-04-20 at 08 57 42" src="https://github.com/coteditor/CotEditor/assets/89194345/7ff8cb51-6a3e-4b06-97b9-ae0c3e6b63d6">

**Comment by 1024jp** [comment]
> when using short words that get repeated in other words, the syntax of both words gets mixed up

CotEditor is not designed so, in general.
Could you share the syntax definition file to help us break down the problem?

In addition, please provide your environments:
- CotEditor's version
- macOS vesion

**Comment by xq369** [comment]
￼ CotEditor 4.8.0  MacOS 14.4.1

On 20 Apr 2024, at 12:30, 1024jp ***@***.***> wrote:


when using short words that get repeated in other words, the syntax of both words gets mixed up

CotEditor is not designed so, in general.
Could you share the syntax definition file to help us break down the problem?

In addition, please provide your environments:

CotEditor's version
macOS vesion

**Comment by 1024jp** [comment]
I tweaked the algorithm parsing such simple words in CotEditor 4.8.1, which was released yesterday.
I suppose now it becomes better but let me know if the issue still exists.

**Comment by xq369** [comment]
you've been working hard !
really appreciated

only see this now, as i've been travelling last weeks
after updating to 3.8.2 and a quick look; it is better but not fully solved
will look into it and come back to you



On 23 Apr 2024, at 11:29, 1024jp ***@***.***> wrote:


I tweaked the algorithm parsing such simple words in CotEditor 4.8.1, which was released yesterday.
I suppose now it becomes better but let me know if the issue still exists.

**Comment by xq369** [comment]
thanks for reflecting so quickly
when looking deeper, things actually got worse


for example this javascript
when using / in a sentence, it takes out a long part of the script
this is selected text, so you can see the original :
￼

this is the result:
￼

on separate lines it works ok :
￼




when using an array that contains /, like this (selected) array:
￼

this is the result:
￼


in the language that uses short commands (which i sent you)
it still combines colors where it should not
so it does not  yet recognise when such combination is used as a single command
￼

as is defined here :
￼


On 23 Apr 2024, at 11:29, 1024jp ***@***.***> wrote:


I tweaked the algorithm parsing such simple words in CotEditor 4.8.1, which was released yesterday.
I suppose now it becomes better but let me know if the issue still exists.

**Comment by xq369** [comment]
can you have a look at the syntax again please,
because even after latest update it keeps misrepresenting even in javascript

this sentence 
￼

becomes like this :
￼


and it is pretty inconvenient


Holywood verpakt Waarheid in een verhaal
Politici, Kranten, TV & Social Media verpakken verhalen in de vorm van Waarheid
Come U Next ! vertelt je de Waarheid

https://comeunext.glitch.me/

**Comment by xq369** [comment]
also html is impacted : 
￼

which should be :
￼



On 17 May 2024, at 05:54, xq369 ***@***.***> wrote:

can you have a look at the syntax again please,
because even after latest update it keeps misrepresenting even in javascript

this sentence 
<Screenshot 2024-05-17 at 05.44.51.png>

becomes like this :
<Screenshot 2024-05-17 at 05.44.32.png>


and it is pretty inconvenient

**Comment by 1024jp** [comment]
Sorry that I couldn't fit the original issue in the last versions.
I'll find a solution further, but now I feel it is hard to fix it with the current implementation of syntax highlighting.
Let me have a time.
