### ISSUE TITLE
Javascript .yml has innterHeight and innterHTML

### ISSUE THREAD

**Issue by 0osh** [coteditor/CotEditor#1623]
### Description

In the Javascript .yml file, it says `innterHeight,` and `innterHTML` (notice the ’t’ after the double ’n’). The code suggestions suggest it aswell. They are on line 212 and 213 in the file if that helps.
If anyone else has this issue and it hasn’t been resolved, go to the app in finder, right click and press `show package contents`. Then go to Contents -> Resources -> Syntax -> JavaScript.yml and change the text on lines 212 and 213. You may have to change some permissions.

### To Reproduce

Type `inn` in a Javascript file

### Expected behavior

It should say `innerHeight` and `innerHTML`.

### CotEditor version

CotEditor: 4.8.0 (642), English

### macOS version

System: macOS Version 14.2 (Build 23C64)

### Additional context

[innter.md](https://github.com/coteditor/CotEditor/files/15050766/innter.md)

**Comment by 1024jp** [comment]
Thank you for the report. The fix will be applied in CotEditor 4.8.2.
