### ISSUE TITLE
Import this format yaml config not working.

### ISSUE THREAD

**Issue by shrimpnine** [coteditor/CotEditor#1625]
### Description

<img width="459" alt="image" src="https://github.com/coteditor/CotEditor/assets/28135683/660cbea9-8763-46f3-973b-a61a53321603">

This yaml config was created by me in previous version, but it has not been available since 4.8.0
https://github.com/shrimpnine/script/blob/main/config/CotEditor_GDScript.yml

I missed something?

### To Reproduce

1. Go to '....'

### Expected behavior

Import as before the version.

### CotEditor version

- CotEditor: 4.8.1 (644)

### macOS version

- System: macOS 版本14.4.1（版号23E224）

**Comment by 1024jp** [comment]
Hi, thank you for the report and for sharing the sample file.
I found the issue and fixed it.
(The cause is your definition file contains an empty dictionary in the interpreter setting.)
The change will be applied to the next CotEditor 4.8.2 so that your syntax file is recognized again.
