### ISSUE TITLE
Open files unexpected slowly

### ISSUE THREAD

**Issue by yuhuangniu** [coteditor/CotEditor#1626]
### Description

When I updated coteditor from 4.7.4 to 4.8.1, opening files with numerous lines is extreme slowly, and everything works fine in old version 4.7.4.

### To Reproduce

You can use this file ( https://github.com/kchen0x/rime-crane/blob/main/liangfen.dict.yaml ) in coteditor(4.8.1) to test:

1. Open coteditor(4.8.1) and drag the above file into coteditor, everything works fine, the file was opened quickly.

2. But close coteditor and directly using coteditor to open the above file with double clicking, this potential bug repeats itself. 

### CotEditor version

4.8.1

### macOS version

macos 13.6.6

**Comment by 1024jp** [comment]
Thank you for the report.
This issue will be solved on the next version, CotEditor 4.8.2.
4.8.2 will be released tomorrow.

If the issue exists still in 4.8.2, please let me know.
