### ISSUE TITLE
General mode is unexpectedly activated for editing shell script file

### ISSUE THREAD

**Issue by gingerbeardman** [coteditor/CotEditor#1629]
### Description

I am editing a shell script and notice that smart quotes is now turning back on every time i open the document.

### To Reproduce

1. open a shell script without shebang
2. type "test", or similar

### Actual behavior

- general mode activated
- quotes are transformed to smart quotes

### Expected behavior

- these options should remain as the user last selected
- Shell script file should not be activating General mode, use Code mode!
- Mode should be active by selected syntax, rather than any other heuristic

### CotEditor version

- 4.8.1 (644)
- 4.8.2 (647)

### macOS version

- 14.4.1 (23E224)

### Additional context

- related to the new "Mode" feature
- found a hint for the solution to turn them off at https://github.com/coteditor/CotEditor/issues/1248
- In latest version it's at: Settings > Mode > General > Smart quotes
- Mode feature is not predictable

**Comment by gingerbeardman** [comment]
It seems my shell script is not recognised as a shell script. Here are its properies

- filename: hash.sh
- shebang: no

**Comment by 1024jp** [comment]
With the default settings, a file with .sh file extension should be mapped to the Shell Script.
When the pop-up menu in the toolbar says it is Shell Script, the document is recognized as a Shell Script document.
Then, (also with the default settings,) the mode for the editor is mapped according to the *syntax kind* defined in the syntax itself, which can be edited from the Format settings pane > Available syntaxes list.
If you have customized the Shell Script, the behavior can be changed. Check it once more.

<img width="792" alt="Screenshot 2024-05-01 at 16 57 32" src="https://github.com/coteditor/CotEditor/assets/1165044/a6e013ed-7d60-45cb-b367-32f05d57a457">
