### ISSUE TITLE
How to disable smart quotes?

### ISSUE THREAD

**Issue by wfwdex** [coteditor/CotEditor#1631]
### Current issue

After I turned off `edit -> substitutions -> smart quotes`, it was still enabled the next time I opened CotEditor.

https://github.com/coteditor/CotEditor/assets/22113416/f58f923a-2420-4ee1-960e-b86655f4a111

### The solution you'd like

I need a switch that turns it off permanently.

### Alternatives you've considered

I've tried turning it off everywhere else but it doesn't work.

<img width="446" alt="Screenshot 2024-05-01 at 16 38 33" src="https://github.com/coteditor/CotEditor/assets/22113416/c75460b6-0d7f-4b7a-b180-0137aab1c148">

<img width="426" alt="Screenshot 2024-05-01 at 16 41 40" src="https://github.com/coteditor/CotEditor/assets/22113416/9b6b85f5-a947-40db-86a0-2e53e3da91e7">

### CotEditor version

4.8.2 (647)

### macOS version

14.4.1

**Comment by 1024jp** [comment]
The smart quotes toggle in the menu bar is just for temporal use for the frontmost editor.

For lasting use, set it in the Mode settings pane.

<img width="712" alt="Screenshot 2024-05-01 at 16 50 34" src="https://github.com/coteditor/CotEditor/assets/1165044/15d3f184-0729-48c8-87a7-57554610e0ec">

**Comment by wfwdex** [comment]
> The smart quotes toggle in the menu bar is just for temporal use for the frontmost editor.
> 
> For lasting use, set it in the Mode settings pane.
> 
> <img alt="Screenshot 2024-05-01 at 16 50 34" width="712" src="https://private-user-images.githubusercontent.com/1165044/327076469-15d3f184-0729-48c8-87a7-57554610e0ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NTEzNDYsIm5iZiI6MTcxNDU1MTA0NiwicGF0aCI6Ii8xMTY1MDQ0LzMyNzA3NjQ2OS0xNWQzZjE4NC0wNzI5LTQ4YzgtODdhNy01NzU1NDYxMGUwZWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDFUMDgxMDQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2FhYWFlNDczMmM5Y2U4MGUzMjU5ZmNhNTBiODJmNDQzMjZmYWViNGIzMjVlZWUwNWUxM2Q2ZDBkYjBhMDFlNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YilI9Ijht8B4epWx0RUNGQfl_jTCOI8kTynj2osNtPc">

Thank you very much, It's work now. 👍

**Comment by gingerbeardman** [comment]
@1024jp do you think use of smart options in the menu bar should change the current mode settings? 

This seems like as compromise between old and new behaviour.

**Comment by gingerbeardman** [comment]
That's a shame.

4.8.x is a real step back in usability as we can see by the number of issues regarding quotes/modes.

**Comment by vfr456** [comment]
This is really a "stupid quote" !

**Comment by 1024jp** [comment]
It depends on the usage. CotEditor is not only for coding. This is the reason why I added the mode feature and gave room to customize it to the user.

**Comment by gingerbeardman** [comment]
I think new behaviour should have been explained with a popup when it was introduced, maybe opt in/out

**Comment by 1024jp** [comment]
> I think new behaviour should have been explained with a popup when it was introduced, maybe opt in/out

I personally don't like the so-called What's New screen, so far I have not added it except for important changes. However, starting with the next minor update, CotEditor will have it (it has already been implemented).

**Comment by gingerbeardman** [comment]
Thank you for remaining open minded about this
