### ISSUE TITLE
タブ切り替えショートカットの実装要望

### ISSUE THREAD

**Issue by maguro-0706** [coteditor/CotEditor#1632]
### Current issue

いつも便利に利用させていただいております。

先日、複数のファイルを立ち上げそれらを横断的に作業する際、タブを左右に移動できるショートカットがあると便利だと感じました。
現状、タブを切り替える方法がクリックしかないように見受けられたので、これがキーボードのみで作業できると嬉しいです。

どうぞご検討のほどよろしくお願いいたします。

### The solution you'd like

ちょうど、Chromeにおける【Cmd+Opt+←】および【Cmd+Opt+→】のような挙動を期待します。
キーボード上にて、タブの移動ができるようになると嬉しいです。

### CotEditor version

4.8.2

### macOS version

Ventura 13.6.6

**Comment by 1024jp** [comment]
<img width="787" alt="Screenshot 2024-05-07 at 11 22 45" src="https://github.com/coteditor/CotEditor/assets/1165044/716c4f22-e6d5-46a6-b365-521ce9f22672">

ウインドウタブですよね。すでにありますよ。
Macの世界ではControl-Tabが。それに当たります。
主要なショートカットはメニュー項目に紐づいていてメニューにも表示があります。

また、Command-数字（例えばCommand-2で2枚目のタブ、Command-9で最後のタブ）で特定のタブ移動することもできます。
こちらはSafariを模倣してCotEditorで独自に実装しているショートカットになります。

**Comment by maguro-0706** [comment]
なぜか長いこと全く気付いておりませんでした……
親切に教えてくださりありがとうございます！
