### ISSUE TITLE
Incorrect “Comments” Label in Preferences > Appearance

### ISSUE THREAD

**Issue by BlazingFrag** [coteditor/CotEditor#1635]
### Description

The English-language label next to the swatch for comments reads “Commands” instead.

### To Reproduce

1. In the menu bar, go to **CotEditor** > **Preferences**.
2. Click on the **Appearance** tab.
3. Find the label next to the swatch in the bottom-right corner, and compare with the label in the left column immediately under “Keywords”. Note that both labels are the same.
4. Click the swatch in the bottom-right corner, then click another color. Observe that the colors affected in the editor are comments, not commands.
5. Click the other swatch, then click another color. Observe that the colors affected are commands, not comments.

### Expected behavior

The bottom-right label should read “Comments”.

### CotEditor version

Version 4.8.2 (647)

### macOS version

14.4.1 (23E224)

### Additional context

System Settings > Language & Region > Preferred Language is set to English (US).

**Comment by 1024jp** [comment]
Oops. Thank you!
