### ISSUE TITLE
Typo in Settings

### ISSUE THREAD

**Issue by makzsslm** [coteditor/CotEditor#1636]
### Description

Command -> **Comments** 

![image](https://github.com/coteditor/CotEditor/assets/125161526/f38e918d-31fe-4321-88d4-038442a15a09)

### To Reproduce

/

### CotEditor version

4.8.2

### macOS version

14.4.1

**Comment by 1024jp** [comment]
Thank you. This has already been reported in #1635 and has just been fixed in 19082ce388516dcc597565fef28c1ef5ade4aa9c.
