### ISSUE TITLE
App open but editor/window not visible

### ISSUE THREAD

**Issue by vinayverghese** [coteditor/CotEditor#1640]
### Description

The app is open in my dock, but I am unable to access any files or open a nw file.

### To Reproduce

1. Open app
2. Click on File -> Open New
3. Right click dock icon -> select recent document or new document 
4. Unable to open existing document or open new file

### Expected behavior

I should be able to open existing document or open a new document

### CotEditor version

4.8.3 (649)

### macOS version

14.4.1 (23E224)

**Comment by 1024jp** [comment]
Thank you for the report, but the issue is already reported at #1638.
