### ISSUE TITLE
collapse/expand indentations

### ISSUE THREAD

**Issue by kenzokabuto77** [coteditor/CotEditor#1641]
### Current issue

The software already keeps tracks of indented portion of code (i.e. an if...then branch) and a long subbranch makes difficult to overview the main code

### The solution you'd like

it would be nice a "+" botton to expand/collapse single subbranches, like notepad++ does

### CotEditor version

4.8.3

### macOS version

14.4.1

**Comment by 1024jp** [comment]
duplicated, already requested at #459
