### ISSUE TITLE
Would it be possible to add a "New Tab to the right" option just like in chrome and notepad ++?

### ISSUE THREAD

**Issue by iggymakesthings** [coteditor/CotEditor#1645]
### Current issue

Sometimes I need a new tab next to the current one for comparison or information. But I am unable to do this in coteditor currently.

### The solution you'd like

When I right click on a tab, there are options like "Close Tab", "Close All Tabs" etc
My solution would be to add a new tab option "New Tab to the Right" or thereabouts so that we can create a new tab next to the current one

### CotEditor version

4.8.2

### macOS version

mac os 14.5

**Comment by 1024jp** [comment]
CotEditor uses window tabs provided by the macOS UI framework straightforwardly and the framework doesn't provide such an option.
CotEditor has a policy to stick to the macOS native UI; therefore, I will not as well as long as Apple doesn't provide such a command.

**Comment by iggymakesthings** [comment]
No issues. Thanks
