### ISSUE TITLE
The icon is too ugly, and the icon color is ugly too

### ISSUE THREAD

**Issue by LetheTan** [coteditor/CotEditor#1646]
### Current issue

The icon is too ugly, and the icon color is ugly too

### The solution you'd like

Make the icon look better and change the color

### Alternatives you've considered

Make the icon look better and change the color

### CotEditor version

latest

### macOS version

14.2.1

### Additional context

Make the icon look better and change the color

**Comment by 1024jp** [comment]
But I am happy with the current icon.
