### ISSUE TITLE
disable that all occurences of current selection are highlighted in same color, too

### ISSUE THREAD

**Issue by marebe1602** [coteditor/CotEditor#1650]
### Current issue

when I have a large, non-source-code file and select a fragment e.g. an e-mail address, all other occurences are automatically highlighted in the same selection color, too. In some files this is a problem, because you don't see anymore, which occurence you were actually focusing, on.
This is sometimes quite annyoing.

### The solution you'd like

use a different color for the automatically highlighted occurences

### Alternatives you've considered

add a config parameter to prevent this behaviour

### CotEditor version

4.8.5 (653)

### macOS version

14.5 Sonoma

### Additional context

<img width="262" alt="grafik" src="https://github.com/coteditor/CotEditor/assets/5097187/13c23174-db7e-428f-8064-30f386f694c6">

**Comment by 1024jp** [comment]
You can disable this feature by turning off the option "highlight instances of selected text" option in the Edit settings pane.

<img width="712" alt="Screenshot 2024-06-09 at 20 57 06" src="https://github.com/coteditor/CotEditor/assets/1165044/659c5519-8028-43e8-b531-762d0c2366ef">


> all other occurences are automatically highlighted in the same selection color, too.

Yeah, this point you made is valid.
This feature, highlighting all the same instances, was implemented when the macOS system use the specific colors for select text. So I assigned the green color for instance highlight.
But in the last systems, macOS prefers using the app specific color for text selection highlight.
This new feature is good, in general; however, it now conflicts with the instance highlight.
It would be better to change the strategy for such highlighting. Let me think.

**Comment by marebe1602** [comment]
Thanks a lot for your quick answer! I changed my settings now. Depending on the solution I will re-activate the option.
I've been using your editor for years and it's great!
Keep up the good work.

**Comment by 1024jp** [comment]
I think now is the right time to add a new color, "Highlight," to the theme format for both occurrences highlighting and matched text highlighting for the Find All command also because Apple added a new highlighting API to TextKit on the upcoming macOS 15.
I'll implement it in the next minor update of CotEditor to be released this autumn.
