### ISSUE TITLE
CSV highlighting

### ISSUE THREAD

**Issue by cal-ellevation** [coteditor/CotEditor#1652]
### Current issue

I love CotEditor for its simplicity, and I like it when I'm doing things other than coding (which is what i use vscode for). There is a plugin in VScode called Rainbow CSV which makes it so that each column in a csv appears in a different color so that it is easy to delineate line to line what column data falls into.

### The solution you'd like

Some implementation of Rainbow CSV for CotEditor. I don't need all the fancy features, would just love the syntax highlighting.

### CotEditor version

4.8.5

### macOS version

Sonoma 14.5

**Comment by 1024jp** [comment]
In my opinion, such a feature is not to bundle to the app officially.
If you want, you can make it as a custom syntax.
