### ISSUE TITLE
文章の方向を「縦書き」にして保存すると、「横書き」状態では保存できなくなる

### ISSUE THREAD

**Issue by wanik** [coteditor/CotEditor#1653]
### Description

フォーマット > 文章の方向　を一度「縦書き」にして保存すると、以降の編集において「横書き」に戻して保存しても、「縦書き」の状態で開くようになる。

### To Reproduce

再現手順
1. 〔設定：文章の方向「左から右」のボタンを選択済み。〕
2. 新規ファイルを作成して、何かを入力し、保存して閉じる（初期設定に従い、横書きのまま）。
3. そのファイルを開く → 横書きで表示される🆗。
4. フォーマット > 文章の方向　を「**縦**書き」にし、内容に変更を加えて保存して閉じる。
5. 再度ファイルを開く → 縦書きで表示される🆗。
6. フォーマット > 文章の方向　を「**横**書き」にし、再び内容に変更を加えて保存して閉じる。
7. 再度ファイルを開く → 直前で保存した横書きではなく、**縦**書きで表示される⚠️。
8. 以降、6.-7. を何度やっても「横書き」状態では保存されない。開くと「**縦**書き」状態となる⚠️。
 

### Expected behavior

ファイルを開いたときに、直前に保存したときの文章の方向で開くのが望ましいと思います。

### CotEditor version

CotEditor: 4.8.5 (653)

### macOS version

System: macOS バージョン13.6.7（ビルド22G720）

**Comment by 1024jp** [comment]
ご指摘ありがとうございます。
確かに現在の実装だと解除が上書きされないですね…。
次のリリースで修正します。

**Comment by wanik** [comment]
ご対応、ありがとうございます。
無造作に、（ファイル毎に）「直前に保存したときの文章の方向で開くのが望ましい」と書いてしまいました。それがユーザーとしては望ましくありますが、保存時の状態に関わらず、環境設定で設定された方向で開くという仕様でも構いません。

**Comment by 1024jp** [comment]
直前の状態を正しく保存するように書き直しましたー。
