### ISSUE TITLE
ファイルを閉じようとするとフリーズします

### ISSUE THREAD

**Issue by reasonfive** [coteditor/CotEditor#1654]
### Description

ファイルを閉じようとすると、ファイル保存or破棄のポップアップでフリーズします

### To Reproduce

command + w

### Expected behavior

フリーズしないこと

### CotEditor version

4.5.9 (575)

### macOS version

macOS バージョン12.6.1（ビルド21G217）

**Comment by 1024jp** [comment]
> 4.5.9 (575)

1. 現在の最新版はCotEditor _4.8.5であり、このバージョンはすでにサポートを終了しています。_
2. このバグは #1377 にて報告済みですが、Apple側のバグのため修正ができないと判断しています。
3. CotEditorの実行環境を日本語**以外**にすることでこの挙動は回避できます。
