### ISSUE TITLE
Most notes open in the tab, but some open in a single window

### ISSUE THREAD

**Issue by tofra** [coteditor/CotEditor#1656]
### Description

I am using CotEditor 4.8.6 (655), using tabs. So all my notes are opened in tabs.
![image](https://github.com/coteditor/CotEditor/assets/1746173/3fec99d3-0bfc-4da1-a5af-0e62cb1d1738)

I had to close CotEditor yesterday, and after opening again one window is opened like above incl tab, but not all notes have opened in the tabs, but now 6 are opening in a new window.
![image](https://github.com/coteditor/CotEditor/assets/1746173/38e2fcd7-d87a-4b8b-bd21-96b34e1109b5)

I have 58 notes open, all of them (incl those 6 in a different window) are showing on the menu bar on the top under `Window`

So is this expected behaviour? Is it possible to move the 6 new windows (eg. `Untitled 125`) back to the window with all the tabs?

### To Reproduce

Not sure if it is reproducable. Maybe after opening 60+ tabs?

### Expected behavior

When working with tabs, all tabs should be in the main window

### CotEditor version

4.8.6 (655)

### macOS version

14.4.1

**Comment by 1024jp** [comment]
I am aware of this phenomenon.
However, unfortunately, I have to say that it cannot be guaranteed 100% that all documents opened simultaneously will open in tabs in the same window.
The system sometimes splits the documents on its own already at the point where CotEditor processes those opened documents.
So CotEditor doesn't know those documents should be bound together.
Sorry.
