### ISSUE TITLE
Unable to edit `/etc/sudoers` file due to a permission issue

### ISSUE THREAD

**Issue by dralshehri** [coteditor/CotEditor#1657]
### Description

When trying to edit the sudoers file `/etc/sudoers` using CotEditor, I get the following message:
  
    The document “sudoers.tmp” could not be opened. You don’t have permission.

### To Reproduce

Run the following command:

```sh
EDITOR="cot -w" sudo visudo
```

### Expected behavior

The sudoers temporary file `/etc/sudoers.tmp` should open in CotEditor and be edited normally.

### CotEditor version

CotEditor: 4.8.6 (655)

### macOS version

macOS Version 14.5 (Build 23F79)

### Additional context

Another issue that may be related is editing config files using [chezmoi](https://www.chezmoi.io). When I try to edit a file using a command like `EDITOR="cot -w" chezmoi edit ~/.zshrc`, the file opens as a temporary file in a `chezmoi-*` directory under `$TMPDIR`, however, when I try to save the changes, I get this message:

    The document “.zshrc” could not be saved. The file is locked.
    
and when I hit "Save Anyway", I get this message:

    You don’t have permission to save the file “.zshrc” in the folder “chezmoi-edit566696390”.

**Comment by 1024jp** [comment]
CotEditor cannot overwrite the files that don't have permission even with `sudo`. 
This action is restricted by Apple as long as CotEditor is sandboxed.

**Comment by jhubbardsf** [comment]
@1024jp Is there a way to install cotEditor outside of the App Store so it won't be sandboxed?

**Comment by 1024jp** [comment]
@jhubbardsf 
CotEditor is also available outside of the AppStore.
You can find it at this link: https://coteditor.com/archives.

However, all CotEditors are sandboxed, even for non-AppStore versions.
We respect Apple’s Sandbox policy, so I have no plans to release CotEditor without sandboxing.

**Comment by jhubbardsf** [comment]
@1024jp I feel like Cot is the only text editor I've tried that couldn't edit a protected file if opened with sudo. Does that mean Sublime, Atom, etc are all non-sandboxed? 

Genuinely curious, I never knew that was a restriction.

**Comment by 1024jp** [comment]
@jhubbardsf 

> Does that mean Sublime, Atom, etc are all non-sandboxed?

Yes. They are not sandboxed.

**Comment by jejacks0n** [comment]
I came here because of the same issue with chezmoi.

I wanted to add that I too wish this worked, because I really like CotEditor, and find that it's just the right balance of feeling system native, while also being functionally appropriate for most of what I need for editing things like system files.

Thanks for your hard work on it, I think it's a great app and product. I feel sad that I need to find a different solution for this specific scenario, while I also really appreciate the app.
