### ISSUE TITLE
拡張子が自動で付きません。デフォルトのシンタックスはplain textに設定しています。

### ISSUE THREAD

**Issue by iooi5009** [coteditor/CotEditor#1660]
### Description

拡張子が自動で付きません。デフォルトのシンタックスはplain textに設定しています。

### To Reproduce

1. 保存

### CotEditor version

4.8.2

### macOS version

14.5

**Comment by iooi5009** [comment]
拡張子なしで保存するとwordのアイコンが付き、テキストエディットで開かれます。

**Comment by 1024jp** [comment]
duplicated #1542

macOS 14で使えるCotEditorの最新版は4.8.6です。
不具合報告は必ず最新のバージョンで検証してから行ってください。

なお、本件はCotEditor 4.8.5で修正済みです。
も最新版でもまだ継続する場合はあらためてレポートください。
