### ISSUE TITLE
Abnormal phenomenon during input

### ISSUE THREAD

**Issue by woshiniming007** [coteditor/CotEditor#1661]
### Description

When I select the character in the picture and type 4418, I will find that the nearby quotation marks become abnormal and the input is confused.

https://github.com/coteditor/CotEditor/assets/55045806/31d1a142-ee26-4054-8484-b2b341b43d0f

raw text:
```
curl -X POST http://127.0.0.1/pipelinePerform/savePipelineImage  -H 'Content-Type: application/json;charset=UTF-8' -d '{\"pipelineHistoryId\":'$HISTORY_ID', \"uniqueId\":\"'$imageId'\", \"artifactoryName\":\"'${imagename}'\", \"artifactoryType\":\"container\",\"artifactoryTag\":\"'ci_${commitId}_$BUILD_ID'\"}'   -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8'  
```

### CotEditor version

4.8.5

### macOS version

14.5

**Comment by 1024jp** [comment]
You can disable the feature by turning off the "Smart quote" option for the appropriate mode in the Mode settings pane.

<img width="712" alt="Screenshot 2024-06-29 at 11 57 14" src="https://github.com/coteditor/CotEditor/assets/1165044/4148ca69-ab27-4f65-a4a9-872f00b355ff">
