### ISSUE TITLE
Open new files directly in a new tab

### ISSUE THREAD

**Issue by Private0xCC** [coteditor/CotEditor#1665]
### Current issue

I'm used to viewing multiple files at the same time using multiple tabs in one window.
Whenever I open a new file, I have to use the merge all windows feature again!

### The solution you'd like

I would like to add a new feature that allows me to open new files by creating a new tab directly in the current window!
As well as the ability to open new files directly in an existing blank tab.
Thank you very much!

### CotEditor version

4.8.6 (655)

### macOS version

macOS Sonoma 14.5

**Comment by 1024jp** [comment]
> I would like to add a new feature that allows me to open new files by creating a new tab directly in the current window!

Does the "Prefer Tabs" option in the Window settings pane work for you?

<img width="712" alt="Screenshot 2024-07-11 at 14 12 06" src="https://github.com/coteditor/CotEditor/assets/1165044/9f2e8d65-66f5-4db9-a7f3-8904447690c8">

> As well as the ability to open new files directly in an existing blank tab.

To create new documents in an existing window as a tab, you can perform the "New Tab" command in the File menu or click the plus button in the tab bar.

**Comment by Private0xCC** [comment]
Perfect. Thank you so much for your help.
