### ISSUE TITLE
Add a global "Restore Defaults" option

### ISSUE THREAD

**Issue by victormoliveira1** [coteditor/CotEditor#1667]
### Current issue

Seeing how some sections of the Preferences window is highly customizable and have a lot of options to choose from (like Appearance, Window and Mode), it would be nice to have a global "Restore Defaults" option in the General tab.

### The solution you'd like

Add a global "Restore Defaults" option in the General tab, so we don't have to reinstall the app from scratch to reset the preferences.

### Alternatives you've considered

I know that it's possible, for some apps on MacOS, to reset the preferences by issuing the command `default delete <CFBundleIdentifier>`, which in the case of CotEditor would be `default delete com.coteditor.CotEditor`.

I don't know if this works for CotEditor but if it does, I think it's a valid alternative solution and worthy of being in the GitHub Project Wiki or inside the app User Guide.

### CotEditor version

4.8.7

### macOS version

MacOS Sonoma 14.5

**Comment by 1024jp** [comment]
It is not usual to have a GUI control to clear all defaults in a macOS app.
If you see macOS apps provided by Apple, you'll find none of them have such a button.
CotEditor strongly follows the standard of macOS application; so I'll not add it.

You can use the `defaults` command if you want.
Or use apps like [AppCleaner](https://freemacsoft.net/appcleaner/).

> I don't know if this works for CotEditor but if it does, I think it's a valid alternative solution and worthy of being in the GitHub Project Wiki or inside the app User Guide.

In the CotEditor User Guide bundled to CotEditor.app, you can see all the locations where settings are stored. 

<img width="872" alt="Screenshot 2024-07-17 at 18 06 35" src="https://github.com/user-attachments/assets/624ab853-950e-4af3-86a7-a4065a383c58">
