### ISSUE TITLE
ドラッグ選択中に選択が解除される

### ISSUE THREAD

**Issue by sdr0x07b6** [coteditor/CotEditor#1669]
### Description

- macOS 14.5
- CotEditor 4.8.7

文字列を範囲選択するためドラッグしていると、途中で、もしくはいきなり最初から、選択が解除されてしまうことが頻繁に発生しています。
現在 4.8.7 ですが、 4.8.7 かもしくは 1 つ前のバージョンで、原因になりうる変更はあったでしょうか？

ドラッグ中に、ウィンドウフッタの「文字数」「位置」が半分リアルタイムに更新されたりされなかったりする感じもしていて、いままで注目していませんでしたが、そんな動作はしなかったような気もします。
ですから最近実装されたとすれば、リアルタイムに更新する過程で選択を解除してしまっているのではと思いました。

選択ドラッグする文字は英数字や日本語など関係なく再現します。

解除されてもドラッグを続けているとそこから選択ドラッグが開始されます。
なんとなく気になるというものでなく、テキスト編集に支障が生じています。
ビデオの22秒あたりでは、解除に併せて文字（半角スペース）の移動までされています。

### To Reproduce

https://github.com/coteditor/CotEditor/assets/1102138/8c495d29-a5ef-4cb4-ab53-71b38c3ef729

### CotEditor version

4.8.7

### macOS version

14.5

**Comment by sdr0x07b6** [comment]
他のテキストエディタで同じ操作をしても再現しないため、操作や環境が原因ではないと思ます。

また CotEditor でも新規ドキュメントを作成して、ビデオの文字列をすべてペーストして試しても再現しないことがあるように思います。
ということは、単に文字列があってそれをドラッグ選択しさえすれば発生するのでなく、そのドキュメントが内部で管理している状態などに依存する？

と憶測を書いていると紛らわしくなりそうですね。。
再現「率」を示すのは難しく、再現するときはビデオのようにある程度頻繁で、しないときはしません。

今日はテキストを書いていてなにかストレスを感じ続けるな…と思ってよく観察したら当現象でした。
CotEditor 以外でも一日中テキストをたくさん書いていましたが操作ストレスは一度もなかったので、いま少し試してたまたま再現しなかったのでなく実際なかったと思います。

**Comment by sdr0x07b6** [comment]
いま新規ウィンドウを開いて書き始めたばかりですが、すぐに再現しているため、内部の状態というわけでもないかもしれません。。

**Comment by 1024jp** [comment]
私の手元の環境では再現できないのですが、macOSにバンドルされているTextEdit.appで再現しますか？

**Comment by sdr0x07b6** [comment]
当件投稿した当日は、ちょうど TextEdit.app もある程度の時間使っていましたが再現していませんでした。ほか、ウェブページのフォームでのテキスト入力も多くしていましたが再現していませんでした。当件に気づいてから意識して見ていましたが、いくら試しても CotEditor のみでしたのでこちらに投稿することにしました。

ただ、いま再現しません。。お書きしたとおり、再現するときはする、しないときはしないため、今しないのがたまたまかは不明です。

もう数日、様子見してみて結果お伝えします（再現しなくてもしなかったこと共有します）。
それまでは放置いただくで大丈夫です🙇🏻

**Comment by 1024jp** [comment]
追加の情報ありがとうございます。ちなみにポインティングデバイスはマウスですか？ トラックパッドですか？ できたら機種も教え得ていただけると幸いです。

**Comment by 1024jp** [comment]
デバイスの回答ありがとうございます。
また細かい挙動の説明も助けになります。

ちょっとすぐに解法は見つけられずにいますが、私の手元で再現できないだけなのかもしれないので、もう少しイシューはクローズせずに様子見させてください。
今年の秋にmacOS 15が出てそのタイミングでCotEditor 5.0をリリースしようと計画しているのでその段階でもう一度判断してレアケースなようだったらクローズしようと思います。それまでにもし何かわかれば対処します。

**Comment by 1024jp** [comment]
こんにちは。
macOS 15とCotEditor 5.0.0がリリースされて数日となりますが、本件変化もしくは改善ありましたでしょうか？

他の方の報告もないようなので、もしも再現されないようでしたらこのチケットはクローズしようかと考えております。

**Comment by sdr0x07b6** [comment]
5.0.0を使っています。いまのところ一度も再現していません。
クローズいただき結構です。万が一再発したらお知らせします。
気にかけていただいており、ありがとうございます。

**Comment by 1024jp** [comment]
ありがとうございます！ また発生したら（ご面倒かもしれませんが）何なりとお知らせください。
