### ISSUE TITLE
TTB - tiny title bar

### ISSUE THREAD

**Issue by martinengelke** [coteditor/CotEditor#1671]
### Current issue

I'm always frustrated when [...]
[...] I am trying to move the find/replace window.

### The solution you'd like

Set the title bar size to 'MacOS standard'.

<img width="617" alt="Bildschirmfoto 2024-07-18 um 12 05 24" src="https://github.com/user-attachments/assets/f74d9b9d-8036-4b2e-95f9-701ce6c3800b">

### CotEditor version

Version 4.8.6 (655)

### macOS version

14.5 (23F79)

**Comment by 1024jp** [comment]
> Set the title bar size to 'MacOS standard'.

Current title bar is the standard size for a utility panel in the macOS world.

For instance, Pages.app by Apple uses this type of title bar for the find panel.
So I will keep the current implementation.

<img width="566" alt="Screenshot 2024-07-19 at 21 25 38" src="https://github.com/user-attachments/assets/307f9d93-dba5-4cfc-81a8-0760a1f6f26d">

**Comment by martinengelke** [comment]
Hi,

Sorry to hear that, maybe I was a bit wrong about that. In the dictionary app, which what I am working daily for hours, it is not like that: 

￼


By the way, how can I donate to your efforts for this beautiful app?

Thanks
Martin

**Comment by martinengelke** [comment]
Same for MS Word, that’s why I maybe struggled about that :)

￼
