### ISSUE TITLE
Option to sort function picker alphabetically

### ISSUE THREAD

**Issue by gingerbeardman** [coteditor/CotEditor#1672]
### Current issue

I use the function picker but my functions are not in any meaningful order so it takes time to find the function i want, even if I type its name it's still slow

<img width="312" alt="Screen shot 2024-07-22 at 22 08 59" src="https://github.com/user-attachments/assets/f0baa494-6fc8-4d80-8a07-5b068734ffb7">

### The solution you'd like

I'd like an option to sort the entries of the function picker

### Alternatives you've considered

re-ordering my code (one for a rainy day, perhaps)

### CotEditor version

- 4.8.7 (657)

### macOS version

- macOS Version 14.5 (Build 23F79)

**Comment by 1024jp** [comment]
I feel this is not a major request and can't come up with an intuitive and smart implementation, so let me reject it.

By the way, you can filter outline items in the outline inspector.

**Comment by gingerbeardman** [comment]
OK, I understand.

I'll use Nova editor when I'm editing code in a serious way.

**Comment by gingerbeardman** [comment]
Here's Nova

<img width="1312" alt="Screen shot 2024-08-08 at 18 29 10" src="https://github.com/user-attachments/assets/3d936d46-3004-4a3f-9179-72fa251db7b1">
