### ISSUE TITLE
"Check Spelling While Typing" ON/OFF Toolbar Tool

### ISSUE THREAD

**Issue by gregarios** [coteditor/CotEditor#1675]
### Current issue

I need to be able to turn off the red underline showing spell checking, quickly, and often.

### The solution you'd like

It would be nice if there were a toolbar item to turn off and on the spell checking while typing feature. Maybe even a hot-key ability too.

### CotEditor version

any

### macOS version

Sonoma 14.5

**Comment by 1024jp** [comment]
I’ve thought about your request several times, but I’ve finally decided not to implement it. I’m sorry.

CotEditor already has a Spell Check toolbar item that toggles the visibility of the Spelling and Grammar window. I think it’s too much to add another spell check toolbar item, but I also think it is not the best to change the behavior of the current Spell Check toolbar item to toggle the auto spell check feature.

So, I would like to keep the current design.

Instead,

> Maybe even a hot-key ability too.

You can assign your own hot-key in the Key Binding settings pane.

<img width="712" alt="Image" src="https://github.com/user-attachments/assets/636a780e-4cec-4855-91ba-4e191965494e" />
