### ISSUE TITLE
Issue with selecting penultimate line using column select

### ISSUE THREAD

**Issue by gingerbeardman** [coteditor/CotEditor#1676]
### Description

It's not possible to selecting penultimate line using column select, it jumps two lines

### To Reproduce

1. Try to select penultimate line using column select
2. it's not possible, it jumps two lines

https://github.com/user-attachments/assets/5e412387-2acd-4b3e-bba3-14bea06c2072

### Expected behavior

- should be possible

### CotEditor version

- 4.8.7

### macOS version

- 14.6

**Comment by 1024jp** [comment]
Thank you for the report.
I’ve just fixed this issue.

This correction will be included in CotEditor 5.0.0 to be released this fall, or possibly in CotEditor 4.8.8 when it is released before that.
