### ISSUE TITLE
Please Publish a dmg for download

### ISSUE THREAD

**Issue by sonaro** [coteditor/CotEditor#1677]
### Current issue

Many of us do not want the all-seeing eye of Apple watching everything we download...

### The solution you'd like

...so please publish a standalone dmg for happy editing, and happy privacy. :)

### Alternatives you've considered

I understand that managing the dmg takes more time too.

### CotEditor version

4.8.7

### macOS version

15

**Comment by 1024jp** [comment]
We already distribute CotEditor outside of the App Store also.
You can download the app from here:
http://coteditor.com/archives
