### ISSUE TITLE
在2024年是否有计划添加高亮修改行的功能？

### ISSUE THREAD

**Issue by DeliciousOrange** [coteditor/CotEditor#1678]
### Current issue

你好，@1024jp，我是一位 windows 上编程的 programmer，在公司使用 notepad++作为文本编辑器， 由于家用机器为 macbook，一直寻找 mac 上替代 notepad++的编辑器，直到发现了CotEditor，不可否认，这是迄今mac 上我能找到的最好的编辑器，遗憾的是，它缺少高亮变更行的这么酷的功能，类似 notepad++，可否将这项酷的功能排进计划表中？

### The solution you'd like

在行编号处高亮显示修改行，类似 issue#1276

### CotEditor version

4.5.9

### macOS version

12.7.5

**Comment by 1024jp** [comment]
Sorry, but I don’t speak Chinese.

> 遗憾的是，它缺少高亮变更行的这么酷的功能，类似 notepad++

DeepL says the translation of the sentence above is the below:

> Unfortunately, it lacks such a cool feature as highlighting changed lines, like notepad++

If I understand correctly, you talk about something like the request #1276?
If so, my answer is not changed from https://github.com/coteditor/CotEditor/issues/1276#issuecomment-1762497546.
