### ISSUE TITLE
Move current line (keyboard shortcut)

### ISSUE THREAD

**Issue by gingerbeardman** [coteditor/CotEditor#1681]
### Current issue

In Nova editor and on GitHub web editor, I can use Alt+cursor up/down to move line up/down

### The solution you'd like

- support Alt+cursor up/down to move line up/down

### Alternatives you've considered

- Nova
- GitHub Editor

### CotEditor version

- 4.8.7 (657)

### macOS version

- 14.6.1

### Additional context

Screen recording

https://github.com/user-attachments/assets/ad05165e-393c-464b-a581-6a4879c1ce81

**Comment by 1024jp** [comment]
Hey, the Alt key is for Windows!
Well, maybe you meant the Option key.

In CotEditor, the default key for the same action are the <kbd>Command</kbd>+<kbd>Option</kbd>+<kbd>↑</kbd> and <kbd>Command</kbd>+<kbd>Option</kbd>+<kbd>↓</kbd>.
In macOS, it is recommended to include the Command key as possible for normal shortcut keys.

<img width="820" alt="Screenshot 2024-08-13 at 14 24 34" src="https://github.com/user-attachments/assets/811db52d-8c17-40af-bc06-e18b715b6afc">


You can assign another shortcuts in the Keybinding settings pane.

**Comment by gingerbeardman** [comment]
Oh, thanks!!

Yes i often say Alt when I mean option because my old Apple External keyboard that I use still has Alt written on it.

Its battle scars are very visible! I will use it until it stops working, or maybe until I dig through to the other side 😆 

![EBDbY1sXkAAaz55](https://github.com/user-attachments/assets/b62cd72d-ba4d-46bb-b8e1-5d1f3ca175b9)
