### ISSUE TITLE
'Reopen windows from last session' not working

### ISSUE THREAD

**Issue by MichaelHipp** [coteditor/CotEditor#1682]
### Description

The option to 'reopen windows from last session' is not working.

### To Reproduce

Open one or more files. Close CotEditor. Open CotEditor. The previously opened files are not there, only a new empty document.

### Expected behavior

The files previously open are re-opened just as they were.

### CotEditor version

CotEditor: 4.8.7 (657)

### macOS version

System: macOS Version 14.4 (Build 23E214)

**Comment by 1024jp** [comment]
I could not reproduce the issue in my environment.

So, could you provide further information to me?

1. > Close CotEditor. Open CotEditor.
  
    Please describe the actions step-by-step. Did you completely close CotEditor, for instance using the <kbd>Command</kbd>+<kbd>Q</kbd> keys?
3. Please share the screenshots of both:
    - The General settings pane in CotEditor
       <img width="712" alt="Screenshot 2024-08-13 at 14 18 13" src="https://github.com/user-attachments/assets/e66f7711-6e25-4b26-99cb-4fc09aee8a8a">
    - The Windows section in the Desktop & Dock pane in the System Settings:
      <img width="827" alt="Screenshot 2024-08-13 at 14 15 11" src="https://github.com/user-attachments/assets/39b8d80d-a3b4-4cbe-85df-93cc41db1112">

**Comment by MichaelHipp** [comment]
Thank you.

To close CotEditor, I clicked the red X in the upper left corner of the CotEditor window.
To open CotEditor, I clicked the CotEditor icon in the dock.

<img width="1296" alt="Screenshot 2024-08-13 at 5 41 49 AM" src="https://github.com/user-attachments/assets/ce988d55-95b8-4e72-b11c-56b71b154a3d">

<img width="1296" alt="Screenshot 2024-08-13 at 5 42 34 AM" src="https://github.com/user-attachments/assets/f84aa762-e70a-46a0-aafa-e8ed0ccf2e6f">

**Comment by 1024jp** [comment]
Thank you for the reply.

> To close CotEditor, I clicked the red X in the upper left corner of the CotEditor window.

Aha, OK. That’s not the right way to quite an application in macOS and the reason why your windows are not restored.
If you close a window, the window is literally closed and not considered to be a window to restore.
Instead, you need to quite an application either by selecting CotEditor > Quit CotEditor menu command or by the <kbd>Command</kbd>+<kbd>Q</kbd> shortcut keys.

**Comment by MichaelHipp** [comment]
> Thank you for the reply.
> 
> > To close CotEditor, I clicked the red X in the upper left corner of the CotEditor window.
> 
> Aha, OK. That’s not the right way to quite an application in macOS and the reason why your windows are not restored.

Ok. I'm recently converting from Windows & Linux. So what happens if I reboot or something crashes? Evidently the reloading of existing documents is not within the control of CotEditor at all?
