### ISSUE TITLE
Cmd - ` does not switch between windows

### ISSUE THREAD

**Issue by edrf12** [coteditor/CotEditor#1683]
### Description

On Mac pressing Cmd - ` should switch between the windows of an app, this does not happen with cot editor

### To Reproduce

1. Open multiple windows of cot editor (not tabs)
2. Try switching between them using Cmd - `
3. Nothing happens

### Expected behavior

Windows switch just like other Mac apps

### CotEditor version

4.8.7

### macOS version

14.6.1

**Comment by 1024jp** [comment]
Hmm, <kbd>Cmd</kbd>-<kbd>`</kbd> works as expected in my environment.

Could you let me know what kind of keyboard layouts you use?

**Comment by edrf12** [comment]
I tried it out with different keyboards and I see what you mean, my main keyboard input source is "Portuguese (Brasil)" even though my keyboard is originally a US keyboard layout. 

On the video I've shared below I switch between the US input source (ABC) and Portuguese Brazil input source.

As you can see everything works alright on the ABC keyboard, but only CotEditor does not work when the Brazilian keyboard is on (Safari was used to demonstrate that, but other apps do work).


https://github.com/user-attachments/assets/10238555-ec06-48b6-9b5e-1eca0283cc2b

**Comment by 1024jp** [comment]
@edrf12 Hi, sorry for taking time.
But now, I’ve identified the cause of the issue, and it will be resolved in the upcoming version of CotEditor, 5.0.7.
