### ISSUE TITLE
Language support for R Markdown and Quarto files

### ISSUE THREAD

**Issue by herry23xet** [coteditor/CotEditor#1684]
### Current issue

Currently, R Markdown (.Rmd) and Quarto (.qmd) files are displayed without syntax highlighting.

### The solution you'd like

Syntax highlighting for both.

### CotEditor version

4.8.7

### macOS version

14.6.1

**Comment by 1024jp** [comment]
There are so many Markdown dialects that there is no end to them, so CotEditor has a policy of not dealing with them in the default syntax definitions.

Instead, you can customize the behavior by adding the filename extensions you want to the Markdown syntax. 

<img width="792" alt="Screenshot 2024-08-23 at 16 02 36" src="https://github.com/user-attachments/assets/bceeac72-41eb-4ec3-b6c3-912bdecdf077">
