### ISSUE TITLE
Only little translation inconsistency

### ISSUE THREAD

**Issue by ToniMaroni** [coteditor/CotEditor#1685]
### Description

![Bildschirmfoto 2024-08-22 um 05 47 44](https://github.com/user-attachments/assets/cc12c284-cd49-4689-a89d-3140dd504f9e)

The german services item to create a document with the selection, doesn't follow Apples own translation.

### To Reproduce

"Neues CotEditor-Dokument mit Auswahl" … should be … 

### Expected behavior

"Auswahl in neuem CotEditor-Fenster"

### CotEditor version

 4.8.7

### macOS version

14.6.1 (Build 23G93)

### Additional context

Sorry if a bug report is a bit drastic, but I thought I'd let you know.

**Comment by 1024jp** [comment]
Thank you for the suggestion!
In the next version, I'll rename it in all localizations to match the service name in the TextEdit expression.
