### ISSUE TITLE
Filename on toolbar remains "Untitled" after creating new file with custom name from sidebar

### ISSUE THREAD

**Issue by kymmt90** [coteditor/CotEditor#1688]
### Description

When creating a new file from the sidebar and naming it anything other than "Untitled", the displayed filename on the toolbar does not update with the name change and remains "Untitled".

https://github.com/user-attachments/assets/d3005001-cc88-48af-a9d5-985cb96d11ce

### To Reproduce

1. Open a directory
2. Click `+` at the bottom left of the sidebar
3. Click "New File" and create a file with a name anything other than "Untitled"
4. The filename on the toolbar remains "Untitled"

### Expected behavior

The displayed filename on the toolbar reflects the changes made to its name in the file system.

### CotEditor version

Version 5.0.0-beta (661)

### macOS version

14.6.1 (23G93)

### Additional context

Deselecting and reselecting the file in the sidebar will update the filename on the toolbar as expected.

**Comment by 1024jp** [comment]
Thank you!
