### ISSUE TITLE
Unintended cursor movement

### ISSUE THREAD

**Issue by tatsy-ymj** [coteditor/CotEditor#1691]
### Description

In Markdown format text, clicking on any part of the text frequently causes the cursor to jump to the heading that contains the part, rather than to the point itself.

### To Reproduce

1. Open a Markdown file. 

[Markdown sample file](https://github.com/user-attachments/files/16835416/dummy.md)

2. Click anywhere in the file.

<img width="1003" alt="screenshot01" src="https://github.com/user-attachments/assets/aa4603b2-d86d-4084-8201-657bf634d565">

<img width="1003" alt="screenshot02" src="https://github.com/user-attachments/assets/890d9b35-f70e-46cd-8bc6-686c346187e5">

<img width="1003" alt="screenshot03" src="https://github.com/user-attachments/assets/b39cf814-83da-4578-a5c1-beb7c6b38121">

3. the cursor moves to the heading instead of the point

### Expected behavior

A cursor should move to the clicked point.

### CotEditor version

5.0.0-beta (661)

### macOS version

14.6.1（23G93）

**Comment by tatsy-ymj** [comment]
This phenomenon still occurs in 5.0.0 Beta3.


https://github.com/user-attachments/assets/3e4407a7-895e-4f94-8d5a-be236c37c33d

[dummy.md](https://github.com/user-attachments/files/16959811/dummy.md)

**Comment by 1024jp** [comment]
Thank you for the update. I'll investigate.

Since I could not reproduce the phenomenon in my environment (although I can roughly guess the cause), could you tell me whether the behavior changes when you:

1. Hide the Navigation Bar
2. Hide the Outline inspector

**Comment by 1024jp** [comment]
I've just added a possible workaround, and it'll be shipped with CotEditor 5.0.0-beta.4 (or rc).
After the release, let me know if the issue is solved or not.

It is still helpful to share the result of my question above on beta.3.

**Comment by tatsy-ymj** [comment]
In 5.0.0-rc, the symptoms does not occur regardless of whether Folder Navigation or Outline Inspector is hidden or not. I tried 4 patterns with the combination of Folder Navigation and Outline Inspector.
Thank you!

**Comment by 1024jp** [comment]
@tatsy-ymj Thank you for the confirmation and also for the devoted feedback while beta testing!
