### ISSUE TITLE
Open folders in sidebar, add option in settings to show sidebar at all times

### ISSUE THREAD

**Issue by bbsixzz** [coteditor/CotEditor#1693]
### Current issue

Please consider adding the option with a configurable default root folder.

### The solution you'd like

--

### CotEditor version

5.0

### macOS version

macOS Sonoma

**Comment by 1024jp** [comment]
Even though CotEditor supports the file browser in CotEditor 5.0, CotEditor is fundamentally a one-window-to-one-document style text editor. The file browser is an optional feature.
Therefore, I don't intend to add a feature that prioritizes opening folders, at least for now.
