### ISSUE TITLE
Closed file does not reopen with double-click

### ISSUE THREAD

**Issue by tatsy-ymj** [coteditor/CotEditor#1694]
### Description

Closed file does not reopen with double-click

### To Reproduce

1. Open a Markdown file with a double-click.
2. Close the window of the file.
3. Try to reopen the file again with double-click. When I try to reopen the file again with a double-click, it does not open. The file can be opened from “File” -> “Open Recent”.

### CotEditor version

5.0.0-beta.2 (663)

### macOS version

14.6.1（23G93）

**Comment by 1024jp** [comment]
Please describe the procedures more step-by-step. 
For instance, where (in which app) did you double-click?

**Comment by tatsy-ymj** [comment]
Sorry, when I uninstalled and reinstalled CotEditor, the symptom disappeared.

**Comment by 1024jp** [comment]
Thank you for the update.
Well, then, I close this issue for the moment.
Feel free to let me know if you face it again.

**Comment by tatsy-ymj** [comment]
This phenomenon still occurs in 5.0.0-Beta3.


https://github.com/user-attachments/assets/1a66e142-b891-4ffd-b633-2656b7e05ed4

[dummy.md](https://github.com/user-attachments/files/16959781/dummy.md)
