### ISSUE TITLE
Option to automatically open a previously opened file in Folder Navigation

### ISSUE THREAD

**Issue by tatsy-ymj** [coteditor/CotEditor#1695]
### Current issue

When a folder is opened in Folder Navigation, no file is selected.

### The solution you'd like

 I would like to have an option to automatically open a file that was previously selected in Folder Navigation.

### CotEditor version

5.0.0-beta.2 (663)

### macOS version

14.6.1（23G93）

**Comment by 1024jp** [comment]
Hmm, to realize it, we need to save the state somewhere.
Some IDEs automatically create a hidden setting file at the directory for such a purpose; however, by CotEditor, I'd like to prevent this approach to avoid making the user's storage dirty.
So let me reject this request (at least, at the moment).
