### ISSUE TITLE
I should open everything if I use close button

### ISSUE THREAD

**Issue by iosysjoshuajeon** [coteditor/CotEditor#1696]
### Current issue

if I close this app in close button, my opened file is gone and I should have to open all of things again

how can I fix it?

### The solution you'd like

click close button -> opened file gone -> have to open all again

### CotEditor version

4.8.7 (657)

### macOS version

14.6.1

**Comment by 1024jp** [comment]
It is not the way to quit an application in macOS.
When you close a document, the document is close.
To quit an application in macOS properly, either perform the Quit CotEditor command in the CotEditor menu or perform the <kbd>Command</kbd>+<kbd>Q</kbd> shortcut.
