### ISSUE TITLE
Scripts don't work for text in file selected in Folder Navigation

### ISSUE THREAD

**Issue by tatsy-ymj** [coteditor/CotEditor#1705]
### Description

Scripts don't work for text in a file selected in Folder Navigation.

### To Reproduce

1. Select any text file in Folder Navigation.
2. Select any text and run the following script file.

```
#!/usr/bin/env ruby -Ku
#%%%{CotEditorXInput=Selection}%%%
#%%%{CotEditorXOutput=ReplaceSelection}%%%

text = ""
while line = $stdin.gets
  print "*" + line + "*"
end
```

3. An error message appears saying that the input source document could not be found.

<img width="819" alt="スクリーンショット 2024-09-12 9 47 38" src="https://github.com/user-attachments/assets/73677fab-a3b7-454a-b1bd-b4d71ccf1444">

### CotEditor version

5.0.0-beta.3 (664)

### macOS version

14.6.1（23G93）

**Comment by 1024jp** [comment]
Thank you! It will be fixed in the next version.
