### ISSUE TITLE
Snippet variable not highlighting

### ISSUE THREAD

**Issue by stonechoe** [coteditor/CotEditor#1708]
### Description

<img width="712" alt="Screenshot 2024-09-15 17 02 12" src="https://github.com/user-attachments/assets/553ad081-32ea-4f77-84d1-e1082e19972a">
<img width="712" alt="Screenshot 2024-09-15 17 02 15" src="https://github.com/user-attachments/assets/f29905d2-9563-4b86-ba07-dae738d96b61">

### To Reproduce

1. Go to 'Settings' > 'Snippet' > 'Command'
2. See 'Insertion format:'

### Expected behavior

variables like `<<<CURSOR>>>` should be highlighted just as 'File Drop' snippet setting.

### CotEditor version

5.0.0-rc

### macOS version

15.0(24A335)

**Comment by 1024jp** [comment]
Ahaa! Thank you for the report!
