### ISSUE TITLE
等幅フォント(Osaka mono 18pt)で句読点がずれる

### ISSUE THREAD

**Issue by deasuke** [coteditor/CotEditor#1710]
### Description

![image](https://github.com/user-attachments/assets/1bbb1f0d-f9fe-4e7b-bd87-f02c39dbf806)
図のように、句読点だけ幅がずれます。

### To Reproduce

Osaka mono 18ptに設定して下記テキストをmono spaceモードで表示

```
12345678901234567890
１２３４５６７８９０
、、、、、、、、、、
。。。。。。。。。。
```

### Expected behavior

すべてのテキストの幅がそろうこと。

### CotEditor version

4.8.7(657)

### macOS version

14.5

**Comment by deasuke** [comment]
一端 Monacoしてから、Osaka Regular → Osaaka Regular Monoにするとずれが是正されることがありますが、新規作成したり、閉じて開きなおすとまた、ずれます。

**Comment by 1024jp** [comment]
うーん、こちらの環境では問題なく表示されますね。
念の為お使いのOsaka一等幅のフォント情報を教えていただけますか？ 標準で入っているFont Book.appで見られます。

<img width="775" alt="Screenshot 2024-09-16 at 21 15 57" src="https://github.com/user-attachments/assets/b8a8b54d-305d-400b-99e4-c9f0fe13449b”>


<img width="938" alt="Screenshot 2024-09-16 at 21 17 58" src="https://github.com/user-attachments/assets/73a74b56-1b77-4d76-81da-f9ea7876511f">

**Comment by deasuke** [comment]
![image](https://github.com/user-attachments/assets/febf8a24-af56-4cfb-b93d-fa9ef5f5835f)
これで良いでしょうか?

**Comment by deasuke** [comment]
setting>mode>general>fontをmonoにしてみましたが、ずれは再現せず。

**Comment by 1024jp** [comment]
検証ありがとうございます。

基本的にはフォールバックフォント（指定のフォントに当該文字がなかった際に代理で使われるフォント）が効いているのだと想像しています。
その上で、システム収録のOsaka Monoであれば「。」「、」は入っているはずなので

1. 使用しているOsakaフォントが壊れている
2.  フォールバックフォントが適切でない

のどちらかが有力です。

> これで良いでしょうか?

フォントの情報が見たいです。「i」で表示される、フォントのバージョンなどをおさめてください。

また、暗黙のフォールバックフォントの可能性として、システム設定の中の言語設定が気になります。
macOSには言語の優先順位を設定できます。
英語をお使いのようですが、英語以下はどうなっていますか？ 直後に日本語が来ますか？ 直後に日本語がない場合は直後を日本語にすると変わりますか？

<img width="827" alt="Screenshot 2024-09-21 at 17 09 00" src="https://github.com/user-attachments/assets/cb5655fe-503f-4651-8703-321df6e5b1a3">

**Comment by 1024jp** [comment]
> 直後に日本語がない場合は直後を日本語にすると変わりますか？

と、聞いてしまいましたが@deasukeのマシン上ではもうズレの不具合は発生していない状況なんですね、おそらく。

再現性がなさそうなので一旦クローズします。
今後の参考になるので、もし上記の私からの質問は教えていただけると幸いです。

**Comment by deasuke** [comment]
すいません。再現できなくなってしまったので、何かを変化させると、という質問にはお答えできなくなってしまいました。
再現していた状態では、句読点の直後が日本語でも半角数字でもずれていました。

**Comment by 1024jp** [comment]
情報ありがとうございます。
