### ISSUE TITLE
Donation feature difficult to find

### ISSUE THREAD

**Issue by gingerbeardman** [coteditor/CotEditor#1713]
### Current issue

Can only donate through Mac App Store version of the app

### The solution you'd like

Donation link could be added to GitHub and website

### Alternatives you've considered

Use Mac App Store version

### CotEditor version

5.0

### macOS version

14.7

### Additional context

Make it easier for people to donate

**Comment by gingerbeardman** [comment]
I found it in the GitHub version.

**Comment by 1024jp** [comment]
Thank you!
