### ISSUE TITLE
Powershell Support

### ISSUE THREAD

**Issue by dannymayer** [coteditor/CotEditor#1714]
### Current issue

Ex. I'm always frustrated when [...]
I would like to edit powershell scripts

### The solution you'd like

Add support for powershelgl syntax and the .ps1 file extension. CotEditor currently prompts to open the file in an external editor

### Alternatives you've considered

I have added a powershelgl syntax profile but cannot edit the powershell files due to lack of support for the file extensions.

### CotEditor version

5.0

### macOS version

10.15

**Comment by 1024jp** [comment]
duplicated #1714
