### ISSUE TITLE
The Doc Window doesn't remember its last position anymore

### ISSUE THREAD

**Issue by ndxyz00** [coteditor/CotEditor#1719]
The doc Window doesn't remeber the last position anymore.

Opening a file or creating a new one always default on opening it on the far left of the screen. There is no default position and opening and closing document in different positions doesen't matter. There is no setting for it either.

I expect the app to remeber the default open position and the last position where each document was last closed.
It was like this not so long ago, but at some point recently the behavior was lost.

In fact the reason i picked up this app is because i wanted the file to open "centered" instead of the textedit nonsensical always left, and now here it is again....

What happened?

I know each person has different opinions of what is important, but i can't work like this...

### CotEditor version

5.0

### macOS version

15.0

**Comment by 1024jp** [comment]
Thank you for the report. I have hard the same phenomenon also from another user.
I have no clue yet, but it would occur under specific conditions.
Let me investigate.

**Comment by ndxyz00** [comment]
ok, thanx, 
let me know if  you need more info...

**Comment by ndxyz00** [comment]
Hi, 
I decided to try to delete the app and all the prefs, and reinstall...
now the window doc is centered at lauch but still don't remeber the position if I move it and save the document...

Could the problem be related to the fact the I moved the app to a folder different than the appliaction folder?

I was using the app store vesion, now I downloaded the app from the website...

**Comment by 1024jp** [comment]
Thank you for the further information.
After my investigation, I found this is a kind of bug on the Apple framework side.
So, I'll add a workaround to the next version, CotEditor 5.0.3, which will be released in mid-October.

**Comment by ndxyz00** [comment]
thank you!

**Comment by ndxyz00** [comment]
it isn't fixed for me as well...

**Comment by 1024jp** [comment]
Oops, sorry. I added another measure to the next version. Thank you for your feedback.
