### ISSUE TITLE
CotEditor in 'folder mode' can't open text files with unusual extensions

### ISSUE THREAD

**Issue by stonechoe** [coteditor/CotEditor#1720]
### Current issue

When I open folder in new CotEditor 5.0.0, I can't open text files with unusual extensions.

For example, I can't open text files end with my custom file extension(`*.ir`).

<img width="752" alt="스크린샷 2024-09-22 06 05 56" src="https://github.com/user-attachments/assets/0887dbfa-1a0b-4c38-857f-7f6071ce27df">

### The solution you'd like

I want the editor to check whether a file is text or not using the same way used when opening file directly.

### CotEditor version

5.0.0

### macOS version

15.0(24A335)

**Comment by 1024jp** [comment]
Thank you for the feedback.
As quick improvements, I added the following changes to CotEditor 5.0.1:
- Add the “Open as Plain Text” button to the preview view for the file browser.
- Open a file selected in the file browser as plain text when the default app set in the Finder for it is CotEditor.

I'll brush up more in future updates to switch the editor and preview more flexibly.
