### ISSUE TITLE
ナビゲーションバーの表示/非表示の不具合

### ISSUE THREAD

**Issue by pneumoniae** [coteditor/CotEditor#1724]
### Description

ナビゲーションバーを表示もしくは非表示にしても1回の操作では表示・非表示にならない。

### To Reproduce

1. メニューの「表示」から「ナビゲーションバーを表示（非表示）」をクリックする。
2. 現在開いているウインドウのナビゲーションバーは非表示（表示）されたまま。
3. もう一度「ナビゲーションバーを表示（非表示）」をクリックする。
4. ナビゲーションバーの表示が現れる（消える）。
5. 別のファイルを開く。
6. ナビゲーションバーが非表示（表示）の状態になる（前の操作の結果が反映されていない）。

「ナビゲーションバーを表示（非表示）」をクリックして、再度クリックせずにファイルを閉じ、再度開くとナビゲーションバーは表示（非表示）状態になっている。

### Expected behavior

「ナビゲーションバーを表示（非表示）」をクリックしたら、今開いているウインドウのナビゲーションバーが表示（非表示）状態になる。

### CotEditor version

5.0.1 (678)

### macOS version

macOS バージョン15.0（ビルド24A335）

**Comment by 1024jp** [comment]
ありがとうございます。
完全にケアレスミスです。
CotEditor 5.0.2で修正されます。

**Comment by pneumoniae** [comment]
ご確認ありがとうございます。
修正よろしくお願いします。
