### ISSUE TITLE
Show/hide invisibles icon in the Toolbar

### ISSUE THREAD

**Issue by rkopicki** [coteditor/CotEditor#1725]
### Current issue

The "Show invisible characters" and "Hide invisible characters" icons in the (customized) Toolbar reflect what they do when pressed, but not the current state - the icon shows the opposite of the actual state.

### The solution you'd like

It would be better if the icon acted as an on/off switch that reflected the state of the feature, with a single tooltip text saying "Show or hide invisible characters".

### CotEditor version

5.0.1

### macOS version

14.7

**Comment by 1024jp** [comment]
There is always discussion about switches that represent states, but CotEditor has consistently tried to indicate “the operation or state that occurs when the button is pressed,” and the invisible character button follows that rule.

I believe this is the proper manner on macOS.
For instance, the Mute toolbar button in Mail.app also follows this rule.

**Comment by rkopicki** [comment]
I understand your point. However, I would personally prefer the "Invisibles", "Line Wrapping" and "Indent Guides" toolbar items to be more like e.g. "Bold", "Italics" or "Underline" (in Mail) with one icon shape accented with a color corresponding to the current state.

Thanks anyway for your reply.

**Comment by 1024jp** [comment]
> one icon shape accented with a color corresponding to the current state.

The problem with using color to indicate status is that it is difficult to convey information to people who have difficulty with color discrimination.
(From that point of view, I feel the current “Indent Guide” button should also be improved.)
