### ISSUE TITLE
Unable to hide Navigation bar

### ISSUE THREAD

**Issue by space-esquire** [coteditor/CotEditor#1727]
### Description

It takes two clicks to hide it and it pops right back up after moving it to the background and foward again. I am on the newst Sequoia version (app store), otherwise love all the other new updates :)

### To Reproduce

1. Go to view
2. Click on hide navigation bar twice

### CotEditor version

5.0.1

### macOS version

Sequoia

**Comment by 1024jp** [comment]
Duplicated #1724
