### ISSUE TITLE
Duplicate directories are displayed after creating a new directory from the sidebar

### ISSUE THREAD

**Issue by kymmt90** [coteditor/CotEditor#1729]
### Description

When creating a new directory from the sidebar, two directories appear as if the created directory is duplicated, but in fact, there is only one directory.

https://github.com/user-attachments/assets/8e141a8b-5080-4395-a65b-053325ffb22d

The directory tree on the file system after the above operation:

```
coteditor-test
├── test-dir
│   └── test2.md
└── test.md
```

### To Reproduce

1. Open a directory in CotEditor
2. Create a new directory from `+` on the sidebar and name it
3. Two directories with the same name are displayed on the sidebar

### Expected behavior

A directory tree with the same structure as the one on the file system is displayed on the sidebar.

### CotEditor version

5.0.1 (678)

### macOS version

15.0

**Comment by 1024jp** [comment]
Thank you for the bug report!
This must be a bug on CotEditor 5.0.1, and will be fixed in the next version, which will be released this week.
