### ISSUE TITLE
Unable to permanently hide the navigation bar

### ISSUE THREAD

**Issue by sh2sg** [coteditor/CotEditor#1730]
### Description

I can only hide it in the current tab, it will reappear when I open a document in a new tab or window, or relaunch CotEditor.

### To Reproduce

1. Open CotEditor
2. Toggle "View / Hide Navigation Bar" twice to hide it
3. When opening a new tab or window, the navigation bar reappears

### Expected behavior

"Hide Navigation Bar" setting should be remembered. It should only appear when I use split editor

### CotEditor version

5.0.1 (678)

### macOS version

macOS Sequoia (15.0)

**Comment by 1024jp** [comment]
duplicate #1724
