### ISSUE TITLE
Text Encoding disappeared from the Status Bar

### ISSUE THREAD

**Issue by sh2sg** [coteditor/CotEditor#1731]
### Current issue

I miss having Text encoding display/switch/convert and Syntax switch on the status bar.

### The solution you'd like

Allow text encoding and syntax switching on the status bar.

### CotEditor version

5.0.1 (678)

### macOS version

macOS Sequoia (15.0)

**Comment by 1024jp** [comment]
Thank you for the report.
The issue will be fixed in the next version.
