### ISSUE TITLE
Hide navigation bar permanently

### ISSUE THREAD

**Issue by msgx** [coteditor/CotEditor#1732]
### Current issue

Currently, I can hide the **navigation bar** from the top menu but only for the current tab and only in the current session. I don't use this bar at all (and it wastes screen space), so I prefer to keep it hidden.

### The solution you'd like

In settings, it would be nice to have an option to hide navigation bar permanently.

### CotEditor version

5.0.1 (678)

### macOS version

15.0 (24A335)

**Comment by 1024jp** [comment]
duplicate #1724
