### ISSUE TITLE
CotEditor always starts with last opened file

### ISSUE THREAD

**Issue by emikaadeo-git** [coteditor/CotEditor#1735]
### Description

No matter what I choose in settings:
<img width="514" alt="Zrzut ekranu 2024-10-2 o 09 05 04" src="https://github.com/user-attachments/assets/6f7ffef7-4869-4fce-a08a-8a2319e171a8">
app always starts with last opened file.

### CotEditor version

5.0.2

### macOS version

15.0

**Comment by 1024jp** [comment]
Could you share the following information?

1. Does the issue still exist when you quit and relaunch CotEditor multiple times after turning off the "Reopen windows from last session" option?
2. Do you enable Auto Save with Versions in CotEditor?
3. Do you turn on iCloud Document for CotEditor?
    - You can check it in System Settings > Apple Account > iCloud > iCloud Drive > Apps syncinc to iCloud Drive

**Comment by 1024jp** [comment]
Thank you for the reply.

> I don't have "Reopen windows from last session" enabled but I relaunch CotEditor multiple times and the issue seems to go away.

Ok, that's good to hear.

I have to say that this is a specification.
CotEditor uses a feature of the macOS system for reopening windows from the last session window. Contrary to intuition, the setting change takes effect only after two restarts after making the setting change.
