### ISSUE TITLE
bar to split editor always visible, wont dissapear

### ISSUE THREAD

**Issue by akarsai** [coteditor/CotEditor#1736]
### Description

i love coteditor for its simplicity. 
recently, for some reason, at the top of the window, a bar with a single button to split the editor has appeared. 
i would really like to get rid of this bar, as it annoys me visually.
i suspect this is a bug, since the bar appears randomly on some documents.

![the annoying split editor bar](https://github.com/user-attachments/assets/b46d46f3-e235-410a-b857-a1f9cccd51d2)

### To Reproduce

i do not have a reliable method to reproduce the issue.

### CotEditor version

5.0.2 (680)

### macOS version

15.1 Beta (24B5055e)

**Comment by 1024jp** [comment]
Perform the View > Hide Navigation Bar command in the menu.
