### ISSUE TITLE
Make it easier to open folders in the side bar

### ISSUE THREAD

**Issue by gingerbeardman** [coteditor/CotEditor#1737]
### Current issue

When opening folders using the mouse in the sidebar you can only use the chevron arrow

### The solution you'd like

- allow interactions on entire row
  - double click on the icon
  - double click on the folder name
  - double click anywhere on the row
  - etc

### Alternatives you've considered

- open using keyboard right cursor key

### CotEditor version

- 5.0.2 (680)

### macOS version

- 14.7

**Comment by 1024jp** [comment]
Thank you for the nice suggestion!
I totally forgot to care about it.

I've just changed to toggle folders by double-clicking a row.
The change will be applied to the next version, CotEditor 5.0.3.

**Comment by gingerbeardman** [comment]
Arigatou!
