### ISSUE TITLE
Want to have a better syntax choosing experience.

### ISSUE THREAD

**Issue by xycabcd** [coteditor/CotEditor#1738]
### Current issue

It's really good using CotEditor, but I'm having a hard time finding the correct syntax in the choosing tab. And it would be even worse for people having eye issues.

### The solution you'd like

A list that looks bigger, searchable, and you can pin syntaxes if you want. Probably in sidebar.

### CotEditor version

N/A

### macOS version

N/A

### Additional context

Thank very much!

**Comment by 1024jp** [comment]
Sorry, but I'd reject your request.

> A list that looks bigger, 

The current size is the standard size defined by the UI framework for macOS. The other sizes are not recommended. So, CotEditor keeps using the current size.

> searchable,

The syntax menus support type-selecting, the feature of selecting an item in a menu by typing the first few letters while opening the menu.

> and you can pin syntaxes if you want. Probably in sidebar.

The syntax menu in the toolbar already has a feature to keep the last used items at the top.
In addition, putting syntax selection (?) in the sidebar is not a macOS UI pattern.
