### ISSUE TITLE
A new "untitled document" is created on each launch of the app

### ISSUE THREAD

**Issue by vbadeasv** [coteditor/CotEditor#1739]
### Description

A new "Untitled" document is created on each launch of the app. So on first launch (assuming no untitled doc is already present) you'll get an "Untitled" doc, on the second launch a new "Untitled 2" is created, on the third a new "Untitled 3" is created, and so on...

Please check [this video](https://youtu.be/okGOyPkY064) to see the aforementioned behavior.

### To Reproduce

1. Get the CotEditor code and build it in Xcode.
2. Run CotEditor, from Xcode, and open at least one document (from disk).
3. Close the app and run it again. You'll get an unexpected "Untitled" document created
4. Close the app and run it again. You'll get an "Untitled 2" document created
5. Close the app and run it again. You'll get an "Untitled 3" document created and so on...

### Expected behavior

If there is already a document opened in the app, no other "Untitled" document is created when launching the app. 

### CotEditor version

5.0.2

### macOS version

Sequoia 15.0.1

### Additional context

Some things that might help you:
* I'm able to reproduce this issue by building the app (and running it) in Xcode (commit 7d7287bb1ca9ca7faf517eaa24240ec9de69c51e). The issue is NOT reproducible when running the App Store version of the app - v5.0.2 (680) . However, not being able to reproduce the issue in the App Store version might be just something temporarily -> saying this because a user of mine (I'm a developer, too) reported the issue in one of my apps, but as is the case with CotEditor, I'm not able to reproduce the problem in the App Store version of my app, but I'm able to reproduce when running in Xcode.
* I assume issue this has something to do with the concurrent opening of the documents in Sequoia, because if I return `false` for `NSDocument.canConcurrentlyReadDocuments` then the issue is no longer reproducible.

**Comment by 1024jp** [comment]
This is a known issue, and as you mentioned, it happens only when the app is built and run from Xcode.
I understand it is annoying (as it's annoying also for me), but I have found no better way so far to avoid showing the Open dialog on launch, even with various user environments (Auto Save, iCloud Document, `NSQuitAlwaysKeepsWindows`, etc...).

> NSDocument.canConcurrentlyReadDocuments then the issue is no longer reproducible.

This means turning off the concurrent document reading. There is a side effect.
