### ISSUE TITLE
Allows users to set their own base colors。 Accent Color

### ISSUE THREAD

**Issue by feinir** [coteditor/CotEditor#1740]
### Current issue

Currently, the background color of the UI is a green theme。

### The solution you'd like

Currently, the background color of the UI is a green theme, which should be allowed to be set by the user. Not everyone likes green. ^_^
Like this:
<img width="1113" alt="Cat2024-10-08 12 04 17" src="https://github.com/user-attachments/assets/afa862dd-dc54-4845-9523-a56878c4710d">

<img width="1037" alt="Cat2024-10-08 12 04 54" src="https://github.com/user-attachments/assets/5e0881c1-e27c-4c82-b2a7-a4a512e4f36c">

Perhaps a set of commonly used colors can be provided for the user to choose from.
Like this:
<img width="798" alt="Cat2024-10-08 12 06 23" src="https://github.com/user-attachments/assets/6d1e0229-cfe7-448c-9b6b-acc53bf5efb8">

### CotEditor version

5.x

### macOS version

15

**Comment by 1024jp** [comment]
Such an option should not be provided at the application level.
If the user wants to turn off the app-specific accent color, set it in System Settings > Appearance > Accent color.

<img width="827" alt="Screenshot 2024-10-13 at 11 00 55" src="https://github.com/user-attachments/assets/ebb9a672-8a9f-4ca2-90f4-e45cda1a6397">
