### ISSUE TITLE
フォント変更後にフォルダナビゲーションを使って別のファイルを選択するとクラッシュする

### ISSUE THREAD

**Issue by pneumoniae** [coteditor/CotEditor#1742]
### Description

フォントを変更し、フォルダナビゲーションを使って別のテキストファイルを開くとアプリがクラッシュする。

### To Reproduce

1. 適当なフォルダを開く
2. フォルダ内の適当なファイルを選択する
3. メニューバーの「設定…」を開く
4. 「外観」でフォントを変更する
5. フォルダナビゲーション（サイドバー）から、現在開いているファイルと同じフォルダ内にある別のファイルをクリックして切り替える
6. アプリがクラッシュする

### Expected behavior

新しく設定したフォントで、フォルダナビゲーションを使って別のテキストファイルを開くことができる

### CotEditor version

CotEditor: 5.0.2 (680)

### macOS version

macOS バージョン15.0.1（ビルド24A348）

### Additional context

ステップ2をとばして書類未選択の状態でフォントを変更した後にファイルを選択してもクラッシュします。

**Comment by 1024jp** [comment]
コメント遅くなりました。
なんとも渋いクラッシュ発見いただきありがとうございます。

この修正は数日内にリリースするCotEditor 5.0.3で修正されます。

**Comment by pneumoniae** [comment]
ご連絡ありがとうございます。
自分でも二度とこの操作はしないだろうなと思いつつ、レポートをあげさせていただきました。
修正よろしくお願いします。
