### ISSUE TITLE
Highlight tabs with edits/changes

### ISSUE THREAD

**Issue by thenktor** [coteditor/CotEditor#1743]
### Current issue

Hi,

when looking at the tabs I cannot see, which ones contain edits/changes. Only the title bar says "edited".

### The solution you'd like

Editors like Sublime Text or Zed highlight tabs with a dot, when it contains edits/changes.

<img width="532" alt="Screenshot Zed" src="https://github.com/user-attachments/assets/b949942c-7e38-41e3-a1e8-1c9097437945">

### CotEditor version

5.0.2

### macOS version

15.0.1

**Comment by 1024jp** [comment]
duplicate. See the discussion in issue https://github.com/coteditor/CotEditor/issues/1441.
