### ISSUE TITLE
"New File/Folder" are disabled when the focus is on a document

### ISSUE THREAD

**Issue by skw398** [coteditor/CotEditor#1744]
### Description

When the focus is on a document, "New File/Folder" in the "+" button menu are disabled.
Those in the context menu are enabled even when the focus is on a document.

<img src="https://github.com/user-attachments/assets/3923f089-9497-41e4-8c04-c40f269e217a" width="320">
<img src="https://github.com/user-attachments/assets/10e143de-2d5c-45ae-92b5-2396db796ac7" width="320">

Thank you!

### To Reproduce

1. Focus on a document
2. Click on the "+" button

### CotEditor version

5.0.3 (682)

### macOS version

14.7（23H124）

**Comment by 1024jp** [comment]
@skw398 Thank you for the report! I fixed it for CotEditor 5.0.4, which will be released next week (probably).
