### ISSUE TITLE
Allow bold/italic in syntax formatting

### ISSUE THREAD

**Issue by Tekl** [coteditor/CotEditor#1745]
### Current issue

Currently, CotEditor only uses one font and style. It would be great if a Format can tell the Editor to highlight keywords in bold and/or italic. This would especially great for Markdown to emphasize headlines with a bold style. In other file formats it would be great to have italic comments.

### The solution you'd like

Either let a format allow to select a style or add bold and italic checkboxes beside the color fields in the appearance settings.

Here is a quick mockup, how it could look like:

<img width="750" alt="CotEditor 000343" src="https://github.com/user-attachments/assets/afe0a763-c865-49c9-a648-dc0ac0927338">

### CotEditor version

5.0.3

### macOS version

15.1 Beta 7

**Comment by 1024jp** [comment]
Thank you for the suggestion.

However, Currently, CotEditor intentionally does not include text styling in the theme for performance reasons. I'll re-consider it when CotEditor migrates the text rendering engine from TextKit 1 to TextKit 2.

For further information, see discussion in #814.
