### ISSUE TITLE
Find & Replace Prompt Shows Question Marks Instead of Characters

### ISSUE THREAD

**Issue by denevin** [coteditor/CotEditor#1746]
### Description

After typing text into the search field of Find & Replace prompt, the characters are shows as question marks instead of the types characters. Text matching functionality seems to be working, copy pasting the question marks into another editor restores
original characters.

I added additional info to closed https://github.com/coteditor/CotEditor/issues/1435 finding.

### To Reproduce
See https://github.com/coteditor/CotEditor/issues/1435 finding

### CotEditor version

5.0.2

### macOS version

14.7

### Additional context

**Comment by 1024jp** [comment]
Thank you for another post.
But I'm still not succeeding in reproducing this issue.

I guess this can occur after inputting a specific character (or character combination).
Please let me know if you know after which text was typed it occurred.
