### ISSUE TITLE
Folder Navigation shows empty folder if contains alias links

### ISSUE THREAD

**Issue by Babelfisch** [coteditor/CotEditor#1747]
### Description

In some cases, the Folder Navigation of CotEditor 5 shows an empty folder even though the folder contains visible files. I guess that this is because of the mixed content with real files and alias links contained in the folder.

This is what CotEditor shows:

<img width="995" alt="Bildschirmfoto 2024-10-19 um 12 08 04" src="https://github.com/user-attachments/assets/ef7b4c23-6a4c-470a-a193-ba4d6db7ad42">

And this is the content of the config folder in Finder:

<img width="1033" alt="Bildschirmfoto 2024-10-19 um 12 09 28" src="https://github.com/user-attachments/assets/8687a142-3aff-4115-b9f7-ae05c8781cb9">

### To Reproduce

See above

### Expected behavior

I expect to see all files or at least the real files.

### CotEditor version

5.0.3 (682)

### macOS version

macOS Version 15.0.1 (Build 24A348)

**Comment by 1024jp** [comment]
Thank you for the feedback.
Although it seems to be a bug on the CotEditor side, I couldn't reproduce it in my environment.

1. Could you make a minimum example to reproduce the issue?
    - For instance, what happens if a folder contains one real file and one alias file, and what happens if only the real file is removed from the folder?
1. How did you make the alias links?

**Comment by Babelfisch** [comment]
1. I can do this next week.
2. The symlinks are created on shell like this `ln -sFf /source/config/file.txt /target/config`

**Comment by 1024jp** [comment]
I've probably identified the issue you’re experiencing.
If a folder contains a symbolic link to a missing file, the folder’s contents will be empty.
I’ve resolved this issue in the upcoming version of CotEditor, version 5.0.6.

If this doesn’t apply to your situation, please let me know after testing your current issue with version 5.0.6.
The new version is scheduled for release in a few days.
