### ISSUE TITLE
Cannot insert current date and time into CotEditor

### ISSUE THREAD

**Issue by stl-victor-sudakov** [coteditor/CotEditor#1751]
### Description

I was trying to follow the advice in https://github.com/coteditor/CotEditor/issues/358 but there is no SampleScript item under the script icon in the CotEditor menu bar. All I have there is "Open Scripts Folder". The path ~/Library/Application Supports/CotEditor/ does not exist either.

### To Reproduce

1. Click on the script icon in the CotEditor menu bar.
2. You will see only the "Open Scripts Folder" option.

### Expected behavior

I expected to find the date and time insertion script as described in https://github.com/coteditor/CotEditor/issues/358 

### CotEditor version

CotEditor 5.0.3

### macOS version

Sequoia 15.1

### Additional context

I usually use a shell command in vim to insert date and time, like `:r !date`, can I have something as simple as that in CotEditor?

**Comment by stl-victor-sudakov** [comment]
Just noticed there is ~/Library/Application Scripts/com.coteditor.CotEditor/ directory but it is empty.

**Comment by 1024jp** [comment]
You need to script scripts (or put the sample scripts) by yourself. See the Help > CotEditor Scripting Guide for details.

**Comment by stl-victor-sudakov** [comment]
@1024jp You mean that the sample script for date/time insertion is no more available?
