### ISSUE TITLE
Cannot save Notes.app’s attachments

### ISSUE THREAD

**Issue by kusazh** [coteditor/CotEditor#1752]
### Description

Add a text file as an attachment to Apple’s Notes.app, then double-click to open it with CotEditor. In this case, the opened file cannot be saved (it will prompt to “Save As”).

However, if I locate this file directly in Finder and open, I can save it without issues.

### To Reproduce

1. Double-click an attachment in Notes.app
2. Press cmd+S (Save)

### CotEditor version

5.0.3

### macOS version

Sonoma 14.7.1

**Comment by 1024jp** [comment]
When double-clicking an attachment text file in Notes, it passes not the actual file but a temporal file without writing permission to CotEditor.
So, CotEditor can nothing to do.
