### ISSUE TITLE
App crashes on opening the Print dialog / プリントメニューの選択でアプリが落ちる

### ISSUE THREAD

**Issue by architshin** [coteditor/CotEditor#1753]
### Description

ファイルメニューから［プリント］を選択、あるいは、⌘Pとすると、アプリが強制終了する。
その後、アップルに送信する問題レポートが表示される。その内容は、添付ファイルの通り。
[report.txt](https://github.com/user-attachments/files/17686562/report.txt)

### To Reproduce

ファイルメニューから［プリント］を選択、あるいは、⌘P。

### CotEditor version

5.0.4 (684)

### macOS version

バージョン14.7.1（ビルド23H222）

**Comment by e-mtmt** [comment]
「CotEditor 5.0.4 (684) / macOS 14.5（23F79）」で同事象です。

**Comment by akas** [comment]
CotEditor 5.0.4 (684) / macOS 15.1 (24B83) (と CANON LIPSLX Printer Driver 10.19.19) の組合せで同様です．

**Comment by 1024jp** [comment]
Sorry for taking the time to fix it, but CotEditor 5.0.5 has now been released. It fixes this issue as well.
