### ISSUE TITLE
No full Positive and Negative lookbehind support for regex syntax highlighting

### ISSUE THREAD

**Issue by 0osh** [coteditor/CotEditor#1755]
### Description

The positive lookbehind `(?<=blah blah blah)` and the negative lookbehind `(?<!blah blah blah)` features are not fully supported, and get the whole expression marked as invalid if it's too complicated.

### To Reproduce

1. Go to `Settings...` > `Format`
2. select one of the items
3. edit
4. add a new item
5. check regex (RE)
6. type a complicated regex using positive and/or negative lookbehind
this is the monstrosity that i am using:
(?<=((\w+\s*\()|[,+\-*/=.\[])\s*(\w+\s+)?)(?<![\*/]/\s*)[a-z]\w+(?=\W)(?!\s+\w+)
(it detects variables when inside of statements or functions, etc. anywhere in c#. not when declaring or assigning)

### CotEditor version

5.0.4 (684)

### macOS version

15.2 beta 2

**Comment by 1024jp** [comment]
The regular expression syntax in CotEditor relies on the [regex engine by ICU](https://unicode-org.github.io/icu/userguide/strings/regexp.html) (as described in the Find window help).

<img width="613" alt="Screenshot 2024-11-17 at 16 09 33" src="https://github.com/user-attachments/assets/bddb1cb6-7606-426e-8e51-4ee2ed0b28ae">

That is, if the ICU’s regular expression (regex) doesn’t support a particular syntax, CotEditor also doesn’t support it. For example, the length of the possible strings matched by the look-behind pattern must not be infinite.
This is in spec and not planned to be changed.
