### ISSUE TITLE
When i press command + p to print document ,CotEditor will panic.

### ISSUE THREAD

**Issue by Leoin1** [coteditor/CotEditor#1757]
### Description

------------------------

## Environment (环境)

- CotEditor: 5.0.4 (684)
- System: macOS 版本15.1（版号24B83）
- Language: Chinese

## Short Description (简单描述)
when i press command + p to print document ,CotEditor will panic.

## Steps to Reproduce the Issue (重现问题步骤)
1.creat new window.
2.text some words.
3.press command + P to Print.
4.panic(softwere quit).
## Expected Result (期待结果)
-------------------------------------

Process:               CotEditor [38460]
Path:                  /Applications/CotEditor.app/Contents/MacOS/CotEditor
Identifier:            com.coteditor.CotEditor
Version:               5.0.4 (684)
App Item ID:           1024640650
App External ID:       870178188
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-11-12 09:51:51.4175 +0800
OS Version:            macOS 15.1 (24B83)
Report Version:        12
Anonymous UUID:        DCAF1AFD-D63A-5812-C5E0-CA3696D26252

Sleep/Wake UUID:       5E96EA84-418F-4582-817A-EE93A9591A02

Time Awake Since Boot: 72000 seconds
Time Since Wake:       884 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x00000001029c6af8

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [38460]

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread

### CotEditor version

CotEditor Version 5.0.4 （684）

### macOS version

macOS Sequoia 15.1

### Additional context

Macbook Air 15' 2024

**Comment by Leoin1** [comment]
https://github.com/user-attachments/assets/1143357d-f631-44c3-9bc4-66ef67afab2a

**Comment by Leoin1** [comment]
https://github.com/user-attachments/assets/80f6b92d-01e8-45f6-9bf5-a93b53c9e415

**Comment by 1024jp** [comment]
duplicate #1753
