### ISSUE TITLE
保存時のボタン操作、ファイル名入力が外部モニターでできない

### ISSUE THREAD

**Issue by TakMunakata** [coteditor/CotEditor#1758]
### Description

ファイルを閉じる際に「この新しい書類”名称未設定”を残しますか？」ダイアログを外部モニターで表示していると、「実行可能ファイルにする」チェックボック以外操作できない。親モニターへダイアログを移動すると操作可能で、その後は外部モニターへダイアログを移動しても操作できる。

### Expected behavior

外部モニターで最初の操作からボタン選択やファイル名の入力ができる

### CotEditor version

4.5.9 (575)

### macOS version

バージョン12.7.6（ビルド21H1320）

**Comment by 1024jp** [comment]
> 4.5.9 (575)

macOS 12に対応したCotEditroの最新版は4.5.9なのですが、現在の最新版はCotEditor 5.0.4であり、こちらのバージョンはすでにサポートを終了しています。
また最新版では報告の症状は再現できないため、本件には対応しません。
ご了承ください。
