### ISSUE TITLE
CotEditor crashes when trying to print a plain text file

### ISSUE THREAD

**Issue by adyteo** [coteditor/CotEditor#1760]
### Description

When I click "file --> print" to print a plain text file (either saved or not saved yet), the editor crashes.

### To Reproduce

1. Go to 'File'
2. Click on 'Print'

### Expected behavior

I would expect to be given the Print menu where I can select the printer

### CotEditor version

5.0.4 (684)

### macOS version

14.7.1 (23H222)

**Comment by 1024jp** [comment]
duplicated #1753

**Comment by Phate0001** [comment]
It's the same for me. As soon as you press "Command" + "P" to print, the program crashes immediately.
My Mac is running macOS Sequoia, latest version.
