### ISSUE TITLE
can support pin window top on the screen

### ISSUE THREAD

**Issue by ixqbar** [coteditor/CotEditor#1763]
### Current issue

can support pin window top on the screen

### The solution you'd like

can support pin window top on the screen

### CotEditor version

5.0.5

### macOS version

15

### Additional context

can support pin window top on the screen

**Comment by 1024jp** [comment]
CotEditor already has the feature.
You can turn it on by the Keep on Top command in the Window menu.

<img width="485" alt="Screenshot 2024-11-21 at 22 58 40" src="https://github.com/user-attachments/assets/f2ddc762-9ecb-49ea-994a-4b5df139c81f">
