### ISSUE TITLE
MacOS 12.5 support

### ISSUE THREAD

**Issue by 369px** [coteditor/CotEditor#1764]
### Current issue

I'm currently on version 4.5.9 cause newer versions don't work on my MacOS (12.5)
I love how fast this app is, you can always keep it open in the background without realizing cause it's so lightweight.
I never saw any code editor that runs better than this on MacOS. 

### The solution you'd like

I'd like to have a very lightweight version of cot editor for older macOS versions...
My computer is an Intel i3 MacBook Air 2020. Why am I not updating the OS?
I've seen a lot of old devices go waaay slower when you do it!
I'm pretty sure that would happen on mine too since it's a low end apple device.

### Alternatives you've considered

I think I can help turning version 4.5.9 into a super light version of Cot Editor that runs on older devices :)

### CotEditor version

4.5.9

### macOS version

12.5

**Comment by 1024jp** [comment]
For application stability, our policy is to always support only the two most recent macOS versions.

You can get older versions of CotEditor from our website:
https://coteditor.com/archives
