### ISSUE TITLE
System requirements too high

### ISSUE THREAD

**Issue by programmingkidx** [coteditor/CotEditor#1765]
### Current issue

Hi, I recently discovered this wonderful program and started to enjoy using it. I develop for as many versions of Mac OS as I can. I noticed that the system requirements for the newest version of CotEditor is already Mac OS 14. As someone who still uses Mac OS X I ask that the system requirements for this program be reduced. I don't think a text editor needs very high system requirements. 

### The solution you'd like

Reduce system requirements as low as possible. 

### CotEditor version

5.0.5

### macOS version

Mac OS X

### Additional context

I am still developing for Mac OS 9, but I don't expect to see CotEditor running on it.

**Comment by 1024jp** [comment]
Such environment is not the target of CotEditor. You can write your own code if you want it.

**Comment by programmingkidx** [comment]
Are you saying you would accept a patch that would allow the latest version of CotEditor to work on older versions of Mac OS X?

**Comment by 1024jp** [comment]
No. Our policy is to always support only the two most recent macOS versions.
