### ISSUE TITLE
Exit the program with a red X

### ISSUE THREAD

**Issue by herry23xet** [coteditor/CotEditor#1766]
### Current issue

Before version 5, if I clicked the red X and did not save the document, the whole program closed and is no longer active in the dock.

### The solution you'd like

Can this be reinstated, perhaps as an option in the settings?

### CotEditor version

5.0.5

### macOS version

15.1.1

**Comment by 1024jp** [comment]
I've not intentionally changed this behavior for 5.0.0 (and later).
However, as you mentioned, the current version, CotEditor 5.0.5, doesn't behave as it did before. 
That is, this can be a bug. I'll investigate.

**Comment by 1024jp** [comment]
According to my investigation, this seems to be a bug on the Cocoa side.
I’ve reported it to Apple (FB15979536) and added a workaround to the next version, CotEditor 5.0.6.

Again, thank you for the report.
