### ISSUE TITLE
Tabs behaviour 

### ISSUE THREAD

**Issue by HaimBAM** [coteditor/CotEditor#1767]
I open a folder so I obtain a window that shows the file browser in the sidebar. I can then click on a doc and open it. I would expect that if I click on a second doc it opens in a new tab as I have "always use tabs" specified in settings. But what happens is that the open doc closes and the new one opens in its place. Is this normal behaviour or a bug? THANKS!

**Comment by 1024jp** [comment]
Currently, this is (unfortunately) in spec.
I'll improve it in the future, but it may take time.
See  #1712 for disucssion.
