### ISSUE TITLE
Syntax Highlighting: JavaScript modules (.mjs)

### ISSUE THREAD

**Issue by strauhmanis** [coteditor/CotEditor#1768]
### Current issue

Hello,

The issue is that MJS files are not automatically associated with JavaScript syntax highlighting.

### The solution you'd like

Please apply JavaScript syntax highlighting to MJS files by default.

### CotEditor version

5.0.5

### macOS version

15.1.1

### Additional context

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules

**Comment by 1024jp** [comment]
Thank you for the feedback (and also for the reference).
I've just added .mjs file extension to the next version, CotEditor 5.0.6.
