### ISSUE TITLE
ダブルクリックでの文字列選択の範囲

### ISSUE THREAD

**Issue by sdr0x07b6** [coteditor/CotEditor#1769]
### Description

111,222,333
と書いて、数字部分をダブルクリックしても "111,222,333" 全体が選択されてしまいます。
.js の拡張子でファイル保存すると数字とカンマは分けてカラーリングされますが、それでも全体が選択されます。
1 の上でダブルクリックしたらカンマまでの "111" が選択されるのが期待される動作かと思います。

もし仕様でしたら、どう期待されることが多そうか、再検討いただければと思います。

### To Reproduce

1. 111,222,333 と書く
2. 111 の箇所でダブルクリックする
3. 111,222,333 全体が選択される

### Expected behavior

111 が選択される

### CotEditor version

5.0.5 (686)

### macOS version

15.1.1

**Comment by sdr0x07b6** [comment]
111, 222, 333 のようにカンマの次にスペースを入れて書くと、"111," でなく "111" と期待どおり選択されます。

**Comment by 1024jp** [comment]
フィードバックありがとうございます。

ユースケースによって機体動作が変わりうる箇所なので難しいのですが、連続する数字に挟まれるカンマは桁区切りのカンマ（や、言語によっては小数点区切り）を想定しています。
例として、以下の数字部分が10と000で分離されるのではなく10,000で一塊だと考えることが自然なことに由来します。

`10,000 km`

同じスペースなしカンマ区切りでも、

`aaa,bbb`

はaaaとbbbで別の単語と認識されます。

CotEditorはコーディング専用エディタではなく汎用のプレーンテキストエディタを指向しており、また安易に設定オプションを増やすことは避ける方針をとっているので、ニーズとしては理解するのですが、当面は現行の仕様を維持したいと考えています。

**Comment by sdr0x07b6** [comment]
方針として検討済ならそのように使いたいと思います。

たとえば CSV で数値ばかりのテーブルはよくあり、最低限カラム単位では区切られたいはずなのに不自然かなと思ってポストしました。
確かに CSV を生テキストで編集操作するケースより、ご指摘の 3 桁カンマを書くほうが多いですね。

コメントありがとうございました！
