### ISSUE TITLE
Enable Drag-and-Drop to Open Files in Empty Editor Window

### ISSUE THREAD

**Issue by zty5678** [coteditor/CotEditor#1771]
### Current issue

Currently, when opening an untitled window, dragging a file into the editor results in the display of the file's path rather than opening the file itself. 

### The solution you'd like

I would like to propose that you implement functionality that allows users to drag and drop files directly into an empty document space, automatically opening the dropped file for editing. This change would streamline the workflow for users who frequently work with multiple documents and enhance the overall usability of CotEditor.

### CotEditor version

5.0.5 (686)

### macOS version

Sonoma 14.6.1 (23G93)

### Additional context

<img width="1407" alt="image" src="https://github.com/user-attachments/assets/553c0506-c286-4ce8-939d-c6c8d50ce99b">

**Comment by ADTC** [comment]
Even if the window is not empty, I would want the dropped file to open in a new tab. We can do this in VS Code, why not in CotEditor, TextEdit or TextMate*? At least in the Tab Bar or Title Bar...

The way VSCode tackles this is to open the file in a new tab if dropped normally, and when dragging it shows a message "Hold Shift to drop in editor" which when done will alter the behavior to insert the file path in current editor.

\* The author of TextMate didn't show interest in doing this when I asked, saying _"The drag behavior can be slightly customized but not to open the file. You would want to drag it onto the dock icon to open the file."_ (Apparently this works with CotEditor as well.)

**Comment by 1024jp** [comment]
duplicated #1323

**Comment by 1024jp** [comment]
@ADTC Posting the same thing to multiple threads is not welcome.

> We can do this in VS Code,

Another text editor has another philosophy.

> why not in CotEditor, TextEdit or TextMate*?

Repeat, because this is not how macOS applications are designed.
If you really want to change it, please send your feedback to Apple.

**Comment by blimeybloke** [comment]
Why not just make it an option?

**Comment by 1024jp** [comment]
@blimeybloke  Making every feature optional would only add complexity, and that’s not what CotEditor aims to be.
