### ISSUE TITLE
Help: How to associate file extensions with Syntax

### ISSUE THREAD

**Issue by FranCarstens** [coteditor/CotEditor#1773]
Is there a way to associate file extensions with a particular Syntax?

I'm working on a project that contains js, jsx, ts, tsx files. When I click on either ts or jsx I get the "Open with External Editor | Open as Plain Text" window. Obviously, when clicking on "Open with Plain Text" neither of these default to their native syntax.

I wasn't able to find and answer in the documentation. I would like to, for example be able to associate jsx with JavaScript.

**Comment by 1024jp** [comment]
> Is there a way to associate file extensions with a particular Syntax?

You can set them by customizing available syntaxes in Settings > Format, and then go to the File Mapping pane in the syntax editor.

<img width="712" alt="Screenshot 2024-12-08 at 02 49 32" src="https://github.com/user-attachments/assets/8d8d66ae-ad1f-46f3-a6e3-14303f58bb46">
<img width="792" alt="Screenshot 2024-12-08 at 02 49 28" src="https://github.com/user-attachments/assets/a606e8c2-4c07-44a2-ad95-3133f61d4e47">


However, in the following case:

> I'm working on a project that contains js, jsx, ts, tsx files. When I click on either ts or jsx I get the "Open with External Editor | Open as Plain Text" window. Obviously, when clicking on "Open with Plain Text" neither of these default to their native syntax.

Setting custom file extensions does not work in the current CotEditor 5.0.5.
The app just tries to show the document icon with "Open with External Editor | Open as Plain Text" as you described.
This behavior will be changed in the next version, CotEditor 5.0.6, which will be released in a few days.
In the next version, the app opens files as a plain-text file if the extension is determined in a syntax.
