### ISSUE TITLE
If `cot --wait` was used to launch CotEditor, quitting CotEditor will launch it again.

### ISSUE THREAD

**Issue by ADTC** [coteditor/CotEditor#1774]
### Description

This assumes `cot` CLI tool is setup as described [here](https://coteditor.com/cot) and the System Events permission is given.

### To Reproduce

1. Quit CotEditor if running.
2. In Terminal, execute `cot -w -n` or `cot -w /path/to/a/file`.
3. Quit the launched CotEditor (Cmd-Q or right-click Dock icon and choose Quit.)
4. Observe that CotEditor launches again.

### Expected behavior

Once quit, CotEditor should not launch again without the user's invocation.

### CotEditor version

Version 5.0.5 (686); CLI 2.10.0

### macOS version

Sonoma 14.7.1 (23H222)

### Additional context

This does not happen with `cot -n`. It seems to be a problem with waiting using `-w`.

**Comment by 1024jp** [comment]
Thank you for the report.
I've just fixed it.
This undesired behavior will be fixed in the next version, CotEditor 5.0.6.
