### ISSUE TITLE
EPUB/ZIP support

### ISSUE THREAD

**Issue by Lululalu** [coteditor/CotEditor#1777]
### Current issue

I would like to be able to open and edit the internal files of an epub container, similarly to what I can do with BBEdit or Oxygen XML. Currently I am obliged to unzip and zip epubs (and rename them) everytime I want to edit them.

### The solution you'd like

I can open and edit the code of ePub files easily, as if I was dragging a folder into it.

### Alternatives you've considered

Unzipping, editing, rezipping, renaming to .epub,
Using Sigil or Calibre. They work, buuuut, buuut, there’s a reason people love simple apps like CotEdit that integrate so well with MacOS.

### CotEditor version

5.0.6

### macOS version

15.2

### Additional context

I believe there’s plenty of people out there working with epubs that would love that.

**Comment by 1024jp** [comment]
CotEditor is a plain-text editor.
Therefore, we have a policy of not handling any format other than plain text.
(For the same reason, we do not support the binary plist format.)
I have no intention of changing this policy as it is a fundamental part of the application.
