### ISSUE TITLE
Donation page can have 0 padding with some currencies

### ISSUE THREAD

**Issue by kra-mo** [coteditor/CotEditor#1780]
### Description

Making a good impression is very important when asking for money, so I feel like this is an important bug.

### To Reproduce

1. Set App Store location to a country with a currency of little value
2. Open the App Store version of the app
3. Open Settings
4. Go to Donation page

### Expected behavior

There is some horizontal padding of the page

### CotEditor version

git main

### macOS version

15.2

**Comment by kra-mo** [comment]
I would upload a screenshot, but GitHub doesn't seem to like that right now for some reason.

The issue is probably there because the size of the page changes after going to it instead of having the size with the correct currency initially.

**Comment by 1024jp** [comment]
@kra-mo Thanks. Please share screenshots when the image uploading is available again.

**Comment by kra-mo** [comment]
<img width="712" alt="Image" src="https://github.com/user-attachments/assets/0af383a4-e625-4ade-ab6a-a6c809e65a01" />

**Comment by 1024jp** [comment]
@kra-mo Thank you!
Well, I understand I need to update the layout. Let me consider.

**Comment by 1024jp** [comment]
Fixed on CotEditor 5.0.7.
