### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by busslina** [coteditor/CotEditor#1781]
### Description

On my spanish mac:
![Image](https://github.com/user-attachments/assets/06c063b3-a8a2-4673-ac3f-264509232d24)

"CotEdiotr"

### CotEditor version

5.0.5 (686)

### macOS version

15.2

**Comment by 1024jp** [comment]
Thank you for the report.
But it has already been fixed in CotEditor 5.0.6.
Please check the latest version before filing an issue.
