### ISSUE TITLE
How to Drag a File into CotEditor and Open It Directly

### ISSUE THREAD

**Issue by lycbeu** [coteditor/CotEditor#1784]
### Current issue

When I drag a file into CotEditor, it inputs the file's path and name, but that's not what I want. I hope that the file will be opened directly when I drag it into CotEditor.

### The solution you'd like

When I drag a file into CotEditor，the file will be opened instead of inputs the file's path and name.

### CotEditor version

5.0.7

### macOS version

15.1.1

**Comment by 1024jp** [comment]
Duplicate #1323

CotEditor doesn't provide this feature intentionally.
