### ISSUE TITLE
The outlines editor in the syntax editor is bugged

### ISSUE THREAD

**Issue by markjirousek** [coteditor/CotEditor#1786]
### Description

When jumping from an outline item to another to edit the **_Title pattern_** field in the syntax editor, any input is rejected (character appears for a few milliseconds before being removed). It is impossible to type in or paste anything in the field until you close all the settings (the main settings window included). This also messes the item's description or title pattern (I don't remember exactly and don't want to mess with it again) which is right above the one you are trying to edit (can be seen only after your reopen the format editor) by mixing them together.

It makes the operation of editing many existing items (no bug when creating new items on the fly) annoying and time wasting, and impossible at once.

### To Reproduce

1. In the syntax editor, select **_Outlines_**.
2. Select an item and edit its **_Title pattern_**.
3. Select another item and try to do the same.
4. It doesn't work (the item right above the selected one is in fact being messed with).
5. Close all settings.
6. Reopen the syntax editor.
7. You can again edit one item and one item only at a time.

### CotEditor version

Version 5.0.7 (690)

### macOS version

15.2 (24C101)

**Comment by 1024jp** [comment]
Thank you for the report. I’ve confirmed the phenomenon, so I’ll prioritize fixing it in the next version.

**Comment by markjirousek** [comment]
Awesome, thank you!

**Comment by 1024jp** [comment]
Fixed.
