### ISSUE TITLE
Show Hidden Files In The Sidebar

### ISSUE THREAD

**Issue by karamfd** [coteditor/CotEditor#1787]
### Current issue

When I open a folder, I cannot see hidden files in the sidebar.

### The solution you'd like

I would like to see hidden files in the sidebar so I can easily edit like any other file.

### Alternatives you've considered

At the moment, I have to open hidden files individually. I prefer seeing those files like in other text editors. You can add an option in the settings menu to show/hide those types of files so people can show/hide them as they like.

### CotEditor version

5.0.7

### macOS version

Mac OS Sequoia 15.2

**Comment by 1024jp** [comment]
CotEditor already has the feature.
You can turn on it by selecting the "Show Hidden Files" command in the context menu in the file browser.

<img width="937" alt="Image" src="https://github.com/user-attachments/assets/5127158b-bf29-4284-ba05-7dd439f89460" />

**Comment by karamfd** [comment]
Thank you for letting me know
