### ISSUE TITLE
改行を含む文字列の検索が改行コードの設定によって動作しない場合がある / Find panel doesn't match strings which include another type of line endings

### ISSUE THREAD

**Issue by niwatako** [coteditor/CotEditor#254]
改行コードがCRまたはCR/LFの状態でテキスト中からコピーした文字列を検索する時、検索対象文字列が改行を含むと、その文字列が検索にヒットしません（バージョン1.5.4で確認）。
どの改行コードの時でも改行を含む文字列を検索できると便利だと思うのですが、ご対応頂く事は可能でしょうか。

【再現手順】
改行が含まれるテキストを作成し、テキスト中の改行箇所をコピーし、Findウィンドウの「検索：」欄にペーストして検索を行います。

このとき、改行コードLFの時にコピーした改行を使って検索を行うと、LF、CR、CR/LFのいずれの改行コードのモードでも改行箇所を検索することが可能です。
しかし、改行コードCRまたはCR/LFの時にコピーした改行を使って検索を行うと、LF、CR、CR/LFのいずれの改行コードのモードでも改行箇所を検索することが出来ません。

**Comment by 1024jp** [comment]
対応が遅くなりました。

次バージョン CotEditor 2.2.0 では、検索文字列の改行コードは問わず、すべての改行コードタイプで文書内の改行にマッチするように変更しました。
厳密に改行コードも含む検索をしたい場合には依然として不便かと思いますが、
いずれにせよ現状でも正常には動いてない上、基本的な検索ニーズはこれで解決できると考え簡易的に実装いたしました。
