### ISSUE TITLE
タブ機能 / Support tab window

### ISSUE THREAD

**Issue by usami-k** [coteditor/CotEditor#26]
（http://sourceforge.jp/ticket/browse.php?group_id=1836&tid=27299 から移動）

タブ機能が付いてくれると嬉しいです。

----

タブが必要なシチュエーションって少ない人が結構多いのでは? と思うので、機能として存在している分にはかまわないのですが、使わない人への配慮があるといいと思います。
例1: 常に新規ウインドウで開くオプション 例2: タブバー非表示 etc...
タブ化されると常に1つのドキュメントしか見えない状態になるので困る場合があります。
例えば僕の場合、ウェブのコーディングで coteditor を使っているのですが、『「.css」や「.js」を見ながら「.html」を編集する』のように、他のドキュメントを見ながら作業することが多い、といった感じです。

**Comment by 1024jp** [comment]
OS X 10.12 Sierra implements system-wide tab feature!
So, this request will be realized in this year.

I need to add some more code to let CotEditor work nicely with tabbed windows, however fundamentally, it already works. I love you Apple.

**Comment by 1024jp** [comment]
The basic implementation is already done on Sierra and I've just divided remaining tasks into small issues: #577, #578. So I close this issue.
