### ISSUE TITLE
Is there any feature related to project management in CotEditor

### ISSUE THREAD

**Issue by orklann** [coteditor/CotEditor#278]
I have to mange my project which contains many files, and I can not find any project manager in CotEditor, It would be cool if CotEditor can have project management.

Please consider taking this feature, thanks very much.

Aaron Elkins

**Comment by kuthair** [comment]
Hey! GREAT EDITOR!

I'm always in search of a better text editor, and I've tried them all: atom, sublime, textmate, textwrangler....

I like Cot best. Thank you.

I too would love to see some form of a file-tree. I just want to be able to navigate between files easily, without having to go to open file dialog everytime.

Each file could remain in the same single window. You already support tabs, you could have a file-tree that opens each file in it's own tab.

Attached is a snapshot of how TextMate does it. Something similar would be perfect.

Thanks for your consideration.

<img width="693" alt="textmate" src="https://cloud.githubusercontent.com/assets/7365514/22619783/208ed4c0-eaca-11e6-97bb-9e8671011e5e.png">

**Comment by 1024jp** [comment]
The problem on CotEditor is the Sandbox requirements by Apple. A sandboxed app cannot open a file from its own UI. A file is basically needed to be opened either via the open panel or a user from Finder. 

One exception is the case when a user put a whole directory to a app. Then the application can open all files in the given directory. Like when you open a project directory. In this way, CotEditor may be able to manage a project directory and files in the directory. 

However, sorry, it is still complecated to implement (Apple also provides only few APIs to control tabbed windows and they are cumbersome) and I don't have enough time for that.

I know some users love project manager, but therefore, the priority is still low at this time point.

**Comment by eivindml** [comment]
Would like to add my voice to that request. I think the sandboxing API's from Apple changed somewhat this year, so might be better options for it.

**Comment by wuehrer** [comment]
Hello, many thanks for the development of the CotEditor.

I would like to pick up the topic Folder/Project again.

From earlier times I use the editors BBEdit or Sublime for larger HTML or Python developments. But also for Markdown diaries or documentations.

Where the project view on the files and working with files - for example fast search - are the most important differences.

Is such a function folder/project still not in focus?

I'd like to say goodbye to my "old" editors and not switch to Atom.io or anything like that - I just want native mac os apps.

Greetings from Austria!

**Comment by 1024jp** [comment]
Sorry, but I still have to say "not yet" for the answer to this question.
I'm not against the project-based file management system, but low priority for me to implement to CotEditor.

**Comment by wuehrer** [comment]
... thank you for the speedy reply and for the clarification. For me that is ok/fine :-)

**Comment by kuthair** [comment]
Any update, here?

It's been 5 years since this ticket was opened.

**Comment by 1024jp** [comment]
Sorry, but no update for this request yet.

**Comment by lojza3d** [comment]
I understand all the issues with sandboxing and everything, however, a tree browser of a project folder as mentioned here https://github.com/coteditor/CotEditor/issues/278#issuecomment-277455545 would be extremely useful. Hopefully it gets to the priority list soon ;) Thank you!

**Comment by kuthair** [comment]
@lojza3d: I got in on the Beta for Panic's new code editor: Nova. So far so good. Give it a shot.

**Comment by helmut72** [comment]
A file-/tree browser is possible in sandboxed apps. Look at Textastic or FS Notes. It would be really useful for CotEditor too, including a search bar on top to filter for file names. A tree browser should be independent to the info browser, where I use the outline view a lot.

**Comment by wuehrer** [comment]
New year ... and same question as 2 years ago ... 
I find Coteditor as a great tool, because modern, active development and M1 support. 
However, I miss unchanged, a file browser to work really well and optimally. In the side window/bar would be optimal, similar to FS Notes, iA Writer, Sublime and so on, would be a significant added value. 
The base with version 4.x would be ... How stand the possibilities in 2021, can we hope?

**Comment by helmut72** [comment]
After years trying different editors, I switched to vscode for my Notes, casual text files and other than Swift development, after fiddling out every Mac-like shortcut. I have now only 3 editors to get used to: vim in the Shell, Xcode for Swift and vscode for the rest. Unsubscribed.

**Comment by wuehrer** [comment]
Similar after years, however VScode is not an option for me (Electron & Google junk). Currently Sublime and for notes iA Writer or FS Notes. Would love to use CotEditor for this, without a file browser it makes no sense.

**Comment by gregarios** [comment]
Request: Just please make sure, for those of us wanting to keep it simple, provide a way to shut off any file management features.

**Comment by onodera-punpun** [comment]
This is the only thing stopping me from using this as my code editor, it is quite hard to not be able to open and see files easily without a kind of sidebar.

**Comment by gingerbeardman** [comment]
As a relatively new user, this is the only thing I am missing. A quick way to drop my project folder and be able to pick and choose which file I want to edit.

**Comment by mohalibou** [comment]
Is the removal of the postponed label an insinuation that this feature is planned on being added?

**Comment by 1024jp** [comment]
> Is the removal of the postponed label an insinuation that this feature is planned on being added?

Unfortunately not. It's yet nowhere in sight to implement this feature. The document-based application design on AppKit is not suitable to have this kind of structure. I know there is a way but requires a lot of effort, and therefore, the priority is still low.

**Comment by gingerbeardman** [comment]
I wonder if there is a way to create a special tab that lists files?

Then we can keep the existing app architecture.

Optionally, the special file browser tab could be docked onto one side of the window?

**Comment by 1024jp** [comment]
Then, you can use a Finder window (No, I'm just joking.

In my philosophy, I wanna implement it in a beautiful way, rather than just adding an extra control. 

This request is actually one of features I would like to work on when I got solid blocks of time. But for me now, the priorities of the following two large changes are higher:
- SwiftUI
- TextKit 2

**Comment by gingerbeardman** [comment]
Are there any recent thoughts for this?

**Comment by 1024jp** [comment]
A teaser image of the next major update to be released this fall.

<img width="951" alt="Screenshot 2024-06-29 at 11 52 16" src="https://github.com/coteditor/CotEditor/assets/1165044/64a26602-8480-47e5-a3f4-065e6f3c1e9b">
