### ISSUE TITLE
[highlight][Ruby] 行コメントの中のヒアドキュメントに影響を受けます / Comment lighlighting with here-document

### ISSUE THREAD

**Issue by jakago** [coteditor/CotEditor#285]
行コメントの中のヒアドキュメント開始ラベル（添付画像では１行目の<<EOS）の影響を受け、対応する識別子（添付画像では８行目のEOS）までが文字列扱いで色が変わってしまいます。

![eos](https://cloud.githubusercontent.com/assets/888019/5138459/987ef478-7192-11e4-80e3-484bb92e83ae.jpg)

**Comment by 1024jp** [comment]
test string

```ruby
# xml += <<EOS
#   <something />
# EOS

3.times do
  xml += <<EOS
  <anything />
EOS
end
```
