### ISSUE TITLE
Multiple cursor for block editing / マルチカーソル入力

### ISSUE THREAD

**Issue by 1024jp** [coteditor/CotEditor#307]
A feature request form #289.

At the moment, I don't have any specific plan for this feature. However, it would be nice, if CotEditor has this.
## 

いわゆる矩形入力に関するリクエスト。現時点で具体的な実装予定はないのですが、そりゃあったらいいなぁということで。

**Comment by yuhei-mukoyama** [comment]
:+1:
この機能がほしいと個人的にも最近すごく思ってるところです。
仕様としては atom の マルチカーソル Issue が参考になりそうですね。

- https://github.com/atom/atom/issues/1365
- https://github.com/atom/atom/issues/1928

**Comment by yuhei-mukoyama** [comment]
うっかり全く関係のない Atom に Issue reference 飛んじゃいました。すみません…

**Comment by 1024jp** [comment]
やっぱ欲しいですよねぇ。この件はそれなりに考えています。
現時点ではロードマップ的に CotEditor 2.2 での AppStore 対応 (とか SandBox対応とか諸々）を優先しているので、対応するとしたら 2.3 以降になります。

ただ、正直なところ Apple が提供している（そして CotEditor のコアとなるテキスト処理部分のベースとなっている）NSTextView はその辺のことはまったく想定していないので、かなり自分でコードを書いて割り込みをしないといけないであろうことが予想されます。
そういう意味で実装するのは時間がかかるかもしれません。

**Comment by yuhei-mukoyama** [comment]
はい、気長にお待ちしてます :+1:
CotEditor にマルチカーソルついたらほんと最強だと思うので、是非よろしくお願いします :bow:

**Comment by danielzilli** [comment]
:+1: 
It's a basic feature for any programmer. People coming from Textmate and Sublime cannot survive without it. :-)

**Comment by danielzilli** [comment]
Hi @1024jp any plans here?

**Comment by danielzilli** [comment]
Hello. I hope this request still in your to-do list :wink:

**Comment by 1024jp** [comment]
Yes, it's still in the list. However, it is actually hard to implement and  there is another to-dos that have higher priority, so I'm not sure when I'll start implementing this.

**Comment by danielzilli** [comment]
Understood. 
Maybe you can take a look at [textmate](https://github.com/textmate/textmate) to get some ideas. :smile:

**Comment by danielzilli** [comment]
I hope this still in your list 😉

**Comment by 1024jp** [comment]
Yes, still in the list.

However I'm not sure if I can include this feature to CotEditor 3.0 that I'm now working on.
In my plan, CotEditor 3.0 should be released before macOS Sierra is released and I may not have time to implement it in the schedule.

**Comment by danielzilli** [comment]
Any updates?

**Comment by 1024jp** [comment]
The situation does not change. It's still on the list but no specific plan yet.

**Comment by mathanimas** [comment]
Hi. Is this still on the to-do list? (BTW: Currently, this is the only feature holding me back from using CotEditor...)

**Comment by 1024jp** [comment]
@mathanimas 
Hi, it is still on the list and still under consideration.
I actually started playing with Cocoa's TextKit framework to implement this feature since the last month.
I feel it is hard and a lot of work to realize, I'm afraid (but not impossible).
So, sorry for letting you guys wait, but at least you can see this request is now at a relatively high position in the waiting queue.

**Comment by mathanimas** [comment]
Cool, thanks for this info! I'm sorry I can't contribute to the project because my codings skills are very limited. However, if you'd ever need someone for testing, you may count me in.

**Comment by 1024jp** [comment]
Today I released a beta version including this multi-cursor editing feature at [coteditor.com/beta](https://coteditor.com/beta).
Please try it and give me feedback to make it better and stable.
To report, you can create a new issue instead of posting to this thread.
