### ISSUE TITLE
Open Folders

### ISSUE THREAD

**Issue by lukaswelte** [coteditor/CotEditor#310]
The ability to open a whole folder in the Editor would be nice. Just display the file tree on the left side of the editor field as many competitors (TextMate, Sublime, Atom...) do.

**Comment by ben-ole** [comment]
too sad! I absolutely love the simplicity of this editor and would like to replace my sublime text with cotEditor, but this does not make sense unless I can open up a project in the editor. Specially the split window functionality makes more sense if you have different files inside :)

**Comment by Cezanna** [comment]
The necessity to have an other windows of a file manger to opne any file we need in a project is obvious.
I like cotEditor, but can't use it when I developp, only to modify a file 'par hasard".

**Comment by sineld** [comment]
I'd love this feature.
