### ISSUE TITLE
Menu bar duplicate Help item (located at very top of the screen) 

### ISSUE THREAD

**Issue by solidcolour** [coteditor/CotEditor#331]
1. Launch the app as first time (delete related plist files, make sure it's fresh).
2. Quit the app (cmd+q).
3. Relaunch, check for updates dialog shows up, and look for the menu bar read as CotEdit Help.
4. Click either Don't check or Check auto, and look for the menu bar, two Help item appears
5. Quit and relaunch again seems to solve the issue, but it should considered as a bug.

**Comment by 1024jp** [comment]
I found the cause of this problem.
However, because it's not easy to fix, the issue is not so critical and furthermore Sparkle support on CotEditor will be dropped on the next version (v2.2) since it will be sandboxed, I leave it as it is.

**Comment by 1024jp** [comment]
We'll support Sparkle continuously on v2.2 and higher for non-AppStore versions.
However, I've fixed this in an another way.
