### ISSUE TITLE
Replace text field accepts rich formatted text / 置換欄にリッチテキストが入る

### ISSUE THREAD

**Issue by kawanet** [coteditor/CotEditor#333]
Japanese follows English.

At "Find" panel, "replace" text field accepts rich formatted text while "find" text field accepts plain text only. It happens when coping some text from Terminal.app (of black background) to CotEditor for instance. "Replace" field should ignore rich format and accept plain text only as "find" field does.

----

検索パネルで、「検索」欄は plain テキストのみしか入らないのに、「置換」欄はリッチテキストが入ってしまいます。
例えば、Terminal アプリから CotEditor の検索・置換欄にコピペする作業をよくするのですが、検索欄にペーストしても白背景ままですが、置換欄にペーストすると黒背景・白文字になってしまいます。（Terminal アプリ側の見た目がそのまま反映されてしまう）
「検索」欄と同じように、「置換」欄でもリッチテキストの情報を無視して、プレインテキストのみをペーストできるようにして欲しいです。

**Comment by 1024jp** [comment]
Sorry for the delayed response. Meanwhile, I've also tried to reproduce this matter on OS X 10.9, but it also couldn't.

However, I changed the roadmap to introduce a brand-new find panel to CotEditor (see #336) in the near feature, and the search/replacement fields on the new panel are based on another kind of UI class. So, it will definitely be solved this issue soon.
