### ISSUE TITLE
Multiline Indent with TAB-key, outdent with SHIFT-TAB

### ISSUE THREAD

**Issue by GHubbler** [coteditor/CotEditor#334]
Thanks for this amazing and promising Editor. I like the approach of CotEditor very much. What I really miss at the moment is a indent/outdent behavior of other code editors. This means:

Without selection on pressing tab it indents text after the curser (fine, works in CotEditor, too)
Without selection on pressing shift-tab the whole line should outdent by a tab (missing)

With selection one or more lines and pressing tab CotEditor should indent the selected lines (missing, CotEditor deletes the line and replaces them with a tab character, very bad)

With selection one or more lines and pressing shift-tab CotEditor should outdent the selected lines (missing, Coteditor does nothing, not so bad, but also not so useful)

 In TextWrangler for comparison one has to check explicitly the option "Allow Tab key to indent text blocks" (Options->Keyboard-section). I have searched in CotEditor for a similar setting but found nothing so I guess it isn't available yet.

It would be great, if CotEditor could feature this indent/outdent behavior like other major editors.
What do you think?

**Comment by arminbw** [comment]
I'm using a customized German keyboard layout. I also customized my text editor, so I can use `⌥` + `⇥` for block indentation (see: [GermanDev](https://github.com/arminbw/GermanDev)).

**Comment by 1024jp** [comment]
@arminbw Danke für deinen Tipp 🍺
