### ISSUE TITLE
画面分割と強制終了

### ISSUE THREAD

**Issue by cqs00622** [coteditor/CotEditor#339]
## 環境 

- CotEditor: 2.0.3 (2.0.3)
- システム: OS X バージョン 10.10.1（ビルド 14B25）
- 言語環境: 日本語

## 不具合が発生したときに行っていた操作、または再現手順

画面右上のエディタを分割ボタンで画面分割→分割画面を閉じる（一つにする）→入力する→強制終了
ただし，メニューから分割をすると問題ないなど発生条件がありそう。
これで今日数時間の作業がパーに。

**Comment by 1024jp** [comment]
報告ありがとうございます。
再現しました上になかなかクリティカルな問題なので、次バージョンリリース前に修正します。
