### ISSUE TITLE
日本語インデントした際のスペース表示問題

### ISSUE THREAD

**Issue by ttoyama** [coteditor/CotEditor#342]
Fill the following template, and post it on [GitHub Issues](https://github.com/coteditor/CotEditor/issues) or send to <coteditor.github@gmail.com>. Please note that the contents of the sent E-Mail can be shared on the Issue page.

-----------------------------------------------

## Environment

- CotEditor: 2.0.3 (2.0.3)
- System: OS X Version 10.10.1 (Build 14B25)
- Language: English

## Short Description

command + ] によるインデントのエラー

## Steps to Reproduce the Issue

インデントする先頭行が日本語だと、インデントを行った際にスペースの幅が狭いものになる。保存して開くと等幅にもどっている。

## Expected Result

ファイルの中身としては問題無し。見た目のみ。

**Comment by 1024jp** [comment]
報告ありがとうございます。

この、日本語のテキスト編集をおこなった際に表示フォントが日本語フォントに引きずられることがある問題はこちらでも認識しており先日対策を施しました。
現在開発中の CotEditor 2.1.0 ではこの不具合はすでに修正が施してあります。
2.1.0 は、数日中にβ版を出したのちに2月中頃までには 正式版をリリーする予定ですので宜しくお願いします。

**Comment by ttoyama** [comment]
ありがとうございます。
楽しみです。
