### ISSUE TITLE
Please give back the classic shortcut for preferences...

### ISSUE THREAD

**Issue by cool8jay** [coteditor/CotEditor#343]
Every Mac OS X application assigns "command + comma"( ⌘ + , ) to its preferences..., besides, no other function is using this combination. :-)

**Comment by 1024jp** [comment]
`⌘,` is still mapped to preferences on the current CotEditor. You probably need to reset key binding setting.
To reset it, go to Preferences > Key Bindings > Menu Key Bindings, press *Restore Defaults* and press *OK* button.

**Comment by cool8jay** [comment]
Fixed, thanks.

**Comment by 1024jp** [comment]
I'm glad to hear that :)
