### ISSUE TITLE
コマンドラインツール cot が絶対パス指定で無いとファイルを開けない

### ISSUE THREAD

**Issue by Watson1978** [coteditor/CotEditor#344]
CotEditor 2.1.0-betaを試しております。

```
$ cot ./test.m
```

のようにファイルを開こうとすると"書類 xxx を開けませんでした。ファイルが存在しません。"

![](http://f.cl.ly/items/2T3A290s3Q2s021m132w/screenshot.png)

とエラー表示されます。`$ cot /Users/watson/tmp/test.m`と絶対パス指定するとファイルを開くことができたのですが、相対パスでファイルを開けるようになりませんでしょうか？

**Comment by 1024jp** [comment]
報告ありがとうございます！
ずいぶん間が抜けたミスをしてしまいました。近日中に修正をしたβ2を出します。
