### ISSUE TITLE
バージョン 2.1 β (2.1.0-beta)の検索について

### ISSUE THREAD

**Issue by ha810** [coteditor/CotEditor#345]
cmd + f にて"検索と置換"ウインドウを表示させ、検索フィールドに文字列を入力し、"すべて検索"を押しても何も起こりません。
検索しようとした文字列は例として半角"http"で試してみました。
書類中に半角"http"は含まれています。
全角の文字列でも動作はしませんでした。
「正規表現」、「大文字／小文字を無視」、「選択範囲のみ」のチェックボックスはすべてOFF。
置換フィールドには何も入力しておりません。

環境
- CotEditorのバージョン: CotEditor  2.1 β (2.1.0-beta)
- OS X のバージョン: 10.10.2
- 言語環境 : 日本語

確認箇所ございましたらご支持いただければと思います。

**Comment by 1024jp** [comment]
報告ありがとうございます。
原因を特定できたので、近日中に修正したβ2をリリースします。
目下問題を回避するときは、検索パネル内でエスケープ文字を手動で設定してください（通常は `\` です。問題が起きているときはこれが設定されていないと思います）。

![screen shot 2015-01-29 at 16 17 02](https://cloud.githubusercontent.com/assets/1165044/5953829/566f396e-a7d2-11e4-92a6-619b33ab4ba6.png)

**Comment by ha810** [comment]
承知致しました。

**Comment by 1024jp** [comment]
Fixed on 753cc2ef0f376b6f3fc3e6ce4a816653df515fb5
