### ISSUE TITLE
cot コマンドのみで新規テキストウィンドウが開いてほしい

### ISSUE THREAD

**Issue by usami-k** [coteditor/CotEditor#353]
以下の要望（or 指摘）をいただきました。

## 環境 

- CotEditor: 2.1 RC2 (2.1.0-rc.2)
- システム: OS X バージョン 10.10.2（ビルド 14C109）
- 言語環境: 日本語

## 簡単な説明

cot コマンドを引数なしで実行したときに、新規テキストウィンドウが開いてほしい。

## 不具合が発生したときに行っていた操作、または再現手順

`cot` コマンドを引数、入力なしで実行する。
（CotEditor を事前に起動していてもいなくても同じ）
（CotEditor 自体は起動して Dock に表示される）

## 期待される挙動

新規テキストウィンドウが開いてほしい。

なお、`echo "" | cot` とすれば新規テキストウィンドウが開く。

**Comment by 1024jp** [comment]
なるほど。フィードバックありがとうございます。

ただ、ウインドウを開かないでただアクティブにしたい場合もあるでしょうから、新しいオプションを追加して、`cot --new` などとした時だけ空の新規ウインドウを開くというのはどうでしょうか？ Sublime Text のコマンドラインツール `subl` なんかは同じような仕様になっています。

**Comment by usami-k** [comment]
なるほど、オプション追加というのはありですね。

Atom にも `--new-window` というオプションがありました。ただ、Sublime Text や Atom はタブエディタなので、CotEditor とは若干ニュアンスが違うかもしれませんが。

**Comment by 1024jp** [comment]
あぁそうか、彼らはタブがあるんですね。実は Sublime の方もオプション名は `--new` ではなく `--new-window` で「わざわざ window つけなくてもいいのに」と思っていたのです。

単純に OS X 的に `open -a CotEditor` などとしたときや、OS X向けの老舗の TextMate のコマンド `mate` なんかは素で投げると新規ウインドウは開かないので（環境設定でリオープンイベント時に新規書類を開くようにしていた場合は別）、OS X 的な挙動を志す CotEditor としては単なる `cot` は単にアプリケーションを呼ぶだけにしたいところです。
CotEditor が新規ウインドウオプションをつけるときに `--new` にするか `--new-window` にするかは悩むところですが（もしも遠い将来タブを実装する可能性があることまで想定すると）、ひとまずは `--new` オプションを追加してみようかなと思います。

**Comment by usami-k** [comment]
`--new` オプション了解です。

> OS X 的な挙動を志す CotEditor としては単なる cot は単にアプリケーションを呼ぶだけにしたいところです。

同意です。

若干気になる点としては、`open -a CotEditor` と `cot` で以下の違いがあります。
* 「起動時 新規書類を開く」設定のとき、`open -a CotEditor` はウィンドウを開く、`cot` は開かない
* 「CotEditor がアクティブになるとき新規書類を開く」設定のとき、`open -a CotEditor` はウィンドウを開く、`cot` は開かない

どういう仕様が良いかはちょっと迷う感じですが・・・。

**Comment by 1024jp** [comment]
ひとまず `--new` (もしくは `-n`) オプションを追加してみました。

新規書類を開く設定の挙動ですが、たしかに違いがありますね。
これは`cot` コマンドの実装の仕方に起因するものですが、
ちょうどよく`--new` オプションも追加したので、とりあえず「仕様です」と言いきっちゃってもいいかなぁ、なんて。
（私はもともと両方とも開かない設定にしているのであまり不便を感じないのですが、開く設定にしている他のユーザがどう感じるかですね）

**Comment by usami-k** [comment]
対応ありがとうございます。仕様ということで問題ないかと思います。

**Comment by yuhei-mukoyama** [comment]
:+1:
