### ISSUE TITLE
Markdownファイルのアイコン

### ISSUE THREAD

**Issue by tsurunaga** [coteditor/CotEditor#355]
## 環境 

- CotEditor: 2.1 RC2 (2.1.0-rc.2)
- システム: OS X バージョン 10.10.2（ビルド 14C109）
- 言語環境: 日本語

## 簡単な説明

使いやすいエディターをご提供いただきありがとうございます。本当に助かっています。MarkdownファイルのデフォルトアプリをCotEditorにしていますが、アイコンがBlankアイコンのままです。環境依存でしょうか。。。

## 不具合が発生したときに行っていた操作、または再現手順

2.0,3で発生していましたが、2.1RC2でも変わらずでした。拡張子をmarkdown/md/mkd等変えてみましたが変わらずでした。アイコンキャッシュをクリアーしても改善しませんでした。

## 期待される挙動

TXTファイルやCPPといった他のCotEditorファイルのように書類アイコン（/Applications/CotEditor.app/Contents/Resources/MarkdownIcon.icns）が割り当てられることを期待します。

**Comment by 1024jp** [comment]
うーん、書類アイコンが反映されない件はMarkdown以外でタイプでですがこちらの手元 (OS X 10.10.2) でも発生していて、直接的な修正方法がわからないでいます。
ただ、CotEditor側では特別なことをしておらず、標準的な方法で対応している書類タイプとそのアイコンをシステムに知らせているだけなので、
システム側の環境依存のところが大きいのではないかと考えています。

念のためですが、もしも Finder の「情報を見る」からおこなう、書類情報の関連付けをまだお試しになっていなければ試してみてください。

![screen shot 2015-02-15 at 12 08 32](https://cloud.githubusercontent.com/assets/1165044/6201939/69c9ef68-b50b-11e4-9564-d8b46c96b1ed.png)

**Comment by tsurunaga** [comment]
ご対応ありがとうございます、「情報を見る」も試しているのですが状況は変わりませんでした。
試しにmdファイルを他のアプリに関連付けても、アイコンはBlankのままでした。3台あるMacのうちXcodeをインストールしている1台は正常にMarkDownアイコンが割り当てられているので、そのあたりも関係しているかもしれませんね。

**Comment by 1024jp** [comment]
なるほど、Xcodeをインストールしているマシンのみ。
ちょっと心当たりがあるので定義を追加してみます。
うまくいくかわかりませんが改善するかもしれません。
有益な検証情報の提供ありがとうございます。

**Comment by yuhei-mukoyama** [comment]
IconServices 関連のキャッシュとかが起因しているって事はないですかね？
OnyXとかで一回キャッシュ関連クリアにしてみたらどうでしょう。

**Comment by tsurunaga** [comment]
ご助言ありがとうございます。OnyxやLiteIconといったアプリを使ってキャッシュをクリアしているのですが改善しないです。

**Comment by Chamiu** [comment]
[smittytone/PreviewMarkdown: Markdown preview and thumbnmailing extensions for macOS Catalina and up](https://github.com/smittytone/PreviewMarkdown)の[PreviewMarkdown 1.1.2 (MAS, Universal)](https://apps.apple.com/jp/app/previewmarkdown/id1492280469?mt=12)で個別対応してみました。

<img width="326" alt="スクリーンショット 2020-12-12 11 48 13" src="https://user-images.githubusercontent.com/2077600/101970927-d3a8f080-3c70-11eb-8ff3-ff9a3f2960e9.png">

ただし、次のふたつの視認性がないのが難点ではあります。
- CotEditorをdefaultのappとして開く
- Markdown形式である
