### ISSUE TITLE
テキスト全選択時にインデント解除すると応答しなくなる

### ISSUE THREAD

**Issue by yaslab** [coteditor/CotEditor#356]
ソースコードのインデントを解除しようとしたところ、以下の事象が発生しました。
ご確認のほど、よろしくお願いします。

## 環境 

- CotEditor: 2.1 RC (2.1.0-rc)
- システム: OS X バージョン 10.10.2（ビルド 14C109）
- 言語環境: 日本語

## 再現手順

- CotEditorを新しく起動し、以下のテキストを貼り付ける (Command + V)

```
    aaa
    aaa
    aaa
```

- 全選択 (Command + A)
- インデント解除 (Command + [)
- Commandを押したままもう一度 [ を押す
- CotEditorが応答しなくなる

**Comment by 1024jp** [comment]
報告ありがとうございます。再現しました。修正します。

**Comment by 1024jp** [comment]
修正しました。

**Comment by yaslab** [comment]
ありがとうございます！
