### ISSUE TITLE
空行でインデントを追加するとその下の行にもインデントが追加される

### ISSUE THREAD

**Issue by yaslab** [coteditor/CotEditor#357]
空行でインデントを追加 (Command + ]) すると、その下の行にもインデントが追加されてしまいます。
おそらく、期待する動作ではないのでご連絡します。
（カーソルのある行のみインデントされるのが期待する動作？？）

## 環境 

- CotEditor: 2.1 RC (2.1.0-rc)
- システム: OS X バージョン 10.10.2（ビルド 14C109）
- 言語環境: 日本語

## 再現手順

- CotEditorを新しく起動し、以下のテキストを貼り付ける (Command + V)

```
    aaa

    aaa
```

- 2行目にカーソルを置く (2行目は空行)

```
    aaa
(ここ)
    aaa
```

- インデント追加 (Command + ])
- 2, 3行目にインデントが追加される

**Comment by 1024jp** [comment]
こちらもありがとうございます。修正いたしました。

**Comment by yaslab** [comment]
こちらもありがとうございました！
