### ISSUE TITLE
Request: Insert date/time stamp.

### ISSUE THREAD

**Issue by sannan39** [coteditor/CotEditor#358]
Hi, dear!

I've used CotEditor in 2013, and used to write daily work log.
 
This Editor quickly and light for editing text. I'm very thankful.

And, please add function insert date/time stamp text, like Miscrosoft Excel.(Ctrl+; / Ctrl+:)

Thank you.

**Comment by 1024jp** [comment]
Hello.
 
CotEditor has already a time stamp script as one of the script samples.
You can find a script named "**Input Current Time.applescript**" in: CotEditor menu bar > script icon > SampleScript > AppleScript > Extras.
The real file path of the script is `~/Library/Application Supports/CotEditor/ScriptMenu/SampleScript/AppleScript/Extras/Input Current Time.applescript`. If you want to change the format of the stamp, edit this script as you like.

If you don't have your `SampleScript` folder or your sample script is too old to run, follow the following instruction:

1. on Finder: remove your current SampleScript folder in `~/Library/Application Supports/CotEditor/ScriptMenu/` (if available).
2. on CotEditor: select the script icon in menu bar.
3. press `option` key and you will find "**Copy Sample to Scripts Folder**" action.
4. select the  "**Copy Sample to Scripts Folder**" menu item.
5. select "Update Script Menu" action.

**Comment by sannan39** [comment]
I should have looked for it so carefully.
I'll write log using this script.

Thank you!
