### ISSUE TITLE
Add Cyrillic (Windows) encoding

### ISSUE THREAD

**Issue by fiery-** [coteditor/CotEditor#360]
Please, add the Cyrillic (Windows - CP1251) encoding. It's supported by OS X with the following constants:

CFString => kCFStringEncodingWindowsCyrillic                  /* code page 1251, Slavic Cyrillic*/
NSString => NSWindowsCP1251StringEncoding

**Comment by 1024jp** [comment]
Hi, fiery. Thanks for your feedback.
I'll add the encoding on the next version :)
