### ISSUE TITLE
Revert command with selected encoding

### ISSUE THREAD

**Issue by fiery-** [coteditor/CotEditor#361]
I found that File -> Revert doesn't preserve the selected encoding. I would like to reopen the file from the disc with the selected encoding (I use Reinterpret encoding option, because I want to open it in original doc encoding). If that's the intention of Revert command, then may be a new command that preserves selected encoding would be fine.

**Comment by 1024jp** [comment]
This is the current intention of the Revert command. However, I'm just recently wondering how it would handle the file encoding on revert (and on resume) in the right way. As you said, I suppose it's better to preserve the initial file encoding that user chose and use it again on revert. I'll improve the behaviour in the near future.

Thanks for the suggestion.

**Comment by 1024jp** [comment]
Hey, I've changed the behavior on reverting to use encoding either at the last saving, opening or reinterpreting. 
So, this issue will be resolved on the next vesion 2.2.0.
