### ISSUE TITLE
Command+Eで検索ウィンドウを開かないようにできますでしょうか？

### ISSUE THREAD

**Issue by jakago** [coteditor/CotEditor#365]
2.1.0はスキップしていたので2.1.1にして気がついたのですが、Command+Eで検索ウィンドウが開くのが目障りで仕方ありません。勝手に開かないように設定できますでしょうか？

**Comment by 1024jp** [comment]
ショートカットキーは
　　環境設定 > キーバインド > メニューキーバインド
から変更できます。

**Comment by jakago** [comment]
キーバインドを変更したいのではありません。2.0.3までのようにCommand+Eで選択部分を検索に使用するだけとし、検索ウィンドウを開かないようにしたいということです。

**Comment by 1024jp** [comment]
おっと、早合点していました、申し訳ないです。
仕様については了解です。
これは実装ミスですね、次バージョンで修正します。
