### ISSUE TITLE
Perl Scriptを使用すると文字化けが発生 ver2.1.0

### ISSUE THREAD

**Issue by 84ma** [coteditor/CotEditor#367]
CotEditor2.1.0以降で以下のバグを確認しました。ご確認いただきますようお願いいたします。

簡単な説明
- 1.5.4,2.0.3まで使用していた、Perl Script を使用すると文字化けが発生。

不具合が発生したときに行っていた操作、または再現手順
- 1.5.4,2.0.3までは正常に動作
- 2.1.0，2.1.1，2.1.3は文字化けが発生

使用したPerl
```
#!/usr/bin/perl
#%%%{CotEditorXInput=Selection}%%%
#%%%{CotEditorXOutput=ReplaceSelection}%%%
use strict;
use warnings;
use utf8; # perl の内部コードに変換(UTF-8 フラグを付ける)
binmode STDOUT, "utf8";  #-画面に出力したい文字コード
binmode STDERR, "utf8";  #-エラー出力に使いたい文字コード
binmode STDIN, "utf8";
while (<>) {
	s/■/□/g;#■→□変換
print;
}
```
入力：□■（UTF-8,LF）
出力：文字化けが発生

環境 
- CotEditor: 2.1x (2.1.0～2.1.2)
- システム: OS X バージョン 10.8.5（ビルド 12F2501）
- 言語環境: 日本語

**Comment by 1024jp** [comment]
2.1.0 からスクリプトの仕様が少々変更され、最前面のドキュメントが既にどこかにファイルを持っている場合はスクリプトの第一引数として(UTF-8で)そのファイルのフルパスを渡すようになりました。
それによってPerlスクリプトの挙動が変わる可能性はありますか？
当方perlはあまり明るくないのですが、それによって文字化けが発生している可能性があります。
CotEditor側で処理を変更しなければどうしようもない場合は検討します。

**Comment by yuhei-mukoyama** [comment]
とりあえず、これで動きますね。
STDIN で入ってきた UTF-8 をバイナリとして認識して再エンコードしちゃってるってことですかね？
自分も Terminal(utf-8) 環境下以外で Perl 使ってないので、詳しく分かりませんが…。

```perl
#!/usr/bin/perl
#%%%{CotEditorXInput=Selection}%%%
#%%%{CotEditorXOutput=ReplaceSelection}%%%
use strict;
use warnings;
use utf8; # perl の内部コードに変換(UTF-8 フラグを付ける)
# binmode STDOUT, "utf8"; <- 不要
# binmode STDERR, "utf8"; <- 不要
# binmode STDIN, "utf8"; <- 不要
while (<>) {
    s/■/□/g;#■→□変換
print;
}
```

**Comment by 84ma** [comment]
CotEditorのテンプレートとして入っている。
template_2.pl をベースにして使用すれば問題有りませんでした。
```perl
#! /usr/bin/perl
# template_2.pl
# Sample Perl Script for CotEditor 
# %%%{CotEditorXInput=Selection}%%%
# %%%{CotEditorXOutput=ReplaceSelection}%%%

$INPUT=`cat -`;
$INPUT =~ tr/■/□/;
print $INPUT;
```
とりあえず、テンプレートをベースに書き換えて使用して行きたいと思います。
ご迷惑をおかけしました。

**Comment by 1024jp** [comment]
解決したようで良かったです。

@yuhei-mukoyama 検証と回答ありがとうございます。助かります。
@84ma 基本的には仕様変更ということで、スクリプト側の変更で対応をしていただければと思います。

このイシューはクローズします。
