### ISSUE TITLE
May I disable auto-saving?

### ISSUE THREAD

**Issue by sunnyxx** [coteditor/CotEditor#368]

**Comment by 1024jp** [comment]
Nope. 
There is no option to disable auto-saving. And also we don't have any plan to implement it in the future.

Yesterday on CotEditor 2.1.2, we've enhanced the behavior of auto-saving (it is actually not the same as the "Autosave" which modern Apple application provides.).
I suppose now the auto-backup feature on CotEditor doesn't bother you anymore.

**Comment by sunnyxx** [comment]
Great, v2.1.2 really solved my problem :)

**Comment by 1024jp** [comment]
I'm glad to hear that :)
