### ISSUE TITLE
4桁以上の行番号 / line number over 9999 lines

### ISSUE THREAD

**Issue by hamadeguchi** [coteditor/CotEditor#370]
便利に利用させてもらっています。
大きなファイルを開いた場合行番号が下４桁で見切れてしまいます。
フォントの問題でしょうか
MrvericksでOsakaを使用しています。
よろしくお願いします。

**Comment by 1024jp** [comment]
おっとこれはバグです。申し訳ない。
行番号およびその幅計算に使うフォントは固定なので、表示フォント設定の影響は受けません。
次バージョンまでに修正します。それまではご辛抱を。
