### ISSUE TITLE
文字列選択→⌘E→⌘Fで検索ダイアログの検索文字列に反映されないのは仕様でしょうか？

### ISSUE THREAD

**Issue by jakago** [coteditor/CotEditor#371]
一度でも検索すれば反映されます（文字列選択→⌘E→⌘G→⌘F）

**Comment by 1024jp** [comment]
状況が手元で再現できません。
OS X および CotEditor のバージョンを明記した上で、もう少し手順を詳細に書いていただけると助かります。
とくに「反映されない」と「一度でも」を具体的に書いてください。

**Comment by jakago** [comment]
OSX 10.8.5
CotEditor 2.1.2

操作：　文字列選択→⌘E→⌘F
開いた検索ダイアログの「検索」欄の文字列が⌘Eの前に選択した文字列になりません。「検索」欄は起動直後なら空、何かを検索した後なら直前に検索した文字列のままです。

操作：　文字列選択→⌘E→⌘G→⌘F
開いた検索ダイアログの「検索」欄の文字列は⌘Eの前に選択した文字列になります。

**Comment by 1024jp** [comment]
追加情報ありがとうございます。
しかし、引き続き問題がこちらで再現できず手がかりがつかめない状態です。

改善するかわかりませんが、一度キーバインドのリセットを試してみていただけますか？
CotEditorの環境設定の「キーバインド」ペイン > メニューキーバインド「編集」ボタンで現れるシート下の「デフォルトに戻す」ボタンをクリックしたのちに「OK」ボタンを押して、再度問題が改善されるか試してみてください。

また、⌘Eや⌘Fなどのショートカットキーを使う代わりに、同様の手順でその操作を逐次CotEditorのメニューバーの「検索」からマウスで選んで実行した時に振る舞いが変化するかも合わせて教えていただきたいです。

**Comment by 1024jp** [comment]
たた

**Comment by 1024jp** [comment]
This will be fixed on the next CotEditor 2.2.2.

----

お待たせしました、この問題は近日中にリリースされる CotEditor 2.2.2 で解決します。
