### ISSUE TITLE
検索ダイアログを開いた時に検索文字列が選択されていません

### ISSUE THREAD

**Issue by jakago** [coteditor/CotEditor#372]
2.0.3からのバージョンアップで気がついたのですが、メニューまたは⌘Fで検索ダイアログを開いた時に検索文字列の後ろにカーソルがあります（2.0.3では検索文字列全体が選択状態）。⌘Fを押す時は基本的に新たな検索を行ないたい時なので、2.0.3までのように全体が選択状態になることを希望します。

ちなみに、Jedit X、TextMate、Sublime Text、Atom、Komodo Edit等、私が知っている他のエディタでは⌘Fで検索文字列が選択状態になります。よろしくお願いします。

**Comment by 1024jp** [comment]
これについては、現在開発中のv2.1.3ではすでに修正済みなのでしばらくお待ち下さい。
おっしゃるとおり検索文字列が選択状態になるのが本来あるべき動作です。
