### ISSUE TITLE
Make vertical tabs (U+000B) visible / 垂直タブの可視化

### ISSUE THREAD

**Issue by ha810** [coteditor/CotEditor#377]
要望になりますが、不可視文字の表示・非表示の設定に垂直タブがあると助かります。
ご検討頂けたら幸いです。

**Comment by 1024jp** [comment]
リクエストありがとうございます。
実装の仕方を含め少し検討させてください。

**Comment by 1024jp** [comment]
__Note__: ␋ (`U+240B`) symbol for vertical tabulation

**Comment by 1024jp** [comment]
垂直タブが存在する場合は「␋」というシンボルを表示するように変更しました。

設定の使用頻度を考え、新たに設定項目を追加するのではなく、「その他の不可視文字」も表示する設定にしている時には垂直タブも描画するようにしました。シンボルは固定になります。

実装は以下のスクリーンショットのようになります。


![screen shot 2015-04-29 at 23 42 54](https://cloud.githubusercontent.com/assets/1165044/7393876/3669f61e-eecb-11e4-9be5-15fa20d577cf.png)

この実装法で使用上不都合がありましたら、お知らせください。

この変更は次の CotEditor 2.1.4 に含める予定です。
