### ISSUE TITLE
「書類”名称未設定”を”top.html”として保存できませんでした」

### ISSUE THREAD

**Issue by maonyan** [coteditor/CotEditor#382]
【CotEditorの初心者です】

CotEditorでテキストエディタを作成し始めました。
テキストを開き、シンタックスをHTMLに設定し、ファイルから「top.html」と保存しようとすると
「書類”名称未設定”を”top.html”として保存できませんでした」と出ました。

他の使い方サイトで見ると、ここでは普通に保存できるはずなのですが、なぜでしょうか。
ご存知のかた、教えていただけると幸いです。よろしくお願い致します。

**Comment by 1024jp** [comment]
それはちょっと不思議な挙動ですね。
どの場所にファイルを保存しようと思っても常に同じ状態でしょうか？
それとも特定のフォルダやファイル名だけでしょうか？

また、現在の CotEditor のバージョンと OS X のバージョンも併記ください。

**Comment by 1024jp** [comment]
この問題は解決しましたか？
返信がないようであればユーザ固有の問題として、このイシューは一旦クローズしようと思います。
