### ISSUE TITLE
ページ番号を出したい

### ISSUE THREAD

**Issue by RekioMac** [coteditor/CotEditor#387]
こんにちは。
縦書きができるエディタと言うことで、私が書いている映画のシナリオに使えないかなと思いまして試してみました。
ページ表示は必要がないのですが、
ページ番号は知りたいです。
例えば、全角20文字x20行まで来たら2Pの文字と区切り線が出てくるとか。

そういうことはできますでしょうか？
(Windowsでは秀丸エディタにそのような機能があります)

なければ機能追加していただける可能性はありますでしょうか？

(まず1ページは何文字x何行なのか設定できることと、一行当たりで折り返す文字数の設定が必要になります)

補足: なぜページ番号が必要かと言うと、シナリオは1ページ(20x20文字)で1分という決まりになっていて、映画の尺が120分と決まっている中で作るので、読む人(監督や役者など)にも伝わるように書いていくことになっているからです。なので常に1ページを意識して書き進めていくことになります)

**Comment by 1024jp** [comment]
現在 CotEditor はページレイアウトに関する機能の追加を積極的に考えておりません。
将来的に補助的な総ページ数カウントの機能を追加する可能性はありますが、
現在のページ数や区切り線の表示は実装しない考えです。

#133 も参照ください。

**Comment by RekioMac** [comment]
1024jpさんへ
ご回答ありがとうございます。

質問にも書きましたが、ページ表示は必要としていません。
ただ、行数のように、ページ番号(何行かを1ページと設定して)がほしいのですが、無理ですか？

CotEditorは縦書きができますが、どのような用途を想定しているのでしょうか？

原稿を書くエディタではなく、プログラムのためのエディタなのかなと思いましたが、それでは縦書きの必然性がよく分かりません。
逆に縦書きが出来るなら、Macで数少ない縦書きエディタとして、原稿を書くのに必要な機能があると使ってみたいなと思った次第です。
(文字レイアウトを重視するワープロではなく、あくまでエディタの範疇で)

開発者の方のコンセプトにそぐわないようでしたら、残念ですが、別のエディタを使うことにします。

**Comment by 1024jp** [comment]
無理です。
CotEditor はプレーンテキストエディタです。それを超える機能を付けるつもりはありません。
また優先順位の問題もあります。私が興味がないので付けません。

縦書きはユーザが有益に感じる利用場面があれば使ってもらえればと考え実装しました。具体的なユースケースはこちらでは想定していません。
ページ数がカウントできなくても縦書きが有効な場面はあると思います。

**Comment by RekioMac** [comment]
分かりました。
オープンソースと書かれていたせいか、いろいろ意見を取り入れていくソフトと勘違いしておりました。
きっぱり興味がないと言われてさっぱりしました。
ご返事ありがとうございます。

**Comment by 1024jp** [comment]
いえいえ。
オープンソースとはソースコードを公開しているというだけです。
フィードバックについても色々な意見は歓迎しますが、かならず取り入れるとは限りません。
ご期待に添えず申し訳ない
