### ISSUE TITLE
Feature request: multi-window feel or auto-close when last file is closed

### ISSUE THREAD

**Issue by rshmelev** [coteditor/CotEditor#389]
-------------------------------------------

## Environment

- CotEditor: 2.1.3 (2.1.3)
- System: OS X Version 10.10.3 (Build 14D136)
- Language: English

## Short Description

Hi! 
CotEditor is used by me as "Notepad" replacement and it is really nice ! :)
To say that it is cool, i'm missing the following feature.. 
- i'm in Finder and opening file in CotEditor
- i edit file and need to press something like ESC or Cmd+W to close file and return back to Finder
- but, CotEditor should remain opened if there are some other files opened in it... or it should close if it was the only file opened in it.

Anyways thanks!

**Comment by 1024jp** [comment]
Thanks for the feature request.

Yes, as you say, modern OS X app should close silently when it is in background and no window is available.
I'll implement it in the next version if no complicated problem is found to enable the auto-termination.
