### ISSUE TITLE
Code completion sometimes obtrusive

### ISSUE THREAD

**Issue by j1r** [coteditor/CotEditor#392]
Code completion is triggered sometimes too eagerly and can interfere with normal typing. Specifically, triggering completion by hitting Return is sometimes problematic. Consider typing e.g.
```
function () {
```
Hitting Return after the opening curly brace will result in the first available completion being inserted after the curly brace, e.g.
```
function () {SOME_UNWANTED_STRING
```
instead of the seemingly expected newline.

Would like to see some way around this, e.g. an option to disable/enable the default completion-by-return behaviour (completion-by-tab only would be perfectly sufficient for me, but your mileage may vary of course).

(Or is there already some fix for this I'm unaware of?)

**Comment by 1024jp** [comment]
Thanks for the feedback.

I've also realised that the timing to trigger auto-completion needs to be improved. And not be fixed yet. It actually isn't marked as the highest priority now, but I'll probably tune it on next versions.

// Unfortunately, there is currently no workaround for for this behaviour. An option for that is just to disable auto-completion in the Preferences -> Edit and trigger it each time manually.

**Comment by 1024jp** [comment]
Hi.
I've add a quick improvement about the code completetion to the next v2.1.4 that completion will not be triggered after a symbol character.
It's not fandamental fix but might be better than the current behaviour.

**Comment by j1r** [comment]
That's awesome, that'll be helpful already. I agree that a more fundamental fix will probably be appropriate, though, but that's great for a quick fix IMO.
