### ISSUE TITLE
検索と置換のウインドウでアイコンが重なって表示される

### ISSUE THREAD

**Issue by kei-ito** [coteditor/CotEditor#393]
## 環境 
- CotEditor: 2.1.3 (2.1.3)
- システム: OS X バージョン 10.10.4（ビルド 14E46）
- 言語環境: 日本語

## 簡単な説明
テキストボックスの左上でアイコンが重なって表示されます。

## 不具合が発生したときに行っていた操作、または再現手順
command + F で検索と置換のウインドウを開きました。

## 期待される挙動
重ならないように表示してほしいです。

![参考画像](https://cloud.githubusercontent.com/assets/7359068/8492439/8d1c9a7a-2184-11e5-970f-ec562c93bada.png)

**Comment by 1024jp** [comment]
報告ありがとうございます。
本件については #381 ですでに修正済みですので近々リリースされる次バージョン (v2.1.4) では修復されています。
また、現在出ている [2.1.4 の β 版](https://github.com/coteditor/CotEditor/releases/tag/2.1.4-beta.3)でも修正が反映されています。

**Comment by kei-ito** [comment]
ありがとうございます。
次バージョンのリリースを楽しみにしております。
