### ISSUE TITLE
Create two versions of target for AppStore ver and non-AppStore ver.

### ISSUE THREAD

**Issue by 1024jp** [coteditor/CotEditor#394]
And use Sparkle framework only on non-App ver.

**Comment by 1024jp** [comment]
現時点では non-AppStore 版も Sandbox 化してしまって、違いは Sparkle のサポートの有無のみにしようかと考えています。
Sandbox 化した上で Sparkle をサポートするというのは、つまり、Sparkle をアップデート版の通知にのみ使って、新しいバージョンのインストール自体はユーザに手動で行ってもらうようにするということです。
（Sparkle が Sandbox されているアプリケーションの書き換えをできないため）
これは、non-AppStore 版でも Sandbox 化をして安全性を高めるためもありますが、正直開発効率の向上の意味合いも大きいです。

cask を使うために AppStore 版を避ける様な人はこれでも十分だと思います。
それ以外の理由で AppStore 版を使う人もレアケースだと思うので手動インストールで我慢してもらおうと。

**Comment by 1024jp** [comment]
reminder: Don't forget to remove `dsa_pub.pem` from AppStore version.

**Comment by usami-k** [comment]
なるほど。AppStore 対応を重視するならそういう方向でいいかもしれません。non-AppStore 版を使い続ける人にはちょっと不便な気もしますが、許容範囲と思います。
むしろ、non-AppStore 版でも Sparkle にこだわる必要はないように思います。アップデート版を通知してダウンロードページに誘導できれば何でもよさそうです。（まあ、それでも結局 Sparkle を使うのが楽かもしれませんが）

**Comment by 1024jp** [comment]
Sparkle は今後一応 Sandbox 対応をする用意があるらしいので、

**Comment by usami-k** [comment]
おお、そうなんですね。了解です。
