### ISSUE TITLE
authopenの挙動不審

### ISSUE THREAD

**Issue by kzhr** [coteditor/CotEditor#401]
## 環境 

- CotEditor: 2.1.3 (2.1.3)
- システム: OS X バージョン 10.10.4（ビルド 14E46）
- 言語環境: 日本語

## 簡単な説明
authopenの挙動に不備があり，作業に支障が出る。

## 不具合が発生したときに行っていた操作、または再現手順
新規ファイルを作成，あるいは保存した状況で，書類に変更を加える。
具体的には，書類に変更を加えると，
「authopenが変更を加えようとしています。これを許可するには、パスワードを入力してください。」
と出，パスワードを入れてもしばらく書類内容に変更を加えていると同様の許可が求められ，キャンセルすると，
「書類“xxx”を自動保存できませんでした。
変更内容は、問題が解決するまで保存されません。」
となって静かになる。作業そのものは続行でき，保存もできる。
ただし、報告者の所有する別の機械では同様の問題は発生せず，再現性は不詳。

## 期待される挙動
このような認証を求められない。

**Comment by 1024jp** [comment]
まず、以下の3点をお試しください。

1. CotEditorを最新版 (2.1.6) にアップデートする
2. アプリケーションフォルダの ユーティリティ > __ディスクユーティリティ__ を立ち上げ、アクセス権の修復をする
3. Mac を再起動

これで状況が変わらない場合は以下の検証をして状況を教えてください。

1. まだ一度も保存していない書類 (名称未設定) の状態でもこのダイアログが表示されることがあるか
2. わかる場合は、この問題が起こったファイルのパーミッション

**Comment by kzhr** [comment]
1〜3を実行してもだめでした。検証1は，例外なく表示されます。~/Library/Autosave Information/のパーミッションが
drwx------+   5 root  wheel    170  5  5 11:33 Autosave Information
だったのですが，これが原因なんでしょうか。

**Comment by kzhr** [comment]
原因でした。パーミッションを修正したら治りました。失礼いたしました。

**Comment by 1024jp** [comment]
Disk Utility.app が ~/Library/Autosave Information のパーミッションもおかしかったら修正してくれるかと考えていたのですが、やってくれなかったようですね。
治ったようで良かったです。
