### ISSUE TITLE
OgreKit build fails

### ISSUE THREAD

**Issue by perfaram** [coteditor/CotEditor#403]
I'm getting errors when compiling OgreKit (being with `pod install`, or in Xcode) :
```
make: error: unable to find utility "make", not a developer tool or in PATH
Command /usr/bin/make failed with exit code 72
```
Any idea ? Note that this is the *only* relevant output, before is just various `export`s making things ready for `make`.

EDIT : Xcode 7 Beta 4, command line tools provided with Xcode.

**Comment by 1024jp** [comment]
Did you install Xcode's command-line tools?
In which phase did you get the fail? 
CotEditor's OgreKit is normally built and provided when you run `pod install` in Terminal.

// To ask such a question, you need at least the information about Xcode version and OS version.

**Comment by 1024jp** [comment]
Ok, I've just found the problem.
Build was failed only when Xcode 7 (beta) is used.
I've quick fixed so now you may be able to build OgreKit ;)

**Comment by perfaram** [comment]
OK, thanks & sorry for the information lack... was in a hurry :runner:.
I added more info in the first post, just in case.

**Comment by 1024jp** [comment]
no problem :)
