### ISSUE TITLE
Add option to get beta release notification

### ISSUE THREAD

**Issue by 1024jp** [coteditor/CotEditor#404]
but only for non-AppStore version.

**Comment by 1024jp** [comment]
他のオープンソースのSparkle利用事例を見てみているかぎり、
ベータ版の提供は AppCast を

- 安定版のみ
- ベータ版含む

の2種類用意して、アプリケーション内でユーザ設定を見て参照する AppCast を切り替えるのが定石なようです。

CotEditor も同じスタイルを取ろうかと思います。
ファイル名は appcast-beta.xml 辺りにしようかと考えています。

**Comment by usami-k** [comment]
なるほど、了解しました。では AppCast は2種類生成するようにします。

**Comment by 1024jp** [comment]
環境設定にチェックボックスを追加しました。
オン／オフで参照する AppCast の URL が appcast.xml <-> appcast-beta.xml で変化します。

なおこれに伴い、SUFeedURL の宣言位置が従来の Info.plist 中から、`CEUpdaterManager.m` 内で delegate として直接 SUUpdater に渡す形に変更されました。

CotEditor 本体側の改修はすでに終了しているので、この Issue はクローズします。
