### ISSUE TITLE
Change build number versioning / ビルドナンバーのナンバリングを変更

### ISSUE THREAD

**Issue by 1024jp** [coteditor/CotEditor#419]
By App Store submission, the build version number MUST BE a _period-separated list of at most three integers_.
So, it means: __the semantic versioning is invalid__.
We can't increase build version with `+` sign anymore.

In addition to that, when we get rejection by Apple and need to submit a new version, we must increase the build number.
If version 2.2.0 is going to be rejected, for example, we need to increase the build number. But 2.2.0+1 is invalid. The only way to conform to the App Store versioning rule is increasing the patch number, namely 2.2.1. But then, it is no more 2.2.0 but just version 2.2.1.

Another problem is: we already manage CotEditor with the semantic versioning. The versioning is used by Sparkle and also in some migration code of CotEditor itself. If we change the versioning style, we also need to care such side effects.

However, it seems we don't have any walk-around about this. We have to change our versioning style. Ok, do it, if it must be done.

-----

App Store へのサブミッションにおいて、ビルドナンバーは__必ず__「 3つ以下ピリオド区切りの整数」で構成されていなければいけない。
つまり、__Semantic Versioning は無効__ である。
`+` 記号でビルド番号を上げることはできない。

加えて、もし Apple が提出をリジェクトをした場合、修正版の提出ではビルドナンバーは以前のものより大きい必要がある。たとえば、もし 2.2.0 がリジェクトされた場合、次再提出では 2.2.0 より数字が大きくなければならない。現状のまま Apple のビルドナンバーのルールの枠組みの中であげられる最小の数値は 2.2.1 だが、これでは別のバージョンになってしまう。

別の問題としては、CotEditor はすでに Semantic Versioning でバージョン管理をしている、ということが挙げられる。Sparkle や CotEditor 自身の内部設定形式の移行処理などで semver による比較が行われている。もし、バージョニングスタイルを変更するならばこれにも配慮する必要がある（おそらくコードを書き足す必要がある。

いずれにせよ、これに関して回避策はないように見える。ビルドナンバーのナンバリング形式は変更されなければならない。

ということで、どうしましょう > @usami-k さん

**Comment by usami-k** [comment]
確かに、App Store に出すのであれば Apple のビルドナンバーのルールを意識しなくてはなりませんね・・・。うっかりしていました。

なお、ビルド番号（CFBundleVersion）だけでなくバージョン番号（CFBundleShortVersionString）についても同様のルールがあるようです。いずれにせよ、Semantic Versioning のルールは使えないですね。

ref.
https://developer.apple.com/library/mac/documentation/IDEs/Conceptual/AppDistributionGuide/ConfiguringYourApp/ConfiguringYourApp.html#//apple_ref/doc/uid/TP40012582-CH28-SW18

今後の方針として、ビルド番号とバージョン番号は全く異なる管理方式にしてはどうかと思います。

* バージョン番号は、従来どおり、「2.2.0」といった値にする。
* ビルド番号は、「34」といった1桁の値にする。iTunes Connect への提出のたびにインクリメントする。

Apple にリジェクトされて再提出する場合は、バージョン番号はそのまま、ビルド番号をインクリメントする、ということになります。

ただ、内部でバージョン比較をしている箇所や Sparkle については、なんらかの対処が必要にはなります。これはいずれにしても避けられないかと思います。

いかがでしょうか。

**Comment by 1024jp** [comment]
そうですね、了解です。
Apple が SemVer を許容していればよかったんですけどね、まぁ仕方ないですね。

提案を元に #419 に変更したものを Pull-Request として出しました。
