### ISSUE TITLE
The Features I want to have.

### ISSUE THREAD

**Issue by wildtang** [coteditor/CotEditor#429]
CotEditor is a great work, Thanks.

I really want the feature below, please consider to add them to the next version, many many thanks!
(1) Underline style cursor (like the DOS style)
(2) Navigation thumbnail map (Just like the one on Sublime right panel)
(3) Do not prompt to save file before Exit, when relaunch CotEditor it still remember the unsaved data. (Just like Sublime)

**Comment by TongKuo** [comment]
Agree with third point, it's very delicious.

**Comment by 1024jp** [comment]
#### 1. Underline style cursor
I won't implement this. It's not an essential feature (at least for me) and I don't wanna make the preferences complicated.

#### 2. Navigation thumbnail map
There are two problems:

- It may conflict with vertical split views on layout.
- This feature actually represents Sublime Text. If it is implemented, everyone may think CotEditor just imitated it from Sublime Text. I'll gladly take good features from well-made existing text editors, however, how to say, this feature has too strong impression of Sublime Text.

Well, I'll consider. It is not *impossible* feature. but the priority will be not so high.

#### 3. Keep unsaved contents on termination
I have a plan to implement Autosave feature in the near future. Is it enough for you? Or it must keep just contents without saving to the real file?

**Comment by yetangye** [comment]
Thanks for your reply.

#### 1. Underline style caret
Sorry for my mistake, my meaning was underline style caret, just as the caret in bash. 
My meaning was not cursor style.

#### 2. Navigation thumbnail map
This feature is not Sublime only, some other editors also have this feather,
such as EverEdit(http://jp.everedit.net/) or sakura(http://sakura-editor.sourceforge.net/), 
this feature is very helpful when edit large text file.

#### 3. Keep unsaved contents on termination
Autosave is another feature, I just need a area for scratch, just as the  temporary memo area of Becky! Internet Mail (http://www.rimarts.co.jp/becky-j.htm).

I am finding a light-weight, full utf-8 support, clean and handful editor on Mac,
but it seems there were no counterpart with EverEdit or EditPlus on Windows platform.
I think Sublime was for Coder or Geeks, not for general users, users need to use codes to config it...,
and that is difficult for general users.

頑張って。

**Comment by wildtang** [comment]
The guy above and wildtang both are one guy's account ;)

**Comment by 1024jp** [comment]
### 1. Underline style caret

I see. However I'm not fan of that kind of caret (personally). Furthermore, I wanna keep CotEditor settings enough simple and OS X-based. I think the underline style caret is not common on OS X. So I will not implement this.

### 2. Navigation thumbnail map

Hmm, let me see. It requires a quite large amount of work. And need to change the internal stricture as well. I'll consider it, but I can’t promise. I'll make an issue for this request as a separated issue later.

### 3. Keep unsaved contents on termination
Ok I see. But how about setting the behavior in the System Preferences (in General pane)? I know it applies to all applications, but I suppose this is actually the behavior that you want.
![screen shot 2015-09-12 at 20 15 39](https://cloud.githubusercontent.com/assets/1165044/9831281/0ed7e798-598b-11e5-9ceb-43021e76e370.png)
Or do you have any special situation that the behavior should be enabled only within CotEditor?

**Comment by 1024jp** [comment]
I've created a single issue for the navigation thumbnail map (mini-map) on #435.
I'll comment on the issue when there is any update for this feature.

**Comment by 1024jp** [comment]
I close this issue because I've already made a single issue page about mini-map on #435 and other requests were probably consented in this issue page.

You can add comments below if you have another idea about this (or create another issue for another theme/request).
