### ISSUE TITLE
シンタックスカラーがツールバーに反映されている

### ISSUE THREAD

**Issue by yuhei-mukoyama** [coteditor/CotEditor#443]
CotEditor App Store 版リリースおめでとうございます。早速インストールしてみました。

インストール後すぐに気になったのが、ツールバーの背景色にシンタックスカラーテーマの背景色が反映されている点です。

![tool bar color](https://cloud.githubusercontent.com/assets/5656927/10272906/513aeaf2-6b62-11e5-879e-a35f87f8496f.png)

通常背景のウィンドウなどがボケて反映されるように他のアプリはなっているかと思うでのすが、前述の通り背景色が反映されています。これはあえてなのか、作り途中なのかわからなかったのですが取り急ぎ Issue を立てさせていただきました。

特に背景色を暗くしていると、アクティブ・非アクティブ時の色が逆になっているように感じ、違和感が強かったです。

**Comment by yuhei-mukoyama** [comment]
今 Finder を見てみたら Finder はウィンドウの内容を反映するようになっていました。
Finder と同じにするということであれば、決して間違っているわけではないんですね。
失礼しました。

どちらが良いのかわからないのですが、自分の認識が誤っていたので一度クローズします。

![2015-10-05 14 56 21](https://cloud.githubusercontent.com/assets/5656927/10273843/7689396c-6b71-11e5-964d-93a58e5ecfa0.png)

**Comment by 1024jp** [comment]
うーん、これに関しては 「OSの仕様です」という回答になっちゃいますね。
（自分では白背景使ってたのでこの辺のことはあんまり深く考えていませんでした）
コードを足せばこの挙動を止めることもできるはずではありますが。
まぁ、「表示」ペイン辺りにこれに関する設定項目を追加するかどうかですね。

**Comment by yuhei-mukoyama** [comment]
ありがとうございます。

> コードを足せばこの挙動を止めることもできるはずではありますが。
> まぁ、「表示」ペイン辺りにこれに関する設定項目を追加するかどうかですね。

なんかそれもオプションが増えてあまり乗り気になれない感じありますね。

個人的に色々違和感の元を探したところ、プルダウンメニューが違和感の元なのかなと思いました。
Finder などはボタンタイプのプルダウンなので、背景色を暗くしても違和感がないのかもしれません。

<img width="615" alt="2015-10-05 16 34 54" src="https://cloud.githubusercontent.com/assets/5656927/10275026/099260fa-6b7f-11e5-8c42-1912d7bce6d6.png">

でも、これに関しても現在どの設定が反映されているか確認する必要がある場合は向いていないのでデザインを変えればいいというわけでもなさそうですね・・・。

**Comment by 1024jp** [comment]
プルダウンメニューの違和感というのは、エンコーディングとかのポップアップメニューの右側の色が付いてる部分が背景色と干渉するということについてですか？
