### ISSUE TITLE
Support Unicode normalization form like HFS+

### ISSUE THREAD

**Issue by doraTeX** [coteditor/CotEditor#445]
#417 と関連して。
HFS+ でファイル名を記録するときに用いられる正規化方式は，NFD をベースにしていますが，[CJK互換漢字を変換しない](http://tama-san.com/hfsplus_normalize/)点が異なります。
この正規化方式は，Apple 独自の正規化方式で，巷では俗に Apple Modified NFD などと呼ばれています。（Unicode Consortium に提案して[否決された](http://www.unicode.org/review/resolved-pri.html#pri7)歴史があるそうです。）
HFS+ にファイル名として保存したときに，Apple Modified NFD によって文字列がどのように変換されるかは，[CFStringGetFileSystemRepresentation](https://developer.apple.com/library/mac/documentation/CoreFoundation/Reference/CFStringRef/#//apple_ref/c/func/CFStringGetFileSystemRepresentation) でシミュレートすることができます。

この正規化方式は，Apple 独自の正規化方式はありますが，HFS+ で採用されているがゆえに，最も身近な正規化方式でもあります。
これも CotEditor がサポートする Unicode 正規化方式の一つに加えてはいかがでしょうか。
`NSString+Normalization.m` のカテゴリに，次のようなメソッドを付け加えれば可能です。
よろしければご検討ください。

```objc
// ------------------------------------------------------
/// A string made by normalizing the receiver’s contents using the normalization form adopted by HFS+, a.k.a. Apple Modified NFD
- (nonnull NSString*)decomposedStringWithHFSPlusMapping
// ------------------------------------------------------
{
    CFStringRef sourceStr = (__bridge CFStringRef)self;
    CFIndex length = CFStringGetMaximumSizeOfFileSystemRepresentation(sourceStr);
    char *destStr = (char*)malloc(length);
    
    Boolean success = CFStringGetFileSystemRepresentation(sourceStr, destStr, length);
    NSString *result = success ? [NSString stringWithUTF8String:destStr] : self;
    free(destStr);
    
    return result;
}
```

**Comment by 1024jp** [comment]
コードまで添えていただいて、ありがとうございます。早速取り込みます。

**Comment by 1024jp** [comment]
ちなみに、メニュー項目等に出す normalization の名称としては「Apple Modified NFD」で適当でしょうか？

**Comment by 1024jp** [comment]
一旦「Apple Modified NFD」(独: Apple Modifizierte NFD) という名称で実装。あとで適宜変更する。

**Comment by doraTeX** [comment]
確かに「Apple Modified NFD」は正式名称ではありませんので，Apple Modified NFD (HFS+) の方が意図が伝わりやすいとは思います。
ただ，メニューがややうるさくなりますので，シンプルな「Apple Modified NFD」もよいと思います。また，検索してみると，よりシンプルな「Modified NFD」という俗称も広く用いられているようです。
ご判断はお任せいたします。

**Comment by 1024jp** [comment]
名前はメニュー項目を「Modified NFD (HFS+)」(日: 「修正 NFD (HFS+)」) 、それ以外は「Modified NFD」という呼称で確定にしました。CotEditor 2.2.2 から導入されます。
