### ISSUE TITLE
「すべて置換」で選択範囲が解除されないようにして欲しい / Keep selection range even after "replace all"

### ISSUE THREAD

**Issue by khiri-co** [coteditor/CotEditor#449]
「置換」には「選択範囲のみ」オプションがあるが、選択範囲に検索ワードが含まれていると「すべて置換」を行った後、テキストの選択が解除されてしまう。
そのため、異なる検索ワードで連続して同じ選択範囲に「すべて置換」を行うとき、毎回テキスト選択を行わなければならないので手間取る。
テキスト選択が解除されないようにして欲しい。

例）「ABC**ABCA**ABC」（ボールド部分が選択されているとする）
検索：「A」、置換：「X」、「選択範囲のみ」で「すべて置換」
従来では）「ABCXBCXABC」
希望動作）「ABC**XBCX**ABC」

検索：「BC」、置換：「」、「選択範囲のみ」で「すべて置換」
従来では）「ABCAAABC」
希望動作）「ABC**AA**ABC」

**Comment by 1024jp** [comment]
この動作はCotEditor 自身ではなく、3rdパーティフレームワークが司っている部分であるため、改修が難しいです。
ちょっと後回しにさせて下さい。
利便性はわかるので、長期的には検討はします。

**Comment by 1024jp** [comment]
お待たせしました。この機能は次の CotEditor 2.4.0 で実装されます。
