### ISSUE TITLE
Close Project page on OSDN / OSDN 上のプロジェクトページを閉鎖する

### ISSUE THREAD

**Issue by 1024jp** [coteditor/CotEditor#450]
そろそろ coteditor.com の方のアドレスが浸透してきたと思うので、思い切って OSDN 上のプロジェクトは完璧に閉鎖・削除してしまってはどうかと考えています。

きちんと誘導をしているし OSDN  上からはバイナリも落とせないので、現状で特に問題がないとも言えるのですが、
Google で日本語優先で「CotEditor」を検索した時に、coteditor.com よりも OSDN 上のプロジェクトページの方が上にきてしまうのが気になっています。
さすが OSDN は強いです。
しかし、この状況はあまりよろしくないのではと感じています。
閉鎖宣言をしても osdn.jp 上にページ（アドレス）が存在するかぎり、この OSDN のページの方が google で上にきてしまう状況は避けられないのかなと考えています。
個人的には OSDN 上のページはもう役割を十分に果たしたかなぁと思います。
過去の歴史を辿るという上ではそれなりに大事ではあるのですが。

これは私個人の見解であるのと、そもそも私には osdn.jp 上のプロジェクトには権限がないので、@usami-k さんの判断に委ねます。

**Comment by usami-k** [comment]
僕も OSDN 上のプロジェクトがいまだに Google 検索で上位に来るのは気になっていました。

OSDN のヘルプでは削除でなく放置が推奨されていたので誘導するだけで放置しておいたのですが、いつまでも検索上位に来るようでは削除したほうが良さそうですね。

削除依頼を出しておきます。

**Comment by 1024jp** [comment]
なるほど推奨されてるのですね。実際検索順位の問題がなければ放置の方が良いのですが。
削除依頼ありがとうございます。

**Comment by usami-k** [comment]
OSDN のプロジェクトを削除していただきました。

**Comment by 1024jp** [comment]
ありがとうございます！
これでサイトへの誘導が楽になることを期待します。
