### ISSUE TITLE
不可視文字・改行の表示位置が行頭でズレる / New line char in empty line is drawn at wrong baseline

### ISSUE THREAD

**Issue by khiri-co** [coteditor/CotEditor#457]
改行コードの不可視文字を表示しているが、行頭での位置が、行頭でないときと一致せず不自然。
改行コード文字の位置を揃えて欲しい。

![p](https://cloud.githubusercontent.com/assets/7039581/10633237/60e43674-7824-11e5-8b3d-2b4193e1d5df.gif)

追記：失礼しました。CotEditor v2.2.2 (78) , OSX 10.11（15A284）

**Comment by 1024jp** [comment]
症状確認しました。
是正すべき挙動なのでなんとかします。

（今後バグ報告をする場合は、必ず CotEditor と OS のバージョンを記してください）

**Comment by 1024jp** [comment]
This is actually an enbug by #444.
`locationForGlyphAtIndex:` method of `NSLayoutManager` returns different `y` value depends on whether the line of the glyph is empty or not.
Not easy.

**Comment by 1024jp** [comment]
This issue will be solved on the next version 2.3.0.

----

この不具合は CotEditor 2.3.0 で修正されます。
