### ISSUE TITLE
極端なウィンドウの伸張を行うと、文字が歪む

### ISSUE THREAD

**Issue by khiri-co** [coteditor/CotEditor#458]
以下のアニメのように、文章が少ない行数でウィンドウを極端に伸び縮みさせると、それに従ってテキストフィールドも伸び縮みしてしまう。
CotEditor v2.2.2 (78) , OSX 10.11（15A284）
![output](https://cloud.githubusercontent.com/assets/7039581/10633628/0084a306-7827-11e5-9bcd-dc26d30528b1.gif)

**Comment by 1024jp** [comment]
これに関してはこちらでも認識しておりますが、現時点では「仕様です」ということにさせてください。
あまりカッコよくないので長期的には変更したいのですが...。

**Comment by 1024jp** [comment]
対策を施してみました。2.3.0-beta で様子を見て大丈夫そうなら 2.3.0 正式版に取り込みます。

**Comment by 1024jp** [comment]
I realized that this issue still exists.
