### ISSUE TITLE
新規保存の際のファイル名部分について　リクエスト

### ISSUE THREAD

**Issue by 84ma** [coteditor/CotEditor#464]
## 環境 
- CotEditor: 2.3.0-beta (80)
- システム: OS X バージョン 10.10.5（ビルド 14F1021）
- 言語環境: 日本語

## 簡単な説明

新規保存や別名保存の際のファイル名部分について
現状は、ファイル名がすべて（拡張子まで）選択された状態

![2015-11-06 10 15 55](https://cloud.githubusercontent.com/assets/7237118/10986714/cf014442-846f-11e5-94ac-026fdf7f73f4.png)

## 期待される挙動

添付のように、ファイル名の選択されている範囲が拡張子を含まない状態にしてほしい。
※CotEditorの154から2.1.6は、こちらの挙動となっています。
![2015-11-06 10 16 10](https://cloud.githubusercontent.com/assets/7237118/10986719/d3d72586-846f-11e5-83b6-2c6fef195fde.png)

**Comment by 1024jp** [comment]
本件は Sandbox の制約上技術的に無理です。
申し訳ないが諦めてください。

**Comment by 1024jp** [comment]
CotEditor 3.0.0 で実現できそうです。
