### ISSUE TITLE
pythonの入力補完について

### ISSUE THREAD

**Issue by ha810** [coteditor/CotEditor#468]
pythonスクリプトを書く際に、例えば「:」や「,」を入力すると入力補完で書類内の様々な単語が候補として上がって来てしまいます。
入力補完の設定は
- 書類に含まれる単語
- シンタックスで定義された単語

にチェック、更に

- 入力中に補完候補を表示

にチェックを入れた状態で使用しています。

CotEditorのバージョンは2.3.0(82)です。

**Comment by 1024jp** [comment]
状況がよくわかりません。例文を出していただけると助かります。

**Comment by ha810** [comment]
<img width="458" alt="screenshot" src="https://cloud.githubusercontent.com/assets/9996418/11014871/ea93d004-858b-11e5-9cf9-e7802df66927.png">

上記スクリーンショットでうまく伝わるかどうかですが、
「:」コロンを入力した時点で表示される補完候補が、スクリーンショットのような状態になります。
全単語を補完候補として表示してきているような印象です。

**Comment by 1024jp** [comment]
あ、再現しました。調査します。
もちろん好ましくない挙動なので修正します。

**Comment by 1024jp** [comment]
この望まれない挙動は次の CotEditor 2.3.1 で抑制されます。
不具合報告（いつも）ありがとうございます。

**Comment by ha810** [comment]
ご対応ありがとうございます。
よろしくお願い致します。
