### ISSUE TITLE
Duplicate Line action / 行の複製

### ISSUE THREAD

**Issue by ha810** [coteditor/CotEditor#471]
最新バージョンにて行編集が充実し、便利に使わせていただいております。
要望になりますが、「行の複製」があったら尚便利かと思い投稿させていただきました。

現在カーソルがある行の内容をそのまま下の行に複製するという挙動です。
スクリプトへの入力で「行」が渡せればスクリプトで対応も可能かとは思いますが、ネイティブに実装して頂けたら嬉しいです。
ご検討お願い致します。

**Comment by 1024jp** [comment]
他のエディタで「行の複製」アクションは見かけつつも必要度はそんなに高くないかなと抜かしていました。
使うということであれば加えましょう。

**Comment by ha810** [comment]
複製して部分的にちょっと修正して、のような作業を個人的にはよく行うので助かります。

**Comment by 1024jp** [comment]
「行を追加」アクションを次リリースの 2.3.1 に追加しました。

**Comment by ha810** [comment]
ご対応ありがとうございます。
