### ISSUE TITLE
不可視ファイルも表示してほしい

### ISSUE THREAD

**Issue by sfuku** [coteditor/CotEditor#473]
ファイルを「開く」時のダイアログでドットで始まる不可視ファイルなども選べるようにしてほしい。
理想的には表示のon/offのチェックボックスをつけもらえるとありがたいです。

**Comment by 1024jp** [comment]
オプションを押しながら「開く」メニュー項目を選択すると、お望みの挙動になると思います。
ちなみに、オープンダイアログを開いてからの不可視ファイルの表示/非表示の切り替えは、フレームワークの構造上実装することができません。

**Comment by sfuku** [comment]
不可視ファイルも開けたんですね、機能を把握していませんでした。
失礼いたしました。

**Comment by 1024jp** [comment]
いえいえ、この機能知らない人が多いだろうなとは私も思ってたので。クローズします。
