### ISSUE TITLE
Request: Separate the “Enable smart quotes and dashes” into “Enable smart quotes” and “Enable dashes”

### ISSUE THREAD

**Issue by handcoding** [coteditor/CotEditor#475]
Part of my workday involves creating ASCII-based UI prototypes. For instance, part of my documents might look something like this:

```
“Do you want to save your work?”

 -------------        ------------
|    Save     |      |   Cancel   |
 -------------        ------------
```

Within CotEditor’s Preferences → Edit, one of its options is:
> ☑ Enable smart quotes and dashes

In these sort of documents, I find that smart quotes can be quite useful for their aesthetics—but if I enable the “Enable smart quotes and dashes” setting, the hyphens (“-”) within the diagram are collapsed into dashes (“—”), which ends up spoiling the effect:

```
“Do you want to save your work?”

 ——————        ——————
|    Save     |      |   Cancel   |
 ——————        ——————
```

If it wouldn’t be too much trouble, I’d like to ask if you might be open to splitting the “Enable smart quotes and dashes” option into two separate settings, such as perhaps something like this?
> ☑ Enable smart quotes
> □ Enable smart dashes

If it were to be split into two options, I’d be able to enable smart quotes but omit smart dashes, which would be ideal for this sort of work.

Cheers,
Ashley

**Comment by handcoding** [comment]
(If it may help, here’s also a screenshot of that option within CotEditor’s preferences.)

![coteditor - preferences - edit](https://cloud.githubusercontent.com/assets/118319/11170000/f18b0e66-8b8c-11e5-9f8b-e860ba1f2201.png)

**Comment by 1024jp** [comment]
Hmm, I see your problem.
And I suppose also it's better to separate the option into each one.

The change itself is technically not so difficult.
However actually, the problem I'm recently facing is: there is no more space in Edit pane to add another settings.
It's probably about time to re-layout the Edit pane, but this takes time and needs careful consideration.
So I'm still not sure whether I'll re-design preferences panes on the next update, 2.4.0.

Well anyway, I'll consider how I can resolve this issue smartly (and possibly quickly).

**Comment by handcoding** [comment]
Thanks for looking into this—I really appreciate it!

**Comment by handcoding** [comment]
> However actually, the problem I'm recently facing is: there is no more space in Edit pane to add another settings.

Just to put this out there, as of CotEditor 2.4.3, it looks like there might be a bit of spare room at the bottom of the Edit pane ;). Might that offer the possibility of perhaps splitting the “Enable smart quotes” and “Enable smart dashes” options and then maybe moving the remaining Edit-pane options downward?
![coteditor 243 - edit pane](https://cloud.githubusercontent.com/assets/118319/13465702/750d442e-e05c-11e5-8a07-ec4d8e857dc3.png)

**Comment by 1024jp** [comment]
Sorry for keeping this issue on hold.

Yes, there is a room there, in English. But I need to keep this space for some localizations like German, the language that has long words. I cannot easily shift the options at the the bottom down.

<img width="662" alt="context menu" src="https://cloud.githubusercontent.com/assets/1165044/13594647/383c0c50-e549-11e5-8772-31a50f8e6517.png">

If you wanna control state of smart substitutions separatoly on the current CotEditor, one option is to set them from the main menu > Edit > Substitutions, or from the context menu as shown below. I know it works only with opened documents and needs to set every time you open a file. But it may help you.

<img width="465" alt="screen shot 2016-03-03 at 12 11 29" src="https://cloud.githubusercontent.com/assets/1165044/13594651/41b8f018-e549-11e5-9731-fd3c344c3c71.png">

**Comment by handcoding** [comment]
It had slipped my mind about the varying word lengths in other languages—you make a good point there.

And with my usual workflow, I tend to open and close files throughout the day, and I’m not sure that I’d always remember to set those options when I open a new file. So in the meantime, I’ll just remain patient until the time is right for these options to join the preferences dialog :).

**Comment by 1024jp** [comment]
😉

![screen shot 2016-04-11 at 15 41 30](https://cloud.githubusercontent.com/assets/1165044/14418746/e0f43e40-fffb-11e5-86eb-5897f979cd1b.png)

**Comment by handcoding** [comment]
@1024jp Hooray! That makes me happy :).
