### ISSUE TITLE
要望（入力補完・行機能等について）

### ISSUE THREAD

**Issue by ha810** [coteditor/CotEditor#476]
度々要望で申し訳ありません。
ご検討頂けたらと思います。

- シンタックススタイル毎に入力補完のON・OFFの設定がほしい。
	- コードのみではなくメモ帳として使用する場合もあるので、日本語の補完をOFFにしたい場合があります。例えばシンタックスがPlain TextやMarkdownの場合など。もっとスマートな実装方法があれば方法は問いません。
- 行機能についての要望（記載のショートカットについてはSublimetextのものですので、確認出来る環境がありましたらお願い致します。）
	- 行の削除：contol + shift + K
	- 行の上に空行を挿入：control + shift + return
	- 行の下に空行を挿入：control + return
- ShellScriptについて
	- スクリプトへの入力で「行」をサポートしてほしい。合わせてカーソル位置の情報も渡すことが出来ると、スクリプトで細かいテキスト操作が出来るような気がします（漠然としていて申し訳ないです）。

よろしくご検討願います。

**Comment by 1024jp** [comment]
- シンタックススタイル毎に入力補完のON・OFF
    - これについては、入力補完以外にもシンタックス毎に設定したい項目がいくつも出てくるのではないかと考えています（これとか #27）。なので、入力補完のみに対してシンタックス毎の設定を追加するということはしません。「ではどうするのか」ということになるのですが、ぼちぼち気に留めてはいるのですがまだ考えがまとまってないので現状後回しです。そのうちひょっこり実装されるかもしれません。
- 行機能
    - 行の削除
        - すでにあります
    - 空行を挿入
        - Sublime Text にそのようなアクションがあることは認識していますが、それ以外のエディタではあまり類例がなく、CotEditor で実装するかどうかは少々懐疑的な立場でいます。場合によっては今後追加する可能性もありますが、現時点ではあえて追加しないでいます。
        - ちなみに、以前同様のリクエストをもらった時に書いたスクリプトがあるので、ひとまずでよろしければお使い下さい。 ref. #290
- Shell Script
    - そのような細かな操作については AppleScript (JXA) を用いる姿勢を CotEditor は取っています。とはいえ AppleScript でも「行」に対する API は現在設けておらず、（AppleScript での「行」概念の導入を）どうしようかなと考えているところです。わりとおおがかりな改修になりそうなので二の足を踏んでいます。

なんだかはっきりしない回答ばかりになってしまいましたが、これが現時点でのスタンスとなります。

[ちなみに] Issue 管理の関係上、今後は要望毎に Issue を立ててください。一度に複数個立てていただいて一向に構いません。

**Comment by ha810** [comment]
ありがとうございます。

**Comment by 1024jp** [comment]
#580 と #581 に個別の Issue を立てたのでこの Issue は落とします。
