### ISSUE TITLE
METAFONTのシンタックスハイライトを追加したい/Add METAFONT syntax highlighting

### ISSUE THREAD

**Issue by VoD** [coteditor/CotEditor#477]
METAFONTのシンタックスハイライト用YAMLファイルを作成したのですが，取り込んでいただけないかと思います。

（YAMLがアップロードできないので，一旦txt形式で添付いたします）

[METAFONT.txt](https://github.com/coteditor/CotEditor/files/41658/METAFONT.txt)

**Comment by 1024jp** [comment]
ありがたいです。是非取り込ませてください（Twitter でお見かけしていいなぁと思っておりました）。

なお、本体に取り込む場合、ライセンスが自動的に CotEditor 同様 (Apache ver.2) となることをご了承ください。

**Comment by VoD** [comment]
了解しました。ありがとうございます。

**Comment by 1024jp** [comment]
いえこちらこそありがとうございます。
また謝辞等に名前を載せる際に当たって、並記すべき URL （ホームページ等）がありましら教えて下さい。

**Comment by VoD** [comment]
特にありません。
他に必要な情報などはあるのでしょうか？（すみません，不慣れなもので...）

**Comment by 1024jp** [comment]
了解です。
いただいたものを取り込みました。
次（多分今年中、くらい）リリースの2.3.2 で反映されます。

> 他に必要な情報などはあるのでしょうか？

いえいえ、これで十分です。

**Comment by 1024jp** [comment]
少し調べたのですが、シンタックス名としては「METAFONT」よりも「MetaPost」（言語名？）の方が的確なような気がするのですがいかがでしょう？
良ければこちらで変更しますが。

**Comment by 1024jp** [comment]
あ、いや、両者はちがうものなのかな。あまり良く知らないので、教えていただけると幸いです。

**Comment by VoD** [comment]
METAFONTとMetaPostは別の言語で，前者がビットマップ形式のフォントを作成し，後者はベクトル形式のフォントを作成するためのものです。下のリンクもご参考までに。

MetaPostはMETAFONTの構文に似せて作られているので，本当はキーワードにもう少し単語を追加すれば両方の言語に対応したハイライトが可能なのですが，（自分に必要なのが前者であるという理由で）METAFONT用のリストしか作成しませんでした。

https://oku.edu.mie-u.ac.jp/~okumura/texwiki/?MetaPost
https://oku.edu.mie-u.ac.jp/~okumura/texwiki/?METAFONT

**Comment by 1024jp** [comment]
いやはや私の早合点でした。解説ありがとうございます。
（もちろん METAFONT のままにします）
