### ISSUE TITLE
【要望】ファイルドロアを表示

### ISSUE THREAD

**Issue by ttakaichi** [coteditor/CotEditor#478]
簡単に言えば、JeditXにあるものと同じ機能が欲しいです。
常に横にファイルドロアを表示できると、アウトラインプロセッサのように他に書いたファイル名を並べて素早くアクセス、他の資料から関連ファイル、内容の整理ができて便利です。
また、タブ機能の要望が上がっていましたが、この機能があれば他部機能がなくても代替機能になるのではと思います。

**Comment by 1024jp** [comment]
duplicated. See #278.

---

たびたびこの手のリクエストはいただいていますが、現時点では、複数のファイルを単一ウインドウ上で扱うあらゆるタイプのファイル管理方法は実装保留となっています。

また、JeditX のような形式を実装するには目下でも以下の問題点があります。

- CotEditor は Sandbox 化されたアプリケーションであるため、ユーザが Finder やファイルオープンダイアログから能動的に開いたファイルやディレクトリでなければ読み込むことができない。
- ドロアは古い仕様であり現在では実装非推奨であるため、これから新しくドロアを実装できない。
