### ISSUE TITLE
Improving the Scroll Bar

### ISSUE THREAD

**Issue by jeffmikels** [coteditor/CotEditor#484]
When using a dark theme, I like having the scrollbar colors match the background and foreground colors, or even make the scroll bar position indicator only appear when scrolling. I'm willing to do the code to make it happen, if someone could point me in the right direction...

OR

By any chance, are the scroll bars already theme-able?

**Comment by 1024jp** [comment]
Sorry for the late answer.

This is actually a bug on the current CotEditor (I've just finally verified it today.). The light scroll bar style should be applied if the theme is a dark one. 

It will be fixed on the next CotEditor 2.4.0. Thank you for the feedback!
