### ISSUE TITLE
行メニューの上へ移動・下へ移動でテキストが選択されていない場合の挙動 / selection after "Move line"

### ISSUE THREAD

**Issue by ha810** [coteditor/CotEditor#491]
テキストが選択されていない場合（例えば行頭にカーソルがある状態）に
行メニューの上へ移動・下へ移動を行うと
行の移動が終わると次の行にカーソルが移動してしまいます。
行やテキストを選択して移動と行った場合と同様の挙動になると助かります。

バージョン 2.3.4 (95)

**Comment by 1024jp** [comment]
おっと、2.3.4 で行アクション系の選択範囲の計算をやり直した際にケース分け漏れをしてしまったようです。報告ありがとうございます。

もちろん修正すべき挙動なので次バージョンで直します。
（ただ、今のところ、次は 2.3.5 を出さず 2.4.0 に飛ぼうと考えているので、修正版リリースは少し先になってしまうかもしれません。とはいえ年度内には出ます。）
