### ISSUE TITLE
Autofill html

### ISSUE THREAD

**Issue by Haroenv** [coteditor/CotEditor#494]
When writing html, I use [emmet](http://emmet.io), so I'm used to writing `html`<kbd>tab</kbd>, which would output `<html></html>`.

Is there some option I'm missing or is this not implemented?

**Comment by 1024jp** [comment]
CotEditor does't support Emmet. I know there is a demand for it. 

Howerver:

- I have lots of tasks for CotEditor besides Emmet support.
- I personally never use Emmet

So, it's pending.

see #101
