### ISSUE TITLE
スニペットのキーバインドが編集できない / Can't edit snippet key bindings

### ISSUE THREAD

**Issue by aximov** [coteditor/CotEditor#496]
## 環境 

- CotEditor: 2.3.4 (95)
- システム: OS X バージョン 10.11.2（ビルド 15C50）
- 言語環境: 日本語

## 簡単な説明

環境設定>キーバインド>スニペット においてキーの編集ができません。環境設定>キーバインド>メニュー項目のキーは編集できます。

## 不具合が発生したときに行っていた操作、または再現手順

環境設定>キーバインド>スニペット においてキーを編集する操作。

## 期待される挙動

環境設定>キーバインド>スニペット においてキーを編集できること。

**Comment by 1024jp** [comment]
症状確認しました。

バグです。次バージョンで修正します。

報告ありがとうございます。

**Comment by 1024jp** [comment]
fixed on a7299596504051227da7c21b7b74487fc1f6eb96
