### ISSUE TITLE
音声入力がうまくいかない

### ISSUE THREAD

**Issue by Dolgorbie** [coteditor/CotEditor#497]
音声入力をしようとしてもうまくいかず何も動作しないか強制終了してしまうことがありました。再現性を確かめるために何度も繰り返しましたが、よく分かりませんでした．クラッシュレポートも一応いくつか保存しましたが，そのままペーストすると長いので，必要ならば助言をお願いします．
バージョン
OSX  10.9.5
Coteditor  2.3.4 (95)

**Comment by 1024jp** [comment]
ご報告ありがとうございます。
本件についてはこちらでも不具合を認識しており、すでに手元の開発版では修正済みです。
来月頃にリリース予定の次バージョンでは修正されるのでしばしお待ち下さい。
