### ISSUE TITLE
小文字の半角 x が入力できない

### ISSUE THREAD

**Issue by aximov** [coteditor/CotEditor#498]
## 環境 

- CotEditor: 2.3.4 (95)
- システム: OS X バージョン 10.11.2（ビルド 15C50）
- 言語環境: 日本語

## 簡単な説明

小文字の半角 x が入力できない。

## 不具合が発生したときに行っていた操作、または再現手順

文書作成画面において，OS X 標準の入力ソース「英語 (U.S., British, Dvorak, ABC)」「日本語」または Google 日本語入力 (ひらがな，英数) を用いて小文字の半角 x を入力できない。ただし，OS X 標準の「日本語」または Google 日本語入力「ひらがな」を用いて，何らかの文字に続けてならば入力できる。e.g. ｋｘ，ｂｘ，ｄｘ... 一方，文書保存ダイアログや検索ウィンドウ，環境設定ウィンドウでは x を入力できる。
なお大文字の X は文書作成画面でも入力できる。

## 期待される挙動

文書作成画面において小文字の半角 x を入力できること。

**Comment by 1024jp** [comment]
本件こちらで再現できません。

以下を試したときに挙動が改善するかに興味があります。

- 環境設定 > キーバインド でメニュー項目およびスニペットのキーバインドを一旦デフォルトに戻す（両方のタブで「デフォルトに戻す」ボタンを押す）
- システムを再起動する

上記で改善しない場合、以下の情報をいただけると何か手がかりになるかもしれません。

- Karabiner などキーマップを変更するソフトウェアを使用しているか
- 使用しているキーボード
- [できたら] 他のアカウントでも同様の症状が再現するか

宜しくお願いします。

**Comment by aximov** [comment]
- 環境設定 > キーバインド でメニュー項目およびスニペットのキーバインドを一旦デフォルトに戻す（両方のタブで「デフォルトに戻す」ボタンを押す）

上記によって問題は解消しました。ありがとうございます。

**Comment by 1024jp** [comment]
返信ありがとうございます。ひとまずは解決してよかったです。

ご存知の通り、2.3.4 はキーバインド登録まわりにバグがあるので、次リリースの 2.4.0 まで編集を待っていただけると安全かと思います。

また念のため、2.4.0 ではこのようにキーバインド設定が壊れた場合でもこのような事態にならないようにひとつ安全策を加えました。
