### ISSUE TITLE
大きなサイズのUTF-8の文書を正常に開けない / Cannot open large size UTF-8 document

### ISSUE THREAD

**Issue by n00** [coteditor/CotEditor#499]
大きなサイズのUTF-8の文書を開くと「ISO 2022-JP」や「欧米 (Mac OS Roman)」で開かれてしまい、UTF-8での再解釈もできません。
文字コードが違うためでしょうか、文書は途中で切れてしまい、大部分が表示されません。
シングルバイト文字を検索をすると表示されていない部分のそれらが一覧として正確に表示はされます。
検索結果一覧内にあるダブルバイト文字は文字化けして見えます。

**Comment by 1024jp** [comment]
ご報告ありがとうございます。

ただ、これだけの曖昧な情報ですと問題をこちらで特定することができません。
最低限不具合報告は以下の情報を添えてください。

1) OS のバージョン
2) CotEditor のバージョン

また、このような場合問題が発生するファイルを何らかの方法でこちらに送っていただけると一番手っ取り早く原因究明がスムーズですが、そう人に渡せるファイルとは限らないでしょうから、本件の以下の情報が知りたいです。

- 「大きな」が具体的にいくつなのか（ファイルサイズ）
- 同等のこれより大きいサイズの別のファイルを開いた時も同様の問題が発生するか
- 他のエディタで開くなどして調べると、途中で切れる部分のファイルの前後（数文字で良いです）には何が書いてあるか（途切れている前後1行程度のスクリーンショットがあるとさらに助かります）
- ウインドウの表示設定は「折り返す」になっているか

また、以下の操作をした時にどうなるかに興味があります。

- メニューバーの「開く...」からオープンダイアログを出した上でエンコーディングメニューで「Unicode (UTF-8)」を指定した上でファイルを開いた場合。
![screen shot 2016-01-28 at 13 34 11](https://cloud.githubusercontent.com/assets/1165044/12635171/d715d1da-c5c3-11e5-9f9d-04656d7c5b0e.png)

- （折り返している場合）途中で途切れている文書を開いた状態で、「折り返す」を解除すると、表示できる部分に変わりがあるか

**Comment by n00** [comment]
1) OS のバージョン
10.8.5での問題でした。

2) CotEditor のバージョン
2.4.4

開けないファイルはこのようなsqlでした。
[hogehoge.txt](https://github.com/coteditor/CotEditor/files/185768/hogehoge.txt)

他にもPDFのテキストをコピペすると文字が全て消えたり、最下部までキャレットを移動すると最上部に飛んでしまったりと、OSが古いと駄目なようですね。

**Comment by 1024jp** [comment]
ありがとうございます！10.8 でしたか。おかげさまで原因をほぼ特定できました！添付ファイル大変参考になりました。おそらく次回までには何らかの手が入れられると思います。

また、迂回策として、目下は環境設定の「編集」の「その他の不可視文字」を表示する設定にすると、この問題は回避できるかと思います。

> 他にもPDFのテキストをコピペすると文字が全て消えたり、最下部までキャレットを移動すると最上部に飛んでしまったりと、OSが古いと駄目なようですね。

なかなか毎回全バージョンを十分テストする時間が取れずいまいちで申し訳ないです。
そろそろ古いOS出のサポートは切ろうかとも考えているのですが、現状ではサポートをうたっているので、不具合があればもちろん潰します。具体的に報告いただければ検証いたします。

**Comment by 1024jp** [comment]
イシュー内容を読み飛ばしていました。

文書が途中までしか表示されない件については修正が済んだのですが、文字コードが誤って認識される件については、頂いたファイルでも再現ができませんでした。このファイルも UTF-8 以外で解釈されてしまいますか？

> 再解釈もできません

が具体的に「どのようにできないのか」が知りたいです。

→ どのような操作（例：ツールバーのエンコードメニューから「Unicode (UTF-8)」を選択）をしてどのような結果が返ってきたか（例：なにも起こらない、「○○」と書かれたダイアログが表示される）。

**Comment by n00** [comment]
文字コードの件ですが、先の添付ファイルでは正常に認識しますね。
問題の実物は出せませんが、10MB程度のsqlで最初のダブルバイト文字が相当下に位置する場合に解釈出来ないようです。
（例：ツールバーのエンコードメニューから「Unicode (UTF-8)」を選択）
これを行うと「再解釈できません。」というダイアログが表示されます。

**Comment by n00** [comment]
> 他にもPDFのテキストをコピペすると文字が全て消えたり、最下部までキャレットを移動すると最上部に飛んでしまったりと、OSが古いと駄目なようですね。

この件も「その他の不可視文字」の表示で解決しました。
[hogehoge.txt](https://github.com/coteditor/CotEditor/files/187250/hogehoge.txt)
添付ファイルで「その他の不可視文字」を非表示としてキャレットを最下部まで移動しようとするとキャレットが消えます。
行数を増やすとスクロールし最上部が見えるようになります。
本件別立てが良ければお願いできますか？

**Comment by 1024jp** [comment]
お返事が遅くなりました。

先ほど CotEditor 2.5.0 のベータ版をリリースしました。
テキストが途中までで途切れてしまう問題、またキャレットが飛ぶ問題はおそらく対応できているのではないかと思います。
ただ、エンコーディング変更についてはこちらでまだ再現できていないので、修正ができていません。
しかし、このエンコーディングの件もこの途中で途切れる問題に関わっているかもしれず、この場合前記の症状を修正した影響で同時に回復している可能性もあります。

つきましては、お手間でなければこちらを試してみてこれら症状が回復されているかを教えていただけると幸いです。

https://github.com/coteditor/CotEditor/releases/tag/2.5.0-beta

**Comment by n00** [comment]
確認しました。先の添付ファイル両方とも問題なさそうです。
ただ、最初の問題は未解決でした。
---
再解釈できません。
ファイル“/Users/hogehoge/Library/Containers/com.coteditor.CotEditor/Data/Desktop/hogehoge.sql”はエンコード“Unicode（UTF-8）”で再解釈できませんでした。
---
と出ましす。
問題のsqlは MySQL dump 10.14  Distrib 5.5.40-MariaDB, for Linux (x86_64) で出力したものだったのですが、調査した結果、バイナリデータを16進でdumpしたものが混入する時に問題が起こるようでした。
OS 10.10.5 でも同じ結果でした。
サンプルを添付します。
[hogehoge.txt](https://github.com/coteditor/CotEditor/files/216872/hogehoge.txt)

**Comment by 1024jp** [comment]
📝 Note
__Error code__: 261 `NSFileReadInapplicableStringEncodingError`

**Comment by 1024jp** [comment]
テストありがとうございました。
途中で途切れる問題に関しては解消したようなので良かったです。

さて、エンコーディングの方ですが、頂いたテストファイルで検証しました。
結果としてはファイル自体に UTF-8 として不正な文字が含まれるため解釈できないようで、であれば現在の挙動は妥当なものであると言えます。
純粋な「欧米（ASCII）」で再解釈すると一応コード部分はおおまかには読めるかと思います（当然 ASCII 外の文字が化けますが）。
他のいくつかのエディタでは「不正なシーケンスを無視する」ことで無理やり表示させているようですが、CotEditor の場合は Cocoa フレームワークにべったりな関係上、そのようにサニタイズしたデータを編集・上書きした際に意図せぬデータ欠損が生じるため、これに関しては「仕様です」という答えにさせてください。
