### ISSUE TITLE
Variant characters of Shift-JIS / Shift-JIS の異字体の扱い

### ISSUE THREAD

**Issue by yosiot** [coteditor/CotEditor#500]
エンコーティングが Shift-JIS のテキスト・ファイルを開いたところ，先頭行の先頭文字が「高」の異字体である「はしごの高」である内容でしたが，CotEditor はこの一文字をスキップし，次の文字から。こ
の「高」には問題があり (規格外でしょうが) 次の 2 つの異なる表現を持ちます。

  16進表現で FB FC は IBM拡張文字，   16進数表現で EEE0 は NEC選定IBM拡張文字

(1) できればどちらの表現であっても，この文字を異字体の「高」として表示するのが望ましいのです
    が，そうでなくとも印字不能文字などを記号で表現することが望ましいと思います。

よろしくご検討ください。

**Comment by 1024jp** [comment]
まず質問・要望がある際は最低限必ず以下の情報を下さい。対応ができません。

- OS のバージョン
- CotEditor のバージョン


また、今回のようなケースの場合はできれば以下を教えてください。

- 本文に指定しているフォント
- 問題が起こるエンコーディング名（正確に）

-- 

髙 (はしごだか) は拡張文字であり Shift JIS には含まれない文字であるためエンコーディングが「__日本語 (Shift JIS)__」のときに表示ができないのは妥当なのではないでしょうか。

ややこしいのですが、CotEditor が扱える Shift JIS には以下の4つがあります（詳しくはヘルプの「Shift JIS 系のエンコーディングの違い」を参照してください）。

- Japanese (Shift JIS): shift_jis
- Mac OS : x-mac-japanese
- Windows, DOS : cp932
- Shift JS X0213 : Shift_JIS

このうち「__Windows, DOS__ (CP932)」であれば IBM拡張文字 に対応しているため FBFC, EEE0 双方のしご高も表示できるかと思います。

いかがでしょうか。

**Comment by yosiot** [comment]
最低限の基本事項を無視した質問をしたこと，たいへん失礼しました。お詫びいたします。
ご教示いただいた「Shift-JIS系のエンコーディングの違い」を読み，理解しました。これまで
ろくに理解もしていないで使っていたことを恥ずかしく思います。中でも「shift-jis」と「cp932」
は，違いを意識しておりませんでした。お陰で「Windows, DOS (CP932)」を選択して解決しま
した。本当にありがとうございました。

最後に，意見を述べますので，その前に当方の環境を書きます。
1. OS のバージョン： 10.9.5 および 10.11.3
2. CotEditor のバージョン: 2.3.4(95)
3. CotEditorの本文表示で使用しているフォント：Ricty Regular version 3.2.4
4. 問題が起こるエンコーディング名 (正確に)：Japanese (Shift JIS): shift_jis
                      および Mac OS : x-mac-japanese

意見：現状の CotEditor では「はしごの高」のような拡張文字を含むテキストを表示する際，
「Japanese (Shift JIS): shift_jis」や「Mac OS : x-mac-japanese」のエンコーディングを選択し
た場合，「はしごの高」のような拡張文字をスキップして表示する扱いにしているように思え
ます。どう扱うかは悩ましいところなのですが，できれば当該文字に位置に「印字できない文
字」の記号を表示すればいいような気がします。しかし，表示すべきテキストにそのような記
号が埋め込まれていた場合には，このような措置は問題を引き起こします。ですので，「テキ
ストが正しく表示できない文字を含む」という趣旨の警告メッセージを CotEditor が表示して
くれると助かります。

最初からテキスト・ファイルの 16進数表現を調べれば，当該箇所が空でないことは分かるこ
とですが，ふつうは，なかなかそのようなことはしませんので。

**Comment by 1024jp** [comment]
長い間オープンのままにしておりましたが、当時からエンコーディング判定の方法が変更になったこともあり、現状このようなファイルをJapanese (Shift JIS)で開こうとした場合は非互換文字を無視するのではなく書類オープン時にダイアログが出るようになったことから、このissueはクローズします。

もし、現状でも特定の条件下で同じような不具合が出るようであれば新規issueを立ててください。
