### ISSUE TITLE
Release CotEditor 2.4.1? / CotEditor 2.4.1 をリリースする？

### ISSUE THREAD

**Issue by 1024jp** [coteditor/CotEditor#505]
CotEditor 2.4.1 has been accepted and released today.
However it contains a serious bug on Mavericks  (again 😨).

I've already submitted the fixed version (2.4.2) to the iTunes Connect. Anyway, 2.4.1 should be tagged and the non-AppStore version may also be released somehow. I suppose we shouldn't update the appcast and just skip the 2.4.1.

---

CotEditor 2.4.1 がリリースされたのですが、またバグを埋めてしまい、Mavericks 以前で正常に動きません。現在 2.4.2 の特急審査を申請していますが、いずれにせよ 2.4.1 のタグを打ったりアーカイブとして 2.4.1 のバイナリを（少なくても）GitHub 上の releases には載せておいたほうが良いかと考えています。その辺りの作業を @usami-k さんにお願いできればと思います。

念のため、appcast は更新せずに 2.4.1 はスキップして 2.4.2 に飛ぶ方向で考えています。

なお 2.4.2 も明日頃にリリースされるはずです（別 Issue を立てます）。慌ただしくて申し訳ありません。

**Comment by usami-k** [comment]
CotEditor 2.4.1 について、Git タグを作成して、バイナリを GitHub releases に置きました。なお、Web のアーカイブページや appcast は、今回は更新していません。
