### ISSUE TITLE
Bug: “Link URL in document” makes CotEditor think that the file has changed (CotEditor 2.4.2 / 105)

### ISSUE THREAD

**Issue by handcoding** [coteditor/CotEditor#507]
I like CotEditor’s “Link URL in document” feature, but when that feature is enabled, CotEditor seems to think that unchanged documents have been changed.

Here’re some steps to reproduce:
 1. In System Preferences → General, check “Ask to keep changes when closing documents.” _(If you’re curious, [here’s what “Ask to keep changes when closing documents” does](http://tidbits.com/article/13187).)_
 2. In CotEditor → Preferences → General:
    * Uncheck “Enable Auto Save with Versions”
    * Uncheck “Link URL in document” (for now)
 3. Paste this text into a new document in CotEditor and save the file:
    ```
    * What the "Show Style Guides” and “Show Direct Formatting Guides” options do within Word:
	http://savethesemicolon.com/2011/04/16/formatting-guides-in-word-for-mac-2011/

    * A bunch of handy Word shortcuts:
	http://jeromyanglim.tumblr.com/post/37897099625/list-of-important-hidden-shortcut-keys-for
    ```
 4. Close the file that you just saved.
 5. Go to CotEditor → Preferences → General and check the “Link URL in document” option.
 6. Open the test file that you just closed. Then immediately close it again.

At this point, CotEditor will ask if you’d like to save your changes—but that doesn’t make sense because the file shouldn’t have any changes.

**Comment by 1024jp** [comment]
Thank you for always creating easy-to-understand reports.
Just as you said, the current behavior is unwanted and rather a bug. It must be fixed.

I also noticed I should improve the timing to update links, e.g. after paste block of sentences including URLs.

I'll fix both on the next version.
