### ISSUE TITLE
要望 保存時のBOM付け / Add BOM on saving

### ISSUE THREAD

**Issue by freeak** [coteditor/CotEditor#509]
ファイルによってBOMつけるか否か異なるので、設定画面からではなく、保存時のファイル名付ける画面か、ツールバーに、BOMありなし項目を置けるようにしていただきたいです。

設定画面からUTF-8時のBOM付けができますが、普段BOM無しで、他の人と共有するファイルのみBOM付けしたい場合があります。(BOMなしだとSharePoint に上げたテキストをブラウザ上で開くと文字化けするので)

よろしくお願いします。

**Comment by 1024jp** [comment]
そうですよねぇ、私もこれはぼんやり思っていたので近いうちに対応します。

どのような UI にするかはまだ決めきれていないのですが、おそらく保存パネルにつけることになると思います。

**Comment by freeak** [comment]
ありがとうございます。ぜひぜひ 実装を心待ちにしています。

**Comment by 1024jp** [comment]
![screen shot 2016-04-09 at 23 20 45](https://cloud.githubusercontent.com/assets/1165044/14404149/90f52ad2-feaa-11e5-88f5-357cc537170c.png)
