### ISSUE TITLE
「フォーマット」＞「不可視文字を隠す」メニュー項目が動作しない（ように見える）

### ISSUE THREAD

**Issue by tsawada2** [coteditor/CotEditor#510]
## 環境 

- CotEditor: 2.4.2 (105)
- システム: OS X バージョン 10.11.3（ビルド 15D21）
- 言語環境: 日本語

## 簡単な説明

以下の2つの現象の合わせ技により、「不可視文字を隠す」メニュー項目が動作していないように感じてしまいます。
1. 「フォーマット」＞「不可視文字を隠す」メニュー項目が、実際の状態に関係なく「不可視文字を隠す」のまま（「不可視文字を表示」と切り替わらない）。
2. さらに「不可視文字を隠す」を選択しても、不可視文字が表示されたままである。しかし再描画操作、例えば、テーマを切り替えると不可視文字が隠れる。（逆も同様）

## 不具合が発生したときに行っていた操作、または再現手順

1. 「編集」環境設定の「不可視文字：」で「不可視文字を表示」及びその配下のすべてのチェックボックスにチェックを付けておく。
2. 「ファイル」＞「新規」と選択し、新規書類に「あいう  え	お」などのような不可視文字を含む語句を入力する。
    - この時、不可視文字がシンボルで表示されていることを確認する。
3. 「フォーマット」＞「不可視文字を隠す」を選択する。
	- この時、不可視文字は表示されたままである。
4. 「フォーマット」メニューを開くと、「不可視文字を隠す」メニュー項目が存在する。
5. ここで「フォーマット」＞「テーマ」サブメニューから現在と異なるテーマを任意に選択する。
6. テーマが変わる。
    - この時、同時に不可視文字も隠れる。
7. 再度「フォーマット」メニューを開くと、やはり「不可視文字を隠す」メニュー項目が存在する。

## 期待される挙動

- 再現手順3. で不可視文字が隠れること。
- 再現手順4. 及び 7. では、メニュー項目が「不可視文字を表示」に切り替わること。

## 補足

現象1. に関しては、`-[CEEditorWrapper toggleInvisibleChars:]` 内で、 CEEditorWrapper 自身の `showsInvisibles` プロパティの更新が必要ではないでしょうか？

**Comment by 1024jp** [comment]
ぬ、確かにおかしいですね。直す必要がありそうです。
報告ありがとうございます。後ほど真面目に検証します。

**Comment by 1024jp** [comment]
さわっちのご指摘通り、2つ組み合わさっていました。
切り分け助かります 🍣
