### ISSUE TITLE
Trim Whitespace on Save

### ISSUE THREAD

**Issue by jeffmikels** [coteditor/CotEditor#512]
Feature request: have an option to trim extra whitespace at the end of lines and at the end of the file whenever it is saved.

**Comment by 1024jp** [comment]
I know some of text editors have this feature, and it looks not so hard to implement.
I'll try it :)

**Comment by 1024jp** [comment]
![screen shot 2016-02-28 at 20 29 36](https://cloud.githubusercontent.com/assets/1165044/13378931/00e8f88a-de5a-11e5-92db-b9af0aad6a31.png)

Finish.

This will be applied either CotEditor 2.4.4 or 2.5.0 (I'm not sure at the moment whether I'll release 2.4.4).
