### ISSUE TITLE
English tweak: “Link URL in document” → “Link URLs”

### ISSUE THREAD

**Issue by handcoding** [coteditor/CotEditor#515]
Hi there,

I recall from one of CotEditor’s tweets or something that you were open to improvements to the English in the app. So here goes:

Under Preferences → General, one of the options is “Link URL in document”. I’d recommend changing that to “Link URLs” since CotEditor will link all URLs when that’s enabled (rather than just a single URL). 

I also think it’d be fine to leave off “in document” if you had wanted to. After all, none of CotEditor’s other options mention “in document.” For instance, the spellcheck option says “Check spelling as you type”—not “Check spelling as you type in document” (and that’s fine).

— Ashley

![coteditor 243 - preferences - general](https://cloud.githubusercontent.com/assets/118319/13466015/c508c56a-e05d-11e5-8f28-fcd13574fab6.png)

**Comment by 1024jp** [comment]
Thank you for the suggestion. I'll fix it on the next version 😀

And to omit the "in document", you are right. However, I'm afraid of whether every user can understand just only with "Link URLs" in this context. By spelling check and other options, it is clear. How do you think? Is it enough?

**Comment by handcoding** [comment]
> And to omit the "in document", you are right. However, I'm afraid of whether every user can understand just only with "Link URLs" in this context. By spelling check and other options, it is clear. How do you think? Is it enough?

I think it could be okay to leave off “in document.” All the same, there’s also little harm in retaining “in document” if you might feel more comfortable with that version.

**Comment by 1024jp** [comment]
I eventually removed the words "in document" according to your advice. Thanks 😋
