### ISSUE TITLE
ダイアログに「アプリケーション”CotEditor.app"を開けません。」

### ISSUE THREAD

**Issue by shishida** [coteditor/CotEditor#518]
## 環境 
- CotEditor: 2.4.3 (108)
- システム: OS X バージョン 10.11.3（ビルド 15D21）
- 言語環境: 日本語

## 簡単な説明
テキストファイルをCotEditorで開くように設定されている状態で、テキストファイルをダブルクリックするといったん「アプリケーション”CotEditor.app"を開けません。」というダイアログボックスが表示されます。
ファイルは問題なく開けて、ダイアログボックスは「OK」を押すと閉じるので使用上の問題はありませんが、なぜこのようなダイアログが出るのか疑問です。

## 不具合が発生したときに行っていた操作、または再現手順
OS再起動の直後に再現しやすいようですが、それ以外でも時々発生します。

**Comment by 1024jp** [comment]
うーん、つきなみな回答ですが、

1. CotEditor.app を一度丸ごと捨てて再インストール
2. /アプリケーション/ユーティリティ/ディスクユーティリティ.app で「First Aid」を実行

でなにか改善しないでしょうか？
App Store 経由でのダウンロードか coteditor.com からの直接のダウンロードかどうかも知りたいです。

**Comment by 1024jp** [comment]
あらら、だめでしたか。

となると、うーん、他に考えられることとしては、システムが適切な CotEditor を見つけられないとかでしょうか。
該当のテキストファイルを Dock や Finder などの CotEditor のアイコンに直接ドラッグ＆ドロップしたときに同様のダイアログが出ることはありますか？
/Applications/ 直下以外(たとえば別パーティションなど) に CotEditor がインストールされている可能性はありますか？
コンソール.app になにかログが出ているかにも興味があります。

**Comment by shishida** [comment]
たびたびすみません。
App Storeからのインストールですので、/Applications/直下にインストールしています。
コンソールのログには、以下のようにlibdispatch.dylib に関するものがいくつか出ています。

2016/03/07 17:55:25.919 CotEditor[784]: CGSReenableUpdate:  3   libdispatch.dylib                   0x00007fff94baa871 _dispatch_call_block_and_release + 12

セーフブートしてみたらしばらく発生しなくなったので、とりあえず様子見にしようかと思います。
何度もありがとうございました。お手数をおかけいたしました。

**Comment by 1024jp** [comment]
こちらこそお役に立てず申し訳ない。

この辺りに関して CotEditor は特に特殊なことをしているわけではないので、環境依存の問題の可能性が高いです。

また以下のコンソールログについてはまた別件の理由に依るもので本件とは関係がない事象です。
（直さないといけないと思いつつ原因が突き止められておらず放置しています...。）

> ```
> 2016/03/07 17:55:25.919 CotEditor[784]: CGSReenableUpdate: 3 libdispatch.dylib 0x00007fff94baa871 _dispatch_call_block_and_release + 12
> ```

**Comment by 1024jp** [comment]
CotEditor 本体とは関係が薄そうなので、本件は一旦クローズとします。
