### ISSUE TITLE
How to create bundles or plugins?

### ISSUE THREAD

**Issue by danielzilli** [coteditor/CotEditor#520]
Thank you guys for this great editor.

I'm wondering if is there any documentation in how to create plugins or bundles for CotEditor? I'm thinking about things like languages auto-complete or other features that you don't want to put in the core.

**Comment by 1024jp** [comment]
There is actually no so-called plug-in like features in CotEditor. 

You can extend our app via script that is documented in the help menu.
Or, by auto-completion, CotEditor uses terms defined in syntax style. So you can modify it from Prederenses > Format > Installed styles list.

**Comment by danielzilli** [comment]
Ok. I'll take a look at it. Thanks.
