### ISSUE TITLE
Bug in CotEditor 2.4.3: File → Open Recent menu is always empty

### ISSUE THREAD

**Issue by handcoding** [coteditor/CotEditor#521]
Hi there,

As of CotEditor 2.4.3, it would seem that its File → Open Recent menu is always empty.

Here’re some steps to reproduce:
1. Open an existing file in CotEditor
2. Close the file
3. Go to File → Open Recent

* Expected result: The file that you had just opened is listed in CotEditor’s “Open Recent” menu.
* Current result: There aren’t any files listed in CotEditor’s “Open Recent” menu.

![file - open recent - coteditor 2-4-3](https://cloud.githubusercontent.com/assets/118319/13615972/74e86330-e53d-11e5-8545-21aeb604c5dd.png)

**Comment by 1024jp** [comment]
This is weird, 'cause it works fine under my environment.
However, I've seen before an user mentioned about a similar problem on Twitter. So, there must be something but I'm not sure if CotEditor causes it.

Does the following discussion help you?
https://discussions.apple.com/thread/1873442?tstart=0

**Comment by handcoding** [comment]
By the way, I just updated CotEditor to the latest version (2.4.4), and now it’s File → Open Recent menu seems to be working again. (And I didn’t make any other system changes.) ¯\_(ツ)_/¯

Anyhow, feel free to mark this issue as issue as “Resolved” or “Fixed” or the like.

**Comment by 1024jp** [comment]
Oh, thank you for the progress report and I'm relieved to hear that 😊
So I close this issue.
