### ISSUE TITLE
検索画面のハイライトボタンの廃止について / independent highlight action & group highlighting

### ISSUE THREAD

**Issue by 84ma** [coteditor/CotEditor#522]
> 
「すべて検索」アクションでエディタ内のマッチ部分のハイライトも同時に行うように改良し、単独の「ハイライト」アクションを撤去

CotEditor2.4.0以降検索ウインドウから「ハイライト」ボタンが無くなり、「すべて検索」ボタンに機能統合されましたが。

「すべて検索」を使用したところ正規表現の括弧によるグループ別の色分けがされなくなりました。
グループ別の色分けの機能は、正規表現の精度確認や検証時に非常に重宝しておりました。
グループ別の色分けの機能は、廃止されたのでしょうか？

希望
1.正規表現のグループ別の色分けの再対応
2.検索ウインドウ内のハイライトボタンの復活 もしくは、検索メニューのみでも良いので、「ハイライト」と「ハイライトの解除」の復活

ご一考頂ければ幸いです。

**Comment by 1024jp** [comment]
グループ分けの機能は作業量の関係で一旦サポートしない状態でリリースしていたのですが、
この度再実装したので、次バージョンで復活予定です。

ハイライト単品のアクションについては、ショートカットキーを割り当てているユーザもいるとは思うので、メニュー内で復活させるかは検討しています。多分やります。ボタンはつけないです。

**Comment by 84ma** [comment]
了解しました。
よろしくお願いします。
