### ISSUE TITLE
「すべて置換」後のアクティブウィンドウに関して / Active window after "Replace All"

### ISSUE THREAD

**Issue by yuhei-mukoyama** [coteditor/CotEditor#523]
検索ウィンドウの挙動で「すべて置換」の際のみ、実行後アクティブウィンドウが検索ウィンドウではなく、ドキュメントウィンドウになります。

その挙動が誤っているかと言われると疑問が残るのですが、個人的には他のボタン同様に検索ウィンドウをアクティブな状態にして頂きたいです。

他の検索ボタンと挙動が同じであろう前提でショートカット操作を行っていると、検索ウィンドウに対して「Cmd + W」を実行しているつもりがドキュメントウィンドウ側に行っていて、イライラすることが多々発生しています…。

また、古いバージョンの CotEditor は自分の希望する挙動だったと記憶しており、たぶんその時の癖がいつまで経っても治らず誤った操作を行う要因になっているのだと思います。

よろしくお願いします。

**Comment by 1024jp** [comment]
あら、これは別に意図している仕様変更ではないので元に戻します 😉

**Comment by 1024jp** [comment]
追調査をしたところ、以前の CotEditror も現在と同じ振る舞いでした。
これは、「すべて置換」では進捗のシートを表示するため、その時に書類ウインドウの方がアクティブになってしまうためです。
OS X 的にはわりと妥当な振る舞いということになります。

とはいえこの現在のが CotEditor 的にベストかと言われるとよくわからないので、もちょっと解決法を含め調べてみます。

**Comment by yuhei-mukoyama** [comment]
本当ですか！これは失礼いたしました。

そうしたら検索ウィンドウが常に前面に来るようになった結果だと思います。それまではアクティブウィンドウが変われば、そのウィンドウが前面に出てくるようになっていたということなので。

これもまた個人的な話になってくるのですが、前面に出てきた邪魔な閉じることのできるウィンドウは「Cmd + W」で消すという挙動が反射神経的に行なわれている結果だと思います。これがドキュメントの横に置くべきインスペクタや、フォントパネルなどであればいいのですが、検索ウィンドウは基本的にドキュメントの手前に出てくる物なのでそういう例外的なウィンドウとは違う認識をしてしまっているのだと思います。

どういった経緯でこの常時前面スタイルになったのか存じ上げないのですが、CotEditor 的なベストという意味では、検索ウィンドウが常に前面にあるのがベストなのかというのが疑点でしょうか。

OS X で 検索窓にこういう常時前面表示の検索窓が利用されるシーンはあまり見覚えがありません。
また、最近はドキュメントウィンドウの下部に結合されていっているイメージがあります。

トレンドに乗っかる意味では、ドキュメントウィンドウ下部に出すのが正解なのかもしれないですね。
改修が面倒だと思いますが :sweat_smile:

**Comment by 1024jp** [comment]
OS X ではパネルは Esc キーで閉じます。検索パネルもパネルなので Esc キーで消せます。Esc キーで書類ウィンドウは閉じないので、誤閉じは防げます。対処療法ですが。
CotEditor はの検索パネルは「パネル」なのでパネルとして振る舞います。常に最前面にくるのもパネルとしては妥当な振る舞いだと思います。
（Pages.app の検索パネルは同様の挙動をします。Apple 自らが作っている document-based のアプリケーションである Pages.app がどのような振る舞いをするかに私は非常に関心があります）
まぁ、キーになるタイミングとかは調整できるので考えます。

> OS X で 検索窓にこういう常時前面表示の検索窓が利用されるシーンはあまり見覚えがありません。
また、最近はドキュメントウィンドウの下部に結合されていっているイメージがあります。
> 
> トレンドに乗っかる意味では、ドキュメントウィンドウ下部に出すのが正解なのかもしれないですね。
> 改修が面倒だと思いますが :sweat_smile:

私はウィンドウをバカバカ出す Macintosh 的な UI が好きなので、トレンドだからといって追従はしないでしょう。特にウィンドウ下部は最悪！ 絶対やりたくありません。
Pages.app なんかは検索が別パネルです。TextMate や TextWrangler のような古参エディタも。まぁ（悪しき）文化ですね。
CotEditor はエンジニア的エディタ文化と Mac の文化が UI レベルでコンフリクトした時は後者を取るようにしています。また同時に、私がコードを書く限り私の好みが優先されるでしょう。

**Comment by yuhei-mukoyama** [comment]
ありがとうございます。
esc キーで閉じられるんですね。なるほど。その発想はなかったです。

パネルの扱いが多様化してきた GUI の中で少し浮いた状態になりつつあるなと思うところもあるのですが、今回の件に関しては大きな不満があるわけではなく CotEditor の方針に従うことに異論はありません。
特に下部に表示されるようなパターンの場合、検索結果のパネルをどうするかなどを考えるとひどく複雑になりそうですし、そうあるべきだと思っているわけではありませんので、あまりお気になさらないでください。失礼しました :pray: 

となると、検索パネルは現状がベターということで、論点が最初に戻るかと思うのですが、そもそも進捗のシートがドキュメント側に表示されるべきなのかなど色々考えるところが広がってきますので、あまり私が下手に考えない方が良さそうですね :sweat_smile:

**Comment by 1024jp** [comment]
いえいえ、自分と違う使い方をしているユーザの意見で気づかされることも多いので、なんか気ついたことがあったらどんどんコメントをいただけるの大歓迎です（フィードバックとはそういう役割のものですし）。

進捗シートは実のところ、置換作業中にユーザが文章を編集できないようにする役割もあります（置換中に元文章いじられると困っちゃうからね）。とある特定のウインドウ（ドキュメント）に対して行われる処理なのでこの場合は明確にドキュメント側に出すのが正解かな。

**Comment by 1024jp** [comment]
遅くなりましたが、本件仕様を変更し、「すべて置換」後に自動で進捗シートが閉じられた場合は検索パネルにフォーカスを戻すようにしました。

この変更は CotEditor 2.5.6 で反映される予定です。多分 WWDC 後に出します（WWDC に特に理由はないのですが、なんとなく）。
