### ISSUE TITLE
行番号が実際の行数とズレる / Wrong line number

### ISSUE THREAD

**Issue by kt81** [coteditor/CotEditor#524]
## 環境 

- CotEditor: 2.4.3 (108)
- システム: OS X バージョン 10.11.3（ビルド 15D21）
- 言語環境: 日本語

## 簡単な説明

左側に表示される行番号が、実際の行数とズレる
カーソル位置の行数として下部ステータスバーに出る行数は合っている
スクロールやカーソル移動で状況が変わり、
同じ行でもズレているときとズレていないときがある

![ss](https://cloud.githubusercontent.com/assets/1610650/13663870/7f12b850-e6e7-11e5-9b84-f986cff24d87.jpg)

※スクショからは内容を削除しています

## 不具合が発生したときに行っていた操作、または再現手順

Shift-JIS、CR/LFの、1行が結構長いCSVテキストを用いて作業中に発生
文字数ベースで1行が400字以上、全体で20000字程度

## 期待される挙動

カーソル位置の行数（実行数）と左の行番号が一致していること

**Comment by kt81** [comment]
念のため手元で再現するファイルを添付します
[行番号バグ発生テキスト.zip](https://github.com/coteditor/CotEditor/files/166803/default.zip)

**Comment by 1024jp** [comment]
ありがとうございます。
最近行カウントのチューンナップで式を差し替えたのでそこで計算を間違えている可能性が高いです。
もちろんバグなので次回までに修正します。
それまではご不便おかけします。

**Comment by 1024jp** [comment]
本件修正しました。次バージョンで反映されます。

再現ファイルありがとうございます。大変役に立ちました。

**Comment by kt81** [comment]
迅速なご対応ありがとうございます！
また、この場を借りていつも使わせていただいているお礼を申し上げます。ありがとうございます！

**Comment by 1024jp** [comment]
🍑
