### ISSUE TITLE
プリントプレビューで見切れる / print preview crops the bottom part

### ISSUE THREAD

**Issue by Gaddict** [coteditor/CotEditor#530]
## 環境 

- CotEditor: 2.4.4 (111)
- システム: OS X バージョン 10.11.4（ビルド 15E65）
- 言語環境: 日本語

## 簡単な説明

100行程度の文書を印刷しようとしたところ、
印刷プレビュー画面で50行目以降が見切れてしまい、印刷できません。

## 不具合が発生したときに行っていた操作、または再現手順

Toshiba e-STUDIO 4540CPEで常に発生。

## 期待される挙動

全文印刷可能

**Comment by 1024jp** [comment]
再現できません。以下のことを教えていただけると幸いです。

- どのファイルでも必ず発生しますか？ 
- 行は折り返し行ですか？それも改行コード毎で数えていますか？
- 必ず 50 行目なのでしょうか？ 50 行目くらいなのでしょうか？
    - 例えば、50行目以降が印刷できない文書でプリントフォントサイズをのみ変更した場合も、同じ箇所で見切れるのでしょうか？
- 他のプリンタ設定でも同様ですか？ それともプリンタ固有の症状ですか？

試しに以下のファイルを CotEditor で印刷し、結果の PDF をいただけると幸いです。

[100.txt](https://github.com/coteditor/CotEditor/files/185715/100.txt)

**Comment by Gaddict** [comment]
すみません。
状況が少し変わりました。

実際に印刷を行うと全行印刷できるようになりました。
しかし、プリントのプレビュー画面では依然見切れています。
<img width="598" alt="2016-03-23 18 01 30" src="https://cloud.githubusercontent.com/assets/5138563/14005687/05d90c2e-f1a9-11e5-9574-3298a927a6b2.png">

以下、回答です。

* どのファイルでも必ず発生します
* 行は改行コード毎です
* 行数依存ではありませんでした。
 * フォントサイズを大きくした場合には50行未満（２ページめの３分の１あたりの位置）できれました
* 他のプリンタ設定でも同様です。プリンタを切り替えてもプリントのプレビュー画面で見切れたままです。

[100.pdf](https://github.com/coteditor/CotEditor/files/187097/100.pdf)
[100_big.pdf](https://github.com/coteditor/CotEditor/files/187098/100_big.pdf)

印刷自体は可能になりましたので、
プレビュー表示へのissueとしていただきたいです。

**Comment by 1024jp** [comment]
リプライありがとうございます。
状況がわかってきました。ちょっとまだ手元で再現できないのでなんとも言えないのですが、修正すべき要件ですので検証します。

**Comment by 1024jp** [comment]
手を入れたのでおそらく本件は修正されたはずです。
この変更は CotEditor 2.5.0 で反映される予定です。

**Comment by Gaddict** [comment]
ご対応ありがとうございます。
リリースされましたら確認します。
