### ISSUE TITLE
行の重複を削除：取り消しメニューのローカライズ漏れ

### ISSUE THREAD

**Issue by tsawada2** [coteditor/CotEditor#531]
## 環境 

- CotEditor: 2.4.4 (111)
- システム: OS X バージョン 10.11.4（ビルド 15E65）
- 言語環境: 日本語

## 簡単な説明

「行の重複を削除」の取り消しメニューがローカライズされていない。

## 不具合が発生したときに行っていた操作、または再現手順

1. テキストを選択
2. 「テキスト」＞「行」＞「重複を削除」を実行
3. 取り消したいので「編集」メニューを開く
4. メニュー項目の表記が「取り消し - **Delete Duplicate Lines**」となっている

## 期待される挙動

「取り消し - **行の重複を削除**」などのように日本語で表記されること

**Comment by 1024jp** [comment]
おっと、ローカライズ元の文字列が間違ってました。
報告ありがとうございます🍅
