### ISSUE TITLE
「ソート・反転・重複を削除」機能は、テキスト未選択時は動作しないけれど… / Availability of text action menu items

### ISSUE THREAD

**Issue by tsawada2** [coteditor/CotEditor#533]
不具合報告というより要望に近いかもしれません：

## 環境 

- CotEditor: 2.4.4 (111)
- システム: OS X バージョン 10.11.4（ビルド 15E65）
- 言語環境: 日本語

## 簡単な説明

「テキスト」＞「行」サブメニューの中で
* ソート
* 反転
* 重複を削除

は、テキストが複数行にまたがって選択されているときに、その選択範囲内に対して適用されるコマンドだが、テキストが選択されていないときでもこれらのメニュー項目は活性状態になっている。
もちろん、このときこれらのメニュー項目を選択しても何も起きない。

## 期待される挙動

今回はたまたま、テキストファイルの行全体を対象にソートや重複行削除を行う作業をしていたので、
「テキストが選択されていない場合は、テキスト全体に対して適用」してくれることを期待しました。

しかしもちろん、「テキストが選択されていない場合は、メニュー項目を非活性にする」という対応も考えられると思います。

**Comment by 1024jp** [comment]
おぉ確かにそうですね、使えないなら使えないで非活性にすべきです。

> 今回はたまたま、テキストファイルの行全体を対象にソートや重複行削除を行う作業をしていたので、
「テキストが選択されていない場合は、テキスト全体に対して適用」してくれることを期待しました。
> 
> しかしもちろん、「テキストが選択されていない場合は、メニュー項目を非活性にする」という対応も考えられると思います。

これは私も以前「未選択の時はテキスト全体に適用してくれたらなぁ」と自分でも思ったくらいなのですが、選択範囲があるときとないときで振る舞いが変わるのは如何なものかと二の足を踏んでいます。それがほとんどのユーザにとって自明の振る舞いであればそうしたいところなのですが、いかんせん内容に手を入れるアクションだし。全体の時は実行後テキストを全選択にするとかにすればわかりやすいかなぁ。

いずれにしても今の態度は良くなさそうです。次までに何らかの手を加えます。

**Comment by tsawada2** [comment]
ありがとうございます。

確かに二の足を踏む気持ち、わかります。

他のコマンドとの挙動の一貫性なども考えると、ひとまずは非活性としておくのが良さそうでしょうか。

----

ちなみに、「テキスト」＞「インデント」＞「インデントを〜に変換」も、選択テキストがないと動作しないようですが、これは選択されていなくても、カーソル位置の行に対して実行できてもいいような気がしました。

**Comment by 1024jp** [comment]
調査してみたところソートがデフォルトで入っているテキストエディタのうち、

- Sublime Text
- Sumltron
- Textmate

は選択範囲のあるなしでソート範囲を自動的に切り替えていて

- Chocolat

は選択範囲がないときは無視

という挙動であった。

ということで、大丈夫そうなので、

> 「テキストが選択されていない場合は、テキスト全体に対して適用」

を採用しようと思う。ただしメニュー項目名は選択範囲のあるなしで適宜変更する。

**Comment by 1024jp** [comment]
メニュー項目名の動的変更に関してはちょっと保留にする。
