### ISSUE TITLE
Window open animation

### ISSUE THREAD

**Issue by eiros** [coteditor/CotEditor#534]
Please remove the animation of opening App window, it's very annoying!

**Comment by 1024jp** [comment]
Even it annoying (or not), it's the standard OS X behavior, and therefore I'll not remove it. Sorry.

**Comment by eiros** [comment]
Standard OS X behavior?? Example?

**Comment by eiros** [comment]
All Windows in OS X open without animation

**Comment by 1024jp** [comment]
See TextEdit.app or Pages.app. It's a standard behavior for document-based windows (not for other windows like ones in Finder or Safari). Some vendors may not respect to this UI manner.

**Comment by eiros** [comment]
Yes, indeed TextEdit opens with animation, sorry. But CotEditor.app not a standard application all the same. It would be great to be able to change this behavior in settings.

**Comment by 1024jp** [comment]
This animation is for document windows on the OS X world and the windows in CotEditor are document windows. A document window should behave like document window.

>  It would be great to be able to change this behavior in settings.

I don't like adding such a hacky setting against the Apple's UI policy. It's not CotEditor's thing.
