### ISSUE TITLE
プリント時の枚数がおかしい

### ISSUE THREAD

**Issue by 84ma** [coteditor/CotEditor#537]
## 環境 

- CotEditor: 2.4.4 (111)
- システム: OS X バージョン 10.10.5（ビルド 14F1713）
- 言語環境: 日本語

## 簡単な説明

プリント時の枚数がおかしい

## 不具合が発生したときに行っていた操作、または再現手順

必ず２ページ分になってしまう。
１枚で収まる場合には、２枚目が白紙
２枚以上になる場合には、２枚目の途中で切れる。

**Comment by 1024jp** [comment]
ご迷惑をおかけしています。
本件は #530 と同源の不具合であり、次回 2.5.0 で修正される予定です。
