### ISSUE TITLE
検索パネルの検索結果メッセージがローカライズされていない

### ISSUE THREAD

**Issue by tsawada2** [coteditor/CotEditor#538]
## 環境 

- CotEditor: 2.4.4 (111)
- システム: OS X バージョン 10.11.4（ビルド 15E65）
- 言語環境: 日本語

## 簡単な説明

「検索と置換」パネルの「Found n strings in "Filename".」がローカライズされていない。

## 期待される挙動

適切な日本語表現にローカライズされて表示されること。
![2016-04-09 23 32 16](https://cloud.githubusercontent.com/assets/9572430/14404364/b83e1a46-feae-11e5-83b0-c7215192be72.png)

**Comment by 1024jp** [comment]
ふおー、ローカライズ漏れ多いなぁ。助かります！
