### ISSUE TITLE
空のファイルを開こうとするとクラッシュする

### ISSUE THREAD

**Issue by speirs** [coteditor/CotEditor#543]
## 環境 

- CotEditor: 2.5.0 (117)
- システム: OS X バージョン 10.11.4（ビルド 15E65）
- 言語環境: 日本語

## 簡単な説明

空のファイルを開こうとするとクラッシュします。

## 不具合が発生したときに行っていた操作、または再現手順

再現手順

ターミナルで空のファイルを作成

    $ touch ~/Desktop/empty.txt

Finder で ~/Desktop/empty.txt をダブルクリックするとCotEditorはクラッシュします。

何か文字を入れてみると正常に起動します:

    $ echo "aaa" > ~/Desktop/empty.txt 

文字列 "aaa" を入れたファイルは Finder で empty.txt アイコンをダブルクリックして
正常にCotEditorが起動します。

## 期待される挙動

空のファイルを開こうとしたときにクラッシュせずにCotEditorが起動できる。

**Comment by 1024jp** [comment]
ありがとうございます。すぐに修正版を申請します。

**Comment by 1024jp** [comment]
修正版の CotEditor 2.5.1 が Mac App Store でリリースされました。non-AppStore 版もおってリリースされる予定です。

この度は簡潔で速やかなレポートありがとうございました。大変助かりました。

**Comment by speirs** [comment]
迅速な対応ありがとうございます。
期待通り起動するようになりました。
