### ISSUE TITLE
不可視文字の表示／非表示について

### ISSUE THREAD

**Issue by 84ma** [coteditor/CotEditor#545]
## 環境 

- CotEditor: 2.5.1 (120)
- システム: OS X バージョン 10.10.5（ビルド 14F1713）
- 言語環境: 日本語

## 簡単な説明

不可視文字の制御について
・環境設定：編集：不可視文字の設定を、【表示し無しない】に設定しても不可視文字が、表示されてる。
・環境設定：プリント：不可視文字の設定を、【プリントしない】設定しても可視文字が、プリントされる。

**Comment by 1024jp** [comment]
レポートありがとうございます。
次バージョンで修正します。

それまでは、もし必要でしたら迂回策として、環境設定の不可視文字の個別のチェックボックスを全てオフにすることで対応できます。
