### ISSUE TITLE
2.5.1 UTF-8 BOM付で保存したファイルがVC++2010でコンパイルエラー

### ISSUE THREAD

**Issue by nktshm** [coteditor/CotEditor#546]

**Comment by nktshm** [comment]
表題の件、2.4では問題ありませんでした。
これまで、Mac Xcode4.6.3で作成したC++ファイルをBOM付で保存してVC++2010へ持っていっています。
2.5.1にしてからは、全てのファイルではありませんが、構文によってはエラーになります。
よろしくお願いいたします。

**Comment by 1024jp** [comment]
C++ のプログラムを Xcode で書き UTF-8 で保存したものを、CotEditor で開き UTF-8 BOM 付きに変換している（CotEditor 上では一切編集してない）、という理解であっていますか？

CotEditor は 2.5.0 から UTF-8 の BOM に対する扱いが変更されました。
以前は、環境設定で「UTF-8 のとき BOM も保存」にチェックが入っていた時は、UTF-8 のファイルを CotEditor 上で開き上書きした場合は自動で BOM が追加されていたのですが、2.5.0 からはエンコーディングのメニューに「Unicode (UTF-8) BOM 付き」という項目が別途追加され、BOM のない UTF-8 ファイルに BOM をつけたい場合は、明示的ににれに変更する必要があります。

![screen shot 2016-05-02 at 15 37 24](https://cloud.githubusercontent.com/assets/1165044/14948496/cee3b06a-107b-11e6-97b3-21e8d36f42e8.png)



その上で、なおエラーが出ているという場合には、以下を教えてください：

1. 具体的なコンパイルエラーのエラーメッセージ
2. CotEditor 上で行っている、 「BOM付きで保存する」の具体的な操作手順
3. （もしわかれば）CotEditor の上記の操作で実際に BOM が追加されたか

**Comment by nktshm** [comment]
環境設定だけではなく、エディタウィンドウのポップアップで「Unicode (UTF-8) BOM 付き」を明示的に指定しなくてはならなくなったのですね。問題解決しました。
わかれば2.5仕様の方が好ましいです。
速やかなご回答ありがとうございます。

**Comment by 1024jp** [comment]
いえいえ、解決して安心しました。
