### ISSUE TITLE
ウィンドウ幅をウィンドウから取得するときにクラッシュする

### ISSUE THREAD

**Issue by hirohitokato** [coteditor/CotEditor#547]
## Overview
環境設定の「ウィンドウ幅」→「ウィンドウから取得…」で、テキストフィールドでリターンキーを入力した後に「デフォルトに設定」ボタンをクリックすると、CotEditorがクラッシュする

## How to reproduce
1. CotEditorを起動
2. メニューバーから「CotEditor」→「環境設定…」→「ウィンドウ」を選択
3. 「ウィンドウ幅」欄の「ウィンドウから取得…」ボタンをクリック
4. 「幅」または「高さ」のテキストフィールドにフォーカスを合わせ、リターンキーを押下
5. 残っているウィンドウで「デフォルトに設定」ボタンをクリック

## Expected results
- 手順4のリターンキー押下時点でウィンドウが閉じること(?)
- 手順5のボタンクリック時にアプリが落ちず、幅設定が完了すること

## Actual results
- 5のボタンクリック時にアプリが落ちる

## Reproducibility
100%

## Environment
- Mac ： MacBook Pro (Retina, 13-inch, Early 2015)
- OS X ： El Capitan 10.11.4（15E65）
- CotEditor：バージョン 2.5.1 (120) （Mac App Store版）

**Comment by 1024jp** [comment]
ありがとうございます。こちらでも再現しました。
修正します。

**Comment by hirohitokato** [comment]
ありがとうございます！
