### ISSUE TITLE
cotコマンドのヘルプ文にTYPOがある

### ISSUE THREAD

**Issue by hirohitokato** [coteditor/CotEditor#548]
## Overview
cotコマンドのヘルプ文（日本語）にTYPOがある

## Location
「CotEditorヘルプ」→「cotコマンド 」→「インストール」内の第2段落

## Expected result
> Terminal からシンボリックリンクを作成して、任意の場所にインストール**することが**できます

## Actual result
> Terminal からシンボリックリンクを作成して、任意の場所にインストール**するが**できます

## Environment
- Mac ： MacBook Pro (Retina, 13-inch, Early 2015)
- OS X ： El Capitan 10.11.4（15E65）
- CotEditor：バージョン 2.5.1 (120) （Mac App Store版）

**Comment by 1024jp** [comment]
typo の指摘助かります！
