### ISSUE TITLE
Bug in CotEditor 2.5.2: Wordwrap breaks mid-word when you indent a line

### ISSUE THREAD

**Issue by handcoding** [coteditor/CotEditor#551]
Hi there,

As of CotEditor 2.5.2, it would seem that wordwrap breaks mid-word when you indent a line.

Here’re some steps to reproduce:

1. Under CotEditor → Preferences → Window, make sure that window width is set to 600 × 620.
2. Under CotEditor → Preferences → Edit
    * Check “Auto indent” 
    * Set “Indent width” to 4 spaces
    * Check “Soft wrap”
    * Check “Indent wrapped lines by” and set it to [ 0 ] spaces
2. Open a new CotEditor window and paste in this text:<br>
    `Prebuilt fractions in ninths, eighths, sevenths, sixths, fifths, quarters thirds, and half.`
3. Go the beginning of that line and press Tab.

* Expected result: The text wraps at word breaks.
* Current result: The text wraps in the middle of words, such as:

![coteditor 252 - wordwrap breaking in the middle of words](https://cloud.githubusercontent.com/assets/118319/15020753/100c5aec-11e9-11e6-97db-cb867efa613f.png)

P.S. If by chance you can’t reproduce this using CotEditor’s default font, you can replicate the fonts I’m using by downloading [Droid Sans Mono](https://www.google.com/fonts/specimen/Droid+Sans+Mono) and then setting CotEditor’s font to Droid Sans Mono 12:

![coteditor - ashleys font settings](https://cloud.githubusercontent.com/assets/118319/15020852/80cc9c24-11e9-11e6-9833-34175cddb0d9.png)

**Comment by 1024jp** [comment]
Oh, you are right. I was so stupid. I'll fix it in the next version.
Thanks!
