### ISSUE TITLE
多すぎるバンドルシンタックススタイルを削減したい

### ISSUE THREAD

**Issue by knoajp** [coteditor/CotEditor#553]
現状ではバンドルされたシンタックススタイルは削除できない仕様ですが、新規ファイルを作成してコードを書き始めるときに、40もある中から目的のスタイルを選ぶのはわずらわしく感じます。
素人目には削除できるようにすることは簡単なように思えるのですが、何かのポリシーに従ってこの仕様になっているのでしょうか。
うっかり削除してしまう危険に備えるだけなら、どれでも削除できるようにした上で、バンドルされたシンタックススタイルもオープンに配布したらいいんじゃないかと思うのですが。

**Comment by 1024jp** [comment]
CotEditor の（OS X のアプリケーションの）構造上、ユーザがバンドルされたデータを誤って削除する可能性はゼロに近いです。

> 素人目には削除できるようにすることは簡単なように思えるのですが

面倒なのでやりたくないです。綺麗に実装されたプルリクエストがいただけるなら検討します。

いちいちプルダウンから目的のスタイルを探すのが煩わしい時は、先にファイルを保存してしまうと保存した時の拡張子に合わせて自動でシンタックスが指定されるのでオススメです。

**Comment by knoajp** [comment]
ご回答ありがとうございます。
何かのポリシーで敢えて削除できなくしているのではないということがわかっただけで十分です。
ファイルを保存すればというのはごもっともなのですが、よそからコピペで貼り付けてきたコードを少しいじって戻すだけ、みたいな機会がたまたま続いたものですから、要望してみた次第です。

最初の文は少し違和感があったのですが、「〜ゼロに近いです。なので、削除できるようにしても問題は起きないとは思います。しかし、面倒なので〜」という意味でしょうか。であればよくわかりました。

ありがとうございました！

**Comment by knoajp** [comment]
コロンブスの卵的な話ですが、単純に、バンドルするシンタックスを減らした上で、下記のような公開シンタックスを充実させれば、事態はスマートに解決するのでは、と思いました。
https://github.com/coteditor/CotEditor/wiki/Additional-Syntax-Styles

バンドルシンタックスと公開シンタックスの記述形式が異なっていて、既存のバンドルシンタックスをyamlに変換して公開するのが難しいのかな、と思ったりもしつつ。

**Comment by 1024jp** [comment]
> 最初の文は少し違和感があったのですが、

おそらく最初の投稿の

> うっかり削除してしまう危険に備えるだけなら、

を私が誤読し回答しました。

> コロンブスの卵的な話ですが、単純に、バンドルするシンタックスを減らした上で、下記のような公開シンタックスを充実させれば、事態はスマートに解決するのでは、と思いました。

そう簡単ではありません。基本的にユーザは一つのアプリケーションにそれほど労力はかけないので、このように設定ファイルを外部に追い出すと、ほとんどのユーザはそもそもインストールできる外部シンタックスがあることに気づかずにおわります。さらに、新たな未対応のファイル形式を開こうとするたびにシンタックスが提供されているかを確認しに行くことは利便性が高いと思いません。CotEditor は「吊るしの状態で使える」ことを志向しています。ユーザが手をかけてカスタマイズをしなければいけないシステムは目指すところではありません。

また、CotEditor はユーザのカスタムシンタックスを自動的にアップデートしたり差分をチェックしたりする機能がありません。仮に多くのシンタックス定義を外部に追い出すと、それらの追加シンタックスを最新の状態に保つのは困難になります。

もしかしたらプラグイン形式をとる多くのコーディングテキストエディタを既にご存知かもしれません。それらのエディタは既にモダンなプラグインシステム・アップデートトラッキング機能・または多くのコントリビュータによる活発なエコシステムを既に持っているでしょう。
CotEditor は1人の人間が余暇時間に開発をしているアプリケーションです。開発リソースは限られています。

よってこの現在の数のシンタックス定義をバンドルする形式を維持します。

これらを踏まえた上で折衷案として考えらるのは、「よく使うシンタックス」というのを自動・または手動で管理するようにし、それらをリストの上方なんかにまとめて表示する、くらいならば現実的な解で且つ有用そうです。

**Comment by knoajp** [comment]
一笑・一蹴されても仕方ない提案に、たいへん丁寧なご回答をいただき恐縮です。

吊しで使える志向はわたしもモノによって気にかける考え方なので、よく納得できました。
アップデートの問題はなるほど、わたしの考えが至っておりませんでした。
「よく使うシンタックス」を指定してリストの上方に表示させられるなら、逆転して「使わないシンタックス」を指定してリストから非表示にすることと大差ないように…素人目には…思えてしまいましたが、いかがでしょうか。

**Comment by 1024jp** [comment]
> 「よく使うシンタックス」を指定してリストの上方に表示させられるなら、逆転して「使わないシンタックス」を指定してリストから非表示にすることと大差ないように…素人目には…思えてしまいましたが、いかがでしょうか。

人間、目に見えないものは忘れてしまうものです。また、コンピュータの世界ではその時は使用しなくても、のちに使用する羽目に陥る形式や言語があります。その時にすぐに選べるようにしておくことは大切です。

ただし、モノによります。シンタックス定義と同様に、ファイルエンコーディングも CotEdtior は長々としたリストを持っていますが、これについてはそのうち任意でいらないものは隠せるようにしたいと考えています。

「よく使うシンタックス」については、どちらかというと自動で選別するイメージでした。手動だとすると、確かに使わないものを指定することとあまり大差はないのかもしれません。

**Comment by 1024jp** [comment]
直近で使った6件（6件に確定するかは後日検討）をプルダウンリストの上方にまとめるようにしました。
この変更は次のバグフィックス版である CotEditor 2.5.6 ではなくマイナーアップデートである 2.x 系の変更の際に適用されます。

![screen shot 2016-06-10 at 19 29 49](https://cloud.githubusercontent.com/assets/1165044/15961794/c22e64c0-2f41-11e6-912e-5c0ca433cd5f.png)

**Comment by knoajp** [comment]
ありがとうございます！
