### ISSUE TITLE
起動直後のフォーカス

### ISSUE THREAD

**Issue by magifd2** [coteditor/CotEditor#562]
MacAppStoreでリリースされている ver.2.5.4を利用しております。

いつのバージョンから現象が出ているのか記憶が定かでは無いのですが、上記のバージョンにおいて、Coteditorを起動直後、ウィンドウ内のフォーカスが編集エリアではなくウィンドウの右上の方のエリア（ウィンドウを分割するボタンのすぐ左隣）にフォーカスがあたっているようで、一度編集エリアを選択するか、タブキーを一回押してフォーカスを変更しないと、入力が出来ないという症状が発生しております。

起動後、若干ですが入力開始までに手間がかかるので、お手すきの際にでも現象確認頂けたら幸いです。

**Comment by 1024jp** [comment]
本件については #557 ですでに報告を頂いており、次の CotEditor 2.5.5 で修正される予定です。
それまでお手数おかけしますがご辛抱ください。2.5.5 は 6 月初め頃リリースします。

**Comment by magifd2** [comment]
ご回答ありがとう御座います。
重複無いか検索していたのですが、見つけきれず余分にIssueを発行してしまい申し訳御座いません。
