### ISSUE TITLE
選択文字列のドラッグ移動機能

### ISSUE THREAD

**Issue by stein2nd** [coteditor/CotEditor#565]
ハイライト選択された文字列を、任意の場所にドロップ移動できるようになれば、物凄く便利だと思います。

参考：サクラエディター「ドラッグ＆ドロップ編集」
http://sakura-editor.sourceforge.net/htmlhelp/HLP000135.html

追記：以前に使用した際には、ドロップ移動が効かなかったのですが、今使った時にはドロップ移動が効いてました。

**Comment by 1024jp** [comment]
すでにできるはずですが、今の実装とはイメージでしょうか？
（ドラッグを開始するまでに気持ち長押しする必要があります）

![drag_drop](https://cloud.githubusercontent.com/assets/1165044/15639139/42b346f2-2663-11e6-99bd-ca5b85f1c22c.gif)

**Comment by 1024jp** [comment]
特に返信がないのでクローズします。
