### ISSUE TITLE
マウスホイールでのスクロール不具合 / scroll is sluggish with wheel mouse

### ISSUE THREAD

**Issue by cy-sachie-kamba** [coteditor/CotEditor#567]
## 環境
- CotEditor: 2.5.5 (130)
- システム: OS X バージョン 10.10.5（ビルド 14F1808）
- 言語環境: 日本語
## 簡単な説明

マウスホイールでのスクロールがかくつく
## 不具合が発生したときに行っていた操作、または再現手順

マウス接続中はタッチパッドが無効になるように設定
端末を再起動
CotEditorを起動
14kb程度のファイルでもスクロールがかくつきます。

マウスを外し、タッチパッドを有効にしすると、スクロールはなめらかになります。
その後、マウスを再接続すると、ホイールでもなめらかにスクロールするようになります。

しかし、以下のようなファイルでは「ホイールでのみ」かくつきます。
・ある程度サイズが大きなファイル(100kb/1600行超)で、改行がない、長い（日本語の？）文章があるファイル
## 期待される挙動

タッチパッドの有効状態にかかわらず、ホイールでもなめらかにスクロールするようにしていただけたら幸いです。

**Comment by 1024jp** [comment]
本件に関して1つ伺いたいのですが、行番号ビューの有無で症状は変化しますか？

**Comment by 1024jp** [comment]
cf. 
- [Smooth scrolling (#3209) · Issues · George Nachman / iterm2 · GitLab](https://gitlab.com/gnachman/iterm2/issues/3209)
- [NSScrollView not scrolling nicely with mouse scrollwheel - Xamarin Forums ](https://forums.xamarin.com/discussion/31312/nsscrollview-not-scrolling-nicely-with-mouse-scrollwheel)

**Comment by 1024jp** [comment]
なかなか手強そうなので 2.5.6 での対応は保留にさせてください。

**Comment by cy-sachie-kamba** [comment]
＞本件に関して1つ伺いたいのですが、行番号ビューの有無で症状は変化しますか？

いえ、変わらないです。

**Comment by 1024jp** [comment]
>> 本件に関して1つ伺いたいのですが、行番号ビューの有無で症状は変化しますか？
>
> いえ、変わらないです。

ありがとうございます。

**Comment by 1024jp** [comment]
まだ継続して CotEditor と該当のマウスを使用していたら伺いたいのですが、
本件最新の CotEditor 3.2.3（と macOS?）でもまだ起こりますでしょうか？

**Comment by cy-sachie-kamba** [comment]
3.2.3では、発生しておりません。
ご対応ありがとうございます！

**Comment by 1024jp** [comment]
経過報告ありがとうございます。安心いたしました。
ではこのイシューはクローズします。
