### ISSUE TITLE
Feature request: Vim mode

### ISSUE THREAD

**Issue by peinan** [coteditor/CotEditor#574]
Hope I can choose to use vim mode in CotEditor.
Vimモードを使える（有効にできる）ようにしてもらえると嬉しいです。

**Comment by 1024jp** [comment]
You mean Vim-like keybindings? Currently, I don't have any plan for that. And sorry, the priority is low for me since it may take time to implement.

Vim っぽいキーバインディングとかカーソル移動ということですよね？現時点では予定がありません。また、実装するのに結構手間がかかりそうなので優先度は低いです。申し訳ない。

**Comment by bobrocke** [comment]
I agree. Although Vim is deeply seated in some folk's muscle memory, it should be a low priority for a new text editor.

**Comment by 1024jp** [comment]
I close this issue as I don't have any plan to implement this feature.

**Comment by livrth** [comment]
Found this issue four years later. Frankly, this is the best editor for macOS right now, but it would be a godsend if it support vim keybindings.
