### ISSUE TITLE
Exclude extension from selection in save panel / 保存時のファイル名入力「名称未設定.txt」の選択状態について

### ISSUE THREAD

**Issue by blue-ocean777** [coteditor/CotEditor#585]
## 環境 

- CotEditor: 2.5.6 (135)
- システム: OS X バージョン 10.11.6（ビルド 15G31）
- 言語環境: 日本語

## 簡単な説明

ファイル保存時にファイル名を入力しますが、「名称未設定.txt」があらかじめ入力されており、またその全部が選択済みの状態になっています。このため、拡張子「.txt」を残したままで希望のファイル名を入力するためには、あらかじめ選択済み状態を解除し、「名称未決定」部分のみを間違いなく削除した後でようやく希望のファイル名を入力できる状態になります。

## 不具合が発生したときに行っていた操作、または再現手順

ファイル＞保存
もしくは
Command＋S

## 期待される挙動

「名称未決定」のみが選択されている状態で、「.txt」は選択から外れている状態から始まり、この状態からファイル名入力を行いたいです。

**Comment by 1024jp** [comment]
duplicated #464

**Comment by 1024jp** [comment]
Sorry but this is technically impossible because of the Sandbox specifications.

**Comment by blue-ocean777** [comment]
直すことが不可能というのを聞き、とても残念に思います。

**Comment by 1024jp** [comment]
CotEditor 3.0.0 で実現できそうです。

**Comment by blue-ocean777** [comment]
ご苦労されたようで、失礼しました。
例えばExcel for Mac2011などを見ますと、保存時には拡張子を除いたファイル名のみが入力できる状態であり、別途フォーマットを選択することで自動的に拡張子が付与されます。拡張子はあくまで自動で別途付与された方がいいと思っていたので、この方式だと間違いがないですし、便利だと思っていました。
素人考えで、簡単に実現できるものと考えており、お手数をおかけしました。

**Comment by 1024jp** [comment]
いえいえ、私自身「イマイチだなぁ」と思っていた箇所だったので修正できて良かったです。

CotEditor は「すべての拡張子を付与できる」という特殊な仕様が話がややこしかった部分なのです。
Apple は紐付けした特定の拡張子しか使えないようにデザインしているので他の一般的なアプリケーションのように .xlsx, .csv などの有限個数の拡張子を扱っている場合は自動的にこの辺をやってくるれるのです。

**Comment by blue-ocean777** [comment]
なるほど、私はこのアプリの仕様を存じなかったのですが、そのような要求仕様があったのですね。

特殊な要求があると大変そうですね。
ご苦労さまです。m(_ _)m
