### ISSUE TITLE
検索と置換の機能の使用変更について

### ISSUE THREAD

**Issue by 84ma** [coteditor/CotEditor#592]
## 環境 

- CotEditor: 3.0.0-beta (142)
- システム: macOS バージョン 10.10.5（ビルド 14F1912）
- 言語環境: 日本語

## 簡単な説明

検索と置換の機能
正規表現のチェックをONにして置き換え文字に正規表現が使用出来なくなってしまった。\n \t など
CotEditor2.5.7と同様に置換側でも正規表現を使用したい。

**Comment by 1024jp** [comment]
あぁ、確かに、そうですよね。ご指摘ありがとうございます。
ちょっとなんとかならないか調べてみます。

**Comment by 1024jp** [comment]
検索パネルの正規表現検索に「置換文字列のエスケープ文字を解釈」というオプションを追加しました。
デフォルトでオンにしてあります。
