### ISSUE TITLE
検索と置換の【すべて検索】ボタンの挙動について

### ISSUE THREAD

**Issue by 84ma** [coteditor/CotEditor#593]
## 環境 

- CotEditor: 3.0.0-beta (142)
- システム: macOS バージョン 10.10.5（ビルド 14F1912）
- 言語環境: 日本語

## 簡単な説明

検索と置換のすべて検索の挙動変更について
検索と置換で[すべて検索]ボタンを使用すると検索と置換の部分が広がり、結果の部分が広がらないため大変使いづらいです。

## 期待される挙動

CotEditor257と同じように結果の部分のみが広がってほしい

**Comment by 1024jp** [comment]
確認しました。 Yosemite でのみ起こっている不具合であると思われます。
好ましくない振る舞いであるので修正します。

NSSplitViewItem の `holdingPriority` が Yosemite で効いてないようにみえる。
