### ISSUE TITLE
現在行のハイライトが行高より広い場合がある

### ISSUE THREAD

**Issue by usami-k** [coteditor/CotEditor#594]
## 環境 

- CotEditor: 3.0.0-beta (142)
- システム: macOS バージョン 10.11.6（ビルド 15G1004）
- 言語環境: 日本語

## 簡単な説明

現在行のハイライトが行高より広くなっています。

<img width="696" alt="2016-09-16 18 22 32" src="https://cloud.githubusercontent.com/assets/536781/18581446/a13689b8-7c3b-11e6-9b46-3fa41d3e52ef.png">

## 不具合が発生したときに行っていた操作、または再現手順

設定で「現在の行の背景カラーを変更」にしている場合、ハイライトが実際の行の高さよりも広がっているようです。
空行では行の高さどおりですが、テキストがある行では上記のスクリーンショットのようになります。

はっきりは分かりませんが、フォントや行の高さの指定に依存しているように思えるので、設定画面のスクリーンショットも貼ります。

<img width="662" alt="2016-09-16 18 22 53" src="https://cloud.githubusercontent.com/assets/536781/18581460/ab4edf86-7c3b-11e6-98d8-1a5fcb4cb699.png">

## 期待される挙動

ハイライトが行の高さどおりであること。
CotEditor 2.5.7 では期待どおりのようです。

**Comment by 1024jp** [comment]
macOS Sierra GM で再現できず。あとで El Capitan でも試します。
ちなみにフォントのバージョンを教えていただけると幸いです。

![screen shot 2016-09-16 at 19 27 14](https://cloud.githubusercontent.com/assets/1165044/18583133/a35460be-7c43-11e6-8f60-e48a0f0f1fed.png)

![screen shot 2016-09-16 at 19 28 39](https://cloud.githubusercontent.com/assets/1165044/18583158/ce462d8e-7c43-11e6-8e49-1faf153a879b.png)

**Comment by usami-k** [comment]
フォントバージョンは 2.000 です。
いま気づきましたが、行の高さが 1.2 倍だと問題なく、1.0 倍だと問題が起こるようです。

**Comment by 1024jp** [comment]
> いま気づきましたが、行の高さが 1.2 倍だと問題なく、1.0 倍だと問題が起こるようです。

おぉ本当だ。行高のこと忘れてました。助かります。

**Comment by 1024jp** [comment]
割とわけのわからない原因で 1.0 が微妙に 1.0 じゃないらしく 1.0 として扱われていませんでした（自分で書いててもよくわかりません）。
たぶん Swift （か AppKit）のバグの類だと思うのですが、迂回策を突っ込んでおきました。
