### ISSUE TITLE
「文字を Unicode 16 進数で入力」の機能で文字が入力できない

### ISSUE THREAD

**Issue by usami-k** [coteditor/CotEditor#595]
## 環境 

- CotEditor: 3.0.0-beta (142)
- システム: macOS バージョン 10.11.6（ビルド 15G1004）
- 言語環境: 日本語

## 簡単な説明

「文字を Unicode 16 進数で入力」の機能で、文字が入力できません。

## 不具合が発生したときに行っていた操作、または再現手順

メニューから「編集 > 文字を Unicode 16 進数で入力」を選択して、適当な 16 進数を入れて入力ボタンを押す。
このとき、開いているウィンドウにテキストが入力されません。

<img width="274" alt="2016-09-16 18 35 47" src="https://cloud.githubusercontent.com/assets/536781/18581751/e265fd0a-7c3c-11e6-85c3-56ed8f8efb2d.png">

## 期待される挙動

上記の操作でテキストが入力されること。
CotEditor 2.5.7 では期待どおりのようです。

**Comment by 1024jp** [comment]
fixed on 259f4de230205bb45c4ba6bb016407dd9d31e1b1

これは間が抜けてました。ガード節の boolean を逆にしてました。
指摘ありがとうございます。
