### ISSUE TITLE
「--」や「...」を入力すると、入力文字が勝手に置換されてしまう

### ISSUE THREAD

**Issue by usami-k** [coteditor/CotEditor#602]
## 環境 

- CotEditor: 3.0.0-beta.3 (146)
- システム: macOS バージョン10.12（ビルド16A323）
- 言語環境: 日本語

## 簡単な説明

「--」や「...」を入力すると、「—」や「…」になってしまいます。

## 不具合が発生したときに行っていた操作、または再現手順

新規テキストを作成して、上記のテキストを入力すると発生します。

CotEditor の「環境設定 > 編集」の自動置換の各種設定はオフです。

<img width="362" alt="2016-09-26 12 45 28" src="https://cloud.githubusercontent.com/assets/536781/18822100/6527a962-83e7-11e6-8d93-e36a0ea756a5.png">

「システム環境設定 > キーボード > ユーザ辞書」の各種設定はオフです。

<img width="274" alt="2016-09-26 12 40 12" src="https://cloud.githubusercontent.com/assets/536781/18822118/8827e184-83e7-11e6-9172-c3d7ffd204d6.png">

CotEditor 2.5.7 では発生しません。

## 期待される挙動

「--」や「...」がそのまま入力できること。
または、有効無効の設定を切り替えられること。

**Comment by 1024jp** [comment]
うーん、同条件でこちらで再現しません。CotEditor 再起動しても毎回起きますか？

**Comment by usami-k** [comment]
こちらの手元では CotEditor 再起動しても発生します。
そちらで再現しないとなると、他に条件があるのかもしれません。何か分かればコメントします。

**Comment by 1024jp** [comment]
悩ましい。何かわかったら教えてください。

念のために伺いますが、

- IM はシステム標準のものですよね？ 入力ソースは「 ABC」？
- 「スマート [ ] 引用符 [ ] ダッシュ」のチェックボックスを一旦切ってから入れ直しても変化はないですか？

**Comment by usami-k** [comment]
IM はシステム標準の日本語入力です。念のため、設定のスクリーンショット。

<img width="780" alt="2016-09-26 19 00 01" src="https://cloud.githubusercontent.com/assets/536781/18830496/e60e4e26-841b-11e6-8057-9f5bb5897787.png">

**Comment by usami-k** [comment]
> 「スマート [ ] 引用符 [ ] ダッシュ」のチェックボックスを一旦切ってから入れ直しても変化はないですか？

これを試したところ、変化がありました。いったんチェックを入れてから外すと、自動置換されなくなります。

その後、CotEditor を再起動すると再発します。さらに再度、上記チェックボックスを入れてから外すと、自動置換されなくなります。

**Comment by 1024jp** [comment]
なるほどー。UserDefaults の読み書きがうまくいってないっぽいですね。Disk Utility.app の First Aid で直ったり...しないですよね。

**Comment by usami-k** [comment]
スマートダッシュのデフォルト値に違う設定の値が入っていましたので、修正して Pull Request を送りました。
