### ISSUE TITLE
テキストを開いて閉じたあとで CotEditor がクラッシュする

### ISSUE THREAD

**Issue by usami-k** [coteditor/CotEditor#605]
## 環境 

- CotEditor: 3.0.0-beta.3+6081e15 (147)
- システム: macOS バージョン 10.11.6（ビルド 15G1004）
- 言語環境: 日本語

（ 6081e15ac3da1068959d59a9f96addb5e145c6a8 をビルド＆アーカイブして使用）

## 簡単な説明

テキストを開いて閉じたあとで CotEditor がクラッシュする。

## 不具合が発生したときに行っていた操作、または再現手順

CotEditor で何らかのテキストファイルを開いたあと、ウィンドウを閉じ、CotEditor 自体は起動したままで放置する。
しばらくすると、CotEditor がクラッシュしてクラッシュログが表示される。

クラッシュログを添付します。
[CrashLog.txt](https://github.com/coteditor/CotEditor/files/494378/CrashLog.txt)

## 期待される挙動

クラッシュしないこと

**Comment by usami-k** [comment]
#603 の確認中に発生。現象や原因が同じかどうかはわかりません・・・。

**Comment by 1024jp** [comment]
あらーありがとうございます。
Document インスタンスがウインドウクローズ時にリリースされてないっぽいですね。
前にこの手のは潰したはずなのだが、またどっかで捕まえてしまってるんだと思います...。

昨日のはあれはあれで必要な対策だったのですが、これはまた別の要因なのかなぁ。
いずれにせよ後ほど調べてみます。

**Comment by 1024jp** [comment]
修正しました。
