### ISSUE TITLE
finder上で、ファイルをコピーしてCotEditorにペーストしたときの挙動の違い

### ISSUE THREAD

**Issue by 84ma** [coteditor/CotEditor#606]
## 環境 

- CotEditor: 3.0.0-beta.3 (146)
- システム: macOS バージョン 10.10.5（ビルド 14F1912）
- 言語環境: 日本語

## 簡単な説明

finder上で、ファイルをコピーしてCotEditorにペーストしたときの挙動の違い
CotEditor: 3.0.0-beta.3 (146)：【フルパスとなる】：/Users/【username】/Desktop/○○○○○.txt
CotEditor: 2.5.7 (138)：【ファイル名のみ】：○○○○○.txt

仕様変更でしょうか？

**Comment by 1024jp** [comment]
挙動確認しました。この変更は意図しないものなので戻します。指摘ありがとうございます。
