### ISSUE TITLE
crash CotEditor 3.0.0b3 on macOS Sierra.1pb1

### ISSUE THREAD

**Issue by Chamiu** [coteditor/CotEditor#607]
- default open set .md as CotEditor 3.0.0b3.
- my mac on CotEditor only 3.0.0b3.
1. double click .md file from recent Document.
2. CotEditor crash and open crash reporter.

But this issue is one time only.
crash log attached.
[CotEditor_2016-09-27-150513_MacBook-Pro.crash.zip](https://github.com/coteditor/CotEditor/files/495111/CotEditor_2016-09-27-150513_MacBook-Pro.crash.zip)

**Comment by 1024jp** [comment]
Thanks. I'll look into this later.

**Comment by 1024jp** [comment]
I addressed your issue a bit on the final 3.0.0.
Tell me if it still happens on that version. Otherwise, I'll close this issue.

**Comment by 1024jp** [comment]
I close this issue.
Create a new one if your app crashes again.
