### ISSUE TITLE
タブ機能は、macOS sierra以降から対応ですか？

### ISSUE THREAD

**Issue by dencosa** [coteditor/CotEditor#613]
El Capitanを使用していますが、
「coteditor 3.0」で
タブ機能がみつかりませんでした。
macOSのバージョンによって制限される機能があるのでしょうか？

**Comment by 1024jp** [comment]
Sierra 以降のみです。リリースノートにも記載があります。

**Comment by dencosa** [comment]
すみません。よく読んでいませんでした。ちょっと残念ですが、そのうちmacOSをアップデートして快適な「coteditor」ライフをおくります。
