### ISSUE TITLE
Use of tab and back-tab

### ISSUE THREAD

**Issue by mrodenkirch** [coteditor/CotEditor#620]
One of the features I frequently use with NotePad++ is having the ability to select multiple rows then using the tab button to indent all of the them together.  I also use backtab (shift+tab).

**Comment by 1024jp** [comment]
On macOS, `⌘[` is used to increase indent level (or `⌘]` to decrease.)

The action is called "Shift Right" (in Text > Indentation menu) and the shortcut for the action on CotEditor is customizable.
However (unfortunately), CotEditor doesn't accept a shortcut excluding ⌘ key. Therefore you currently can not use tab key for indent. So regarding CotEditor, you need to get used to `⌘[` kind shortcut.

**Comment by 1024jp** [comment]
Sorry, I mistakenly closed.
