### ISSUE TITLE
Indentation Shift Deselects Block in Newest Version

### ISSUE THREAD

**Issue by jeffmikels** [coteditor/CotEditor#623]
To reproduce:

- Download the latest version from the Mac App Store.
- Select a block of text.
- Choose Indentation>shift right from the menu or use the keystroke

The block of text will now be deselected preventing multiple shift indentations.

The previous version (2.5) did not have this behavior.

**Comment by 1024jp** [comment]
Sorry, it is a bug on CotEditor 3.0.2 and already fixed in the next CotEditor 3.0.3 that will be released in the next week.

Thanks for your report.
