### ISSUE TITLE
MarsEditの外部エディターとして使ったときに、保存が反映されない。

### ISSUE THREAD

**Issue by yuzuk2** [coteditor/CotEditor#625]
## Environment (環境)

- CotEditor: 3.0.2 (163)
- System: macOS バージョン10.12.1（ビルド16B2555）
- Language: Japanese
- MarsEdit Version 3.7.8 (7375)

## Steps to Reproduce the Issue (不具合が発生したときに行っていた操作、または再現手順)

■再現手順
 1. MarsEditの
　　[Preferences]->[Editor]->"Edit With" editor
　　に、CotEditorを設定する。
　
 2. MarsEditで任意のPostを選択し、
　　[File]->[Edit With CotEditor]
　　を実行する。
　
 3. 適当に編集して保存後、ウインドウを閉じる。

 4. MarsEditのPost上に、保存内容が反映されていない。 (不具合)

■備考
・同様の操作を、TextWranglerというエディターを対象にして行った場合、
　保存->ウインドウを閉じた際にMarsEditのPostにもすぐに反映されます。
　

## Expected Result (期待される挙動)

MarsEditの外部エディターとして使ったときに、
保存が反映されること。

**Comment by 1024jp** [comment]
Sandbox の影響でした。
対応しましたので、次の CotEditor 3.1.0 で反映される予定です。
