### ISSUE TITLE
Somewhat inconsistent menu ordering of NFD/NFC

### ISSUE THREAD

**Issue by rinopo** [coteditor/CotEditor#630]
![161101](https://cloud.githubusercontent.com/assets/45791/19878905/16c8b1ec-a031-11e6-8696-4d1f827d1fec.png)

Version 3.0.4 (167)

上図のように、「テキスト ＞ Unicode 正規化」メニューの並び順が揃っていないのがなんとなく気になりました。
細かいことで恐縮です。

**Comment by 1024jp** [comment]
確かに...。
こういった細かい指摘は歓迎します。
3.1.0 で変更します。

**Comment by 1024jp** [comment]
Fixed in dc7fcf143ee9a707dd241c5aa0cad77ade2a62af.
