### ISSUE TITLE
CotEditorの編集結果が、MarsEditに反映されない。 (3.0.4)

### ISSUE THREAD

**Issue by yuzuk2** [coteditor/CotEditor#631]
## Steps to Reproduce the Issue (不具合が発生したときに行っていた操作、または再現手順)

■再現手順
 1. MarsEditの
　　[Preferences]->[Editor]->"Edit With" editor
　　に、CotEditorを設定する。
　
 2. MarsEditで任意のPostを選択し、
　　[File]->[Edit With CotEditor]
　　を実行する。
　
 3. 適当に編集して保存後、ウインドウを閉じる。

 4. MarsEditのPost上に、保存内容が反映されていない。 (不具合)

■備考
・同様の操作を、TextWranglerというエディターを対象にして行った場合、
　保存->ウインドウを閉じた際にMarsEditのPostにもすぐに反映されます。
　
・3.0.4で修正された
　「ウインドウを閉じたあと MarsEdit 編集結果が反映されなかった不具合を修正」
　とはこのことかと思うのですが、私の環境ではまだ出来ない状況です。
　何か、確認することがありましたらご教示ください。

## Expected Result (期待される挙動)

MarsEditの外部エディターとして使ったときに、
保存が反映されること。

**Comment by 1024jp** [comment]
うーん、念のため、CotEditor のバージョンが 3.0.4 であることをを再度確認の上、以下のことを教えてください。

1. MarsEdit のバージョン
2. MarsEdit の入手元 (AppStore / MarsEdit サイトから)
3. MarsEdit が AppStore 製の場合：
    1. /Applications/MarsEdit.app の「パッケージを開」いた中にある、Contents/Info.plist の中身が知りたい（このページに添付もしくはコピーペースとしていただける助かります）
    2. サイトから直接落とした MarsEdit https://red-sweater.com/marsedit/ でも同様の症状か

**Comment by yuzuk2** [comment]
下記にご回答します。
　
1. MarsEdit のバージョン
　→3.7.8 (7375)です。
　　添付ファイルをご参照ください。
　
2. MarsEdit の入手元 (AppStore / MarsEdit サイトから)
　→AppStoreです。
　
3. MarsEdit が AppStore 製の場合：
/Applications/MarsEdit.app の「パッケージを開」いた中にある、Contents/Info.plist の中身が知りたい（このページに添付もしくはコピーペースとしていただける助かります）
サイトから直接落とした MarsEdit https://red-sweater.com/marsedit/ でも同様の症状か
　
　→Info.plistを添付しましたので、ご確認ください。 
　　また、サイトから直接落としたMarsEditでは、問題なく編集が反映されました。
　
添付ファイル：version.jpeg
　　　　　　　Info.plist.zip
　
　
以上、宜しくお願い致します。


![version](https://cloud.githubusercontent.com/assets/23065813/20002597/f64475a0-a2c4-11e6-83de-2a81d8920e00.jpeg)

[Info.plist.zip](https://github.com/coteditor/CotEditor/files/571235/Info.plist.zip)

**Comment by 1024jp** [comment]
ありがとうございます。MarsEdit の id が App Store 版とダウンロード版で異なるのが原因でした。
App Store 版についても追加しましたので 3.1.0 で反映される予定です。

**Comment by 1024jp** [comment]
ありがとうございます。MarsEdit の id が App Store 版とダウンロード版で異なるのが原因でした。
App Store 版についても追加しましたので 3.1.0 で反映される予定です。

**Comment by 1024jp** [comment]
ありがとうございます。MarsEdit の id が App Store 版とダウンロード版で異なるのが原因でした。
App Store 版についても追加しましたので 3.1.0 で反映される予定です。

**Comment by 1024jp** [comment]
ありがとうございます。MarsEdit の id が App Store 版とダウンロード版で異なるのが原因でした。
App Store 版についても追加しましたので次で反映される予定です。
