### ISSUE TITLE
ファイルを開いたとき、テキストの1行目が隠れて表示されない場合がある

### ISSUE THREAD

**Issue by usami-k** [coteditor/CotEditor#632]
## Environment (環境)

- CotEditor: 3.0.4 (167)
- System: macOS バージョン10.12.1（ビルド16B2555）
- Language: Japanese

## Short Description (簡単な説明)

ファイルを開いたとき、テキストの1行目が隠れて表示されない場合がある。

## Steps to Reproduce the Issue (不具合が発生したときに行っていた操作、または再現手順)

CotEditor が起動していない状態から、何か適当なテキストファイルを CotEditor で開いたときに、ときどき発生するようです。再現条件は分かっていません。
発生したとき、ウィンドウをリサイズすると正常な表示に戻ります。

![20161104](https://cloud.githubusercontent.com/assets/536781/20002868/7dc033ec-a2c6-11e6-8237-770e65a8f3a9.png)

## Expected Result (期待される挙動)

テキストの1行目が隠れずに表示されること。

**Comment by 1024jp** [comment]
あぁしまった。それまだ起こるんですね...。macOS と Xcode がベータの時に起こっていてその時は迂回コードを入れていたのですが、正式版で直ったかと勘違いして抜いてしまいました。
また差し戻します。

**Comment by 1024jp** [comment]
cf. #600
