### ISSUE TITLE
Cannot open files of the specific extension in Finder / 特定の拡張子のファイルがFinderから開けない

### ISSUE THREAD

**Issue by KKQ-KKQ** [coteditor/CotEditor#635]
Finderから"README"などの拡張子がないファイル、もしくはCotEditorで対応していない拡張子のファイルを右クリックして「ファイルを CotEditor で開く」を押すと、
> ファイル"README"のフォーマットが正しくないため、開けませんでした。

というメッセージが出てしまいます。
同じファイルをCotEditorのメニューから開くと正常に開きます。

**Comment by 1024jp** [comment]
再現できません。

CotEditor と Mac のバージョンを教えてください。
また、

> ファイル"README"のフォーマットが正しくないため、開けませんでした。

のアラートは CotEditor 上で表示されているものでしょうか？それとも Finder ですか？
できればアラートウインドウのスクリーンショットもいただきたいです。
マシン上に CotEditor.app が複数インストールされていないかも気になります。

**Comment by KKQ-KKQ** [comment]
バージョンの書き忘れ、失礼しました。
OS X El Capitan 10.11.6
CotEditor 3.0.4

アラートはCotEditorで表示されます。
この機能が追加された頃から発生していたような気がします。
複数インストールは検索をしてみましたが1つしか出てきませんでした。

スクリーンショットは「configure.ac」ファイルをFinderから開いたところです。
![2016-11-10 18 15 10](https://cloud.githubusercontent.com/assets/23325395/20170946/c6ca0e46-a771-11e6-9163-e75a3ac9b9c1.png)

なお、Finderからのファイル名の変更では拡張子は消せませんので、「情報を見る」からファイル名を変更する必要があります。

**Comment by KKQ-KKQ** [comment]
追記です。
Finderからの右クリックメニューの「ファイルを CotEditor から開く」は、環境によっては「サービス」の中にあります。

**Comment by 1024jp** [comment]
あ、サービスの方ですね。すみません、勘違いしていました。再現しました。バグだと思われるので修正します。
お手数おかけしました。

**Comment by 1024jp** [comment]
本件、次 (3.0.5) の次 (3.1.0) のリリースで修正される予定です。
