### ISSUE TITLE
Localize added strings

### ISSUE THREAD

**Issue by 1024jp** [coteditor/CotEditor#637]
I'm not yet decided CotEditor 3.1.0 is ready for release. However, I wanna let all the added strings be localized once at this time point. 

### Chinese

@onevcat Please localize strings with `FIXME:` tag in the .strings files as usual. (The line-up of the to-be-localized strings are not the same as the following Italian ones)

### Italian

@AgostinoM Please localize the following strings to Italian and post them in this issue page.

```c
// Find panel (result message in the replacement string field)
"Not Replaced";
"%@ replaced";  // %@ is number of replaced

// Touch bar item labels
"Shift";  // group button label for "Shift Left" and "Shift Right" actions
"Text Size";

// Window preferences pane
"Prefer Tabs:";
"Respect System Setting";  // setting option for "Prefer Tabs"
"(Only on Sierra and later)";
```

reference for the "Prefer Tabs" option
![screen shot 2016-11-14 at 14 40 27](https://cloud.githubusercontent.com/assets/1165044/20254473/51473c2a-aa78-11e6-8bac-ee35bd943c86.png)

**Comment by AgostinoM** [comment]
Not replaced = Non sostituiti
@ replaced = @ sostituzioni

Shift = Scorri
Text size = Dimensione testo

Prefer tabs = Pref. pannelli
Respect System Setting = Come imp. di sistema
Only on Sierra and later = Solo su Sierra e successivi

**Comment by 1024jp** [comment]
@AgostinoM Thank you very much 🐈
