### ISSUE TITLE
Doucment cannnot be opened on CotEditor 3.1.0

### ISSUE THREAD

**Issue by 1024jp** [coteditor/CotEditor#640]
under some environments...

**Comment by usami-k** [comment]
手元で 3.1.0 をデバッグ実行してみたところ、AppDelegate の以下の箇所でクラッシュします。macOS 10.12.1 + Xcode 8.1 です。

```
        // setup touchbar
        if #available(macOS 10.12.1, *) {
            NSApp.isAutomaticCustomizeTouchBarMenuItemEnabled = true
        }
```

**Comment by 1024jp** [comment]
ありがとうございます。素晴らしい。だとすると、予想が当たったっぽいです...。今テスト版を作成したので cl.ly/i98p これで問題が解決しているようであればすぐにリリースを出します。

**Comment by usami-k** [comment]
テスト版をダウンロードして試したところ、アプリが起動してファイルが開けることが確認できました。

**Comment by 1024jp** [comment]
ありがとうございます！ ビンゴだ。これを 3.1.1 としてリリースします。non-AppStore 版は 3.1.0 は飛ばしてそっちを出しましょう。

**Comment by usami-k** [comment]
了解しました。

**Comment by 1024jp** [comment]
fixed

**Comment by 1024jp** [comment]
訂正。念のため目立つように 3.1.1 がリリースされるまではオープンにしておきます。すでに修正済みの案件です。
