### ISSUE TITLE
File/Project Browser

### ISSUE THREAD

**Issue by diethardsteiner** [coteditor/CotEditor#642]
As a developer I'd like to see all the files of my current project in a side bar (like e.g. in TextMate) so that I can open multiple files in tabs easily. Can you please add this feature?

**Comment by 1024jp** [comment]
I know some users want to have this feature and therefore it's actually a duplicated issue (see #278).
Just because of my limited development time, it's not a high priority in my todo list now.

I close this issue due to duplication but it doesn't mean rejected.
