### ISSUE TITLE
Localize Credits.html in Chinese

### ISSUE THREAD

**Issue by 1024jp** [coteditor/CotEditor#643]
I've totally forgotten to ask @onevcat to localize Credits.html in Chinese for a long time. It's an HTML file for the "About CotEditor" menu action and placed at `CotEditor/zh-Hans.lproj/Credits.html`.

I'm not in hurry at all. So @onevcat, would you localize it when you have time?

**Comment by onevcat** [comment]
Sure, I will do it later.
