### ISSUE TITLE
Default Document Window should close when opening another document

### ISSUE THREAD

**Issue by maximeplante** [coteditor/CotEditor#654]
## Environment

- CotEditor: 3.1.1 (174)
- System: macOS Version 10.12.1 (Build 16B2555)
- Language: English

## Short Description

When opening CotEditor, an empty default document is opened (named Untitled) as it is expected in any code editor. However, when the user opens another document without modifying the empty document, the default document window should automatically close.

## Steps to Reproduce the Issue

- Open CotEditor by clicking on its icon.
- An empty document is automatically created.
- Go in File > Open and open any document.
- The document will open, but the default document stays open.

## Expected Result

In most code editors, when opening a file, the default empty document created automatically closes.

**Comment by Max840** [comment]
I successfully implemented this new behavior in the code. If the change is accepted, I will refine it a bit and submit it as a pull request.

**Comment by 1024jp** [comment]
It's actually by design. 

Previously (several years ago), CotEditor also had this behavior but I purposely removed it. I know some text editors including major ones have this feature, however IMHO, it's not so common in native macOS apps.

**Comment by Max840** [comment]
I totally agree CotEditor should keep a native macOS feeling. It is one of the main reason I like this editor.

However, there could be a checkbox in the settings to allow this behavior.

**Comment by 1024jp** [comment]
Well, then, give me time to consider. I don't wanna add setting options easily. But if it is really needed, then it should be.

**Comment by fiery-** [comment]
I agree with @maximeplante, that we need an option to close the empty document when user opens CotEditor with a specific txt document (i.e. by double clicking in the Finder or by drag&drop on Dock icon). Or better yet just don't open the empty (Untitled) document in that case. You may open it only when user launches CotEditor alone (there is already an option for that in Preferences, which is useful, but it should work only if I start the app alone).

**Comment by 1024jp** [comment]
I've just changed my mind.
I'll implement this feature to CotEditor 3.3.0 since I realized that Apple's TextEdit.app has a similar feature.
The sample source code of the TextEdit by Apple helps a lot.
