### ISSUE TITLE
現在行がハイライトされない / Current line is not highlighted

### ISSUE THREAD

**Issue by dsdsk** [coteditor/CotEditor#655]
## Environment (環境)

- CotEditor: 3.1.2 (177)
- System: macOS バージョン10.12.1（ビルド16B2657）
- Language: Japanese

## Short Description (簡単な説明)

現在行がハイライトされない

## Steps to Reproduce the Issue (不具合が発生したときに行っていた操作、または再現手順)

いつのバージョンからか不明ですが、通常起動、またはファイルを開いた時点で、既に現在行がハイライトされていない状態です。
カーソルで行を移動してみても、環境設定からテーマを切り替えてみてもハイライトされませんでした。

## Expected Result (期待される挙動)

現在行がハイライトされる。

**Comment by 1024jp** [comment]
うーん、手元の環境では通常通りハイライトがされています。

環境設定の「現在の行： 背景カラーの変更」はチェックが入っていますよね？
![screen shot 2016-12-10 at 15 19 58](https://cloud.githubusercontent.com/assets/1165044/21071691/1eab1808-beec-11e6-9dc0-51326c581a10.png)

念のため行の高さの設定も教えていただけますか？

**Comment by dsdsk** [comment]
> 環境設定の「現在の行： 背景カラーの変更」はチェックが入っていますよね？

あ、こちらのチェックボックスがオフになっていました。
チェックをオンにしたところ、現在行がハイライトされました。

が、この設定自体いじったことはないので、何のタイミングでオフになったのか不明です・・・。

**Comment by 1024jp** [comment]
いずれにせよ良かったです。
閉じときますね。
