### ISSUE TITLE
font selector doesn't open.

### ISSUE THREAD

**Issue by giuseppeannunziata** [coteditor/CotEditor#662]
## Environment

- CotEditor: 2.5.7 (138)
- System: OS X Version 10.9.5 (Build 13F1911)
- Language: English

## Short Description

Font selector into appearance dosn't work.

## Steps to Reproduce the Issue

Open Preference, select tab Appearance and click on [select...] button near font indicator. 

## Expected Result

Open font dialog to select another font. Nothing happen (neither error message).

**Comment by 1024jp** [comment]
Hmm, it works under my environment (macOS 10.12). I'll try it on OS X 10.9 later.

BTW:
1. Does it occur from the beginning or at some time point?
2. Can you open the font panel selecting Format > Font > Show Fonts?

**Comment by 1024jp** [comment]
I tried this on my OS X 10.9.5 and it works for me.

As I mentioned in [CotEditor for earlier macOS](https://coteditor.com/archives), we now don't support CotEditor 2 series anymore. Therefore, I don't take a measure for this issue but just close.
