### ISSUE TITLE
The program is in Japanese, how do I change it so it is in English?

### ISSUE THREAD

**Issue by nicolasmin02** [coteditor/CotEditor#665]
I installed the program directly from the Appstore, but as soon as I opened it it was in japanese, I don't really know japanese so I have  no way of knowing what it says.
And every time I try to look up something to base myself on, (example: "how to change the language on Coteditor") It just shows up how to change the Programming language. What do I do?

**Comment by 1024jp** [comment]
In such case, go to the __Language & Region__ pane in the __System Preferences__ and bring the priority of English higher than Japanese.

<img width="890" alt="screen shot 2017-01-09 at 2 30 54" src="https://cloud.githubusercontent.com/assets/1165044/21752046/efa5d198-d614-11e6-8128-c2ddca22ac5d.png">

After changing the priority, you need to restart CotEditor.

This is the standard way on macOS how the language of a software is set.

**Comment by nicolasmin02** [comment]
@1024jp It worked! Thanks a million!
