### ISSUE TITLE
Feature Request: Bookmarks

### ISSUE THREAD

**Issue by rovf** [coteditor/CotEditor#667]
It would be helpful to be able to set bookmarks in the code and jump to them. 

I.e. new commands in the "Find" Menu

- toggle bookmark
- jump to next bookmark in file
- jump to previous bookmark in file

**Comment by 1024jp** [comment]
Duplicated request #300.

I'm relatively positive about this feature. However, at the same time, the priority is not so high. I'll implement it when I feel like it.
