### ISSUE TITLE
A strange behavior about regular expression

### ISSUE THREAD

**Issue by tatsy-ymj** [coteditor/CotEditor#669]
I found a strange behavior about regular expression on 3.1.2.

The below is a sample text.

　あいうえお
あいうえお

When I search "^[　]", there is no problem. The Zenkaku space of line 1 is just hit.
However, when I search "^[^　]", Every character of line 2 is hit.

When I tried with another text editor (JeditX), only "あ" of line 2 is hit, and it is an expected behavior.

**Comment by 1024jp** [comment]
Thanks for the feedback.

This seems a side-effect of a previous behavior change on  04fb1f2e5d9c20ca02e663cfa1ab4da350741e40. I understand your problem. I'll consider.

**Comment by 1024jp** [comment]
The issue will be fixed in the next CotEditor 3.1.3. Thanks.
