### ISSUE TITLE
全画面表示時，行番号部分だけテーマが正しく適用されない．

### ISSUE THREAD

**Issue by NSTomoS** [coteditor/CotEditor#672]
## Environment (環境)

- CotEditor: 3.1.3 (180)
- System: macOS バージョン10.12.3（ビルド16D32）
- Language: Japanese

## Short Description (簡単な説明)

全画面表示時，行番号部分だけテーマが正しく適用されない．

## Steps to Reproduce the Issue (不具合が発生したときに行っていた操作、または再現手順)

テーマをデフォルトでないものに設定していた時，ウィンドウ表示から全画面表示に切り替えた際に，行番号表示部分の背景がデフォルトテーマの背景色になる．
全画面表示状態で設定を開きテーマを再選択すると正しい背景色になる．

## Expected Result (期待される挙動)

全画面表示にした際に行番号表示部分の背景色が設定しているテーマの背景色に設定される．

**Comment by 1024jp** [comment]
症状確認しました。バグだと思われるので次回までの修正を試みます。
