### ISSUE TITLE
"Help" doesn't appear even in 3.1.3

### ISSUE THREAD

**Issue by tatsy-ymj** [coteditor/CotEditor#673]
## Environment (環境)

- CotEditor: 3.1.3 (180)
- System: macOS バージョン10.12.4（ビルド16E144f）
- Language: Japanese

## Short Description (簡単な説明)

"Help" doesn't appear.

## Steps to Reproduce the Issue (不具合が発生したときに行っていた操作、または再現手順)

- Select "ヘルプ" -> "CotEditor ヘルプ"
- Select "ヘルプ" -> "CotEditor スクリプトマニュアル" -> "スクリプトについて"

On both cases, help window appears but no contents is displayed.

![2017-02-04 13 01 39](https://cloud.githubusercontent.com/assets/4995795/22615559/3a4976b2-eada-11e6-82ba-4ee9026720e1.png)

**Comment by 1024jp** [comment]
Hmm, that's strange. At least, it works under my environment (CotEditor 3.1.3 + macOS 10.12.3). Is the situation the same after rebooting the whole macOS system?
Furthermore, it seems you are using a beta macOS. Is it possible to try it on a stable system?

-- 

うーん、こちらの環境では動いているのですが、Mac ごと再起動しても同じ感じですか？ また、現在ベータ版の macOS をお使いのようですが、それが関係している可能性はありますか？

**Comment by tatsy-ymj** [comment]
再起動では同じ症状だったんですが、パブリックベータ2ではちゃんと表示されるようになりました（OSのバージョンだけが理由かどうかは不明ですが……）。お騒がせしました。

**Comment by 1024jp** [comment]
おや、それは良かったです。安心しました。ご報告ありがとうございます。


-----

This issue has been fixed on macOS 10.12.4-beta.2.
