### ISSUE TITLE
Cannot open document due to incorrect permission error

### ISSUE THREAD

**Issue by cormullion** [coteditor/CotEditor#674]
## Environment

- CotEditor: 3.1.3 (180)
- System: macOS Version 10.12.3 (Build 16D32)
- Language: English

## Short Description

Can't open files in /tmp.

## Steps to Reproduce the Issue

In Terminal:

    $ cd /tmp
    $ touch temp.txt

In CotEditor:
     
    File>Open... 

Try to open this file in /tmp.

## Expected Result

Expected file to open. But Alert says I don't have permission. 

![screen shot 2017-02-07 at 18 17 53](https://cloud.githubusercontent.com/assets/52289/22705077/019615e8-ed62-11e6-9de4-f7d37f7c50e2.png)

Is this because I'm using the App store version?

**Comment by 1024jp** [comment]
Interesting. However, it works under my environment. I can open my newly created file at /tmp/tmp.txt with my CotEditor from the MAS. So, is there any conditions not described yet?
Please tell me the permissions of your temp.txt that can not be opened in CotEditor.

**Comment by cormullion** [comment]
Files are 

    -rw-r--r--

owned by me  in group `wheel`.

The error is "SandboxViolation":

```
SandboxViolation: CotEditor(39980) deny file-read-data /private/tmp/temp.txt
Violation:       deny file-read-data /private/tmp/temp.txt
Process:         CotEditor [39980]
Path:            /Applications/CotEditor.app/Contents/MacOS/CotEditor
Load Address:    0x10a18e000
Identifier:      com.coteditor.CotEditor
Version:         180 (3.1.3)
Code Type:       x86_64 (Native)
Parent Process:  launchd [1]
Responsible:     /Applications/CotEditor.app/Contents/MacOS/CotEditor [39980]
User ID:         502

Date/Time:       2017-02-08 08:21:29.637 GMT
OS Version:      Mac OS X 10.12.3 (16D32)
Report Version:  8

Thread 0 (id: 2319368):
0   CoreFoundation                	0x00007fff8a0281ff __CFBasicHashAddValue + 1919
1   CoreFoundation                	0x00007fff8a028b9d CFDictionarySetValue + 221
2   CoreFoundation                	0x00007fff8a0838d8 _CFDoExceptionOperation + 248
3   AppKit                        	0x00007fff87c19e9e -[NSViewHierarchyLock _lockForWriting:handler:] + 576
4   AppKit                        	0x00007fff87e44c85 __19-[NSWindow release]_block_invoke + 397
5   AppKit                        	0x00007fff87be69d9 -[NSWindow release] + 112
6   libobjc.A.dylib               	0x00007fff9edb2e60 (anonymous namespace)::AutoreleasePoolPage::pop(void*) + 808
7   CoreFoundation                	0x00007fff8a063106 _CFAutoreleasePoolPop + 22
8   Foundation                    	0x00007fff8bac9f13 -[NSAutoreleasePool drain] + 146
9   AppKit                        	0x00007fff87bc7fdc -[NSApplication run] + 1093
10  AppKit                        	0x00007fff87b92850 NSApplicationMain + 1237
11  CotEditor                     	0x000000010a195bc9
12  libdyld.dylib                 	0x00007fff9f69f255 start + 1
13  CotEditor                     	0x0000000000000001

Thread 1 (id: 2319408, com.apple.NSEventThread):
0   libsystem_kernel.dylib        	0x00007fff9f7c638a mach_msg_trap + 10
1   CoreFoundation                	0x00007fff8a0a3e84 __CFRunLoopServiceMachPort + 212
2   CoreFoundation                	0x00007fff8a0a3301 __CFRunLoopRun + 1361
3   CoreFoundation                	0x00007fff8a0a2b54 CFRunLoopRunSpecific + 420
4   AppKit                        	0x00007fff87d20a62 _NSEventThread + 205
5   libsystem_pthread.dylib       	0x00007fff9f8b6aab _pthread_body + 180
6   libsystem_pthread.dylib       	0x00007fff9f8b69f7 _pthread_body + 0
7   libsystem_pthread.dylib       	0x00007fff9f8b61fd thread_start + 13

Thread 2 (id: 15326062):
0   libsystem_kernel.dylib        	0x00007fff9f7ce4e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff9f8b61ed start_wqthread + 13

Thread 3 (id: 15326625):
0   libsystem_kernel.dylib        	0x00007fff9f7ce4e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff9f8b61ed start_wqthread + 13

Thread 4 (id: 15326629):
0   libsystem_kernel.dylib        	0x00007fff9f7cdad2 __open + 10
1   Foundation                    	0x00007fff8bb84be2 +[NSFileVersion(NSPrivate) _permanentVersionStorageSupportedForURL:temporaryStorageIdentifier:error:] + 63
2   AppKit                        	0x00007fff886b2ea8 -[NSDocument(NSDocument_Versioning) _updateTemporaryVersionStorageState] + 193
3   AppKit                        	0x00007fff87df48f3 -[NSDocument _setFileURL:] + 493
4   CotEditor                     	0x000000010a2a6601
5   CotEditor                     	0x000000010a29d545
6   AppKit                        	0x00007fff87df44f3 -[NSDocument _initWithContentsOfURL:ofType:error:] + 44
7   AppKit                        	0x00007fff87df4458 -[NSDocument initWithContentsOfURL:ofType:error:] + 231
8   AppKit                        	0x00007fff87ed1a50 -[NSDocumentController makeDocumentWithContentsOfURL:ofType:error:] + 644
9   CotEditor                     	0x000000010a336b2d
10  CotEditor                     	0x000000010a33513c
11  AppKit                        	0x00007fff88124a92 __97-[NSDocumentController makeDocumentWithContentsOfURL:alternateContents:ofType:completionHandler:]_block_invoke + 83
12  Foundation                    	0x00007fff8baf72d9 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
13  Foundation                    	0x00007fff8baf6fbc -[NSBlockOperation main] + 101
14  Foundation                    	0x00007fff8baf56e4 -[__NSOperationInternal _start:] + 672
15  Foundation                    	0x00007fff8baf159b __NSOQSchedule_f + 201
16  libdispatch.dylib             	0x00007fff9f6690b8 _dispatch_client_callout + 8
17  libdispatch.dylib             	0x00007fff9f67fae5 _dispatch_queue_serial_drain + 896
18  libdispatch.dylib             	0x00007fff9f671cd9 _dispatch_queue_invoke + 1046
19  libdispatch.dylib             	0x00007fff9f66ae70 _dispatch_root_queue_drain + 476
20  libdispatch.dylib             	0x00007fff9f66ac47 _dispatch_worker_thread3 + 99
21  libsystem_pthread.dylib       	0x00007fff9f8b6712 _pthread_wqthread + 1299
22  libsystem_pthread.dylib       	0x00007fff9f8b61ed start_wqthread + 13

Binary Images:
       0x10a18e000 -        0x10a3f7fff  com.coteditor.CotEditor (3.1.3 - 180) <ba37b7eb-b0c4-3164-ad35-e5f12ad6f90c> /Applications/CotEditor.app/Contents/MacOS/CotEditor
    0x7fff87b8c000 -     0x7fff8895eff3  com.apple.AppKit (6.9 - 1504.81.100) <0ccb2e18-076e-3d8a-a777-a6e57ef2570a> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff8a01e000 -     0x7fff8a4b2ff7  com.apple.CoreFoundation (6.9 - 1348.28) <0f1faa52-1c06-327e-a170-382b48b1846d> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff8bab3000 -     0x7fff8be5aff3  com.apple.Foundation (6.9 - 1349.25) <d820a498-2e62-367d-bc72-5845b14c06e3> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff9eda9000 -     0x7fff9f17e127  libobjc.A.dylib (706) <47104a1b-13e8-369f-bc36-27ff465809fd> /usr/lib/libobjc.A.dylib
    0x7fff9f667000 -     0x7fff9f699fff  libdispatch.dylib (703.30.5) <ea0cc14e-d559-3802-b4b2-0e8c7579aac4> /usr/lib/system/libdispatch.dylib
    0x7fff9f69a000 -     0x7fff9f69fff3  libdyld.dylib (421.2) <6f506653-fff6-3db8-84f1-109ae3c52f32> /usr/lib/system/libdyld.dylib
    0x7fff9f7b4000 -     0x7fff9f7d6ff7  libsystem_kernel.dylib (3789.41.3) <b75b128c-7d7a-3318-91cd-82b5a69c5329> /usr/lib/system/libsystem_kernel.dylib
    0x7fff9f8b3000 -     0x7fff9f8bdff7  libsystem_pthread.dylib (218.30.1) <c869ed7c-be29-3532-8e69-3a8da1447edc> /usr/lib/system/libsystem_pthread.dylib
```

**Comment by 1024jp** [comment]
Thank you for the additional information.

Hmm, I don't think this caused because the app is the App Store version. It should be able to open. Does the general fix like the followings help?:

- [Repair a disk using Disk Utility](https://support.apple.com/kb/PH22243?locale=en_US)
- [Reset the System Management Controller (SMC) on your Mac](https://support.apple.com/en-us/HT201295)

And what if you open the file not from the open panel but for example by dropping the file to the CotEditor's icon in Dock.

**Comment by cormullion** [comment]
Some more details. After restarting CotEditor, the same files can be opened and saved. So the cause of this problem is something that arises while CotEditor is running. When I first ran CotEditor it was working fine. But after some time (perhaps a few days) of being open, the app started having these permissions issues. I'll keep an eye out in case it starts again.

By the way, this is a really nice editor, and a great pleasure to use! All it needs to be perfect is multiple cursors, like Atom and VisualCode... :)

**Comment by 1024jp** [comment]
Aha, ok, then I remember that I heard that problem from another user before. This issue can occur not only in /tmp directory but anywhere. I only know that this issue can temporary resolve by restarting CotEditor, as you said. 
I'm still working on this and no clue was found so far. Sorry but it may takes time to resolve. But your console log may helpful. I'll look into.

> By the way, this is a really nice editor, and a great pleasure to use! All it needs to be perfect is multiple cursors, like Atom and VisualCode... :)

Thanks. The request for multi-corsor is already registered at #307. It's not implemented yet only because the development of CotEditor is slow since just one person, namely I, develops this app in my free time.

**Comment by 1024jp** [comment]
cf. https://twitter.com/Aquavit/status/796988420555845632

**Comment by 1024jp** [comment]
__note__: The following case on TextEdit.app seems exactly the same as this isse:
[Denied file read access on file I own and have full r/w permissions on](http://apple.stackexchange.com/a/105167/183082)

**Comment by 1024jp** [comment]
I suppose these issues can be based on the same cause:
- [Log error when accessing the apple menu in a Sandboxed macOS App](https://forums.developer.apple.com/thread/69515)
- [NSUserDefaults stopping working](https://forums.developer.apple.com/thread/27049)

**Comment by 1024jp** [comment]
Is there anyone who came across this issue on the macOS High Sierra (or later)?

**Comment by 1024jp** [comment]
I suppose this issue doesn't exist anymore on macOS 10.13.0 with CotEditor 3.2.3.
Please reopen if you still come across this.

**Comment by F474M0R64N4** [comment]
same problem

**Comment by 1024jp** [comment]
Hmm, this works for me with CotEditor 4.4.0-beta + macOS 12.5.1. Let me know your environment and the steps to reproduce.

**Comment by F474M0R64N4** [comment]
Need to ask permission for a folder

**Comment by 1024jp** [comment]
@F474M0R64N4 Sorry, but your information is too few to address the issue.
Please answer my previous question, otherwise, I cannot help.

> Let me know your environment and the steps to reproduce.
I mean the "environment" here by the version of your macOS and CotEditor.
