### ISSUE TITLE
スクロール表示の不具合

### ISSUE THREAD

**Issue by kenkob** [coteditor/CotEditor#680]
いつも愛用させてもらっております。

【環境】
・OSX10.11.6
・2.5.7 から 3.1.5へ、バージョンアップした
・日本語環境

【現象】
・長めの文書を開く
　↓
・コマンド+aで全選択する
　↓
・カーソルキーの「↓」キーを押す。

上記手順を行うと、文書の最下部が表示されるはずが、途中でスクロールが止まる

（補足）
・何度か上記手順を繰り返し、一度文書最下部を表示させると、ファイルを閉じるまで正常に動作する。
・Endキーでは正常に最下部が表示される。ただしカーソルは文書頭（正常動作）。

**Comment by 1024jp** [comment]
症状確認＆修正しました。
次のバージョンで反映されます。
フィードバックありがとうございました。

**Comment by kenkob** [comment]
神速のご対応ありがとうございます。
