### ISSUE TITLE
文字列をダブルクリックした時の選択範囲

### ISSUE THREAD

**Issue by kenkob** [coteditor/CotEditor#681]
要望です。

【環境】
・OSX10.11.6
・バージョン3.1.5
・日本語環境

【要望】
文字列をダブルクリックした時の選択範囲を、設定できるようにしてほしい
（例）
・現状　：　山田太郎　→　「山田」あるいは「太郎」が選択される
・要望　：　山田太郎　→　「山田太郎」が選択されるオプションを追加（漢字つながり・ひらがなつながり・数字つながり・・・等が選択される（エディタ「mi」での動作））

**Comment by 1024jp** [comment]
要望ありがとうございます。
ただ、CotEditor は闇雲に環境設定を増やさない方針なので、このような細かい設定を追加することはしないつもりです。

**Comment by kenkob** [comment]
ご返信ありがとうございます。

そうですか。。。当方コピペを繰り返す作業が多いので、あればありがたかったのですが。。。
了解しました。
