### ISSUE TITLE
Multiple "File Drop" formats for same extension(s)

### ISSUE THREAD

**Issue by marc-medley** [coteditor/CotEditor#687]
## Environment
- CotEditor: 3.1.7 (188)
- System: macOS Version 10.12.3 (Build 16D32)
- Language: English

## Short Description

**Enhancement Request:** Support a one of many selection prompt dialog in cases where the same extension has more than one available `File Drop` `Insertion Format`.

**Use Case:** As a user, my productivity to be improved with a `File Drop` prompt to select between a HTML, Markdown, or Path Only `File Drop` `Insertion Format`. 

## Steps to Reproduce the Issue

In Preferences, observer or add the (original default) jpg, jpeg, gif, png `Insertion Format`:

> `<img src="<<<RELATIVE-PATH>>>" alt="<<<FILENAME-NOSUFFIX>>>" title="<<<FILENAME-NOSUFFIX>>>" width="<<<IMAGEWIDTH>>>" height="<<<IMAGEHEIGHT>>>" />`

In Preferences, without removing the default mentioned above, add `+`  another same `Extensions` set jpg, jpeg, gif, png `Insertion Format`:

> `![<<<FILENAME-NOSUFFIX>>>](<<<RELATIVE-PATH>>>)`

Optionally, a Path Only can be added jpg, jpeg, gif, png `Insertion Format` as:

> `<<<RELATIVE-PATH>>>`

## Expected Result

1. Present a dialog list of available `Insertion Format` for the particular extension.
2. Have the first listed in Preference be selected in the prompt dialog as the quick carriage return.
3. Ideally, have a way to name for the `Insertion Format` in Preference panel. And, show such names in the `Insertion Format` prompt dialog.

**Comment by 1024jp** [comment]
Good. I just think about this kind of enhancement recently. I'll implement in the near future.

**Comment by marc-medley** [comment]
I look forward to when this feature is available.  Thanks.

Some optional details to consider for a multiple "File Drop" formats dialog feature: 

1. Have the formats present in a table which allows user `Insertion Format` selection with either a mouse click or up/down arrow keys.

2. Support order of appearance for `Insertion Format Name` like `01)` similar to CotEditor script name patterns.   The name pattern could let the user control the order presented on a format choice dialog.  

![filedropnamepattern](https://cloud.githubusercontent.com/assets/15098151/23636789/60a84512-028c-11e7-9d46-919ee8b96731.png)

**Comment by 1024jp** [comment]
So far, I implemented this feature as below (it's still WIP and can be chaned in the final product).

<img width="879" alt="screen shot 2017-03-08 at 9 35 42" src="https://cloud.githubusercontent.com/assets/1165044/23684518/a0793456-03e2-11e7-8180-deb0c6a87903.png">


The priorities can be set by drag & drop the rows.

**Comment by marc-medley** [comment]
Thanks for the udpate.

In my use case, I would like to _dynamically select_ an Insertion Pattern at the time when the file is added.  This would be a different interaction than a static assignment to a syntax style.

For example, sometimes I use an "HTML style" link in a Markdown document since Markdown does allowed the inclusion of HTML.  This is a non-default case where I need to specify an image height and/or width property.  A Markdown link does not have this control.

Another example, in an HTML document, one might wish to dynamically choose between a `Simple HTML` format or `Bootstrap HTML` format which includes selected class attribute(s) for example `<img class="media-object" src="..." alt="...">`

**Comment by 1024jp** [comment]
> Is the Drop Definition "Syntax Style" based on the current document "Syntax Style"? Or, is the Drop Definition "Syntax Style" more like a name the user can choose at the time of adding a file link?

It's based on the current document style and user can set it one (or all) for each row. Namely, the file drop setting is available only if the style of the document in which files are dropped is pecified one. If there are more than one available settings, then jsut the most top setting is used.

I understood your needs, however, even so, I'll not implement dynamic file drop selection. I suppose your demand is really minor and too complicated for others. Sorry for that.
