### ISSUE TITLE
Option + 矢印移動時 行末で止まって欲しい / Stop caret at end of line

### ISSUE THREAD

**Issue by yuhei-mukoyama** [coteditor/CotEditor#69]
現在の CotEditor の動作は OS X 標準のどおりのなので要望となります。

Option + ← or Option + → で移動時行末で止まらない場合があります。

文章では分かりづらいと思ったので、Gif アニメーションにしました。
![2014-03-23 00_49_24](https://f.cloud.github.com/assets/5656927/2491069/9bbf89aa-b1d9-11e3-9104-e7f1dc008244.gif)

出来れば行末で止まって欲しいと思うのですが、いかがでしょうか。

理由としては
- 動きが単純に不自然であるように感じる
- vim や Sublime Text 等のエディタが行末で止まるようになっている為
- 思わず癖でやってしまう（個人的

ただし、Cmd + → 等の行末移動のショート・カットを利用するべきシーンである為、この操作自体が無駄であるとも言えます。

ご検討下さい。よろしくお願いします。

**Comment by 1024jp** [comment]
申し訳ない。本件についてはwon't fix にさせてください。
