### ISSUE TITLE
Feature request: expand/ collapse mode for json file type

### ISSUE THREAD

**Issue by datnm** [coteditor/CotEditor#691]
<img width="366" alt="screen shot 2017-03-07 at 3 51 32 pm" src="https://cloud.githubusercontent.com/assets/5654360/23648665/33526576-034e-11e7-9c99-78a1c4ffe0ea.png">
When open json file, I want to expand/ collapse for the each block data.
Please add more function for json file type as attach image.

Thanks!

**Comment by 1024jp** [comment]
I close this issue as it's duplicate request #459.
