### ISSUE TITLE
起動時に前回終了時のファイルを開いてくれるオプションが欲しいです

### ISSUE THREAD

**Issue by owanf** [coteditor/CotEditor#693]
起動時に前回終了時のファイルを開いてくれるオプションが欲しいです。

**Comment by 1024jp** [comment]
#463 ですでに同様のリクエストがあるので、本 issue に関しては重複ということでクローズします。

----

内容について改めていうと、本件はすでに設定次第で実現可能です。

1. CotEditor の環境設定「一般」で、オートセーブを有効にする
2. システム環境設定の「一般」で「アプリケーションアイコンを終了するときにウインドウを閉じる」のチェックを外す

の2条件が揃うと、表題通りの振る舞いをするようになります。ただし、システム環境設定の方の設定変更については他のアプリケーションにも影響します。

（しかし、それにもかかわらずたまにもらうリクエストでもあるので、CotEditor 内で完結できるかどうか考えてみるべきなのかもしれません。）

**Comment by owanf** [comment]
既に同様の要望があったとのこと。また，設定で可能とのこと。
有難うございます。お手数をお掛けしました。
