### ISSUE TITLE
paste cursor key right/left page up/down

### ISSUE THREAD

**Issue by Chamiu** [coteditor/CotEditor#695]
CotEditor 3.1.8 on macOS Sierra.4.

I want to move cursor before or next character point after paste.

But now,
1. paste.
2. right key at page up, left key at page down.

Perhaps this issue at macOS Sierra.4.

**Comment by 1024jp** [comment]
Sorry, but I'm not sure about your issue.
Could you write it more in detail so that I can reproduce. Or in Japanese is also welcome.

**Comment by 1024jp** [comment]
一旦閉じるので、また必要があれば遠慮なく開けてください。
