### ISSUE TITLE
保存時にRubyコード中で使用されているEncodingクラスの定数に影響されて不要な警告が表示される / Don't display wrong IANA charset warning

### ISSUE THREAD

**Issue by jakago** [coteditor/CotEditor#698]
## Environment (環境)

- CotEditor: 3.1.8 (191)
- System: macOS バージョン 10.11.6（ビルド 15G1217）
- Language: Japanese

## Short Description (簡単な説明)

保存時にRubyコード中で使用されているEncodingクラスの定数に影響されて不要な警告が表示される。

## Steps to Reproduce the Issue (不具合が発生したときに行っていた操作、または再現手順)

・新規ファイル作成
・ツールバーで文字コードを「Unicode(UTF-8)」に設定
・一行目に「Encoding::Windows_31J」を記述（RubyのEncodingクラスの定数を参照するコード。この一行だけでも正しいRubyプログラム）
・保存を行おうとすると「エンコーディングは"Unicode (UTF-8)"ですが、IANA文字セット名は"日本語(Windows,DOS)です。」という警告が表示される
・上記の手順は新規の場合ですが、既存のUTF-8で記述されたプログラム内に「Encoding::Windows_31J」を記述すると、それ以降、保存時に警告が表示されるようになり不都合です

## Expected Result (期待される挙動)

RubyのEncodingクラスをファイルの文字コード指定と混同しないでください

**Comment by 1024jp** [comment]
うーん、これ私が引き継ぐ前からある機能なのですが、ご指摘の通り言語によっては誤爆もありなかなか悩ましいんですよねぇ。
現時点でも一度「今後この書類ではこの警告を表示しない」にチェックを入れるとウインドウで開いている間は保存しても再度警告を出さないようにしたのですが、一度閉じるとリセットされてしまうし。

精度を上げるか、機能を切れるようにするか、機能ごと撤廃するか、いずれにせよ次Ver.でテコ入れします。
