### ISSUE TITLE
[Bug]word/lines/location/characters count not work

### ISSUE THREAD

**Issue by cool8jay** [coteditor/CotEditor#699]
## Environment

- CotEditor: 3.1.8 (191) from Mac App Store
- System: macOS Version 10.12.4 (Build 16E183b)
- Language: English

## Short Description

These info do not update while typing.

## Steps to Reproduce the Issue

1. launch app
2. type some text

**Comment by 1024jp** [comment]
This is a known bug that will be fixed in the next version.

For a workaround until the release of the next version, you can see correct counts in the inspector (the side bar in document windows shown with "Get Info" toolbar button) at least.
