### ISSUE TITLE
Update localizations

### ISSUE THREAD

**Issue by 1024jp** [coteditor/CotEditor#701]
I'm now planning to release CotEditor 3.2.0 after several beta releases. So while beta testing, I beg you guys @onevcat and @AgostinoM to localize newly added strings.

### Chinese

@onevcat Please localize strings with `FIXME:` tag in the .strings files as usual. Furthermore, I also added a sentence to the ReportTemplate.md. I didn't add `FIXME:` tag but please localize that too.

### Italian

@AgostinoM Please localize the following strings to Italian and post them in this issue page.

```c
// Appearance preferences pane and Format preferences pane
"Reload All Themes";
"Reload All Styles";

// General preferences pane
"Link URLs in document";

// File Drop preferences pane
"File Drop Definitions:";
"File extensions of dropped file (comma separated).";
"Syntax style in which this file drop setting is enabled.";
"Insert Variable";  // button label

// Find Panel
"Empty find string";  // a warning message
"Input text to find.";  // tooltip
"The cursor position after inserting the snippet.";  // tooltip

// Bug report template
"Please write the contents either in English or in Japanese.";

// Custom Surround String Panel
"Surround With:";
"Begin:";
"End:";

// Menu items in the menu bar
"Surround Selection With";
"Parenthesis";  // name of ()
"Brackets";  // name of {}
"Custom…";
```

cf.  Custom Surround String Panel

<img width="311" alt="screen shot 2017-05-06 at 22 35 47" src="https://cloud.githubusercontent.com/assets/1165044/25772745/703e66b4-32ac-11e7-87a5-45a3f3de916a.png">

**Comment by AgostinoM** [comment]
// Appearance preferences pane and Format preferences pane
"Ricarica tutti i Temi";
"Ricarica tutti gli Stili";

// General preferences pane
"Collegamenti agli URL nel documento";

// File Drop preferences pane
"Definizioni dei file rilasciati:";
"Estensione dei file rilasciati (valori separati da virgola).";
"Stile della sintassi cui applicare questa impostazione sul rilascio.";
"Inserisci Variabile";  // button label

// Find Panel
"Stringa di ricerca vuota";  // a warning message
"Inserire il testo da cercare.";  // tooltip
"Posizione del cursore dopo aver inserito lo snippet.";  // tooltip

// Bug report template
"Si prega di scrivere in inglese oppure in giapponese.";

// Custom Surround String Panel
"Circonda con:";
"Inizio:";
"Fine:";

// Menu items in the menu bar
"Circonda la selezione con";
"Parentesi";  // name of ()
"Parentesi graffe";  // name of {}
"Personalizzato…";

**Comment by 1024jp** [comment]
@AgostinoM Thank you!
