### ISSUE TITLE
A potential crash

### ISSUE THREAD

**Issue by DanPristupov** [coteditor/CotEditor#707]
Hi guys.

I just noticed a suspicious piece of code in your source and want to let you know about it.

In `init` of `LineNumberView.swift` you implicitly assign `NSTextView` (which is `scrollview?.documentView`) to `self.clientView`.

```
final class LineNumberView: NSRulerView {
...
    override init(scrollView: NSScrollView?, orientation: NSRulerOrientation) {
        
        super.init(scrollView: scrollView, orientation: orientation)
        
        self.clientView = scrollView?.documentView // <-- here
    }
```

The `clientView` property is defined as **weak** in `NSRulerView`:
```
open class NSRulerView : NSView {
...
    weak open var clientView: NSView?
```

According to Apple docs you cannot assign `NSTextView` to a weak property.

Quote: 
> Which classes don’t support weak references?

> You cannot currently create weak references to instances of the following classes:
> NSATSTypesetter, NSColorSpace, NSFont, NSMenuView, NSParagraphStyle, NSSimpleHorizontalTypesetter, and **NSTextView**.
https://developer.apple.com/library/content/releasenotes/ObjectiveC/RN-TransitioningToARC/Introduction/Introduction.html#//apple_ref/doc/uid/TP40011226

Assigning NSTextView to clientView causes rare random crashes on termination with messages like this:
```objc[43931]: __weak variable at 0x10f9d5db0 holds 0x406625f800000000 instead of 0x610000388470. This is probably incorrect use of objc_storeWeak() and objc_loadWeak(). Break on objc_weak_error to debug.```

You should not assign `textView` to `clientView` property and use a different way to access it instead:

```
final class LineNumberView: NSRulerView {
...
    fileprivate var textView: NSTextView? {
       
        self.scrollView?.documentView as? NSTextView
    }
```

I just wanted to share my experience with this. Please let me know if I'm missing something.

Thank you for the great application.

**Comment by 1024jp** [comment]
Thanks for pointing out.

Regarding to this issue, Apple recently changed NSRulerView's clientView from the regacy `assign` to the modern `weak` on macOS Sierra.
However, NSRulerView's clientView was originally designed for document views, typically for NSTextView (subclass).
So I'm felt strange why Apple made such a change, and then I've just kept it as-is to see hot it goes (I also optimistically guessed that Apple made some undocmented tricks around this).

But as you said, now I suppose it's better to stop using `clientView`.
I'll fix this. Thanks.
