### ISSUE TITLE
CotEditor 3.2.0b2 incompatibility macOS High Sierra.0PB1

### ISSUE THREAD

**Issue by Chamiu** [coteditor/CotEditor#710]
- download CotEditor_3.2.0-beta.2.dmg from https://coteditor.com/beta.
- double click CotEditor_3.2.0-beta.2.dmg. -> mount CotEditor_3.2.0-beta.2.
- open a finder window at diskimage.
- CotEditor.app on One-way mark.
- copy to local storage from diskimage.
- CotEditor.app on One-way mark.

Perhaps not stable macOS High Sierra.0PB1.

**Comment by 1024jp** [comment]
I have not tried High Sierra yet, and also CotEditor 3.2.0 doesn't guarantee working on High Sierra.
However, I'll look into it later.
Thanks 😉

**Comment by Chamiu** [comment]
Add information.

CotEdior 3.2.0b1 work on macOS High Sierra.0pb1, no problem.
CotEdior 3.2.0b1 install before update macOS High Sierra.0pb1.

**Comment by 1024jp** [comment]
I tried reproducing this problem on my High Sierra beta.2 + CotEditor 3.2.0-beta.2 but it worked without any issues.

Yesterday, another High Sierra beta was released. How about on that?
