### ISSUE TITLE
CotEditor should not open a blank document when opening an existing document from the command line.

### ISSUE THREAD

**Issue by kuthair** [coteditor/CotEditor#711]
## Environment

- CotEditor: 3.1.8 (191)
- System: macOS Version 10.12.5 (Build 16F73)
- Language: English

## Short Description

CotEditor should not open a blank document when opening an existing document from the command line.

## Steps to Reproduce the Issue

1. Open CotEditor.
2. Open Preferences.
3. Set the setting to "Open a new document: On launch" to checked.
4. Quit CotEditor.
5. Open Terminal.
6. From a prompt type:  cot <some_file.txt>

## Expected Result

CotEditor opens 2 windows: some_file.txt and also a new document.

It should only open some_file.txt.

**Comment by 1024jp** [comment]
Thanks for your feedback.

You are right. This behavior should be avoided.
However, I suppose, it's actually hard to change this because CotEditor's command line is a bit tricky in order to make it sandboxed.
So, I'll try to find a solution but it may take time.

**Comment by 1024jp** [comment]
I've just updated `cot` command to avoid creating an extra blank document on launch ;-)
This change will be applied to CotEditor.app on the next CotEditor 3.2.1.

**Comment by kuthair** [comment]
Awesome... thanks!
