### ISSUE TITLE
\v doesn't match to vertical tab / 正規表現で \v が認識しない

### ISSUE THREAD

**Issue by ha810** [coteditor/CotEditor#713]
## Environment (環境)

- CotEditor: 3.2.0 (196)
- System: macOS バージョン10.12.6（ビルド16G29）
- Language: Japanese

## Short Description (簡単な説明)

検索と置換ダイアログにて
検索文字に「\v」
置換文字に「\n」
を入力し、すべて置換を実行すると、置換文字欄に「XX件置換しました。」と表示はされますが、置換が実行されないようです。

## Steps to Reproduce the Issue (不具合が発生したときに行っていた操作、または再現手順)

検索・置換

## Expected Result (期待される挙動)
垂直タブを改行に置き換えたい。

**Comment by 1024jp** [comment]
現象が再現されませんでした（私の環境下では正常に置換がされました）。
検索パネルの詳細検索オプションの設定のスクリーンショット（以下参照）と、できれば問題が再現できる垂直タブを含むファイルをいただけますか？
![screen shot 2017-07-28 at 19 13 37](https://user-images.githubusercontent.com/1165044/28713141-def598c2-73c8-11e7-832a-cc3b81a62aeb.png)

**Comment by ha810** [comment]
検索結果は以下のようになります。
サンプル.txtを検索した結果なのですが、垂直タブだけではなく改行もマッチしているような表示でした。

[サンプル.txt](https://github.com/coteditor/CotEditor/files/1182819/default.txt)

![pic](https://user-images.githubusercontent.com/9996418/28714935-bc004102-73d0-11e7-963a-f21c5956c505.jpg)

**Comment by 1024jp** [comment]
サンプルありがとうございます。
おかげさまである程度原因が絞れました。

## 現状の仕様
結論から申し上げますと、残念ですが「仕様です」という回答になります。
CotEditor の内部で使っている Apple の正規表現エンジンは基本的には ICU の正規表現規格に準拠しているのですが、例外的に \v には対応していないようです。

- [NSRegularExpression - Foundation | Apple Developer Documentation](https://developer.apple.com/documentation/foundation/nsregularexpression#main)
    - "Regular Expression Metacharacters" の欄に `\v` に関する記述なし
- [Adventures in lexing | Irregular Impression](http://h2co3.org/blog/index.php/2014/06/01/adventures-in-lexing/)
    - > Apple’s implementation of NSRegularExpression __does not recognize “\v” as an escape sequence for the vertical tab__.

@ha810 さんのおっしゃる通り、`\v` は垂直タブだけでなく改行も認識するので使い物にならなそうです。


## 迂回策
ただ、Apple の正規表現は `\v` は使用できませんが `\u000b` または `\cK` を VERTICAL TABULATION として使用することができます。現状ではこちらをお使いください。

## 対策
この状態が良いとも思わないので、次バージョンまでに以下のどちらかの対策は取る予定です。

1. CotEditor のヘルプなどに `\v` は認識しない旨を記載
2. 正規表現時の検索文字列内の `\v` を内部で `\u000b` に変換して利用

**Comment by ha810** [comment]
検証ありがとうございます。

**Comment by 1024jp** [comment]
以下の対策を講じましたので、3.2.1 からは `\v`も使用できるようになります。

> 2. 正規表現時の検索文字列内の `\v` を内部で `\u000b` に変換して利用

**Comment by ha810** [comment]
承知しました。
