### ISSUE TITLE
Can't set file-drop preferences

### ISSUE THREAD

**Issue by creme-brulee** [coteditor/CotEditor#715]
ファイルドロップの設定ができないようなのですが、そのような報告はあがってませんね。
もしかして自分の環境だけでみなさん問題なく使えてる？

症状：
環境設定＞ファイルドロップの設定＞ファイルドロップ定義：で新規追加・既存の項目のエディットなど行っても、他のタブに切り替えたり設定ウィンドウを閉じると消えてしまう

たとえばキーバインド＞スニペットの設定なら、
~/Library/Containers/com.coteditor.CotEditor/Data/Library/Application Support/CotEditor/
ここにKeyBindingsってフォルダが作られて設定もちゃんと保存できてるし、
それ以外の設定もできてるようなのですが。

osはSierraを数日前にクリーンインストールし直したもので、Time machine の以前の設定はオプションで外したのでインポートされていないはず
CotEditor(3.2)はAppStoreからインストール、その症状発見後アンインストール、サイトにある非Appstoreのものを再度インストール、やはり同じ症状

**Comment by 1024jp** [comment]
症状確認しました。バグです。
現在ちょうど CotEditor 3.2.1 のリリース作業をしていたので、これの修正も加えます。
ありがとうございます。

**Comment by 1024jp** [comment]
この修正を含む CotEditor 3.2.1 を Mac App Store に回したので、Apple のチェックが済み次第リリースされるはずです。

**Comment by creme-brulee** [comment]
対応ありがとうございます

**Comment by creme-brulee** [comment]
対応ありがとうございます
