### ISSUE TITLE
import error about python script via cotEditor

### ISSUE THREAD

**Issue by tadaken3** [coteditor/CotEditor#718]
## Environment (環境)

- CotEditor: 3.2.0 (196)
- System: macOS バージョン10.12.6（ビルド16G29）
- Language: Japanese

## Short Description (簡単な説明)

cotEditor開発者様
いつもありがたく使わせて頂いてます。

一点、教えていただきたいことがあります。

Pythonで作成したスクリプトを実行する際に、サードパーティ製のモジュールをインポートしようとするとエラーが発生してしまいます。デスクトップなどファイルを実行すると動くのですがスクリプトフォルダ(com.coteditor.CotEditor)に置いてcotEditorから実行するとエラーが発生するようです。

Pythonのサードパーティ製のモジュールは対応されていないのでしょうか。

### 環境

- Python 2.7.10
- rerequests 2.8.1

実行しようとしたPythonスクリプトは以下のとおりです。

```python:test_print.py
#!/usr/bin/python
#coding=utf-8
import sys
import requests

print sys.argv[1]
```

発生したエラーコードはこちらです。

```test_print
Traceback (most recent call last):
  File "/Users/username/Library/Application Scripts/com.coteditor.CotEditor/test_print.py", line 4, in <module>
    import requests
ImportError: No module named requests
```

お手数ですが、内容をご確認いただけますと幸いです。

ターミナルから実行した場合は、import errorが発生せず、Pythonのスクリプトが実行されております。また、macのシステムで組み込まれている標準の環境にrequestsをインストールしている状態です。

こちらの環境のせいでしたらすみません。

## Expected Result (期待される挙動)

サードパーティ製のモジュールも使えるようにしていただけると助かります。

**Comment by 1024jp** [comment]
Python のパスに関する問題だと思うのですが、

1行目の shebang を
```
#!/usr/bin/python
```
でなく
```
#!/usr/bin/env python
```
にしてみた時に問題が解決するかに興味があります。

**Comment by tadaken3** [comment]
コメントありがとうございます。
こちらで２点試してみたのですが、うまくいきませんでした。

①shebangを変更しても同じエラーでした。
②pyenvでcom.coteditor.CotEditorの配下を別のバージョンPythonに変更して同様のエラーが発生しております。

例えば以下の環境です。
~~~
$ pynev local anaconda3-4.1.0
$ python -- version 
Python 3.5.1  :: Anaconda custom (x86_64)
~~~

**Comment by 1024jp** [comment]
状況報告ありがとうございます。
時間を見つけて検証します。

**Comment by tadaken3** [comment]
早々にコメントいただきましてありがとうございます。
こちらでもいろいろ試してみて、何かわかりましたら、ご連絡させていただきます！

**Comment by tadaken3** [comment]
すみません。自己解決しました。
shebangを以下に変更したら、きちんと動作します。

~~~
#!/usr/local/bin/python
~~~

homebrewでPythonを入れていたため、Pythonのパスが/usr/local/bin/pythonになってしまっていたようです。お騒がせ致しました。

**Comment by 1024jp** [comment]
それは良かったです。
解決手段の提供ありがとうございます。
このチケットは閉じます。

**Comment by tadaken3** [comment]
お騒がせしました、、、

今後の方のために詳しい状況を記載しておきます。
PythonのVersion管理をするために、HomebrewでPython、pyenvを入れています。
PATHは以下の優先順位で設定しています。
~~~
$ echo $PATH | tr ':' '\n'
/Users/username/.pyenv/shims
/Users/username/.pyenv/bin
/usr/local/bin
/usr/local/sbin
/Users/username/bin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
~~~

PATHの優先度的にpyenvで管理されているPythonが実行されてると思ったのですが、
そうではないのですね。勉強になりました。
