### ISSUE TITLE
Failed large number of replacement / 大量件数の置換ができない

### ISSUE THREAD

**Issue by nanako1212** [coteditor/CotEditor#720]
## Environment (環境)

- CotEditor: 3.2.1 (201)
- System: macOS バージョン10.12.6（ビルド16G29）
- Language: Japanese

## Short Description (簡単な説明)

アップデートをしたところ、大量件数の置換ができなくなりました。

## Steps to Reproduce the Issue (不具合が発生したときに行っていた操作、または再現手順)

8/31にAppのAppStoreを通してアップデートをしたところ、大量件数の置換ができなくなりました。
すみませんが、アップデート前のバージョンは不明です。

6500行ほどのファイルのタブ（10万件ほど）正規表現\tで指定し、カンマに置換する操作を行ないました。進捗バーが表示され、件数がカウントされて正常に処理されるように見えますが、完了にならず、置換もできないままです。

## Expected Result (期待される挙動)

アップデート前には全く同じ行数、検索対象件数の置換ができていましたので、以前の挙動に戻して欲しいです。

**Comment by 1024jp** [comment]
不具合報告ありがとうございます。
現象が手元で再現され次第対応をします。しばしお待ちください。

**Comment by 1024jp** [comment]
本件、手元の開発環境で再現ができません。
以下の条件が知りたいので、お答えいただけますでしょうか：

- 本件は必ず発生するか（100%, 半分くらいの割合、など）。
- 処理に時間がかかっているだけの可能性も考えられます。試しに置換後30分くらい放置してみて状況を教えてください。
- 本不具合が発生するファイルをいただけますと検証に助かります

**Comment by 1024jp** [comment]
手元で検証した限りでは、現状の CotEditor の置換の進捗通知のバランスが悪く、後処理で時間がかかる割には進捗表示の更新が一切ないため、フリーズしているように見える可能性があります。
これについては、進捗更新のタイミングを改めようかと思います。

それ以外で明らかに置換ができないようであれば別途対処します。

**Comment by nanako1212** [comment]
おっしゃる通り、18万件の置換でフリーズ（しているように見える）後も放置したところ、置換は完了していました。
進捗通知上完了しているように見えるだけで、処理を行っているということですね。
承知しました。ご対応ありがとうございます。

ちなみに、この状態（進捗バーが右まで進み、キャンセル押下可能な状態）でキャンセルボタンを押下すると、置換処理の進捗ボックスは消えますが、それ以降検索・置換ができなくなります。これもキャンセル処理が完了していないということでしょうか？

**Comment by 1024jp** [comment]
検証ありがとうございます。

> ちなみに、この状態（進捗バーが右まで進み、キャンセル押下可能な状態）でキャンセルボタンを押下すると、置換処理の進捗ボックスは消えますが、それ以降検索・置換ができなくなります。これもキャンセル処理が完了していないということでしょうか？

これについてもそのご理解であっております。
ただ、置換計算はそのまま引き続き行われてしまうのですが、キャンセル自体は効いており、置換自体は書類には反映されません。おそらく処理が終了した後は再び編集可能に戻ると思います。

キャンセルボタンも含め本件について修正を入れましたので、近日（来週中？）リリース予定の CotEditor 3.2.2 にて修正が反映されます。
それまでご不便おかけしますがしばらくご辛抱ください。
