### ISSUE TITLE
Indenting wrapped lines fails to update when first line changes indent.

### ISSUE THREAD

**Issue by jeffmikels** [coteditor/CotEditor#721]
## Environment

- CotEditor: 3.2.1 (201)
- System: macOS Version 10.11.6 (Build 15G1611)
- Language: English

## Short Description

Indenting wrapped lines fails to update when first line changes indent.

## Steps to Reproduce the Issue

1. Turn on “Soft Wrap Lines” & turn on “Indent Wrapped Lines” with any value.
2. Create a new document
3. Type enough text to cause a soft line wrap & notice that subsequent lines are indented.
4. Go to the beginning of the line and type CMD+] & notice that the whole block gets indented more.
5. Go to the beginning of the line and type BACKSPACE / DEL & notice that only the first line is changed. **The remainder of the text block should change indent as well.**
6. Using CMD+[ and CMD+] to change indent levels works as expected.

## Expected Result

1. Typing or deleting a tab at the beginning of a line should have the same effect as CMD+[ & CMD+].
2. When the indent of the first line changes, the indent of the subsequent wrapped lines should also change.

**Comment by 1024jp** [comment]
Thanks for the report, and sorry for my late reply.
This issue will be fixed in the next CotEditor 3.2.2 as I've fixed it on f762d1eb5a7b752c6350e426d5153daf81f8df9e.
