### ISSUE TITLE
support for markdown preview

### ISSUE THREAD

**Issue by harlentan** [coteditor/CotEditor#722]
Hi, 

cotEdit has a great help for my work.

How about supportting for markdown preview?

**Comment by 1024jp** [comment]
I'd like to keep CotEditor as a general plain-text editor.
Therefore, for me, the motivation to add features for a specific language is very low. 
It is actually due to the limited development resource.
So, at this time point, I have no plan to support Markdown preview. Sorry.

IMPO, [Marked (2)](http://marked2app.com) is a good markdown previewer suitable to use beside CotEditor.

**Comment by peteog** [comment]
I was able to build a Markdown preview using the awesome script support:

after `brew install cmark`

```

**Comment by 1024jp** [comment]
I close this issue since I do not have any plan to implement this kind of features in the future.

**Comment by Chamiu** [comment]
> I was able to build a Markdown preview using the awesome script support:
> 
> after `brew install cmark`, I made a script: `~/Library/Application Scripts/com.coteditor.CotEditor/Markdown Preview.@M.sh`
> 
> ```
> #!/bin/bash
> #%%%{CotEditorXInput=AllText}%%%
> #%%%{CotEditorXOutput=None}%%%
> 
> INPUT=$(/usr/local/bin/cmark)
> HTML="<html><style>body { font-family: -apple-system; }</style><body>$INPUT</body></html>"
> OUTPUT=$(echo "$HTML" | base64 | cat <(echo -n "data:text/html;charset=UTF-8;base64,") -)
> osascript -e "tell application \"Safari\" to open location \""$OUTPUT"\""
> ```
> 
> I can then press: ⇧⌘M to see the result in Safari:
> 
> ![screen shot 2018-01-18 at 09 09 56](https://user-images.githubusercontent.com/37008/35089702-a38df154-fc2f-11e7-994b-35a02d7b1fee.png)
> 
> https://github.com/peteog/CotEditorScripts/blob/master/Markdown%20Preview.%40M.sh

I try macOS Big Sur.1 on MacBook Air Late 2020 (Apple M1).
Only two different things have, **but this tips is able to use macOS Big Sur.1 on MacBook Air Late 2020 (Apple M1)**.

One, brew install cmark -> brew install --build-from-source cmark
Because cmark not release Apple M1 version. 

Two, script 5 line "/usr/local/" -> "/opt/HomeBrew/"
Because HomeBrew change to use directory at macOS Big Sur version,

One more thing.
Marked 2.6.2(Intel) through Rosetta 2 is not need. and this ***CRASH CRASH CRASH*** on macOS Big Sur.1 on Apple M1.

**Comment by YUX** [comment]
> > I was able to build a Markdown preview using the awesome script support:
> > after `brew install cmark`, I made a script: `~/Library/Application Scripts/com.coteditor.CotEditor/Markdown Preview.@M.sh`
> > ```
> > #!/bin/bash
> > #%%%{CotEditorXInput=AllText}%%%
> > #%%%{CotEditorXOutput=None}%%%
> > 
> > INPUT=$(/usr/local/bin/cmark)
> > HTML="<html><style>body { font-family: -apple-system; }</style><body>$INPUT</body></html>"
> > OUTPUT=$(echo "$HTML" | base64 | cat <(echo -n "data:text/html;charset=UTF-8;base64,") -)
> > osascript -e "tell application \"Safari\" to open location \""$OUTPUT"\""
> > ```
> > 
> > 
> > I can then press: ⇧⌘M to see the result in Safari:
> > ![screen shot 2018-01-18 at 09 09 56](https://user-images.githubusercontent.com/37008/35089702-a38df154-fc2f-11e7-994b-35a02d7b1fee.png)
> > https://github.com/peteog/CotEditorScripts/blob/master/Markdown%20Preview.%40M.sh
> 
> I try macOS Big Sur.1 on MacBook Air Late 2020 (Apple M1).
> Only two different things have, **but this tips is able to use macOS Big Sur.1 on MacBook Air Late 2020 (Apple M1)**.
> 
> One, brew install cmark -> brew install --build-from-source cmark
> Because cmark not release Apple M1 version.
> 
> Two, script 5 line "/usr/local/" -> "/opt/HomeBrew/"
> Because HomeBrew change to use directory at macOS Big Sur version,
> 
> One more thing.
> Marked 2.6.2(Intel) through Rosetta 2 is not need. and this _**CRASH CRASH CRASH**_ on macOS Big Sur.1 on Apple M1.


and do not forget to run this line in the terminal.
`chmod u+x ~/Library/Application Scripts/com.coteditor.CotEditor/Markdown Preview.@M.sh`

**Comment by montrealist** [comment]
Updated the last line to make Safari jump to the foreground:

```
osascript -e "tell application \"Safari\" to open location \""$OUTPUT"\"" -e "tell application \"Safari\" to activate"
```

**Comment by kra-mo** [comment]
To support embedded images, videos, you can try something like this:

```bash
#!/bin/bash
#%%%{CotEditorXInput=AllText}%%%

TMPFILE="`mktemp -d`/index.html"

echo "
<!doctype html>
<html lang='en'>
  <head>
    <base href='file://`dirname $1`/index.html' />
    <title>`basename $1 .md`</title>
    <style>
      body {
        width: 50em;
        max-width: 90%;
        margin: 2em auto;
        color: rgb(0 0 0 / 80%);
        font-family: system-ui;
      }

      a {
        color: inherit;
      }

      img,
      video {
        max-width: 100%;
      }

      @media (prefers-color-scheme: dark) {
        body {
          color: white;
          background: #1e1e1e;
        }
      }
    </style>
  </head>
  <body>
    `/opt/homebrew/bin/cmark --unsafe`
  </body>
</html>
" > "$TMPFILE"

osascript -e "tell application \"Safari\" to open location \"file://$TMPFILE\""
osascript -e "tell application \"Safari\" to activate"
```

**Comment by NayamAmarshe** [comment]
I've posted a guide for this in the Discussions tab: https://github.com/coteditor/CotEditor/discussions/2112
