### ISSUE TITLE
Project Side bar if this is possible 

### ISSUE THREAD

**Issue by msdocs** [coteditor/CotEditor#723]
I have been using sublime for a while and I was looking for a FOSS alternative for mac. I would use coteditor more if it integrated the project folder sidebar like sublime . Thanks

**Comment by 1024jp** [comment]
Currently, I don't have a plan to implement project management things. Sorry.

The reasons are followings:

1. I wanna keep CotEditor simple.
1. I have less interest in it. 
1. I don't have time to implement and manage it.

As it's actually a duplicate issue, I'll close this one.
cf. #278

**Comment by wuehrer** [comment]
Hello, many thanks for the development of the CotEditor. 

I would like to pick up the topic Folder/Project again. 

From earlier times I use the editors BBEdit or Sublime for larger HTML or Python developments. But also for Markdown diaries or documentations.

Where the project view on the files and working with files - for example fast search - are the most important differences. 

Is such a function folder/project still not in focus?

I'd like to say goodbye to my "old" editors and not switch to Atom.io or anything like that - I just want native mac os apps. 

Greetings from Austria!
