### ISSUE TITLE
一部のフォントで現在の行のハイライトがはみ出る

### ISSUE THREAD

**Issue by Dolgorbie** [coteditor/CotEditor#724]
一部のフォントにおいて，現在の行のハイライトが上下にはみでます．
<img width="860" alt="samp" src="https://user-images.githubusercontent.com/16800764/30634516-554e6dba-9e2a-11e7-8bdb-e43117134547.png">
<img width="857" alt="samp2" src="https://user-images.githubusercontent.com/16800764/30634565-84322388-9e2a-11e7-8676-ab5dfc59d34e.png">

**Comment by 1024jp** [comment]
CotEditor と macOS のバージョンを教えていただけますか？
心当たりはあるので、次のマイナーアップデートで修正できるかと思います。

**Comment by Dolgorbie** [comment]
CotEditor 3.2.1
macOS 10.12.6
です．

**Comment by 1024jp** [comment]
ありがとうございます。
修正しましたので次のバージョンで反映されます。
