### ISSUE TITLE
Sometimes, freeze when the edited text is tried to save on 3.2.1

### ISSUE THREAD

**Issue by mikanbako** [coteditor/CotEditor#725]
Sometimes, CotEditor 3.2.1 freezes when the edited text is tried to save by Command+S. The file menu is highlighted while freezing. The file is not saved.

The following is a system report about this issue.

--------------------------------------------------

Date/Time:       2017-09-21 09:27:04 +0900
OS Version:      Mac OS X 10.12.6 (Build 16G29)
Architecture:    x86_64
Report Version:  25

Data Source:     Stackshots

Command:         CotEditor
Path:            /Applications/CotEditor.app/Contents/MacOS/CotEditor
Version:         3.2.1 (201)
App Item ID:     1024640650
App External ID: 823295009
Parent:          launchd [1]
PID:             30576

Event:           hang
Duration:        2.89s (process was unresponsive for 264 seconds before sampling)
Steps:           29 (100ms sampling interval)

Hardware model:  MacBookPro8,2
Active cpus:     8

Fan speed:       1999 rpm

Heaviest stack for the main thread of the target process:
  29  start + 1 (libdyld.dylib + 21045) [0x7fffe45bf235]
  29  ??? (CotEditor + 29017) [0x10fcde159]
  29  NSApplicationMain + 1237 (AppKit + 24078) [0x7fffcc4abe0e]
  29  -[NSApplication run] + 1002 (AppKit + 242727) [0x7fffcc4e1427]
  29  -[NSApplication(NSEvent) sendEvent:] + 3377 (AppKit + 8130361) [0x7fffccc66f39]
  29  routeKeyEquivalent + 1024 (AppKit + 8139548) [0x7fffccc6931c]
  29  -[NSMenu performKeyEquivalent:] + 367 (AppKit + 2712037) [0x7fffcc73c1e5]
  29  _os_activity_initiate_impl + 53 (libsystem_trace.dylib + 13223) [0x7fffe47f13a7]
  29  -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 114 (AppKit + 2716626) [0x7fffcc73d3d2]
  29  -[NSMenuItem _corePerformAction] + 324 (AppKit + 2717286) [0x7fffcc73d666]
  29  -[NSApplication(NSResponder) sendAction:to:from:] + 456 (AppKit + 8144673) [0x7fffccc6a721]
  29  _os_activity_initiate_impl + 53 (libsystem_trace.dylib + 13223) [0x7fffe47f13a7]
  29  ??? (CotEditor + 984264) [0x10fdc74c8]
  29  ??? (CotEditor + 982937) [0x10fdc6f99]
  29  -[NSDocument(NSDocumentSaving) _saveDocumentWithDelegate:didSaveSelector:contextInfo:] + 93 (AppKit + 12061585) [0x7fffcd026b91]
  29  -[NSDocument(NSDocumentSerializationAPIs) performActivityWithSynchronousWaiting:usingBlock:cancellationHandler:] + 447 (AppKit + 6415081) [0x7fffccac42e9]
  29  -[NSDocument(NSDocumentSerializationAPIs) _performActivity:] + 1488 (AppKit + 6409213) [0x7fffccac2bfd]
  29  _dispatch_semaphore_wait_slow + 103 (libdispatch.dylib + 43153) [0x7fffe4592891]
  29  semaphore_wait_trap + 10 (libsystem_kernel.dylib + 74630) [0x7fffe46e6386]
 *29  semaphore_wait_continue + 0 (kernel + 1106960) [0xffffff800030e410]

Process:         CotEditor [30576]
Path:            /Applications/CotEditor.app/Contents/MacOS/CotEditor
Architecture:    x86_64
Parent:          launchd [1]
UID:             502
Task size:       51.13 MB (-12 KB)
CPU Time:        <0.001
Note:            Unresponsive for 264 seconds before sampling
Note:            2 idle work queue threads omitted

  Thread 0x825e6            DispatchQueue 1           29 samples (1-29)         priority 46 (base 46)
  <thread QoS user interactive (requested user interactive), process unclamped, process received importance donation from WindowServer [181], process received importance donation from filecoordinationd [411], IO tier 0>
  29  start + 1 (libdyld.dylib + 21045) [0x7fffe45bf235] 1-29
    29  ??? (CotEditor + 29017) [0x10fcde159] 1-29
      29  NSApplicationMain + 1237 (AppKit + 24078) [0x7fffcc4abe0e] 1-29
        29  -[NSApplication run] + 1002 (AppKit + 242727) [0x7fffcc4e1427] 1-29
          29  -[NSApplication(NSEvent) sendEvent:] + 3377 (AppKit + 8130361) [0x7fffccc66f39] 1-29
            29  routeKeyEquivalent + 1024 (AppKit + 8139548) [0x7fffccc6931c] 1-29
              29  -[NSMenu performKeyEquivalent:] + 367 (AppKit + 2712037) [0x7fffcc73c1e5] 1-29
                29  _os_activity_initiate_impl + 53 (libsystem_trace.dylib + 13223) [0x7fffe47f13a7] 1-29
                  29  -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 114 (AppKit + 2716626) [0x7fffcc73d3d2] 1-29
                    29  -[NSMenuItem _corePerformAction] + 324 (AppKit + 2717286) [0x7fffcc73d666] 1-29
                      29  -[NSApplication(NSResponder) sendAction:to:from:] + 456 (AppKit + 8144673) [0x7fffccc6a721] 1-29
                        29  _os_activity_initiate_impl + 53 (libsystem_trace.dylib + 13223) [0x7fffe47f13a7] 1-29
                          29  ??? (CotEditor + 984264) [0x10fdc74c8] 1-29
                            29  ??? (CotEditor + 982937) [0x10fdc6f99] 1-29
                              29  -[NSDocument(NSDocumentSaving) _saveDocumentWithDelegate:didSaveSelector:contextInfo:] + 93 (AppKit + 12061585) [0x7fffcd026b91] 1-29
                                29  -[NSDocument(NSDocumentSerializationAPIs) performActivityWithSynchronousWaiting:usingBlock:cancellationHandler:] + 447 (AppKit + 6415081) [0x7fffccac42e9] 1-29
                                  29  -[NSDocument(NSDocumentSerializationAPIs) _performActivity:] + 1488 (AppKit + 6409213) [0x7fffccac2bfd] 1-29
                                    29  _dispatch_semaphore_wait_slow + 103 (libdispatch.dylib + 43153) [0x7fffe4592891] 1-29
                                      29  semaphore_wait_trap + 10 (libsystem_kernel.dylib + 74630) [0x7fffe46e6386] 1-29
                                       *29  semaphore_wait_continue + 0 (kernel + 1106960) [0xffffff800030e410] 1-29

  Thread 0x8268a            Thread name "com.apple.NSEventThread"               29 samples (1-29)         priority 46 (base 46)
  <thread QoS user interactive (requested user interactive), process unclamped, process received importance donation from WindowServer [181], process received importance donation from filecoordinationd [411], IO tier 0>
  29  thread_start + 13 (libsystem_pthread.dylib + 12429) [0x7fffe47d808d] 1-29
    29  _pthread_start + 286 (libsystem_pthread.dylib + 14471) [0x7fffe47d8887] 1-29
      29  _pthread_body + 180 (libsystem_pthread.dylib + 14651) [0x7fffe47d893b] 1-29
        29  _NSEventThread + 205 (AppKit + 1654530) [0x7fffcc639f02] 1-29
          29  CFRunLoopRunSpecific + 420 (CoreFoundation + 542020) [0x7fffce9f4544] 1-29
            29  __CFRunLoopRun + 1361 (CoreFoundation + 543985) [0x7fffce9f4cf1] 1-29
              29  __CFRunLoopServiceMachPort + 212 (CoreFoundation + 546932) [0x7fffce9f5874] 1-29
                29  mach_msg_trap + 10 (libsystem_kernel.dylib + 74570) [0x7fffe46e634a] 1-29
                 *29  ipc_mqueue_receive_continue + 0 (kernel + 850128) [0xffffff80002cf8d0] 1-29

  Binary Images:
           0x10fcd7000 -        0x10ff0ffff  com.coteditor.CotEditor 3.2.1 (201)   <A05F0194-A9D5-3B63-A5F4-1B2F72764245>  /Applications/CotEditor.app/Contents/MacOS/CotEditor
        0x7fffcc4a6000 -     0x7fffcd27ffff  com.apple.AppKit 6.9 (1504.83.101)    <AE51ACB3-D501-3F91-B369-3D3711F24D0A>  /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
        0x7fffce970000 -     0x7fffcee03fff  com.apple.CoreFoundation 6.9 (1349.8) <36385A3A-60D3-32DB-BF55-C6D8931A7AA6>  /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
        0x7fffe4588000 -     0x7fffe45b9fff  libdispatch.dylib (703.50.37)         <6582BAD6-ED27-3B30-B620-90B1C5A4AE3C>  /usr/lib/system/libdispatch.dylib
        0x7fffe45ba000 -     0x7fffe45bffff  libdyld.dylib (433.5)                 <9B2AC56D-107C-3541-A127-9094A751F2C9>  /usr/lib/system/libdyld.dylib
        0x7fffe46d4000 -     0x7fffe46f6fff  libsystem_kernel.dylib (3789.70.16)   <34B1F16C-BC9C-3C5F-9045-0CAE91CB5914>  /usr/lib/system/libsystem_kernel.dylib
        0x7fffe47d5000 -     0x7fffe47dffff  libsystem_pthread.dylib (218.60.3)    <B8FB5E20-3295-39E2-B5EB-B464D1D4B104>  /usr/lib/system/libsystem_pthread.dylib
        0x7fffe47ee000 -     0x7fffe4801fff  libsystem_trace.dylib (518.70.1)      <AC63A7FE-50D9-3A30-96E6-F6B7FF16E465>  /usr/lib/system/libsystem_trace.dylib
   *0xffffff8000200000 - 0xffffff80009fffff  kernel (3789.70.16)                   <D3314D98-5D40-3CD8-98A4-F1DD46C20E03>  /System/Library/Kernels/kernel

**Comment by 1024jp** [comment]
Thanks for the report and sorry for the bug.
I close this issue as it was already registered at #663.
However, crash reports are always welcome.

I really wanna fix this long-standing issue... (but can't so far).
