### ISSUE TITLE
Update localizations

### ISSUE THREAD

**Issue by 1024jp** [coteditor/CotEditor#726]
Hi, I've just added a string to be localized to CotEditor.
Could you guys, @onevcat and @AgostinoM, translate the following line in Localizable.strings?
The line will be used in the progress indicator of the Replace All action.

```c
"Searching in text…" = "Searching in text…"; // FIXME: added
```

**Comment by onevcat** [comment]
Hi, may I just provide the entry here, since I cannot reach computer for a while.

Searching in text… 

正在文本中搜索...

**Comment by 1024jp** [comment]
@onevcat Wow, so fast. Thanks!

**Comment by AgostinoM** [comment]
Hello,

here you go:



> "Searching in text…" = "Ricerca nel testo…"; // FIXME: added
>
>

**Comment by 1024jp** [comment]
@AgostinoM Thanks also! ☕️
