### ISSUE TITLE
UserDefaults this operation will be reported wrong

### ISSUE THREAD

**Issue by DivenLee** [coteditor/CotEditor#728]
Because I was testing the cotangent, I stumbled upon this problem, and the other applications didn't, but the cotangent was able to reproduce.

10.13 + xcode9

1. I completely delete this directory in Finder
/Users/xxxxxxxxxxxx/Library/Containers/com.coteditor.CotEditor

2. I also clear all the files in the recycle bin

3. debug items in xcode9

4. error occurred and cannot be repaired

> 2017-09-28 22:25:50.149252+0800 CotEditor[6883:217644] [User Defaults] Couldn't read values in CFPrefsPlistSource<0x6000000e0e00> (Domain: com.coteditor.CotEditor, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: Yes): accessing preferences outside an application's container requires user-preference-read or file-read-data sandbox access, detaching from cfprefsd
> 2017-09-28 22:25:50.363981+0800 CotEditor[6883:217644] [User Defaults] attempt to set (
> ) for key in recentStyleNames in non-persistent preferences domain CFPrefsPlistSource<0x6000000e0e00> (Domain: com.coteditor.CotEditor, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: Yes)
> 2017-09-28 22:25:50.476068+0800 CotEditor[6883:217644] [User Defaults] attempt to set 86400 for key in SUScheduledCheckInterval in non-persistent preferences domain CFPrefsPlistSource<0x6000000e0e00> (Domain: com.coteditor.CotEditor, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: Yes)
> 2017-09-28 22:25:50.810016+0800 CotEditor[6883:217644] [User Defaults] attempt to set (
>     "Plain Text"
> ) for key in recentStyleNames in non-persistent preferences domain CFPrefsPlistSource<0x6000000e0e00> (Domain: com.coteditor.CotEditor, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: Yes)
> 2017-09-28 22:25:50.922263+0800 CotEditor[6883:217644] [User Defaults] attempt to set {
>     "TB Display Mode" = 1;
>     "TB Icon Size Mode" = 1;
>     "TB Is Shown" = 1;
>     "TB Size Mode" = 1;
> } for key in NSToolbar Configuration docWindowToolbarID in non-persistent preferences domain CFPrefsPlistSource<0x6000000e0e00> (Domain: com.coteditor.CotEditor, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: Yes)
> 2017-09-28 22:25:50.933511+0800 CotEditor[6883:217644] [User Defaults] attempt to set 390 128 600 642 0 0 1280 777  for key in NSWindow Frame document in non-persistent preferences domain CFPrefsPlistSource<0x6000000e0e00> (Domain: com.coteditor.CotEditor, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: Yes)
> 2017-09-28 22:25:51.142244+0800 CotEditor[6883:217644] [User Defaults] attempt to set 1 for key in SUHasLaunchedBefore in non-persistent preferences domain CFPrefsPlistSource<0x6000000e0e00> (Domain: com.coteditor.CotEditor, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: Yes)
> 2017-09-28 22:25:51.179377+0800 CotEditor[6883:217644] MessageTracer: load_domain_whitelist_search_tree:73: Search tree file's format version number (0) is not supported
> 2017-09-28 22:25:51.179422+0800 CotEditor[6883:217644] MessageTracer: Falling back to default whitelist
> 2017-09-28 22:25:51.207184+0800 CotEditor[6883:217644] [User Defaults] attempt to set (
>     "0.000000, 0.000000, 600.000000, 620.000000, NO, NO",
>     "0.000000, 0.000000, 0.000000, 0.000000, YES, NO"
> ) for key in NSSplitView Subview Frames windowContentSplitView in non-persistent preferences domain CFPrefsPlistSource<0x6000000e0e00> (Domain: com.coteditor.CotEditor, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: Yes)

5., this is the only way to use it properly.
Method 1: killall -SIGTERM cfprefsd
Method 2: restart mac

I think the reason is that the UserDefaults configuration file is missing and there is no way to recreate it. But I want to find out why it happened and try to fix it. I created a new project to use UserDefaults, which should be created automatically, without this problem.
If you have the answer, please let me know

**Comment by 1024jp** [comment]
But why did you delete `/Users/xxxxxxxxxxxx/Library/Containers/com.coteditor.CotEditor` directory?
The UserDefaults configuration file is created in this folder.

**Comment by DivenLee** [comment]
I delete this directory, and this is a test. What I don't understand is why other applications recreate the directory, and Cot does not.

**Comment by 1024jp** [comment]
I guess this issue is related to #729.
So, I'd gather to #729.
