### ISSUE TITLE
「次のディスクイメージは開けませんでした」（CotEditor_3.2.2.dmg）

### ISSUE THREAD

**Issue by kkdd** [coteditor/CotEditor#730]
「次のディスクイメージは開けませんでした」というエラーメッセージが出ます：
「CotEditor_3.2.2.dmg  マウントできるファイルシステムがありません」

**Comment by 1024jp** [comment]
手元の環境では正常にマウントできます。
もう一度ダウンロードし直してみて、それでもダメならば
macOS のバージョンを教えていただけますか？

**Comment by kkdd** [comment]
こんにちは。
macOS 10.11.6 です。
https://github.com/coteditor/CotEditor/releases/download/3.2.2/CotEditor_3.2.2.dmg はマウントで異常となり、
https://github.com/coteditor/CotEditor/releases/download/3.2.1/CotEditor_3.2.1.dmg は正常にマウントできます。

**Comment by motooka** [comment]
手元の Sierra (10.12.6) マシンで 3.2.2 のdmgをマウントしたところ、マウントできました。

ディスクユーティリティで確認したところ、 `ファイルシステム: APFS（大文字/小文字を区別）` となっていたので、Sierraよりも古いOSだとマウントできないのかもしれません。
（SierraのAPFSサポートは実験的な実装と言われてたような気もしますが…）

**Comment by christopheranderton** [comment]
Same issue here. Also fails via Homebrew Cask (`brew cask install coteditor`)
- _macOS 10.11.6 El Capitan_  
- HFS+ Journaled case-insensitive (Default)
 

**”No Mountable Filesystems”:**
https://github.com/coteditor/CotEditor/releases/download/3.2.2/CotEditor_3.2.2.dmg

**Works:**
https://github.com/coteditor/CotEditor/releases/download/3.2.1/CotEditor_3.2.1.dmg

**Comment by 1024jp** [comment]
Oh, I see. I may need to create the DMG again. Please be patient a while.

**Comment by kkdd** [comment]
additional information:
```
$ echo CotEditor_3.2.{1..2}.dmg | xargs -n 1 hdiutil imageinfo | ggrep -oP '(?<=disk image \(Apple_).[A-Z]*(?=\s)'
HFS
APFS
```

**Comment by 1024jp** [comment]
Sorry for my late. I've just made a new DMG file.
I'd like to ask you guys, can you open this one on macOS 10.12 (or lower)?
If yes, this is the correct fixed version (the content is the same as the last one).
If no, I'll try another solution.

https://github.com/coteditor/CotEditor/releases/download/3.2.2/CotEditor_3.2.2.dmg

--- 

遅くなりましたが、新たに DMG ファイルを作成しました。
手元に古いこれで大丈夫か試していただけますか？
もし大丈夫であれば、これが正式なバージョンとなります（中身は以前の CotEditor_3.2.2.dmg と同一です）。
ダメなようであれば、別の方法を試します。

**Comment by kkdd** [comment]
updated information:
```
$ echo CotEditor_3.2.{1..2}.dmg | xargs -n 1 hdiutil imageinfo | ggrep -oP '(?<=disk image \(Apple_).[A-Z]*(?=\s)'
HFS
HFS
```

**Comment by 1024jp** [comment]
@kkdd 開けましたか？

**Comment by kkdd** [comment]
Updated CotEditor_3.2.2.dmg, as well as CotEditor 3.2.2 itself, works well on my environment, macOS 10.11.6. Thank you.

**Comment by 1024jp** [comment]
@kkdd Thanks for the reply.
Then, I’d close this issue.
