### ISSUE TITLE
[Request] Unlock/Sudo when needed upon editing.

### ISSUE THREAD

**Issue by christopheranderton** [coteditor/CotEditor#731]
In TextWrangler/BBEdit, when you open a document, let's say your `hosts` file (`/etc/hosts`), and starts to edit the contents, you will be presented with a alert dialog prompting if you want to unlock the file (see screenshot). 

It's the only feature i'm missing in CotEditor. 

<img width="880" alt="screenshot 2017-10-04 at 20 48 48" src="https://user-images.githubusercontent.com/1305802/31193912-beddeac8-a945-11e7-9c32-eafc808a9bcc.png">

**Comment by 1024jp** [comment]
This feature was previously implemented to CotEditor; however, we removed it when we sandboxed the app, as there is no way to write to a file that the user isn't permitted. 
So, sorry, but we can't provide this feature anymore.

cf. http://coteditor.com/news/2015/CotEditor_2.2.0
