### ISSUE TITLE
To be able to enter snippet from TouchBar

### ISSUE THREAD

**Issue by tamasan238** [coteditor/CotEditor#734]
I think if we can enter preregistered snippets from TouchBar with a feeling like a Safari bookmark is good.
Don't you think so?

**Comment by 1024jp** [comment]
Thank you for the feedback.
I’ll consider.

**Comment by 1024jp** [comment]
Although this request is still a (relatively) high-priority task in my implementation queue, I drop it from CotEditor 3.3.0.
Because I really feel that the snippet feature of CotEditor needs a fundamental reconstruction.
Without that, snippet insertion from the Touch Bar becomes messy.

**Comment by 1024jp** [comment]
Because Apple seems to discontinue Touch Bar, I give up implementing this feature, although I have already implemented it halfway.
