### ISSUE TITLE
Open second file in new tab instead of new window

### ISSUE THREAD

**Issue by uschmelzer** [coteditor/CotEditor#737]
Hi, 
this is a feature request, thanks for reading:

__Situation__
- CotEditor is open with one text file.
- Now I go to the finder and doubleclick on a second text file to open it

__Current behaviour of CotEditor__
- The second text file is opened in a new CotEditor window
- I have two CotEditor windows now
- It's hard to switch between the two windows
- Would be easier if both files were in tabs in one window.

__Desired behaviour of CotEditor/feature request__
- The second text file is opened in a new tab in the same window.
- Now, I can easily switch between the two files

Cheers
Uwe

P.S.: Thx for creating CotEditor. I use it every day, besides my phpstorm.

**Comment by uschmelzer** [comment]
Found the solution myself:

__Old Setting:__
- Settings > Windows > Prefer Tabs > Automatic

__New Setting:__
- Settings > Windows > Prefer Tabs > Always

Cheers
Uwe

**Comment by mrichman** [comment]
I came looking for this today and stupidly assumed "Prefer Tabs" meant "Prefer Tabs over Spaces" :) Perhaps the UI should read Settings > Windows > Open Files in Tabs (or something) > Always ?

**Comment by 1024jp** [comment]
@mrichman Thank you for the feedback.
I followed the expression used by Apple at the time.
However, as you pointed out, I also think it is not clear.
So, I'll improve it in the next version.
(Maybe, “Prefer tabs when opening documents” or “Open documents in Tabs”)

https://applelocalization.com/macos?q=Prefer+tabs

**Comment by mrichman** [comment]
I like "Open documents in Tabs" as "Prefer..." might imply that sometimes they won't open in tabs.
