### ISSUE TITLE
"Show invisible Characters" option in Preferences is confusing

### ISSUE THREAD

**Issue by fiery-** [coteditor/CotEditor#740]
First, thank you for the great editor. I noticed two very small issues:

1. It seems that "Show invisible Characters" option in Preferences actually is not showing anything. I just can't understand what's the purpose of this option here, not to mention that it's very confusing to turn it on and see no Invisibles. The command that shows/hides Invisibles is "Show invisible Characters" command at Format menu or Toolbar (which is fine). I don't see why you want to use that option in Preferences.

2. Please, shorten the "Incompatible Characters" Toolbar button to "Incompatibles" or "Incomp.". It takes too much space on the Toolbar.
![CotEditor Prefs](https://user-images.githubusercontent.com/4441889/31952880-55116a2a-b8ea-11e7-9751-ee4195ff7766.png)

**Comment by 1024jp** [comment]
1. The setting in the Preferences is the default setting for all windows. On the other hand, the "Show invisible Characters" in the toolbars and the Format menu is for an individual window. Therefore, the purpose is different.
2. I agree with you. I shortened the toolbar item label to "Incompatibles".
