### ISSUE TITLE
Some "Status bar" preferences show only dashes

### ISSUE THREAD

**Issue by fiery-** [coteditor/CotEditor#741]
In CotEditor 3.2.3, when I turn on "Status bar shows" -> "Encoding", "Line Endings", "File Size" preferences, they appear correctly, but once I close and open CotEditor (with any document), only three dashes are shown.
![Status fields working](https://user-images.githubusercontent.com/4441889/31956585-826ccad2-b8f4-11e7-822d-d46a6fcd4560.png)
![Status fields showing dash](https://user-images.githubusercontent.com/4441889/31956569-7a815dba-b8f4-11e7-9e03-cc83357323a1.png)

**Comment by 1024jp** [comment]
Oops, I've committed fixes with a wrong issue number. They are for #743.
Sorry, and reopen this.

**Comment by 1024jp** [comment]
Thanks for the report!
The bug will be fixed in CotEditor 3.2.4.
