### ISSUE TITLE
Enhancement: allow root to run COT

### ISSUE THREAD

**Issue by Slowly** [coteditor/CotEditor#745]
I just discovered the COT shell command. I'd LOVE to use coteditor to edit text files as root. However, as of version 3.2.4 (207), if I try:

 ` sudo cot <some text file>`

It opens, but not as the root user.

If I login as root, and try, for example:

`cot /etc/bashrc`

I get:

`[BETA35-8.local:~]> cot /etc/bashrc

Traceback (most recent call last):
  File "/usr/local/bin/cot", line 340, in <module> main(args, stdin)
  File "/usr/local/bin/cot", line 272, in main app.open(path)
  File "/usr/local/bin/cot", line 141, in open self.tell('open POSIX file "{}"'.format(path), is_async=True)
  File "/usr/local/bin/cot", line 121, in tell return run_osascript(script, is_async)
  File "/usr/local/bin/cot", line 92, in run_osascript
  raise CalledProcessError(p.returncode, script)
  subprocess.CalledProcessError: Command 'ignoring application responses
  tell app "/Applications/CotEditor.app" to open POSIX file "/private/etc/bashrc"
  end ignoring' returned non-zero exit status 1`

Please add this, when you can :)

John Bonifas
MS Applied Geospatial Science Candidate
Dept of Geography, Planning and Recreation
School of Behavioral Sciences
Northern Arizona University

**Comment by 1024jp** [comment]
Thanks for your feedback.

I suppose it actually hard 'cause CotEditor must follow the Apple's Sandboxing rules.
However, I'm yet not sure whether it really cannot. I'll try once.

**Comment by 1024jp** [comment]
Sorry for my late reply.
According to my research, macOS applications cannot be invoked as root as long as the application is Sandboxed.
And we don't have any plan to remove Sandbox in the future.
So, unfortunately, it's currently impossible.

**Comment by malhal** [comment]
I guess TextMate lives on then since it's the only app that can do this:
```
sudo mate /etc/hosts
```

**Comment by 1024jp** [comment]
TextMate is not sandboxed.
