### ISSUE TITLE
PHP syntax formatting/beautify with php-cs-fixer

### ISSUE THREAD

**Issue by uschmelzer** [coteditor/CotEditor#746]
Hi everybody, 

I've created a CotEditor script for PHP syntax formatting/beautify with php-cs-fixer.
Please find it here:
https://github.com/uschmelzer/coteditor-scripting-test/blob/master/Scripts/Format-PHP/php-cs-fixer.php

If this is the wrong place to post, please advise me.

Cheers
uwe5

**Comment by 1024jp** [comment]
Thank you for sharing a nice script!
I've just added yours to [CotEditor Script list in Wiki](https://github.com/coteditor/CotEditor/wiki/CotEditor-Scripts).

If you made more, feel free to add your other scripts.
