### ISSUE TITLE
quotes automate convert mistake

### ISSUE THREAD

**Issue by harlentan** [coteditor/CotEditor#747]
CotEditor will always convert `"` to ` “`. 

How to disable this feature?

**Comment by 1024jp** [comment]
For future searchers:
You can set it in the Edit pane in the Preferences.

<img width="662" alt="screen shot 2017-11-22 at 23 15 07" src="https://user-images.githubusercontent.com/1165044/33131865-39848ba4-cfdb-11e7-97c9-09113e2b8e79.png">
