### ISSUE TITLE
Disable atomic saves

### ISSUE THREAD

**Issue by az82** [coteditor/CotEditor#749]
## Problem
CotEditor uses atomic saves, which among other things breaks hard links. 
Hard links are necessary for common use cases such as managing dotfiles in git (For reference see https://dotfiles.github.io/)

## Solution
- Remove atomic saves
- Provide an option to disable atomic saves

## How to reproduce:
1. Create two hard-linked files:
    ```sh
    echo one > a.txt
    ln a.txt b.txt
    ```
2. Open one in CotEditor
    ```sh
    cot a.txt
    ```
3. Edit the file and save

4. Open the other file -> The changes won't be visible in the other file, the hard link is broken

**Comment by 1024jp** [comment]
CotEditor already has an option to disable the autosaving in General pane.
Isn't it enough for your demand?

![screen shot 2017-11-29 at 18 25 39](https://user-images.githubusercontent.com/1165044/33367698-c9701920-d532-11e7-9220-feb3cf8b62ed.png)

**Comment by az82** [comment]
I've already tried that without success. The autosave switch only seems to disable automatic background saves.

The issue is with the regular save behaviour. There should be at least an option to save without replacing the file.

**Comment by 1024jp** [comment]
Oops sorry, I've just misread "atomic" with "automatic." It's my fail.

Well, regard to __atomic__ saving: this is the recommended and provided way to save documents on Cocoa apps (If I remember correctly).
I'll reproduce and study later this behavior under my environment. But, at this time point, I'm not sure if CotEditor __should__ implement this feature, although I personally understand your practical issue.

**Comment by 1024jp** [comment]
I remembered that I had the same request from a user before (#452), and I've rejected it.
So, I'd say this time also: it's in the spec. Sorry.
