### ISSUE TITLE
Showing character count for a paragraph in status bar

### ISSUE THREAD

**Issue by mu373** [coteditor/CotEditor#750]
I suggest that it would be more convenient if I could see a character count/word count for a paragraph that I am working on in the status bar. Considering the wide range of usage of the app, this function can help the users to construct a balanced and organized document, efficiently reaching an aimed word count.

**Comment by 1024jp** [comment]
Thanks for the request.
However, isn't it enough performing "Select Line" (Command+Shift+A) and seeing the inside of the parentheses in character count.

Technically speaking, implementing this feature is not difficult. But I must be careful to add an option and prefer to avoid it.

**Comment by 1024jp** [comment]
I close this issue since there is no active motivation to impelement this.
