### ISSUE TITLE
検索ウィンドウの横幅について

### ISSUE THREAD

**Issue by wanik** [coteditor/CotEditor#751]
検索ウィンドウ内に、長い正規表現を入力して検索すると、検索ウィンドウがスクリーンいっぱいに広がってしまい、幅を狭めようとしても狭まりません。

検索文字列と置換文字列を入力する部分は、上下に広げられますので、長い正規表現を枠内で折り返して表示することで、検索ウィンドウの幅を広がりすぎないようにすることはできませんでしょうか。

Mac OS X Yosemite 10.10.5
CotEditor 3.2.5 (208)

正規表現パターン例：
アルファベット母音字の後ろに合成可能なディアクリティカルマークがあるものを検出したい場合
(?:a\p{InCombiningDiacriticalMarks}*)|(?:e\p{InCombiningDiacriticalMarks}*)|(?:i\p{InCombiningDiacriticalMarks}*)|(?:o\p{InCombiningDiacriticalMarks}*)|(?:u\p{InCombiningDiacriticalMarks}*)

（上のパターンは「[aeiou]\p{InCombiningDiacriticalMarks}*」のように書けば済みますが、複数の単語などを検索したいときに、長くなることもありますので、よろしくお願い致します。）

**Comment by 1024jp** [comment]
状況がイメージできていないので以下をいただけませんか？
- 現象を再現する手順
- 広がった状態のスクリーンショット

**Comment by wanik** [comment]
現象が生じる流れ・状況をスクリーンショットにまとめてみました。
このような感じになりますが、どうぞよろしくお願い致します。
![findwindow](https://user-images.githubusercontent.com/34469683/33881846-75fa5be2-df79-11e7-88f7-426b85075128.jpg)

**Comment by 1024jp** [comment]
ありがとうございます。再現できました。
確かにこれはイマイチな挙動なので、次のバージョンアップ時に修正をしたいです。

要望ありがとうございます。

**Comment by wanik** [comment]
どうもありがとうございます。
さっそくご確認いただいて、うれしいです。
修正をお待ちいたしております。

**Comment by 1024jp** [comment]
修正しました。CotEditor 3.2.7 で反映される予定です。
3.2.7 のリリースは未定ですが、おそらく来年の1月中かと思われます。
場合によっては 3.2.7 を飛ばして 3.3.0 に数字をすすめる可能性もあります。

**Comment by wanik** [comment]
さっそくの修正、どうもありがとうございます。
次回のリリースが楽しみです。
