### ISSUE TITLE
About input fields on the find panel / 検索結果の表示と検索文字列の折り返しについて

### ISSUE THREAD

**Issue by wanik** [coteditor/CotEditor#754]
（検索ウィンドウの横幅の改善、どうもありがとうございます。検索ウィンドウにつきまして、もう一件、お願い致します。）

検索時に、「見つかりません」あるいは「1件見つかりました」などの結果が、検索文字列の入力欄の右隅に表示されます。しかし、検索文字列が長い場合、末尾部分がこの表示の下に隠れます。

入力欄に何かを入力すれば表示は消えますが、横スクロールをしたりカーソルを移動するだけでは、表示に隠れたままで、入力の末尾部分を確認できません。

正規表現の検索などで予想外の結果が出た場合などに、その場で入力したパターンを確認したいことがあります。「見つかりません」などの結果の表示は必要ですが、入力値を隠さない場所に表示されるか、入力値の変更以外の何らかのイベントで消せるなどできますと、助かります。

これとの関連ですが、検索ウィンドウは上下に拡大でき、また入力欄の文字列に改行を含む場合は、複数行の入力が可能です。しかし、改行を含まない長い文字列の場合は、折り返しされずに1行のままです。

改行を含まない場合も、折り返して表示されるようになりますと、横スクロールをしなくても、入力値全体が見渡せるようになるかと思います。

併せてご検討頂けますと、助かります。どうぞよろしくお願い致します。

![coteditor_find](https://user-images.githubusercontent.com/34469683/34610318-f5ed87be-f263-11e7-8823-7f39b7cf1dda.jpg)

**Comment by 1024jp** [comment]
フィードバックありがとうございます。

最初の検索結果によってフィールド内の文字が隠れる件については、なんらかの対策を考えたいと思います。

2つ目のフィールドはして折り返さずにスクロールされる仕様は、
意図的にこのような仕様にしているので、変更予定はありません。
お手数ですがパネルのサイズを広げることでしのいでいただければと思います。

**Comment by wanik** [comment]
3.3.0のmilestone、どうもありがとうございます。

折り返ししない旨、了解致しました。

**Comment by 1024jp** [comment]
CotEditor 3.3.0 (次にリリース予定の 3.2.8 の次) にて対策を行い、
結果が表示されていても検索フィールドの中身全体が見えるところまでスクロールができるようにしました。

**Comment by wanik** [comment]
どうもありがとうございます。
3.3.0 のアップデートが待ち遠しいです。
