### ISSUE TITLE
File Drop to edit the file?

### ISSUE THREAD

**Issue by hosupc** [coteditor/CotEditor#761]
I'd like to drop a file to CotEditor to edit the file. 
Sometimes, I have to update multiple files. And drag and drop is a convenient way to edit file.
I believe most of editors will edit the file, if it was drag and drop to the editor. 

So is there's a way to do this from File Drop preferences setting?

**Comment by 1024jp** [comment]
Thanks for the feedback.

I know it is actually a popular feature in text editors opening a file by drag-and-drop on an editor window. And also some users want this also on CotEditor.
However, I feel this is not a behavior for a macOS application.
If you want to open files by drag-and-drop, then you should drop them on the application icon in Dock.
Therefore, I don't implement it on purpose.
Sorry, but to behave in the macOS manner is the most important policy for CotEditor.
