### ISSUE TITLE
I'm unable to open multiple files in the order they appear in the folder

### ISSUE THREAD

**Issue by jro31** [coteditor/CotEditor#762]
I have multiple files in a folder, which I need to edit in the order that they're named numerically, eg:
1.html
2.html
3.html
4.html
5.html
etc.

When using CotEditor and I click 'Open', then 'Command + A' to select the files, then open them, they appear in the tabs in a seemingly randomised order, eg:
7.html
2.html
3.html
9.html
1.html
12.html
etc.

Apologies if this is an obvious question; I'm new to both Mac and CotEditor, but is there a way to open the files so that they appear in the tabs, in the order in which they are organised in the folder?

**Comment by 1024jp** [comment]
Hmm, this is just the way macOS handles document files, and therefore, I’ll not insert additional code to change this behavior.
Sorry.
