### ISSUE TITLE
削除時のアラート非表示の設定

### ISSUE THREAD

**Issue by uchidasatoshi** [coteditor/CotEditor#763]
ファイル削除時にアラートが表示されないように設定できるようにしてほしい。
アラート表示後に削除ボタンを押下をしないとウィンドウ削除ができないのは、作業の無駄が多い。

**Comment by 1024jp** [comment]
これはmacOSの標準的な仕様なので、オプションとしてでも変更するつもりはありません。

**Comment by uchidasatoshi** [comment]
回答ありがとうございます。macOSの標準的な仕様だと理解しました。
テキストエディタ含め、他のエディタも同様の挙動をしています。
この挙動をしないエディタを探しているのですが、なかなか見つかりません。
ソース上で修正しようと思うと大変なのでしょうか？

**Comment by 1024jp** [comment]
大変かどうかは実装次第ですが、Cocoa（macOS用のフレームワーク）を使っていないアプリケーションであれば、余計なチェックをしなくて良い分むしろ楽なんじゃないかと思います。

**Comment by uchidasatoshi** [comment]
回答ありがとうございます。もうすこし調べてみました。
macOSの標準的な仕様であれば、システム環境設定の一般の「書類を閉じるときには変更内容を保持するかどうか確認」のチェックがはずれていれば、確認のアラートを表示させないのが本来は正しいように思えます。
ですが、チェックがはずれていても、大概のテキストエディタはアラートが表示されるようです。macOSのバグなのでしょうか？それとも実装を変更すれば、アラートを表示しないようにできるのでしょうか？
（参考）
http://souzou.motta.jp/2016/07/08/3718/
（参考２）
http://d.hatena.ne.jp/zariganitosh/20121017/autosave_version_tracking
（参考３）
http://jp.tidbits.com/TidBITS-jp-1138.html#lnk2

**Comment by 1024jp** [comment]
もしかしたら理解に行き違いがあるかもしれません。
「ファイル削除時」の定義をもう少し明確にしていただくとこちらも状況がわかるかもしれません。
（正確にいえば、CotEditor が「ファイルの削除」を行うことはないので。「書類のウインドウを閉じるときに」ということでしょうか）

以下の2つの条件が揃っていれば、「書類のウインドウを閉じるときに」はすでに変更がオートセーブによりファイルに保存されているので確認のダイアログは出ないはずです。
1. CotEditorのオートセーブが有効（環境設定 > 一般 で設定できます）
2. 新規書類ではなくすでにどこかに保存されている書類

なお、この仕様は Cocoa フレームワークの dobument-based サブシステムを正しく利用したアプリケーションの仕様なので、「大概のテキストエディタ」がこれに適合するものかはそのテキストエディタ次第になります。ちなみに、これに適合する著名なテキストエディタは数える程しかないかと思います。CotEditor は適合しているつもりです。していない場合はバグの可能性もあるので調査します。

**Comment by uchidasatoshi** [comment]
回答ありがとうございます。
１、２の状態であれば、確認アラートは表示されないことを確認できました。
本当は新規書類で確認アラートが表示されないことが望ましいのですが、
それはCocoa フレームワークに準拠したら、難しいということですね。
同じように困っていた人で、保存ファイルで書類作成をしていたTIPを見つけました。
この方法で対処したいと思います。ありがとうございます。
（参考４）
http://gorolib.blog.jp/archives/50447392.html

**Comment by 1024jp** [comment]
すり合わせができたようでよかったです。
難しいと言うか、それなりに理由があって採用されている仕様なので変えたくない、と言ったところです。

そう言う意味では、唯一CotEditorに限って言うと、その時の書類の中身が空であれば新規書類でもアラートが表示されずすぐにウインドウが閉じ中身（空ですが）も廃棄されます。
なので、編集中などであれば「⌘A」で全体を選択してからdeleteキーや⌘Xで丸ごと中身を削除したのち⌘Wでウインドウを閉じればすぐに閉じることができます。
（私自身もたまにそうやって保存するまでもない書類のウインドウを閉じてます）

**Comment by uchidasatoshi** [comment]
なるほど。仕様がわかれば、対処の仕方がわかりますね。
助かります。
