### ISSUE TITLE
None for Syntax Style

### ISSUE THREAD

**Issue by bluemix** [coteditor/CotEditor#771]
I downloaded CotEditor Version 3.3.0-beta (216) and I have a problem with
_Syntax Style_ always shows _None_ for any file I open.

I restarted my Mac, and re-downloaded it, and still having this issue.

<img width="417" alt="screen shot 2018-01-24 at 11 47 03" src="https://user-images.githubusercontent.com/3332274/35371939-1fc307fa-01a8-11e8-9368-d3459eac3114.png">

**Comment by 1024jp** [comment]
Hmmm, thanks for opening an issue.
Could you tell me your macOS version?

**Comment by 1024jp** [comment]
Ah, I've just reproduced this issue.
This is definitely a bug caused by my mistake.
I'll fix this in the next beta, 3.0.0-beta.2.
Thanks.

**Comment by 1024jp** [comment]
I've just released CotEditor 3.3.0-beta.2 fixing this issue.

[coteditor.com/beta](https://coteditor.com/beta)

**Comment by bluemix** [comment]
OK, I updated the version (3.3.0-beta.2), and it is showing Syntax Style 👍

**Comment by 1024jp** [comment]
@bluemix Thank you for confirming the bug fix.
