### ISSUE TITLE
realizing emacs key-binding by using option-key for meta key

### ISSUE THREAD

**Issue by kkdd** [coteditor/CotEditor#772]
こんにちは
今後の開発方向性として、emacs key-binding に近づけるという目的で、meta key として option を指定可能とさせる可能性はあり得るでしょうか？（それとも開発方向性としてあり得ないでしょうか？）

**Comment by 1024jp** [comment]
方向性としてはあり得なくないのですが、
現状の実装として⌘を絡めることが前提になってしまっているので変更が難しいです。
ニーズとしてはわかるので長期的には検討します。

**Comment by kkdd** [comment]
Thank you for your comment, and I appreciate your possible intention of its realization in futuristic CotEditor if possible.
（なお Terminal.app で meta key として option を指定可能なので有難いですね, for example.）
