### ISSUE TITLE
CotEditor 3.3.0 crashes on OS X 10.11 / CotEditorが予期しない理由で終了

### ISSUE THREAD

**Issue by rye03** [coteditor/CotEditor#779]
CotEditor ver 3.3.0(224)にアップデート後にCotEditorを起動したところ、予期しない理由で終了しました。
念のため、PC再起動を行った後にCotEditorを起動しましたが、同様の事象が発生。
MacOSによるレポートを添付します。
[report.txt](https://github.com/coteditor/CotEditor/files/1709450/report.txt)

**Comment by 1024jp** [comment]
ありがとうございます。
クラッシュレポート大変助かります。
早急に原因を突き止め今週中に修正版を提出したいです。
