### ISSUE TITLE
CotEditor won't launch on OS X El Capitan 10.11.6

### ISSUE THREAD

**Issue by CupInertia** [coteditor/CotEditor#781]
Hello,

Really looking forward to trying this editor, but it crashed when I try to launch it on 10.11.6. Installed it from the App Store.

I did find the following in the logs:
`10/02/2018 11:25:08.269 CotEditor[455]: objc[455]: Cannot form weak reference to instance (0x7fcec3f02420) of class NSKVONotifying_CotEditor.EditorTextView. It is possible that this object was over-released, or is in the process of deallocation.
`

Please let me know if there's more information I could provide.

Cheers!

**Comment by 1024jp** [comment]
Really sorry for the bug and thank you for the report.

This issue was already reported in #779, #780.
CotEditor 3.3.1, which fixes this issue, was already submitted to Apple yesterday and now is waiting for the approvement. Please be patient until the release.

**Comment by CupInertia** [comment]
Thank you for looking into it! :)

**Comment by 1024jp** [comment]
The issue was finally fixed on CotEditor 3.3.2, which was released today).

**Comment by CupInertia** [comment]
Thank you! Works great! ;)
