### ISSUE TITLE
Smart Home feature

### ISSUE THREAD

**Issue by andylima** [coteditor/CotEditor#785]
I've been really loving CotEditor these latest months — congrats! It's quick to start and good for many light programming tasks, writing, & note taking. It also has some surprising features that other editors often don't have.

One thing I'm really missing is Smart Home functionality — So that, if we press Cmd+Left, instead of just going to visual column 1, CotEditor would:
1. If there's only one visual line (no wrapping), go first to the column right after indentation. And then, if we press Cmd+Left again, we then go to column 1.
2. If there are several visual lines (wrapped lines) in the current absolute line, go first to visual column 1, then — if we press Cmd+Left again — go to the visual column 1 of the visual line that's above it (if it's part of the same current absolute line, of course), except when the visual line above is the beginning line (i.e., the first visual line of the current absolute line) — in this case go first to the column right after indentation… and then, if we press Cmd+Left again, we then go to column 1.

This approach (or at least case 1 above) is taken by lots of programming editors, like Visual Studio Code, Sublime Text, etc.  It brings the best of both worlds. And also, we always have Ctrl+A to go straight to absolute column 1.

**Comment by 1024jp** [comment]
Thank you for the feedback.

It seems a reasonable behavior.
I'll definitely implement case 1, then consider the rest.

**Comment by 1024jp** [comment]
I implemented both case 1 and case 2.

I actually really struggled whether I should implement case 2 because it seemed not a major behavior in other text editors (at least on macOS).
However, I personally felt the case 2 is a natural and convenient behavior that has worth to implement.
So I did.
Well, let's see how other users say.

**Comment by andylima** [comment]
This is great! Thank you! 👌

I think that, in the event that most users don’t like Cmd-Left with case 2, having this as a preference (even if hidden, and being set through the terminal) would be great for users like me... — In the Vim editor, there’s a key combination for this, which many people map to the normal key for “home”.
