### ISSUE TITLE
Editor should indent selected lines after hitting tab key while multiple lines are selected

### ISSUE THREAD

**Issue by ethemcemozkan** [coteditor/CotEditor#786]
Currently editor just deletes selected lines and starts new line with indent. However most text editors keeps selected lines and creates indent for this lines. I think this should be the default behavior.

**Comment by 1024jp** [comment]
duplicate #620, #324.

It's actually duplicated request, I've said always "no."
However, well, because I receive this request so often, it seems I should add an option to toggle the behavior.

**Comment by 1024jp** [comment]
I added "Indent selection with tab key" option to the next CotEditor 3.3.3 😉

<img width="672" alt="screen shot 2018-02-22 at 22 37 14" src="https://user-images.githubusercontent.com/1165044/36541375-082b6102-1821-11e8-8e68-ed71dd4b59b8.png">

**Comment by ethemcemozkan** [comment]
Thanks!!

**Comment by jr-k** [comment]
Thanks for this ! Absolutely needed feature !
