### ISSUE TITLE
Scroll Past End of File

### ISSUE THREAD

**Issue by andylima** [coteditor/CotEditor#790]
Allow the user to be able to scroll past the bottom of the document.

…So that we can type comfortably, e.g., with the text being typed in the middle of the screen and not at the bottom (when the caret is near the EOF).

This is another preference that many popular text editors have. Would be great! — Otherwise I keep placing (and having) blank lines at the bottom of files just so that I don't have to bend my neck to write… 😉

You can see a user asking for this, e.g., for a JetBrain's editor (which, as you can see by the answer, already has it):
https://intellij-support.jetbrains.com/hc/en-us/community/posts/205814379-Scroll-Past-End-Of-File

I'm pasting the relevant text:
> When scrolling down to the bottom of a long file, I'd like to be able to keep scrolling past the end
> of the file. This way the last line in the file can be in the middle or even at the top of the screen.
> I don't like having to look down at the bottom of my monitor to edit the last line of a file.
> Is there a setting that allows for this?

The setting in that IDE seems to be called "Show virtual space at file bottom".

…Though I remember in some editors this setting being called something along the lines of: "Scroll Past End of File".

I hope you can add this… One of the few features I am missing.

And, again, thank you for a fantastic text editor!

**Comment by 1024jp** [comment]
Thank you for the feedback.
I know some users love this feature.
However, to avoid the CotEditor' settings and layout conditions being complex, the priority for it is very low on CotEditor.
I keep this issue open, but currently, I don't have any plan to implement it.

**Comment by 1024jp** [comment]
I've changed my mind.
I'll implement this option on the next minor update.

**Comment by 1024jp** [comment]
finished the implementation.

<img width="875" alt="screen shot 2018-06-15 at 18 09 32" src="https://user-images.githubusercontent.com/1165044/41480433-c62ddc06-70ce-11e8-899a-eecd288e1aab.png">
