### ISSUE TITLE
Shift+Tab should revert indent

### ISSUE THREAD

**Issue by ethemcemozkan** [coteditor/CotEditor#792]
Shift+Tab should revert indent by one level at a time like most text editors did. Maybe you can add another option for this.

**Comment by 1024jp** [comment]
It's actually already implemented with "Indent selection with Tab option".
However, it outdents only when something is selected (just like indent with Tab key).
You mean it should outdent even when nothing is selected?

**Comment by ethemcemozkan** [comment]
@1024jp That behavior is fine. What i am saying is it should outdent current line if nothing is selected.

**Comment by 1024jp** [comment]
Ok, honestly speaking, I just forgot such case.
I'll change the behavior on the next CotEditor 3.3.4 to outdent current line even nothing is selected.

**Comment by ethemcemozkan** [comment]
No problem thats why we can open issues here. :)

**Comment by 1024jp** [comment]
Finish implementation.
I'll release CotEditor 3.3.4 in one or two weeks.
Thank you for the feedobak.
