### ISSUE TITLE
Allow permanently close get info pane

### ISSUE THREAD

**Issue by ethemcemozkan** [coteditor/CotEditor#793]
I may be missing something here but my problem is get info pane always opens when new window is created. Maybe some users don't want to close this panel every time they open app.

**Comment by 1024jp** [comment]
"Show document inspector" option in Window preference may be on.

<img width="672" alt="screen shot 2018-02-25 at 9 48 47 pm" src="https://user-images.githubusercontent.com/1165044/36641603-b979f58a-1a75-11e8-9627-05cdb708a66e.png">

Please tell me if the inspector appears even the option turned off. Then, it must be a bug.

**Comment by ethemcemozkan** [comment]
@1024jp Okay it works as expected. I will close this issue.
