### ISSUE TITLE
「この新しい書類“名称未設定”を残しますか?」ダイアログのレイアウトが崩れているように感じる

### ISSUE THREAD

**Issue by griffin-stewie** [coteditor/CotEditor#795]
## Environment (環境)

- CotEditor: 3.3.3 (232)
- System: macOS バージョン10.13.3（ビルド17D102）
- Language: Japanese

## Short Description (簡単な説明)

「この新しい書類“名称未設定”を残しますか?」ダイアログのレイアウトが崩れる場合がある。

## Steps to Reproduce the Issue (不具合が発生したときに行っていた操作、または再現手順)

1. 新規ドキュメントを作成
2. 適当な文字を入力する
3. Cmd+s を押し保存ダイアログを表示させる
4. 保存ダイアログをキャンセルする
5. Cmd+w でドキュメントを閉じようとする
6. 「この新しい書類“名称未設定”を残しますか?」ダイアログが表示される

最後のステップで表示されるのはこのような画面です。レイアウトが右に寄ってしまっているように感じます。

<img width="972" alt="dialog" src="https://user-images.githubusercontent.com/22316/36669640-e60151b6-1b38-11e8-87d9-09f81236fbdd.png">

感触としては先に出ている保存ダイアログの幅と同じ幅で「残しますか？」ダイアログが表示された場合に AutoLayout の設定かなにかで右に引っ張られているように思います。

## Expected Result (期待される挙動)

1. 新規ドキュメントを作成
2. 適当な文字を入力する
3. Cmd+w でドキュメントを閉じようとする
4. 「この新しい書類“名称未設定”を残しますか?」ダイアログが表示される

上記ステップで表示されるようなレイアウトでおそらくはセンタリングされたようなものかと思います。

**Comment by 1024jp** [comment]
それ私もさっき気づいたんですよねぇ。
Apple側のAutolayoutのあれな気がするのですが、かっこ悪いので何らか迂回策をとります。

**Comment by 1024jp** [comment]
だめだ、まだケース漏れがあった。

**Comment by griffin-stewie** [comment]
🙇

**Comment by 1024jp** [comment]
🐈
