### ISSUE TITLE
[Feature Request] „Match New Line“ for Regex Search

### ISSUE THREAD

**Issue by Berovowilare** [coteditor/CotEditor#798]
Hello 

I would love to see a checkbox in the advanced search options for „Match New Line“. So if a Regex query goes over a \n or \r it will find the string too.

Greetings

**Comment by 1024jp** [comment]
I'm not sure what exactly "<q>a Regex query</q>" in:

> So if a Regex query goes over a \n or \r it will find the string too.

But you may be able to use the "Dot matches line separators" option.

**Comment by Berovowilare** [comment]
Hello

For example:


<sub>some 
text</span>

<sub>some text
</span>

<sub>
some text</span>


To find all cases. I know I can <sub>((?s).+?)</span> if I have a more complicated string to search this is a little annoying. One time I saw in another application with the option to search Regex over different lines, by checking a box „Match New Line“. 

Greetings

**Comment by Berovowilare** [comment]
Hello

For example:


<sub>some 
text</span>

<sub>some text
</span>

<sub>
some text</span>


To find all cases. I know I can <sub>((?s).+?)</span> if I have a more complicated string to search this is a little annoying. One time I saw in another application with the option to search Regex over different lines, by checking a box „Match New Line“. 

Greetings

**Comment by 1024jp** [comment]
Have you tried "Dot matches line separators"? Then, you can find all cases with `<sub>(.+?)</span>`.

![screen shot 2018-03-05 at 20 14 50](https://user-images.githubusercontent.com/1165044/36972298-f7954652-20b1-11e8-91ee-83fabaa118e3.png)

**Comment by Berovowilare** [comment]
Thanks that works.

Greetings
