### ISSUE TITLE
[Feature Request] add character spacing option

### ISSUE THREAD

**Issue by aesthicc** [coteditor/CotEditor#800]
A bit of a silly request but as there is also an option to adjust the line height, could you add an option to horizontally adjust character spacing? 

So for example 
![1](https://user-images.githubusercontent.com/32882701/36761021-7d394644-1c1d-11e8-8de1-02bdfe3b1e1c.png)

looks more like
![2](https://user-images.githubusercontent.com/32882701/36761035-8d0b7dd0-1c1d-11e8-8f3a-133f46abe8a5.png)

Thank you!
And thank you for this free and open source app, it's really wonderful.

**Comment by 1024jp** [comment]
Thank you for the feedback.
However, because such a demand is minor, I'll not add an option for it.
I have to keep CotEditor's preferences simple as possible.
Sorry.
