### ISSUE TITLE
Revert the behavior for ⌘← shortcut / ⌘←キーを押したときのカーソルの挙動を元に戻してください

### ISSUE THREAD

**Issue by slapstop** [coteditor/CotEditor#801]
3.3.3で以下のように挙動が変わっていますが、基本的にMacでは⌘キーと矢印キーの組み合わせでは、ドキュメント最上部、ドキュメント最下部、行頭、行末に移動です。長年慣れ親しんでいる挙動を変えないでください。

⌘←キーを押したときのカーソルの挙動を以下のような順で移動するように変更：折り返し行の行頭→その前の折り返し行の行頭→インデントの手前→行頭

**Comment by 1024jp** [comment]
ref. #785

**Comment by 1024jp** [comment]
まず前提として、⌘←のCotEditor 3.3.3以前の挙動は「折り返し行の行頭に移動」でした。

今回の変更点は分解すると以下の2点となります:
1. 行が折り返していない場合はインデント手前を一旦挟む
2. 「⌘←」を折り返し行の行頭で押した時に前の行の折り返し行の行頭へ移動

このうち 1. についてはApple製の開発環境Xcodeでも採用されている仕様であり、コードエディタとしてはより一般的かと思いましたので採用に至りました。
また 2. については、若干イレギュラーな仕様でもあるので私自身迷ったのですが、「⌘←」1回については従来の仕様と変わらないこと、また複数回「⌘←」押すことで以前では達成できない挙動が達成できること、
の二点から採用に至りました。

基本的には、「⌘←」を連打しないかぎり大きくは挙動が変わらないと考えています。1.については現時点では変更の予定はありません。2. については新しい仕様で不都合がある場合は具体的なケースを教えてください。場合によっては検討します。

**Comment by slapstop** [comment]
最近のXcodeはそうなっているんですね（もう10年ほど使っていません）。ただ、Mac歴30年の私の感覚が古いだけなのかもしれませんが、やはり⌘+矢印キーは上下左右の端というのが定番だと思います。ワード等の頭はoption+←。

⌘+←が行頭でないと困るのはコピペする時です。ペーストしたい場所の下の行を適当にクリックして⌘+←　⌘+V。この動作で変な場所にペーストされてしまい非常に困っています。

せめて設定で切り替えられるようにしていただければと思います。

**Comment by 1024jp** [comment]
具体例の説明ありとうございます。
ではどちらかというとどちらかというと戻して欲しい挙動は

> 1. 行が折り返していない場合はインデント手前を一旦挟む

についてということですね。

現時点では

a. （コーディング）テキストエディタとしてはより一般的な挙動であること
b. 1. を採用しないときはインデント手前に行くすべがないが、現在の実装であれば「⌘←」を2回押せば従来の動きも再現できること

から以前の挙動に戻す予定はありません。

また、以下についてですが、

> せめて設定で切り替えられるようにしていただければと思います。

CotEditorの設計方針としてこれだけのために（隠し設定を含め）新たな設定項目を加えることはしません。

すべてのユーザのすべての要望に応えることはできないので、最大公約を探りながら実装しています。
要望に添えず申し訳ないですがご理解願います。

ショートカットのキーマッピングについては長期的には考えます。

**Comment by slapstop** [comment]
残念ですが3.3.2を使い続けるかソースを自分で修正するか検討してみます。

ただ、実際にプログラムを作っていて思うのですが、ifとかunlessの前に何かを挿入する（カーソルを移動する）などということは皆無なのです。ifやunlessの後ろの条件を変更することは普通ですが。ですので行頭ではなくインデントの後にカーソルを移動する意味がわかりません。

**Comment by 1024jp** [comment]
> 残念ですが3.3.2を使い続けるかソースを自分で修正するか検討してみます。

フォークをする場合は、EditorTextView の `moveToBeginningOfLine(_:)` と `moveToBeginningOfLineAndModifySelection(_:)` をコメントアウトすると元の挙動に戻ります。

> ただ、実際にプログラムを作っていて思うのですが、ifとかunlessの前に何かを挿入する（カーソルを移動する）などということは皆無なのです。ifやunlessの後ろの条件を変更することは普通ですが。ですので行頭ではなくインデントの後にカーソルを移動する意味がわかりません。

これに関しては人によると思うのでなんとも言えません。
個人的には正直どっちでもいいと思ってます。ただこの機能が欲しい人もいるということです。
