### ISSUE TITLE
Highlighted text unreadable with Lakritz theme if window unfocused

### ISSUE THREAD

**Issue by toddyco** [coteditor/CotEditor#802]
## Environment

- CotEditor: 3.3.4 (234)
- System: macOS Version 10.12.6 (Build 16G1212)
- Language: English

## Short Description

Highlighted text (i.e. text click-and-drag selected by the end user) is not readable when CotEditor window is unfocused while the Lakritz theme is active.

## Steps to Reproduce the Issue

1.  Enable the "Lakritz" theme in the CotEditor preferences.
2.  Open a file with text in it, or create a new file and paste text into it.
3.  Use cursor to highlight a portion of the text.
4.  While the text is still highlighted, click cursor on a window in a different application.
5.  Observe that the highlight color in the now-unfocused CotEditor window has turned white and make the text unreadable. 
![screen shot 2018-03-17 at 12 37 28 pm](https://user-images.githubusercontent.com/30083938/37557784-2e7c7ac8-29e0-11e8-952f-983c3cf77c75.png)

## Expected Result

The highlight color should not turn a color that makes the text it highlights unreadable while unfocusing from the CotEditor application. This is especially a problem when using multiple monitors—CotEditor has highlighted text on one monitor and clicking on another application on the other monitor causes the highlighted text in CotEditor to become unreadable.
![screen shot 2018-03-17 at 12 37 21 pm](https://user-images.githubusercontent.com/30083938/37557787-326c12c4-29e0-11e8-84ec-d90d84f9f86f.png)

**Comment by 1024jp** [comment]
Thank you for the feedback.
I honestly concerned about that.

I've just improved CotEditor 3.4.0 so that an original alternative color (grayish, but less contrast) is used for selected text when an editor is inactive.

![screen shot 2018-03-18 at 2 54 00 am](https://user-images.githubusercontent.com/1165044/37558443-a2faa588-2a57-11e8-8875-ecc871d8bcd0.png)
(above:inactive / below: active)

(It may take at least more than one month to release CotEditor 3.4.0 because it's a minor update.)

**Comment by toddyco** [comment]
@1024jp Great, thanks. Keep up the great work!

**Comment by nuno-agostinho** [comment]
This issue still occurs for me with an inactive window and using Lakritz or other dark themes.

- CotEditor: 3.8.5 (384)
- System: macOS Version 10.14.6 (Build 18G87)
- Language: English

Maybe it would be best if we could edit the selection colour for inactive windows?

![Unreadable selected text when using Lakrtiz theme in an inactive window](https://user-images.githubusercontent.com/3199157/68952953-c349ec00-07b8-11ea-8aa3-5252d3790559.png)

**Comment by 1024jp** [comment]
Oh, thank you for pointing it out.
I forgot to update that part to follow some changes in the window appearance setting option in the last versions.
I'll fix it in the next version.
