### ISSUE TITLE
検索パネル：正規表現入力フィールドにおける括弧のハイライトとダブルクリックによる選択 / Highlight brackets in find panel on regex mode

### ISSUE THREAD

**Issue by zumuya** [coteditor/CotEditor#807]
## Environment

- CotEditor: 3.3.5 (237)
- System: macOS Version 10.13.3 (Build 17D47)
- Language: English

## Description

現在エディタ上で以下の操作が可能ですが、検索パネルで正規表現を編集するときにも使えたら便利だと思いました。
1. 括弧文字の直後にカーソルが移動したとき、対応する括弧を一時的にハイライト
2. 括弧文字をダブルクリックしたとき、括弧全体のまとまりを選択

（バックスラッシュでエスケープされた括弧や [] 内の括弧は無視されるのが理想）

**Comment by 1024jp** [comment]
正規表現がチェックされてるときは正規表現のシンタックスハイライトが適用されると愉快だなぁとは思っていましたので、せっかくリクエストも来たのでなんらかやります。

個別に具体的にどれを採用するかは考えさせてください。

単純なのは現在のエディタ用のNSTextViewサブクラスのメソッドを流用できそうですが

> （バックスラッシュでエスケープされた括弧や [] 内の括弧は無視されるのが理想）

はネックですね。ただ、それが理想なのはその通りなので善処します。

**Comment by 1024jp** [comment]
ひとまずカーソル移動したときにペアをハイライトする奴は実装した。

> バックスラッシュでエスケープされた括弧や [] 内の括弧は無視

も実装。

**Comment by 1024jp** [comment]
しかし括弧ペアの入れ子関係が正規表現的に正しいことを期待してハイライトしてるので、
編集中とか間違ってるときは正しいヤツが探せない。まぁこれはもうしょうがないと思うが。

**Comment by 1024jp** [comment]
> 2. 括弧文字をダブルクリックしたとき、括弧全体のまとまりを選択

こっちも実装。

**Comment by zumuya** [comment]
対応ありがとうございます。
Change Log にある "when a brace was clicked" というのは double-clicked の間違いではないですか？

**Comment by 1024jp** [comment]
@zumuya 
> Change Log にある "when a brace was clicked" というのは double-clicked の間違いではないですか？

おっと、ありがとうございます。その通りです。直します。

**Comment by 1024jp** [comment]
要望の実装は終わったのでクローズします。

なお、わりと軌道に乗ってきたので、シンタックスハイライトするところまで CotEditor 3.4.0 に積むつもりです。

![screen shot 2018-04-05 at 10 36 54](https://user-images.githubusercontent.com/1165044/38343163-4c3ef810-38bd-11e8-894d-d842f8bc5891.png)
