### ISSUE TITLE
Feature request for outline feature 3.4.0

### ISSUE THREAD

**Issue by tatsy-ymj** [coteditor/CotEditor#808]
Outline feature of 3.4.0 is marvelous!
I have a request about this feature, which is synchronization with a main window and a side-bar.

Auto-extracted document outline of main window synchronizes with body text ( A heading is checked). I hope the same specification with side-bar (with check mark, in bold etc.).

**Comment by 1024jp** [comment]
Thank you for the feedback.
I’ll implement it to the next beta.
