### ISSUE TITLE
Can't delete a replacement term when there is just one term(3.4.0)

### ISSUE THREAD

**Issue by tatsy-ymj** [coteditor/CotEditor#809]
## Environment (環境)

- CotEditor: 3.4.0-beta (241)
- System: macOS バージョン10.13.4（ビルド17E199）
- Language: Japanese

## Short Description (簡単な説明)

Can't delete a term when there is just one term.

## Steps to Reproduce the Issue (不具合が発生したときに行っていた操作、または再現手順)

- Show "Replacement Set"
- When there is just one term, it can't be deleted. A "-" button doesn't appear.
- [screenshot](https://www.dropbox.com/s/61fjxfrdzb8181p/)

**Comment by 1024jp** [comment]
This is in spec because a replacement set with zero term definition doesn’t make sense.
