### ISSUE TITLE
A subtle difference of outline feature between main window and sidebar

### ISSUE THREAD

**Issue by tatsy-ymj** [coteditor/CotEditor#810]
There is a subtle diffrence of outline feature (3.4.0beta) between main window and sidebar.
Several horizontal lines of Markdown is displayed differently.

- [screenshot](https://www.dropbox.com/s/5b7gpejxcqtxxbf/)

**Comment by 1024jp** [comment]
Thank you for your active feedback on the beta.

It seems that the popup menu in the navigation bar automatically merges multiple separators next to each other into a single separator, and there is no way to change this behavior.
Thus, to match the handling of separators between the navigation bar and sidebar inspector, I may need to merge multiple separators in the sidebar inspector, just like the popup menu does.

**Comment by 1024jp** [comment]
I've changed my mind and tweaked the outline menu in the navigation bar.

<img width="983" alt="screen shot 2018-04-14 at 4 39 42 pm" src="https://user-images.githubusercontent.com/1165044/38765762-782d34ea-4002-11e8-9230-7af50bf43ff1.png">
