### ISSUE TITLE
[Feature request] Add the option that "When using monospaced font, make width of full-width characters is 2 times width of half-width characters"

### ISSUE THREAD

**Issue by abc1236762** [coteditor/CotEditor#812]
Add the option that can setting width of half-width and full-width characters.

For example, width of half-width and full-width characters in many monospaced font are 0.6 and 1.0, so if my text has both half-width and full-width character, they cannot align with each other. Then I can set width of half-width characters to 0.6 and full-width characters to 1.2 to fix width of characters in monospaced font and let every characters can align with each other.

In font Fira Code, width of '我' is 1.0, and width of 'a' is 0.6, so width of '我' * 6 is equal to 'a' * 10.
![default](https://user-images.githubusercontent.com/11353779/39409707-6f5fce40-4c1e-11e8-8211-f1a7d1c21956.png)
But I think if width of '我' is 2 time width of 'a' is better, like Noto Sans Mono CJK. Every '我' can align with 'aa'. But monospaced font that can do this are too few.
![default](https://user-images.githubusercontent.com/11353779/39409745-26a356e4-4c1f-11e8-8bf2-4039bf3aaa38.png)

Or add the option that is "When using monospaced font, make width of full-width characters is 2 times width of half-width characters". Many terminal also make this feature like zsh on iTerm2 that I am using. I use Fira Code in it.
![default](https://user-images.githubusercontent.com/11353779/39409822-45bf5608-4c20-11e8-8842-bf2b1d641328.png)

**Comment by 1024jp** [comment]
This kind of behaviors should be solved not by the text editor level but the font level.
Use a font full-width those full-width letters are also monospaced (or double-spaced).
