### ISSUE TITLE
Some VS themes that I made

### ISSUE THREAD

**Issue by abc1236762** [coteditor/CotEditor#813]
I made some some VS themes for CotEditor, includes VS2017 dark and VSCode dark.
[Visual Studio dark theme.zip](https://github.com/coteditor/CotEditor/files/1960752/Visual.Studio.dark.theme.zip)

But comparing with real VS2017 dark and VSCode dark coloring scheme, there are still with some slight difference.

And I request add the feature that can set not only color, but also bold, italic, and underline in each theme.

**Comment by 1024jp** [comment]
I've separately created a new issue for your request at #814 to manage issues easily.

**Comment by 1024jp** [comment]
I added your theme to [our wiki page](https://github.com/coteditor/CotEditor/wiki/Additional-Themes).
Thanks.
