### ISSUE TITLE
Highlight other usages of selection

### ISSUE THREAD

**Issue by ethemcemozkan** [coteditor/CotEditor#815]
When user selects something in editor other usages of that selected part can be highlighted too. This can be usefull especially when user works with source code files. For example user selects variable and can detect where it is used instantly.

**Comment by 1024jp** [comment]
Yes, I also like this feature in Xcode. It seems not so hard to implement. I'll consider.

**Comment by 1024jp** [comment]
This feature has been finished implementing and will be shipped with CotEditor 3.5.0 which will be released in this summer.
