### ISSUE TITLE
How to change the UI language?

### ISSUE THREAD

**Issue by bndnico** [coteditor/CotEditor#824]
It seems that CotEditor uses the system language (in my case German) for its UI by default. I'd like to change that to English, because the translation is more confusing than helpful. How can I do that? I did not find it in the settings dialog (but I may just have missed it).

**Comment by 1024jp** [comment]
As you thought, CotEditor uses the system language just as other ordinary Cocoa applications do. CotEditor also doesn't provide any option to change the UI language. Please use an external app like [Language Switcher](http://www.tj-hd.co.uk/en-gb/languageswitcher/) (but I'm not sure it works on the lastest systems).

And if you feel the translation is awful, please feel free to point out and suggest us better ones. It may help also other people.
