### ISSUE TITLE
scrolling should pick a direction (either vertical or horizontal, but not both)

### ISSUE THREAD

**Issue by alvint** [coteditor/CotEditor#825]
## Environment
- CotEditor: 3.4.2 (257)
- System: macOS Version 10.13.5 (Build 17F77)
- Language: English
- Other: using a trackpad to scroll and not a mouse wheel

## Short Description
When trying to scroll vertically with word wrap turned off, the document will "drift" from side to side because it's difficult to move a trackpad/mouse with a scroll area completely straight. Please do what most macOS apps do and either move vertically or horizontally depending on the predominate scroll direction. It wouldn't surprise me if the OS already has a mechanism to do this--it sounds like an Apple-ly thing to do.

## Steps to Reproduce the Issue
- Open a large file.
- Turn off word wrap.
- Try to scroll vertically with a trackpad. You can't help drifting from side to side.

## Expected Result
Scrolling should be along one axis only.

**Comment by 1024jp** [comment]
Thank you for the suggestion.
What you pointed out is exactly the right thing.
I've just changed the editor's scrolling behavior.
This change will be shipped with CotEditor 3.5.0, that will be released in this summer.
