### ISSUE TITLE
either row number should start at 0 or column number should start at 1 (or add an option)

### ISSUE THREAD

**Issue by alvint** [coteditor/CotEditor#826]
- CotEditor: 3.4.2 (257)
- System: macOS Version 10.13.5 (Build 17F77)
- Language: English

I imagine that there's no way this hasn't been brought up before, so I assume someone there must genuinely, truly believe that column numbering must begin at 0. If that's the case it seems to me to make better sense that the line number should also start at 0 to be consistent. Please make both column number and line number start at 0, or 1, or better yet add an option for it.

**Comment by playerofgames** [comment]
It doesn't strike me as inconsistent. The cursor is on line 1, but not beyond any character, so at column zero.It is the cursor coordinate definition.

**Comment by alvint** [comment]
@playerofgames Using your own logic, the cursor is not beyond any line, so it should be line 0.

**Comment by 1024jp** [comment]
<img width="420" alt="screen shot 2018-12-12 at 19 30 14" src="https://user-images.githubusercontent.com/1165044/49863808-73de9b80-fe44-11e8-97b1-682807cee842.png">

Counting line number from 1 is almost de facto standard. In addition, as @playerofgames pointed out, the cursor locates between characters. Therefore, the first column, which is the location of the cursor before the first character, is 0.
This is enough understandable (at least for me), and therefore I will not change the current behavior.

**Comment by alvint** [comment]
@1024jp: It's your app so it's your call, but even your illustration above shows that when you type a character, it gets inserted at line 1, column 1. That is the information that most text editors are trying to show--where the next character will be inserted. Also, the cursor does **not** locate between characters; it just appears that way when using a vertical line cursor. Drawing the cursor as a block or a horizontal line (which are functionally identical) shows the cursor occupying the actual column.

The most I can say is that 99% of creators of other text editors don't agree with your logic, so even if you don't want to change the default it should at least be an option.

**Comment by 1024jp** [comment]
Ok, good.
As you pointed out, it seems most text editors start location with 1.
Then CotEditor should follow that.

Honestly, I personally don't care so much if the location starts with 0 or 1, and just adopted the original behavior so far (I'm not the original developer but the third maintainer).
I'll change in the next version (3.6.10).
Thank you for the detailed explanation.
