### ISSUE TITLE
make the "Count each line ending as one character" option less confusing (and improve on it)

### ISSUE THREAD

**Issue by alvint** [coteditor/CotEditor#828]
This issue is closely related to issue #827.

- CotEditor: 3.4.2 (257)
- System: macOS Version 10.13.5 (Build 17F77)
- Language: English

The "Count each line ending as one character" option is confusing as it's currently worded. Since many people are aware that Windows line endings are two characters, the immediate assumption for most of them is that this option counts such line endings as one character.

This brings up another issue: there should be three character count options to account for files with CRLF line endings--0, 1, or 2. How about changing the option to something like this?

```
[x] Include line endings in character count
    [x] Count Windows line endings as 1 character
```

The second option should be disabled if the first option is not checked.

**Comment by 1024jp** [comment]
I agree that the label for that option leads to misunderstanding.
However as I replied in #827, I don't wanna easily introduce a new option.

So, removing the current unclearness of the option description, I'll change the label to something like "Ignore line endings by counting character" (namely, reversing the on/off state).
How do you think?

**Comment by alvint** [comment]
@1024jp: Yep that's much clearer.

**Comment by 1024jp** [comment]
Thanks. I've just changed.
