### ISSUE TITLE
Potential bug—Pasting text can take a few seconds if “Link URLs in document” is turned on

### ISSUE THREAD

**Issue by handcoding** [coteditor/CotEditor#831]
It would seem that pasting any amount of text into a large-ish document can take several seconds if CotEditor’s “Link URLs in document” option is turned on. 

Here are steps that you can use to reproduce.
1. In CotEditor, under Preferences → General, enable “Link URLs in document”
2. Open the attached text file in CotEditor: 
[Pride and Prejudice by Jane Austen.txt](https://github.com/coteditor/CotEditor/files/2178319/Pride.and.Prejudice.by.Jane.Austen.txt)
3. Copy any single word to your clipboard, such as any of these: `Jane` or `Austen` or `EBook`
4. Switch to CotEditor and paste that word anywhere into the document.

* Actual results: CotEditor takes several seconds to paste the word
* Expected results: CotEditor pastes the word right away

This bug seems to be most apparent in large-ish files. And [_Pride and Prejudice_ by Jane Austen](http://www.gutenberg.org/ebooks/1342) is 708 KB, which is large enough to make this bug visible. 

And for what it’s worth, in Step 3, I recommended copying a single word just to emphasize that this bug doesn’t have anything to do with the amount of text that’s being pasted. But as you might guess, this bug also happens when pasting text of any size.

P.S. Just for completeness: I’m running CotEditor 3.4.4 (261) on macOS 10.13.5 on a 15″ MacBook Pro.

**Comment by 1024jp** [comment]
Sorry for my late reply.

I confirmed your issue also under my environment and have just improved the code.
It would be still not perfect but much better than the current uncomfortable lag.

**Comment by handcoding** [comment]
@1024jp Thanks so much!
