### ISSUE TITLE
Needs optimization on macOS Mojave (esp. its dark mode.)

### ISSUE THREAD

**Issue by ShikiSuen** [coteditor/CotEditor#832]
macOS Mojave supports a more-complete dark mode but requires support from developers of their apps. From the following screenshot you could see that the Finder supports dark mode (completely dark) but CotEditor 3.4.4 (261) doesn't (I only chose a dark theme, but the main window is still bright).
<img width="925" alt="image" src="https://user-images.githubusercontent.com/3164826/43352326-8d4245ce-9254-11e8-9dab-18ced077deea.png">

**Comment by 1024jp** [comment]
Finish implementation (expect tiny issues I still working on).
