### ISSUE TITLE
Request for More Syntaxes: LESS, SASS, Stylus, HAML & Pug

### ISSUE THREAD

**Issue by luxlogica** [coteditor/CotEditor#836]
Thank you for such great work in providing syntax highlighting and autocompletion for over  **50 different syntaxes** - wow!!!

I imagine you must already be pretty busy working on new features and updates, but if there are any plans to expand the list of supported syntaxes, would I please be able to put in a request for the pre-processor languages, that are so useful in Web Development? There are:

### CSS Preprocessing Languages
   * [LESS](http://lesscss.org)
   * [SASS](https://sass-lang.com)
   * [Stylus](http://stylus-lang.com)

### HTML Preprocessing Languages
   * [Pug](https://pugjs.org)
   * [HAML](http://haml.info)

**Comment by 1024jp** [comment]
Thank you for the request.

However, CotEditor will have built-in syntax styles for the languages that are relatively standard, but not subsets. Such styles should be created and maintained by somebody else, outside of the project.
If you guys create your own, you can put them on the list [here](https://github.com/coteditor/CotEditor/wiki/Additional-Syntax-Styles) to let others use.

**Comment by alvint** [comment]
For LESS and SASS at least, I'm not sure I agree with the rationale. You already have syntaxes for niche transpiled languages, and the percentage of JavaScript users who transpile from CoffeeScript has got to be far smaller than the percentage of CSS users who transpile from LESS or SASS. Both of those languages are pretty standard these days.
