### ISSUE TITLE
Hard to cancel syntax highlighting by large file / サイズの大きいファイルを開くとテキストのカラーリングがキャンセルできない

### ISSUE THREAD

**Issue by wp-wakahara** [coteditor/CotEditor#837]
10MBぐらいのサイズの大きいファイルを開き、テキストのカラーリングをしばらく待っていると、CotEditorのアプリケーション内にカーソルが入るとポインタがローディングのものになりキャンセルボタンが効かなくなり、何もできなくなる。
キャンセルはできるように修正していただきたいです。

CotEditor 3.5.0(268)

PC環境
MacBook Pro (Retina 13-inch、Early 2015)
El Capitan 10.11.6

**Comment by 1024jp** [comment]
各処理の最適化については普段から諸々取り組んでおりますが、本件に関しては、現状「仕様です」としかいえない状況です。
こちらとしても課題であるとは考えている箇所ではあるのですが、CotEditorが依存しているTextKitの技術的な制約ですぐに「修正する」とはいかない箇所です。

---
### 技術的解説

SyntaxParser の `apply(highlights:range:)` 内でハイライト色をtemporaryAttributesとして適用しているが、これがmain threadでやらざるを得ず、ハイライト箇所が増えるにつれ負担となる。

**Comment by 1024jp** [comment]
シンタックスハイライトのパフォーマンスおよびキャンセルしやすさについて、3.6.8および3.6.9で改良を加えました。
