### ISSUE TITLE
CotEditor crashed while typing

### ISSUE THREAD

**Issue by Ktakuya332C** [coteditor/CotEditor#838]
## Environment

- CotEditor: 3.5.0 (268)
- System: macOS Version 10.13.6 (Build 17G65)
- Language: English

## Short Description

CotEditor crashed while typing.

## Steps to reproduce the issue

I tried to reproduce the crash intentionally but was hard to find out specifically which action caused the crash.

## Other info
* [crash_log](https://github.com/coteditor/CotEditor/files/2299117/crash_log.txt)

* I often encounter the issue (1-2 times when typing a short (~100 lines) script.)
* The crash occurred while typing a script in Go language this time but also occurred when typing in Python previously.

**Comment by Snazzyham** [comment]
Had the same issue with a relatively small html file today

**Comment by 1024jp** [comment]
I've just released CotEditor 3.5.1 which includes a measure of this issue.
Please let me know if the crash still exists on the latest one.

**Comment by Ktakuya332C** [comment]
@1024jp Thank you very much! Even though I may not be able to confirm that the bug has really been fixed because the cause itself could not be identified, I'll continue to use the editor to see whether the bug will occur. 
If I would encounter the bug again, I'll raise another issue.

**Comment by 1024jp** [comment]
Observing the latest crash logs I received since CotEditor 3.5.3, this issue seems fixed in the last versions.
Please raise another issue if you encounter a crash.
