### ISSUE TITLE
Multi Replace feature exports replacement definitions without file extension

### ISSUE THREAD

**Issue by tsmsogn** [coteditor/CotEditor#841]
## Environment

CotEditor: 3.5.1 (271)
System: macOS Sierra 10.12.6 (16G1212)

## Actual

Multi Replace feature exports replacement definitions without file extension.

## Expected

It exports replacement definitions with `.cotrpl` file extension.

**Comment by 1024jp** [comment]
Thank you for the bug report and sorry for the bug.

This is definitely a bug.
I'll fix this in the next CotEditor that will be released in this weekend.

**Comment by tsmsogn** [comment]
@1024jp Thank you for your reply. I'm looking forward to new version.
