### ISSUE TITLE
直前が半角文字だと全角スペースが半角スペースとして入力される

### ISSUE THREAD

**Issue by hiromoto-t** [coteditor/CotEditor#842]
英数記号や半角スペース等の半角文字の後ろに全角スペースを入力すると、半角スペースが入力されます。改行するか、全角スペース以外の全角文字を入力するまでこの状態が続きます。
半角文字の後でも全角スペースが入力できるように修正お願いします。

エンコーディングは UTF-8, UTF-8BOM, Shift-JIS, EUC, Windows-DOS, Shift-JIS X0213, 日本語(Mac OS), 日本語(ISO 2022-JP) のいずれでも同じく発生します。

CotEditor 3.5.2
macOS 10.13.6
ことえり

**Comment by 1024jp** [comment]
本件、macOS 標準の日本語入力（旧ことえり）の仕様かと思います。
CotEditor 以外のアプリケーションでも同様の挙動になるかと思いますが、がいかがでしょうか？

**Comment by hiromoto-t** [comment]
確かに他のエディタ(テキストエディット、MS-WORD、VSCode）でも同じ挙動でした。
CotEditorアップデートとGoogle日本語入力からmacOS標準の日本語入力に切り替えたので混同していたようです。

macOS標準の日本語入力の仕様ということで、クローズいたします。
