### ISSUE TITLE
Replace in Find and Replace stopped working after the latest update

### ISSUE THREAD

**Issue by kre2018** [coteditor/CotEditor#843]
## Environment

- CotEditor: 3.5.2 (273)
- System: macOS Version 10.13.6 (Build 17G65)
- Language: English

## Short Description

After the latest update Find and Replace stopped working

## Steps to Reproduce the Issue

Use any RegEx expression for example \.0 and leave the replacement box empty.

## Expected Result

I am expecting all occurences in the text of a decimal point (.0) to be erased.
They are found but not deleted.

**Comment by 1024jp** [comment]
The issue was already fixed in 3.5.3.
