### ISSUE TITLE
Request : add ability to make app start by default writing direction right to left

### ISSUE THREAD

**Issue by tripletroop** [coteditor/CotEditor#844]
Hello,
I love your application and always se it to edit some Arabic files so every time i start a file i have to set the writing direction to right to left
It would be great if you can add ability to app's settings to set default writing directions

**Comment by 1024jp** [comment]
Thank you for the request.
I'll implement this to the next CotEditor (3.6.0) as it seems reasonable enough and useful also for other users.

**Comment by 1024jp** [comment]
Implemented to CotEditor 3.6.0.

<img width="672" alt="screen shot 2018-09-16 at 1 50 19 am" src="https://user-images.githubusercontent.com/1165044/45588652-e11c8680-b952-11e8-8788-11de3a41b6b3.png">

**Comment by tripletroop** [comment]
thank you for your quick support.
