### ISSUE TITLE
cot invoked from command line with --wait should return focus to terminal on close

### ISSUE THREAD

**Issue by vassudanagunta** [coteditor/CotEditor#845]
When CotEditor configured as the editor for git using `editor = cot --wait`, closing the file should also return focus to the invoking progrem (i.e. Terminal). Right now the focus remains with CotEditor, so that when one resumes typing to continue working in Terminal, one gets the macOS warning sounds that there is no application with focus to accept the keyboard events. One is forced to use the mouse or CMD-TAB to give Terminal focus before typing the next command.

(I love CotEditor btw. Thank ou!)

**Comment by vassudanagunta** [comment]
Grazie mille!

**Comment by vassudanagunta** [comment]
ok cool. I wonder how editors implement it. I pretty certain that when I was using BBEdit and TextEdit as the editor, focus returned to the command line, because my muscle memory got surprised by the change in behavior when I switched to CotEditor.  I think Sublime Text is the most popular GUI editor... but I don't have it so can't compare.

Is there a way to get notified of beta releases? I'm happy to be a beta tester.

**Comment by vassudanagunta** [comment]
@1024jp I got the beta and it works perfectly now. Thank you!

**Comment by 1024jp** [comment]
@vassudanagunta
Thank you for the testing and feedback!
Feel free to let me know if you encounter any issue.
