### ISSUE TITLE
Window size preference can be ignored / cot コマンドで複数のファイルを一度に開く場合に、ウィンドウサイズが踏襲されない

### ISSUE THREAD

**Issue by charonferry** [coteditor/CotEditor#850]
$ cot \<file1\> \<file2\> [...]
  OR 
$ (COMMAND) | xargs cot

cot コマンドで複数のファイルを一度に開く時、2つ目以降のウィンドウサイズが
不定なサイズ (アプリの初期値?) で表示される。
2つ目以降のウィンドウも1つ目と同じサイズで表示してほしい。

環境
- CotEditor 3.6.0 (286)
- macOS Mojave 10.14 (18A391)

補記
以前の環境 (CotEditor 3.5.3 + macOS High Sierra 10.13.x) では、すべてのウィンドウが
1つ目と同サイズで表示されていたはず。

**Comment by charonferry** [comment]
$ cot \<file1\>
$ cot \<file2\>

1. 最初のコマンドで \<file1\> ウィンドウが表示される
2. 1. を開いたままにする (アプリケーションを終了しない)
3. 次のコマンドで \<file2\> が不定なサイズで表示される

**Comment by 1024jp** [comment]
CotEditor 3.5.0以来、ウインドウサイズの保存をCocoaのフレームワークに任せてみているのですが、なかなか不安定ですね。`cot`コマンド以外でも過去のサイズが無視されることがありそうで。いずれにせよ調整します。

**Comment by charonferry** [comment]
> cot コマンド以外でも過去のサイズが無視されることがありそうで。

1. アプリケーションを起動する
2. 期待するポジション、サイズで新規ウィンドウが表示される
3. メニュー [ファイル] - [新規 ⌘N] をクリックする
4. 不定なサイズ、期待しないポジション (2\. の右下) でウィンドウが表示される

追記
重複投稿になりすみませんでした。

**Comment by 1024jp** [comment]
次にリリースする3.6.1で対策をしました。
だいぶ状況がましになるはずです。

もしまだ漏れがありましたら新しいIssueを立ててください。
