### ISSUE TITLE
Open a file by drag & drop.

### ISSUE THREAD

**Issue by Yanchi4425** [coteditor/CotEditor#851]
I want open a file by drag & drop.
Do not input a path.

Is there such a setting?

**Comment by 1024jp** [comment]
No, there is no such setting or feature, currently.
Because, in the macOS world, dropping files to the application icon in the Dock is the standard way to open files in a specific app.

**Comment by Yanchi4425** [comment]
OK.
Some Mac text editors can do it, please implement it if you like it.

**Comment by 1024jp** [comment]
> Some Mac text editors can do it, please implement it if you like it.

Actually, I receive this request sometimes.
So, I understand some users love it. I'll consider.
