### ISSUE TITLE
Strange scroll after paste with auto URL link option / ペースト直後にカーソルキーで移動すると画面が勝手にスクロールする 

### ISSUE THREAD

**Issue by minami-manbou** [coteditor/CotEditor#856]
## Environment (環境)

- CotEditor: 3.6.1 (288)
- System: macOS バージョン10.13.6（ビルド17G65）
- Language: Japanese

## Short Description (簡単な説明)

ペースト直後にカーソルキーで移動すると画面が勝手にスクロールする

## Steps to Reproduce the Issue (不具合が発生したときに行っていた操作、または再現手順)

設定
　書類中のURLをリンクをチェック

発生時のファイル

　ファイル中にURLが複数（18個）
　329行 22375文字

ファイルの最後のほうで任意の文字列をペーストし直後にカーソルキーで移動すると
画面が勝手にスクロールする

## Expected Result (期待される挙動)

スクロールしない

**Comment by 1024jp** [comment]
不具合確認しました。
確かにこれは修正すべきですね。
報告ありがとうございます。次回のパッチアップデートで修正できるかと思います。
