### ISSUE TITLE
Keyboard shortcuts for switching tabs are non-standard

### ISSUE THREAD

**Issue by ghurley** [coteditor/CotEditor#858]
In Mac programs, the standard keyboard shortcuts for switching between tabs are Cmd+Shift+[ (for previous tab) and Cmd+Shift+] (for next tab). This is true for Safari, Chrome, Terminal, TextEdit etc. In CotEditor they seem to be mapped to the standard keyboard shortcuts that one would use on Windows (namely Ctrl+TAB and Ctrl+Shift+TAB).

Also, it's not possible to override those keyboard shortcuts in the keybindings portion of preferences. I'm assuming this is because the defaults don't include the Cmd key.

**Comment by alvint** [comment]
Hi @1024jp, I just did a quick test on a fairly stock install of Mojave, and it appears that virtually all Apple apps with a tab-like interface do support these shortcuts, including Safari, Terminal, Maps, Messages, and iTunes. Third-party apps also tend to support this including big players like Chrome, WhatsApp, and iTerm. Text editors also tend to support some form of this including Brackets, which doesn't even have tabs.

Even if the HIG doesn't specify that this shortcut is required, would it hurt anything to include it? It seems to be the de facto standard.

**Comment by 1024jp** [comment]
@alvint Thank you for the confirming. However, what strange for me is, I actually don't set those keyboard shortcuts in CotEditor project but the system automatically adds them. Furthermore, under my Mojave environment, those applications (Safari, Terminal, etc...) also use Ctrl+TAB for the tab switching. Maybe, some system-wide user setting or 3rd party app affects those shortcut. Do you use Karabiner, BetterTouchTool, or some similar kind of tool?

> Even if the HIG doesn't specify that this shortcut is required, would it hurt anything to include it? It seems to be the de facto standard.

If this is really so, I would like to. But it seems I need first to figure out this incomprehensible phenomenon.

**Comment by 1024jp** [comment]
cf. [Keyboard shortcuts for Terminal on Mac](https://support.apple.com/en-in/guide/terminal/keyboard-shortcuts-trmlshtcts/mac)

**Comment by 1024jp** [comment]
Aha, ok, I got it. While the default shortcuts for tab switching are Ctrl+TAB and Ctrl+Shift+TAB, the apps accept also Cmd+Shift+[ and Cmd+Shift+], right? And regard CotEditor, Cmd+Shift+[ can not be used for tab switching because the shortcut is assigned for "Surround Selection with Brackets {}".

Well, then, I need to prioritize tab switching than the current command for Cmd+Shift+[. I'll change it in the next version. Thanks.
