### ISSUE TITLE
[feature request] Add command for "select word"

### ISSUE THREAD

**Issue by ghurley** [coteditor/CotEditor#865]
Some text editors (e.g. VSCode, Atom, TextMate, Sublime) have a command to select the current word that the cursor is on. It's be great if CotEditor had the same command. For what it's worth, most of the editors above (with the exception being TextMate) bind it to Cmd-D and subsequent invocations of the command will each select the next instance of that word in the document. This may not work in CotEditor since it seems to rely on being able to have multiple cursors or multiple, non-contiguous selections but even the single instance would be useful.

**Comment by 1024jp** [comment]
Thank you for the feedback. I've also considered adding such kind of commands to the menu. I'll implement it to the next version.
