### ISSUE TITLE
Option for thicker cursor / カーソルを見やすく（太いカーソル、四角の

### ISSUE THREAD

**Issue by sue44** [coteditor/CotEditor#867]

**Comment by 1024jp** [comment]
実装しました。次バージョンで対応します。

---

Finished the implementation.

<img width="575" alt="screen shot 2018-11-11 at 2 47 50 pm" src="https://user-images.githubusercontent.com/1165044/48314943-e5dc7e80-e613-11e8-9f6c-c4b7e396e05a.png">

**Comment by sue44** [comment]
ありがとうございます！大変助かります。
（コメントの入力時にミスがあり失礼しました）
