### ISSUE TITLE
Editing plist files directly in CotEditor

### ISSUE THREAD

**Issue by GHubbler** [coteditor/CotEditor#868]
According to https://github.com/coteditor/CotEditor/issues/335 I would like to bring this up again because we are now a couple of years later and maybe I can convince you now. ;)

CotEditor becomes a great programmers editor. Like so, editing plist files is not just a nice possibility but mostly a need for serious tasks.
I would like to ask you, if you meanwhile can imagine implementing the simple conversion process from plist to editable xml on opening and back to plist while saving. Most easily it might be done by invoking the command line tool which comes natively with macOS.
If there is a way to include this with a scripting extension it should be also fine.
What do think?
Many thanks.

**Comment by 1024jp** [comment]
Really sorry, but I still believe it is beyond CotEditor's tasks.
I do not like to let CotEditor do an extra task only for a specific file format.

**Comment by GHubbler** [comment]
Never mind. Still a very good editor. ;)
