### ISSUE TITLE
Right-click no longer opens the context menu (CotEditor 3.6.6)

### ISSUE THREAD

**Issue by handcoding** [coteditor/CotEditor#873]
I′ve just updated to CotEditor 3.6.6 (299), and it would appear that right-clicking within a document no longer opens the context menu.

(If it might make any difference, I’m running the non-Mac-App-Store version of CotEditor, and I’m on macOS High Sierra 10.13.6.)

**Comment by alvint** [comment]
If it helps, the same setup works on Mohave.

**Comment by 1024jp** [comment]
I've just reproduced this issue under my macOS 10.12. 
Then, it becomes much easier to fix. Thank you.

**Comment by 1024jp** [comment]
Fixed in 855aee86c84bdd55db0edbb27b26f27b1173cc11 and 746ef4daf6c1251e3f6f0b5f6349a70763ea39d5.
