### ISSUE TITLE
Request: find/replace performance 

### ISSUE THREAD

**Issue by lojza3d** [coteditor/CotEditor#876]
Due to its decline, I've left TextWrangler in favour of CotEditor. It seems pretty slick, but there are - in my opinion - some serious performance issues. I've made a screen recording with two simple use cases, TextWrangler (latest legacy version) and CotEditor ver. 3.6.7 (301) side by side. Here is the result:

https://youtu.be/-YFTH-DXnvc

Use Case 1: pasting 383 lines of text from an Excel table - TextWrangler instantly, CotEditor shows "rainbow ball" three times and suffers from some graphic glitches while redrawing (white rectangle over text).

Use Case 2: Find/replace of 17235 tabs for semicolons: TextWrangler instantly, CotEditor needs 40 seconds.

Is there any space for optimization? Namely the find/replace functionality would deserve some. I'm using MacBook Pro 13'' Early 2015, 3,1 GHz Intel Core i7, 16 GB 1867 MHz DDR3 with Apple Thunderbolt Display 27'' (2560 x 1440) attached and running macOS Mojave 10.14.1.

Thanks for a great editor, anyway!

**Comment by 1024jp** [comment]
Oops, I reopened this because I have only addressed the second use case yet.

**Comment by 1024jp** [comment]
Following your request, I examined the source code around "Replace All" again and tried removing current major bottlenecks I found.
As a result, the performance of "Replace All" with a large number of occurrence improved a lot 😉.
Under my environment (MacBook Pro 2016), replacing about 71,000 of `,` with `\t` takes:
- CotEditor 3.6.7 (current version): 23 seconds
- CotEditor 3.6.8 (next version): 2.8 seconds

Thank you for pointing out.

Regarding the first use case, there might be other bottlenecks. I suppose this one is actually hard to improve. But not tried yet. I'll look into it later.

**Comment by 1024jp** [comment]
Hi @lojza3d,

I tried reproducing your use case 1 with CotEditor 3.6.7 + macOS 10.14.1 but couldn't. The text was pasted instantly without any glitch.
If possible, could you give me a file that this issue can be reproduced (in your environment, at least)?
The screenshots of your preferences window (especially General and Edit panes) would also be helpful.

**Comment by lojza3d** [comment]
Hi @1024jp, no problem. Screenshots are here:
<img width="560" alt="screenshot_1213" src="https://user-images.githubusercontent.com/19929447/49361080-550d3600-f6db-11e8-8856-63015f2d1974.png">
<img width="560" alt="screenshot_1214" src="https://user-images.githubusercontent.com/19929447/49361085-56d6f980-f6db-11e8-8143-d2450de70649.png">
<img width="560" alt="screenshot_1215" src="https://user-images.githubusercontent.com/19929447/49361087-58082680-f6db-11e8-86bb-482c2dfa9a84.png">
<img width="560" alt="screenshot_1216" src="https://user-images.githubusercontent.com/19929447/49361091-5a6a8080-f6db-11e8-95dd-d0335d9a1972.png">
<img width="560" alt="screenshot_1217" src="https://user-images.githubusercontent.com/19929447/49361093-5cccda80-f6db-11e8-93af-a886c8e8375f.png">

**Comment by lojza3d** [comment]
I'll send the source Excel file via a private message.

**Comment by 1024jp** [comment]
@lojza3d I've received the file. Thanks.

**Comment by 1024jp** [comment]
Thanks to the additional information provided by lojza3d, I've succeeded reproducing this issue.
It seems this behaviour occurs only when the lines are __not__ wrapped.
I continue researching how to avoid.

**Comment by 1024jp** [comment]
Ok, I found the cause of the use case 1.
This is a side-effect of the Cocoa's feature called "noncontiguous layout".
Therefore, actually, CotEditor's code has nothing to do.

However, since I feel the noncontiguous layout has too many negative side-effects besides its drawing efficiency with a large text, now I'm planning to disable it when the document is enough small.
This may solve unwanted scrollbar jump as well as the issue of the use case 1.
