### ISSUE TITLE
Behavior of "Jump to beginning of line"

### ISSUE THREAD

**Issue by tatsy-ymj** [coteditor/CotEditor#878]
I found an odd behavior of "Jump to beginning of line" on a recent version (3.6.7) of CotEditor.

1. Set a cursor in the middle of a line ("A").
https://www.dropbox.com/s/jb50g4ei5q11exa/coteditor_cursor_1.png

2. Execute "Jump to beginning of line" (ctrl+A or command + left)

3. Althogh the position of the cursor is expected to move to "B", it moved to "C".
https://www.dropbox.com/s/3x79rebegkjqcwg/coteditor_cursor_2.png

4. On "TextEdit" of macOS, the cursor moves to "B".

Could you fix it?

**Comment by 1024jp** [comment]
Oops, thank you for pointing out.
I've just fixed it.
