### ISSUE TITLE
Do not show suggestions when holding a letter

### ISSUE THREAD

**Issue by adamjanovsky** [coteditor/CotEditor#880]
Hi,

I hope that the issue is not a duplicate. When I attempt to fill a line with single letter input, I tend to hold the random key accordingly. For instance, when I want to write 40x letter k, i simply hold the key k. What is quite annoying (in otherwise the most fitting text editor for mac os x personally) is that when holding a key, the editor only writes single letter and suggests alternations to the letter in a pop-up dialog window. For instance, diacritics is suggested etc. I failed to find any way how to modify such behaviour. Is there any? 

TY for answering

**Comment by 1024jp** [comment]
Hi.
This behavior is not controlled by CotEditor but the input method, although there is no GUI control to change the behavior. 

cf. https://discussions.apple.com/thread/7455939
