### ISSUE TITLE
New Syntax Style: TOML

### ISSUE THREAD

**Issue by Seklfreak** [coteditor/CotEditor#881]
I work a lot with `.toml` files, and it would be very useful to have Syntax Highlighting, and the ability to comment out code, in CotEditor. 

The documentation for the format TOML can be found here: https://github.com/toml-lang/toml .

Thank you very much for considering it.

**Comment by 1024jp** [comment]
Honestly, I heard the TOML format for the first time. But it seems worth to consider. I'll implement it to the next version.
