### ISSUE TITLE
日本語入力を行うと行番号の一部が消える / some of Line numbers disappear if Japanese text is about to be input

### ISSUE THREAD

**Issue by halringo** [coteditor/CotEditor#882]
## Environment (環境)

- CotEditor: 3.6.8 (303)
- System: macOS バージョン10.13.6（ビルド17G4015）
- Language: Japanese

## Short Description (簡単な説明)

- 日本語入力を行うと行番号の一部が消える。
- 改行を削除する場合でも発生する。

### 再現手順
1. 新規書類を作成する。
1. 10行程度改行を入力する。
1. 1行目にカーソルを移動し、日本語入力を行う。
1. **変換候補ウィンドウが表示されているときに行番号の一部が消える。**
1. 入力を確定して変換候補ウィンドウが消えれば行番号は元どおり表示される。

![japanese](https://user-images.githubusercontent.com/4532079/49689319-d264fa80-fb62-11e8-8467-8dc0a44ce038.png)

### 再現するときの状況
- 日本語入力(IM)はmacOS標準のものを使用している。
- ライブ変換を有効にしている。
- 1行目以外に入力しても発生する。
- 1文字目を入力したときから発生する。
- 日本語を入力している行から3行下の行番号から最後まで消える。
- 例えば1行目に入力していると、4行目から一番下まで消える。(4行目も消える)

### 改行の削除で行番号の一部が消える場合の再現手順
1. 新規書類を作成する。
1. 10行程度改行を入力する。
1. 3行目にカーソルを移動し、deleteキーを押して改行を削除する。
1. 5行目から一番下までの行番号が消える。

![delete](https://user-images.githubusercontent.com/4532079/49689328-f7f20400-fb62-11e8-815b-d02feb268718.png)

**Comment by 1024jp** [comment]
レポートありがとうございます。
macOS 10.14では起こらずmacOS 10.13で現象確認しました。
次バージョンで修正します。

**Comment by charonferry** [comment]
- macOS バージョン10.14.2 (18C54)
- CotEditor: 3.6.8 (303)

> 改行の削除で行番号の一部が消える場合の再現手順

こちらは再現できました。
