### ISSUE TITLE
全置換実行時にプログレス・ダイアログに表示される置換件数が、検索件数と食い違う件

### ISSUE THREAD

**Issue by wanik** [coteditor/CotEditor#884]
使用環境
- CotEditor: 3.6.9 (305)
- System: macOS Version 10.13.6 (Build 17G4015)
- Language: English

問題が生じているファイル
- Plain Text, LF, UTF-8

すべて置換を実行した際に、プログレス・ダイアログに置換件数が表示されますが、その数値が、すべてを検索した場合の検索結果の件数と食い違うということがあります。

実験では、英字7000字くらいまでですと問題ないようですが、7300字を超えるくらいのテキストだと、食い違いが生じます。

また、置換をアン・ドゥーで元に戻して再度置換すると、やり直すたびに、異なる置換件数が表示されるようです。

ご確認をよろしくお願い致します。

![cot_found](https://user-images.githubusercontent.com/34469683/50151316-e8618080-0303-11e9-964f-ea8984149ec9.jpg)

![cot_replace](https://user-images.githubusercontent.com/34469683/50151465-5017cb80-0304-11e9-8af8-acdfa044c52c.jpg)

**Comment by 1024jp** [comment]
バグ報告ありがとうございます。
先のバージョンでプログレスダイアログの更新タイミングを変更したときにケース漏れがあったようです。
次バージョン（1月頭リリース予定）で修正します。
それまでしばしお待ちください。
