### ISSUE TITLE
Live update of invisible characters visibility / 不可視文字のライブ切替え

### ISSUE THREAD

**Issue by charonferry** [coteditor/CotEditor#885]
### Environment (環境)

- CotEditor: 3.6.9 (305)
- System: macOS  Mojave 10.14.2（18C54）
- Language: Japanese

### Short Description (簡単な説明)

[不可視文字を表示]のチェックボックスが機能していない？

#### 設定
[x] 不可視文字を表示
[ ] スペース " "  [x] 改行コード "↵"
[x] タブ "▸" [x] 全角スペース "▫️"
[ ] 他の不可視文字

#### 再現方法
1. ファイルを開く
2. [環境設定] - [表示] を表示する
2. [不可視文字を表示] のチェックを外す
3. 設定画面の個別項目がグレーアウトする & ファイルは変化なし
4. 設定を戻す
5. [改行コード] のチェックを外す
6. プルダウンがグレーアウトする & ファイルからも改行が消える

p.s.
そもそも一度設定すると、変更することは稀なので急ぎません。

**Comment by 1024jp** [comment]
不可視文字全体のオンオフに関しては開いてる書類ごとに一時的な切り替えができるため、
あえて環境設定の変更には追従しないようにしており、つまり「これは仕様です」という回答となるのですが、
確かに分かりづらくもあるので、環境設定への変更にも追従するよう次バージョンで変更しようかと思います。

**Comment by charonferry** [comment]
仕様というには分かりづらいので、変更快諾いただきありがとうございます。
