### ISSUE TITLE
ステータスバーに "選択した単語" の件数を表示したい/表示できるようにしてほしい / Show the count of highlighted words on the status-bar

### ISSUE THREAD

**Issue by charonferry** [coteditor/CotEditor#888]
いつも愛用しております。

### 趣意
表題の通りですが、ステータスバーに表示可能でしょうか？
- "選択した単語" の「総数 (選択数)」を表示したい

### 具体的に
1. 単語を選択 (⌘+D)
(ステータスバー) 選択件数: 15 (1)
2. さらに単語を選択 (⌘+D)
(ステータスバー) 選択件数: 15 (2)

**Comment by 1024jp** [comment]
リクエストありがとうございます。

ニーズとしてはわからなくもないのですが、利用者が少なそうなことと、実装の関係上ステータスバーでのリアルタイム更新には向かないので却下させてください。

**Comment by charonferry** [comment]
承知しました。
返信ありがとうございます。
