### ISSUE TITLE
[beta] press Esc key to hope to exit the multi-cursors mode / ESCキー押下でマルチカーソルモードを抜けたい

### ISSUE THREAD

**Issue by charonferry** [coteditor/CotEditor#891]
待望のマルチカーソル対応ありがとうございます。

### Environment (環境)
- CotEditor 3.7.0-beta (321)
- macOS Mojave 10.14.2（18C54）
- Language: Japanese

### Short Description (簡単な説明)
SSIA; 表題の通り

**Comment by 1024jp** [comment]
早速のフィードバックありがとうございます。

CotEditorでのマルチカーソル実装は特に「モード」という概念を持っておらず、すべてのカーソルや選択範囲が平等に扱われるようになっています。
とはいえ、確かになんらかの操作で複数カーソルから1つだけに絞れた方が良いとも思うので、検討します。
ただ、上記の理由から、Escキーをそのアクションに当てることにはいくばくか抵抗があるのでショートカットキーの割り当てに関しては考えさせてください。

**Comment by charonferry** [comment]
キーボード操作で、マルチカーソル "状態" から抜け出す方法があれば望ましいと思った次第です。
修飾キーは組合せ次第ですが、直感的でない気もします。検討ください。

**Comment by charonferry** [comment]
ちなみにキー操作でマルチカーソル "状態" を抜けた後の、(シングル) カーソルも考慮ください。
- 最初のカーソル (これが普通かな？)
- 最後のカーソル
- 最上部のカーソル

**Comment by 1024jp** [comment]
あらためて色々なプレーンテキストエディタを観察してみましたが、Escキーでカーソルを1つに戻すのはわりと一般的なようですね。であれば実装しようかと思います。

抜けた後のカーソル位置ですが、唯一の正解はなさそうなのと、実装上、追加順序は保持していないので、最上部のカーソルにします。
