### ISSUE TITLE
[beta] マルチカーソル状態でカーソルの幅が異なる？ / feel strange that the size of cursors

### ISSUE THREAD

**Issue by charonferry** [coteditor/CotEditor#892]
### Environment (環境)
- CotEditor 3.7.0-beta (321)
- macOS Mojave 10.14.2（18C54）
- Language: Japanese

### Short Description (簡単な説明)
普段のカーソルに (細い) 線を使用していますが、複数個目のカーソルが太い気がします。
太い線とブロックに変更した場合は、同じサイズのカーソルが描画されているので、
(細い) 線の時だけの現象かと思われます。

**Comment by 1024jp** [comment]
本当だ...。太いカーソルでデバッグしていたので気づいてませんでした。ありがとうございます。
