### ISSUE TITLE
[beta] マルチカーソル状態で上下すると異常終了 / When move the cursors, shut down

### ISSUE THREAD

**Issue by charonferry** [coteditor/CotEditor#893]
### Environment (環境)

CotEditor 3.7.0-beta (321)
macOS Mojave 10.14.2（18C54）
Language: Japanese

### Short Description (簡単な説明)
1. 新規テキストを作成し、改行を10回ほど入力
2. 3行目にカーソル移動
3. 5行目にカーソルを追加 (マルチカーソル状態)
4. 矢印キーでカーソルを上下に移動

**Comment by 1024jp** [comment]
ありがとうございます。修正します。
