### ISSUE TITLE
[beta] マルチカーソルで `⌘+delete` の挙動が怪しい /  In the multi-cursor, press `⌘+delete` to feel strange

### ISSUE THREAD

**Issue by charonferry** [coteditor/CotEditor#895]
### Environment (環境)

- CotEditor 3.7.0-beta.2 (323)
- macOS Mojave 10.14.2（18C54）
- Language: Japanese

### Short Description (簡単な説明)

シングルカーソルで `⌘+delete`  キー押下すると、カーソル位置から行頭までが削除される (正常)。
マルチカーソルで `⌘+delete` キー押下した場合、各行を残してそれぞれの行でカーソル位置から行頭までを削除してほしい。

### サンプル ("|"はカーソルを表す)

> aaa bbb| ccc
> aaa bbb| ccc
> aaa bbb| ccc

`⌘+delete` 押下

> | ccc
> | ccc
> | ccc

**Comment by 1024jp** [comment]
ありがとうございます。
細かい検証ハチャメチャに助かります。

ちょうど先ほど自分でもコード読み直していて気づき、手元で直したところでした。次のベータに載せます。
