### ISSUE TITLE
[beta] [multi-cursor] do NOT work of deleting text in fron of the cursors by press fn+delete keys / fn+deleteキー押下で前方削除されない

### ISSUE THREAD

**Issue by charonferry** [coteditor/CotEditor#896]
### Environment (環境)

- CotEditor: 3.7.0-beta.2 (323)
- System: macOS Mojave 10.14.2 (18C54)
- Language: Japanese

### Short Description (簡単な説明)

SSIA; 表題の通り

**Comment by charonferry** [comment]
Don't work by press Ctrl+D keys.
Ctrl+Dも機能していない模様。

**Comment by 1024jp** [comment]
Fixed. Thank you!

**Comment by charonferry** [comment]
- CotEditor: 3.7.0-rc.3 (335)
- System: macOS バージョン10.14.3（ビルド18D109）
- Language: Japanese

対応ありがとうございます。
現在、[Mac のキーボードショートカット](https://support.apple.com/ja-jp/HT201236) を参考に動作確認しています。
その中で、1件不備を発見しましたので、新しいイシュー起こします。
