### ISSUE TITLE
[beta] [multi-cursor] 勝手にマルチカーソルが終了する (レアケース)

### ISSUE THREAD

**Issue by charonferry** [coteditor/CotEditor#897]
### Environment (環境)

CotEditor: 3.7.0-beta.2 (323)
System: macOS Mojave 10.14.2 (18C54)
Language: Japanese

### Short Description (簡単な説明)

1. 3行ほど改行を入力
2. 1行目にカーソル移動
3. ctrl+shift+↓押下 (マルチカーソル開始)
4. "aaa "と入力 ("a"×3+" "(スペース))
5. しばらく放置
6. 2行目のカーソルが消える

おそらく "オートセーブ" と "保存時に行末の空白を削除" が機能した結果、
2行目のカーソルが消えたものと思われます。
シングルカーソルの場合はカレント行の行末空白は堅持されるけど、
マルチカーソルでも空白を残せるのでしょうか？
色々、面倒がありそう。

**Comment by 1024jp** [comment]
原因まで見つけていただいて大変助かります。

> マルチカーソルでも空白を残せるのでしょうか？

これはなんとかなるかと思います。
