### ISSUE TITLE
起動後の復元で表示（文字、背景色、シンタックスカラー）が反映されない。

### ISSUE THREAD

**Issue by rio-redstone** [coteditor/CotEditor#898]
## Environment (環境)

- CotEditor: 3.6.11 (309)
- System: macOS バージョン10.12.6（ビルド16G1710）
- Language: Japanese

## Short Description (簡単な説明)

書類を開いたままシャットダウン、再起動し、起動後に背景や文字色の表示など反映されていない。
普段はPulseをに少し変更を加えたものを使っているが、復元後には背景が白、文字が黒、シンタックスカラーが無い状態になっている。
新規書類や起動後に書類を開いた場合は反映されている。

## Steps to Reproduce the Issue (不具合が発生したときに行っていた操作、または再現手順)

書類を開いたままシャットダウン、または再起動
->起動後に背景が白、文字色が黒、シンタックスなしになっている。

## Expected Result (期待される挙動)

起動後、再起動後の復元でも表示の背景色、文字色、シンタックスカラーが反映されるようになって欲しい。

**Comment by 1024jp** [comment]
報告ありがとうございます。
手元の環境で再現ができないのでOSのバージョンが関係しているかもれません。何れにせよ不便だと思うので今月中にはこれを修正するCotEditor 3.6.12を出して対応したいです。それまでしばしお待ちください。

**Comment by rio-redstone** [comment]
ありがとうございます。

よく見ると、シンタックスは動作しているようです。
ただ、背景色や文字色（例えばPulse）が反映されたシンタックスカラーかどうかは確認できませんでした。

**Comment by 1024jp** [comment]
@rio-redstone 本日CotEditorの新しいベータ版を[coteditor.com/beta](https://coteditor.com/beta)にてリリースしました。
このベータは次の新機能を含むアップデートであるCotEditor 3.7.0のためのテスト版なのですが、ここに本Issueのバグ修正を含むCotEditor 3.6.12の変更も加えました。CotEditor 3.6.12は何れにせよ数日中にリリースする予定ですが、お時間ありましたらこのベータ版を試用してみて不具合が修正されているか確認していただけないでしょうか？
なお、ベータ版試用の際、App StoreからCotEditorをインストールしている場合は、Storeでのアップデートあサイクルを壊さないために、/Applications/のCotEditor.appをベータ版と入れ替えるのではなくデスクトップなどにベータ版は仮置きして試してみることをお勧めしています。

**Comment by rio-redstone** [comment]
復帰後に、文字色、背景色、シンタックスカラーが反映されて、終了前の状態で復帰しました！
ありがとうございます！

**Comment by 1024jp** [comment]
@rio-redstone 確認ありがとうございます。助かります。
