### ISSUE TITLE
Request: wrapping lines to editor window as a menu item

### ISSUE THREAD

**Issue by lojza3d** [coteditor/CotEditor#900]
Please, could you add current "Settings->Edit->Line Wrapping->Wrap lines to editor width" toggle as a dedicated menu item so it can get assigned a keyboard shortcut?

This would be extremely useful in my case - moving often between ordinary plaintext files (wrapping desired) to code (wrapping usually undesired). Thank you for considering.

**Comment by 1024jp** [comment]
CotEditor already has a menu item for that action in __Format__ > __Unwrap Lines__ (or __Wrap Lines__).

<img width="600" alt="screen shot 2019-01-14 at 8 02 02 pm" src="https://user-images.githubusercontent.com/1165044/51109048-52077880-1837-11e9-892c-572850c84484.png">

In addition, you can also add a toolbar item to toggle the line wrapping state from View > Customize Toolbar, if you want.

<img width="732" alt="screen shot 2019-01-14 at 8 04 15 pm" src="https://user-images.githubusercontent.com/1165044/51109203-d954ec00-1837-11e9-8289-8888e060ee38.png">

**Comment by lojza3d** [comment]
Oops, thank you & sorry for that issue. I only searched under "View" and "Text" menu entries :( This made my day! 👍

**Comment by 1024jp** [comment]
@lojza3d np.
