### ISSUE TITLE
[REQUEST] (Replace text/Find text/ Save) in all opened tabs at once

### ISSUE THREAD

**Issue by tripletroop** [coteditor/CotEditor#902]
Hello,
I'd like to suggest the ability to replace all in all opened files in tabs
or to find some text in all opened tabs
and to save changes happened to all opened tabs at once

**Comment by 1024jp** [comment]
Hi. CotEditor does currently not have any project management system that would be suitable for your requested feature (ref. #278).
The current implementation of CotEditor's window tabbing is actually just tying specific document windows up and no semantic relationship with each other.
Therefore, I'll implement your request after implementing the project management system, although it does not have specific implementation plans.

**Comment by rightsaidfred99** [comment]
Literally the only I thing I miss about Windows is notepad++ and the ability to do this. Not fun to search and replace multiple open docs :(
