### ISSUE TITLE
(要望) 複数行選択時の行コメントの挙動について

### ISSUE THREAD

**Issue by charonferry** [coteditor/CotEditor#903]
### Environment (環境)

- CotEditor: 3.6.12 (311)
- System: macOS Mojave 10.14.2 (ビルド18C54)
- Language: Japanese

### Short Description (簡単な説明)

```
#!/bin/bash

if true; then
    :
fi

exit 0
```

上記のような Bash スクリプトで `if - fi` 部分の3行を行コメントする場合、

1. if の行頭にカーソル移動
2. `shift-↓` × 3 (if から fi までの3行が反転し行番号が太字化される)
3. `⌘-/` 押下

すると、4行目もコメントアウトされます。

### Request (要望)

直感的には、反転しているかつ行番号が太字の3行のみコメントアウトしてほしい。

**Comment by 1024jp** [comment]
本件次マイナーアップデートに当たる3.7.0にて挙動が変更され、希望通りのものとなります。
3.7.0は2月頭にリリース予定です。

**Comment by charonferry** [comment]
- CotEditor: 3.7.0-rc.3 (335)
- System: macOS バージョン10.14.3（ビルド18D109）
- Language: Japanese

動作確認しました。正式リリースお待ちしております。
ありがとうございます。
