### ISSUE TITLE
[Feature request] Please add per-tab 'edited' indicator

### ISSUE THREAD

**Issue by willbprog127** [coteditor/CotEditor#904]
Please add per-tab edited indicator, such as '*' or some other symbol to indicate that a tab's document has been edited but not saved.

Thanks! 😄

**Comment by 1024jp** [comment]
Hi, long time not see.
But from CotEditor 4.4.0, CotEditor shows a small dot on the right side of the window tab when the document has unsaved changes.

CotEditor 4.4.0 will be released this fall when macOS Venture is released.

<img width="705" alt="Screen Shot 2022-07-03 at 11 13 20" src="https://user-images.githubusercontent.com/1165044/177021783-38f26272-82d0-461f-ba62-1053965c1128.png">

**Comment by willbprog127** [comment]
Thank you! :+1:
