### ISSUE TITLE
Auto complete in new syntax file

### ISSUE THREAD

**Issue by ronaldmannak** [coteditor/CotEditor#905]
I'm having troubles to activate auto completion in a new syntax file. I had assumed it would be as easy as just adding key strings to "completions:" but it seems it's not enough. 

Related: are variable names and user-defined function names also added to the auto-completion array? It might make sense to add those using regex.

Syntax file: https://github.com/compositeapp/EditorFramework/blob/develop/CotEditor/Syntaxes/Solidity.yaml

**Comment by 1024jp** [comment]
Apologies for the oversight, but I just noticed that I hadn’t responded to your ticket.

In the syntax definition of CotEditor, words in the completion list are used if more than one word is assigned; otherwise, all non-regex words assigned for syntax highlighting are used.
