### ISSUE TITLE
[New Theme] XCode syntax style for coteditor

### ISSUE THREAD

**Issue by JARVIS-AI** [coteditor/CotEditor#913]
Thanks for great app
I made a new theme for coteditor

XCode Dark and Light 
New Xcode highlighter

[LINK](https://github.com/JARVIS-AI/coteditor-theme)

**Comment by 1024jp** [comment]
Thank you for the post and I close this issue since your theme has been added to [our wiki page](https://github.com/coteditor/CotEditor/wiki/Additional-Themes).
