### ISSUE TITLE
「エディタを分割」でテキストが短く折り返されてしまう / Text wraps shorter than view width when split the editor

### ISSUE THREAD

**Issue by wanik** [coteditor/CotEditor#916]
## Environment

- CotEditor: 3.6.12 (311)
- System: macOS Version 10.13.6 (Build 17G5019)
- Language: English

## Short Description

「表示」メニューから「エディタを分割」を行なうと、テキストが短く折り返されてしまいます。

## Steps to Reproduce the Issue

1.
「表示」メニューから「エディタを分割」を行ないますと、分割後の下段で、テキストが短く折り返されて表示されます。

![cotsplit](https://user-images.githubusercontent.com/34469683/52172956-add17b80-27bd-11e9-8d6d-e55caf658259.jpg)

2.
「フォーマット」メニューで、行を「折り返さない」→「折り返す」をすると、直ります。

3.
分割後、上段にカーソルを置いて、「分割エディタを閉じる」と、テキストが短く折り返されたままの状態で、一つのエディタ画面になります。

これも、「フォーマット」メニューで、行を「折り返さない」→「折り返す」をすると、直ります。

## Expected Result

行の折り返し操作で直るには直りますが、分割前後で、折り返し位置が変わらないほうが、ありがたいです。

（環境設定等で、勝手にいじってしまったりしたところもあるかも知れません。使い方の誤解や行き違いありましたら、ご容赦下さい。）

念のため、動画(.mp4)と使用したテキストファイルを添付いたします。
よろしくお願いいたします。

[CotSplit.zip](https://github.com/coteditor/CotEditor/files/2825193/CotSplit.zip)

**Comment by wanik** [comment]
ご対応、どうもありがとうございます。

**Comment by 1024jp** [comment]
本件、こちらでいくつかの環境（macOS 10.12, 10.13, 10.14）で試してみたのですが、いずれも再現できませんでした。
しかし、頂いたスクリーンショットや動画を見る限りも現に発生していますし、状況としてもどう考えてもバグの部類なので、なんとか修正できないかと考えています。

ひとまず、今週末あたりにリリース予定のテスト版である 3.7.0-rc.3 にて、コード的に関連しそうな部分に対策を設けてみるので、それで一度修正ができているか試していただけないでしょうか？
3.7.0-rc.3をリリースしたらまたこちらでご連絡いたします。

**Comment by wanik** [comment]
ご連絡、どうもありがとうございます。

　こちらでも何度かやってみましたが、毎回症状が出ております。
　また、添付した動画では、分割後の行の折り返し位置が、ちょうど単語間のスペースの後ろになっていますが、何度かやっているうちに、同じ英文テキストであっても、語中で、単語間のスペースのほかにも、4文字数毎に折り返されてしまうようにもなりました（添付図）。
　こちらのパソコンやCotEditorの設定が関係していたり、設定のどこかの部分がこわれていたりするなども考えられますでしょうか？

　3.7.0-rc.3 にての確認の件、了解いたしました。よろしくお願いいたします。

![cotsplit2](https://user-images.githubusercontent.com/34469683/52251404-00d33c00-2940-11e9-83e1-5a9eb43276e9.jpg)

**Comment by wanik** [comment]
症状が現れているのは iMac なのですが、MacBook Pro で同じテキストファイルを使ってやってみましたところ、症状は出ませんでした。

　MacBook Pro の環境は以下のとおりで、

- CotEditor: 3.6.12 (311)
- System: macOS Version 10.13.6 (Build 17G5019)
- Language: English

症状が出ている iMac と基本的には同じです。

　私の iMac 固有の問題かも知れません。

**Comment by 1024jp** [comment]
追加情報ありがとうございます。

症状再現しました。システム環境設定でスクロールバーを常に表示にしていると発生するようです。
再現さえできれば俄然デバッグは楽になるので、次バージョンまでにはなんとかします。
（頂いた動画が役に立ちました。丁寧なレポート感謝します。）

<img width="780" alt="screen shot 2019-02-05 at 16 03 37" src="https://user-images.githubusercontent.com/1165044/52257808-bf528900-295f-11e9-984a-9334226c1775.png">

**Comment by wanik** [comment]
ありがとうございます。

　iMac で、システム環境設定のスクロールバーの表示を「常に／Always」以外にしてみたところ、確かに、症状が出ず、折り返されることがなくなりました。

　一方で、MacBook Pro ですが、システム環境設定のスクロールバーの表示が「常に／Always」であっても、短く折り返される症状は出ておりません。原因等見当がつきませんが、念のため、お知らせいたしておきます。
　MacBook Pro側の動画を添付いたします。前半と後半でスクロールバーの表示設定を変えて、試行しております。

[CotSplitMacBookPro.mp4.zip](https://github.com/coteditor/CotEditor/files/2831267/CotSplitMacBookPro.mp4.zip)

**Comment by 1024jp** [comment]
私も複数持っているマシンのうち、スクロールバーを常に表示させても現象再現される場合とされない場合がありました。
（ありえない挙動なのでどちらかというとApple側がヘマをしていると思うのですが...）

何れにせよ、1個対策を挟み、手元で再現できた現象は抑制されたので、おそらくこれで大丈夫かと思います。
今週末にこれを盛り込んだテスト版を出します。

**Comment by wanik** [comment]
異なるマシン間で、症状の有無に差があるのは、不思議ですね。

面倒なところ、ご対応くださいまして、どうもありがとうございます。
テスト版のリリースをお待ちいたしております。

**Comment by 1024jp** [comment]
本修正を含むテスト版のCotEditor 3.7.0-rc.3をリリースしました。お試しいただければ幸いです。

http://coteditor.com/beta

このバージョンで特に問題がなければ来週中に正式版をリリース予定です。

**Comment by wanik** [comment]
3.7.0-rc.3 で何度か試してみましたが、依然として、やはり症状が出ております。

環境:
- CotEditor: 3.7.0-rc.3 (335)
- System: macOS Version 10.13.6 (Build 17G5019)
- Language: English 


システム環境設定の「一般」の「スクロールバーの表示」の設定ですが、
「常に表示」の場合と「マウスまたはトラックパッドに基づいて自動的に表示」の場合で、症状が出ます。
「スクロール時に表示」の場合は、大丈夫でした。
（3.6.12で再度確認してみましたが、3.6.12の場合と同じです。）

動画を添付いたします。

[CotSplit3.7.0-rc.3.mp4.zip](https://github.com/coteditor/CotEditor/files/2849856/CotSplit3.7.0-rc.3.mp4.zip)

**Comment by 1024jp** [comment]
ほんとうですね...。早合点してました。お知らせいただきありがとうございます。

**Comment by wanik** [comment]
（Appleがらみらしいということもあり、また、個人的には急ぎではありませんが）
よろしくお願いいたしまーす。

**Comment by 1024jp** [comment]
本件の対応を含めたテスト版の 3.7.0-rc.5 を急遽作成・リリースしました：[coteditor.com/beta](https://coteditor.com/beta)。
手元であまり症状が再現せず手探りですが、お試しいただけますでしょうか？

**Comment by wanik** [comment]
rc.5、どうもありがとうございます。

さっそく試してみました。
おおむね順調だったのですが、妙なところで、症状が出ました。

まず、システム環境設定「一般」の「スクロールバーの表示」の設定を、順次変えてやってみました。このとき、カーソルを**テキストの冒頭**に置いてやったところ、いずれの場合もうまく行きました。

**ところが**、 「**スクロール時に表示**」の際に、 カーソルを**テキストの下半分くらいの位置**に置いてやったところ、短く折り返される症状が出ました。添付の動画の40秒目くらいから以降です。

「マウスまたはトラックパッドに基づいて自動的に表示」と「常に表示」の場合は、同じようにやっても大丈夫でした。

ややこやしそうで恐縮ですが、よろしくお願いいたします。

[cotsplit3.7.0-rc.5c.mp4.zip](https://github.com/coteditor/CotEditor/files/2851381/cotsplit3.7.0-rc.5c.mp4.zip)

**Comment by 1024jp** [comment]
早速の検証ありがとうございます！
そしてダメでしたか。詳細な状況説明とても助かります。もう少し足掻いてみます。

**Comment by 1024jp** [comment]
新たに対策を加えたものを、CotEditor 3.7.0の正式版としてリリースしてしまいました。これで直ってると思うのですが...。
まだダメでしたら3.7.1で対策したいので、ご連絡いただけるとさいわいです。

**Comment by wanik** [comment]
これまで試行してきた条件でひととおりやってみましたが、
**いずれも問題なく、分割ができました**。

**画面を一つに戻すのも、問題なしでした**。
今のところ、これで**OK**です。

テスト版では何度もたいへんでしたが、
お蔭さまで問題がなくなって、うれしいです。
どうもありがとうございます。

**Comment by 1024jp** [comment]
やっと修正できたようでよかったです。
こちらこそ、辛抱強くデバッグお手伝いいただき大変感謝しております。
