### ISSUE TITLE
合成可能なダイアクリティカルマークの正規表現での置換に失敗する / "Replace All" fails replacing diacritical marks with regex

### ISSUE THREAD

**Issue by wanik** [coteditor/CotEditor#917]
## Environment

- CotEditor: 3.6.12 (311)
- System: macOS Version 10.13.6 (Build 17G5019)
- Language: English

## Short Description

合成可能なダイアクリティカルマークについて、正規表現での検索は成功しますが、置換に失敗するようです。

## Steps to Reproduce the Issue

1.
例えば、ローマ字の「i」U+0069 等に、合成可能なダイアクリティカルマークのマクロン U+0304 を重ね打ちします。

2.
検索ウィンドウで、正規表現として \p{InCombiningDiacriticalMarks} を検索すると、図の例で正しく3件のヒットがあります。

3.
しかし、この \p{InCombiningDiacriticalMarks} を、例えば「XX」に置換しようとします。
そうすると、プログレス・ダイアログには「3件置換した」旨が表示されますが、実際のテキストは置換されておらず、元のままです。

4.
重ね打ち箇所の文字コードを見ても、元の U+0069 と U+0304 のままです。

5.
Unicodeの正規表現で \u0304 として置換してみても、同じ結果です。

![cdmpagesev](https://user-images.githubusercontent.com/34469683/52219786-ad7dd100-28e0-11e9-8f9d-e21cf80f01e9.jpg)

## Expected Result

合成可能なダイアクリティカルマークについて、 \p{InCombiningDiacriticalMarks} や \u0304 等の正規表現で、検索・置換ができるとありがたいです。

よろしくお願いいたします。

**Comment by 1024jp** [comment]
ありがとうございます。症状確認しました。3.7.0にて修正する予定です。

**Comment by wanik** [comment]
ご対応、どうもありがとうございます。

「すべて置換」の場合の症状であると述べておりませんでしたが、ご確認どうもありがとうございます。また、一つずつ「置換」すると、確かに成功しました。当面はこれで処理できます。

**Comment by wanik** [comment]
3.7.0-rc.3 にてひと通り試してみました。
無事に解決されたようです。どうもありがとうございます。
