### ISSUE TITLE
テキストエリア下部に余白が欲しい

### ISSUE THREAD

**Issue by hazi** [coteditor/CotEditor#920]
機能要望です。

テキストエリア下部に余白があったらいいなと思うのですが、いかがでしょうか。

**イメージ**
![image](https://user-images.githubusercontent.com/5656927/52515022-40f53000-2c5a-11e9-80d0-08804cb513a4.png)

## 理由

一番下の行に文字を入力している際に改行をすると、スクロールが発生してしまいます。
１行ぐらいだったらいいのですが、コピペなどで複数行操作しているとガタガタ画面が動いて、入力がしづらいというのが理由です。

ちなみに、他のエディタでは画面１面分ぐらいの余白があり、それぐらいがちょうどいいかなと思っております。

よろしくお願いします。

**Comment by 1024jp** [comment]
去年のどっかのタイミングでその昨日入れたので、環境設定 > ウインドウ > 超過スクロールで余白量を調整できます。

<img width="950" alt="screen shot 2019-02-09 at 2 44 35 pm" src="https://user-images.githubusercontent.com/1165044/52517110-529a0000-2c79-11e9-8baa-ba528c15ce3e.png">

**Comment by hazi** [comment]
大変失礼しました！ありがとうございます！

あるような、なんなら自分が要望を出したような気がししてたんですが、Issueも設定も探しても見つからず書いてしまいました…。
お手数をおかけしました。
