### ISSUE TITLE
[rc] [multi-cursor] option+delete キー押下でカーソル左の単語が削除されない

### ISSUE THREAD

**Issue by charonferry** [coteditor/CotEditor#921]
### Environment (環境)

- CotEditor: 3.7.0-rc.3 (335)
- System: macOS Mojave 10.14.3（18D109）
- Language: Japanese

### Short Description (簡単な説明)

シングルカーソルで `option+delete` キー押下した場合、カーソルの左の単語が削除される (正常)。
マルチカーソルで同様のキーを押下した場合、カーソルの "右" の単語が削除されてる？

**Comment by 1024jp** [comment]
いつもありがとうございます。
これは完璧に私のケアレスミスで向きを逆にしてました。修正しました。
