### ISSUE TITLE
[rc] [multi-cursor] ⌘+←/→ キー押下で横スクロールされない

### ISSUE THREAD

**Issue by charonferry** [coteditor/CotEditor#922]
### Environment (環境)
* CotEditor: 3.7.0-rc.3 (335)
* System: macOS Mojave 10.14.3（18D109）
* Language: Japanese

#### 準備
ウィンドウ幅を超えるような行を複数行入力し、横スクロールが必要な状況を起こす。

```text
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

#### シングルカーソル時の正常挙動
1. 1行目の行頭にカーソルを移動する
2. ⌘+→ キー押下
3. カーソルが行末に移動し、右端にカーソルが表示される (横スクロールされる)

#### マルチカーソル時の挙動
1. 1行目の行頭にカーソルを移動する
2. control+shift+↓ キー押下でマルチカーソル開始
3. ⌘+→ キー押下
4. (画面がちょっと動く) 右端のカーソルは表示されない
5. マウスorトラックパッドで横スクロールすると、行末にカーソルは移動している

**Comment by charonferry** [comment]
#### 別件かも
"マルチカーソル時の挙動" の 4. (画面がちょっと動く) が予期しない時に起こります。

```text
aaa bbb ccc
aaa bbb ccc
aaa bbb ccc


aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

**Comment by charonferry** [comment]
横スクロールして、カーソルが表示されてほしいけどされない場合として、
option+→ (⌥→) キー押下でも発生します。

```text
aaaaaaaa bbbbb ccccccc dddddd eeeeee ffffff gggggg hhhhh iiiiiii jjjjjj aaaaaaaa bbbbb ccccccc dddddd eeeeee ffffff gggggg hhhhh iiiiiii jjjjjj
aaaaaaa bbbb cccccc ddddd eeeee fffff ggggg hhhhhhhh iiiiii jjjjjjjjjj aaaaaaa bbbb ccccccc dddddd eeeeee ffffff gggggg hhhhh iiiiiii jjjjjj
```

シングルカーソルの場合、⌥→ キー連打で単語の境界を超える場合にスクロールする。
マルチカーソルの場合、どの行に追従するかは検討する必要があるものの、スクロールはしてほしい。

**Comment by 1024jp** [comment]
状況把握しました。
確かにどのカーソルを表示するかは悩ましいのですが、どちらにせよ最低限どれかは見えるようにスクロールしたいところですね。

ひとまず、

- 左または上にカーソルを移動するときは最初のカーソル
- 右または下にカーソルを移動するときは最後のカーソル

が収まるようにスクロールするよう仕様を変更しました。

本当なら左/右移動のときは左端/右端にあるカーソルを表示するのがより好ましいようにも思えるのですが、
計算量がぐっと増えるので少々考えさせて下さい。

**Comment by 1024jp** [comment]
> 本当なら左/右移動のときは左端/右端にあるカーソルを表示するのがより好ましいようにも思えるのですが、
計算量がぐっと増えるので少々考えさせて下さい。

考えてみたのですが、相当面倒なのでいったん今の仕様とします。

**Comment by charonferry** [comment]
> 本当なら左/右移動のときは左端/右端にあるカーソルを表示するのがより好ましいようにも思えるのですが、
> 計算量がぐっと増えるので少々考えさせて下さい。

承知しました。
テキストの長短によっては、
- 右端を追従すると左端のカーソルが表示外になることもあり得る
- 右端のカーソルが行末で右移動すると、次行の行頭に移動する (つまり左端のカーソルになる) ので、加味する状況も複雑化しそう

など、意外と仕様が面倒そうです。


正しい仕様は、
- 出来るだけ多くのカーソルが表示可能なように表示する

の気がします。
