### ISSUE TITLE
(要望) [rc] [multi-cursor] ⌘⇧D キー押下 (行複製) で複製された行のマルチカーソルを堅持してほしい

### ISSUE THREAD

**Issue by charonferry** [coteditor/CotEditor#923]
### Environment (環境)

- CotEditor: 3.7.0-rc.3 (335)
- System: macOS Mojave 10.14.3（18D109）
- Language: Japanese

### Short Description (簡単な説明)

シングルカーソルで ⌘⇧D キー押下すると行複製され、複製された行にカーソルが移動する (下行、同列) (正常)。
マルチカーソルで同様に行複製した場合、行が複製されシングルカーソルに戻る (仕様？)

### 要望

マルチカーソルで行複製した場合も、それぞれの下行でマルチカーソルを堅持してほしい。
("|"はカーソルを表す)

```text
|aaa bbb cccc

|ddddd eee ffff

```

行複製後

```text
aaa bbb cccc
|aaa bbb cccc

ddddd eee ffff
|ddddd eee ffff

```

**Comment by 1024jp** [comment]
なるほど、これは現時点では「仕様です」ですが、改良しましょう。できるだけ3.7.0の正式版に突っ込むようにします。

**Comment by charonferry** [comment]
びっくりするほど早速の対応、ありがとうございます。
