### ISSUE TITLE
Line highlight does not work in a multi-cursor / マルチカーソルで行ハイライトが強調表示されない

### ISSUE THREAD

**Issue by charonferry** [coteditor/CotEditor#926]
### Environment (環境)

- CotEditor: 3.7.0 (342)
- System: macOS Mojave 10.14.3 (18D109)
- Language: Japanese

### Short Description (簡単な説明)

環境設定 > [表示] パネル
現在の行: [x] 背景カラーを変更

マルチカーソルで2個目以降のカーソルの "現在の行" の背景が強調表示されない。
行番号は全てのカーソル行で "太字表示" されているので、背景も強調表示した方が適っている気がします。

p.s.
これまで背景カラーを使ってなかったので、気付いていませんでした。

**Comment by 1024jp** [comment]
なるほど、今までも複数選択エリアがあってもハイライトは1箇所なんでこういうもんだと思ってましたけど、確かに全部ハイライトされる方が理に適ってますね。
次で改良します。
指摘ありがとうございます。

**Comment by charonferry** [comment]
早速の対応ありがとうございます👍 
リビジョン更新お待ちしてます。

**Comment by charonferry** [comment]
- CotEditor: 3.7.1 (344)

👍
