### ISSUE TITLE
popclip extension

### ISSUE THREAD

**Issue by qxs7** [coteditor/CotEditor#927]
Is it possible to provide a popclip extension -- Create a new CotEditor document containing the selected text.
https://github.com/pilotmoon/PopClip-Extensions
https://pilotmoon.com/popclip/extensions/

**Comment by 1024jp** [comment]
I've never used PopClip. But according to README of the [PopClip-Extensions](https://github.com/pilotmoon/PopClip-Extensions) repo, it seems you can use Service or AppleScript.
