### ISSUE TITLE
DocumentViewController observers calls UI on background thread

### ISSUE THREAD

**Issue by ronaldmannak** [coteditor/CotEditor#928]
The `ViewDidLoad` method of DocumentViewController sets the `defaultObservers` property to observe for theme, line number, etc. 

The observation closures are called on a background thread by the UserDefaults extension in the DefaultKey+Observation.swift file: `func observe<Value>(key: DefaultKey<Value>, options: NSKeyValueObservingOptions = [], changeHandler: @escaping (UserDefaultsObservation.Change<Value>) -> Void) -> UserDefaultsObservation`. 

As an example, in case of the Theme observer, the observation closure calls `setTheme` in DocumentViewController and triggers the first `assert(Thread.isMainThread)` assertion.

A single line solution would be to wrap `changeHandler(typedChange)` in UserDefaults in a `DispatchQueue.main.async` closure, but unsure if that would have any side effects elsewhere in the code.

**Comment by 1024jp** [comment]
Thank you for pointing it out. I've just fixed it.
