### ISSUE TITLE
Textclippingファイルを正しく扱わない

### ISSUE THREAD

**Issue by taniguti** [coteditor/CotEditor#929]
## Environment

- CotEditor: 3.7.0 (342)
- System: macOS Version 10.14.4 (Build 18E184e)
- Language: English

## Short Description
Textclipping ファイルをドキュメントウインドウにドラッグ＆ドロップすると、クリップしたテキストの内容ではなく、textclipping ファイルへのパスが入力されてしまう。

## Steps to Reproduce the Issue
テキストを選択して、デスクトップにドラッグ＆ドロップすることで、Textclippingファイルをデスクトップに生成する。
生成したTextclippingファイルをドキュメントウインドウに戻す。
（結果）Textclippingファイルへの絶対パスが入力される。

## Expected Result
Textclipping ファイルの中身がドキュメントウインドウのドロップした場所に入力されるべき。
同じtextclippingファイルを Notes.appなど他のアプリケーションで使うと期待通り動作することを確認しています。

**Comment by 1024jp** [comment]
たしかに、textClippingは中身がドロップされるべきですね。次バージョンで取り入れます。
