### ISSUE TITLE
After input 9 Space from begin of the line, cursor will jump to the begin

### ISSUE THREAD

**Issue by eailfly** [coteditor/CotEditor#930]
## Environment

- CotEditor: 3.7.0 (342)
- System: macOS Version 10.14.3 (Build 18D109)
- Language: English

## Short Description

Cursor will jump to wrong position when input several space from begin of line.

## Steps to Reproduce the Issue

open a new window, just input space, when input about 9 space, cursor will jump to the begin of the line

## Expected Result

Cursor in the right place

**Comment by 1024jp** [comment]
Thank you for the report.
However, under my environment, it works correctly.
Please inform me any other conditions that may relate to the behavior.
Uploading a recorded movie also helps me.

**Comment by eailfly** [comment]
I put a screen recording in youtube, according the recording, it's not the cursor problem, it's the space is missing, please note the column number at left bottom, when I input Space, it up to 12 and back to 1 when I move the mouse.

[![Watch the video](https://img.youtube.com/vi/P6IUVcd2apM/maxresdefault.jpg)](https://youtu.be/P6IUVcd2apM)

**Comment by 1024jp** [comment]
Oh, I got it! Thank you.
This is a bug that relates to "Trim trailing whitespace on save" option.
I'll fix it in the next version that may be released in this weekend.
Please be patient a while.
