### ISSUE TITLE
Speichern der Tabulatorbreite

### ISSUE THREAD

**Issue by scharrin2** [coteditor/CotEditor#932]
## Environment (Umgebung)

- CotEditor: 3.7.0 (342)
- System: macOS Version 10.14.3 (Build 18D109)
- Language: German

## Short Description (Kurzbeschreibung)

Die Tabulatorbreite kann nicht gespeichert werden
The width of the tabulator can't be saved

## Steps to Reproduce the Issue (Schritte zur Reproduktion)

Wenn ich die Tabulator-Breite von 4 auf 8 ändere und das Dokument erneut öffne, ist die Tabolaturbreite wieder bei 4
Set tabulator width from 4 (default) to 8. Then reopen a document and it was set back to 4.

## Expected Result (Erwartetes Ergebnis)

Aufnahme der Tabolatorbreite in die Einstellungen. Oder kann die Voreinstellung manuell verändert werden?
Is it possible to include the tabulator width into the settings dialog? Or can the default value be set in a configuration file?

**Comment by 1024jp** [comment]
Tut mir Leid für meine späte Antwort.

Changing tab width via menu is valid only for frontmost document and not saved to the file. You can change the default behavior in Preference > Edit > Indentation. Currently, CotEditor doesn't have a tab width settings par file/syntax style.

**Comment by scharrin2** [comment]
Thank you for your reply.

When setting this option to 8 characters nothing changes.

I added a screenshot.
The first Editor is TextEdit from Apple (with standard tab width of 8 characters (not changeable)
The second is CotEditor with standard setting of 4 characters

![image](https://user-images.githubusercontent.com/22325491/55012770-344d5100-4fe8-11e9-893f-1389926b09f5.png)

Would it be possible to add the width of a tab to the settings in a future release?

**Comment by 1024jp** [comment]
> When setting this option to 8 characters nothing changes.

Hmm, that's strange. The width doesn't change at all? Or changes but not enough to your desired width? 

Which font do you use?
You may be better to use a monospace font, such as Menlo, to align columns.
