### ISSUE TITLE
Go to Line の際に、Goボタンが機能しない / “Go” button for "Go to Line” command doesn’t work

### ISSUE THREAD

**Issue by wanik** [coteditor/CotEditor#935]
## Environment

- CotEditor: 3.7.1 (344)
- System: macOS Version 10.13.6 (Build 17G5019)
- Language: English

## Short Description

メニューから Find > Go to Line を選択し、行番号を入力して Goボタンをクリックしても、当該行にジャンプしないようです。

## Steps to Reproduce the Issue

例えば、100行あるテキストファイルで、メニューから Find > Go to Line を選択し、20 あるいは 50 などの行番号を入力して Goボタンをクリックしても、当該行にジャンプしません。

カーソルのある行が黄色くフラッシュされるだけです。

Enterキーを押下するとジャンプしますので、Goボタンに問題があるように見受けられます。

#301の報告と同じ症状のようです。

Goボタンをクリックした場合のみですが、動画を添付いたします。

[go_to_line_not_work.zip](https://github.com/coteditor/CotEditor/files/2952292/go_to_line_not_work.zip)

## Expected Result

Go to Line で行番号を入力し、Goボタンをクリックすると、その行にジャンプする。

**Comment by 1024jp** [comment]
バグ報告ありがとうございます。
これは明らかにバグですね。次のバージョンで修正します。

**Comment by wanik** [comment]
ありがとうございます。
よろしくお願いいたします。
