### ISSUE TITLE
Autocomplete doesn't respect beginString

### ISSUE THREAD

**Issue by ronaldmannak** [coteditor/CotEditor#936]
## Issue

Auto complete doesn't seem to respect beginString, and suggests unexpected words as if letters in the middle of a word are the first letter of a new word.

## Expected behavior

1. I want to type the word `contract`, a keyword defined in the YAML file.

1. When I type the letter `c`, auto-complete correctly suggests various keywords and commands that start with the letter c.

<img width="285" alt="Screen Shot 2019-03-13 at 12 35 24 AM" src="https://user-images.githubusercontent.com/455476/54261038-eafcfc00-4527-11e9-8bb0-9891d3d3d33e.png">

2. While I type more letters I expect auto complete to narrow down the list to the words, until at some point there is only the word `contract` in the auto complete list and I can press `enter` to insert the word in the editor.

## What happens

1. When I type the letter `c`, auto-complete correctly suggests various keywords and commands that start with the letter c.

<img width="285" alt="Screen Shot 2019-03-13 at 12 35 24 AM" src="https://user-images.githubusercontent.com/455476/54261038-eafcfc00-4527-11e9-8bb0-9891d3d3d33e.png">

2. Once I type the letter `t` in `contract`, auto complete unexpectedly suggests words that start with the letter `t`, even though I'm in the middle of the word contract. 

<img width="247" alt="Screen Shot 2019-03-13 at 12 28 43 AM" src="https://user-images.githubusercontent.com/455476/54261273-9dcd5a00-4528-11e9-93df-d0a88956c72d.png">

It seems auto correct doesn't respect the beginString, which I interpret as "Only match if a word begins with 'True' " (like "\b" regex). Syntax highlighting does seem to respect beginString

Interestingly, this issue does not seem to happen in Yaml files provided by the author, which suggests the issue is with the Yaml file.

## Code

`contract` is a keyword defined in the yams file as such:

```
keywords:
- beginString: "contract"
```

`True` is defined in the YAML file as a value:

```
values:
- beginString: "True"
```

Completions itself is an empty array:
```
completions: []
```

## File

File:
[Scilla.yaml.zip](https://github.com/coteditor/CotEditor/files/2960235/Scilla.yaml.zip)

**Comment by ronaldmannak** [comment]
I did some additional testing and isolated the issue more.

In the example above, typing the first `t` in `contract` would trigger autocomplete to suggest words starting with `t`, which leads to nonsense words like conTrue or contransition.

The bug can be reproduced with just three words (contract, transition, and True) in the YAML file. (ScillaBug.yaml in the attached zip file)

```
completions: []
keywords:
- beginString: "contract"
- beginString: "transition"
values:
- beginString: "True"
```
<img width="358" alt="Screen Shot 2019-03-13 at 1 10 49 PM" src="https://user-images.githubusercontent.com/455476/54311267-765ea780-4591-11e9-8998-fad299549065.png">

when deleting the keyword `transition` from the YAML file, the problem is solved, and CotEditor does *not* suggest `True` when typing the first `t`.

However, auto-complete only triggers at the first character, i.e. autocomplete only suggests `contract` when I type the letter `c`. After typing `co` or `con` (etc) autocomplete does not suggest anything. That seems to be a separate bug.

```
keywords:
- beginString: "contract"
values:
- beginString: "True"
```
<img width="376" alt="Screen Shot 2019-03-13 at 1 13 13 PM" src="https://user-images.githubusercontent.com/455476/54311435-cc334f80-4591-11e9-837f-d4412d4261ae.png">

Things get even more confusing when using regex. Autocomplete does not activate at all in this case. neither typing a `c`, `t`, or `T` triggers any of the words. Syntax highlighting does work, suggesting the simple regex expression itself is fine.

```
completions: []
keywords:
- beginString: "\\bcontract\\b"
  regularExpression: true
- beginString: "\\btransition\\b"
  regularExpression: true
values:
- beginString: "\\bTrue\\b"
  regularExpression: true
```


Attached the three files: ScillaBug.yaml, ScillaFine.yaml, and ScillaRegex.yaml
[Autocomplete.zip](https://github.com/coteditor/CotEditor/files/2963460/Autocomplete.zip)

**Comment by ronaldmannak** [comment]
It looks like at least some of the bundled yaml files have the same issues. The 'Suggest completions while typing' option seems broken.

<img width="369" alt="Screen Shot 2019-03-13 at 1 45 11 PM" src="https://user-images.githubusercontent.com/455476/54313296-41088880-4596-11e9-84c5-d9df032ed833.png">

**Comment by ronaldmannak** [comment]
FYI: It turns out the ScillaFine.yaml file attached in above comment only worked because `True` was with a capital `T`. When `True` is replaced by `true` then autocomplete will again suggest `true` when typing the first t of `contract`.

```
keywords:
- beginString: "contract"
values:
- beginString: "true"
```

**Comment by ronaldmannak** [comment]
Here's another odd thing. When the `none` syntax style is selected, and the completion list includes `Words in document`, only the words in the document are added to the autocomplete list.

So it should be easy to simulate the issue above by typing the words `contract` and `true` in the document. Once these two words are typed into an empty document with no syntax style, I expect CotEditor to behave exactly the same as if a syntax file was selected with just the words `contract` and `true`.

However, this does not seem the case. Words in the document are treated differently from words in the syntax YAML file. The words from the document work as expected.

<img width="591" alt="Screen Shot 2019-03-13 at 2 03 14 PM" src="https://user-images.githubusercontent.com/455476/54314481-094f1000-4599-11e9-9db1-6d0315068bc7.png">

It indeed seems the lists are treated differently in EditorTextview (lines 1681 to 1704).

**Comment by ronaldmannak** [comment]
I've added a print statement on line 1679 in EditorTextView.swift: `print(particalWord)`

With the `words in document` and `words defined in syntax style`, and `suggest completions while typing` on and `standard words` off, I got the following results.

With syntax style `none` selected in the toolbar I slowly type the word `contract` in an empty document:

```
c
co
con
cont
contr
contra
contrac
contract
```

With a (any) syntax style selected (e.g. Java):
```
c
n
nt
nt
ntr
ntra
ntrac
ntract
```

This suggests `override func completions(forPartialWordRange charRange: NSRange, indexOfSelectedItem index: UnsafeMutablePointer<Int>)` is receiving a different range depending on a syntax style is selected or not.

**Comment by ronaldmannak** [comment]
Apologies for rubber-ducking through the issue. The bug is in `override var rangeForUserCompletion: NSRange`. The default OS implementation already does a great job  (at least in 10.13), and I'm not 100% sure how overriding the property is supposed to improve the default implementation, but when you comment out the property and let the OS do its job, it all works fine. If there's any edge case not supported by the default implementation, I'm unaware of it.

**Comment by 1024jp** [comment]
Thank you for the study and really sorry for my late reply.
As you pointed out, the current behavior is uncurrent and therefore need to change.

>The default OS implementation already does a great job (at least in 10.13), and I'm not 100% sure how overriding the property is supposed to improve the default implementation, but when you comment out the property and let the OS do its job, it all works fine.

Unfortunately, the default implemention of `rangeForUserCompletion` is not suitable for completing coding keywords, such as ones including non-alphabetic characters (e.g. __init__), and therefore it is modified.

Anyway, I'll fix somehow.
