### ISSUE TITLE
検索・置換ウィンドウの 消去ボタン と スクロールバー の挙動について

### ISSUE THREAD

**Issue by wanik** [coteditor/CotEditor#940]
## Environment

- CotEditor: 3.7.1 (344)
- System: macOS Version 10.13.6 (Build 17G6029)
- Language: English

## Short Description

検索・置換ウィンドウの **消去ボタン** と **スクロールバー** の挙動について、お尋ねいたします。

システム環境設定 > 一般 General の中の **「スクロールバーの表示 Show scroll bars」の設定** 
によって、消去ボタン と スクロールバー の現れ方に違いがあるようです。

機能そのものに実害はなく、見栄えの問題です。
仕様なのか、バグなどの問題なのか、あるいはシステム側の問題なのか、
念のためご確認いただけますと、助かります。
よろしくお願いいたします。

## Steps to Reproduce the Issue

1. スクロールバーの表示を「 **Always** 」にした場合

![cotFindWindow1EV](https://user-images.githubusercontent.com/34469683/55052191-58b63580-509b-11e9-9181-406ed0890621.jpg)

（なお、いったん「When scrolling」にしてから、再度「Always」に戻すと、
消去ボタンは、以下の 3. と同じようになります。）

2. スクロールバーの表示を「 **When scrolling** 」にした場合

![cotFindWindow2EV](https://user-images.githubusercontent.com/34469683/55052200-5eac1680-509b-11e9-822a-c370e0d3bd4a.jpg)

3. スクロールバーの表示を「 **Automatically ...** 」にした場合

![cotFindWindow3EV](https://user-images.githubusercontent.com/34469683/55052205-61a70700-509b-11e9-90e1-6ce7df4026ac.jpg)

## Expected Result

「When scrolling」の場合を基準にして、その他の場合でも、
消去ボタンが適切な位置に表示され、
スクロールバーについても、エディタの編集画面本体での挙動と一致していると、
よりスマートだと思います。

**Comment by 1024jp** [comment]
ご指摘ありがとうございます。
チェック漏れです。おっしゃる通りだと思います。
次のバージョンで調整します。

**Comment by wanik** [comment]
さっそくのご確認、どうもありがとうございます。
調整、どうぞよろしくお願いいたします。
