### ISSUE TITLE
Translation : French

### ISSUE THREAD

**Issue by aurelien-roy** [coteditor/CotEditor#941]
Are you aware of someone working on a french translation ?
If not, I can do it. :)

**Comment by 1024jp** [comment]
Currently, nobody works on French localization.
So, it's great if you make one for CotEditor.
The fundamental guidance about CotEditor localiztion is at [CONTRIBUTING.md](https://github.com/coteditor/CotEditor/blob/develop/CONTRIBUTING.md). But please feel free to ask me if you have any questions for localization.

**Comment by 1024jp** [comment]
@aurelien-roy 
Thank you for the pull-request in #950.
After the merge, I found a missing file. Could you also translate Credits.html?
