### ISSUE TITLE
Not opening after 3.7.2 update

### ISSUE THREAD

**Issue by ggrabau** [coteditor/CotEditor#944]
I updated to 3.7.2 today and now the app doesn't open I am using 10.4.4

**Comment by 1024jp** [comment]
Could you describe "the app doesn't open" more in detail?
For instance: the app crashed? No response? or it launches correctly but ignores opening files?

**Comment by ggrabau** [comment]
was working fine until I updated then when you click on it icon indicates that it is opening in the dock but then nothing happens so No response would be what I would call it

**Comment by 1024jp** [comment]
Hmm, thanks.

- Please just try a system restart.
- Can you see CotEditor in Activity Monitor at least after you launch CotEditor?
- Please give me CotEditor's crash log if you have any.
- What if you move files in `~/Library/Containers/com.coteditor.CotEditor/Data/Library/Autosave\ Information/` to somewhere (e.g. Desktop) and then launch CotEditor.

**Comment by ggrabau** [comment]
There are no files in the autosave.  I did a restart immediately I was in a coding class and was trying to use it.  I am a CS student (Senior) I have tried to remove and reinstall the program as well it is still not functioning.  When I click the icon all I get is one bounce in the dock from your icon and then nothing.  I use this program daily and have been for over a year I have even recommended it to friends who have Macs I really need this program up and running again but am at a complete loss as to what I can do to make it work again short of you sending me the previous version which was working for me

**Comment by ggrabau** [comment]
Tried to compile the file myself and received these errors

Showing Recent Issues
Build system information
error: No account for team "HT3Z3A72WZ". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials. (in target 'CotEditor')
Build system information
error: No profiles for 'com.coteditor.CotEditor' were found: Xcode couldn't find any Mac App Development provisioning profiles matching 'com.coteditor.CotEditor'. (in target 'CotEditor')
Build system information
error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'CotEditor')

**Comment by 1024jp** [comment]
Hi, I improved the code since then.
Do you still have this issue under the lastest version (CotEditor 3.8.4)?

**Comment by 1024jp** [comment]
I close this issue due to no-reply.
