### ISSUE TITLE
CotEditor3.7.2で、ウィンドウを閉じるとクラッシュする / Crash when closing window

### ISSUE THREAD

**Issue by ggg21st** [coteditor/CotEditor#945]
ドキュメントのウィンドウを閉じると、クラッシュします。
3.7.2よりも前でも発生していましたが、3.7.2にアップデートした後も発生しています。
・Mac App版、non Mac App版のどちらでも発生しています。
・OSは10.13.3の英語環境となります。

クラッシュレポートを添付いたします。
ご確認をお願いいたします。

[coteditor_report_190415_3_7_2.txt](https://github.com/coteditor/CotEditor/files/3078280/coteditor_report_190415_3_7_2.txt)

**Comment by 1024jp** [comment]
報告ありがとうございます。
原因がわからないタイプのクラッシュログで悩ましいですが、
何れにせよmacOS 10.13で調査します。

**Comment by 1024jp** [comment]
返信遅くなりました。macOS 10.13.6上で色々試してみましたが再現しません。
現時点での最新バージョン:
- macOS 10.13.6
- CotEditor 3.7.3

でも本件まだ発生しますか？
その場合、もしなにか再現条件（新規書類でなく既存のファイルを開いたときのみ、何かを入力したあとで閉じたときのみ、など）などありましたら合わせて教えていただきたいです。

**Comment by 1024jp** [comment]
わからないながら、本日（5月18日）リリースしたCotEditor 3.7.4でいくつか対策を加えてみました。
状況が改善されたか否かを教えていただける大変助かります。

**Comment by ggg21st** [comment]
ありがとうございます。また、ご面倒をおかけしています。
CotEditor 3.7.4で、まだ発生していますが、macOSは10.13.3です。
10.13.6にアップデート後、改めて確認いたします。

**Comment by ggg21st** [comment]
お時間かかってしまい、申し訳ありません。
先ほどOS環境を10.13.6 (17G65)にアップデートできましたので、
CotEditor Version 3.7.5 (353)で確認したところ、現象が発生しなくなったことを確認いたしました。
ご面倒をおかけしましたが、ありがとうございました！
本件、私からもクローズさせていただきます。

**Comment by 1024jp** [comment]
おぉ、報告ありがとうございます。直ったようで良かったです。安心しました。
