### ISSUE TITLE
Mojaveでのカラーテーマと変換ウィンドウの背景色について

### ISSUE THREAD

**Issue by rio-redstone** [coteditor/CotEditor#947]
## Environment (環境)

- CotEditor: 3.7.2 (347)
- System: macOS バージョン10.14.4（ビルド18E226）
- Language: Japanese

## Short Description (簡単な説明)

ダークモードにしていませんが、カラーテーマを「Pulse」にしていると、文字変換の際に変換候補のウィンドウの背景が黒くなってします。

## Steps to Reproduce the Issue (不具合が発生したときに行っていた操作、または再現手順)

カラーモードを「Pulse」にして日本語を打って変換する -> 変換候補のウィンドウの背景色が黒（ダークモード？）
![](https://oyrworks.bitbucket.io/ImageUpload/dark.png) 

カラーモードを「Classic」にして日本語を打って変換する -> 変換候補のウィンドウの背景色が白
![](https://oyrworks.bitbucket.io/ImageUpload/light.png)

## Expected Result (期待される挙動)

ライトモードの時は、「Pulse」でも変換候補のウィンドウの背景色が白であってほしい。

**Comment by 1024jp** [comment]
なるほど、これに関して現時点では意図的に行っており「仕様です」という回答になります。

**Comment by rio-redstone** [comment]
ご連絡ありがとうございます。
では、そのように承知しました。

**Comment by rio-redstone** [comment]
とりあえず、Mojaveでは3.5.4を使うことにしました。
プログラムを実際に書き換える以外に回避する方法は現状では無いということでよろしいでしょうか？

**Comment by 1024jp** [comment]
うーん、そうですね。
この辺カーソル（Iビーム）の色とかスクロールバーの色とか全部連動しているので、安直に戻すとそれらが水らくなってしまうこともあり。
システムがライトモードの時でも書類ウインドウをダークモードにできるようのすることも検討しているので、
それと合わせてちょっと検討させてください。

**Comment by rio-redstone** [comment]
わかりました！
いつも本当に便利に気持ちよく使えています。ありがとうございます！

**Comment by 1024jp** [comment]
本件、変更を加えました。
次のバージョン（3.7.6）からは、背景が暗いテーマでもシステムのアピアランスがライトであれば変換候補ウインドウや辞書ポップオーバーもライトで表示されます。

<img width="610" alt="Screen Shot 2019-06-13 at 17 09 40" src="https://user-images.githubusercontent.com/1165044/59415251-12e94d80-8dfe-11e9-8d8a-3c80e5393fba.png">

**Comment by rio-redstone** [comment]
ありがとうございます！
