### ISSUE TITLE
Width of a space character is only half of other characters.

### ISSUE THREAD

**Issue by water137780117** [coteditor/CotEditor#949]
## Environment (环境)

- CotEditor: 3.7.2 (347)
- System: macOS Version 10.14.4 (Build 18E226)
- Language: English

## Short Description (简单描述)

The width of a space character is about half of other characters. I type six spaces between the two "1" character, it looks like this in TextEdit.app(the default text editor in macOS):
<img width="201" alt="1" src="https://user-images.githubusercontent.com/16634745/56722255-45b98280-6779-11e9-9368-85dc9f982cb7.png">
But in CotEditor, it looks like this, the width of six spaces is almost the same as the three characters "234":
<img width="402" alt="2" src="https://user-images.githubusercontent.com/16634745/56722265-4c47fa00-6779-11e9-832c-1ca7131e910a.png">
This also causes another problem, I set Tap width to 8 in CotEditor, but it looks like 4. I type some words seperated by tap, and it looks like this in TexEdit.app:
<img width="414" alt="3" src="https://user-images.githubusercontent.com/16634745/56722282-5538cb80-6779-11e9-8a36-2e01ad67c2f6.png">
But in CotEditor, it looks like this:
<img width="451" alt="4" src="https://user-images.githubusercontent.com/16634745/56722296-5bc74300-6779-11e9-975a-08a48c2b46fc.png">
When I set Tap width to 16, it looks well:
<img width="450" alt="5" src="https://user-images.githubusercontent.com/16634745/56722307-671a6e80-6779-11e9-92c5-c5f361401547.png">

## Steps to Reproduce the Issue (重现问题步骤)

Open the text file below with TextEdit and CotEditor, and the difference  is evident.
[space_width_test.txt](https://github.com/coteditor/CotEditor/files/3115991/space_width_test.txt)

## Expected Result (期待结果)
I wish the space width of CotEditor can be same as other characters, or there is an option to custom it.

**Comment by 1024jp** [comment]
It depends on your font.
If the font is a non-monospace font, then the space width is not the same as other characters.

You can set your font in Preferences > Appearance.

<img width="672" alt="Screen Shot 2019-04-25 at 19 17 57" src="https://user-images.githubusercontent.com/1165044/56728888-d8185100-678e-11e9-9fe1-b27866ad52d1.png">

If the space-width is still something wrong although you set a monospace font (such as Menlo), then let me know the font name.

**Comment by water137780117** [comment]
> It depends on your font.
> If the font is a non-monospace font, then the space width is not the same as other characters.
> 
> You can set your font in Preferences > Appearance.
> 
> <img alt="Screen Shot 2019-04-25 at 19 17 57" width="672" src="https://user-images.githubusercontent.com/1165044/56728888-d8185100-678e-11e9-9fe1-b27866ad52d1.png">
> 
> If the space-width is still something wrong although you set a monospace font (such as Menlo), then let me know the font name.

It works. Thank you very much!
