### ISSUE TITLE
スニペットの編集ができない

### ISSUE THREAD

**Issue by StatsBeginner** [coteditor/CotEditor#951]
バージョン3.7.3 (349)をMac OS Mojaveで使っています。
スニペットですが、「キー」の欄にキーの組み合わせを打ち込むことができるのですが、下の「挿入文字列のフォーマット」のところは「変数を挿入」だけが選択できる状態で、フォームには何も入力できません。

**Comment by 1024jp** [comment]
報告ありがとうございます。
どうやらバグのようです。手元の環境でも再現しました。
次のバージョンまでに修正できるよう努めます。しばしご辛抱ください。
