### ISSUE TITLE
CJK characters are not counted as words.

### ISSUE THREAD

**Issue by water137780117** [coteditor/CotEditor#952]
## Environment

- CotEditor: 3.7.3 (349)
- System: macOS Version 10.14.4 (Build 18E226)
- Language: English

## Short Description

I type a sentence in three languages.
First in English, "Glad to see you!" is a sentence with four words. CotEditor recognize it correctly.
![image](https://user-images.githubusercontent.com/16634745/56905822-8a278400-6ad3-11e9-8377-aa12c4fea806.png)
Second in Chinese, "见到你很高兴！" is a sentence with six words, because one Chinese character is one words, but CotEditor count no words.
![image](https://user-images.githubusercontent.com/16634745/56905988-f73b1980-6ad3-11e9-91d7-13ed894d2709.png)
I also try Japanese, which is translated by google, "お会いできて嬉しい！" is recognized as none either.
![image](https://user-images.githubusercontent.com/16634745/56906596-269e5600-6ad5-11e9-9a19-f6972b1045b7.png)

## Steps to Reproduce the Issue

Type CJK characters in CotEditor and watch the count of words.

## Expected Result

It would be nice if CJK characters can be counted as words or there is an option like "CJK words count ON/OFF".
Thanks.

**Comment by 1024jp** [comment]
This is currently not a bug but in spec.
The word count in CotEditor changes its behavior depending on the language in spell check.
But it means, at the same time, you cannot use a language that is not supported by the spell check.
So maybe, it seems I need to change this implementation at first.

In any case, the word counting rule can differ from language to language and detecting the language of a document to use for word counting is quite hard. Thus, I think it would be good to use auto-detection at first but users can force the language for word counting on demand.

I'll consider.

<img width="475" alt="Screen Shot 2019-05-02 at 8 12 46" src="https://user-images.githubusercontent.com/1165044/57049235-21e2c900-6cb2-11e9-82de-57a660b0bf9b.png">

**Comment by 1024jp** [comment]
Since version 3.8.0, CotEditor has used another word-counting method that counts also CJK languages.
So, this issue was solved
