### ISSUE TITLE
文字種によってファイルの終端の近くで矢印キー押下によるカーソル移動が極端に遅くなる

### ISSUE THREAD

**Issue by wanik** [coteditor/CotEditor#957]
## Environment

- CotEditor: 3.7.4 (351)
- System: macOS Version 10.13.6 (Build 17G7024)
- Language: English

## Short Description

ギリシア文字からなるプレーンテキスト・ファイルの終端の近くで、矢印キーを押下したままカーソルを移動させようとすると、カーソルの移動が極端に遅くなります。

## Steps to Reproduce the Issue

160行程度・約1万字のギリシア文字からなるプレーンテキスト・ファイルを、テスト用に用意しました。

矢印キーを押したままカーソルを移動させます。
ファイルの冒頭付近では、ほぼデフォルトの速さでカーソルが移動します。
ところが、終端付近では、カーソルの移動が極端に遅くなります。

比較のために、同程度の文字数のラテン文字からなるプレーンテキスト・ファイルで試してみました。
そうすると、ファイルの冒頭・終端どちらの場合も、カーソルが移動する速さに違いは感じられません。

上下方向のカーソル移動も同じ状況です。
ファイルの終端に近づくにつれて、しだいに遅くなっていくようです。

（動画には録りませんでしたが）かな漢字交じりのプレーンテキスト・ファイルでは、ラテン文字と同じく、問題はありません。

動画では、ラテン文字のファイル、ギリシア文字のファイルの順に録りました。

[greek_cursor_speed.zip](https://github.com/coteditor/CotEditor/files/3196471/greek_cursor_speed.zip)

## Expected Result

文字種・ファイル内のカーソル位置によって、矢印キー押下によるカーソル移動の速さが遅くならないようになりますと、ありがたいです。

**Comment by wanik** [comment]
ご参考までですが、アラビア文字のファイルでも、やはりカーソルの移動が遅くなります。
よろしくお願いいたします。

**Comment by 1024jp** [comment]
不具合報告ありがとうございます。また検証ファイル大変助かりました。
CotEditor 3.7.4で加えたSwift 5.1の仕様変更による不具合回避コードがあまり計算コストが良くなかったようで
カーソル移動などに影響を与えていました。
よりパフォーマンス重視のコードの書き換えたので次の3.7.5では改善されるはずです。
それまでご不便かけますがしばしお待ちください。

**Comment by wanik** [comment]
さっそくのご対応、どうもありがとうございます。
3.7.5のリリースをお待ちしております。

**Comment by wanik** [comment]
App Storeに 3.7.5 (353) が降りてきましたので、アップデートしました。
カーソル移動の問題、なくなりました。
どうもありがとうございます。

**Comment by 1024jp** [comment]
検証報告ありがとうございます。
無事解決したようでよかったです。
