### ISSUE TITLE
What will trigger the ServicesProvider.openSelection(:::) method?

### ISSUE THREAD

**Issue by marcocpt** [coteditor/CotEditor#961]
I am a beginner, I am reading the source code, but I can not find a way to trigger the function, need help, thanks

**Comment by 1024jp** [comment]
That function is for the system feature called Service.
Implementing it, users can open a file in CotEditor from Service menu via other apps. 

<img width="614" alt="Screen Shot 2019-05-27 at 12 44 49" src="https://user-images.githubusercontent.com/1165044/58394246-3cc01780-807d-11e9-9344-049c1e562002.png">

**Comment by 1024jp** [comment]
Oops, that exploration was about `ServicesProvider.openFile(:::)`.
Regarding `ServicesProvider.openSelection(:::) `, the concept is the same, but the target object is selected string.

<img width="850" alt="Screen Shot 2019-05-27 at 12 53 02" src="https://user-images.githubusercontent.com/1165044/58394470-6299ec00-807e-11e9-828d-c198179573e0.png">

**Comment by marcocpt** [comment]
I found that "Open File in CotEditor" was automatically added to the menu. However, "New CotEditor Document with Selection" has not been added to the menu in my case. I need to check it in the settings to appear. Is there any way to add it automatically?
Thank you for your answer!

**Comment by 1024jp** [comment]
> I need to check it in the settings to appear. 

Right. It seems you need to make sure the item is enabled in System Preferences > Keyboard > Shortcuts > Services.

> Is there any way to add it automatically?

I'm not sure but maybe there is no way.

**Comment by marcocpt** [comment]
Thank you very much!
