### ISSUE TITLE
特定の文字種（㊙︎）が2倍角の幅で表示される。

### ISSUE THREAD

**Issue by koujioota** [coteditor/CotEditor#962]
## Environment (環境)

- CotEditor: 3.7.4 (351)
- System: macOS バージョン10.12.6（ビルド16G1918）
- Language: Japanese

## Short Description (簡単な説明)

特定の文字種が2倍角の幅で表示される。

## Steps to Reproduce the Issue (不具合が発生したときに行っていた操作、または再現手順)

文字種
㊙︎
を入力すると、全角2文字分の幅で表示される。

## Expected Result (期待される挙動)

全角1文字分の幅で表示されてほしい。

**Comment by 1024jp** [comment]
それはフォントの問題でこちらで何か対応する類のものではないかと思います。

**Comment by koujioota** [comment]
ご回答ありがとうございます。

利用できる複数種類の日本語フォントで同じように発生し、他のアプリケーションでは発生していないようでした。

**Comment by 1024jp** [comment]
状況把握しました。
㊙そのものというよりも㊙の後ろの付いてるvariation selector (`U+FE0E`) の領域が確保されているようです。
これは、こちらの問題ですね、失礼いたしました。
修正します。

報告ありがとうございます。

**Comment by 1024jp** [comment]
対応しました。
次バージョン（3.7.6）で反映されます。
