### ISSUE TITLE
ファイル末尾付近の半角の右丸括弧「)」のところで、カーソルがもたついた動きをする

### ISSUE THREAD

**Issue by wanik** [coteditor/CotEditor#963]
## Environment

- CotEditor: 3.7.5 (353)
- System: macOS Version 10.13.6 (Build 17G7024)
- Language: English

## Short Description

ファイル末尾付近の半角の右丸括弧「)」のところで、カーソルがもたついた動きをする

## Steps to Reproduce the Issue

ファイル末尾付近の半角の右丸括弧「)」のところで、カーソルがもたついた動きをします。
今のところ使用上大きな支障はないのですが、やや違和感ありました。

他の括弧類についてはまだ検証おりませんが、取り急ぎご報告いたします。
（#957 と関係あるでしょうか。）

テストファイルと動画
[cursor_not_smooth.zip](https://github.com/coteditor/CotEditor/files/3231058/cursor_not_smooth.zip)

テストファイルとして、英数字と半角の右丸括弧「)」、ひらがな、句点等からなるプレーンテキスト・ファイルを用意しました。
1000行、34000字になります。

症状は、以下のようになりますので、添付の動画に記録しました。

1. 右矢印キーを押したまま、カーソル移動をしてみます。

- ファイルの冒頭部分では、カーソルがスムーズに移動します。
- **ファイルの末尾付近では、半角の右丸括弧「)」の手前で、カーソルの動きが一瞬止まる**ような感じになります。

2. また、右矢印キーを、だいたい一定の間隔で繰り返し押下して、カーソルを移動してみます。
（動画で20秒目付近から）

- ファイルの冒頭部分では、問題ありませんが、
- ファイルの末尾付近では、半角の右丸括弧「)」の手前で、カーソルの動きが引っかかるような感じです。

## Expected Result

文字の如何に関わらず、カーソルの移動速度が安定していると、ありがたいです。
よろしくお願いいたします。

**Comment by 1024jp** [comment]
なるほど、CotEditorは括弧の対応でハイライトをするようになっているのですが、片側の括弧が大量にあると書類の最初まで1文字ずつ確認しながら戻って探すので計算に時間がかかっているのかと思います。
パフォーマンスチューニングを検討します。

> #957 と関係あるでしょうか。
うーん、#957 とは直接は関係ないはずです。でもSwift 5.0での仕様変更の影響の可能性もあるので、その場合は根底ではつながっているといえますが...。

**Comment by wanik** [comment]
なるほど、確かに、括弧の対応のハイライトの影響ありますね。

Preferences > General で、**Highlight matching braces... のチェックをはずしましたら**、
上記のテストファイルでも、カーソルがスムーズに動きました。

一方で、**Highlight matching braces... をチェックした状態の場合**ですが、
**ファイル中に括弧の数が少なくても、もたつきが生じる**ようです。

テストとして、上記のテストファイルを改造して、
3行目と998行目の**2箇所のみに半角の右丸括弧「)」があるファイル**を作って試してみました。
他の行の「)」は、除去です。

テストファイルと動画
[cursor_not_smooth2.zip](https://github.com/coteditor/CotEditor/files/3232545/cursor_not_smooth2.zip)

その結果は、やはり998行目の「)」の位置で、一瞬止まったような感じになります。

チューニングの際に何かご参考になれば、ということです。
よろしくお願いいたします。

**Comment by 1024jp** [comment]
対応するカッコの検索について、パフォーマンスを改善しました。
この変更は次のバージョン（3.7.6）に乗ります。

**Comment by wanik** [comment]
さっそく改善下さり、どうもありがとうございます。
3.7.6 のリリースをお待ちしております。

**Comment by wanik** [comment]
テストファイルで試した限りですが、問題なくスムーズにカーソル移動ができるようになりました。
どうもありがとうございます。
