### ISSUE TITLE
the homebrew installer for CotEditor references 2.7.4

### ISSUE THREAD

**Issue by ryanwhocodes** [coteditor/CotEditor#964]
Does the homebrew package for CotEditor need updating?

I generally prefer installing via homebrew when possible and it looked like it was referencing an older version.

```
brew install cot
Warning: coteditor/coteditor/cot 2.7.4 is already installed and up-to-date
To reinstall 2.7.4, run `brew reinstall cot`
```

**Comment by 1024jp** [comment]
Refer my answer at https://github.com/coteditor/homebrew-coteditor/issues/3#issuecomment-497901501

**Comment by ryanwhocodes** [comment]
Thanks - read it and closed the other issue too.
