### ISSUE TITLE
行番号が表示されていると、ファイルの後半に近づくにつれてカーソル移動が遅くなる

### ISSUE THREAD

**Issue by wanik** [coteditor/CotEditor#965]
## Environment

- CotEditor: 3.7.5 (353)
- System: macOS Version 10.13.6 (Build 17G7024)
- Language: English

## Short Description

サイズが大きめのプレーンテキスト・ファイルで、行番号が表示されていると、ファイルの後半に近づくにつれてカーソルの動きが遅くなります。

## Steps to Reproduce the Issue

今回もテスト用のファイルを使って、動画に記録いたしました。

【ファイルと動画】
[cursor_slow_linenum.zip](https://github.com/coteditor/CotEditor/files/3248494/cursor_slow_linenum.zip)

ファイルは、半角英数字・ひらがな・カタカナ・漢字からなり、10,000行、500,000字です。

**動画の前半は、行番号が表示されている状態です。**
3行目と 9,998行目とで、右矢印キーを押したままにして、カーソルを移動させました。
9,998行目では、顕著に遅くなっています。

（動画には記録しておりませんが、2,000行目くらいではあまり感じません。3,000行目くらいで遅くなった感じが分かります。）

（動画では画面分割してますが、分割を解除しても同じようになりますので、分割のせいではないようです。）

**動画の後半は、行番号が表示されていない状態です。**
やはり、3行目と 9,998行目とで、右矢印キーを押したままにしてカーソルを移動させました。
この場合、とくに遅くなった感じはありません。

（ナビゲーション・バー、ステータス・バーについては、それらの表示の有無による影響がないようですので、行番号の表示が主たる原因かと思われます。）

## Expected Result

行番号の表示の有無にかかわらず、カーソルの移動が遅くならないようになりますと、助かります。

どうぞよろしくお願いいたします。

**Comment by 1024jp** [comment]
いつもテストデータとわかりやすい報告ありがとうございます。
パフォーマンスチューニングを行いました。
次

**Comment by wanik** [comment]
チューニング、どうもありがとうございます。
（WWDC中に重なってしまって、恐縮です。）

3.7.6のリリースをお待ちいたしております。

**Comment by wanik** [comment]
こちらも、テストファイルで試した限りですが、問題なくスムーズにカーソル移動ができるようになりました。
どうもありがとうございます。

なお、テストファイルでの話ですが、行番号の表示・非表示の際に、行番号が現れたり消えたりするまでに、やや時間がかかるようです。マシンの環境やファイルのサイズの影響あるかも知れません。
（再現できなければ、動画をお送りいたします。）
いちおう、ご参考までです。

**Comment by 1024jp** [comment]
検証ありがとうございます。もたつき抑制されたようで安心いたしました。

> なお、テストファイルでの話ですが、行番号の表示・非表示の際に、行番号が現れたり消えたりするまでに、やや時間がかかるようです。マシンの環境やファイルのサイズの影響あるかも知れません。

これ私も先日気づいて、Apple側のTouch Barのバグではないかと疑っているのですが、もうちょっと真面目に突き止めています。
（なぜTouch Bar...と思われるでしょうが実際エディタサイズが変わるとTouch Barの処理が呼び出されてそれが延々とかかっているのです）

**Comment by 1024jp** [comment]
ref. #971

**Comment by wanik** [comment]
ご検討、どうもありがとうございます。
エディタは、テキストの処理だけでなく、背後でさまざまなことをしているのですね。
Appleマターかも知れず、お手数ですが、よろしくお願いいたします。
