### ISSUE TITLE
スペースを押し続けると、最初のスペースがピリオドに変換されてしまいます。

### ISSUE THREAD

**Issue by hirotakami** [coteditor/CotEditor#966]
そうならないようにするには、どのように設定すればよろしいでしょうか。

**Comment by 1024jp** [comment]
<img width="780" alt="スクリーンショット 2019-06-05 午前6 02 18" src="https://user-images.githubusercontent.com/1165044/58958376-a0220780-8757-11e9-93f5-60f313b11acf.png">

これに関してはCotEditorは関係なくmacOS側の入力の機能です。__システム環境設定__ > __キーボード__ > __ユーザ辞書__ の「スペースバーを2回押してピリオドを入力」で変更することができます。

**Comment by hirotakami** [comment]
どうもありがとうございました！
