### ISSUE TITLE
Resizing NSTextView frame invokes updateTextTouchBarItems() repeatedly

### ISSUE THREAD

**Issue by 1024jp** [coteditor/CotEditor#971]
I suspect this is a bug of NSTextView...
But anyway, I need to clarify the cause and report it if it is really a bug or fix if something goes wrong with CotEditor. Strange...

<img width="1340" alt="Screen Shot 2019-06-19 at 11 35 13" src="https://user-images.githubusercontent.com/1165044/59732715-5ae8f400-9286-11e9-9e33-d9d7d05f42d0.png">

**Comment by carlos4242** [comment]
Note: this guy https://twitter.com/jessegrosjean/status/818496252241383424 says he saw the same thing two years ago and had a hack that fixed it. I saw the same thing and tried the same hack. Worked for me!

**Comment by 1024jp** [comment]
@carlos4242 Thank you for sharing your trial. I also did the same workaround in https://github.com/coteditor/CotEditor/commit/5ba37eee97796ff38c52bdbf6a14b93583f484f5. And feedback to Apple as well.
