### ISSUE TITLE
「検索と置換」ウィンドウリサイズ時の問題

### ISSUE THREAD

**Issue by sig-miyamoto** [coteditor/CotEditor#972]
## Environment (環境)

- CotEditor: 3.7.6 (355)
- System: macOS バージョン10.14.5（ビルド18F132）
- Language: Japanese

## Short Description (簡単な説明)

「検索と置換」ウィンドウで、「すべて検索」を実行した後に、「検索と置換」ウィンドウをリサイズすると検索結果が閉じてしまう。

## Steps to Reproduce the Issue (不具合が発生したときに行っていた操作、または再現手順)

「検索と置換」ウィンドウで「すべて検索」ボタンをクリックした後にウィンドウをリサイズ。
または
「検索と置換」ウィンドウで「すべて検索」ボタンをクリックした後にウィンドウ中央のセパレータをドラッグ。

## Expected Result (期待される挙動)

3.7.5では問題がありませんでした。

**Comment by 1024jp** [comment]
本当ですね...。ご報告ありがとうございます。
これは確実にバグなので次回までに修正します。
