### ISSUE TITLE
Do not display horizontal scrollbars

### ISSUE THREAD

**Issue by hrxind** [coteditor/CotEditor#973]
- CotEditor: 3.7.6 (355)
- System: macOS 10.13.6（17G7024）
- Language: Chinese (Simplified)

Do not display horizontal scrollbars, How can I solve it?

**Comment by 1024jp** [comment]
Could you explain some more?
Please describe what do you expect under which condition, and what you actually get instead. 
Also, screenshot may help.

**Comment by hrxind** [comment]
Please see attached pictures and documents.
There is a system.ini file in the attachment, which does not display the horizontal scroll bar when it does not change lines.
The horizontal scrollbar should be displayed without wrapping, but it is not displayed now.

**Comment by hrxind** [comment]
Sorry, there's another picture. Please look at it.

**Comment by 1024jp** [comment]
Hmmm, I cannot find the picture attached.
Could you post it in https://github.com/coteditor/CotEditor/issues/973 via web browser?

**Comment by 1024jp** [comment]
I also would like to know your settings. 

Please check your state of "Wrap lines to editor width" in CotEditor's preferences > Appearance?

<img width="672" alt="Screen Shot 2019-06-24 at 8 37 56 PM" src="https://user-images.githubusercontent.com/1165044/60016067-1616f000-96c0-11e9-9aae-9e6b2fe04ba6.png">


And also the System Preferences' (not CotEditor's ones) > General > Show scroll bars.

<img width="780" alt="Screen Shot 2019-06-24 at 8 39 06 PM" src="https://user-images.githubusercontent.com/1165044/60016115-32b32800-96c0-11e9-87fa-5b937afbfcef.png">

**Comment by hrxind** [comment]
I follow your graphics. I haven't solved the problem. The problem still exists.
What photos do you need from me? I sent the screenshot to #973.

**Comment by hrxind** [comment]
I don't need to change lines, but I need a scroll bar to show that I can pull to the right.

**Comment by hrxind** [comment]
The line break feature does have problems.
Only the up and down scroll bars are displayed.
Long-line content does not display left and right scroll bars.
The line feed is turned on, and then the line feed function is turned off, and the long line content displays the left and right scroll bars.

**Comment by 1024jp** [comment]
> What photos do you need from me? I sent the screenshot to #973.

I have not received any images from you.
In addition, as I mentioned, please let me know your scrollbar-related settings in both CotEditor and System Preferences.

So far I tried, it works as expected. I need to reproduce your issue to fix (if it is a bug).

**Comment by hrxind** [comment]
I'm glad to receive your reply.
I have taken some pictures. Please see where the problem is. Thank you.

![屏幕快照 2019-06-25 20 58 38](https://user-images.githubusercontent.com/38482781/60100481-665b8400-978c-11e9-9dac-08cf507bdd18.png)
![屏幕快照 2019-06-25 20 59 15](https://user-images.githubusercontent.com/38482781/60100482-665b8400-978c-11e9-974b-df2addc46929.png)
![屏幕快照 2019-06-25 20 59 23](https://user-images.githubusercontent.com/38482781/60100483-665b8400-978c-11e9-8e02-65845d1d3ece.png)
![屏幕快照 2019-06-25 20 59 32](https://user-images.githubusercontent.com/38482781/60100485-66f41a80-978c-11e9-9042-57acdfd1dd55.png)
![屏幕快照 2019-06-25 20 59 42](https://user-images.githubusercontent.com/38482781/60100486-66f41a80-978c-11e9-9d38-c07ab09a47af.png)
![屏幕快照 2019-06-25 20 59 51](https://user-images.githubusercontent.com/38482781/60100487-66f41a80-978c-11e9-8025-f1ebdc8428be.png)

**Comment by hrxind** [comment]
The first picture is my file, the fifth line of the file is a long line, and the scroll bar is not displayed above the status bar.

**Comment by 1024jp** [comment]
Thanks! I'll look into it.

**Comment by hrxind** [comment]
I just updated CotEditor through the app store, but the problem I asked is still there.

**Comment by 1024jp** [comment]
Ok, I succeed to reproduce this issue.
I'll release an extra version for this issue as soon as possible.
Thank you for the report.

**Comment by hrxind** [comment]
Thank you very much for your attention. Thank you.
I'm waiting for an updated version.
