### ISSUE TITLE
[request] Assign different symbol for U+00A0 / 不可視文字の表示で NO-BREAK SPACE (U+00A0) に別記号を割り当てたい

### ISSUE THREAD

**Issue by wanik** [coteditor/CotEditor#974]
## Environment

- CotEditor: 3.7.7 (358)
- System: macOS Version 10.13.6 (Build 17G7024)
- Language: English

## Short Description

不可視文字の表示の際に NO-BREAK SPACE (U+00A0) に別記号を割り当てることができると助かります。

## Expected Result

不可視文字の表示の際に、
現状では、SPACE (U+0020) と NO-BREAK SPACE (U+00A0) とが
区別されない仕様になっているものと理解しております。

![cot_invisible](https://user-images.githubusercontent.com/34469683/60187535-b445ba00-9868-11e9-9a3a-5517819f5600.jpg)

もし将来的に可能でしたら、
NO-BREAK SPACE (U+00A0) に別記号を割り当てることができるような
変更をお願い致したく存じます。

参考までですが、
「総合テキストツール」のJeditΩ と ワープロのNisis Writer Pro は、
下図のように区別して表示できます。

![invisibleJeditNisus](https://user-images.githubusercontent.com/34469683/60187503-a728cb00-9868-11e9-94b9-6982a8b867cb.jpg)

どれほどのニーズがあるのかと訊かれると、困りますが（笑）、
取り敢えず、リクエストをあげてみます。
よろしくお願い致します。

**Comment by 1024jp** [comment]
リクエストありがとうございます。
闇雲に設定項目を増やすのは避けたいので実装の仕方はちょっと悩ましいですが、ニーズはとてもよくわかるので前向きに検討します。

**Comment by wanik** [comment]
さっそく、どうもありがとうございます。
ニーズをご理解いただけて、うれしいです。
設計のポリシーやお考えもあろうかと存じます。
機会ありましたら、よろしくお願い致します。

**Comment by 1024jp** [comment]
お待たせしました。
次のCotEditor 3.9.0で不可視文字描画の刷新を行うので、
それに合わせ普通のSPACEとNO-BREAK SPACEで描画記号を分けました。
（今まであった不可視文字の記号をユーザが選択できる機能は廃止になります）

<img width="490" alt="Screen Shot 2020-04-25 at 15 24 58" src="https://user-images.githubusercontent.com/1165044/80273000-7d029c80-8709-11ea-9236-94adbed9696c.png">

NO-BREAK SPACEの記号はAppleのPagesに倣って `·̂` にしました。

- cf. [View formatting symbols and layout guides in Pages on Mac](https://support.apple.com/guide/pages/view-formatting-symbols-and-layout-guides-tan322bf978a/mac)

来週くらいにベータ版を出す予定です。

**Comment by 1024jp** [comment]
あとは、このNO-BREAK SPACEをどの設定のときに表示するかという問題があるのですが、
現状以下の3案で迷ってます。

もしご意見あれば（どなたでも）ください。

1. 「スペース」にチェックを入れたときにSPACEとNO-BREAK SPACEを表示する
2.  現在の「全角スペース」を「特殊なスペース」に変更し、これにチェックを入れたときにNO-BREAK  SPACEと全角スペース（場合によってはそれ以外のスペースも）を表示する
3. 「スペース」はSPACEのみとし、「その他の不可視文字」にチェックが入っているときにNO-BREAK SPACEも表示する

現状ひとまずの実装は1.ですが、個人的には2.がわかりやすいかなと考えています。

**Comment by wanik** [comment]
ご対応、どうもありがとうございます。
実装となると、いろいろ選択肢がありますね。

ことの発端として、SPACE と NO-BREAK SPACE が表示の上で区別されればよいという意味では、1. の実装で問題ないと思います。

日本語の一（いち）ユーザーとして、半角のスペースと全角のスペースの両方を混在させて使う立場では、設定ボタンにおける半角の「スペース」と「全角スペース」というこれまでの区別は、継承されたほうが分かりやすいかとも思います。
「全角スペースの設定ボタン、どこ行っちゃったの〜??」、みたいな混乱を起こさないという意味ですが、その点では、2. や 4. よりは、3. のほうが無難なのかも知れません。（個人的な所感ですが）

**Comment by wanik** [comment]
ちょっと脱線かも知れませんが、
「特殊なスペース」を新設する場合、SPACE と NO-BREAK SPACE 以外に、
主だったところで、
- EN SPACE U+2002
- EM SPACE U+2003
- THIN SPACE U+2009
- HAIR SPACE U+200A
- ZERO WIDTH SPACE U+200B

などもあろうかと思います。

これらについては、すべてを区別して表示するのは困難かと思いますが、「特殊なスペース」として一括して表示されるなど、何らかの形で表示対象となる予定でしょうか。
それとも、今までどおりで、特に変更ないということでしょうか。
（ふと思い浮かびましたので、念のためお聞きしてみます。）

**Comment by 1024jp** [comment]
> ことの発端として、SPACE と NO-BREAK SPACE が表示の上で区別されればよいという意味では、1. の実装で問題ないと思います。
> 
> 日本語の一（いち）ユーザーとして、半角のスペースと全角のスペースの両方を混在させて使う立場では、設定ボタンにおける半角の「スペース」と「全角スペース」というこれまでの区別は、継承されたほうが分かりやすいかとも思います。
> 「全角スペースの設定ボタン、どこ行っちゃったの〜??」、みたいな混乱を起こさないという意味ですが、その点では、2. や 4. よりは、3. のほうが無難なのかも知れません。（個人的な所感ですが）

なるほど、ありがとうございます。参考になります。

「（よく使う）普通のスペースはわざわざ描画したくないけどそれに紛れてるそれ以外の空白は知りたい」と言うニーズが結構あるんじゃないかと考えていて、その場合2.が妥当かなと考えています。全角スペースについては、日本語話者にとって重要なのはそうなのですが、逆に言うとそれ以外の人にはあまり興味がないであろう文字なので、そこまで特別扱いしなくて、「特殊なスペース」で対応できれば十分じゃないかと言う立場です（あとは設定項目を増やしたくないという欲望と...）。4.はイマイチそうですね。

その他のスペースはUnicodeの括りで言うとこの辺ですね：

<img width="400" alt="Screen Shot 2020-04-26 at 13 04 27" src="https://user-images.githubusercontent.com/1165044/80297604-8fd7a880-87bf-11ea-8968-2a2481cd3133.png">

全角スペースとno-break以外は、1本線とか2本線で幅がわかるように表示できれば十分かなと考えています。
ゼロ幅のものは描画しない予定です（例外的にU+200Bは現状「その他の不可視文字」で表示されているので。これを「特別なスペース」側に持っていくのはありうるかもしれません）。

**Comment by wanik** [comment]
全角スペースの扱いですが、何を区別し、何を括るかは、設計やニーズ把握にもよるかと思います。絶対的な基準もないかと思い、ご一任いたしますので、よろしくお願いいたします。

ZERO WIDTH SPACE U+200B につきましては、引き続き表示できたほうがありがたいです。
（いちおう「SPACE」という名を持っていますので、「特殊なスペース」に含めて可視化できたほうがよいかと...）

**Comment by wanik** [comment]
少し話が広がってしまって別件になりそうですが、ちょっと追加をお願いしてみます。
スペース類とはちょっと異なりますが、以下も「その他の制御記号」扱いか何かで可視化できると助かります。

- ZERO WIDTH NON-JOINER U+200C
- ZERO WIDTH JOINER U+200D
- LEFT-TO-RIGHT MARK U+200E
- RIGHT-TO-LEFT MARK U+200F
