### ISSUE TITLE
Character count not working for multiple selection

### ISSUE THREAD

**Issue by mu373** [coteditor/CotEditor#978]
## Environment

- CotEditor: 3.7.8 (360)
- System: macOS Version 10.14.5 (Build 18F203)
- Language: English

## Short Description
When multiple words/sentences are selected with `command` key, the character/word count are not updated. (Should be 8 character for this case?)

![image](https://user-images.githubusercontent.com/2176670/61625526-f3bfc480-acb5-11e9-8584-0a17dce30f6f.png)

## Steps to Reproduce the Issue
Select words/sentences with `command` key

## Expected Result
Although I'm not sure if this behavior is as expected, I thought that it is more natural to count all the text selected.

**Comment by 1024jp** [comment]
Hmm, this is in spec currently.

Well, I can change this (though the calculation cost increases), but I'm not sure which implementation makes more sense for most of the users:

1. Display only the count of the first selection.
2. Display the total count of all selections.

I suppose this is just preference, and the current implementation is enough...

**Comment by 1024jp** [comment]
Sorry for taking a long time.
But in the next version, CotEditor 4.5.0, the characters/lines/words count will display the total count of all selections.

**Comment by mu373** [comment]
Thank you for implementing this. I really appreciate your continuous effort in developing the application, even addressing such feature request from the past!
