### ISSUE TITLE
検索結果の表示がおかしい（合字になってる？）

### ISSUE THREAD

**Issue by edktsnr** [coteditor/CotEditor#980]
1◯などの検索結果が1○と表示されてしまいます
![スクリーンショット 2019-08-08 23 53 27](https://user-images.githubusercontent.com/1954547/62714104-e4bc6e80-ba38-11e9-9797-f93e416db005.png)

検索結果だけではなくCotEditorからコピー＆ペーストでも起きますね……

**Comment by 1024jp** [comment]
頂いた不具合、手元の環境で再現ができませんでした。
@edktsnr さんの環境下で再現できるテキストファイルおよびOSなどのバージョンを教えていだけますか？

<img width="809" alt="Screen Shot 2019-08-11 at 8 22 38 AM" src="https://user-images.githubusercontent.com/1165044/62830561-122d3600-bc4c-11e9-872c-8edfb8763975.png">

**Comment by edktsnr** [comment]
私も他のバージョンで試したら起きませんでした。
この現象が起こるバージョンは10.12.6です。
私の環境固有なのかもしれませんね。

![スクリーンショット 2019-08-18 4 33 58](https://user-images.githubusercontent.com/1954547/63216536-79c61280-c171-11e9-8e94-56e665cf7558.png)

上のキャプチャのようにテキストエディタからここにペーストしても丸数字になってしまいます……
『1○2○3○4○5○』（ペーストした文字列がこれです）

**Comment by 1024jp** [comment]
本件、申し訳ないのですが対応する前にCotEditor自体がmacOS 10.12を切ってしまったのでwontfixとさせて下さい💦。
10.13以降では正常に動くことを確認しています。
