### ISSUE TITLE
カーソル移動で、期待通りの範囲選択が行われない / Cursor move causes to unexpected range selection

### ISSUE THREAD

**Issue by takasek** [coteditor/CotEditor#983]
## Environment (環境)

- CotEditor: 3.7.8 (360)
- System: macOS バージョン10.15（ビルド19A546d）
- Language: Japanese

## Short Description (簡単な説明)

After `Shift + Option + →` , `Shift + ←` causes unexpected range selection.

## Steps to Reproduce the Issue (不具合が発生したときに行っていた操作、または再現手順)

1. type abcd
2. place cursor between `b` and `c` 
    - ab|cd
3. input `Shift + Option + →`
    - ab**cd**|
3. input `Shift + ←` 
    - a**bcd**|

## Expected Result (期待される挙動)

- ab**c**|d

**Comment by 1024jp** [comment]
ref. #979

**Comment by 1024jp** [comment]
Close as duplicate of #979 。
