### ISSUE TITLE
カラーピッカーで不透明度の調整ができない(Can't change opacity)

### ISSUE THREAD

**Issue by picomatzh** [coteditor/CotEditor#984]
テーマの色を変更しようとしたところ、不透明度調整スライダーが表示されません。
他のアプリでは不透明度調整スライダーが表示されているので、CotEditorの不具合と思われます。
<img width="499" alt="ss01" src="https://user-images.githubusercontent.com/53472137/64460965-c8464b80-d136-11e9-8910-9f9795a9810c.png">

**Comment by 1024jp** [comment]
仕様です。
CotEditorのテーマは不透明度に対応していません。
