### ISSUE TITLE
About <br />

### ISSUE THREAD

**Issue by wwwayneee** [coteditor/CotEditor#985]
whenever entering a new line there occurs <br /> no matter which type of text is being edited and there's no way to turn off the auto-<br />

**Comment by 1024jp** [comment]
This is the presetting of the snippet feature. If you press the Return key with the Shift key, that snippet is triggered. Try not to press Shift key when you type enter, or remove the default setting for Return+Shift keybinding combination.

<img width="672" alt="Screen Shot 2019-10-18 at 10 30 27" src="https://user-images.githubusercontent.com/1165044/67059045-68f64500-f192-11e9-97fa-28771ce88fae.png">
