### ISSUE TITLE
Freeze when editing bracket on 3.8.0 / 3.8.0でブラケット記号を編集するとフリーズする。

### ISSUE THREAD

**Issue by toku-mac** [coteditor/CotEditor#991]
ブラケット記号 [] の入力、削除を行うとレインボーカーソルになりフリーズすることがあります。macOS 10.14.6です。

**Comment by 1024jp** [comment]
報告ありがとうございます。
OSのバージョンと、できたら確実に再現できる手順を教えていただけると幸いです。
また、クラッシュログがある場合はいただきたいです。

**Comment by 1024jp** [comment]
先ほどリリースされたCotEditor 3.8.1で対策を盛り込みました。
該当箇所はすべて潰したつもりですが、漏れがあったらおしらせください。
