### ISSUE TITLE
Crash CotEditor 3.8.0 on macOS 10.14

### ISSUE THREAD

**Issue by bstyleYamakawa** [coteditor/CotEditor#992]
Application Specific Information:
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[NSBigMutableString characterAtIndex:]: Index 296 out of bounds; string length 296'
terminating with uncaught exception of type NSException
abort() called

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff309392fd __exceptionPreprocess + 256
1   libobjc.A.dylib                     0x00007fff5b02fa17 objc_exception_throw + 48
2   CoreFoundation                      0x00007fff3093912f +[NSException raise:format:] + 201
3   Foundation                          0x00007fff32b58c21 -[NSBigMutableString characterAtIndex:] + 100
4   libswiftCore.dylib                  0x00007fff5c174bd3 $ss11_StringGutsV34foreignErrorCorrectedUTF16CodeUnit2ats6UInt16VSS5IndexV_tFTf4nx_n + 51
5   libswiftCore.dylib                  0x00007fff5c174c7e $ss11_StringGutsV18foreignScalarAlignySS5IndexVAEFTf4nx_n + 14
6   libswiftCore.dylib                  0x00007fff5c0f2069 $ss11_StringGutsV18foreignScalarAlignySS5IndexVAEF + 9
7   CotEditor                           0x0000000107939507 CotEditor + 746759

**Comment by bstyleYamakawa** [comment]
OSを10.15にアップデートすれば解消しました

**Comment by bthalmayr** [comment]
Thanks for this great tool. Unfortunately CotEditor 3.8.0 crashes on my Mac OS 10.14.6

**Comment by 1024jp** [comment]
Please, somebody, give me a procedure to reproduce this crash.
I recognize there is a bug on CotEditor 3.8.0 (only with macOS 10.14?) but cannot reproduce it yet.

**Comment by bstyleYamakawa** [comment]
On MacOS 10.14
Updated to 3.8.0 with unsaved files remaining.

It will crash when trying to start

It was solved by updating MacOS to 10.15.

**Comment by bthalmayr** [comment]
Hi @1024jp , before upgrading to CotEditor 3.8.0, I had several files opened. CotEditor 3.8.0 crashes when starting, potentially because it tries to open the previous files. Even when I right-click on the CotEditor icon in the dock and only select to open one file of the list it crashes immediately after start. I'm a bit reluctant to upgrade to Mac OS 10.15 at the moment.

**Comment by 1024jp** [comment]
Thank you for the feedback.

I revealed that this is a bug in the latest Apple's Foundation causing only under macOS 10.14 (and 10.13?) and in release build.
I don't understand why Apple (and other developers) missed this bug. This is a serious one.

Anyway, I've just released CotEditor 3.8.1 addressing fixing this crash/freeze.
If you still have this kind of issue with the new version, please let me know.

**Comment by 1024jp** [comment]
@bthalmayr Thank you for your confirmation. I'm glad to hear that.
