### ISSUE TITLE
入力中のクラッシュ

### ISSUE THREAD

**Issue by fvrtedit** [coteditor/CotEditor#994]
C++ コードの記入中、例えばmain() {    <- この後記入が出来なくなり、そのままフリーズする。
一度、再インストールして、記入を再開することができたが、また同じ挙動でフリーズしたため、
報告します。
MacOS v10.14.6

**Comment by 1024jp** [comment]
報告ありがとうございます。
#991 と内容は重複するためこのIssueはクローズしますが、情報大変助かります。
