### ISSUE TITLE
How can I format JSON to pretty JSON?

### ISSUE THREAD

**Issue by huseyinmetin** [coteditor/CotEditor#995]
I didn't find extension or script.  How can I format json?

**Comment by 1024jp** [comment]
There is no specific command for that in CotEditor.
But you can use the Scripting feature for that purpose.
See the bundled manual for scripting in CotEditor for details.

<img width="670" alt="Screen Shot 2019-10-18 at 10 14 06" src="https://user-images.githubusercontent.com/1165044/67058505-1451ca80-f190-11e9-8552-8cbdd39d0c36.png">
